### ISSUE TITLE
CONDA_PY not transferring to test time correctly

### ISSUE THREAD

**Issue by Korijn** [conda/conda-build#1028]
~~Since last night the CONDA_PY env var is no longer adhered to by conda-build on our AppVeyor builds. We have to specify it manually on the command line now. We think it has something to do with the release of conda 4.1.0.~~

See [my comment below for a more accurate description](https://github.com/conda/conda-build/issues/1028#issuecomment-226399250).

**Comment by msarahan** [comment]
CC @kalefranz

**Comment by msarahan** [comment]
@Korijn having a hard time reproducing this:

```
((MC34x64)) Z:\msarahan\code\staged-recipes\recipes>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.0
  conda-build version : 1.21.0+0.g40e7abb.dirty
       python version : 3.4.3.final.0
     requests version : 2.10.0
     root environment : c:\MC34x64  (writable)
  default environment : c:\MC34x64
     envs directories : c:\MC34x64\envs
        package cache : c:\MC34x64\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
                        https://conda.anaconda.org/conda-forge/win-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://conda.anaconda.org/msys2/win-64/
                        https://conda.anaconda.org/msys2/noarch/
                        http://repo.continuum.io/pkgs/msys2/win-64/
                        http://repo.continuum.io/pkgs/msys2/noarch/
          config file : C:\Users\builder\.condarc
    is foreign system : False


((MC34x64)) Z:\msarahan\code\staged-recipes\recipes>set CONDA_PY=27 && conda build menuinst
Removing old build environment
BUILD START: menuinst-1.4.0-py27_0
Fetching package metadata .................Traceback (most recent call last):
  File "c:\MC34x64\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "z:\msarahan\code\conda-build\conda_build\main_build.py", line 140, in main
    args_func(args, p)
  File "z:\msarahan\code\conda-build\conda_build\main_build.py", line 380, in args_func
    args.func(args, p)
  File "z:\msarahan\code\conda-build\conda_build\main_build.py", line 327, in execute
    dirty=args.dirty)
  File "z:\msarahan\code\conda-build\conda_build\build.py", line 469, in build
    [ms.spec for ms in m.ms_depends('build')])
  File "z:\msarahan\code\conda-build\conda_build\build.py", line 358, in create_env
    index = get_build_index(clear_cache=True)
  File "z:\msarahan\code\conda-build\conda_build\build.py", line 341, in get_build_index
    prepend=not override_channels)
  File "c:\MC34x64\lib\site-packages\conda\api.py", line 26, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "c:\MC34x64\lib\site-packages\conda\fetch.py", line 281, in fetch_index
    repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
  File "c:\MC34x64\lib\site-packages\conda\fetch.py", line 281, in <listcomp>
    repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
  File "c:\MC34x64\lib\concurrent\futures\_base.py", line 397, in result
    self._condition.wait(timeout)
  File "c:\MC34x64\lib\threading.py", line 290, in wait
    waiter.acquire()
KeyboardInterrupt

((MC34x64)) Z:\msarahan\code\staged-recipes\recipes>set CONDA_PY=35 && conda build menuinst
Removing old build environment
BUILD START: menuinst-1.4.0-py35_0
Fetching package metadata .................Traceback (most recent call last):
  File "c:\MC34x64\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "z:\msarahan\code\conda-build\conda_build\main_build.py", line 140, in main
    args_func(args, p)
  File "z:\msarahan\code\conda-build\conda_build\main_build.py", line 380, in args_func
    args.func(args, p)
  File "z:\msarahan\code\conda-build\conda_build\main_build.py", line 327, in execute
    dirty=args.dirty)
  File "z:\msarahan\code\conda-build\conda_build\build.py", line 469, in build
    [ms.spec for ms in m.ms_depends('build')])
  File "z:\msarahan\code\conda-build\conda_build\build.py", line 358, in create_env
    index = get_build_index(clear_cache=True)
  File "z:\msarahan\code\conda-build\conda_build\build.py", line 341, in get_build_index
    prepend=not override_channels)
  File "c:\MC34x64\lib\site-packages\conda\api.py", line 26, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "c:\MC34x64\lib\site-packages\conda\fetch.py", line 281, in fetch_index
    repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
  File "c:\MC34x64\lib\site-packages\conda\fetch.py", line 281, in <listcomp>
    repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
  File "c:\MC34x64\lib\concurrent\futures\_base.py", line 397, in result
    self._condition.wait(timeout)
  File "c:\MC34x64\lib\threading.py", line 290, in wait
    waiter.acquire()
KeyboardInterrupt

((MC34x64)) Z:\msarahan\code\staged-recipes\recipes>set CONDA_PY=27

((MC34x64)) Z:\msarahan\code\staged-recipes\recipes>conda build menuinst
Removing old build environment
BUILD START: menuinst-1.4.0-py27_0
Fetching package metadata .................Traceback (most recent call last):
  File "c:\MC34x64\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "z:\msarahan\code\conda-build\conda_build\main_build.py", line 140, in main
    args_func(args, p)
  File "z:\msarahan\code\conda-build\conda_build\main_build.py", line 380, in args_func
    args.func(args, p)
  File "z:\msarahan\code\conda-build\conda_build\main_build.py", line 327, in execute
    dirty=args.dirty)
  File "z:\msarahan\code\conda-build\conda_build\build.py", line 469, in build
    [ms.spec for ms in m.ms_depends('build')])
  File "z:\msarahan\code\conda-build\conda_build\build.py", line 358, in create_env
    index = get_build_index(clear_cache=True)
  File "z:\msarahan\code\conda-build\conda_build\build.py", line 341, in get_build_index
    prepend=not override_channels)
  File "c:\MC34x64\lib\site-packages\conda\api.py", line 26, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "c:\MC34x64\lib\site-packages\conda\fetch.py", line 281, in fetch_index
    repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
  File "c:\MC34x64\lib\site-packages\conda\fetch.py", line 281, in <listcomp>
    repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
  File "c:\MC34x64\lib\concurrent\futures\_base.py", line 397, in result
    self._condition.wait(timeout)
  File "c:\MC34x64\lib\threading.py", line 290, in wait
    waiter.acquire()
KeyboardInterrupt
```

Can you point me to an appveyor build log?

**Comment by Korijn** [comment]
Thanks for getting back to me so quickly @msarahan. I've spent some time building a minimal reproduction, please see here: https://github.com/Korijn/condabug

It looks like the `CONDA_PY` environment variable or alternatively the `--python` argument are picked up after all, but result in awkward behavior together with `noarch_python: True`.

In the minimal reproduction sample, `conda build .\conda_recipe --py 27` builds 3.5 egg, and subsequently fails on python 2 syntax in the `pyqt` dependency. Something's being mixed up internally there.

**Comment by msarahan** [comment]
Thanks for the excellent example.  I will look into this.

**Comment by msarahan** [comment]
I think the responsible code is at https://github.com/conda/conda-build/blame/master/conda_build/metadata.py#L473-L474

@ilanschnell - since you wrote this code, can you please comment on why this particular part is necessary?  I'm inclined to just remove those 2 lines, but would appreciate your input here.

**Comment by Korijn** [comment]
Any progress on this?

**Comment by msarahan** [comment]
No, sorry. I have this lumped together with improving noarch in general. I
will fix that, but there are a few higher priority issues. I did try simply
removing the problem code I pointed out, but that broke things even worse.

**Comment by Korijn** [comment]
No worries, thanks for the update!

**Comment by carlodri** [comment]
Don't know if it's of any use, but I think this is the problem surfacing here on AppVeyor: https://ci.appveyor.com/project/conda-forge/pywin32-feedstock/build/1.0.18/job/dyhbqy8haekbvuhj from https://github.com/conda-forge/pywin32-feedstock/pull/9/

The relevant tests being executed (which fail for wrong `CONDA_PY`) are here: https://github.com/conda-forge/pywin32-feedstock/blob/c58e9a62e9a97896c515c1ae54e3bbb05736d956/recipe/meta.yaml

**Comment by msarahan** [comment]
What's happening is that the variant appears to no longer be defined at test time - only what is present in the package's collection of what is a "used variable" - which python never is, because it is special-cased as part of the build string.  Once that is lost, it falls back to the python version that is running conda-build: https://github.com/conda/conda-build/blob/master/conda_build/variants.py#L22

That's 3.6 for you, and that's why it appears to be losing its mind.  It would be better to try at least one more fallback path to detect if Python is installed, and to use the appropriate version found there, then finally fall back to the default.
