### ISSUE TITLE
hg clone error

### ISSUE THREAD

**Issue by looooo** [conda/conda-build#1033]
I tried to create a conda-build for [coin](https://bitbucket.org/Coin3D/coin/wiki/Home).The recipe can be found [here](https://github.com/looooo/FreeCAD_Conda/blob/master/coin/meta.yaml)

```
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/lo/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/home/lo/anaconda/lib/python3.5/site-packages/conda_build/main_build.py", line 140, in main
    args_func(args, p)
  File "/home/lo/anaconda/lib/python3.5/site-packages/conda_build/main_build.py", line 380, in args_func
    args.func(args, p)
  File "/home/lo/anaconda/lib/python3.5/site-packages/conda_build/main_build.py", line 327, in execute
    dirty=args.dirty)
  File "/home/lo/anaconda/lib/python3.5/site-packages/conda_build/build.py", line 487, in build
    assert not need_source_download, "Source download failed.  Please investigate."
AssertionError: Source download failed.  Please investigate.
```
- conda info

```
platform : linux-64
conda version : 4.1.0
conda-build version : 1.21.0
python version : 3.5.1.final.0
requests version : 2.10.0
```

**Comment by looooo** [comment]
not a conda issue

**Comment by looooo** [comment]
this is the error:

```
checkout: 'CMake'
Aktualisiere auf Zweig default
Abbruch: Projektarchiv ~/anaconda/conda-bld/hg_cache/generalmsvcgeneration nicht gefunden!
```

I don't understand what conda does in this step. conda first checkout the CMake branch and then reloads the default branch????

**Comment by msarahan** [comment]
What does your recipe (meta.yaml) look like?

If you do not specify hg_tag, but instead define that in your url, then this might happen.  Guilty code at https://github.com/conda/conda-build/blob/master/conda_build/source.py#L231

I don't use hg much, so I'd appreciate your perspective on the way things *should* be.

**Comment by looooo** [comment]
see the commented lines: https://github.com/looooo/FreeCAD_Conda/blob/master/coin/meta.yaml#L14

**Comment by msarahan** [comment]
The problem appears to be handling of submodules.  We'll try to figure this out, but if you know commands that we should add to https://github.com/conda/conda-build/blob/master/conda_build/source.py#L206-L241, it would help us fix things sooner.

**Comment by looooo** [comment]
I have no idea! Manually running a subprocess cloning the repo with hg does work for me. But with conda it doesn't work. I am testing with these function: (I have manually cleared the hg_cache-dir before running "conda build").

```python
def hg_source(meta, verbose=False):
    ''' Download a source from Mercurial repo. '''
    if verbose:
        stdout = None
        stderr = None
    else:
        FNULL = open(os.devnull, 'w')
        stdout = FNULL
        stderr = FNULL

    hg = external.find_executable('hg')
    if not hg:
        sys.exit('Error: hg not installed')
    hg_url = meta['hg_url']
    if not isdir(HG_CACHE):
        os.makedirs(HG_CACHE)
    hg_dn = hg_url.split(':')[-1].replace('/', '_')
    cache_repo = join(HG_CACHE, hg_dn)
    # if isdir(cache_repo):
    #     check_call([hg, 'pull'], cwd=cache_repo, stdout=stdout, stderr=stderr)
    # else:
    check_call([hg, 'clone', hg_url, cache_repo], stdout=stdout, stderr=stderr)
    # assert isdir(cache_repo)

    # # now clone in to work directory
    # update = meta.get('hg_tag') or 'tip'
    # if verbose:
    #     print('checkout: %r' % update)

    # check_call([hg, 'clone', cache_repo, WORK_DIR], stdout=stdout, stderr=stderr)
    # check_call([hg, 'update', '-C', update], cwd=WORK_DIR, stdout=stdout, stderr=stderr)

    # if not verbose:
    #     FNULL.close()

    # return WORK_DIR
```

```python
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was: 
Command '['/usr/bin/hg', 'clone', 'https://bitbucket.org/Coin3D/coin', ~/anaconda/conda-bld/hg_cache/__bitbucket.org_Coin3D_coin']' returned non-zero exit status 255
```

This seems to be something different now?
