### ISSUE TITLE
bad "deactivate" on Windows

### ISSUE THREAD

**Issue by janssen** [conda/conda-build#1034]
Trying to build matplotlib, I get this.  Including "conda info" output as requested.

```
Traceback (most recent call last):
  File "C:\Users\wjanssen\AppData\Local\Continuum\Miniconda2\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\wjanssen\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda_build\main_build.py", line 140, in main
    args_func(args, p)
  File "C:\Users\wjanssen\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda_build\main_build.py", line 380, in args_func
    args.func(args, p)
  File "C:\Users\wjanssen\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda_build\main_build.py", line 327, in execute
    dirty=args.dirty)
  File "C:\Users\wjanssen\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda_build\build.py", line 558, in build
    deactivate_env()
  File "C:\Users\wjanssen\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda_build\environ.py", line 440, in deactivate_env
    return activate_or_deactivate_env("deactivate")
  File "C:\Users\wjanssen\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda_build\environ.py", line 426, in activate_or_deactivate_env
    vars = subprocess.check_output(cmd).replace("\r\n", "\n")
  File "C:\Users\wjanssen\AppData\Local\Continuum\Miniconda2\lib\subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '"C:\Users\wjanssen\AppData\Local\Continuum\Miniconda2\Scripts\deactivate.bat" "" && set' returned non-zero exit status 255
$ conda info
Current conda install:

             platform : win-64
        conda version : 4.1.1
  conda-build version : 1.21.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Users\wjanssen\AppData\Local\Continuum\Miniconda2  (writable)
  default environment : C:\Users\wjanssen\AppData\Local\Continuum\Miniconda2
     envs directories : C:\Users\wjanssen\AppData\Local\Continuum\Miniconda2\envs
        package cache : C:\Users\wjanssen\AppData\Local\Continuum\Miniconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by msarahan** [comment]
Fixed by #1044 - please update to conda-build 1.21.1 (should be available shortly) and try again.
