### ISSUE TITLE
conda install from tarball appears to modify pkg path

### ISSUE THREAD

**Issue by ijstokes** [conda/conda-build#1053]
Note the path of the tarball I'm trying to install:
* ` /opt/wakari/anaconda/conda-bld/linux-64/wakari-server-1.10.9-GIT_STUB.tar.bz2`

Now note the path reported at the end of the stack trace:
* `/opt/wakari/miniconda/pkgs/wakari-server-1.10.9-GIT_STUB.tar.bz2`

It looks like something unexpected to me.

```
$ /opt/wakari/miniconda/bin/conda install -p /opt/wakari/wakari-server/ /opt/wakari/anaconda/conda-bld/linux-64/wakari-server-1.10.9-GIT_STUB.tar.bz2
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/wakari/miniconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 202, in install
    verbose=not args.quiet)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/misc.py", line 258, in install_local_packages
    shutil.copyfile(src_path, dst_path)
  File "/opt/wakari/miniconda/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/opt/wakari/miniconda/pkgs/wakari-server-1.10.9-GIT_STUB.tar.bz2'
```

**Comment by msarahan** [comment]
yes, this is related to #1051 I think - conda-build has some bizarre behavior where the package being tested only provides metadata - and perhaps is copied into the pkgs folder, but ultimately, any install happens from the pkgs folder.

Closing this to consolidate discussion at #1051 - reopen if they do not look related to you.
