### ISSUE TITLE
MacOS: convert paths in executables to relative paths

### ISSUE THREAD

**Issue by btel** [conda/conda-build#106]
I have been trying to make a conda package of a library that contains some executables. The build fails on relocation:

```
Traceback (most recent call last):
  File "//anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "//anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 77, in main
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 198, in execute
    build.build(m)
  File "//anaconda/lib/python2.7/site-packages/conda_build/build.py", line 281, in build
    binary_relocation=bool(m.get_value('build/binary_relocation', True)))
  File "//anaconda/lib/python2.7/site-packages/conda_build/post.py", line 195, in post_build
    mk_relative(f, binary_relocation=binary_relocation)
  File "//anaconda/lib/python2.7/site-packages/conda_build/post.py", line 176, in mk_relative
    mk_relative_osx(path)
  File "//anaconda/lib/python2.7/site-packages/conda_build/post.py", line 158, in mk_relative_osx
    assert not name.startswith(build_prefix), path
AssertionError: //anaconda/envs/_build/bin/ivoc
```

When I run `file` on the `ivoc` I get:

```
//anaconda/envs/_build/bin/ivoc: Mach-O 64-bit executable x86_64
```

`otool -L` returns:

```
    //anaconda/envs/_build/x86_64/lib/libocxt.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    //anaconda/envs/_build/x86_64/lib/libivoc.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    //anaconda/envs/_build/x86_64/lib/libnrnmpi.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    //anaconda/envs/_build/x86_64/lib/liboc.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    //anaconda/envs/_build/x86_64/lib/libmemacs.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    //anaconda/envs/_build/x86_64/lib/libmeschach.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    //anaconda/envs/_build/x86_64/lib/libneuron_gnu.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    //anaconda/envs/_build/x86_64/lib/libivos.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    /opt/X11/lib/libX11.6.dylib (compatibility version 10.0.0, current version 10.0.0)
    /usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
    /usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
    /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 56.0.0)
    /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1669.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
```

I suppose the problem is in this line of `conda_build/post.py`

```
    if path.endswith('.dylib'):
        # note that not every MachO binaries is a "dynamically linked shared
        # library" which have an identification name, a .so C extensions
        # extensions is a "bundle".  One can verify this using the "file"
        # command.
        names = macho.otool(path)
```

**Comment by msarahan** [comment]
I believe this is long since sorted.  Current OSX builds user RPATH.
