### ISSUE TITLE
KeyError: 'installationfolder'

### ISSUE THREAD

**Issue by agmills7** [conda/conda-build#1063]
Include the output of the command 'conda info' in your report:
 $ conda info
Current conda install:

             platform : win-64
        conda version : 4.1.3
    conda-env version : 2.5.1
  conda-build version : 1.21.2
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Users\Anthony\Anaconda3  (writable)
  default environment : C:\Users\Anthony\Anaconda3
     envs directories : C:\Users\Anthony\Anaconda3\envs
        package cache : C:\Users\Anthony\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

Traceback (most recent call last):
  File "C:\Users\Anthony\Anaconda3\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda_build\main_build.py", line 144, in main
    args_func(args, p)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda_build\main_build.py", line 389, in args_func
    args.func(args, p)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda_build\main_build.py", line 332, in execute
    dirty=args.dirty, activate=args.activate)
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda_build\build.py", line 563, in build
    import conda_build.windows as windows
  File "C:\Users\Anthony\Anaconda3\Lib\site-packages\conda_build\windows.py", line 30, in <module>
    'installationfolder')
  File "C:\Users\Anthony\Anaconda3\envs\my-rdkit-env\Lib\distutils\msvc9compiler.py", line 70, in get_value
    raise KeyError(key)
KeyError: 'installationfolder'

**Comment by msarahan** [comment]
This is fixed in conda-build 1.21.3, which should be available now.  Please update and try again.  Closing - but happy to reopen if you still have issues.
