### ISSUE TITLE
conda skeleton pypi cf-python gives Unicode error u'\u2122' or  u'\xb5'

### ISSUE THREAD

**Issue by ajheaps** [conda/conda-build#1091]
I didn't want to jump into issue #1089 in case this is an entirely unrelated issue.

I have updated conda with 
conda uopdate conda

and I'm trying to create a new Conda release for cf-python from pypi. The conda skeleton for this package has woked in the past but now I get a Uncode error:

conda skeleton pypi cf-python
Traceback (most recent call last):
  File "/panfs/jasmin/users/andy/anaconda2/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/panfs/jasmin/users/andy/anaconda2/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 300, in main
    args_func(args, p)
  File "/panfs/jasmin/users/andy/anaconda2/lib/python2.7/site-packages/conda_build/main_build.py", line 389, in args_func
    args.func(args, p)
  File "/panfs/jasmin/users/andy/anaconda2/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 315, in execute
    pypi.main(args, parser)
  File "/panfs/jasmin/users/andy/anaconda2/lib/python2.7/site-packages/conda_build/pypi.py", line 263, in main
    all_packages = [match["name"] for match in client.search({"name": args.packages}, "or")]
  File "/panfs/jasmin/users/andy/anaconda2/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/panfs/jasmin/users/andy/anaconda2/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/panfs/jasmin/users/andy/anaconda2/lib/python2.7/site-packages/conda_build/pypi.py", line 233, in request
    return self.parse_response(resp)
  File "/panfs/jasmin/users/andy/anaconda2/lib/python2.7/site-packages/conda_build/pypi.py", line 240, in parse_response
    p.feed(resp.text)
  File "/panfs/jasmin/users/andy/anaconda2/lib/python2.7/xmlrpclib.py", line 558, in feed
    self._parser.Parse(data, 0)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2122' in position 697992: ordinal not in range(128)

Sometimes the error given is 
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb5' in position 292891: ordinal not in range(128)

conda info gives:
Current conda install:

             platform : linux-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 2.7.12.final.0
     requests version : 2.9.1
     root environment : /panfs/jasmin/users/andy/anaconda2  (writable)
  default environment : /panfs/jasmin/users/andy/anaconda2
     envs directories : /panfs/jasmin/users/andy/anaconda2/envs
        package cache : /panfs/jasmin/users/andy/anaconda2/pkgs
         channel URLs : https://conda.anaconda.org/r/linux-64/
                        https://conda.anaconda.org/r/noarch/
                        https://conda.anaconda.org/ska/linux-64/
                        https://conda.anaconda.org/ska/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/swsheaps/.condarc
         offline mode : False
    is foreign system : False

Have I corrupted something locally or is this a central conda issue?

Thanks
Andy

**Comment by msarahan** [comment]
Fixed by #1092
