### ISSUE TITLE
conda skeleton crashes on Ubuntu 14.04

### ISSUE THREAD

**Issue by r-handsfield** [conda/conda-build#1094]
Skeleton fails when searching pypi repositories.

> conda skeleton pypi wikipedia

Stack trace:
Traceback (most recent call last):
  File "/home/qq/Applications/anaconda/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/home/qq/Applications/anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 300, in main
    args_func(args, p)
  File "/home/qq/Applications/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 389, in args_func
    args.func(args, p)
  File "/home/qq/Applications/anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 315, in execute
    pypi.main(args, parser)
  File "/home/qq/Applications/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 263, in main
    all_packages = [match["name"] for match in client.search({"name": args.packages}, "or")]
  File "/home/qq/Applications/anaconda/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/home/qq/Applications/anaconda/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/home/qq/Applications/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 233, in request
    return self.parse_response(resp)
  File "/home/qq/Applications/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 242, in parse_response
    return u.close()
  File "/home/qq/Applications/anaconda/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault -32500: 'application error'>

Current conda install:
             platform : linux-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.4
       python version : 2.7.12.final.0
     requests version : 2.9.1
     root environment : /home/qq/Applications/anaconda  (writable)
  default environment : /home/qq/Applications/anaconda
     envs directories : /home/qq/Applications/anaconda/envs
        package cache : /home/qq/Applications/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by msarahan** [comment]
Thanks for the report. I'll investigate this soon. Nothing obvious jumps out at me from the traceback. I'll try to reproduce, but may need your help.

**Comment by msarahan** [comment]
Of course, this doesn't happen for me.  Is it a repeatable error, or does it sometimes work?  Do you have any sort of firewall or proxy that may interfere?

**Comment by msarahan** [comment]
I ran into this, but it is intermittent.  This indicates that it is a PyPI error.  Nothing we can do about those, but I'll try to add a nicer error message, at least.

**Comment by msarahan** [comment]
Closing.  Better messaging added in #1098.  If you see this error more than once in a while, please raise an issue with the PyPI maintainers.  At some point, we'll migrate to using pypi.io, which might help some of these issues, if they have changed their systems to scale better.
