### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by daavoo** [conda/conda-build#1114]
```
Traceback (most recent call last):
  File "C:\Users\David de la Iglesia\Anaconda3\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\David de la Iglesia\Anaconda3\lib\site-packages\conda_build\main_build.py", line 144, in main
    args_func(args, p)
  File "C:\Users\David de la Iglesia\Anaconda3\lib\site-packages\conda_build\main_build.py", line 401, in args_func
    args.func(args, p)
  File "C:\Users\David de la Iglesia\Anaconda3\lib\site-packages\conda_build\main_build.py", line 344, in execute
    dirty=args.dirty, activate=args.activate)
  File "C:\Users\David de la Iglesia\Anaconda3\lib\site-packages\conda_build\build.py", line 620, in build
    include_recipe=bool(m.path) and include_recipe)
  File "C:\Users\David de la Iglesia\Anaconda3\lib\site-packages\conda_build\build.py", line 205, in create_info_files
    f.write("# " + source.get_repository_info(m.path) + "\n")
  File "C:\Users\David de la Iglesia\Anaconda3\lib\site-packages\conda_build\source.py", line 292, in get_repository_info
    origin = check_output(["git", "config", "--get", "remote.origin.url"], cwd=recipe_path)
  File "C:\Users\David de la Iglesia\Anaconda3\lib\subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "C:\Users\David de la Iglesia\Anaconda3\lib\subprocess.py", line 696, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\David de la Iglesia\Anaconda3\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "C:\Users\David de la Iglesia\Anaconda3\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
```

```

Current conda install:

             platform : win-64
        conda version : 4.1.8
    conda-env version : 2.5.2
  conda-build version : 1.21.5
       python version : 3.5.1.final.0
     requests version : 2.10.0
     root environment : C:\Users\David de la Iglesia\Anaconda3  (writable)
  default environment : C:\Users\David de la Iglesia\Anaconda3
     envs directories : C:\Users\David de la Iglesia\Anaconda3\envs
        package cache : C:\Users\David de la Iglesia\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : C:\Users\David de la Iglesia\.condarc
         offline mode : False
    is foreign system : False

```

**Comment by msarahan** [comment]
Sorry about this.  If you still have this issue with conda-build >=2.0.12, please reopen this issue, or open a new one.
