### ISSUE TITLE
conda skeleton needs to gracefully handle pypi versions that lack tarballs

### ISSUE THREAD

**Issue by novalis** [conda/conda-build#1139]
~:~$ conda skeleton pypi pyavl
Warning, the following versions were found for pyavl
1.12_1
1.12
Using 1.12
Use --version to specify a different version.
Using url http://sourceforge.net/projects/pyavl/ (0 B) for pyavl.
Downloading pyavl
Unpacking pyavl...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda-build/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/novalis/miniconda2/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/home/novalis/miniconda2/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 319, in main
    args_func(args, p)
  File "/home/novalis/miniconda2/lib/python2.7/site-packages/conda_build/main_build.py", line 401, in args_func
    args.func(args, p)
  File "/home/novalis/miniconda2/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 334, in execute
    pypi.main(args, parser)
  File "/home/novalis/miniconda2/lib/python2.7/site-packages/conda_build/pypi.py", line 352, in main
    get_package_metadata(args, package, d, data)
  File "/home/novalis/miniconda2/lib/python2.7/site-packages/conda_build/pypi.py", line 503, in get_package_metadata
    setup_options=args.setup_options)
  File "/home/novalis/miniconda2/lib/python2.7/site-packages/conda_build/pypi.py", line 757, in get_pkginfo
    unpack(join(SRC_CACHE, filename), tempdir)
  File "/home/novalis/miniconda2/lib/python2.7/site-packages/conda_build/pypi.py", line 691, in unpack
    raise Exception("not a valid source")
Exception: not a valid source
~:~$ conda info
Warning: somethings is wrong with binstar_client (No module named binstar_client.utils)Current conda install:

```
         platform : linux-64
    conda version : 4.1.9
conda-env version : 2.5.2
```

  conda-build version : 1.21.6
       python version : 2.7.12.final.0
     requests version : 2.9.1
     root environment : /home/novalis/miniconda2  (writable)
  default environment : /home/novalis/miniconda2
     envs directories : /home/novalis/miniconda2/envs
        package cache : /home/novalis/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
##     is foreign system : False
1. 1.12_1 is in fact later than 1.12
2. Conda should detect that the tarball is missing from 1.12 and provide a reasonable error message.

**Comment by msarahan** [comment]
That's a good idea.  There's some code that looks like it should be doing that at https://github.com/conda/conda-build/blob/master/conda_build/pypi.py#L406-L412 - but apparently isn't working, based on your report.

I have attempted to fix the version sorting and added a test.  I'm leaving this issue open until I have time to investigate the missing tarball handling.
