### ISSUE TITLE
pipbuild doesn't parse '==' in setup.py dependencies

### ISSUE THREAD

**Issue by ligfx** [conda/conda-build#114]
Hi all,

I'm trying to use `pipbuild` to install the package `yhat` from PyPI. I can build and install the package fine using combinations of `conda skeleton pypi` and `conda build`, and doing the same for the dependencies manually, but pipbuild doesn't work. It looks like pipbuild isn't parsing the version strings correctly:

```
~/Downloads » conda pipbuild yhat
Fetching package metadata: ..
Creating standard recipe for yhat-0.7.5
Converting recipe in /Users/michaelmaltese/Downloads/yhat
package = yhat
   dependences = [u'colorama ==0.2.5', u'progressbar ==2.2', u'flask ==0.10.1', u'websocket-client ==0.12.0', u'prettytable ==0.7.2', u'dill ==0.2b1']
Creating standard recipe for colorama-==0.2.5
Error: Version ==0.2.5 of colorama is not available on PyPI.

conda create -n _pipbuild_ --yes python pip
Error: prefix already exists: /opt/conda/envs/_pipbuild_
/opt/conda/envs/_pipbuild_/bin/pip install colorama====0.2.5
Exception:
Traceback (most recent call last):
  File "/opt/conda/envs/_pipbuild_/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/opt/conda/envs/_pipbuild_/lib/python2.7/site-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/opt/conda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/opt/conda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/opt/conda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/opt/conda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/opt/conda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'colorama====0.2.5', 'at', '====0.2.5')

Storing debug log for failure in /Users/michaelmaltese/.pip/pip.log
Traceback (most recent call last):
  File "/opt/conda/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 76, in main
    args.func(args, p)
  File "/opt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 347, in execute
    build_package(package, version)
  File "/opt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 310, in build_package
    build_package(depend)
  File "/opt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 300, in build_package
    directory, dependencies = make_recipe(package, version)
  File "/opt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 244, in make_recipe
    depends = get_all_dependencies(package, version)
  File "/opt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 216, in get_all_dependencies
    raise RuntimeError("Could not pip install %s==%s" % (package, version))
RuntimeError: Could not pip install colorama====0.2.5
```

I looked around Conda and conda-build for the problem, but I'm not familiar enough with the source to figure out what's happening. I'm on a Miniconda install on Mac OS X, with Conda 3.5.1 and conda-build 1.3.3.

**Comment by zonksoft** [comment]
I encountered the same problem with flask-mongoengine:
```
$ conda pipbuild flask-mongoengine
Fetching package metadata: ....
Creating standard recipe for flask-mongoengine-0.7.1
Converting recipe in /tmp/flask-mongoengine
package = flask-mongoengine
   dependencies = [u'flask >=0.8', u'mongoengine >=0.7.10', u'flask-wtf']
Creating standard recipe for mongoengine->=0.7.10
Error: directory already exists: ./mongoengine

conda create -n _pipbuild_ --yes python pip
Error: prefix already exists: /home/xx/anaconda/envs/_pipbuild_
/home/xx/anaconda/envs/_pipbuild_/bin/pip install mongoengine==>=0.7.10
Exception:
Traceback (most recent call last):
  File "/home/xx/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/xx/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/home/xx/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/home/xx/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/xx/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/home/xx/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/home/xx/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'mongoengine==>=0.7.10', 'at', '==>=0.7.10')

Storing debug log for failure in /tmp/tmpgMltUu
Error: Could not pip install mongoengine==>=0.7.10
```

**Comment by msarahan** [comment]
pipbuild no longer exists.  You need to do (at least) 2 steps now:

1. conda skeleton pypi (package name)
2. try building with ``conda build (package name)``
3. troubleshoot as necessary, or if it worked, great, go use your package
