### ISSUE TITLE
conda metapackage not working with conda build version 1.21.7

### ISSUE THREAD

**Issue by patanijo** [conda/conda-build#1158]
**Command**
conda metapackage my_package 1.0 -d pandas

** Conda Info Results**
Current conda install:

             platform : osx-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.7
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /Users/johnpatanian/anaconda  (writable)
  default environment : /Users/johnpatanian/anaconda
     envs directories : /Users/johnpatanian/anaconda/envs
        package cache : /Users/johnpatanian/anaconda/pkgs
         channel URLs : file:///Volumes/conda_repo/gepowerservices/osx-64/
                        file:///Volumes/conda_repo/gepowerservices/noarch/
                        file:///Volumes/conda_repo/osx-64/
                        file:///Volumes/conda_repo/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/r/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/r/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/johnpatanian/.condarc
         offline mode : False
    is foreign system : False

**Program Output**
Traceback (most recent call last):
  File "/Users/johnpatanian/anaconda/bin/conda-metapackage", line 5, in <module>
    sys.exit(main())
  File "/Users/johnpatanian/anaconda/lib/python2.7/site-packages/conda_build/main_metapackage.py", line 108, in main
    args_func(args, p)
  File "/Users/johnpatanian/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 408, in args_func
    args.func(args, p)
  File "/Users/johnpatanian/anaconda/lib/python2.7/site-packages/conda_build/main_metapackage.py", line 126, in execute
    build(m)
  File "/Users/johnpatanian/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 486, in build
    vcs_source = m.uses_vcs_in_build()
  File "/Users/johnpatanian/anaconda/lib/python2.7/site-packages/conda_build/metadata.py", line 758, in uses_vcs_in_build
    with open(self.meta_path) as f:
IOError: [Errno 2] No such file or directory: ''

**Comment by msarahan** [comment]
Thanks for the report.  I'll look into it as soon as possible.

**Comment by msarahan** [comment]
I have not been able to reproduce this with the test in #1160.  I'm closing this issue for now, but please reopen it or open a new issue if the problem recurs.
