### ISSUE TITLE
ValueError: Empty version string

### ISSUE THREAD

**Issue by pitrou** [conda/conda-build#1197]
```
Z:\numba>conda build --python=3.5 --numpy=1.11 buildscripts\condarecipe.local
Removing old build environment
BUILD START: numba-0.28.0.dev-np111py35_72
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
[...]
  File "C:\Miniconda3\lib\site-packages\conda\version.py", line 138, in __init__

    raise ValueError("Empty version string.")
ValueError: Empty version string.
```

**Comment by pitrou** [comment]
```
Z:\numba>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.11+0.g5b44ab3.dirty
       python version : 3.5.1.final.0
     requests version : 2.10.0
     root environment : C:\Miniconda3  (writable)
  default environment : C:\Miniconda3
     envs directories : C:\Miniconda3\envs
        package cache : C:\Miniconda3\pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/antoine/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/antoine/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/numba/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/numba/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : C:\Users\Antoine\.condarc
         offline mode : False
    is foreign system : False
```

**Comment by msarahan** [comment]
Thanks for the report.  I need more of a traceback.  That error ends in conda, somehow, so I'm less certain about where it is originating.  Almost certainly conda-build, but I don't know where in conda-build.

**Comment by pitrou** [comment]
Sorry, here is the full traceback:
```
Removing old build environment
BUILD START: numba-0.28.0.dev-np111py35_72
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Miniconda3\lib\site-packages\conda_build\main_build.py", line 152, in
 main
    args_func(args, p)
  File "C:\Miniconda3\lib\site-packages\conda_build\main_build.py", line 415, in
 args_func
    args.func(args, p)
  File "C:\Miniconda3\lib\site-packages\conda_build\main_build.py", line 358, in
 execute
    debug=args.debug)
  File "C:\Miniconda3\lib\site-packages\conda_build\build.py", line 530, in buil
d
    create_env(config.build_prefix, specs, debug=debug)
  File "C:\Miniconda3\lib\site-packages\conda_build\build.py", line 395, in crea
te_env
    actions = plan.install_actions(prefix, index, specs)
  File "C:\Miniconda3\lib\site-packages\conda\plan.py", line 466, in install_act
ions
    pkgs = r.install(specs, linked, update_deps=update_deps)
  File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 944, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 981, in solve
    dists, new_specs = self.get_dists(specs)
  File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 460, in get_dist
s
    specs, optional, features = self.verify_specs(specs)
  File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 451, in verify_s
pecs
    if not self.valid(ms, filter):
  File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 360, in valid
    return v_(spec)
  File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 348, in v_
    return v_ms_(spec) if isinstance(spec, MatchSpec) else v_fkey_(spec)
  File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 351, in v_ms_
    return ms.optional or any(v_fkey_(fkey) for fkey in self.find_matches(ms))
  File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 617, in find_mat
ches
    res = [p for p in res if self.match_fast(ms, p)]
  File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 617, in <listcom
p>
    res = [p for p in res if self.match_fast(ms, p)]
  File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 607, in match_fa
st
    return ms.match_fast(rec['version'], rec['build'])
  File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 170, in _match_v
ersion
    return self.version.match(version)
  File "C:\Miniconda3\lib\site-packages\conda\version.py", line 287, in veval_ma
tch_
    return self.op(VersionOrder(vspec), self.cmp)
  File "C:\Miniconda3\lib\site-packages\conda\version.py", line 138, in __init__

    raise ValueError("Empty version string.")
ValueError: Empty version string.
```

**Comment by msarahan** [comment]
Thanks.  That helps.  I'll have to debug further, though.  Is this on a particular branch of numba that I can clone and work with?

**Comment by pitrou** [comment]
Just the master branch.

**Comment by msarahan** [comment]
Sorry, I haven't been able to reproduce this with a seemingly identical  setup:

```
Z:\msarahan\code\numba>conda info
Current conda install:

               platform : win-64
          conda version : 4.1.6.dev1135+17e0e22
       conda is private : False
      conda-env version : 2.5.2
    conda-build version : 1.21.11+0.g5b44ab3.dirty
         python version : 2.7.11.final.0
       requests version : 2.9.1
       root environment : C:\MC2x64  (writable)
    default environment : C:\MC2x64
       envs directories : C:\MC2x64\envs
          package cache : C:\MC2x64\pkgs
           channel URLs : conda-forge
                          defaults
                          https://repo.continuum.io/pkgs/msys2
                          http://repo.continuum.io/pkgs/msys2
            config file : C:\Users\builder\.condarc
           offline mode : False


Z:\msarahan\code\numba>conda install conda
Fetching package metadata .............
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at C:\MC2x64:
#
conda                     4.1.11                   py27_1    conda-forge

Z:\msarahan\code\numba>cd ..\conda

Z:\msarahan\code\conda>python setup.py develop --uninstall
running develop
Removing c:\mc2x64\lib\site-packages\conda.egg-link (link to .)
Removing conda 4.1.6.dev1135+17e0e22 from easy-install.pth file
Note: you must uninstall or replace scripts manually!

Z:\msarahan\code\conda>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.11+0.g5b44ab3.dirty
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\MC2x64  (writable)
  default environment : C:\MC2x64
     envs directories : C:\MC2x64\envs
        package cache : C:\MC2x64\pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/conda-forge/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
                        http://repo.continuum.io/pkgs/msys2/win-64/
                        http://repo.continuum.io/pkgs/msys2/noarch/
          config file : C:\Users\builder\.condarc
         offline mode : False
    is foreign system : False


Z:\msarahan\code\conda>cd ..\numba

Z:\msarahan\code\numba>conda build buildscripts\condarecipe.local --numpy=1.11 -c numba --python=3.5
Removing old build environment
BUILD START: numba-0.26.0.dev-np111py35_186
(hide many warnings about failing to empty trash)
Using Anaconda Cloud api site https://api.anaconda.org

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    llvmlite-0.13.0.dev        |          py35_63         6.2 MB  numba
    numpy-1.11.1               |           py35_1         2.8 MB
    setuptools-23.0.0          |           py35_1         694 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         9.7 MB

The following NEW packages will be INSTALLED:

    certifi:        2016.8.2-py35_0    conda-forge
    llvmlite:       0.13.0.dev-py35_63 numba
    mkl:            11.3.3-1
    numpy:          1.11.1-py35_1
    pip:            8.1.2-py35_0       conda-forge
    python:         3.5.2-2            conda-forge
    setuptools:     23.0.0-py35_1      conda-forge
    vs2015_runtime: 14.0.25420-0       conda-forge
    wheel:          0.29.0-py35_0      conda-forge
    wincertstore:   0.2-py35_0         conda-forge
```

I note that my git tag for numba itself is different (0.26 vs 0.28) - but I have pulled from master, with the latest commit being:

```
commit 660e77784759fb15d91052dd532a022b74620a8b
Merge: 2ab828c ff96015
Author: Antoine Pitrou <pitrou@free.fr>
Date:   Thu Aug 11 22:09:50 2016 +0200

    Merge pull request #1996 from sklam/feature/foldlooplifting

    Rewrite looplifting as transformation on numba IR
```

Is there any more information you might be able to provide to help reproduce this?  Perhaps I can log into your build machine tomorrow and take a look?

**Comment by rolando** [comment]
I had this error and was gone after deleting the `$CONDA_ROOT/conda-bld`  directory.

**Comment by bp-kelley** [comment]
A newer version of this error is:
```  File "/usr/prog/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 134, in __init__
    self.groups[name] = sorted(group, key=self.version_key, reverse=True)
  File "/usr/prog/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 803, in version_key
    version_comparator = VersionOrder(prec.get('version', ''))
  File "/usr/prog/anaconda3/lib/python3.6/site-packages/conda/models/version.py", line 40, in __call__
    val = cls._cache_[arg] = super(SingleStrArgCachingType, cls).__call__(arg)
  File "/usr/prog/anaconda3/lib/python3.6/site-packages/conda/models/version.py", line 163, in __init__
    raise InvalidVersionSpec(vstr, "empty version string")
conda.exceptions.InvalidVersionSpec: Invalid version '': empty version string
```
As @rmax commented, deleting `$CONDA_ROOT/conda-bld` also solved my issue.
