### ISSUE TITLE
conda clean -a fails with conda build 2.0.0beta2

### ISSUE THREAD

**Issue by ericdill** [conda/conda-build#1249]
```
$ conda clean -a
Cache location: 
There are no tarballs to remove
Cache location: 
There are no unused packages to remove
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/eric/miniconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/eric/miniconda/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/eric/miniconda/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/eric/miniconda/lib/python3.5/site-packages/conda/cli/main_clean.py", line 455, in execute
    json_result['source_cache'] = find_source_cache()
  File "/home/eric/miniconda/lib/python3.5/site-packages/conda/cli/main_clean.py", line 362, in find_source_cache
    'source cache': conda_build.source.SRC_CACHE,
AttributeError: module 'conda_build.source' has no attribute 'SRC_CACHE'
```

and the relevant bits from my conda environment
```
$ conda list -e | grep conda
Using Anaconda Cloud api site https://api.anaconda.org
# $ conda create --name <env> --file <this file>
anaconda-client=1.4.0=py35_0
conda=4.1.11=py35_1
conda-env=2.5.2=py35_0
conda-execute=0.6.0=py35_0
```

```
$ pip list | grep conda
anaconda-client (1.4.0)
conda (4.1.11)
conda-build (2.0.0b2, /home/eric/dev/conda/conda-build)
conda-build-all (0.13.3, /home/eric/dev/conda/conda-build-all)
conda-env (2.5.0a0)
conda-execute (0.6.0)
```

**Comment by msarahan** [comment]
Thanks.  This requires a patch to conda.  I'll look into it.
