### ISSUE TITLE
conda build fails for pyad - Win-x64

### ISSUE THREAD

**Issue by bmcguirk** [conda/conda-build#1263]
Hi guys - 

Trying to install [pyad](https://github.com/zakird/pyad/) for interacting with Active Directory. Here's the report out: 

```shell
PS pkg:\> conda skeleton pypi pyad
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): pypi.python.org
Warning, the following versions were found for pyad
0.4.10
0.4.12
0.4.13
0.4.14
0.4.15
0.4.16
0.4.17
0.4.18
0.4.19
0.4.9
0.5.02
0.5.03
0.5.04
0.5.05
0.5.06
0.5.07
0.5.08
0.5.11
0.5.14
Using 0.5.14
Use --version to specify a different version.
Using url https://pypi.python.org/packages/28/f3/251f4fcc765bca67d6a9944590696bb11fea124f0a2851b9667b7abfa3d6/pyad-0.5.14.tar.gz (22 KB) for pyad.
Downloading pyad
Using cached download
Unpacking pyad...
done
working in C:\Users\[USER]\AppData\Local\Temp\tmpzpqlopzxconda_skeleton_pyad-0.5.14.tar.gz
Using Anaconda Cloud api site https://api.anaconda.org

Applying patch: 'C:\\Users\\[USER]\\AppData\\Local\\Temp\\tmpzpqlopzxconda_skeleton_pyad-0.5.14.tar.gz\\pypi-distutils.patch'
patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 1 line).
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    long_description = read('README.rst'),
  File "setup.py", line 7, in read
    return open(os.path.join(os.path.dirname(__file__), fname)).read()
  File "C:\Anaconda3\envs\_build\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6116: character maps to <undefined>
$PYTHONPATH = C:\Users\BRIAN~1.MCG\AppData\Local\Temp\tmpzpqlopzxconda_skeleton_pyad-0.5.14.tar.gz\pyad-0.5.14
Error: command failed: C:\Anaconda3\envs\_build\python.exe setup.py install
```
`conda info` readout:
```shell
PS pkg:\> conda info
Current conda install:

             platform : win-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.14+0.g4dfebe9.dirty
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/spacy/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/spacy/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : C:\Users\Brian.McGuirk\.condarc
         offline mode : False
    is foreign system : False
```

Happy to use a different module if anyone knows a better one, but, for now, trying to install this. 
Thanks in advance, as always.

**Comment by msarahan** [comment]
Some kind of unicode errror from the contents of their readme.  I'm surprised to see this with Python 3, but I'll see about a patch.  Thanks for raising the issue.

**Comment by msarahan** [comment]
I took a closer look here.  There's nothing conda-build can do here.  The exception is happening completely in the pyad code.  They define their own read alias, but they don't do any unicode handling in it: https://github.com/zakird/pyad/blob/master/setup.py#L7

There is no way for conda-build to get in the middle there - especially not in any generally supportable way.

This exception might not show up if you run conda skeleton pypi under a python 2.7 installation, just due to differences in how the read function behaves between python 2 and 3.

Please close this issue if it answers your question - sorry there isn't an easy fix.

**Comment by msarahan** [comment]
Closing this issue pending resolution of https://github.com/zakird/pyad/issues/58 - please reopen or open a new issue if new information develops.
