### ISSUE TITLE
conda build master needs at least conda 4.1.0

### ISSUE THREAD

**Issue by ericdill** [conda/conda-build#1264]
or conda build fails with this stack trace:

```
$ conda install "conda<4.1"
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /home/eric/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.0.11               |           py35_0         189 KB  defaults

The following packages will be DOWNGRADED due to dependency conflicts:

    conda:     4.1.11-py35_1 conda-forge --> 4.0.11-py35_0 defaults
    conda-env: 2.5.1-py35_0  defaults    --> 2.4.5-py35_0  defaults

Fetching packages ...
conda-4.0.11-p 100% |#######################################################################################| Time: 0:00:00   1.93 MB/s
Extracting packages ...
[      COMPLETE      ]|##########################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##########################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##########################################################################################################| 100%
()eric@eric-VirtualBox:~/dev/conda-forge/spylon-feedstock/recipe (master * u=)$ conda build .
Traceback (most recent call last):
  File "/home/eric/miniconda/bin/conda-build", line 9, in <module>
    load_entry_point('conda-build', 'console_scripts', 'conda-build')()
  File "/home/eric/miniconda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/eric/miniconda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2570, in load_entry_point
    return ep.load()
  File "/home/eric/miniconda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2230, in load
    return self.resolve()
  File "/home/eric/miniconda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2236, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/eric/dev/conda/conda-build/conda_build/cli/main_build.py", line 17, in <module>
    import conda_build.api as api
  File "/home/eric/dev/conda/conda-build/conda_build/api.py", line 22, in <module>
    from conda_build.config import Config, get_or_merge_config, DEFAULT_PREFIX_LENGTH as _prefix_length
  File "/home/eric/dev/conda/conda-build/conda_build/config.py", line 14, in <module>
    from .conda_interface import string_types, binstar_upload
  File "/home/eric/dev/conda/conda-build/conda_build/conda_interface.py", line 23, in <module>
    from conda.utils import human_bytes, hashsum_file, md5_file, memoized, unix_path_to_win, win_path_to_unix, url_path  # NOQA
ImportError: cannot import name 'unix_path_to_win'
```

But this is fine on conda 4.1.0 and newer:

```
$ conda install "conda=4.1.0"
Using Anaconda API: https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: .........

Package plan for installation in environment /home/eric/miniconda:

The following packages will be UPDATED:

    conda:     4.0.11-py35_0 defaults --> 4.1.0-py35_0 defaults
    conda-env: 2.4.5-py35_0  defaults --> 2.5.1-py35_0 defaults

Unlinking packages ...
[      COMPLETE      ]|##########################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##########################################################################################################| 100%
()eric@eric-VirtualBox:~/dev/conda-forge/spylon-feedstock/recipe (master * u=)$ conda build .
Removing old build environment
BUILD START: spylon-0.2.4-py35_0
    (actual version deferred until further download or env creation)
updating index in: /home/eric/miniconda/conda-bld/linux-64
updating index in: /home/eric/miniconda/conda-bld/noarch
Using Anaconda API: https://api.anaconda.org
Using Anaconda API: https://api.anaconda.org

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    zlib-1.2.8                 |                3          87 KB  conda-forge

The following NEW packages will be INSTALLED:

    ca-certificates: 2016.8.2-3      conda-forge
    certifi:         2016.8.2-py35_0 conda-forge
    ncurses:         5.9-8           conda-forge
    openssl:         1.0.2h-2        conda-forge
    pip:             8.1.2-py35_0    conda-forge
    python:          3.5.2-2         conda-forge
    readline:        6.2-0           conda-forge
    setuptools:      25.1.6-py35_0   conda-forge
    sqlite:          3.13.0-1        conda-forge
    tk:              8.5.19-0        conda-forge
    wheel:           0.29.0-py35_0   conda-forge
    xz:              5.2.2-0         conda-forge
    zlib:            1.2.8-3         conda-forge

WARNING:/home/eric/dev/conda/conda-build/conda_build/build.py:Build prefix failed with prefix length 255.
WARNING:/home/eric/dev/conda/conda-build/conda_build/build.py:Error was: 
WARNING:/home/eric/dev/conda/conda-build/conda_build/build.py:ERROR: placeholder '/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho' too short in: conda-forge::ncurses-5.9-8

WARNING:/home/eric/dev/conda/conda-build/conda_build/build.py:One or more of your package dependencies needs to be rebuilt with a longer prefix length.
WARNING:/home/eric/dev/conda/conda-build/conda_build/build.py:Falling back to legacy prefix length of 80 characters.
WARNING:/home/eric/dev/conda/conda-build/conda_build/build.py:Your package will not install into prefixes > 80 characters.
updating index in: /home/eric/miniconda/conda-bld/linux-64
updating index in: /home/eric/miniconda/conda-bld/noarch
Using Anaconda API: https://api.anaconda.org

The following NEW packages will be INSTALLED:

    ca-certificates: 2016.8.2-3      conda-forge
    certifi:         2016.8.2-py35_0 conda-forge
    ncurses:         5.9-8           conda-forge
    openssl:         1.0.2h-2        conda-forge
    pip:             8.1.2-py35_0    conda-forge
    python:          3.5.2-2         conda-forge
    readline:        6.2-0           conda-forge
    setuptools:      25.1.6-py35_0   conda-forge
    sqlite:          3.13.0-1        conda-forge
    tk:              8.5.19-0        conda-forge
    wheel:           0.29.0-py35_0   conda-forge
    xz:              5.2.2-0         conda-forge
    zlib:            1.2.8-3         conda-forge

WARNING: Could not detect installed version of conda-build
WARNING: Could not detect installed version of conda-build
Source cache directory is: /home/eric/miniconda/conda-bld/src_cache
Downloading source to cache: spylon-0.2.4.tar.gz
Downloading https://github.com/maxpoint/spylon/archive/0.2.4.tar.gz
Success
SHA256 mismatch: 'b4bffde914eea4d5ac8810b82b0e5578e9f0debd94ff4efcdffcd2b978e2c44e' != '6882a1ea5d7fb7dc206b96a93d2b386acab964f8a8ecf2441e10a006288bf811'
```

^ (obviously the sha256 mismatch is my problem :grinning: )

attn @msarahan

**Comment by ericdill** [comment]
Where would you pin that master needs `conda >=4.1.0` ? `setup.py`?

**Comment by ericdill** [comment]
Yup, just as a I feared.  Just checked the meta.yaml and its already pinned.  Perfect.  1/3 in reporting useful issues these last few days

**Comment by msarahan** [comment]
hah, well, that's infinitely better than 0.
