### ISSUE TITLE
Trying to copy directory as file?

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1275]
Running into this issue when building [repo]( https://github.com/conda-forge/ncurses-feedstock/ ) locally in the `conda-forge/linux-anvil` container. Reproduced with `conda-build` versions `1.21.14` and `1.21.12`. However, `1.21.11` does not have the problem.

```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.5/site-packages/conda_build/main_build.py", line 151, in main
    args_func(args, p)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/main_build.py", line 412, in args_func
    args.func(args, p)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/main_build.py", line 355, in execute
    debug=args.debug)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 661, in build
    post_build(m, sorted(files2 - files1))
  File "/opt/conda/lib/python3.5/site-packages/conda_build/post.py", line 370, in post_build
    make_hardlink_copy(f)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/post.py", line 416, in make_hardlink_copy
    shutil.copy2(path, "tmpfile")
  File "/opt/conda/lib/python3.5/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/conda/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: 'lib/terminfo'
```
Info

```
conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.14+0.g4dfebe9.dirty
       python version : 3.5.2.final.0
     requests version : 2.11.0
     root environment : /opt/conda  (writable)
  default environment : /opt/conda
     envs directories : /opt/conda/envs
        package cache : /opt/conda/pkgs
         channel URLs : https://conda.anaconda.org/conda-forge/linux-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /root/.condarc
         offline mode : False
    is foreign system : False

```

```
$ docker info
Containers: 7
 Running: 2
 Paused: 0
 Stopped: 5
Images: 18
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 68
 Dirperm1 Supported: true
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.789 GiB
Name: xxx
ID: xxx
Debug mode (server): true
 File Descriptors: 25
 Goroutines: 56
 System Time: 2016-08-25T19:52:23.8851545Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: 
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: xxx
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.9.5
BuildVersion:	13F1911
```

**Comment by msarahan** [comment]
Thanks for the report.  I'll fix this for the 2.0 release on Monday.

**Comment by jakirkham** [comment]
Alright, thanks. Just as FYI, this problem doesn't exist in `1.21.11` if that helps.

**Comment by msarahan** [comment]
Yes, this was compensation for anaconda-verify not allowing hard-links.  Someone ran into trouble with installing a package that had them.  I think that you cannot soft-link to a hard-linked file, or something.  Not a common problem, but important.

**Comment by jakirkham** [comment]
Guess this came full circle then. The reason that got added to `anaconda-verify` was to catch issues with `ncurses` using hardlinks.

Weird though as we tell `ncurses` [not to use hardlinks]( https://github.com/conda-forge/ncurses-feedstock/blob/f2c5cafeaac66cd35ce7a4c55b68098800a2d925/recipe/build.sh#L20 ). 😕

cc @mingwandroid

**Comment by msarahan** [comment]
I think #1273 works.  I tested it in my docker container.  If it does not work in linux-anvil, then I'm inclined to start pointing at devtoolset doing something unwanted.

**Comment by hainm** [comment]
@msarahan I got `IsADirectoryError` too with 

```bash
             platform : linux-64
        conda version : 4.1.12
    conda-env version : 2.5.2
  conda-build version : 2.0.0beta4
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/haichit/anaconda3  (writable)
  default environment : /home/haichit/anaconda3
     envs directories : /home/haichit/anaconda3/envs
        package cache : /home/haichit/anaconda3/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/conda-canary/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/conda-canary/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/conda-forge/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/conda-forge/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/ambermd/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/ambermd/noarch/
          config file : /home/haichit/.condarc
         offline mode : False
    is foreign system : False
```

error
```bash
Traceback (most recent call last):
  File "/home/haichit/anaconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/haichit/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 246, in main
    execute(sys.argv[1:])
  File "/home/haichit/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 231, in execute
    action(m, config)
  File "/home/haichit/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 172, in test_action
    return api.test(metadata.path, move_broken=False, config=config)
  File "/home/haichit/anaconda3/lib/python3.5/site-packages/conda_build/api.py", line 92, in test
    tar_xf(package_path, tmp)
  File "/home/haichit/anaconda3/lib/python3.5/site-packages/conda_build/utils.py", line 180, in tar_xf
    t = tarfile.open(tarball, mode)
  File "/home/haichit/anaconda3/lib/python3.5/tarfile.py", line 1562, in open
    return func(name, "r", fileobj, **kwargs)
  File "/home/haichit/anaconda3/lib/python3.5/tarfile.py", line 1688, in xzopen
    fileobj = lzma.LZMAFile(fileobj or name, mode, preset=preset)
  File "/home/haichit/anaconda3/lib/python3.5/lzma.py", line 118, in __init__
    self._fp = builtins.open(filename, mode)
IsADirectoryError: [Errno 21] Is a directory: '/net/casegroupp/u1/haichit/pytraj_git/pytraj/devtools/conda-recipe/pytraj'
```

any idea how I can fix that? thanks.

**Comment by msarahan** [comment]
Please update to conda build 2.0.7 and try again.

**Comment by hainm** [comment]
@msarahan  I would love to and I actually tried to do that this afternoon.

```bash
 $ conda install conda-build -c conda-forge --force
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment /home/haichit/anaconda3:

The following NEW packages will be INSTALLED:

    conda-build: 2.0.0beta4-py35_0 conda-canary

Proceed ([y]/n)? y

Pruning extracted packages from the cache ...
[      COMPLETE      ]|##################################################################################################################################################################################| 100%
Extracting packages ...
[      COMPLETE      ]|##################################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################################################################################################################################################| 100%
haichit@casegroup1 ~/pytraj_git/pytraj (test) $ conda build --version
conda-build 2.0.0beta4
```

**Comment by msarahan** [comment]
Due to channel priority, you are getting the old package.  You need to probably remove the conda-canary channel from your .condarc.  I will also remove the conda-build package there to avoid further confusion.

**Comment by hainm** [comment]
Do you think it's a bug?

I explicitly specified the channel.

**Comment by msarahan** [comment]
Maybe - specifying the channel really should put conda-forge at the top of the list (though note that conda-forge currently only has 1.21.14).  If you don't mind, please write up a bug report on the conda issue tracker.

**Comment by hainm** [comment]
sure. https://github.com/conda/conda/issues/3742
