### ISSUE TITLE
Bug when postprocessing build

### ISSUE THREAD

**Issue by johanneskoester** [conda/conda-build#1292]
I see the following error when building a package (version 1.21.14+0.g4dfebe9.dirty):

```
Traceback (most recent call last):
  File "/home/johannes/.local/opt/miniconda3/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/home/johannes/.local/opt/miniconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 151, in main
    args_func(args, p)
  File "/home/johannes/.local/opt/miniconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 412, in args_func
    args.func(args, p)
  File "/home/johannes/.local/opt/miniconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 355, in execute
    debug=args.debug)
  File "/home/johannes/.local/opt/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 650, in build
    preserve_egg_dir=bool(m.get_value('build/preserve_egg_dir')))
  File "/home/johannes/.local/opt/miniconda3/lib/python3.5/site-packages/conda_build/post.py", line 194, in post_process
    compile_missing_pyc(files)
  File "/home/johannes/.local/opt/miniconda3/lib/python3.5/site-packages/conda_build/post.py", line 189, in compile_missing_pyc
    call([python_exe, '-Wi', '-m', 'py_compile', f], cwd=cwd)
  File "/home/johannes/.local/opt/miniconda3/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/johannes/.local/opt/miniconda3/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/home/johannes/.local/opt/miniconda3/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/home/johannes/.local/opt/miniconda3/envs/_build_placehold_placehold_placehold_p/bin/python'
```

**Comment by msarahan** [comment]
Thanks for reporting.  This is already fixed by https://github.com/conda/conda-build/pull/1261, which is available in conda-build 2.0.  This has been released, but does not seem to be generally available yet in package form.  I will ask why.

**Comment by msarahan** [comment]
Conda-build 2.0 is available.  I'm closing this issue.  If you have further problems, please reopen this issue, or open a new one.

**Comment by johanneskoester** [comment]
Ok, thanks Mike!
