### ISSUE TITLE
conda.instructions.UNLINK_CMD TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Korijn** [conda/conda-build#1319]
We've been seeing this bug (which is a regression, judging from other issues) since the 2.0.0 release, and it's breaking our release cycle, so any thoughts are welcome. It's an unpredictable issue that pops up randomly a few times a day, so we don't know how to reproduce either.

```
[00:11:06] Traceback (most recent call last):
[00:11:06] 
[00:11:06]   File "C:\Miniconda35-x64\Scripts\conda-build-script.py", line 5, in <module>
[00:11:06] 
[00:11:06]     sys.exit(conda_build.cli.main_build.main())
[00:11:06] 
[00:11:06]   File "C:\Miniconda35-x64\lib\site-packages\conda_build\cli\main_build.py", line 234, in main
[00:11:06] 
[00:11:06]     execute(sys.argv[1:])
[00:11:06] 
[00:11:06]   File "C:\Miniconda35-x64\lib\site-packages\conda_build\cli\main_build.py", line 226, in execute
[00:11:06] 
[00:11:06]     already_built=None, config=config)
[00:11:06] 
[00:11:06]   File "C:\Miniconda35-x64\lib\site-packages\conda_build\api.py", line 81, in build
[00:11:06] 
[00:11:06]     need_source_download=need_source_download, config=config)
[00:11:06] 
[00:11:06]   File "C:\Miniconda35-x64\lib\site-packages\conda_build\build.py", line 944, in build_tree
[00:11:06] 
[00:11:06]     test(metadata, config=config)
[00:11:06] 
[00:11:06]   File "C:\Miniconda35-x64\lib\site-packages\conda_build\build.py", line 798, in test
[00:11:06] 
[00:11:06]     create_env(config.test_prefix, specs, config=config)
[00:11:06] 
[00:11:06]   File "C:\Miniconda35-x64\lib\site-packages\conda_build\build.py", line 440, in create_env
[00:11:06] 
[00:11:06]     plan.execute_actions(actions, index, verbose=config.deb
[00:11:06] ug)
[00:11:06] 
[00:11:06]   File "C:\Miniconda35-x64\lib\site-packages\conda\plan.py", line 599, in execute_actions
[00:11:06] 
[00:11:06]     inst.execute_instructions(plan, index, verbose)
[00:11:06] 
[00:11:06]   File "C:\Miniconda35-x64\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
[00:11:06] 
[00:11:06]     cmd(state, arg)
[00:11:06] 
[00:11:06]   File "C:\Miniconda35-x64\lib\site-packages\conda\instructions.py", line 82, in UNLINK_CMD
[00:11:06] 
[00:11:06]     unlink(state['prefix'], arg)
[00:11:06] 
[00:11:06]   File "C:\Miniconda35-x64\lib\site-packages\conda\install.py", line 1121, in unlink
[00:11:06] 
[00:11:06]     mk_menus(prefix, meta['files'], remove=True)
[00:11:06] 
[00:11:06] TypeError: 'NoneType' object is not subscriptable
```

`conda info -a`:

```
[00:01:54] conda info -a
[00:01:55] Current conda install:
[00:01:55] 
[00:01:55]              platform : win-64
[00:01:55]         conda version : 4.1.11
[00:01:55]     conda-env version : 2.5.2
[00:01:55]   conda-build version : 2.0.0
[00:01:55]        python version : 3.5.2.final.0
[00:01:55]      requests version : 2.9.1
[00:01:55]      root environment : C:\Miniconda35-x64  (writable)
[00:01:55]   default environment : C:\Miniconda35-x64
[00:01:55]      envs directories : C:\Miniconda35-x64\envs
[00:01:55]         package cache : C:\Miniconda35-x64\pkgs
[00:01:55]          channel URLs : https://repo.continuum.io/pkgs/free/win-64/
[00:01:55]                         https://repo.continuum.io/pkgs/free/noarch/
[00:01:55]                         https://repo.continuum.io/pkgs/pro/win-64/
[00:01:55]                         https://repo.continuum.io/pkgs/pro/noarch/
[00:01:55]                         https://repo.continuum.io/pkgs/msys2/win-64/
[00:01:55]                         https://repo.continuum.io/pkgs/msys2/noarch/
[00:01:55]           config file : C:\Users\appveyor\.condarc
[00:01:55]          offline mode : False
[00:01:55]     is foreign system : False
[00:01:55] 
[00:01:55] # conda environments:
[00:01:55] #
[00:01:55] root                  *  C:\Miniconda35-x64
[00:01:55] 
[00:01:55] s
[00:01:55] ys.version: 3.5.2 |Continuum Analytics, Inc.| (defau...
[00:01:55] sys.prefix: C:\Miniconda35-x64
[00:01:55] sys.executable: C:\Miniconda35-x64\python.exe
[00:01:55] conda location: C:\Miniconda35-x64\lib\site-packages\conda
[00:01:55] conda-build: C:\Miniconda35-x64\Scripts\conda-build.exe
[00:01:55] conda-convert: C:\Miniconda35-x64\Scripts\conda-convert.exe
[00:01:55] conda-develop: C:\Miniconda35-x64\Scripts\conda-develop.exe
[00:01:55] conda-env: C:\Miniconda35-x64\Scripts\conda-env.exe
[00:01:55] conda-index: C:\Miniconda35-x64\Scripts\conda-index.exe
[00:01:55] conda-inspect: C:\Miniconda35-x64\Scripts\conda-inspect.exe
[00:01:55] conda-metapackage: C:\Miniconda35-x64\Scripts\conda-metapackage.exe
[00:01:55] conda-render: C:\Miniconda35-x64\Scripts\conda-render.exe
[00:01:55] conda-server: C:\Miniconda35-x64\Scripts\conda-server.exe
[00:01:55] conda-sign: C:\Miniconda35-x64\Scripts\conda-sign.exe
[00:01:55] conda-skeleton: C:\Miniconda35-x64\Scripts\conda-skeleton.exe
[00:01:55] user site dirs: 
[00:01:55] 
[00:01:55] CIO_TEST: <not set>
[00:01:55] CONDA_DEFAULT_ENV: <not set>
[00:01:55] CONDA_ENVS_PATH: <not set>
[00:01:55] PATH: C:\Miniconda35-x64\Library\bin;C:\Miniconda35-x64;C:\Miniconda35-x64
[00:01:55] \Scripts;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Mercurial;;C:\Program Files\7-Zip;C:\Program Files\AppVeyor\BuildAgent
[00:01:55] PYTHONHOME: <not set>
[00:01:55] PYTHONPATH: <not set>
```

**Comment by msarahan** [comment]
Interesting. I'll fix it for the next bug fix release.

**Comment by msarahan** [comment]
@Korijn can you paste any more of your traceback?  This seems to be happening while creating the test environment.  It seems to be issuing package unlink instructions, but this makes no sense, because the environment should be completely brand-new.  I'm curious what additional output, if any, conda shows about which packages are getting unlinked.

**Comment by Korijn** [comment]
Well, actually, one thing I noticed in relation to this, is that if I run `conda remove -n myenv --all -y` and in the working directory there is a source folder `myenv`, then conda will remove that folder too! Maybe it's related?

**Comment by Korijn** [comment]
Same for `conda env remove -n myenv -y`

**Comment by msarahan** [comment]
Those are definitely worrisome, but I don't think they are related here.  Nothing in conda-build should be removing environments or packages.  The removal of the build folder is done by simply removing it with conda's rm_rf function - no uninstall of any packages, just a straight removal of folders.

Please file an issue on the conda issue tracker for those issues.

**Comment by msarahan** [comment]
When you get time, please paste more of your build log.  I have tried to see where unlinking might be happening, but have not identified it yet.

**Comment by Korijn** [comment]
Sorry, on this side of the globe, office hours pretty much end when yours seem to begin. :)

I filed an issue with a reproduction example for the delete bug here: https://github.com/conda/conda/issues/3383

I'm  working on a reproduction example for this one.

**Comment by Korijn** [comment]
Is there someway I can send the build log to you in private? I have it ready but since it's for a propietary package I'd rather send it to you differently.

**Comment by Korijn** [comment]
Here's the build log, it should be only accessible to you @msarahan, because it contains output of a propietary package. You should have an invite.

https://github.com/Korijn/conda-build-bug-build-log/blob/master/build_log.txt

**Comment by msarahan** [comment]
@Korijn, thank you.  That is a very strange build log.  I'm concerned that things appear to be happening out of order.  In particular, it appears that the output from ```python setup.py install``` is coming before the output from creation of the build environment.  Do you have more than one build occurring simultaneously?  I noticed that because your recipe is in the conda-recipe folder, your build id's may collide if you build this same recipe in multiple processes at the same time (the long number is the number of ms since the epoch).

The removal itself happens because the test environment already exists, but due to channel priority, conda wants to replace a build of ```cachedproperty``` from your channel with one from defaults.

I will ponder possible ways that this might arise, but welcome any further information you have.

**Comment by Korijn** [comment]
We do run the same build for py27 & py35 using the build matrix on AppVeyor. I wonder if they aren't running in isolated processes? It seems unlikely, especially since we sometimes encounter the same bug locally.

Trying to reproducing the bug predictably so far has not yielded results, unfortunately.

**Comment by msarahan** [comment]
Does your local build log also show the same out of order behavior?

**Comment by Korijn** [comment]
Well, as soon as we encounter it, I'll be sure to share the log.

**Comment by msarahan** [comment]
Thanks.  I'll keep an eye out for this behavior on my end in the meantime as well.
