### ISSUE TITLE
skeleton pypi doesn't work with paver

### ISSUE THREAD

**Issue by winni-genp** [conda/conda-build#1352]
```
conda build pypi paver
```
Fails with the output stored in [log.txt](https://github.com/conda/conda-build/files/472221/log.txt)
Here is a tail:
```
Applying patch: '/tmp/tmpiIWvNhconda_skeleton_Paver-1.2.4.tar.gz/pypi-distutils.patch'
Traceback (most recent call last):
  File "/local/scratch/winni/proj/EchiDNA/conda_packages/env/bin/conda-skeleton", line 6, in <module>
    sys.exit(conda_build.cli.main_skeleton.main())
  File "/local/scratch/winni/proj/EchiDNA/conda_packages/env/lib/python2.7/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/local/scratch/winni/proj/EchiDNA/conda_packages/env/lib/python2.7/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    api.skeletonize(package, repo=args.repo, config=config)
  File "/local/scratch/winni/proj/EchiDNA/conda_packages/env/lib/python2.7/site-packages/conda_build/api.py", line 179, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/local/scratch/winni/proj/EchiDNA/conda_packages/env/lib/python2.7/site-packages/conda_build/skeletons/pypi.py", line 405, in skeletonize
    noprompt, packages, config=config, setup_options=setup_options)
  File "/local/scratch/winni/proj/EchiDNA/conda_packages/env/lib/python2.7/site-packages/conda_build/skeletons/pypi.py", line 644, in get_package_metadata
    config=config)
  File "/local/scratch/winni/proj/EchiDNA/conda_packages/env/lib/python2.7/site-packages/conda_build/skeletons/pypi.py", line 905, in get_pkginfo
    with open(join(tempdir, 'pkginfo.yaml')) as fn:
IOError: [Errno 2] No such file or directory: '/tmp/tmpiIWvNhconda_skeleton_Paver-1.2.4.tar.gz/pkginfo.yaml'
```

**Comment by msarahan** [comment]
Thanks for reporting.  It looks like Paver does not include the pkginfo.yaml file.  I don't know what package or version of package used to create the Paver package does not include that.  It does have PKG-INFO, though, which I think is the same thing.  I'll add a fallback to PKG-INFO.

**Comment by winni-genp** [comment]
Thanks for the quick response!
