### ISSUE TITLE
corrupt package from conda-build 2.0: puts .exe file with no prefix in has_prefix file

### ISSUE THREAD

**Issue by mwiebe** [conda/conda-build#1409]
The `has_prefix` file contains:

```
"C:\Anaconda3\conda-bld\libe57_1474996957811\_b_env" binary "Library/bin/las2e57.exe"
```

trying to use this package in a subsequent conda-build produces this error message:

```
2016-09-27 11:49:17:  0: STDOUT: Traceback (most recent call last):
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\install.py", line 974, in link
2016-09-27 11:49:17:  0: STDOUT:     update_prefix(join(prefix, filepath), prefix, placeholder, mode)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\install.py", line 368, in update_prefix
2016-09-27 11:49:17:  0: STDOUT:     data = replace_prefix(mode, data, placeholder, new_prefix)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\install.py", line 352, in replace_prefix
2016-09-27 11:49:17:  0: STDOUT:     data = binary_replace(data, placeholder.encode(UTF8), new_prefix.encode(UTF8))
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\install.py", line 273, in binary_replace
2016-09-27 11:49:17:  0: STDOUT:     data = pat.sub(replace, data)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\install.py", line 268, in replace
2016-09-27 11:49:17:  0: STDOUT:     raise _PaddingError
2016-09-27 11:49:17:  0: STDOUT: conda.install._PaddingError
2016-09-27 11:49:17:  0: STDOUT: During handling of the above exception, another exception occurred:
2016-09-27 11:49:17:  0: STDOUT: Traceback (most recent call last):
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda_build\build.py", line 427, in create_env
2016-09-27 11:49:17:  0: STDOUT:     plan.execute_actions(actions, index, verbose=config.debug)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
2016-09-27 11:49:17:  0: STDOUT:     inst.execute_instructions(plan, index, verbose)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
2016-09-27 11:49:17:  0: STDOUT:     cmd(state, arg)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 78, in LINK_CMD
2016-09-27 11:49:17:  0: STDOUT:     link(state['prefix'], dist, lt, index=state['index'])
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\install.py", line 976, in link
2016-09-27 11:49:17:  0: STDOUT:     raise PaddingError(dist, placeholder, len(placeholder))
2016-09-27 11:49:17:  0: STDOUT: conda.exceptions.PaddingError: Placeholder of length '50' too short in package http://conda-01:8080::libe57-1.1.332-msvc2012rel_6.
2016-09-27 11:49:17:  0: STDOUT: The package must be rebuilt with conda-build > 2.0.
2016-09-27 11:49:17:  0: STDOUT: During handling of the above exception, another exception occurred:
2016-09-27 11:49:17:  0: STDOUT: Traceback (most recent call last):
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\install.py", line 974, in link
2016-09-27 11:49:17:  0: STDOUT:     update_prefix(join(prefix, filepath), prefix, placeholder, mode)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\install.py", line 368, in update_prefix
2016-09-27 11:49:17:  0: STDOUT:     data = replace_prefix(mode, data, placeholder, new_prefix)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\install.py", line 352, in replace_prefix
2016-09-27 11:49:17:  0: STDOUT:     data = binary_replace(data, placeholder.encode(UTF8), new_prefix.encode(UTF8))
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\install.py", line 273, in binary_replace
2016-09-27 11:49:17:  0: STDOUT:     data = pat.sub(replace, data)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\install.py", line 268, in replace
2016-09-27 11:49:17:  0: STDOUT:     raise _PaddingError
2016-09-27 11:49:17:  0: STDOUT: conda.install._PaddingError
2016-09-27 11:49:17:  0: STDOUT: During handling of the above exception, another exception occurred:
2016-09-27 11:49:17:  0: STDOUT: Traceback (most recent call last):
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\Scripts\conda-build-script.py", line 5, in <module>
2016-09-27 11:49:17:  0: STDOUT:     sys.exit(conda_build.cli.main_build.main())
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda_build\cli\main_build.py", line 239, in main
2016-09-27 11:49:17:  0: STDOUT:     execute(sys.argv[1:])
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda_build\cli\main_build.py", line 231, in execute
2016-09-27 11:49:17:  0: STDOUT:     already_built=None, config=config)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda_build\api.py", line 83, in build
2016-09-27 11:49:17:  0: STDOUT:     need_source_download=need_source_download, config=config)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda_build\build.py", line 998, in build_tree
2016-09-27 11:49:17:  0: STDOUT:     config=recipe_config)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda_build\build.py", line 558, in build
2016-09-27 11:49:17:  0: STDOUT:     create_env(config.build_prefix, specs, config=config)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda_build\build.py", line 451, in create_env
2016-09-27 11:49:17:  0: STDOUT:     clear_cache=clear_cache)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda_build\build.py", line 427, in create_env
2016-09-27 11:49:17:  0: STDOUT:     plan.execute_actions(actions, index, verbose=config.debug)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
2016-09-27 11:49:17:  0: STDOUT:     inst.execute_instructions(plan, index, verbose)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
2016-09-27 11:49:17:  0: STDOUT:     cmd(state, arg)
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 78, in LINK_CMD
2016-09-27 11:49:17:  0: STDOUT:     link(state['prefix'], dist, lt, index=state['index'])
2016-09-27 11:49:17:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda\install.py", line 976, in link
2016-09-27 11:49:17:  0: STDOUT:     raise PaddingError(dist, placeholder, len(placeholder))
2016-09-27 11:49:17:  0: STDOUT: conda.exceptions.PaddingError: Placeholder of length '50' too short in package http://conda-01:8080::libe57-1.1.332-msvc2012rel_6.
2016-09-27 11:49:17:  0: STDOUT: The package must be rebuilt with conda-build > 2.0.
2016-09-27 11:49:17:  0: INFO: Process exit code: 1
```

The executable is a windows program, naturally has no prefix:

![image](https://cloud.githubusercontent.com/assets/399551/18887693/0a140eda-84aa-11e6-84c0-3b1063da405f.png)

**Comment by msarahan** [comment]
Some windows programs do actually have prefixes, unfortunately.  Most notably, pip is now creating exe's for entry points that have the launcher, plus the prefix, plus the python code all rolled into one.  We're having some growing pains coming up with supporting those.

This definitely looks wrong, though.  Are you certain that it does not have the prefix anywhere in the executable?  I have not seen it find something that simply isn't there before.

Conda should probably just be ignoring these prefixes in programs other than the pip-created entry points.  I'm not sure that conda-build should ignore detection of these prefixes.

**Comment by mwiebe** [comment]
Here's the generated package for you to inspect:

[libe57-1.1.332-msvc2012rel_6.tar.bz2.zip](https://github.com/conda/conda-build/files/496484/libe57-1.1.332-msvc2012rel_6.tar.bz2.zip)

I'm not sure what it is, but could be __FILE__ in a debug output of the source code or something similar. Maybe it should just be checking the first few bytes of the file for a prefix?

**Comment by msarahan** [comment]
Good idea, but we can't do that.  Those pip entry point exe's have the prefix in the middle of the file.

I submitted a conda PR to ignore non-pip entry points, which should hopefully make this problem go away for you.

**Comment by mwiebe** [comment]
This package was generated by conda-build 2.0.1, is it suspicious that the error message is telling us to do something we already did?

**Comment by msarahan** [comment]
The whole padding error stuff is pretty meaningless on Windows, since it has a hard path limit of 260 characters (that is going away soon?).

That error came up because it tried to do the traditional prefix replacement, which it really should not be doing.  They pip entry point replacement doesn't care about length - it just splits up the binary, replaces the prefix, and makes a new sandwich.

**Comment by mwiebe** [comment]
Ok, so it will still create the has_prefix metadata potentially inappropriately sometimes, but conda will ignore it now.

**Comment by msarahan** [comment]
Yeah, exactly.  I'm not sure I'd ever call it inappropriate.  It is information that should be correct, but how it gets interpreted and acted upon is the thing that makes it inappropriate.  If the information is flat out wrong, like conda-build is making stuff up, then I'd call conda-build's behavior inappropriate.  

Conda-build is the only reliable source of knowledge about the prefix, because only it knows what the prefix was at build time.  That's the only reason it is involved here.  Really, conda is doing all the magic (and any unwanted hijinx) here.

**Comment by mwiebe** [comment]
After working around it in libe57, got an error in the next package:

```
conda.exceptions.PaddingError: Placeholder of length '47' too short in package http://conda-01:8080::tbb-4.4-msvc2012rel_4.
```

**Comment by msarahan** [comment]
Conda is again trying to replace a prefix there.  You need the patch I put forward for Conda, I'm pretty sure.

**Comment by mwiebe** [comment]
The conda-build behaviour seems to contradict http://conda.pydata.org/docs/building/meta-yaml.html#detect-binary-files-with-prefix which says the default is no detection. Is this a behaviour change?

**Comment by msarahan** [comment]
Yes, the docs need to be updated.  This change might have happened at the
2.0 release, but I'm not certain.  To ignore it completely, set this:

http://conda.pydata.org/docs/building/meta-yaml.html#ignore-prefix-files

**Comment by mwiebe** [comment]
Would this work?

```
build:
  detect_binary_files_with_prefix: False
```

**Comment by msarahan** [comment]
I'm pretty sure it would, but if it doesn't, then

```
build:
  ignore_prefix_files: True
```

https://github.com/conda/conda-docs/pull/359

**Comment by mwiebe** [comment]
The option `detect_binary_files_with_prefix` does not work, trying `ignore_prefix_files`

**Comment by mwiebe** [comment]
Setting `ignore_prefix_files` did work.

**Comment by msarahan** [comment]
Thanks, I updated the docs accordingly.

**Comment by msarahan** [comment]
@mwiebe this should be sorted out in recent versions of conda 4.2.  Can you please confirm whether this is still an issue?

**Comment by msarahan** [comment]
Closing due to inactivity.

**Comment by mwiebe** [comment]
Right, sorry for the inactivity - we've been using `ignore_prefix_files` where this was a problem.

**Comment by msarahan** [comment]
No problem.  Be aware that in very recent versions of conda-build, I have separated the notion of RPATH changes and prefix replacement.  ignore_prefix_files is now strictly the prefix replacement.  http://conda.pydata.org/docs/building/meta-yaml.html#binary-relocation is the RPATH stuff.  I need to update the docs, but that field supports glob expressions for files that should be altered.  There is no inverse logic right now - as in "do everything, except these few files" - but that would be nice to have.
