### ISSUE TITLE
`Placeholder of length '48' too short in package` when using conda-build 2 on Windows

### ISSUE THREAD

**Issue by ocefpaf** [conda/conda-build#1415]
@msarahan I need some advice on what may the wrong here. `hdf5` was re-build with `conda-build 2` but the next dependency in the build queue complains what the placeholder is too short. (Everything is fine on `Linux` and `OS X` though.)

```shell
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-all-script.py", line 11, in <module>
    load_entry_point('conda-build-all==1.0.0', 'console_scripts', 'conda-build-all')()
  File "C:\Miniconda\lib\site-packages\conda_build_all\cli.py", line 90, in main
    b.main()
  File "C:\Miniconda\lib\site-packages\conda_build_all\builder.py", line 263, in main
    built_dist_location = self.build(meta, build_config)
  File "C:\Miniconda\lib\site-packages\conda_build_all\builder.py", line 200, in build
    conda_build.api.build(meta.meta, config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 83, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 998, in build_tree
    config=recipe_config)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 558, in build
    create_env(config.build_prefix, specs, config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 451, in create_env
    clear_cache=clear_cache)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 427, in create_env
    plan.execute_actions(actions, index, verbose=config.debug)
  File "C:\Miniconda\lib\site-packages\conda\plan.py", line 643, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Miniconda\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
    cmd(state, arg)
  File "C:\Miniconda\lib\site-packages\conda\instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "C:\Miniconda\lib\site-packages\conda\install.py", line 976, in link
    raise PaddingError(dist, placeholder, len(placeholder))
conda.exceptions.PaddingError: Placeholder of length '48' too short in package local::hdf5-1.8.17-vc9_0.
The package must be rebuilt with conda-build > 2.0.
Command exited with code 1
```

Full log https://ci.appveyor.com/project/comtbot/conda-recipes/build/1.0.2147/job/1mtdhegha2dnpqva

**Comment by msarahan** [comment]
More info at https://github.com/conda/conda-build/issues/1409

Closing this issue to consolidate discussion there.

**Comment by ocefpaf** [comment]
Thanks @msarahan!
