### ISSUE TITLE
Error with conda skeleton 

### ISSUE THREAD

**Issue by perlinger** [conda/conda-build#1425]
The following error was encountered
conda skeleton cran RPresto

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/mnt/efs/Anaconda/Anaconda3/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/mnt/efs/Anaconda/Anaconda3/lib/python3.5/site-packages/conda_build/main_skeleton.py", line 298, in main
    args_func(args, p)
  File "/mnt/efs/Anaconda/Anaconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 493, in args_func
    args.func(args, p)
  File "/mnt/efs/Anaconda/Anaconda3/lib/python3.5/site-packages/conda_build/main_skeleton.py", line 302, in execute
    import conda_build.pypi as pypi
  File "/mnt/efs/Anaconda/Anaconda3/lib/python3.5/site-packages/conda_build/pypi.py", line 30, in <module>
    from conda.config import get_proxy_servers
ImportError: cannot import name 'get_proxy_servers'

__________________________________
below is from conda info

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/mnt/efs/Anaconda/Anaconda3/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/mnt/efs/Anaconda/Anaconda3/lib/python3.5/site-packages/conda_build/main_skeleton.py", line 298, in main
    args_func(args, p)
  File "/mnt/efs/Anaconda/Anaconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 493, in args_func
    args.func(args, p)
  File "/mnt/efs/Anaconda/Anaconda3/lib/python3.5/site-packages/conda_build/main_skeleton.py", line 302, in execute
    import conda_build.pypi as pypi
  File "/mnt/efs/Anaconda/Anaconda3/lib/python3.5/site-packages/conda_build/pypi.py", line 30, in <module>
    from conda.config import get_proxy_servers
ImportError: cannot import name 'get_proxy_servers'
(r-env) [hadoop@ip-10-184-193-170 ~]$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 1.20.0
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /mnt/efs/Anaconda/Anaconda3  (writable)
    default environment : /mnt/efs/Anaconda/Anaconda3/envs/r-env
       envs directories : /mnt/efs/Anaconda/Anaconda3/envs
          package cache : /mnt/efs/Anaconda/Anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None

**Comment by msarahan** [comment]
You need to update conda-build.  1.20.0 is too old, and conda 4.2 has changed a lot of its internal layout.  Conda-build 2.0.2 should work.

**Comment by msarahan** [comment]
Closing this issue.  If you continue having issues, please reopen it or open a new issue.

**Comment by bkreider** [comment]
I just got hit by this issue as well.  If conda-build is using conda internals, should it have a more strict dependencies?

**Comment by msarahan** [comment]
Conda build began pinning conda some time ago, but I don't remember the exact version. Officially, conda build supports conda 4.1 and up, but there are some major issues with 4.3.

Which conda build version are you trying to use @bkreider ?

**Comment by bkreider** [comment]
I had a very old version of conda-build, so i ended up upgrading.  From my my history it looked like: `conda-build-1.18.2-py27_0`
