### ISSUE TITLE
file chmods fail with conda-build 2.0.2

### ISSUE THREAD

**Issue by janssen** [conda/conda-build#1426]
Given the forest of "placehold" strings, I'm having a hard time figuring out what's going on here.  But it looks like a file protection issue of some sort.  I checked; all my recipes have the same protection for bld.bat.  Could this be due to multiple unpacks of the "goodstuff" packages, due to multiple scans of the setup.py file?  This is on a buildbot, with a clean OS X Vagrant image, with conda-build 2.0.2.  Do I have to roll back to conda-build 1.x again?

```
BUILD START: goodstuff-1.0a5.post218+g344ae1df4486f1448d088fabb88cfa9a785e38ce.development-0

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pandoc-1.15.2              |                0        25.0 MB
    pyparsing-2.1.4            |           py27_0          70 KB
    six-1.10.0                 |           py27_0          16 KB
    packaging-16.7             |           py27_0          41 KB  https://goodstuff.parc.xerox.com/conda
    ------------------------------------------------------------
                                           Total:        25.1 MB

The following NEW packages will be INSTALLED:

    openssl:    1.0.2j-0                                       
    packaging:  16.7-py27_0   https://goodstuff.parc.xerox.com/conda
    pandoc:     1.15.2-0                                       
    pip:        8.1.2-py27_0                                   
    pyparsing:  2.1.4-py27_0                                   
    python:     2.7.12-1                                       
    readline:   6.2-2                                          
    setuptools: 27.2.0-py27_0                                  
    six:        1.10.0-py27_0                                  
    sqlite:     3.13.0-0                                       
    tk:         8.5.18-0                                       
    wheel:      0.29.0-py27_0                                  
    zlib:       1.2.8-3                                        

Package: goodstuff-1.0a5.post218+g344ae1df4486f1448d088fabb88cfa9a785e38ce.development-0
source tree in: /var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/conda-bld/goodstuff_1475512243326/work
compiling .pyc files...
number of files: 299
Fixing permissions
Traceback (most recent call last):
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 246, in main
    execute(sys.argv[1:])
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 238, in execute
    already_built=None, config=config)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/api.py", line 83, in build
    need_source_download=need_source_download, config=config)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 1004, in build_tree
    config=recipe_config)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 716, in build
    prefix=config.build_prefix)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 336, in create_info_files
    copy_recipe(m, config)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 190, in copy_recipe
    copy_into(src_path, dst_path, timeout=config.timeout)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/utils.py", line 107, in copy_into
    shutil.copy2(src, dst_fn)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/conda-bld/goodstuff_1475512243326/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/info/recipe/bld.bat'
```

**Comment by janssen** [comment]
Completely mystified here.  Same script works fine on my Ubuntu buildbot.

**Comment by msarahan** [comment]
We've seen some other mystifying things to do with shared folders passed into virtual machines.  There's some logic in there that tries to cope with how different OS's handle symlinks and such, and those heuristics are based on how Python reports itself - which may not match the underlying filesystem when shared folders and VMs are involved.

The other issue so far is https://github.com/conda/conda-build/issues/1302

**Comment by janssen** [comment]
I'm also a little wary of using the "shutil" module at all.  Neither the design nor the implementation of "shutil" fill me with admiration.

**Comment by janssen** [comment]
This is an OS X Yosemite Vagrant image running under Parallels on an OS X Yosemite host.  Run from a terminal on a MB Pro it runs just fine.

**Comment by msarahan** [comment]
If you have better ideas, I'm wide open to them.  shutil is rife with strangeness and issues, but it works right now for the vast majority of the time.

**Comment by janssen** [comment]
By the way, this OS X buildbot has been working fine for months until I shifted to conda-build 2.0.2.  Did you change the copying action somehow?

**Comment by msarahan** [comment]
What version did you update from?

**Comment by janssen** [comment]
1.21.14.

**Comment by msarahan** [comment]
Nothing really stands out to me, just addition of file locking for better support of parallel builds: https://gist.github.com/msarahan/73e21e87acd9822fc5e81a42e541b3c9

**Comment by janssen** [comment]
Better ideas:  unipath's Path.copy() would work here.  It doesn't try to copy flags.

**Comment by msarahan** [comment]
I'm hesitant to take on a new dependency just for this, and unipath's Path.copy() ends up using shutil anyway: https://github.com/mikeorr/Unipath/blob/master/unipath/path.py#L267-L279 .  Is it worth trying to copy flags first, but falling back to just ```copy```, and then ```copyfile``` so that your use case might work?

**Comment by janssen** [comment]
Unipath uses shutil, but not the overly ambitious part of shutil that attempts to copy flags.  It copies permissions and mtime, but not flags.

I think it would be fine, instead, to break down your use of shutil in a similar fashion; basically, just repeat the code from https://github.com/mikeorr/Unipath/blob/master/unipath/path.py#L267-L287 in your code to make your own copy.  The key is either to not use os.chflags, or catch the error if you do use it.

**Comment by janssen** [comment]
I've reverted my OS X buildbot to 1.21.14 till this gets fixed.  Seems to work OK.

**Comment by janssen** [comment]
Just ran with 2.0.4, seems OK now.  Thanks!

**Comment by janssen** [comment]
Hmmm, just tried upgrading to 2.1.3, and this bug is back.
```
+ conda build goodstuff --no-test
Copying /Volumes/SharedFolders/vagrant/platform to /var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/conda-bld/goodstuff_1487196967372/work
Traceback (most recent call last):
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T//miniconda2/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 1466, in build_tree
    config=config)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/render.py", line 157, in render_recipe
    config=config)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/render.py", line 86, in parse_or_try_download
    source.provide(metadata, config=config)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/source.py", line 521, in provide
    copy_into(path, config.work_dir, config.timeout, locking=config.locking)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/utils.py", line 119, in copy_into
    merge_tree(src, dst, symlinks, timeout=timeout, lock=lock, locking=locking)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/utils.py", line 236, in merge_tree
    copytree(src, dst, symlinks=symlinks)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/utils.py", line 199, in copytree
    copytree(s, d, symlinks, ignore)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/site-packages/conda_build/utils.py", line 202, in copytree
    shutil.copy2(s, d)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/8r/w07v646575j16n5bjcfrk44h0000gn/T/miniconda2/conda-bld/goodstuff_1487196967372/work/.git/config'
```
Same environment: an OS X Yosemite Vagrant image running under Parallels on an OS X Yosemite host.

**Comment by msarahan** [comment]
Try 2.1.4.  There were some attempts to fix these errors: https://github.com/conda/conda-build/pull/1728
