### ISSUE TITLE
Build failures in 2.0.3 due to load_setup_py_data()

### ISSUE THREAD

**Issue by sscherfke** [conda/conda-build#1429]
Some packages (e.g., NumPy and matplotlib) are failing with `conda-build = 2.0.3` in `File "/opt/pydist3/lib/python3.5/site-packages/conda_build/jinja_context.py", line 140, in load_setup_py_data`.

A traceback for NumPy 1.11.2:
```
Traceback (most recent call last):
  File "/opt/pydist3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/pydist3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 246, in main
    execute(sys.argv[1:])
  File "/opt/pydist3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 238, in execute
    already_built=None, config=config)
  File "/opt/pydist3/lib/python3.5/site-packages/conda_build/api.py", line 83, in build
    need_source_download=need_source_download, config=config)
  File "/opt/pydist3/lib/python3.5/site-packages/conda_build/build.py", line 1081, in build_tree
    config=recipe_config)
  File "/opt/pydist3/lib/python3.5/site-packages/conda_build/build.py", line 784, in build
    entry_point_script_names = get_entry_point_script_names(get_entry_points(config, m))
  File "/opt/pydist3/lib/python3.5/site-packages/conda_build/build.py", line 352, in get_entry_points
    setup_py_data = jinja_context.load_setup_py_data(config)
  File "/opt/pydist3/lib/python3.5/site-packages/conda_build/jinja_context.py", line 140, in load_setup_py_data
    exec(code, ns, ns)
  File "/opt/pydist3/conda-bld/python-numpy_1475583377288/work/numpy-1.11.2/setup.py", line 386, in <module>
    setup_package()
  File "/opt/pydist3/conda-bld/python-numpy_1475583377288/work/numpy-1.11.2/setup.py", line 339, in setup_package
    write_version_py()
  File "/opt/pydist3/conda-bld/python-numpy_1475583377288/work/numpy-1.11.2/setup.py", line 142, in write_version_py
    a = open(filename, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'numpy/version.py'
```
A traceback for matplotlib 1.5.3:

```
Traceback (most recent call last):
  File "/opt/pydist3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/pydist3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 246, in main
    execute(sys.argv[1:])
  File "/opt/pydist3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 238, in execute
    already_built=None, config=config)
  File "/opt/pydist3/lib/python3.5/site-packages/conda_build/api.py", line 83, in build
    need_source_download=need_source_download, config=config)
  File "/opt/pydist3/lib/python3.5/site-packages/conda_build/build.py", line 1081, in build_tree
    config=recipe_config)
  File "/opt/pydist3/lib/python3.5/site-packages/conda_build/build.py", line 790, in build
    create_info_files(m, pkg_files, config=config, prefix=config.build_prefix)
  File "/opt/pydist3/lib/python3.5/site-packages/conda_build/build.py", line 394, in create_info_files
    entry_point_scripts = get_entry_points(config, m)
  File "/opt/pydist3/lib/python3.5/site-packages/conda_build/build.py", line 352, in get_entry_points
    setup_py_data = jinja_context.load_setup_py_data(config)
  File "/opt/pydist3/lib/python3.5/site-packages/conda_build/jinja_context.py", line 140, in load_setup_py_data
    exec(code, ns, ns)
  File "/opt/pydist3/conda-bld/python-matplotlib_1475587962616/work/matplotlib-1.5.3/setup.py", line 48, in <module>
    del sdist.sdist.make_release_tree
AttributeError: make_release_tree
```

Both packages are building nicely with `conda-build = 2.0.2`.

```console
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.3
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /opt/pydist3  (writable)
    default environment : /opt/pydist3
       envs directories : /opt/pydist3/envs
          package cache : /opt/pydist3/pkgs
           channel URLs : file:///opt/pydist3/conda-bld/linux-64/
                          file:///opt/pydist3/conda-bld/noarch/
            config file : /opt/pydist3/.condarc
           offline mode : False
```

**Comment by sscherfke** [comment]
mysqlclient fails to:
```
Traceback (most recent call last):
  File "/opt/emsconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/emsconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 246, in main
    execute(sys.argv[1:])
  File "/opt/emsconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 238, in execute
    already_built=None, config=config)
  File "/opt/emsconda/lib/python3.5/site-packages/conda_build/api.py", line 83, in build
    need_source_download=need_source_download, config=config)
  File "/opt/emsconda/lib/python3.5/site-packages/conda_build/build.py", line 1081, in build_tree
    config=recipe_config)
  File "/opt/emsconda/lib/python3.5/site-packages/conda_build/build.py", line 784, in build
    entry_point_script_names = get_entry_point_script_names(get_entry_points(config, m))
  File "/opt/emsconda/lib/python3.5/site-packages/conda_build/build.py", line 352, in get_entry_points
    setup_py_data = jinja_context.load_setup_py_data(config)
  File "/opt/emsconda/lib/python3.5/site-packages/conda_build/jinja_context.py", line 140, in load_setup_py_data
    exec(code, ns, ns)
  File "/opt/emsconda/conda-bld/python-mysqlclient_1475588467546/work/mysqlclient-1.3.9/setup.py", line 17, in <module>
    metadata, options = get_config()
  File "/opt/emsconda/conda-bld/python-mysqlclient_1475588467546/work/mysqlclient-1.3.9/setup_posix.py", line 44, in get_config
    libs = mysql_config("libs_r")
  File "/opt/emsconda/conda-bld/python-mysqlclient_1475588467546/work/mysqlclient-1.3.9/setup_posix.py", line 26, in mysql_config
    raise EnvironmentError("%s not found" % (mysql_config.path,))
OSError: mysql_config not found
```

**Comment by msarahan** [comment]
Are your recipes public?

This stuff is happening because conda-build is trying to load information from setup.py.  Unless meta.yaml is actually using this metadata, these errors should not show up.

Further, these errors seem to be showing up because it is failing to import or use some symbol.  This may be an issue with sys.path (which we prepend the root dir containing setup.py to), or perhaps an issue with packages/modules within that folder.

If you can share your recipe, it will help me track this down.

**Comment by sscherfke** [comment]
Our recipies are more or less copies of https://github.com/conda/conda-recipes/ with the major exception that we use `pip install --no-deps .` instead of `python setup.py install`.

Here is our NumPy recipe:

meta.yml:
```yaml
package:
  name: numpy
  version: 1.11.2

source:
  fn: numpy-1.11.2.tar.gz
  url: https://pypi.python.org/packages/16/f5/b432f028134dd30cfbf6f21b8264a9938e5e0f75204e72453af08d67eb0b/numpy-1.11.2.tar.gz
  sha256: 04db2fbd64e2e7c68e740b14402b25af51418fc43a59d9e54172b38b906b0f69

build:
  number: 0

requirements:
  build:
    - python
    - pip
    - openblas

  run:
    - python
    - openblas

test:
  commands:
    - python -c 'import numpy; numpy.arange(3) * 2'

about:
  home: http://www.numpy.org
  license: PSF
```
build.sh
```bash
unset LDFLAGS

$PYTHON -m pip install --no-deps .


# Make sure the linked gfortran libraries are searched for on the RPATH.
if [[ `uname` == 'Darwin' ]]; then
    GFORTRAN_LIB=$(python -c "from os.path import realpath; print(realpath(\"$(gfortran -print-file-name=libgfortran.3.dylib)\"))")
    GCC_LIB=$(python -c "from os.path import realpath; print(realpath(\"$(gfortran -print-file-name=libgcc_s.1.dylib)\"))")
    QUADMATH_LIB=$(python -c "from os.path import realpath; print(realpath(\"$(gfortran -print-file-name=libquadmath.0.dylib)\"))")

    for EACH_FILE in `find ${SP_DIR}/numpy -name "*.so"`;
    do
        install_name_tool -change $GFORTRAN_LIB @rpath/libgfortran.3.dylib $EACH_FILE
        install_name_tool -change $GCC_LIB @rpath/libgcc_s.1.dylib $EACH_FILE
        install_name_tool -change $QUADMATH_LIB @rpath/libquadmath.0.dylib $EACH_FILE
    done
fi
```

**Comment by mpharrigan** [comment]
We're getting

```
Traceback (most recent call last):
  File "/home/travis/miniconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/travis/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 246, in main
    execute(sys.argv[1:])
  File "/home/travis/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 238, in execute
    already_built=None, config=config)
  File "/home/travis/miniconda3/lib/python3.5/site-packages/conda_build/api.py", line 83, in build
    need_source_download=need_source_download, config=config)
  File "/home/travis/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 1081, in build_tree
    config=recipe_config)
  File "/home/travis/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 784, in build
    entry_point_script_names = get_entry_point_script_names(get_entry_points(config, m))
  File "/home/travis/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 352, in get_entry_points
    setup_py_data = jinja_context.load_setup_py_data(config)
  File "/home/travis/miniconda3/lib/python3.5/site-packages/conda_build/jinja_context.py", line 140, in load_setup_py_data
    exec(code, ns, ns)
  File "/home/travis/miniconda3/conda-bld/conda-recipe_1475610024242/work/setup.py", line 10, in <module>
    import numpy as np
ImportError: No module named 'numpy'
```

Recipe here: https://github.com/msmbuilder/msmbuilder/blob/master/devtools/conda-recipe/meta.yaml

I'd rather `setup.py` not be `exec()`-ed at all

**Comment by mpharrigan** [comment]
I think `setup.py` is being called due to the changes in https://github.com/conda/conda-build/pull/1366

If entry_points is present in the `meta.yaml` file, I don't think we should be scraping setup.py

**Comment by snorfalorpagus** [comment]
I think I'm also having this issue.

```
Traceback (most recent call last):
  File "C:\conda\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\conda\lib\site-packages\conda_build\cli\main_build.py", line 246, in main
    execute(sys.argv[1:])
  File "C:\conda\lib\site-packages\conda_build\cli\main_build.py", line 238, in execute
    already_built=None, config=config)
  File "C:\conda\lib\site-packages\conda_build\api.py", line 83, in build
    need_source_download=need_source_download, config=config)
  File "C:\conda\lib\site-packages\conda_build\build.py", line 1081, in build_tree
    config=recipe_config)
  File "C:\conda\lib\site-packages\conda_build\build.py", line 784, in build
    entry_point_script_names = get_entry_point_script_names(get_entry_points(config, m))
  File "C:\conda\lib\site-packages\conda_build\build.py", line 352, in get_entry_points
    setup_py_data = jinja_context.load_setup_py_data(config)
  File "C:\conda\lib\site-packages\conda_build\jinja_context.py", line 140, in load_setup_py_data
    exec(code, ns, ns)
  File "C:\conda\conda-bld\conda-recipe_1475615576577\work\setup.py", line 13, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils
```
The full build log is here: https://ci.appveyor.com/project/snorfalorpagus/pywr/build/1.0.516/job/pgpuuii02a307aj2

This is happening after the actual build (which requires Cython, and works as expected) but before testing begins.

The issue is present in 2.0.3 but not 2.0.2.

`meta.yaml` is here: https://github.com/pywr/pywr/blob/9104a3da9ec233287f36558b93359abdcd7ce483/conda-recipe/meta.yaml

**Comment by msarahan** [comment]
Thanks @snorfalorpagus - that traceback is helpful.  I'll look into this asap.

**Comment by msarahan** [comment]
@mpharrigan, you nailed it.  I agree with your sentiment that entry points should not be scraped where entry points are in meta.yaml. and will make that change.

The bug itself happens because sys.path doesn't have the build environment injected at that point - I think that happens in ```context_processor```.
