### ISSUE TITLE
[Bug] load_setup_py_data creates chicken-egg problem with build requirements

### ISSUE THREAD

**Issue by Korijn** [conda/conda-build#1439]
One of our projects has `cython` code (which makes use of `numpy`). One would expect that adding `cython` and `numpy` to the build requirements in `meta.yml` would suffice, but `conda-build >=2.0` tries to `exec()` `setup.py` in `load_setup_py_data` to allow for some (helpful) `jinja2` parsing in the recipe file. 

However, this means that any imports in `setup.py` will also be evaluated, even though there might be build requirements in there! As such, importing `cython` for the `cythonize` command or `numpy` for `numpy.get_include()` will break the build, even if they're listed in the build requirements.

**The workaround is installing `cython` and `numpy` into our root environment, while they are really build requirements!** This makes dependency management (version pinning specifically) unnecessarily complicated.

Here's an example traceback where we just added the call to `numpy.get_include()` (at this point we already caved in and added `cython` to our root environment...):

```
Traceback (most recent call last):
File "/home/rof/miniconda/bin/conda-build", line 6, in <module>
sys.exit(conda_build.cli.main_build.main())
File "/home/rof/miniconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 246, in main
execute(sys.argv[1:])
File "/home/rof/miniconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 238, in execute
already_built=None, config=config)
File "/home/rof/miniconda/lib/python3.5/site-packages/conda_build/api.py", line 83, in build
need_source_download=need_source_download, config=config)
File "/home/rof/miniconda/lib/python3.5/site-packages/conda_build/build.py", line 1081, in build_tree
config=recipe_config)
File "/home/rof/miniconda/lib/python3.5/site-packages/conda_build/build.py", line 784, in build
entry_point_script_names = get_entry_point_script_names(get_entry_points(config, m))
File "/home/rof/miniconda/lib/python3.5/site-packages/conda_build/build.py", line 352, in get_entry_points
setup_py_data = jinja_context.load_setup_py_data(config)
File "/home/rof/miniconda/lib/python3.5/site-packages/conda_build/jinja_context.py", line 140, in load_setup_py_data
exec(code, ns, ns)
File "/home/rof/miniconda/conda-bld/conda-recipe_1475791099627/work/setup.py", line 4, in <module>
import numpy
ImportError: No module named 'numpy'
```

**Comment by msarahan** [comment]
Thanks for the report.  This should be fixed in #1431 which removes this use of load_setup_py_data.  I'll be tagging a release a little later today.

**Comment by msarahan** [comment]
This should be fixed in 2.0.4, which I've just tagged.  Packages should be available soon.  I'm closing this issue for now, but please reopen it if you still have issues.

**Comment by Korijn** [comment]
Thanks!

**Comment by tajalagawani** [comment]
`sudo apt-get install libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libhdf5-serial-dev protobuf-compiler`
