### ISSUE TITLE
conda build KeyError when calling absolute path

### ISSUE THREAD

**Issue by koverholt** [conda/conda-build#1446]
I'm building a conda package by calling `conda-build` via an absolute path:

```
$ /opt/continuum/anaconda/bin/conda build conda.recipe/
```

But [this code](https://github.com/conda/conda-build/blob/bb128940c63b9f3f015d649df1789be54125d86a/conda_build/build.py#L298-L304) is calling conda from my PATH, which is:

```
$ which conda
/opt/wakari/anaconda/bin/conda
```

and that conda installation in `/opt/wakari` doesn't have `conda-env` installed, therefore I get an error like:

```
$ /opt/continuum/anaconda/bin/conda build conda.recipe/
BUILD START: delay-0.6.0-py27_0
updating index in: /home/vagrant/conda-bld/linux-64
updating index in: /home/vagrant/conda-bld/noarch

The following NEW packages will be INSTALLED:

    openssl:    1.0.2j-0
    pip:        8.1.2-py27_0
    python:     2.7.12-1
    readline:   6.2-2
    setuptools: 27.2.0-py27_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-3

WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
Copying /home/vagrant/delay to /home/vagrant/conda-bld/conda.recipe_1476158063265/work
Package: delay-0.6.0-py27_0
source tree in: /home/vagrant/conda-bld/conda.recipe_1476158063265/work
+ source /opt/continuum/anaconda/bin/activate /home/vagrant/conda-bld/conda.recipe_1476158063265/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
+ /home/vagrant/conda-bld/conda.recipe_1476158063265/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python setup.py install
running install
running bdist_egg
running egg_info
creating delay.egg-info
writing delay.egg-info/PKG-INFO
writing top-level names to delay.egg-info/top_level.txt
writing dependency_links to delay.egg-info/dependency_links.txt
writing manifest file 'delay.egg-info/SOURCES.txt'
reading manifest file 'delay.egg-info/SOURCES.txt'
writing manifest file 'delay.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/delay
copying delay/models.py -> build/lib/delay
copying delay/__init__.py -> build/lib/delay
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/delay
copying build/lib/delay/models.py -> build/bdist.linux-x86_64/egg/delay
copying build/lib/delay/__init__.py -> build/bdist.linux-x86_64/egg/delay
byte-compiling build/bdist.linux-x86_64/egg/delay/models.py to models.pyc
byte-compiling build/bdist.linux-x86_64/egg/delay/__init__.py to __init__.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/delay/data
copying airline_delay_causes.csv -> build/bdist.linux-x86_64/egg/delay/data
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying delay.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying delay.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying delay.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying delay.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying delay.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/delay-0.6.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing delay-0.6.0-py2.7.egg
creating /home/vagrant/conda-bld/conda.recipe_1476158063265/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python2.7/site-packages/delay-0.6.0-py2.7.egg
Extracting delay-0.6.0-py2.7.egg to /home/vagrant/conda-bld/conda.recipe_1476158063265/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python2.7/site-packages
Adding delay 0.6.0 to easy-install.pth file

Installed /home/vagrant/conda-bld/conda.recipe_1476158063265/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python2.7/site-packages/delay-0.6.0-py2.7.egg
Processing dependencies for delay==0.6.0
Finished processing dependencies for delay==0.6.0
compiling .pyc files...
found egg dir: /home/vagrant/conda-bld/conda.recipe_1476158063265/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python2.7/site-packages/delay-0.6.0-py2.7.egg
number of files: 10
Fixing permissions
Using Anaconda Cloud api site https://api.anaconda.org
Traceback (most recent call last):
  File "/opt/continuum/anaconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/continuum/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 243, in main
    execute(sys.argv[1:])
  File "/opt/continuum/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 235, in execute
    already_built=None, config=config)
  File "/opt/continuum/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 83, in build
    need_source_download=need_source_download, config=config)
  File "/opt/continuum/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1087, in build_tree
    config=recipe_config)
  File "/opt/continuum/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 788, in build
    create_info_files(m, pkg_files, config=config, prefix=config.build_prefix)
  File "/opt/continuum/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 389, in create_info_files
    write_about_json(m, config)
  File "/opt/continuum/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 304, in write_about_json
    d['conda_env_version'] = conda_info['conda_env_version']
KeyError: 'conda_env_version'
```

**Comment by msarahan** [comment]
Cool, that was a bad assumption on my part.  I'll make that key optional.  Thanks for reporting.

**Comment by koverholt** [comment]
Won't the info that it's grabbing related to conda and conda-build versions still be wrong if it's calling conda on my path as opposed to the conda that I called via the absolute path? Perhaps that's not a big deal.

**Comment by msarahan** [comment]
Yes, it would be better to get these bits of info from importing the modules and getting their ```__version__``` - dependent on sys.path, rather than PATH.  That is indeed the right way to do it.  Thanks for reiterating.
