### ISSUE TITLE
Conda package install error for adaptfilt

### ISSUE THREAD

**Issue by jaganmohan** [conda/conda-build#1447]
C:\Users\Jagan>conda skeleton pypi adaptfilt
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\Jagan\Anaconda3\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\Jagan\Anaconda3\lib\site-packages\conda_build\main_skeleton.py", line 300, in main
    args_func(args, p)
  File "C:\Users\Jagan\Anaconda3\lib\site-packages\conda_build\main_build.py", line 389, in args_func
    args.func(args, p)
  File "C:\Users\Jagan\Anaconda3\lib\site-packages\conda_build\main_skeleton.py", line 315, in execute
    pypi.main(args, parser)
  File "C:\Users\Jagan\Anaconda3\lib\site-packages\conda_build\pypi.py", line 263, in main
    all_packages = [match["name"] for match in client.search({"name": args.packages}, "or")]
  File "C:\Users\Jagan\Anaconda3\lib\xmlrpc\client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "C:\Users\Jagan\Anaconda3\lib\xmlrpc\client.py", line 1432, in __request
    verbose=self.__verbose
  File "C:\Users\Jagan\Anaconda3\lib\site-packages\conda_build\pypi.py", line 233, in request
    return self.parse_response(resp)
  File "C:\Users\Jagan\Anaconda3\lib\site-packages\conda_build\pypi.py", line 242, in parse_response
    return u.close()
  File "C:\Users\Jagan\Anaconda3\lib\xmlrpc\client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -32700: 'parse error; not well formed'>

C:\Users\Jagan>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : C:\Users\Jagan\Anaconda3  (writable)
  default environment : C:\Users\Jagan\Anaconda3
     envs directories : C:\Users\Jagan\Anaconda3\envs
        package cache : C:\Users\Jagan\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by msarahan** [comment]
Please update conda build and try again. 2.0.4 is the current version.

**Comment by msarahan** [comment]
Closing due to inactivity.  Please reopen or open a new issue if you are still having problems after updating.
