### ISSUE TITLE
conda build --check fails when using source_files directive

### ISSUE THREAD

**Issue by Hornswoggles** [conda/conda-build#1476]
Using conda-build 2.0.6
Reproduce by creating a recipe with a source_files directive

```
conda` build --check recipe
Traceback (most recent call last):
  File "REDACTED/miniconda2/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "REDACTED/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 242, in main
    execute(sys.argv[1:])
  File "REDACTED/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 227, in execute
    action(m, config)
  File "REDACTED/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 181, in check_action
    return api.check(metadata.path, config=config)
  File "REDACTED/miniconda2/lib/python2.7/site-packages/conda_build/api.py", line 62, in check
    return metadata.check_fields()
  File "REDACTED/miniconda2/lib/python2.7/site-packages/conda_build/metadata.py", line 536, in check_fields
    (section, key))
ValueError: in section u'test': unknown key u'source_files'
```

**Comment by msarahan** [comment]
Sorry for the delay here.  Have you tried the latest conda-build (2.0.10)?  Is this still an issue?  FWIW, we use this for conda-build itself, so it should be reasonably well tested.

**Comment by Hornswoggles** [comment]
Yes this is still an issue as of 
```
$ conda build -V
conda-build 2.0.11
```

**Comment by msarahan** [comment]
OK, thanks.  I will investigate this before the next bug-fix release.
