### ISSUE TITLE
assertion error in script post.py

### ISSUE THREAD

**Issue by loraine-gueguen** [conda/conda-build#1481]
Hi,

I have the following error message when executing conda-build for recipe https://github.com/bioconda/bioconda-recipes/tree/master/recipes/parafly:

`Traceback (most recent call last):
  File "/tmp/mc2/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/tmp/mc2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 242, in main
    execute(sys.argv[1:])
  File "/tmp/mc2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 234, in execute
    already_built=None, config=config)
  File "/tmp/mc2/lib/python2.7/site-packages/conda_build/api.py", line 77, in build
    need_source_download=need_source_download, config=config)
  File "/tmp/mc2/lib/python2.7/site-packages/conda_build/build.py", line 1099, in build_tree
    config=recipe_config)
  File "/tmp/mc2/lib/python2.7/site-packages/conda_build/build.py", line 791, in build
    croot=config.croot)
  File "/tmp/mc2/lib/python2.7/site-packages/conda_build/post.py", line 430, in post_build
    mk_relative(m, f, prefix)
  File "/tmp/mc2/lib/python2.7/site-packages/conda_build/post.py", line 389, in mk_relative
    mk_relative_linux(f, prefix=prefix, rpaths=m.get_value('build/rpaths', ['lib']))
  File "/tmp/mc2/lib/python2.7/site-packages/conda_build/post.py", line 362, in mk_relative_linux
    rel_ours, rel_stdlib, f, rpath)
AssertionError: utils.relative ./lib and relpath lib disagree for ParaFly, lib
`

Looks like the assertion `assert rel_ours == rel_stdlib` in post.py should pass but did not because of `./`
Am I right?

Loraine

**Comment by loraine-gueguen** [comment]
seems linked to issue #1411

**Comment by loraine-gueguen** [comment]
I have added `binary_relocation: False` the meta.yml like in https://github.com/bioconda/bioconda-recipes/pull/2686. It has solved the issue.
But not sure it is a good practice.

**Comment by msarahan** [comment]
Thanks for posting that workaround.  We'll try to have a proper fix soon.
