### ISSUE TITLE
conda info fails on assert if CONDA_BLD_PATH is defined

### ISSUE THREAD

**Issue by afeblot** [conda/conda-build#1485]
Is it forbidden to run conda build with CONDA_BLD_PATH defined, while using the root env?
```
    Traceback (most recent call last):
      File "/raid1/condapoc/root/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/raid1/condapoc/root/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/raid1/condapoc/root/lib/python2.7/site-packages/conda/cli/main_info.py", line 225, in execute
        channels = list(prioritize_channels(channels).keys())
      File "/raid1/condapoc/root/lib/python2.7/site-packages/conda/models/channel.py", line 380, in prioritize_channels
        channel = Channel(chn)
      File "/raid1/condapoc/root/lib/python2.7/site-packages/conda/models/channel.py", line 161, in __call__
        c = Channel.from_value(value)
      File "/raid1/condapoc/root/lib/python2.7/site-packages/conda/models/channel.py", line 221, in from_value
        if value in context.custom_multichannels:
      File "/raid1/condapoc/root/lib/python2.7/site-packages/conda/_vendor/auxlib/decorators.py", line 265, in new_fget
        cache[inner_attname] = func(self)
      File "/raid1/condapoc/root/lib/python2.7/site-packages/conda/base/context.py", line 254, in custom_multichannels
        'local': (self.local_build_root_channel,),
      File "/raid1/condapoc/root/lib/python2.7/site-packages/conda/_vendor/auxlib/decorators.py", line 265, in new_fget
        cache[inner_attname] = func(self)
      File "/raid1/condapoc/root/lib/python2.7/site-packages/conda/base/context.py", line 246, in local_build_root_channel
        assert name == 'conda-bld'
    AssertionError
```

**Comment by msarahan** [comment]
Thanks for reporting.  This seems like a bug in conda, not conda-build.  It appears to me that it has a hard-coded assumption that the local build root channel will always be named conda-bld, which is not a valid assumption.  I'm going to move this issue to the conda issue tracker.

**Comment by msarahan** [comment]
Issue moved to [conda/conda #3741](https://github.com/conda/conda/issues/3741) via [**ZenHub**](https://www.zenhub.com/)
