### ISSUE TITLE
filelock.Timeout while building a single recipe

### ISSUE THREAD

**Issue by ocefpaf** [conda/conda-build#1494]
@msarahan I am getting a odd file lock timeout error when building [this](https://github.com/ioos/conda-recipes/tree/master/recipes/rasterio) recipe with `conda-build=2`:

```
Fixing permissions
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build-all", line 11, in <module>
    load_entry_point('conda-build-all==1.0.0', 'console_scripts', 'conda-build-all')()
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/cli.py", line 90, in main
    b.main()
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/builder.py", line 263, in main
    built_dist_location = self.build(meta, build_config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/builder.py", line 200, in build
    conda_build.api.build(meta.meta, config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/api.py", line 83, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 1097, in build_tree
    test(metadata, config=recipe_config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 902, in test
    create_files(tmp_dir, m, config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/create_test.py", line 53, in create_files
    copy_into(path, join(dir_path, fn), config.timeout)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/utils.py", line 107, in copy_into
    lock.acquire(timeout=timeout)
  File "/opt/conda/lib/python3.5/site-packages/filelock.py", line 243, in acquire
    raise Timeout(self._lock_file)
filelock.Timeout: The file lock '/conda-recipes/recipes/rasterio/test_data/.conda_lock' could not be acquired.
```

The actual error there should be due to the missing file `test_data/test.tif`` that did not exist in the first commit. `conda-build=1` correctly complains about the missing file with:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/conda-recipes/recipes/rasterio/test_data/test.tif'
```

**Comment by msarahan** [comment]
Yes, I'm also seeing this.  Trying to figure it out.  Thanks for the extra bit about FileNotFound - that should help.

**Comment by ocefpaf** [comment]
If you are already on it feel free to close this as, for my goals, I only had to re-add the proper test file :grimacing:

**Comment by msarahan** [comment]
Nah, it's a real problem.  Needs a solution.

**Comment by msarahan** [comment]
@ocefpaf if you have time, do you mind trying out a checkout of master?  I think it's ready for a release.  How hard is it for you to use a master installation, rather than a conda package?

**Comment by ocefpaf** [comment]
> How hard is it for you to use a master installation, rather than a conda package?

No problem on Linux it is easy and I will start testing right away.

I can only do `OS X` and `AppVeyor` with a package though as I would be using CIs. But I can bootstrap a build on those as well if we do not have a canary release. Reporting back soon...

**Comment by ocefpaf** [comment]
This issue is gone on Linux with latest `master`. I removed the `test_data` on purpose and now I get the right error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/conda-recipes/recipes/rasterio/test_data/test.tif'
```

Thanks @msarahan!
