### ISSUE TITLE
Memory error on conda builds

### ISSUE THREAD

**Issue by SylvainCorlay** [conda/conda-build#1514]
An error I have seen occur on a number of recipes is the following: A memory error in `ruamel_yaml`

```bash
# All requested packages already installed.
# packages in environment at C:\conda:
#
conda                     4.1.12                   py27_0    conda-forge
Traceback (most recent call last):
  File "C:\conda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\conda\lib\site-packages\conda\cli\main.py", line 61, in main
    from conda.cli import conda_argparse
  File "C:\conda\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\conda\lib\site-packages\conda\cli\common.py", line 12, in <module>
    from ..config import (envs_dirs, default_prefix, platform, update_dependencies,
  File "C:\conda\lib\site-packages\conda\config.py", line 475, in <module>
    load_condarc(rc_path)
  File "C:\conda\lib\site-packages\conda\config.py", line 391, in load_condarc
    rc = load_condarc_(path)
  File "C:\conda\lib\site-packages\conda\config.py", line 129, in load_condarc_
    return yaml_load(f) or {}
  File "C:\conda\lib\site-packages\conda\utils.py", line 296, in yaml_load
    yaml = get_yaml()
  File "C:\conda\lib\site-packages\conda\utils.py", line 43, in __call__
    value = self.func(*args, **kw)
  File "C:\conda\lib\site-packages\conda\utils.py", line 282, in get_yaml
    import ruamel_yaml as yaml
  File "C:\conda\lib\site-packages\ruamel_yaml\__init__.py", line 13, in <module>
    from .cyaml import *                               # NOQA
  File "C:\conda\lib\site-packages\ruamel_yaml\cyaml.py", line 5, in <module>
    from ruamel_yaml.ext._ruamel_yaml import CParser, CEmitter
  File "ruamel_yaml\ext\_ruamel_yaml.pyx", line 18, in init ruamel_yaml.ext._ruamel_yaml (ruamel_yaml/ext/_ruamel_yaml.c:23219)
  File "C:\conda\lib\site-packages\ruamel_yaml\reader.py", line 58, in <module>
    class Reader(object):
  File "C:\conda\lib\site-packages\ruamel_yaml\reader.py", line 152, in Reader
    u'[^\x09\x0A\x0D\x20-\x7E\x85\xA0-\uD7FF\uE000-\uFFFD]')
  File "C:\conda\lib\re.py", line 194, in compile
    return _compile(pattern, flags)
  File "C:\conda\lib\re.py", line 249, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\conda\lib\sre_compile.py", line 576, in compile
    code = _code(p, flags)
  File "C:\conda\lib\sre_compile.py", line 558, in _code
    _compile_info(code, p, flags)
  File "C:\conda\lib\sre_compile.py", line 536, in _compile_info
    _compile_charset(charset, flags, code)
  File "C:\conda\lib\sre_compile.py", line 232, in _compile_charset
    flags & SRE_FLAG_UNICODE):
  File "C:\conda\lib\sre_compile.py", line 274, in _optimize_charset
    r = range(av[0], av[1]+1)
MemoryError
```

**Comment by msarahan** [comment]
Yikes.  This seems like it might have something to do with ruamel_yaml (which conda uses) vs. pyyaml, which conda-build uses.  I can certainly try switching conda-build to ruamel_yaml.  My guess is that the C extension is probably commonly named between the two, but may now have subtle, incompatible diffferences.  Conda-build is probably loading its pyyaml extension first, and then the traceback here indicates that conda's ruamel_yaml is incompatible.

@kalefranz are you aware of any binary incompatibilities that may have cropped up in recent ruamel_yaml versions?
