### ISSUE TITLE
conda-build broke by conda-build update 2.0.6 - 2.0.8 (copying to test-tmp) (with workaround)

### ISSUE THREAD

**Issue by BjornFJohansson** [conda/conda-build#1520]
Hi, i just updated conda & conda-build. Sfter update I have these versions
```
conda                     4.2.12                   py35_0    defaults
conda-build               2.0.8                    py35_0    defaults
conda-env                 2.6.0                         0    defaults
```

conda build then broke with this traceback:
```
found egg dir: /home/bjorn/anaconda3/conda-bld/pydna_1478761130485/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.5/site-packages/pydna-1.0.2-py3.5.egg
number of files: 48
Fixing permissions
Fixing permissions
updating index in: /home/bjorn/anaconda3/conda-bld/linux-64
updating: pydna-1.0.2-py35_66.tar.bz2
Traceback (most recent call last):
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/utils.py", line 120, in copy_into
    shutil.copy2(src, dst_fn)
  File "/home/bjorn/anaconda3/lib/python3.5/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/bjorn/anaconda3/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bjorn/anaconda3/conda-bld/pydna_1478761130485/test_tmp/pydna/amplify.py'
```
my meta.yaml had this test section:
```
test:
  requires:
    - nose
  imports:
    - pydna
  source_files:
    - pydna/*.py
    - pydna/py_rstr_max/*.py
    - tests/*.*
```
Which I switched for this:
```
test:
  requires:
    - nose
  imports:
    - pydna
  source_files:
    - tests
    - pydna
```
The former version was perhaps wrong, but it used to work in the previous version (I believe it was 2.0.6 of conda build and conda 4.2.9).

I posted this issue just as a heads up.

**Comment by msarahan** [comment]
Thanks for posting this.  I think this is addressed in https://github.com/conda/conda-build/pull/1511 - the issue being that intermediate folders were being created for copying directories, but not necessarily for copying files (which the glob patterns were doing).
