### ISSUE TITLE
Jinja doesn't work with name or license_family

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1537]
If I try something like the following...

```yaml
{% set data = load_setup_py_data() %}
...
about:
  ...
  license: {{ data.get("license") }}
  license_family: {{ data.get("license").split()[0] }}
```

I get the following error.

```python
Traceback (most recent call last):
  File "/zopt/conda2/bin/conda-render", line 6, in <module>
    sys.exit(conda_build.cli.main_render.main())
  File "/zopt/conda2/lib/python2.7/site-packages/conda_build/cli/main_render.py", line 141, in main
    return execute(sys.argv[1:])
  File "/zopt/conda2/lib/python2.7/site-packages/conda_build/cli/main_render.py", line 130, in execute
    metadata, _, _ = render_recipe(args.recipe, no_download_source=args.no_source, config=config)
  File "/zopt/conda2/lib/python2.7/site-packages/conda_build/render.py", line 152, in render_recipe
    m = MetaData(recipe_dir, config=config)
  File "/zopt/conda2/lib/python2.7/site-packages/conda_build/metadata.py", line 421, in __init__
    self.parse_again(config=config, permit_undefined_jinja=True)
  File "/zopt/conda2/lib/python2.7/site-packages/conda_build/metadata.py", line 447, in parse_again
    config=config, path=self.meta_path)
  File "/zopt/conda2/lib/python2.7/site-packages/conda_build/metadata.py", line 173, in parse
    ensure_valid_license_family(res)
  File "/zopt/conda2/lib/python2.7/site-packages/conda_build/license_family.py", line 108, in ensure_valid_license_family
    (license_family, comma_join(sorted(allowed_license_families)))))
RuntimeError: about/license_family '' not allowed. Allowed families are AGPL,
APACHE, BSD, GPL, GPL2, GPL3, LGPL, MIT, NONE, OTHER, PROPRIETARY,
PSF, and PUBLICDOMAIN.
```

However, if I make the following change...

```yaml
{% set data = load_setup_py_data() %}
...
about:
  ...
  license: {{ data.get("license") }}
extra:
  license_family: {{ data.get("license").split()[0] }}
```

...and run `conda render <recipe_dir>`. I get the following...

```yaml
{% set data = load_setup_py_data() %}
...
about:
  ...
  license: BSD 3-Clause
extra:
  license_family: BSD
```

Here is my environment information.

```
$ conda list -n root 
# packages in environment at /zopt/conda2:
#
Using Anaconda API: https://api.anaconda.org
appnope                   0.1.0                    py27_0    defaults
conda-build               2.0.10                   py27_0    defaults
anaconda-client           1.5.1                    py27_0    conda-forge
anaconda-verify           1.2.0                    py27_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                    py27_0    conda-forge
ca-certificates           2016.9.26                     0    conda-forge
certifi                   2016.9.26                py27_0    conda-forge
clyent                    1.2.1                    py27_0    conda-forge
conda                     4.1.12                   py27_0    conda-forge
conda-build-all           1.0.0                    py27_0    conda-forge
conda-env                 2.5.2                    py27_0    conda-forge
conda-execute             0.7.0                    py27_1    conda-forge
constructor               1.3.4                    py27_0    conda-forge
contextlib2               0.5.3                    py27_0    conda-forge
coverage                  3.7.1                    py27_0    conda-forge
curl                      7.49.1                        1    conda-forge
decorator                 4.0.10                   py27_0    conda-forge
enum34                    1.1.6                    py27_1    conda-forge
expat                     2.1.0                         2    conda-forge
filelock                  2.0.6                    py27_0    conda-forge
funcsigs                  1.0.2                    py27_0    conda-forge
gitdb                     0.6.4                    py27_0    conda-forge
gitpython                 2.0.8                    py27_1    conda-forge
ipython                   5.1.0                    py27_1    conda-forge
ipython_genutils          0.1.0                    py27_0    conda-forge
jinja2                    2.8                      py27_1    conda-forge
libconda                  4.0.0                    py27_0    conda-forge
markupsafe                0.23                     py27_0    conda-forge
mock                      2.0.0                    py27_0    conda-forge
ncurses                   5.9                           9    conda-forge
nose                      1.3.7                    py27_2    conda-forge
openssl                   1.0.2h                        2    conda-forge
pathlib2                  2.1.0                    py27_0    conda-forge
pbr                       1.10.0                   py27_0    conda-forge
pexpect                   4.2.0                    py27_1    conda-forge
pickleshare               0.7.3                    py27_0    conda-forge
pip                       8.1.2                    py27_0    conda-forge
pkginfo                   1.2.1                    py27_0    conda-forge
prompt_toolkit            1.0.8                    py27_0    conda-forge
psutil                    4.3.0                    py27_0    conda-forge
ptyprocess                0.5.1                    py27_0    conda-forge
pycosat                   0.6.1                    py27_0    conda-forge
pycrypto                  2.6.1                    py27_0    conda-forge
pygithub                  1.29                     py27_0    conda-forge
pygments                  2.1.3                    py27_1    conda-forge
python                    2.7.12                        1    conda-forge
python-dateutil           2.5.3                    py27_0    conda-forge
pytz                      2016.7                   py27_0    conda-forge
pyyaml                    3.11                     py27_0    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.11.1                   py27_0    conda-forge
ruamel.ordereddict        0.4.6                    py27_0    conda-forge
ruamel.yaml               0.11.11                  py27_1    conda-forge
ruamel_yaml               0.11.7                   py27_0    conda-forge
setuptools                27.3.1                   py27_0    conda-forge
simplegeneric             0.8.1                    py27_0    conda-forge
six                       1.10.0                   py27_1    conda-forge
smmap                     0.9.0                    py27_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        0    conda-forge
traitlets                 4.3.1                    py27_0    conda-forge
wcwidth                   0.1.7                    py27_0    conda-forge
wheel                     0.29.0                   py27_0    conda-forge
yaml                      0.1.6                         0    conda-forge
zlib                      1.2.8                         3    conda-forge
conda-verify              2.0.0                    py27_0    defaults
python.app                1.2                      py27_4    defaults
```

Edit: Should add that I see the same behavior when using jinja with `name`.

**Comment by msarahan** [comment]
Yep, the license family stuff is being done before rendering, but it should be done after.  I'll try to work this into a future release.

I think it would be simpler if you just remove the license_family entry from your recipe, though.  The whole point of that addition ( #1495 ) was to fix and make the "guessed" categories consistent.  There's quite a bit more logic there than your naive split-and-take-the-first approach.

**Comment by jakirkham** [comment]
Ok sounds good.

Yep, I completely agree. Though one should also be able to add `license_family` as a keyword argument to `setup`, which would be a bit more reasonable.

Any thoughts on the other point? Namely using Jinja for the `name`? Is that even a reasonable thing to ask for?

**Comment by msarahan** [comment]
There are a few things that are undesirably special cased in how they are handled.  name is one of them.  I don't like it, but I'm not prepared to spend the time to fix it right now.  If you want to change it, I'd take any reasonable PR.
