### ISSUE TITLE
Fail to build R package from CRAN

### ISSUE THREAD

**Issue by Victorcxq** [conda/conda-build#1550]
Fail to execute conda skeleton command. Info see below:

    conda skeleton cran highfrequency
    An unexpected error has occurred, please consider sending the following traceback to the conda GitHub issue tracker at:

        https://github.com/conda/conda-build/issues

    Include the output of the command 'conda info' in your report.

    Traceback (most recent call last):
       File "/Users/Vicky_chen/anaconda/bin/conda-skeleton", line 5, in <module>
          sys.exit(main())
       File "/Users/Vicky_chen/anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py",       line 298, in main
          args_func(args, p)
       File "/Users/Vicky_chen/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 493, in args_func 
          args.func(args, p)
       File "/Users/Vicky_chen/anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py",      line 302, in execute
          import conda_build.pypi as pypi
       File "/Users/Vicky_chen/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 30, in     <module>
          from conda.config import get_proxy_servers
       ImportError: cannot import name get_proxy_servers

And attached conda info:

               platform : osx-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 0+unknown
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/Vicky_chen/anaconda  (writable)
    default environment : /Users/Vicky_chen/anaconda
       envs directories : /Users/Vicky_chen/anaconda/envs
          package cache : /Users/Vicky_chen/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/Vicky_chen/.condarc
           offline mode : False`

**Comment by msarahan** [comment]
What version of conda-build do you have?  How did you install conda-build?

**Comment by msarahan** [comment]
closing due to inactivity.  Please reopen or file a new issue if you have more information.
