### ISSUE TITLE
conda skeleton pypi nbval fails because file lock '/home/.../anaconda3/conda-bld/linux-64/.conda_lock' could not be acquired.

### ISSUE THREAD

**Issue by BjornFJohansson** [conda/conda-build#1564]
conda clean --lock does not help.
thanks!

```bjorn@bjorn-ThinkPad-T450s:~/Desktop/python_packages$ root
(root) bjorn@bjorn-ThinkPad-T450s:~/Desktop/python_packages$ conda update conda
Fetching package metadata ...........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/bjorn/anaconda3:
#
conda                     4.2.13                   py35_0  
(root) bjorn@bjorn-ThinkPad-T450s:~/Desktop/python_packages$ conda update conda-build
Fetching package metadata ...........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/bjorn/anaconda3:
#
conda-build               2.0.11                   py35_0  
(root) bjorn@bjorn-ThinkPad-T450s:~/Desktop/python_packages$ conda update conda-env
Fetching package metadata ...........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/bjorn/anaconda3:
#
conda-env                 2.6.0                         0  
(root) bjorn@bjorn-ThinkPad-T450s:~/Desktop/python_packages$ bjorn3
(bjorn3) bjorn@bjorn-ThinkPad-T450s:~/Desktop/python_packages$ conda clean --lock
(bjorn3) bjorn@bjorn-ThinkPad-T450s:~/Desktop/python_packages$ conda skeleton pypi nbval
Warning, the following versions were found for nbval
0.3.2
0.3.4
0.3.5
0.3.6
Using 0.3.6
Use --version to specify a different version.
Using url https://pypi.python.org/packages/6f/7f/03affe0888eb77d4cbd960b642f3943b6ab110e77a498480451610ae8e53/nbval-0.3.6.tar.gz (8 KB) for nbval.
Downloading nbval
Using cached download
Unpacking nbval...
done
working in /tmp/tmpnpf5g51econda_skeleton_nbval-0.3.6.tar.gz
Traceback (most recent call last):
  File "/home/bjorn/anaconda3/bin/conda-skeleton", line 6, in <module>
    sys.exit(conda_build.cli.main_skeleton.main())
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    api.skeletonize(package, args.repo, config=config)
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/api.py", line 220, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 407, in skeletonize
    noprompt, packages, config=config, setup_options=setup_options)
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 665, in get_package_metadata
    config=config)
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 925, in get_pkginfo
    run_setuppy(src_dir, tempdir, python_version, config=config, setup_options=setup_options)
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 958, in run_setuppy
    config=config)
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/build.py", line 627, in create_env
    update_index(folder, config=config, lock=lock, could_be_mirror=False)
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/index.py", line 81, in update_index
    with lock:
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/filelock.py", line 297, in __enter__
    self.acquire()
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/filelock.py", line 243, in acquire
    raise Timeout(self._lock_file)
filelock.Timeout: The file lock '/home/bjorn/anaconda3/conda-bld/linux-64/.conda_lock' could not be acquired.
(bjorn3) bjorn@bjorn-ThinkPad-T450s:~/Desktop/python_packages$ ls -a /home/bjorn/anaconda3/conda-bld/linux-64/
.   .conda_lock  pydna-1.0.5a14-py35_0.tar.bz2  pydna-1.1.1-py35_5.tar.bz2  repodata.json.bz2
..  .index.json  pydna-1.1.1a13-py35_7.tar.bz2  repodata.json
(bjorn3) bjorn@bjorn-ThinkPad-T450s:~/Desktop/python_packages$ rm /home/bjorn/anaconda3/conda-bld/linux-64/.conda_lock 
(bjorn3) bjorn@bjorn-ThinkPad-T450s:~/Desktop/python_packages$ conda skeleton pypi nbval
Warning, the following versions were found for nbval
0.3.2
0.3.4
0.3.5
0.3.6
Using 0.3.6
Use --version to specify a different version.
Using url https://pypi.python.org/packages/6f/7f/03affe0888eb77d4cbd960b642f3943b6ab110e77a498480451610ae8e53/nbval-0.3.6.tar.gz (8 KB) for nbval.
Downloading nbval
Using cached download
Unpacking nbval...
done
working in /tmp/tmpmj4n0gnnconda_skeleton_nbval-0.3.6.tar.gz
Traceback (most recent call last):
  File "/home/bjorn/anaconda3/bin/conda-skeleton", line 6, in <module>
    sys.exit(conda_build.cli.main_skeleton.main())
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    api.skeletonize(package, args.repo, config=config)
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/api.py", line 220, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 407, in skeletonize
    noprompt, packages, config=config, setup_options=setup_options)
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 665, in get_package_metadata
    config=config)
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 925, in get_pkginfo
    run_setuppy(src_dir, tempdir, python_version, config=config, setup_options=setup_options)
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 958, in run_setuppy
    config=config)
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/build.py", line 627, in create_env
    update_index(folder, config=config, lock=lock, could_be_mirror=False)
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/conda_build/index.py", line 81, in update_index
    with lock:
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/filelock.py", line 297, in __enter__
    self.acquire()
  File "/home/bjorn/anaconda3/lib/python3.5/site-packages/filelock.py", line 243, in acquire
    raise Timeout(self._lock_file)
filelock.Timeout: The file lock '/home/bjorn/anaconda3/conda-bld/noarch/.conda_lock' could not be acquired.
(bjorn3) bjorn@bjorn-ThinkPad-T450s:~/Desktop/python_packages$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.11
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/bjorn/anaconda3  (writable)
    default environment : /home/bjorn/anaconda3/envs/bjorn3
       envs directories : /home/bjorn/anaconda3/envs
          package cache : /home/bjorn/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/BjornFJohansson/linux-64
                          https://conda.anaconda.org/BjornFJohansson/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /home/bjorn/.condarc
           offline mode : False

(bjorn3) bjorn@bjorn-ThinkPad-T450s:~/Desktop/python_packages$ conda list
# packages in environment at /home/bjorn/anaconda3/envs/bjorn3:
#
_license                  1.1                      py35_1  
alabaster                 0.7.9                    py35_0  
anaconda                  custom                   py35_0  
anaconda-clean            1.0.0                    py35_0  
anaconda-client           1.5.5                    py35_0  
appdirs                   1.4.0                    py35_0  
argcomplete               1.0.0                    py35_1  
args                      0.1.0                    py35_0    conda-forge
arrow                     0.8.0                    py35_0    conda-forge
astroid                   1.4.7                    py35_0  
astropy                   1.2.1               np111py35_0  
babel                     2.3.4                    py35_0  
backports                 1.0                      py35_0  
backports.shutil_get_terminal_size 1.0.0                    py35_0    conda-forge
beautifulsoup4            4.5.1                    py35_0  
binaryornot               0.4.0                    py35_1    conda-forge
biopython                 1.68                np111py35_0  
bitarray                  0.8.1                    py35_0  
boto                      2.42.0                   py35_0  
bottleneck                1.1.0               np111py35_0  
cairo                     1.12.18                       6  
cffi                      1.7.0                    py35_0  
chardet                   2.3.0                    py35_0  
chest                     0.2.3                    py35_0  
click                     6.6                      py35_0  
clint                     0.5.1                    py35_0    conda-forge
cloudpickle               0.2.1                    py35_0  
clyent                    1.2.2                    py35_0  
colorama                  0.3.7                    py35_0  
configobj                 5.0.6                    py35_0  
contextlib2               0.5.3                    py35_0  
cookiecutter              1.4.0                    py35_1    conda-forge
coverage                  4.0.3                    py35_0  
cryptography              1.5                      py35_0  
curl                      7.49.0                        1  
cycler                    0.10.0                   py35_0  
cython                    0.24.1                   py35_0  
cytoolz                   0.8.0                    py35_0  
datashape                 0.5.2                    py35_0  
dbus                      1.10.10                       0  
decorator                 4.0.10                   py35_0  
dill                      0.2.5                    py35_0  
docopt                    0.6.2                    py35_0  
docutils                  0.12                     py35_2  
dropbox                   6.9.0                     <pip>
dynd-python               0.7.2                    py35_0  
entrypoints               0.2.2                    py35_0  
et_xmlfile                1.0.1                    py35_0  
expat                     2.1.0                         0  
fastcache                 1.0.2                    py35_1  
filelock                  2.0.6                    py35_0  
flask                     0.11.1                   py35_0  
flask-cors                2.1.2                    py35_0  
fontconfig                2.11.1                        6  
freetype                  2.5.5                         1  
future                    0.15.2                   py35_0  
get_terminal_size         1.0.0                    py35_0  
gevent                    1.1.2                    py35_0  
glib                      2.43.0                        1  
gmp                       6.1.1                         0    conda-forge
greenlet                  0.4.10                   py35_0  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.6.0               np111py35_2  
harfbuzz                  0.9.39                        1  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py35_1  
icu                       54.1                          0  
idna                      2.1                      py35_0  
imagesize                 0.7.1                    py35_0  
ipykernel                 4.5.0                    py35_0  
ipython                   5.1.0                    py35_0  
ipython_genutils          0.1.0                    py35_0  
ipywidgets                5.2.2                    py35_2    conda-forge
itsdangerous              0.24                     py35_0  
jbig                      2.1                           0  
jdcal                     1.2                      py35_1  
jedi                      0.9.0                    py35_1  
jinja2                    2.8                      py35_1  
jinja2-time               0.1.0                    py35_0    conda-forge
jpeg                      8d                            2  
jsonschema                2.5.1                    py35_0  
jupyter                   1.0.0                    py35_3  
jupyter_client            4.4.0                    py35_0  
jupyter_console           5.0.0                    py35_0  
jupyter_core              4.2.0                    py35_0  
jupyterlab                0.4.1                    py35_0    conda-forge
lazy-object-proxy         1.2.1                    py35_0  
libdynd                   0.7.2                         0  
libffi                    3.2.1                         0  
libgcc                    4.8.5                         2  
libgfortran               3.0.0                         1  
libpng                    1.6.22                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         2  
libxcb                    1.12                          0  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
llvmlite                  0.13.0                   py35_0  
locket                    0.2.0                    py35_1  
lxml                      3.6.4                    py35_0  
markdown                  2.6.7                    py35_0  
markupsafe                0.23                     py35_2  
matplotlib                1.5.3               np111py35_0  
mistune                   0.7.3                    py35_0  
mkl                       11.3.3                        0  
mkl-service               1.1.2                    py35_2  
mpldatacursor             0.6.2                         0    BjornFJohansson
mpmath                    0.19                     py35_1  
multipledispatch          0.4.8                    py35_0  
nb_conda                  2.0.0                    py35_0    conda-forge
nb_conda_kernels          2.0.0                    py35_0    conda-forge
nbconvert                 4.2.0                    py35_0  
nbformat                  4.1.0                    py35_0  
nbpresent                 3.0.2                    py35_1    conda-forge
nbval                     0.3.6                     <pip>
networkx                  1.11                     py35_0  
nltk                      3.2.1                    py35_0  
notebook                  4.2.3                    py35_0  
numba                     0.28.1              np111py35_0  
numexpr                   2.6.1               np111py35_0  
numpy                     1.11.1                   py35_0  
numpydoc                  0.6.0                    py35_0  
odo                       0.5.0                    py35_1  
openpyxl                  2.3.2                    py35_0  
openssl                   1.0.2j                        0  
ordered-set               2.0.1                    py35_0    conda-forge
pandas                    0.18.1              np111py35_0  
pandoc                    1.18                          0    conda-forge
partd                     0.3.6                    py35_0  
patchelf                  0.9                           0  
path.py                   8.2.1                    py35_0  
pathlib2                  2.1.0                    py35_0  
patsy                     0.4.1                    py35_0  
pdfkit                    0.5.0                    py35_0    bioconda
pep8                      1.7.0                    py35_0  
pexpect                   4.0.1                    py35_0  
pickleshare               0.7.4                    py35_0  
pillow                    3.3.1                    py35_0  
pint                      0.7.2                    py35_0    conda-forge
pip                       9.0.1                    py35_0  
pixman                    0.32.6                        0  
pkginfo                   1.3.2                    py35_0  
ply                       3.9                      py35_0  
poyo                      0.3.0                    py35_0    conda-forge
prettytable               0.7.2                    py35_0    conda-forge
prompt_toolkit            1.0.3                    py35_0  
psutil                    4.3.1                    py35_0  
ptyprocess                0.5.1                    py35_0  
py                        1.4.31                   py35_0  
pyasn1                    0.1.9                    py35_0  
pycosat                   0.6.1                    py35_1  
pycparser                 2.14                     py35_1  
pycrypto                  2.6.1                    py35_4  
pycurl                    7.43.0                   py35_0  
pyflakes                  1.3.0                    py35_0  
pygments                  2.1.3                    py35_0  
pyinstaller               3.2.3                    py35_0    acellera
pylint                    1.5.4                    py35_1  
pyopenssl                 16.0.0                   py35_0  
pypandoc                  1.3.3                    py35_0    conda-forge
pyparsing                 2.1.4                    py35_0  
pyqt                      5.6.0                    py35_0  
pytables                  3.2.3.1             np111py35_0  
pytest                    3.0.3                    py35_0  
pytest-cov                2.4.0                    py35_0    conda-forge
python                    3.5.2                         0  
python-dateutil           2.5.3                    py35_0  
pytz                      2016.6.1                 py35_0  
pyyaml                    3.12                     py35_0  
pyzmq                     15.4.0                   py35_0  
qt                        5.6.0                         1  
qtawesome                 0.3.3                    py35_0  
qtconsole                 4.2.1                    py35_1  
qtpy                      1.1.2                    py35_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py35_0  
reportlab                 3.3.0                    py35_0  
requests                  2.12.1                   py35_0  
requests-toolbelt         0.7.0                    py35_0    conda-forge
rope                      0.9.4                    py35_1  
ruamel_yaml               0.11.7                   py35_0  
scikit-image              0.12.3              np111py35_1  
scikit-learn              0.17.1              np111py35_2  
scipy                     0.18.1              np111py35_0  
setuptools                27.2.0                   py35_0  
sh                        1.11                     py35_0  
simplegeneric             0.8.1                    py35_1  
singledispatch            3.4.0.3                  py35_0  
sip                       4.18                     py35_0  
six                       1.10.0                   py35_0  
six                       1.10.0                    <pip>
snowballstemmer           1.2.1                    py35_0  
sockjs-tornado            1.0.3                    py35_0  
sphinx                    1.4.6                    py35_0  
sphinx_rtd_theme          0.1.9                    py35_0  
spyder                    3.0.2                    py35_0  
sqlalchemy                1.0.13                   py35_0  
sqlite                    3.13.0                        0  
statsmodels               0.6.1               np111py35_1  
sympy                     1.0                      py35_0  
termcolor                 1.1.0                    py35_1    conda-forge
terminado                 0.6                      py35_0  
tk                        8.5.18                        0  
toolz                     0.8.0                    py35_0  
tornado                   4.4.1                    py35_0  
traitlets                 4.3.0                    py35_0  
twine                     1.8.1                    py35_1    conda-forge
typing                    3.5.2.2                   <pip>
unicodecsv                0.14.1                   py35_0  
urllib3                   1.18                      <pip>
urllib3                   1.16                     py35_1    conda-forge
versioneer                0.17                     py35_0    conda-forge
wcwidth                   0.1.7                    py35_0  
werkzeug                  0.11.11                  py35_0  
wheel                     0.29.0                   py35_0  
whichcraft                0.4.0                    py35_0    conda-forge
widgetsnbextension        1.2.6                    py35_0  
wkhtmltopdf               0.12.3                        0    bioconda
wrapt                     1.10.6                   py35_0  
xlrd                      1.0.0                    py35_0  
xlsxwriter                0.9.3                    py35_0  
xlwt                      1.1.2                    py35_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zeromq                    4.1.4                         0  
zlib                      1.2.8                         3  
(bjorn3) bjorn@bjorn-ThinkPad-T450s:~/Desktop/python_packages$ 
```

**Comment by msarahan** [comment]
I am not certain that conda clean --lock will work here. Please try to
manually remove that file if it exists.

The lock code is not shared between conda and conda build. I did this
because conda's lock code was inadequate at the time that conda build
needed it. It is worth reexamining the situation to see if conda build can
just use conda locks again.

**Comment by BjornFJohansson** [comment]
thanks that helped!

**Comment by msarahan** [comment]
Locking has been reworked for the pending 2.1.0 release.  Closing this issue.  Please reopen or open a new issue as necessary.
