### ISSUE TITLE
--dirty option is broken

### ISSUE THREAD

**Issue by Zaharid** [conda/conda-build#1584]
```
$ conda build . --dirty
Traceback (most recent call last):
  File "/home/zah/anaconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/zah/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 255, in main
    execute(sys.argv[1:])
  File "/home/zah/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 247, in execute
    already_built=None, config=config, noverify=args.no_verify)
  File "/home/zah/anaconda3/lib/python3.5/site-packages/conda_build/api.py", line 75, in build
    need_source_download=need_source_download, config=config)
  File "/home/zah/anaconda3/lib/python3.5/site-packages/conda_build/build.py", line 1216, in build_tree
    config=recipe_config)
  File "/home/zah/anaconda3/lib/python3.5/site-packages/conda_build/render.py", line 159, in render_recipe
    config=config)
  File "/home/zah/anaconda3/lib/python3.5/site-packages/conda_build/render.py", line 112, in parse_or_try_download
    return metadata, need_source_download, need_reparse_in_env
UnboundLocalError: local variable 'need_source_download' referenced before assignment
```

Indeed the function `parse_or_try_download` does not define the value of that variable in all the cases.

This is for latest conda build (2.0.12)

**Comment by msarahan** [comment]
Thanks, I will fix this for the next release.
