### ISSUE TITLE
Problem: When using output-folder the index doesn't get updated properly

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#1603]
Using the latest master, I get the following error while build patchelf:

```
Fixing permissions
patchelf: file: /[PREFIX]/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/patchelf
    setting rpath to: $ORIGIN/../lib
Fixing permissions
Detected hard-coded path in binary file bin/patchelf
updating index in: /[PREFIX]/conda-bld/linux-64
updating index in: /builds/[TMP]/output-folder
TEST START: patchelf-0.9-2
Deleting work directory, /[PREFIX]/conda-bld/recipe_1482480512395/work/patchelf-0.9
updating index in: /[PREFIX]/conda-bld/linux-64
updating index in: /[PREFIX]/conda-bld/noarch
Traceback (most recent call last):
  File "/[PREFIX]/lib/python3.5/site-packages/conda/core/index.py", line 159, in fetch_repodata_remote_request
    resp.raise_for_status()
  File "/[PREFIX]/lib/python3.5/site-packages/requests/models.py", line 884, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: None for url: file:///builds/[TMP]/output-folder/linux-64/repodata.json.bz2
```

I think the problem is, that the conda index does get created in output-folder but not in output-folder/linux-64...

**Comment by msarahan** [comment]
Thanks @gabm - will fix this for the final 2.1.0 release.
