### ISSUE TITLE
Regression in 2.1.0: conda render raises incorrect assertion

### ISSUE THREAD

**Issue by mwiebe** [conda/conda-build#1640]
While the assertion is fine, it fails in the first pass of render, before the source is downloaded. With the source downloaded, it would not fail.

Relevant version metadata is:

```
  version: {{ GIT_DESCRIBE_TAG.lstrip('v') }}.{{ GIT_DESCRIBE_NUMBER }}.{{ GIT_DESCRIBE_HASH }}
```

Assertion is:

```
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-render-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_render.main())
  File "C:\Anaconda3\lib\site-packages\conda_build\cli\main_render.py", line 130, in main
    return execute(sys.argv[1:])
  File "C:\Anaconda3\lib\site-packages\conda_build\cli\main_render.py", line 122, in execute
    config=config)
  File "C:\Anaconda3\lib\site-packages\conda_build\render.py", line 157, in render_recipe
    config=config)
  File "C:\Anaconda3\lib\site-packages\conda_build\render.py", line 90, in parse_or_try_download
    metadata.parse_again(config=config, permit_undefined_jinja=False)
  File "C:\Anaconda3\lib\site-packages\conda_build\metadata.py", line 431, in parse_again
    self.meta = parse(self._get_contents(permit_undefined_jinja, config=config),
  File "C:\Anaconda3\lib\site-packages\conda_build\metadata.py", line 770, in _get_contents
    permit_undefined_jinja=permit_undefined_jinja))
  File "C:\Anaconda3\lib\site-packages\conda_build\jinja_context.py", line 213, in context_processor
    ctx = get_environ(config=config, m=initial_metadata)
  File "C:\Anaconda3\lib\site-packages\conda_build\environ.py", line 222, in get_dict
    d.update(meta_vars(m, config))
  File "C:\Anaconda3\lib\site-packages\conda_build\environ.py", line 331, in meta_vars
    d['PKG_VERSION'] = meta.version()
  File "C:\Anaconda3\lib\site-packages\conda_build\metadata.py", line 547, in version
    assert not res.startswith('.'), "Version can't start with leading period -  got %s" % res
AssertionError: Version can't start with leading period -  got ..
```

**Comment by msarahan** [comment]
Dang.  I'll fix this for 2.1.1.
