### ISSUE TITLE
Cannot patch sources on Windows with conda-build 2.1

### ISSUE THREAD

**Issue by dolfim** [conda/conda-build#1642]
As reported at conda-forge/staged-recipes#2180 (commit 0536724) and conda-forge/conda-forge-build-setup-feedstock#49, updating the builds to latest ```conda-build``` (2.1 at the time) breaks while patching the sources.

The error is:

```
[00:01:54] BUILD START: patch-win-0.1-0
[00:02:04] 
[00:02:04] The following packages will be downloaded:
[00:02:04] 
[00:02:04]     package                    |            build
[00:02:04]     ---------------------------|-----------------
[00:02:04]     toolchain-2.0.0            |                0           2 KB  conda-forge
[00:02:04] 
[00:02:04] The following NEW packages will be INSTALLED:
[00:02:04] 
[00:02:04]     toolchain: 2.0.0-0 conda-forge
[00:02:04] 
[00:02:04] Applying patch: u'C:\\projects\\staged-recipes\\recipes\\patch-win\\test.patch'
[00:02:04] Traceback (most recent call last):
[00:02:04]   File "C:\Miniconda\Scripts\conda-build-all-script.py", line 11, in <module>
[00:02:04]     load_entry_point('conda-build-all==1.0.0', 'console_scripts', 'conda-build-all')()
[00:02:04]   File "C:\Miniconda\lib\site-packages\conda_build_all\cli.py", line 90, in main
[00:02:04]     b.main()
[00:02:04]   File "C:\Miniconda\lib\site-packages\conda_build_all\builder.py", line 263, in main
[00:02:04]     built_dist_location = self.build(meta, build_config)
[00:02:04]   File "C:\Miniconda\lib\site-packages\conda_build_all\builder.py", line 200, in build
[00:02:04]     conda_build.api.build(meta.meta, config=config)
[00:02:04]   File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 86, in build
[00:02:04]     need_source_download=need_source_download, config=config)
[00:02:04]   File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1427, in build_tree
[00:02:04]     config=config)
[00:02:04]   File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 948, in build
[00:02:04]     config=config)
[00:02:04]   File "C:\Miniconda\lib\site-packages\conda_build\render.py", line 87, in parse_or_try_download
[00:02:04]     source.provide(metadata, config=config)
[00:02:04]   File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 522, in provide
[00:02:04]     apply_patch(src_dir, join(metadata.path, patch), config, git)
[00:02:04]   File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 478, in apply_patch
[00:02:04]     check_call_env([patch] + patch_args, cwd=src_dir)
[00:02:04]   File "C:\Miniconda\lib\site-packages\conda_build\utils.py", line 596, in check_call_env
[00:02:04]     return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
[00:02:04]   File "C:\Miniconda\lib\site-packages\conda_build\utils.py", line 592, in _func_defaulting_env_to_os_environ
[00:02:04]     return func(_args, **kwargs)
[00:02:04]   File "C:\Miniconda\lib\subprocess.py", line 536, in check_call
[00:02:04]     retcode = call(*popenargs, **kwargs)
[00:02:04]   File "C:\Miniconda\lib\subprocess.py", line 523, in call
[00:02:04]     return Popen(*popenargs, **kwargs).wait()
[00:02:04]   File "C:\Miniconda\lib\subprocess.py", line 711, in __init__
[00:02:04]     errread, errwrite)
[00:02:04]   File "C:\Miniconda\lib\subprocess.py", line 959, in _execute_child
[00:02:04]     startupinfo)
[00:02:04] TypeError: environment can only contain strings
```

**Comment by msarahan** [comment]
Sorry about this.  Thanks for reporting.  I'll fix it for a 2.1.1 release.
