### ISSUE TITLE
'Resolve' object has no attribute 'get_pkgs'

### ISSUE THREAD

**Issue by mahmoud** [conda/conda-build#1654]
Running with conda build 2.0.12 on conda 4.3.3, I see the following when running a basic conda build:

```
$ conda build .
BUILD START: jenkins-1.0.2-py27_0
updating index in: /Users/mahmoud/anaconda2/conda-bld/osx-64
updating index in: /Users/mahmoud/anaconda2/conda-bld/noarch

The following NEW packages will be INSTALLED:

    openssl:    1.0.2j-0
    pip:        9.0.1-py27_1
    python:     2.7.13-0
    readline:   6.2-2
    setuptools: 27.2.0-py27_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-3

Traceback (most recent call last):
  File "/Users/mahmoud/anaconda2/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 255, in main
    execute(sys.argv[1:])
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 247, in execute
    already_built=None, config=config, noverify=args.no_verify)
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_build/api.py", line 75, in build
    need_source_download=need_source_download, config=config)
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 1230, in build_tree
    config=recipe_config)
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 758, in build
    create_env(config.build_prefix, specs, config=config)
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 664, in create_env
    warn_on_old_conda_build(index=index)
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 712, in warn_on_old_conda_build
    available_packages = get_conda_build_index_versions(index)
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 690, in get_conda_build_index_versions
    pkgs = r.get_pkgs(MatchSpec('conda-build'))
AttributeError: 'Resolve' object has no attribute 'get_pkgs'
```

The recipe is pretty basic, generated by conda skeleton with almost no tweaks, [based on the PyPI Jenkins package](https://pypi.python.org/pypi/jenkins). I also tried it with canary conda build and got the same error.

**Comment by msarahan** [comment]
Conda build is currently incompatible with conda 4.3.  I hope to fix this soon.  Please downgrade conda and try again.

**Comment by mahmoud** [comment]
OK I downgraded to 4.2.13 using conda install -c conda-forge "conda>=4.2" and that seems to have done the trick. You may want to leave this open until 4.3 compat is there, but it's up to you. Thanks!

**Comment by msarahan** [comment]
yep, will do. thanks.
