### ISSUE TITLE
Invalid cross-device link

### ISSUE THREAD

**Issue by bgruening** [conda/conda-build#1659]
```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/conda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 242, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 234, in execute
    already_built=None, config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/api.py", line 77, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 1099, in build_tree
    config=recipe_config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 634, in build
    create_env(config.build_prefix, specs, config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 504, in create_env
    plan.execute_actions(actions, index, verbose=config.debug)
  File "/opt/conda/lib/python3.5/site-packages/conda/plan.py", line 837, in execute_actions
    execute_instructions(plan, index, verbose)
  File "/opt/conda/lib/python3.5/site-packages/conda/instructions.py", line 258, in execute_instructions
    cmd(state, arg)
  File "/opt/conda/lib/python3.5/site-packages/conda/instructions.py", line 111, in PROGRESSIVEFETCHEXTRACT_CMD
    progressive_fetch_extract.execute()
  File "/opt/conda/lib/python3.5/site-packages/conda/core/package_cache.py", line 467, in execute
    self._execute_action(action)
  File "/opt/conda/lib/python3.5/site-packages/conda/core/package_cache.py", line 489, in _execute_action
    raise CondaMultiError(exceptions)
conda.CondaMultiError: OSError(18, 'Invalid cross-device link')
OSError(18, 'Invalid cross-device link')
```
More information: https://travis-ci.org/bioconda/bioconda-recipes/jobs/191903636

**Comment by msarahan** [comment]
This is tied into Conda, I think, more than conda-build.  Conda is getting more and more careful, and raising errors where before it probably would have just failed in less obvious ways.

This is also specific to your system - if your conda-build temporary directory is on a different volume than your conda package cache, then this error happens.  There should be a fallback to copying files rather than linking them - and that's the conda issue.

**Comment by msarahan** [comment]
I take that back a bit - conda-build is using enough of conda internals that it may be conda-build's fault for not handling that exception.  We'll try to sort out how to make this work.

**Comment by bgruening** [comment]
Thanks @msarahan!

**Comment by mpekalski** [comment]
I got a similar problem when trying to build a docker images with

`RUN conda skeleton pypi mecab-python3 && conda build mecab-python3`

it used to work before.  In the beginning of building the image I run 
`RUN conda update --all `
so I guess I get the latest version of build.

```
Warning, the following versions were found for mecab-python3
0.5
0.6
0.7
Using 0.7
Use --version to specify a different version.
Using url https://pypi.python.org/packages/25/e9/bbf5fc790a2bedd96fbaf47a84afa060bfb0b3e0217e5f64b32bd4bbad69/mecab-python3-0.7.tar.gz (41 KB) for mecab-python3.
Downloading mecab-python3
Unpacking mecab-python3...
done
working in /tmp/tmpjlrloe18conda_skeleton_mecab-python3-0.7.tar.gz

The following NEW packages will be INSTALLED:

    openssl:    1.0.2j-0
    pip:        9.0.1-py35_1
    python:     3.5.2-0
    pyyaml:     3.12-py35_0
    readline:   6.2-2
    setuptools: 27.2.0-py35_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py35_0
    xz:         5.2.2-1
    yaml:       0.1.6-0
    zlib:       1.2.8-3

Traceback` (most recent call last):
  File "/opt/conda/bin/conda-skeleton", line 6, in <module>
    sys.exit(conda_build.cli.main_skeleton.main())
  File "/opt/conda/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/opt/conda/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    api.skeletonize(package, args.repo, config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/api.py", line 192, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 407, in skeletonize
    noprompt, packages, config=config, setup_options=setup_options)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 665, in get_package_metadata
    config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 925, in get_pkginfo
    run_setuppy(src_dir, tempdir, python_version, config=config, setup_options=setup_options)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 958, in run_setuppy
    config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 678, in create_env
    plan.execute_actions(actions, index, verbose=config.debug)
  File "/opt/conda/lib/python3.5/site-packages/conda/plan.py", line 837, in execute_actions
    execute_instructions(plan, index, verbose)
  File "/opt/conda/lib/python3.5/site-packages/conda/instructions.py", line 258, in execute_instructions
    cmd(state, arg)
  File "/opt/conda/lib/python3.5/site-packages/conda/instructions.py", line 111, in PROGRESSIVEFETCHEXTRACT_CMD
    progressive_fetch_extract.execute()
  File "/opt/conda/lib/python3.5/site-packages/conda/core/package_cache.py", line 467, in execute
    self._execute_action(action)
  File "/opt/conda/lib/python3.5/site-packages/conda/core/package_cache.py", line 489, in _execute_action
    raise CondaMultiError(exceptions)
conda.CondaMultiError: OSError(18, 'Invalid cross-device link')
OSError(18, 'Invalid cross-device link')
OSError(18, 'Invalid cross-device link')
```
