### ISSUE TITLE
conda skeleton cpan Moose

### ISSUE THREAD

**Issue by jerowe** [conda/conda-build#1675]
```
➜  ~ conda skeleton cpan Moose
Using url https://cpan.metacpan.org/authors/id/E/ET/ETHER/Moose-2.1807.tar.gz (809565) for Moose.
Processing dependencies for Moose....Fetching package metadata .........
..Fetching package metadata .........
.Traceback (most recent call last):
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda/gateways/download.py", line 64, in download
    resp.raise_for_status()
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://api.metacpan.org/v0/release/File-Spec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/bin/conda-skeleton", line 6, in <module>
    sys.exit(conda_build.cli.main_skeleton.main())
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    api.skeletonize(package, args.repo, config=config)
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda_build/api.py", line 192, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda_build/skeletons/cpan.py", line 301, in skeletonize
    recursive=recursive, config=config)
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda_build/skeletons/cpan.py", line 479, in deps_for_package
    perl_version, config=config)
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda/utils.py", line 44, in __call__
    value = self.func(*args, **kw)
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda_build/skeletons/cpan.py", line 546, in dist_for_module
    rel_dict = get_cpan_api_url('{0}/v0/release/{1}'.format(cpan_url, module), colons=False)
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda_build/skeletons/cpan.py", line 158, in get_cpan_api_url
    with PerlTmpDownload(url) as json_path:
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda_build/skeletons/cpan.py", line 151, in __enter__
    download(self.url, dst)
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda/core/package_cache.py", line 514, in download
    gateway_download(url, dst_path, md5)
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda/gateways/download.py", line 122, in download
    getattr(e.response, 'elapsed', None))
conda.exceptions.CondaHTTPError: HTTP 404 NOT FOUND for url <http://api.metacpan.org/v0/release/File-Spec>
Elapsed: 00:00.356382

An HTTP error occurred when trying to retrieve this URL.
HTTPError('404 Client Error: Not Found for url: http://api.metacpan.org/v0/release/File-Spec',)
```

**Comment by msarahan** [comment]
Confirmed.  This is happening with following links to dependencies.  Haven't quite been able to isolate it yet.

**Comment by jerowe** [comment]
This is more of a feature request than a bug, but is it possible to either remove or comment out perl core deps?

If I ran this with --recusursive, the commented out libraries would just be place holders, because they are core.  I think it is better to comment them out, because very occasionally you have an update of perl core module. In this case a recipe needs to be built, but it is infrequent and probably an edge case.

```
requirements:
  build:
    - perl
    - perl-pathtools
    - perl-data-optlist
    - perl-extutils-makemaker
    - perl-test-requires
    - perl-module-runtime
    - perl-apache-test
    - perl-module-implementation
    - perl-test-fatal
    - perl-try-tiny
    - perl-scalar-list-utils
    - perl-test-simple
    - perl-package-stash
    #- perl-exporter
    #- perl-constant
    #- perl-version

  run:
    - perl
    - perl-data-optlist
    - perl-module-runtime
    - perl-module-implementation
    - perl-apache-test
    - perl-try-tiny
    - perl-scalar-list-utils
    - perl-package-stash
    #- perl-exporter
```

**Comment by msarahan** [comment]
Sorry, we see pretty minimal usage of perl right now.  It's really hard for me to justify much time working on this.  If anyone uses perl a lot, I'd be very happy to support your development efforts here.  I don't, and I don't trust myself to do meaningful work when I'm not actually using things for my own purposes.

What appears to be the issue is that perl is expressing dependencies at a finer-grained level than the package level.  For example, ```conda skeleton cpan Moo``` tries to get the ``Test::More`` package.  This is not a package at all.  It is part of the Test-Simple package: http://search.cpan.org/~exodist/Test-Simple-1.302075/lib/Test/More.pm

I have fixed this by just ignoring 404's, which appears to have been the behavior of past conda versions.  Conda 4.3 raises CondaHTTPError, which changed conda-build's behavior here, bubbling up and killing the skeleton job.

**Comment by jerowe** [comment]
Fair enough. Are you accepting pull requests?

**Comment by msarahan** [comment]
Always! Very happy to help if you have any questions, also.

**Comment by jerowe** [comment]
Alright then. I use perl quite a bit, so it will be useful for me to take this on. ;-) I will let you know if I have any questions.

**Comment by mictadlo** [comment]
Hi, I have similar problem:

```
$ conda skeleton cpan IO::Prompt
Using url https://cpan.metacpan.org/authors/id/D/DC/DCONWAY/IO-Prompt-0.997004.tar.gz (15297) for IO::Prompt.
Processing dependencies for IO::Prompt....Traceback (most recent call last):
  File "/anaconda/bin/conda-skeleton", line 6, in <module>
    sys.exit(conda_build.cli.main_skeleton.main())
  File "/anaconda/lib/python2.7/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/anaconda/lib/python2.7/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    api.skeletonize(package, args.repo, config=config)
  File "/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 192, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/anaconda/lib/python2.7/site-packages/conda_build/skeletons/cpan.py", line 301, in skeletonize
    recursive=recursive, config=config)
  File "/anaconda/lib/python2.7/site-packages/conda_build/skeletons/cpan.py", line 479, in deps_for_package
    perl_version, config=config)
  File "/anaconda/lib/python2.7/site-packages/conda/utils.py", line 45, in __call__
    value = self.func(*args, **kw)
  File "/anaconda/lib/python2.7/site-packages/conda_build/skeletons/cpan.py", line 546, in dist_for_module
    rel_dict = get_cpan_api_url('{0}/v0/release/{1}'.format(cpan_url, module), colons=False)
  File "/anaconda/lib/python2.7/site-packages/conda_build/skeletons/cpan.py", line 158, in get_cpan_api_url
    with PerlTmpDownload(url) as json_path:
  File "/anaconda/lib/python2.7/site-packages/conda_build/skeletons/cpan.py", line 151, in __enter__
    download(self.url, dst)
  File "/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 513, in download
    gateway_download(url, dst_path, md5)
  File "/anaconda/lib/python2.7/site-packages/conda/gateways/download.py", line 124, in download
    getattr(e.response, 'elapsed', None))
conda.exceptions.CondaHTTPError: HTTP 404 NOT FOUND for url <http://api.metacpan.org/v0/release/IO-Handle>
Elapsed: 00:00.891148

An HTTP error occurred when trying to retrieve this URL.
HTTPError(u'404 Client Error: Not Found for url: http://api.metacpan.org/v0/release/IO-Handle',)
```

**Comment by jerowe** [comment]
@mictadlo , could you update conda-build and try again?

```
conda install conda-build
conda skeleton cpan IO::Prompt
```

I was able to get it working.

**Comment by jerowe** [comment]
@msarahan , do you mind if I create another PR which makes the recipe conda-forge linter happy?

**Comment by mictadlo** [comment]
I did not get it to work. 

```
/QRISdata/Q0231/bioconda-recipes> conda install conda-build
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /QRISdata/Q0231/apps:

The following NEW packages will be INSTALLED:

    beautifulsoup4: 4.5.3-py27_0             
    chardet:        2.3.0-py27_0             
    futures:        3.0.5-py27_0  conda-forge

The following packages will be UPDATED:

    conda-build:    2.0.11-py27_0             --> 2.1.2-py27_0  conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    conda:          4.3.4-py27_0              --> 4.2.13-py27_0 conda-forge
    conda-env:      2.6.0-0                   --> 2.6.0-0       conda-forge

Proceed ([y]/n)? y

conda-env-2.6. 100% |############################################################################################################################################################| Time: 0:00:00  16.10 kB/s
beautifulsoup4 100% |############################################################################################################################################################| Time: 0:00:00 235.27 kB/s
chardet-2.3.0- 100% |############################################################################################################################################################| Time: 0:00:00   3.61 MB/s
futures-3.0.5- 100% |############################################################################################################################################################| Time: 0:00:00  36.98 kB/s
conda-4.2.13-p 100% |############################################################################################################################################################| Time: 0:00:02 136.34 kB/s
conda-build-2. 100% |############################################################################################################################################################| Time: 0:00:01 180.03 kB/s
```

```
/QRISdata/Q0231/bioconda-recipes> conda install perl
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment /QRISdata/Q0231/apps:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    perl-5.22.2.1              |                0        15.0 MB  conda-forge

The following packages will be UPDATED:

    perl:          5.22.0.1-0         conda-forge --> 5.22.2.1-0 conda-forge

The following packages will be DOWNGRADED due to dependency conflicts:

    perl-threaded: 5.22.0-pl5.22.0_12 bioconda    --> 5.22.0-10  bioconda   

Proceed ([y]/n)? y

Fetching packages ...
perl-5.22.2.1- 100% |############################################################################################################################################################| Time: 0:00:22 683.24 kB/s
Extracting packages ...
[      COMPLETE      ]|###############################################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###############################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|###############################################################################################################################################################################| 100%
```

```
/QRISdata/Q0231/bioconda-recipes> conda skeleton cpan IO::Prompt
Error: command failed: corelist -v 5.20.3 IO::Prompt
Please make sure you have the perl conda package installed in your default environment
```


What did I miss?

Thank you in advnace.

**Comment by msarahan** [comment]
This fix is only present in conda-build 2.1.3.  You appear to have 2.1.2.  You may need to install 2.1.3 from defaults.

**Comment by mictadlo** [comment]
How do I do it?

**Comment by mictadlo** [comment]
I updated it to 2.1.3 from defaults, but I get 

```
> conda install -c defaults conda-build
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment /QRISdata/Q0231/apps:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          502 B
    conda-4.3.8                |           py27_0         468 KB
    conda-build-2.1.3          |           py27_0         311 KB
    ------------------------------------------------------------
                                           Total:         780 KB

The following NEW packages will be INSTALLED:

    conda-build: 2.1.3-py27_0             

The following packages will be UPDATED:

    conda:       4.2.13-py27_0 conda-forge --> 4.3.8-py27_0

The following packages will be SUPERCEDED by a higher-priority channel:

    conda-env:   2.6.0-0       conda-forge --> 2.6.0-0     

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
conda-env-2.6. 100% |############################################################################################################################################################| Time: 0:00:00   7.21 kB/s
conda-4.3.8-py 100% |############################################################################################################################################################| Time: 0:00:02 238.61 kB/s
conda-build-2. 100% |############################################################################################################################################################| Time: 0:00:01 188.53 kB/s
Extracting packages ...
[      COMPLETE      ]|###############################################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###############################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|###############################################################################################################################################################################| 100%
```



```
> conda skeleton cpan IO::Prompt
Error: command failed: corelist -v 5.20.3 IO::Prompt
Please make sure you have the perl conda package installed in your default environment.
```

```
> conda install perl
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /QRISdata/Q0231/apps:

The following packages will be SUPERCEDED by a higher-priority channel:

    conda:     4.3.8-py27_0 --> 4.2.13-py27_0 conda-forge
    conda-env: 2.6.0-0      --> 2.6.0-0       conda-forge

Proceed ([y]/n)? y

conda-env-2.6. 100% |############################################################################################################################################################| Time: 0:00:00 174.36 kB/s
```

```
> conda skeleton cpan IO::Prompt
Error: command failed: corelist -v 5.20.3 IO::Prompt
Please make sure you have the perl conda package installed in your default environment.
```

What did I miss?

**Comment by msarahan** [comment]
Conda has a crappy behavior where it always tries to update itself.  This block here:

```
> conda install perl
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /QRISdata/Q0231/apps:

The following packages will be SUPERCEDED by a higher-priority channel:

    conda:     4.3.8-py27_0 --> 4.2.13-py27_0 conda-forge
    conda-env: 2.6.0-0      --> 2.6.0-0       conda-forge

Proceed ([y]/n)? y

conda-env-2.6. 100% |############################################################################################################################################################| Time: 0:00:00 174.36 kB/s
```

You didn't actually get perl.  We don't have it in defaults.  It should be on conda-forge, though.  What does ``which perl`` tell you?

**Comment by mictadlo** [comment]
```
> which perl
/QRISdata/Q0231/apps/bin/perl
```

**Comment by msarahan** [comment]
OK, no problem there.  It looks to me like the confusion is that IO::Prompt is a submodule, or whatever perl calls those.  It is not a package unto itself.  The package that contains it is IO-Prompt, and this command works for me:

```conda skeleton cpan IO-Prompt```

I found this by Googling "cpan IO prompt" and found this page: http://search.cpan.org/~dconway/IO-Prompt-0.997004/lib/IO/Prompt.pm

Conda-build could definitely have more helpful error messages.  Maybe @jerowe might help with that when she works on the cpan skeleton module.

**Comment by mictadlo** [comment]
Thank you, it works, but it looks like it does not resolve dependencies automatically.

**Comment by msarahan** [comment]
It has in the past - that's a new bug.  I'm sorry I don't have time to fix it at this moment.  I'll mark it for the next bugfix milestone.  PRs welcome.

**Comment by mictadlo** [comment]
No worries. I did 

```
conda skeleton cpan Want
conda build perl-want/0.29/
```

but I got `Can't locate Want.pm in @INC (you may need to install the Want module)`
