### ISSUE TITLE
conda-build-2.1.1 / conda-4.3.5. fails with Permission denied: '/opt/anaconda/locks'

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#1682]
_From @itldo on January 19, 2017 17:55_

I just upgraded to the latest conda build and conda 4.3 but now my 'conda build' fails attempting
to create a missing 'locks' directory in the system conda directory.
Should I have expected this directory to already exist?
Or can I build only within my own environment? 

Thanks
-tim

```
$ conda build .
BUILD START:
...
number of files: 1
Fixing permissions
...
Fixing permissions
Traceback (most recent call last):
  File "/opt/anaconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 321, in main
    execute(sys.argv[1:])
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 312, in execute
    noverify=args.no_verify)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 89, in build
    need_source_download=need_source_download, config=config)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1460, in build_tree
    config=config)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1116, in build
    built_package = bundlers[output.get('type', 'conda')](output, m, config, env)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 811, in bundle_conda
    info_files = create_info_files(tmp_metadata, files, config=config, prefix=config.build_prefix)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 485, in create_info_files
    copy_recipe(m, config)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 203, in copy_recipe
    utils.copy_into(src_path, dst_path, timeout=config.timeout, locking=config.locking)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 140, in copy_into
    lock = get_lock(src_folder, timeout=timeout)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 257, in get_lock
    os.makedirs(locks_dir)
  File "/opt/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/opt/anaconda/locks'
```

_Copied from original issue: conda/conda#4379_

**Comment by kalefranz** [comment]
Might already be fixed.  Not sure.

**Comment by msarahan** [comment]
conda-build does not support "central" installs right now.  It expects to have write access to the root conda installation.  What is needed is a fallback, as Conda has implemented in the 4.3 series.  This feature is slated for the 3.0.0 release.

For now, yes, you need to manually create the locks folder and set permissions so that whichever user you run conda-build as has write access to the locks folder.

**Comment by msarahan** [comment]
Closing to consolidate discussion at #1601

**Comment by itldo** [comment]
Thank you. I didn't think to look for exisiting issues in conda-build.

**Comment by joelhullcio** [comment]
FYI, conda and conda-build need to always support central installs going forward.  This is a critical feature for enterprise usage.  Looking forward to the fix ASAP.  This is currently an issue for us at a client site.
