### ISSUE TITLE
build environment creation fails with ValidationError on paths.json

### ISSUE THREAD

**Issue by Korijn** [conda/conda-build#1699]
Conda build started failing on our CI recently with the following error, which seems to be related to `paths.json` containing messed up paths.

Interestingly, conda itself _is_ capable of creating the environment (through `conda env create`), which has the same list of (pinned) dependencies and channels.

*It would be helpful if conda-build reported _which_ package caused the error*. Now I have to go through all of them to find the faulty package.

```
Traceback (most recent call last):
  File "C:\Miniconda35-x64\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\cli\main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\cli\main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\build.py", line 1478, in build_tree
    config=config)
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\build.py", line 943, in build
    create_env(config.build_prefix, specs, config=config)
  File "C:\Miniconda35-x64\lib\site-packages\conda_build\build.py", line 684, in create_env
    plan.execute_actions(actions, index, verbose=config.debug)
  File "C:\Miniconda35-x64\lib\site-packages\conda\plan.py", line 837, in execute_actions
    execute_instructions(plan, index, verbose)
  File "C:\Miniconda35-x64\lib\site-packages\conda\instructions.py", line 258, in execute_instructions
    cmd(state, arg)
  File "C:\Miniconda35-x64\lib\site-packages\conda\instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
    txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
  File "C:\Miniconda35-x64\lib\site-packages\conda\core\link.py", line 121, in create_from_dists
    for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
  File "C:\Miniconda35-x64\lib\site-packages\conda\core\link.py", line 121, in <genexpr>
    for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
  File "C:\Miniconda35-x64\lib\site-packages\conda\gateways\disk\read.py", line 74, in read_package_info
    paths_data = read_paths_json(extracted_package_directory)
  File "C:\Miniconda35-x64\lib\site-packages\conda\gateways\disk\read.py", line 137, in read_paths_json
    paths=(PathDataV1(**f) for f in data['paths']),
  File "C:\Miniconda35-x64\lib\site-packages\conda\_vendor\auxlib\entity.py", line 702, in __call__
    instance = super(EntityType, cls).__call__(*args, **kwargs)
  File "C:\Miniconda35-x64\lib\site-packages\conda\_vendor\auxlib\entity.py", line 719, in __init__
    setattr(self, key, kwargs[key])
  File "C:\Miniconda35-x64\lib\site-packages\conda\_vendor\auxlib\entity.py", line 424, in __set__
    instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
  File "C:\Miniconda35-x64\lib\site-packages\conda\_vendor\auxlib\entity.py", line 581, in box
    return self._type(v if isinstance(v, et) else et(**v) for v in val)
  File "C:\Miniconda35-x64\lib\site-packages\conda\_vendor\auxlib\entity.py", line 581, in <genexpr>
    return self._type(v if isinstance(v, et) else et(**v) for v in val)
  File "C:\Miniconda35-x64\lib\site-packages\conda\gateways\disk\read.py", line 137, in <genexpr>
    paths=(PathDataV1(**f) for f in data['paths']),
  File "C:\Miniconda35-x64\lib\site-packages\conda\_vendor\auxlib\entity.py", line 702, in __call__
    instance = super(EntityType, cls).__call__(*args, **kwargs)
  File "C:\Miniconda35-x64\lib\site-packages\conda\_vendor\auxlib\entity.py", line 719, in __init__
    setattr(self, key, kwargs[key])
  File "C:\Miniconda35-x64\lib\site-packages\conda\_vendor\auxlib\entity.py", line 424, in __set__
    instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
  File "C:\Miniconda35-x64\lib\site-packages\conda\_vendor\auxlib\entity.py", line 465, in validate
    raise ValidationError(getattr(self, 'name', 'undefined name'), val)
conda._vendor.auxlib.exceptions.ValidationError: Value for _path cannot be None.
```

conda info:

```
Current conda install:
               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.1.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\Miniconda35-x64  (writable)
    default environment : C:\Miniconda35-x64
       envs directories : C:\Miniconda35-x64\envs
          package cache : C:\Miniconda35-x64\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\appveyor\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.5.2 Windows/8.1 Windows/6.3.9600
```

**Comment by Korijn** [comment]
It turns out our `requests` package was built as `noarch` last week and conda-build apparently produced a botched package. Not sure how that happened.

**Comment by msarahan** [comment]
Sorry about that.  Yes, conda-build 2.1.0-2.1.1 had a bug with new-style noarch packages.  If you encounter further issues, please post!

**Comment by Korijn** [comment]
> It would be helpful if conda-build reported which package caused the error.
