### ISSUE TITLE
conda build crash

### ISSUE THREAD

**Issue by dsludwig** [conda/conda-build#1726]
Using conda-build 2.1.3:

We're using `requirements.txt` and `__conda_buildnum__.txt`/`__conda_version__.txt`, in case that's relevant (I suspect it's the former causing problems).

```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda2/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 1480, in build_tree
    config=config)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 1132, in build
    built_package = bundlers[output.get('type', 'conda')](output, m, config, env)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 825, in bundle_conda
    info_files = create_info_files(tmp_metadata, files, config=config, prefix=config.build_prefix)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 489, in create_info_files
    write_info_json(m, config)  # actually index.json
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 436, in write_info_json
    for dist in sorted(dists + [m.dist()]):
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/conda/models/dist.py", line 230, in __gt__
    assert isinstance(other, self.__class__)
AssertionError

conda build conda.recipe returned exit code 1

Action failed: conda build conda.recipe
```

Let me know if you need any additional information.

**Comment by msarahan** [comment]
Thanks.  This has also been reported on flowdock, I think.  It's a conda 4.3 incompatibility.  Downgrading to conda 4.2 should fix it for you.  I'll fix this in conda-build for the next bugfix release.
