### ISSUE TITLE
Conda build: WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by RedDevil91** [conda/conda-build#1737]
Hi All!

I have a problem building a package with conda-build which was created by myself (its called pyptc).
Used system: 
- win 7 64-bit
- conda 4.3.9

I get the following error:
```
C:\Miniconda2\conda-bld\pyptc_1486482915937\_b_env) C:\Miniconda2\conda-bld\pyp
tc_1486482915937\work>if errorlevel 1 exit 1
compiling .pyc files...
found egg dir: C:\Miniconda2\conda-bld\pyptc_1486482915937\_b_env\Lib\site-packa
ges\pyptc-0.1.6-py2.7.egg
number of files: 17
Fixing permissions
Fixing permissions
Traceback (most recent call last):
  File "C:\Miniconda2\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda2\lib\site-packages\conda_build\cli\main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "C:\Miniconda2\lib\site-packages\conda_build\cli\main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "C:\Miniconda2\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda2\lib\site-packages\conda_build\build.py", line 1480, in build_tree
    config=config)
  File "C:\Miniconda2\lib\site-packages\conda_build\build.py", line 1132, in build
    built_package = bundlers[output.get('type', 'conda')](output, m, config, env)
  File "C:\Miniconda2\lib\site-packages\conda_build\build.py", line 825, in bundle_conda
    info_files = create_info_files(tmp_metadata, files, config=config, prefix=config.build_prefix)
  File "C:\Miniconda2\lib\site-packages\conda_build\build.py", line 485, in create_info_files
    copy_recipe(m, config)
  File "C:\Miniconda2\lib\site-packages\conda_build\build.py", line 245, in copy_recipe
    f.write("# " + source.get_repository_info(m.path) + "\n")
  File "C:\Miniconda2\lib\site-packages\conda_build\source.py", line 378, in get_repository_info
    cwd=recipe_path)
  File "C:\Miniconda2\lib\site-packages\conda_build\utils.py", line 596, in check_output_env
    return _func_defaulting_env_to_os_environ(subprocess.check_output, *popenargs, **kwargs)\
  File "C:\Miniconda2\lib\site-packages\conda_build\utils.py", line 588, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "C:\Miniconda2\lib\subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Miniconda2\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Miniconda2\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by msarahan** [comment]
I think you need git installed.  In your root environment, run this:

``conda install posix m2-git``

The error message should be better, though.

**Comment by RedDevil91** [comment]
Thanks for the answer. We have figured out that the .git directory causes the problem. After deleting the files and directories which was related to git the build process manages to finish without errors.

**Comment by msarahan** [comment]
Cool, thanks for following up.  Recent versions of conda-build should be ignoring .git folders.  Please update conda-build and if you ever see problems with this again, please let us know.

Closing this issue for now.

**Comment by RedDevil91** [comment]
We used the latest released versions from conda and conda-build. Maybe the win-64 caused the problem.
Thanks for help!

**Comment by edadoko** [comment]
Hi there,

I am also getting this same error message. I have clean installed conda and tried to make sure the path had no non-ascii characters/numbers. As well as installed git as mentioned above. I manage to create environments, but when I try to activate them I get the error message:

`'@"C:\Anaconda\Scripts\..\python.exe" -c "import ctypes; print(ctypes.cdll.kernel32.GetACP())"' is not recognized as an internal or external command,
operable program or batch file.
The filename, directory name, or volume label syntax is incorrect.`

When running `conda update anaconda` the error message is:
`
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::qt-5.6.2-vc9_4'.
WindowsError(2, 'The system cannot find the file specified')
Attempting to roll back.
WindowsError(2, 'The system cannot find the file specified')`
