### ISSUE TITLE
2.1.4 can't find Xcode tools on OS X Yosemite

### ISSUE THREAD

**Issue by janssen** [conda/conda-build#1746]
I get this:
```
+ conda build goodstuff --no-test
xcode-select: error: no developer tools were found at '/Applications/Xcode.app', and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.
xcode-select: error: no developer tools were found at '/Applications/Xcode.app', and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.
xcode-select: error: no developer tools were found at '/Applications/Xcode.app', and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.
Traceback (most recent call last):
  File "./figure-version", line 17, in <module>
    git_ref = subprocess.check_output(['git', 'describe', '--long', '--dirty', '--abbrev=40']).strip()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'describe', '--long', '--dirty', '--abbrev=40']' returned non-zero exit status 1
```
conda-build 2.0.4 works fine with the same Vagrant box and same build script I use here (OS X Yosemite).  Could this be a paths problem?

**Comment by jakirkham** [comment]
Please try running `xcode-select -p`. Also please make sure to run `xcode-select --install` just in case. Please include results of both in your response.

**Comment by jakirkham** [comment]
Looks like an XCode install issue. Do we document those somewhere?

Anyways should be closed.
