### ISSUE TITLE
Failed to create env (possibly long filename)

### ISSUE THREAD

**Issue by rolando** [conda/conda-build#1768]
I'm getting this error when trying to build a package for windows on appveyor, and something that catch my attention is the long filepath (262 chars):

```
WARNING conda_build.build:create_env(731): failed to create env, retrying.  exception was: [Errno 2] No such file or directory: u'C:\\Miniconda-x64\\pkgs\\pystan-2.14.0.0-np111py27_vc9_0.tmp\\Lib\\site-packages\\pystan\\stan\\lib\\stan_math_2.14.0\\doc\\api\\html\\d7\\d67\\structstan_1_1math_1_1promote__scalar__type_3_01_t_00_01_eigen_1_1_matrix_3_01_s_00_011_00_01_eia6a45e8e9b504fc35f96b001b609d995.html'
The following NEW packages will be INSTALLED:
    [SNIP]
ERROR conda_build.build:create_env(735): Failed to create env, max retries exceeded.
Traceback (most recent call last):
  File "C:\Miniconda-x64\Scripts\conda-build-all-script.py", line 5, in <module>
    sys.exit(conda_build_all.cli.main())
  File "C:\Miniconda-x64\lib\site-packages\conda_build_all\cli.py", line 90, in main
    b.main()
  File "C:\Miniconda-x64\lib\site-packages\conda_build_all\builder.py", line 267, in main
    built_dist_location = self.build(meta, build_config)
  File "C:\Miniconda-x64\lib\site-packages\conda_build_all\builder.py", line 204, in build
    conda_build.api.build(meta.meta, config=config)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 1493, in build_tree
    test(metadata, config=config)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 1311, in test
    create_env(config.test_prefix, specs, config=config)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 733, in create_env
    clear_cache=clear_cache, retry=retry + 1)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 733, in create_env
    clear_cache=clear_cache, retry=retry + 1)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 733, in create_env
    clear_cache=clear_cache, retry=retry + 1)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 690, in create_env
    plan.execute_actions(actions, index, verbose=config.debug)
  File "C:\Miniconda-x64\lib\site-packages\conda\plan.py", line 643, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Miniconda-x64\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "C:\Miniconda-x64\lib\site-packages\conda\instructions.py", line 58, in EXTRACT_CMD
    extract(arg)
  File "C:\Miniconda-x64\lib\site-packages\conda\install.py", line 810, in extract
    t.extractall(path=temp_path)
  File "C:\Miniconda-x64\lib\tarfile.py", line 2081, in extractall
    self.extract(tarinfo, path)
  File "C:\Miniconda-x64\lib\tarfile.py", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Miniconda-x64\lib\tarfile.py", line 2194, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Miniconda-x64\lib\tarfile.py", line 2234, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 2] No such file or directory: u'C:\\Miniconda-x64\\pkgs\\pystan-2.14.0.0-np111py27_vc9_0.tmp\\Lib\\site-packages\\pystan\\stan\\lib\\stan_math_2.14.0\\doc\\api\\html\\d7\\d67\\structstan_1_1math_1_1promote__scalar__type_3_01_t_00_01_eigen_1_1_matrix_3_01_s_00_011_00_01_eia6a45e8e9b504fc35f96b001b609d995.html'
```

Any idea how to overcome this error?

**Comment by mingwandroid** [comment]
Install to C:\M instead of C:\Miniconda-x64?

But if you can report it upstream that would be appreciated. Those paths are a bit much.

**Comment by rolando** [comment]
Fixed by not including `doc` files in the package.
