### ISSUE TITLE
Unhelpful error message

### ISSUE THREAD

**Issue by stefanseefeld** [conda/conda-build#1783]
I regularly get the error

```FileNotFoundError: [WinError 2] The system cannot find the file specified```

when running `conda build` (notably in a new environment that doesn't yet have all the required tools.
It would be good if the error above could include the name of the file that is missing.
(Here is a more complete traceback:
```
Traceback (most recent call last):
  File "C:\Users\stefan\Anaconda3\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Users\stefan\Anaconda3\lib\site-packages\conda_build\cli\main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "C:\Users\stefan\Anaconda3\lib\site-packages\conda_build\cli\main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "C:\Users\stefan\Anaconda3\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Users\stefan\Anaconda3\lib\site-packages\conda_build\build.py", line 1493, in build_tree
    config=config)
  File "C:\Users\stefan\Anaconda3\lib\site-packages\conda_build\build.py", line 1143, in build
    built_package = bundlers[output_dict.get('type', 'conda')](output_dict, m, config, env)
  File "C:\Users\stefan\Anaconda3\lib\site-packages\conda_build\build.py", line 890, in bundle_conda
    create_info_files(tmp_metadata, files, config=config, prefix=config.build_prefix)
  File "C:\Users\stefan\Anaconda3\lib\site-packages\conda_build\build.py", line 510, in create_info_files
    source.git_info(config, fo)
  File "C:\Users\stefan\Anaconda3\lib\site-packages\conda_build\source.py", line 266, in git_info
    p = Popen(cmd.split(), stdout=PIPE, stderr=PIPE, cwd=config.work_dir, env=env)
  File "C:\Users\stefan\Anaconda3\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\stefan\Anaconda3\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
i.e.,  it appears `conda build` is trying to run some tool such as `git` or `cygpath` or similar. Right now I need to modify the code to print out the missing info, which obviously isn't the right way to solve this.)

**Comment by msarahan** [comment]
fixed by #1803 - closing
