### ISSUE TITLE
conda build purge seems to be broken in 2.1.6

### ISSUE THREAD

**Issue by nicoddemus** [conda/conda-build#1812]
Hi,

`conda build purge` appears to be broken in `2.1.6`:

```
Traceback (most recent call last):
  File "E:\Miniconda\Scripts\conda-build-script.py", line 3, in <module>
    import conda_build.cli.main_build
  File "E:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 16, in <module>
    import conda_build.api as api
  File "E:\Miniconda\lib\site-packages\conda_build\api.py", line 22, in <module>
    from conda_build.config import Config, get_or_merge_config, DEFAULT_PREFIX_LENGTH as _prefix_length
  File "E:\Miniconda\lib\site-packages\conda_build\config.py", line 15, in <module>
    from .conda_interface import root_dir, root_writable, subdir, cc_platform, cc_conda_build
  File "E:\Miniconda\lib\site-packages\conda_build\conda_interface.py", line 154, in <module>
    cc_conda_build = context.conda_build
AttributeError: 'Context' object has no attribute 'conda_build'
```

This happens in both Windows and Linux. Downgrading to `2.1.5` fixes the problem.

**Comment by msarahan** [comment]
Thanks for the report.  We had an internal report of this too, but I haven't been able to reproduce.  What conda version are you using this with?

**Comment by nicoddemus** [comment]
Oh sorry, should have mentioned that, we're using `4.2.11`.

**Comment by msarahan** [comment]
Yep, confirmed.  This error goes away with conda 4.2.16 for me.  I'll see about reverting or otherwise fixing this.  Sorry for the breakage.

CC @kalefranz

**Comment by nicoddemus** [comment]
Not at all, thanks for the prompt response. 

If this is too complicated to fix, we are OK with pinning our internal conda-build version until we upgrade our conda version.

**Comment by msarahan** [comment]
I think it should be very quick, but go ahead and pin for now.  I thought this would be the last 2.1.x release, but I can't leave 2.1.x broken like this.

**Comment by nicoddemus** [comment]
Thanks @msarahan for the quick response!
