### ISSUE TITLE
I installed the minicondo for python 2.7 & 64 bit & windows

### ISSUE THREAD

**Issue by zooobeee** [conda/conda-build#1828]
It installed ok..  
but it  fails before anything 
condo install .....  fails

Condo List ... fails 
produced this results :  any ideas

P.S.  my ultimate  goal is to use it to  install ggplot python 2.7/64bit/windows because that fails to install using  pip install   etc

this is for

condo list
---------------------------------
Traceback (most recent call last):
  File "C:\Users\XXX\Miniconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\XXX\Miniconda2\lib\site-packages\conda\cli\main.py", line 167, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\XXX\Miniconda2\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Users\XXX\Miniconda2\lib\site-packages\conda\exceptions.py", line 559, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Users\XXX\Miniconda2\lib\site-packages\conda\exceptions.py", line 529, in get_info
    args.func(args, p)
  File "C:\Users\XXX\Miniconda2\lib\site-packages\conda\cli\main_info.py", line 142, in execute
    from conda.api import get_index
  File "C:\Users\XXX\Miniconda2\lib\site-packages\conda\api.py", line 1, in <module>
    from .core.index import get_index
  File "C:\Users\XXX\Miniconda2\lib\site-packages\conda\core\index.py", line 23, in <module>
    from .package_cache import PackageCache
  File "C:\Users\XXX\Miniconda2\lib\site-packages\conda\core\package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\XXX\Miniconda2\lib\site-packages\conda\core\path_actions.py", line 32, in <module>
    from ..gateways.download import download
  File "C:\Users\XXX\Miniconda2\lib\site-packages\conda\gateways\download.py", line 15, in <module>
    from ..connection import CondaSession
  File "C:\Users\XXX\Miniconda2\lib\site-packages\conda\connection.py", line 55, in <module>
    python=platform.python_implementation(),
  File "C:\PYTHON27\LIB\platform.py", line 1451, in python_implementation
    return _sys_version()[0]
  File "C:\PYTHON27\LIB\platform.py", line 1416, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.13 |Continuum Analytics, Inc.| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)]'

**Comment by ccordoba12** [comment]
You have another Python version installed in your system (in `C:\PYTHON27`). Please uninstall it to fix the conda problems you're seeing.

**Comment by zooobeee** [comment]
No I have 2.7 and 2.7 only and I  have been running it for few months... I can't even run 3.* with software that I am using is not available for that version

here is the log

print 'Python version:', sys.version
print 'Pandas version: ', pd.__version__

------------------------------------------------------------------------------------------------------------------
Python version: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
Pandas version:  0.19.2
