### ISSUE TITLE
wheel build fails on windows + python 2.7

### ISSUE THREAD

**Issue by mwcraig** [conda/conda-build#1829]
Attempting to build a wheel by adding a `wheel` to the `outputs` section of `meta.yaml` leads to a failure in the build process on Windows + python 2.7.

I can reproduce the error locally, but the traceback below is from an [appveyor run](https://ci.appveyor.com/project/mwcraig/vpython-jupyter/build/1.0.224/job/b79u5r3guwvek08l#L435). 

Use [this `meta.yaml`](https://gist.github.com/mwcraig/62ec496d07ec02797fe5f4b0321b18fd) to reproduce.

```
Package: vpython-2.0.6+6.gc8dacee-py27_0
source tree in: C:\Miniconda-x64\conda-bld\vpython_1489194783994\work
Processing c:\miniconda-x64\conda-bld\vpython_1489194783994\work
    Error environment can only contain strings while executing command python setup.py egg_info
Exception:
Traceback (most recent call last):
  File "C:\Miniconda-x64\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Miniconda-x64\lib\site-packages\pip\commands\wheel.py", line 199, in run
    if not wb.build():
  File "C:\Miniconda-x64\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Miniconda-x64\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Miniconda-x64\lib\site-packages\pip\req\req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "C:\Miniconda-x64\lib\site-packages\pip\req\req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "C:\Miniconda-x64\lib\site-packages\pip\req\req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\Miniconda-x64\lib\site-packages\pip\utils\__init__.py", line 667, in call_subprocess
    cwd=cwd, env=env)
  File "C:\Miniconda-x64\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Miniconda-x64\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
Traceback (most recent call last):
  File "C:\Miniconda-x64\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda-x64\lib\site-packages\conda_build\cli\main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "C:\Miniconda-x64\lib\site-packages\conda_build\cli\main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 1494, in build_tree
    config=config)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 1140, in build
    built_package = bundlers[output_dict.get('type', 'conda')](output_dict, m, config, env)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 962, in bundle_wheel
    wheel_file = glob(os.path.join(tmpdir, "*.whl"))[0]
IndexError: list index out of range
Command exited with code 1
```

**Comment by msarahan** [comment]
Punting due to lack of time.  Will fix soon.

**Comment by msarahan** [comment]
I think that #2080 might fix this, but I still need to test it.

**Comment by msarahan** [comment]
I'm not sure that this is an improvement, but it's at least a change:

```
Source cache directory is: C:\Users\msarahan\Miniconda2\conda-bld\src_cache
Downloading source to cache: vpython-2.0.6.tar.gz
Downloading https://pypi.io/packages/source/v/vpython/vpython-2.0.6.tar.gz
Success
Extracting download
source tree in: C:\Users\msarahan\Miniconda2\conda-bld\vpython_1497234704567\work
BUILD START: [u'vpython_wheel-2.0.6-h4193f2f_0.tar.bz2']
Solving package specifications: .

The following NEW packages will be INSTALLED:

    pip:            9.0.1-py27_1
    python:         2.7.13-1
    setuptools:     27.2.0-py27_1
    vs2008_runtime: 9.00.30729.5054-0
    wheel:          0.29.0-py27_0

Traceback (most recent call last):
  File "C:\Users\msarahan\Miniconda2\Scripts\pip-script.py", line 3, in <module>
    import pip
  File "C:\Users\msarahan\Miniconda2\lib\site-packages\pip\__init__.py", line 28, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Users\msarahan\Miniconda2\lib\site-packages\pip\vcs\mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "C:\Users\msarahan\Miniconda2\lib\site-packages\pip\download.py", line 37, in <module>
    from pip.utils.ui import DownloadProgressBar, DownloadProgressSpinner
  File "C:\Users\msarahan\Miniconda2\lib\site-packages\pip\utils\ui.py", line 57, in <module>
    _BaseBar = _select_progress_class(IncrementalBar, Bar)
  File "C:\Users\msarahan\Miniconda2\lib\site-packages\pip\utils\ui.py", line 50, in _select_progress_class
    six.text_type().join(characters).encode(encoding)
LookupError: unknown encoding: cp65001
Traceback (most recent call last):
  File "C:\Users\msarahan\Miniconda2\Scripts\conda-build-script.py", line 11, in <module>
    load_entry_point('conda-build', 'console_scripts', 'conda-build')()
  File "c:\users\msarahan\documents\github\conda-build\conda_build\cli\main_build.py", line 332, in main
    execute(sys.argv[1:])
  File "c:\users\msarahan\documents\github\conda-build\conda_build\cli\main_build.py", line 323, in execute
    noverify=args.no_verify)
  File "c:\users\msarahan\documents\github\conda-build\conda_build\api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "c:\users\msarahan\documents\github\conda-build\conda_build\build.py", line 1503, in build_tree
    built_packages=built_packages,
  File "c:\users\msarahan\documents\github\conda-build\conda_build\build.py", line 1090, in build
    built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env)
  File "c:\users\msarahan\documents\github\conda-build\conda_build\build.py", line 782, in bundle_wheel
    utils.check_call_env(['pip', 'wheel', '--wheel-dir', tmpdir, '--no-deps', '.'], env=env)
  File "c:\users\msarahan\documents\github\conda-build\conda_build\utils.py", line 670, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "c:\users\msarahan\documents\github\conda-build\conda_build\utils.py", line 666, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "C:\Users\msarahan\Miniconda2\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'wheel', '--wheel-dir', 'c:\\users\\msarahan\\appdata\\local\\temp\\tmpvfd0il', '--no-deps', '.']' returned non-zero exit status 1
```

This appears to be a Unicode error, as cp65001 is the UTF-8 codepage for Windows.  @mingwandroid any tips here?  Is there anything we can tweak in our _func_defaulting_env_to_os_environ?

**Comment by msarahan** [comment]
Punt to 3.0.1 - this one is very important to fix, but don't want to hold up 3.0.0 for it.

**Comment by mwcraig** [comment]
:+1: sounds good!

**Comment by mingwandroid** [comment]
I believe `cp65001` is unknown to Python 2. This seems to be some Python 2 vs Python 3 confusion. It goes like this:

```
from pip._vendor.progress.bar import Bar, IncrementalBar

_BaseBar = _select_progress_class(IncrementalBar, Bar)
encoding = getattr(_BaseBar.file, "encoding", None)
```

.. where:
```
Lib\site-packages\pip\_vendor\progress\bar.py begins with:
# -*- coding: utf-8 -*-
```

For me, on Python 2.7, using the following testcase:
```
from pip._vendor.progress.bar import Bar, IncrementalBar
getattr(IncrementalBar.file, "encoding", None)
```

I get `'cp1252'` while Python 3.6, I get `'utf-8'`.

Can you try my testcase? How is your `cmd.exe` configured? Are you using a Truetype font or not? (yes, that matters here, go figure). What do you get from `chcp`?

**Comment by msarahan** [comment]
chcp shows 1252.  I'm using "Anaconda Prompt" but have not customized the fonts at all.  It appears to be Consolas, size 16.

The py2/py3 explanation makes some sense, but I just don't know how I've run into this.  The way that the code was before, I was importing pip with the same interpreter process running conda-build.  The new way calls check_call_env so that we're running pip (the cli command) from the env that conda-build created for the skeletonize operation.  That env may not be activated here - would that make a difference?  I guess it would not be running your chcp command?

**Comment by mingwandroid** [comment]
I wonder if Python sets something like `PYTHONIOENCODING` and that gets passed on to the other Python.

Do we have Python 3 calling Python 2 here?

**Comment by msarahan** [comment]
Here's an extraordinarily interesting debugging output to ponder:

```
ipdb> subprocess.check_call(['chcp'], shell=True)
Active code page: 1252
0
ipdb> n
> z:\msarahan\code\conda-build\conda_build\build.py(931)build()
    930                 not os.listdir(m.config.build_prefix)):
--> 931             environ.create_env(m.config.build_prefix, build_actions, env='build', config=m.config,
    932                                subdir=m.config.build_subdir, is_cross=m.is_cross)

ipdb> n
> z:\msarahan\code\conda-build\conda_build\build.py(932)build()
    931             environ.create_env(m.config.build_prefix, build_actions, env='build', config=m.config,
--> 932                                subdir=m.config.build_subdir, is_cross=m.is_cross)
    933

ipdb>

The following NEW packages will be INSTALLED:

    backports:           1.0-py27_0
    backports_abc:       0.5-py27_0
    bleach:              1.5.0-py27_0
    colorama:            0.3.9-py27_0
    configparser:        3.5.0-py27_0
    cython:              0.25.2-py27_0
    decorator:           4.0.11-py27_0
    entrypoints:         0.2.2-py27_1
    enum34:              1.1.6-py27_0
    functools32:         3.2.3.2-py27_0
    get_terminal_size:   1.0.0-py27_0
    html5lib:            0.999-py27_0
    icu:                 57.1-vc9_0        [vc9]
    ipykernel:           4.6.1-py27_0
    ipython:             5.3.0-py27_0
    ipython_genutils:    0.2.0-py27_0
    ipywidgets:          6.0.0-py27_0
    jinja2:              2.9.6-py27_0
    jpeg:                9b-vc9_0          [vc9]
    jsonschema:          2.6.0-py27_0
    jupyter:             1.0.0-py27_3
    jupyter_client:      5.1.0-py27_0
    jupyter_console:     5.1.0-py27_0
    jupyter_core:        4.3.0-py27_0
    libpng:              1.6.27-vc9_0      [vc9]
    markupsafe:          0.23-py27_2
    mistune:             0.7.4-py27_0
    nbconvert:           5.2.1-py27_0
    nbformat:            4.3.0-py27_0
    notebook:            5.0.0-py27_0
    openssl:             1.0.2l-vc9_0      [vc9]
    pandocfilters:       1.4.1-py27_0
    path.py:             10.3.1-py27_0
    pathlib2:            2.2.1-py27_0
    pickleshare:         0.7.4-py27_0
    pip:                 9.0.1-py27_1
    prompt_toolkit:      1.0.14-py27_0
    pygments:            2.2.0-py27_0
    pyqt:                5.6.0-py27_2
    python:              2.7.13-1
    python-dateutil:     2.6.0-py27_0
    pyzmq:               16.0.2-py27_0
    qt:                  5.6.2-vc9_4       [vc9]
    qtconsole:           4.3.0-py27_0
    scandir:             1.5-py27_0
    setuptools:          27.2.0-py27_1
    simplegeneric:       0.8.1-py27_1
    singledispatch:      3.4.0.3-py27_0
    sip:                 4.18-py27_0
    six:                 1.10.0-py27_0
    ssl_match_hostname:  3.4.0.2-py27_1
    testpath:            0.3.1-py27_0
    tornado:             4.5.1-py27_0
    traitlets:           4.3.2-py27_0
    ujson:               1.35-py27_0
    vs2008_runtime:      9.00.30729.5054-0
    wcwidth:             0.1.7-py27_0
    wheel:               0.29.0-py27_0
    widgetsnbextension:  2.0.0-py27_0
    win_unicode_console: 0.5-py27_0
    zlib:                1.2.8-vc9_3       [vc9]

> z:\msarahan\code\conda-build\conda_build\build.py(936)build()
    935         #     make people wait longer only to see an error
--> 936         warn_on_use_of_SRC_DIR(m)
    937

ipdb> subprocess.check_call(['chcp'], shell=True)
Active code page: 65001
```

So creating the env is somehow changing the codepage.  Wow.  Can't wait to find the reason behind this.

**Comment by msarahan** [comment]
Tracked it into Conda.  I suspect that there is a misbehaving post-link script.  Conda issue at https://github.com/conda/conda/issues/5609

**Comment by msarahan** [comment]
Closing.  Ultimate issue was codepage being changed in Qt's post-link script, but then never changed back.  Issue for Qt is at https://github.com/ContinuumIO/anaconda-issues/issues/2713

**Comment by mwcraig** [comment]
Nice sleuthing! Thx for tracking this down.
