### ISSUE TITLE
TypeError in _trim_None_strings

### ISSUE THREAD

**Issue by groutr** [conda/conda-build#1844]
https://github.com/conda/conda-build/blame/master/conda_build/metadata.py#L198
Probably shouldn't use indexing here because sometimes `value` is a set.
This could be a bug elsewhere, though, causing values to be sets instead of lists.
```
value == [{'intradependencies': {'binutils_linux-cos5-x86_64'}, 'name': 'gcc_linux-cos5-x86_64', 'script': 'install-gcc.sh', 'pin_downstream': ['libgcc_linux-cos5-x86_64 >=6.3.0,<7'], 'requirements': ['binutils_linux-cos5-x86_64']}, {'intradependencies': {'gcc_linux-cos5-x86_64'}, 'name': 'gxx_linux-cos5-x86_64', 'script': 'install-g++.sh', 'pin_downstream': ['libstdcxx_linux-cos5-x86_64 >=6.3.0,<7'], 'requirements': ['gcc_linux-cos5-x86_64']}, {'intradependencies': {'gcc_linux-cos5-x86_64'}, 'name': 'gfortran_linux-cos5-x86_64', 'script': 'install-gfortran.sh', 'pin_downstream': ['libgfortran_linux-cos5-x86_64 >=6.3.0,<7'], 'requirements': ['gcc_linux-cos5-x86_64']}, {'version': '2.26', 'name': 'binutils_linux-cos5-x86_64', 'script': 'install-binutils.sh', 'intradependencies': set()}, {'intradependencies': set(), 'name': 'libstdcxx_linux-cos5-x86_64', 'script': 'install-libstdc++.sh'}, {'intradependencies': set(), 'name': 'libgcc_linux-cos5-x86_64', 'script': 'install-libgcc.sh'}, {'intradependencies': set(), 'name': 'libgfortran_linux-cos5-x86_64', 'script': 'install-libgfortran.sh'}] <class 'list'>
value == {'binutils_linux-cos5-x86_64'} <class 'set'>
Traceback (most recent call last):
  File "/home/osboxes/miniconda3/bin/conda-build", line 11, in <module>
    load_entry_point('conda-build', 'console_scripts', 'conda-build')()
  File "/home/osboxes/conda-build/conda_build/cli/main_build.py", line 313, in main
    execute(sys.argv[1:])
  File "/home/osboxes/conda-build/conda_build/cli/main_build.py", line 304, in execute
    noverify=args.no_verify)
  File "/home/osboxes/conda-build/conda_build/api.py", line 159, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/osboxes/conda-build/conda_build/build.py", line 1395, in build_tree
    built_packages=built_packages)
  File "/home/osboxes/conda-build/conda_build/build.py", line 900, in build
    m.parse_until_resolved()
  File "/home/osboxes/conda-build/conda_build/metadata.py", line 662, in parse_until_resolved
    self.parse_again(permit_undefined_jinja=True)
  File "/home/osboxes/conda-build/conda_build/metadata.py", line 605, in parse_again
    path=self.meta_path)
  File "/home/osboxes/conda-build/conda_build/metadata.py", line 243, in parse
    return sanitize(res)
  File "/home/osboxes/conda-build/conda_build/metadata.py", line 298, in sanitize
    _trim_None_strings(meta)
  File "/home/osboxes/conda-build/conda_build/metadata.py", line 201, in _trim_None_strings
    trimmed_dict = _trim_None_strings(d)
  File "/home/osboxes/conda-build/conda_build/metadata.py", line 199, in _trim_None_strings
    if hasattr(value[0], 'keys'):
TypeError: 'set' object does not support indexing
```

The change I think needs to happen is:
```
value[0]  --->  next(iter(value))  # Since we know at this point that value is iterable.
```
Since we are iterating through the entire container, all iterable containers can be valid instead of just the indexable containers.

**Comment by groutr** [comment]
I'll open a PR when I can find the time to commit this change to a branch.

**Comment by msarahan** [comment]
Thanks Ryan, especially for the good suggested fix.

**Comment by groutr** [comment]
@msarahan What is the preference for checking attributes with `hasattr` vs instance checks against built in types or abstract types?

**Comment by msarahan** [comment]
Whatever is simplest in any given case? For strings I most often use isinstance with string_types.  Here, I think I'd use hasattr and check for ``__iter__``

**Comment by msarahan** [comment]
Fixed in https://github.com/conda/conda-build/commit/36b079030a0688b9f072b67240c1f33558d86e4f - Thanks @groutr
