### ISSUE TITLE
Decompressing tarball fails Windows Python 2.7

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1845]
Running into an issue decompressing a tarball in PR ( https://github.com/conda-forge/sphinx-feedstock/pull/15 ) on Windows Python 2.7. Does not happen on Python 3.5 or 3.6. Please see the [AppVeyor builds]( https://ci.appveyor.com/project/conda-forge/sphinx-feedstock/build/1.0.40 ) for details. Seems like some sort of encoding issue with the path, but am not sure.

<details>

```python
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1484, in build_tree
    config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 983, in build
    config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\render.py", line 86, in parse_or_try_download
    source.provide(metadata, config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 505, in provide
    unpack(metadata, config=config)
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 90, in unpack
    tar_xf(src_path, config.work_dir)
  File "C:\Miniconda\lib\site-packages\conda_build\utils.py", line 314, in tar_xf
    t.extractall(path=dir_path)
  File "C:\Miniconda\lib\tarfile.py", line 2081, in extractall
    self.extract(tarinfo, path)
  File "C:\Miniconda\lib\tarfile.py", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Miniconda\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 48: ordinal not in range(128)
```

</details>
<br>
cc @chohner @willingc @humitos

**Comment by msarahan** [comment]
Your build log shows that you're using conda-build 2.1.4.  Conda-build 2.1.6 includes a fix for this: https://github.com/conda/conda-build/pull/1779

Please do not file issues if you have not at least tried the latest version of conda-build.

**Comment by jakirkham** [comment]
I'm confused. Does that mean it is fixed with 2.1.6? Have others experienced this issue?

**Comment by msarahan** [comment]
I believe so. The person who put up the PR that I linked to seemed to have
had the same issue.

**Comment by chohner** [comment]
Fixed it for me locally! Thanks

**Comment by jakirkham** [comment]
It seems after retesting this is fixed. Thanks @msarahan.

**Comment by willingc** [comment]
Thanks everyone for sorting this out. The documentation users thank you too ;-)
