### ISSUE TITLE
Unicode Env Variable CONDA_ALLOW_SOFTLINKS causes Issues on py27 on windows

### ISSUE THREAD

**Issue by stuertz** [conda/conda-build#1865]
Hi,
I retrieved the following traceback while using conda-smithy on windows with py27:
conda-build: 2.1.7
conda-smithy: 2.2.1

```
Traceback (most recent call last):
  File "C:\Users\js\AppData\Local\Continuum\Miniconda2\Scripts\conda-smithy-script.py", line 5, in <module>
    sys.exit(conda_smithy.cli.main())
  File "C:\Users\js\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda_smithy\cli.py", line 275, in main
    args.subcommand_func(args)
  File "C:\Users\js\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda_smithy\cli.py", line 186, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "C:\Users\js\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda_smithy\configure_feedstock.py", line 674, in main
    remove_file(os.path.join(forge_dir, old_file))
  File "C:\Users\js\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda_smithy\feedstock_io.py", line 68, in remove_file
    repo.index.remove([filename])
  File "C:\Users\js\AppData\Local\Continuum\Miniconda2\lib\site-packages\git\index\util.py", line 58, in post_clear_cache_if_not_raised
    rval = func(self, *args, **kwargs)
  File "C:\Users\js\AppData\Local\Continuum\Miniconda2\lib\site-packages\git\index\util.py", line 76, in check_default_index
    return func(self, *args, **kwargs)
  File "C:\Users\js\AppData\Local\Continuum\Miniconda2\lib\site-packages\git\index\base.py", line 868, in remove
    removed_paths = self.repo.git.rm(args, paths, **kwargs).splitlines()
  File "C:\Users\js\AppData\Local\Continuum\Miniconda2\lib\site-packages\git\cmd.py", line 424, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "C:\Users\js\AppData\Local\Continuum\Miniconda2\lib\site-packages\git\cmd.py", line 873, in _call_process
    return self.execute(call, **_kwargs)
  File "C:\Users\js\AppData\Local\Continuum\Miniconda2\lib\site-packages\git\cmd.py", line 598, in execute
    **subprocess_kwargs
  File "C:\Users\js\AppData\Local\Continuum\Miniconda2\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Users\js\AppData\Local\Continuum\Miniconda2\lib\subprocess.py", line 964, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
```

I turns out that the reason was 
CONDA_ALLOW_SOFTLINKS false 
which key and value is <type 'unicode'> <type 'unicode'>

This is implicitly added by using future imports (unicode_literals)

My local Quickfix was using:
    os.environ[str('CONDA_ALLOW_SOFTLINKS')] = str('false')
instead of 
   os.environ['CONDA_ALLOW_SOFTLINKS'] = 'false'

But that can't be the full answer and may not work with all variants.

Version Info:
`λ conda info
Current conda install:

               platform : win-32
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.1.7
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : C:\Users\js\AppData\Local\Continuum\Miniconda2  (writable)
    default environment : C:\Users\js\AppData\Local\Continuum\Miniconda2
       envs directories : C:\Users\js\AppData\Local\Continuum\Miniconda2\envs
          package cache : C:\Users\js\AppData\Local\Continuum\Miniconda2\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-32
                          https://conda.anaconda.org/conda-forge/noarch
                          file:///Z:/js/public_html/conda/win-32
                          file:///Z:/js/public_html/conda/noarch
                          https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : c:\users\js\Documents\.condarc
           offline mode : False`

**Comment by stuertz** [comment]
This seems already be fixed in 2.1.x branch by https://github.com/conda/conda-build/commit/f189cd2cdad7e47778bfb3bb13fbf3046c61e915
