### ISSUE TITLE
Windows error: "TypeError: environment can only contain strings"

### ISSUE THREAD

**Issue by jiffyclub** [conda/conda-build#188]
I am trying to build https://github.com/jiffyclub/pandana-conda on Windows 8. When I run `conda build` I get the following error:

``` pytb
[pandana] C:\Users\Workstation>conda build --python 2.7 pandana-conda
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda_build\main_build.py", line 111, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda_build\main_build.py", line 309, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda_build\main_build.py", line 241, in execute
    m = MetaData(recipe_dir)
  File "C:\Anaconda\lib\site-packages\conda_build\metadata.py", line 194, in __init__
    self.meta = parse(get_contents(self.meta_path))
  File "C:\Anaconda\lib\site-packages\conda_build\metadata.py", line 175, in get
_contents
    env.globals.update(context_processor())
  File "C:\Anaconda\lib\site-packages\conda_build\jinja_context.py", line 47, in context_processor
    ctx = get_environ()
  File "C:\Anaconda\lib\site-packages\conda_build\environ.py", line 78, in get_dict
    d.update(**get_git_build_info(d['SRC_DIR']))
  File "C:\Anaconda\lib\site-packages\conda_build\environ.py", line 43, in get_git_build_info
    env=env)
  File "C:\Anaconda\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Anaconda\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
```

Here's the output of `conda info`:

```
[pandana] C:\Users\Workstation>conda info
Current conda install:

             platform : win-64
        conda version : 3.6.2
  conda-build version : 1.8.0
       python version : 2.7.5.final.0
     requests version : 2.3.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda\envs\pandana
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://conda.binstar.org/synthicity/win-64/
                        http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : C:\Users\Workstation\.condarc
    is foreign system : False
```

I apologize if this is something stupid, I'm very to new to building stuff on Windows.

**Comment by jschueller** [comment]
seems I encoutered this one too just now, regardless of the python version:
https://ci.appveyor.com/project/conda-forge/pyfmi-feedstock/build/1.0.13/job/08c8ss2cftvemy4a

**Comment by SylvainCorlay** [comment]
Same here. I encounter this error on all python versions.

**Comment by msarahan** [comment]
There was a conda issue related to this some time ago.  Conda was putting
in environment variables after conda-build converted them all, IIRC.  What
conda version are you running?

**Comment by SylvainCorlay** [comment]
This is on conda-forge. I have the following versions:

```
    conda: 4.3.11-py27_0 --> 4.3.14-py27_1
    anaconda-client: 1.5.1-py27_0   conda-forge
    conda-build:     2.1.6-py27_0   conda-forge
    conda-verify:    2.0.0-py27_0   conda-forge
```

The last succesfull build was using conda-build 2.1.4

**Comment by SylvainCorlay** [comment]
Apparently, lots of conda-forge feedstock have this issue, with python 2 only.

**Comment by msarahan** [comment]
Sorry, I'll try to fix it quickly.  PRs welcome, too.
