### ISSUE TITLE
ImportError: cannot import name 'get_proxy_servers'

### ISSUE THREAD

**Issue by tisaconundrum2** [conda/conda-build#1890]
$ conda skeleton pypi pyinstrument
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\ANACONDA3\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\ANACONDA3\lib\site-packages\conda_build\main_skeleton.py", line 298, in main
    args_func(args, p)
  File "C:\ANACONDA3\lib\site-packages\conda_build\main_build.py", line 493, in args_func
    args.func(args, p)
  File "C:\ANACONDA3\lib\site-packages\conda_build\main_skeleton.py", line 302, in execute
    import conda_build.pypi as pypi
  File "C:\ANACONDA3\lib\site-packages\conda_build\pypi.py", line 30, in <module>
    from conda.config import get_proxy_servers
ImportError: cannot import name 'get_proxy_servers'

**Comment by msarahan** [comment]
What version of conda and conda-build are you using?  Please try updating them both.

**Comment by msarahan** [comment]
Closing due to inactivity.  @tisaconundrum2 If you'd like to reopen this, please feel free.
