### ISSUE TITLE
Building from git repository with a single directory on root fails during 'git log'

### ISSUE THREAD

**Issue by nicoddemus** [conda/conda-build#1910]
Consider this `meta.yaml`:

```yaml
package:
  name: foobar
  version: 1.0

source:
  git_url: ssh://git@eden.fln.esss.com.br:7999/~bruno/foobar.git
  git_rev: master
```

The `foobar` repository contains this file structure:

```
src/
  foobar.py
```

When building with conda-build `2.1.9`, I get this error:

```
λ conda build foobar\
BUILD START: foobar-1.0-0
Cloning into 'E:\Miniconda\conda-bld\foobar_1491486042312\work'...
done.
checkout: u'd3e664c33'
Note: checking out 'd3e664c33'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at d3e664c... Rename source to src
fatal: Not a git repository: 'E:\Miniconda\conda-bld\foobar_1491486042312\work\src\.git'
Traceback (most recent call last):
  File "E:\Miniconda\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "E:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 334, in main
    execute(sys.argv[1:])
  File "E:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 325, in execute
    noverify=args.no_verify)
  File "E:\Miniconda\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "E:\Miniconda\lib\site-packages\conda_build\build.py", line 1503, in build_tree
    config=config)
  File "E:\Miniconda\lib\site-packages\conda_build\build.py", line 1051, in build
    config=config)
  File "E:\Miniconda\lib\site-packages\conda_build\render.py", line 86, in parse_or_try_download
    source.provide(metadata, config=config)
  File "E:\Miniconda\lib\site-packages\conda_build\source.py", line 521, in provide
    git = git_source(metadata, config=config)
  File "E:\Miniconda\lib\site-packages\conda_build\source.py", line 250, in git_source
    git, mirror_dir, config.work_dir, git_url, config, git_ref, git_depth, True)
  File "E:\Miniconda\lib\site-packages\conda_build\source.py", line 216, in git_mirror_checkout_recursive
    git_info(config)
  File "E:\Miniconda\lib\site-packages\conda_build\source.py", line 283, in git_info
    raise Exception("git error: %s" % str(e))
Exception: git error: Command '['git', 'log', '-n1']' returned non-zero exit status 128
```

The important bit is this:

```
fatal: Not a git repository: 'E:\Miniconda\conda-bld\foobar_1491486042312\work\src\.git'
```

It seems conda-build is assuming the root git directory is `$SRC_DIR\src` instead of `$SRC_DIR`.

If I add a new directory to the root of the repository:

```
src/
  foobar.py
tools/
  foobar.py
```

The the build passes as expected. It seems there's a different  behavior in case there's a single directory at the repository root, but I couldn't find anything related to that in the docs.

Also, the build also passes with conda-build `1.21.11` (in both scenarios).

cc @gabrielmarcilio

**Comment by msarahan** [comment]
Sorry for the confusion.  I think there used to be a bifurcation in logic that I removed to simplify things.  I apparently need to add that back in, or some compensation mechanism.  It's there so that when you extract tarballs that contain just one folder (as they all should, to prevent messes), then the root is one level deeper, so that people don't have to figure out that cd command in their recipe.

This issue is well-timed.  I need to figure out the ability to have multiple source inputs, and in doing so, I'll have to figure out a better way to do this.

**Comment by nicoddemus** [comment]
@msarahan OK, thanks for the quick response!

Since we own that repository, as a workaround we will just add a new directory to the root repository. 👍
