### ISSUE TITLE
conda skeleton pypi refuses to find package which works for pip

### ISSUE THREAD

**Issue by somada141** [conda/conda-build#198]
I've been following the instructions in the binstar docs [here](http://binstar-client.readthedocs.org/en/latest/pypi_to_binstar.html) in order to upload my PyPI package, [FieldPy](https://pypi.python.org/pypi/FieldPy) but I've been facing tons of issues and errors from conda.

Before I start listing the errors, here's the output of `conda info --all`:

```
Current conda install:

             platform : osx-64
        conda version : 3.6.2
  conda-build version : 1.3.1
       python version : 2.7.8.final.0
     requests version : 2.4.0
     root environment : //anaconda  (writable)
  default environment : //anaconda
     envs directories : //anaconda/envs
        package cache : //anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
          config file : None
    is foreign system : False

# conda environments:
#
py27                     //anaconda/envs/py27
py34                     //anaconda/envs/py34
root                  *  //anaconda

sys.version: 2.7.8 |Anaconda 2.0.0 (x86_64)| (default...
sys.prefix: //anaconda
sys.executable: //anaconda/bin/python
conda location: //anaconda/lib/python2.7/site-packages/conda
conda-build: //anaconda/bin/conda-build
conda-convert: //anaconda/bin/conda-convert
conda-index: //anaconda/bin/conda-index
conda-metapackage: //anaconda/bin/conda-metapackage
conda-pipbuild: //anaconda/bin/conda-pipbuild
conda-skeleton: //anaconda/bin/conda-skeleton

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
DYLD_LIBRARY_PATH: <not set>
PATH: /opt/local/bin:/opt/local/sbin://anaconda/bin:/Users/somada141/Library/Application Support/GoodSync:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/texbin
PYTHONHOME: <not set>
PYTHONPATH: /Users/somada141/Data/Development

License directories:
    //anaconda/licenses
    /Users/somada141/.continuum
    /Users/somada141/Library/Application Support/Anaconda
License files (license*.txt):
    /Users/somada141/.continuum/license_academic_20140831211334.txt
               Reading license file : 1
                    Signature valid : 1
                       Vendor match : 1
                            product : u'Academic'
                           packages : u'numbapro mkl iopro'
                           end_date : u'2015-08-31'
                               type : None
Package/feature end dates:
    numbapro        : 2015-08-31
    iopro           : 2015-08-31
    mkl             : 2015-08-31
```

When I try to create a skeleton for a given version being v0.1.5 with:

```
conda skeleton pypi FieldPy --version 0.1.5
```

I get

```
Error: Version 0.1.5 of FieldPy is not available on PyPI.
```

while as you can see from the [PyPI page](https://pypi.python.org/pypi/FieldPy) is clearly available.

Then I say 'ok forget the version' and try:

```
conda skeleton pypi FieldPy
```

which gives me

```
Using url UNKNOWN () for FieldPy.
Using "LICENSE.txt" for the license
Downloading FieldPy (use --no-download to skip this step)
Traceback (most recent call last):
  File "//anaconda/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "//anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 124, in main
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 135, in execute
    pypi.main(args, parser)
  File "//anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 305, in main
    download(d['pypiurl'], join(SRC_CACHE, d['filename']))
  File "//anaconda/lib/python2.7/site-packages/conda/fetch.py", line 271, in download
    raise RuntimeError("Could not open '%s': %s" % (url, e))
RuntimeError: Could not open 'UNKNOWN': Invalid URL u'UNKNOWN': No schema supplied. Perhaps you meant http://UNKNOWN?
```

So I say 'lets point straight to the tarball using the URL given by PyPI' and use

```
conda skeleton pypi FieldPy --pypi-url https://pypi.python.org/packages/source/F/FieldPy/FieldPy-0.1.5.tar.gz
```

which gives me:

```
Traceback (most recent call last):
  File "//anaconda/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "//anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 124, in main
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 135, in execute
    pypi.main(args, parser)
  File "//anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 158, in main
    client = ServerProxy(args.pypi_url)
  File "//anaconda/lib/python2.7/xmlrpclib.py", line 1547, in __init__
    type, uri = urllib.splittype(uri)
  File "//anaconda/lib/python2.7/urllib.py", line 1074, in splittype
    match = _typeprog.match(url)
TypeError: expected string or buffer
```

Any idea what's going on?

**Comment by hargup** [comment]
@asmeurer @somada141 `conda-skeleton` now works with `FieldPy` both with and without `--version 0.1.5`, if it was a bug with PyPI it has probably been fixed and I guess the issue here needs to be closed.

**Comment by asmeurer** [comment]
I don't know if the bug was fixed or just masked by the FieldPy releases being deleted. At any rate, it didn't look like a conda-build issue.

**Comment by rainwoodman** [comment]
One of my package got bitten by this as well.

If we do not assert the version (`--version`) is in the 'released' list, we can work around this issue.

**Comment by msarahan** [comment]
reopening until more permanent fix (perhaps that suggested by @rainwoodman) is put in place.

**Comment by rainwoodman** [comment]
I put a cleaner workaround. in PR #1698

**Comment by jakirkham** [comment]
This is solved now, right?

**Comment by rainwoodman** [comment]
Yes. I suppose so -- the workaround has been merged.

**Comment by msarahan** [comment]
Thanks, closing.
