### ISSUE TITLE
conda develop ignores the environment's python version

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#1990]
_From @cubranic on February 11, 2017 0:56_

When I'm working in a environment that uses Python 2.7, `conda develop tries to install into `lib/python3.5/site-packages`:

```
$ conda create --name py27 python=2
...
$ source activate py27
(py27) $ git clone https://github.com/pypa/sampleproject
(py27) $ cd sampleproject/
(py27) $ type python
python is hashed (/Users/davor/anaconda3/envs/py27/bin/python)
(py27) $ python -V
Python 2.7.13 :: Continuum Analytics, Inc.
(py27) $ conda develop .
Traceback (most recent call last):
  File "/Users/davor/anaconda3/bin/conda-develop", line 6, in <module>
    sys.exit(conda_build.cli.main_develop.main())
  File "/Users/davor/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_develop.py", line 72, in main
    return execute(sys.argv[1:])
  File "/Users/davor/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_develop.py", line 68, in execute
    build_ext=args.build_ext, clean=args.clean, uninstall=args.uninstall)
  File "/Users/davor/anaconda3/lib/python3.5/site-packages/conda_build/api.py", line 203, in develop
    return execute(recipe_dir, prefix, no_pth_file, build_ext, clean, uninstall)
  File "/Users/davor/anaconda3/lib/python3.5/site-packages/conda_build/develop.py", line 191, in execute
    write_to_conda_pth(sp_dir, pkg_path)
  File "/Users/davor/anaconda3/lib/python3.5/site-packages/conda_build/develop.py", line 50, in write_to_conda_pth
    with open(c_file, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/davor/anaconda3/envs/py27/lib/python3.5/site-packages/conda.pth'
```

Running `pip install -e .` installs (correctly) into `~/anaconda3/envs/py27/lib/python2.7/site-packages/`

_Copied from original issue: conda/conda#4605_

**Comment by kalefranz** [comment]
_From @oulenz on March 14, 2017 10:21_

I think my issue may have the same cause: running `develop` in an environment that uses 3.6 has no effect because it updates `conda.pth` in `/python3.5` 

I've had a look in the source code of conda-build and I don't understand why this would go wrong. It calls `sys.version_info.minor`, which reports 6 if I call it, both in my working environment and in the root environment.

**Comment by sklam** [comment]
I am seeing a similar error and downgrading to 2.1.10 works.

```bash
(pycudf_notebook_py35) appuser@e51ca28d64eb:~/pygdf$ conda develop .
Traceback (most recent call last):
  File "/home/appuser/Miniconda3/bin/conda-develop", line 6, in <module>
    sys.exit(conda_build.cli.main_develop.main())
  File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda_build/cli/main_develop.py", line 72, in main
    return execute(sys.argv[1:])
  File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda_build/cli/main_develop.py", line 68, in execute
    build_ext=args.build_ext, clean=args.clean, uninstall=args.uninstall)
  File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 219, in develop
    return execute(recipe_dir, prefix, no_pth_file, build_ext, clean, uninstall)
  File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda_build/develop.py", line 175, in execute
    write_to_conda_pth(sp_dir, pkg_path)
  File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda_build/develop.py", line 50, in write_to_conda_pth
    with open(c_file, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/appuser/Miniconda3/envs/pycudf_notebook_py35/lib/python3.6/site-packages/conda.pth'
(pycudf_notebook_py35) appuser@e51ca28d64eb:~/pygdf$ conda install -nroot conda-build=2.1.10
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/appuser/Miniconda3:

The following packages will be DOWNGRADED due to dependency conflicts:

    conda-build: 2.1.13-py36_0 --> 2.1.10-py36_0

Proceed ([y]/n)? y

conda-build-2. 100% |######################################################################################| Time: 0:00:00   6.62 MB/s
(pycudf_notebook_py35) appuser@e51ca28d64eb:~/pygdf$ conda develop .
added /home/appuser/pygdf
completed operation for: /home/appuser/pygdf
```

This happened inside the docker container described in https://github.com/gpuopenanalytics/demo-docker/tree/104b1eab14bf4021273c02cb7a95ba669cc8b6bb

**Comment by canyon289** [comment]
I also am seeing the same error on Arch Linux

**Comment by moorepants** [comment]
I'm also hitting this issue trying to use conda develop in a Python 2.7 environment.

**Comment by msarahan** [comment]
Sorry, conda develop needs a rework.  Unfortunately, there's a lot of stuff in front of it.

I recommend activating your environment and using ``python setup.py develop`` or ``pip install -e .`` for now.

**Comment by montanaflynn** [comment]
Also hitting this, the problem with `python setup.py` develop or `pip install -e .` is the package(s) don't have a `setup.py` file. The previous admin was adding the path to `PYTHONPATH` environment variable which made the scripts all work with the packages, but anaconda doesn't use that.
