### ISSUE TITLE
Type error when running latest conda-build

### ISSUE THREAD

**Issue by Adriandorr** [conda/conda-build#2013]
When I run conda-build with the latest release  2.1.12 I get the following error. 2.1.10 works fine.

INFO conda_build.build:bundle_conda(861): Packaging my_code-12.0.0-py35_0
found egg: /local/scratch/blah/env-pr/conda-bld/my_code_1494410582628/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.5/site-packages/annotation_service-0.0.0-py3.5.egg
Traceback (most recent call last):
  File "/local/scratch/blah/env-pr/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/local/scratch/blah/env-pr/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 334, in main
    execute(sys.argv[1:])
  File "/local/scratch/blah/env-pr/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 325, in execute
    noverify=args.no_verify)
  File "/local/scratch/blah/env-pr/lib/python3.5/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/local/scratch/blah/env-pr/lib/python3.5/site-packages/conda_build/build.py", line 1516, in build_tree
    config=config)
  File "/local/scratch/blah/env-pr/lib/python3.5/site-packages/conda_build/build.py", line 1152, in build
    built_package = bundlers[output_dict.get('type', 'conda')](output_dict, m, config, env)
  File "/local/scratch/blah/env-pr/lib/python3.5/site-packages/conda_build/build.py", line 882, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/local/scratch/blah/env-pr/lib/python3.5/site-packages/conda_build/build.py", line 824, in post_process_files
    skip_compile_pyc=m.get_value('build/skip_compile_pyc'))
  File "/local/scratch/blah/env-pr/lib/python3.5/site-packages/conda_build/post.py", line 225, in post_process
    remove_easy_install_pth(files, prefix, config, preserve_egg_dir=preserve_egg_dir)
  File "/local/scratch/blah/env-pr/lib/python3.5/site-packages/conda_build/post.py", line 148, in remove_easy_install_pth
    write_pth(egg_path, config=config)
  File "/local/scratch/blah/env-pr/lib/python3.5/site-packages/conda_build/post.py", line 94, in write_pth
    with open(join(utils.get_site_packages(config.build_prefix),
TypeError: get_site_packages() missing 1 required positional argument: 'py_ver'

**Comment by msarahan** [comment]
Thanks for reporting.  Fixed by #2009 - closing.  2.1.13 has been tagged.  Builds should be available soon.
