### ISSUE TITLE
What is the source tree output line for?

### ISSUE THREAD

**Issue by kurtwheeler** [conda/conda-build#2024]
I'm not sure if the issue I'm running into is actually an issue or not because I don't know what's going on. If there is somewhere the answer to my question is documented I am happy to look there, but I couldn't find any documentation on many of the terms that `conda build` spits out. Specifically the terms "source tree" and `work dir` are unclear to me.

I am trying to recursively build recipes so that I can add a lot of packages to conda programmatically. I start by trying to build a package like so:
```
conda build --no-build-id -c r -c Terradue recipes/bioconductor-a4
```

That command spits out an error like this:
```
ERROR: dependencies ‘a4Base’, ‘a4Preproc’, ‘a4Classif’, ‘a4Core’, ‘a4Reporting’ are not available for package ‘a4’
```

I then create a recipe for it's first dependency `a4Base` and try to build it like so:
```
conda build --no-build-id -c Terradue -c r recipes/bioconductor-a4base
```

However that outputs:
```
BUILD START: bioconductor-a4base-1.24.0-0

Source cache directory is: /home/kurt/miniconda3/conda-bld/src_cache
Found source in cache: a4Base_1.24.0.tar.gz
Extracting download
Package: bioconductor-a4base-1.24.0-0
source tree in: /home/kurt/miniconda3/conda-bld/work/a4
+ source /home/kurt/miniconda3/bin/activate /home/kurt/miniconda3/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
+ R CMD INSTALL --build .
* installing to library ‘/home/kurt/miniconda3/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/R/library’
ERROR: dependencies ‘a4Base’, ‘a4Preproc’, ‘a4Classif’, ‘a4Core’, ‘a4Reporting’ are not available for package ‘a4’
* removing ‘/home/kurt/miniconda3/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/R/library/a4’
Traceback (most recent call last):
  File "/home/kurt/miniconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/kurt/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 334, in main
    execute(sys.argv[1:])
  File "/home/kurt/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 325, in execute
    noverify=args.no_verify)
  File "/home/kurt/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/home/kurt/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1518, in build_tree
    config=config)
  File "/home/kurt/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1143, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/home/kurt/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 628, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/home/kurt/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 624, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/home/kurt/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/home/kurt/miniconda3/conda-bld/work/a4/conda_build.sh']' returned non-zero exit status 1.
```

A lot of that output is confusing to me but it seems like instead of trying to build `bioconductor-a4base` it is trying to build `bioconductor-a4` again. The most relevant line seems to be:
```
source tree in: /home/kurt/miniconda3/conda-bld/work/a4
```
which is why I started this issue off by asking about documentation around the `source tree` term. Is this a bug or am I doing something wrong? It seems like I should be able to build a package, have that fail, build a different package, and not have build errors related to the first package. (Note that the first time I ran into this issue was with 2 packages that were much less directly linked. I build a package that had nothing to do at all with A4, and then when I tried to build A4 I got an error message relating to that packge.)

**Comment by msarahan** [comment]
source tree and work_dir are equivalent.  Exactly what a "source tree" contains is defined by the recipe though.  It could be source code, or it could be binaries that you download and then repackage.  Sorry, but it looks like you need to sort out your dependencies.  You need to somehow teach R where those other packages are - that seems to be your current issue.

**Comment by kurtwheeler** [comment]
> source tree and work_dir are equivalent. Exactly what a "source tree" contains is defined by the recipe though. It could be source code, or it could be binaries that you download and then repackage.

Those are examples of implementations of a `source tree`, not an explanation of the abstract concept of `source tree` or `work dir`. I want to understand what they are and how they are used because they seem to be interfering with my build process. 

> You need to somehow teach R where those other packages are - that seems to be your current issue.

I disagree. `a4base` does not need to know where `a4` is. `a4` depends on `a4base`, not the other way around. The issue actually seems to be the opposite. I want conda to forget about `a4` while I build its dependencies, then I can teach R where they are. I've actually found a workaround where I delete the `miniconda3/conda-bld/work` directory after each attempted build. This allows dependencies to build without interacting with packages that depend on them. However it doesn't seem to make sense to me that that workaround should be necessary, so I think this might be a bug. It's hard to say for sure though without understanding what the point of `work_dir` is.

**Comment by msarahan** [comment]
I'm not sure what else to tell you.  ``source tree`` and ``work dir`` are the place where source code is checked out or extracted to.  It's also the directory where the build.sh or bld.bat scripts are executed from (hence work_dir).  This differs from the build and test prefixes, which are conda environments created for the build and test phases, respectively.

Why are you using --no-build-id?  I think conda-build's default behavior of having separate build folders for each recipe would be the same thing as your workaround?

**Comment by msarahan** [comment]
Closing due to inactivity.  If you'd like to discuss this further, please comment.
