### ISSUE TITLE
Patch with non-ascii characters causes UnicodeDecodeError

### ISSUE THREAD

**Issue by rolando** [conda/conda-build#2032]
I'm build a package for conda-forge on appveyor and it fails when applying a patch with non-ascii characters:

```
Downloading source to cache: ftfy-5.1.tar.gz
Downloading https://pypi.io/packages/source/f/ftfy/ftfy-5.1.tar.gz
Success
Applying patch: 'C:\\projects\\ftfy-feedstock\\recipe\\tests-fix-linesep.patch'
Traceback (most recent call last):
  File "C:\Miniconda35\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda35\lib\site-packages\conda_build\cli\main_build.py", line 334, in main
    execute(sys.argv[1:])
  File "C:\Miniconda35\lib\site-packages\conda_build\cli\main_build.py", line 325, in execute
    noverify=args.no_verify)
  File "C:\Miniconda35\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda35\lib\site-packages\conda_build\build.py", line 1510, in build_tree
    config=config)
  File "C:\Miniconda35\lib\site-packages\conda_build\build.py", line 1058, in build
    config=config)
  File "C:\Miniconda35\lib\site-packages\conda_build\render.py", line 86, in parse_or_try_download
    source.provide(metadata, config=config)
  File "C:\Miniconda35\lib\site-packages\conda_build\source.py", line 544, in provide
    apply_patch(src_dir, join(metadata.path, patch), config, git)
  File "C:\Miniconda35\lib\site-packages\conda_build\source.py", line 499, in apply_patch
    patch_args[-1] = _ensure_unix_line_endings(path)
  File "C:\Miniconda35\lib\site-packages\conda_build\source.py", line 420, in _ensure_unix_line_endings
    for line in inputfile:
  File "C:\Miniconda35\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 331: character maps to <undefined>
Command exited with code 1
```

I tried to set the envvar `PYTHONIOENCODING=UTF-8` but had no success.

Full log: https://ci.appveyor.com/project/conda-forge/ftfy-feedstock/build/1.0.11/job/soe86qk54ln43gtd
Patch file: https://github.com/rolando-contrib/ftfy-feedstock/blob/fix-win-build/recipe/tests-fix-linesep.patch

**Comment by msarahan** [comment]
Thanks for reporting this issue.  We've had another recent report of the unix line ending conversion breaking things.  I'll look into it soon.

**Comment by msarahan** [comment]
Sorry, I tinkered with this a bit, trying to get BeautifulSoup's UnicodeDammit to work.  I have no idea what I'm doing.

The best idea I have for a fallback path is to just try the line ending conversion, but if it fails, show a warning and return the original patch file unchanged.  Does this seem like it would work for you?

**Comment by rolando** [comment]
I was able to reproduce with a test

```
def test_ensure_line_endings_with_nonutf8_characters():
    in_path = tempfile.mktemp()
    with open(in_path, "wb") as fp:
        fp.write(b"\xf1\r\n")  # tilde-n encoded in latin1

    out_path = source._ensure_unix_line_endings(in_path)
    with open(out_path, "rb") as fp:
        assert fp.read() == b"\xf1\n"
```

```
Traceback (most recent call last):
  File "/Users/rmax/Projects/gh/conda-build/tests/test_source.py", line 87, in test_ensure_line_endings_with_nonutf8_characters
    out_path = source._ensure_unix_line_endings(in_path)
  File "/Users/rmax/Projects/gh/conda-build/conda_build/source.py", line 439, in _ensure_unix_line_endings
    for line in inputfile:
  File "/Users/rolando/miniconda3/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 0: invalid continuation byte
```

What I think is that the line-ending replacement should be done in bytes and not text. I will make a PR.
