### ISSUE TITLE
Be more verbose when setuptools tries to download deps

### ISSUE THREAD

**Issue by CJ-Wright** [conda/conda-build#2050]
Would it be possible to have a more verbose error than this for when setuptools tries to go get a dependency?
Eg it tells you what dep it tried to get.
`RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://files.pythonhosted.org/packages/source/c/certifi/certifi-2016.9.26.tar.gz#md5=baa81e951a29958563689d868ef1064dr`

**Comment by msarahan** [comment]
Great idea.  It seems like it's always buried in the traceback somewhere.  Having it in the message would be much better.

Not sure when I'll get to this, but it's certainly worth some time.

**Comment by jjhelmus** [comment]
This error message is coming from the [setuptools package](https://github.com/ContinuumIO/anaconda-recipes/tree/master/setuptools) itself due to a [patch](https://github.com/ContinuumIO/anaconda-recipes/blob/master/setuptools/nodownload.patch) made especially for the conda-build environment.

**Comment by msarahan** [comment]
We should still be able to show the offending package name or url, right?

**Comment by jjhelmus** [comment]
The url, from which the package name can be determined, is shown in the trackback but oftentimes it is hard to fine and it seems to be truncated.  I do not believe the package name is accessible in the content where the patch is applied without unwinding the stack, although the url could be parsed to determine the name.  I would be curious why the RunTimeError line is being truncated.  

Here is an example of the full output from a recent build.
```
$ conda build .
BUILD START: pytest-3.1.0-py_0
    (actual version deferred until further download or env creation)

The following NEW packages will be INSTALLED:

    openssl:    1.0.2k-2      defaults
    py:         1.4.33-py36_0 defaults
    python:     3.6.1-2       defaults
    readline:   6.2-2         defaults
    setuptools: 27.2.0-py36_0 defaults
    sqlite:     3.13.0-0      defaults
    tk:         8.5.18-0      defaults
    xz:         5.2.2-1       defaults
    zlib:       1.2.8-3       defaults

Source cache directory is: /home/jhelmus/anaconda3/conda-bld/src_cache
Found source in cache: pytest-3.1.0.tar.gz
Extracting download
BUILD START (revised): pytest-3.1.0-py_0
Package: pytest-3.1.0-py_0
source tree in: /home/jhelmus/anaconda3/conda-bld/pytest_1495572891704/work/pytest-3.1.0
+ source /home/jhelmus/anaconda3/bin/activate /home/jhelmus/anaconda3/conda-bld/pytest_1495572891704/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
+ python setup.py install --single-version-externally-managed --record=record.txt
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    main()
  File "setup.py", line 79, in main
    zip_safe=False,
  File "/home/jhelmus/anaconda3/conda-bld/pytest_1495572891704/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/jhelmus/anaconda3/conda-bld/pytest_1495572891704/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 315, in __init__
  File "/home/jhelmus/anaconda3/conda-bld/pytest_1495572891704/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 361, in fetch_build_eggs
  File "/home/jhelmus/anaconda3/conda-bld/pytest_1495572891704/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 851, in resolve
  File "/home/jhelmus/anaconda3/conda-bld/pytest_1495572891704/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1123, in best_match
  File "/home/jhelmus/anaconda3/conda-bld/pytest_1495572891704/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1135, in obtain
  File "/home/jhelmus/anaconda3/conda-bld/pytest_1495572891704/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 428, in fetch_build_egg
  File "/home/jhelmus/anaconda3/conda-bld/pytest_1495572891704/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 652, in easy_install
  File "/home/jhelmus/anaconda3/conda-bld/pytest_1495572891704/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/package_index.py", line 634, in fetch_distribution
  File "/home/jhelmus/anaconda3/conda-bld/pytest_1495572891704/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/package_index.py", line 469, in find_packages
  File "/home/jhelmus/anaconda3/conda-bld/pytest_1495572891704/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/package_index.py", line 807, in scan_url
  File "/home/jhelmus/anaconda3/conda-bld/pytest_1495572891704/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/package_index.py", line 307, in process_url
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/setuptools-scm/r
Traceback (most recent call last):
  File "/home/jhelmus/anaconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 334, in main
    execute(sys.argv[1:])
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 325, in execute
    noverify=args.no_verify)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1518, in build_tree
    config=config)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1143, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 628, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 624, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/home/jhelmus/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/home/jhelmus/anaconda3/conda-bld/pytest_1495572891704/work/pytest-3.1.0/conda_build.sh']' returned non-zero exit status 1.

```

**Comment by jjhelmus** [comment]
Nevermind about the truncation, it is not happening.  The complete url is getting printed and as a bonus a "r" is appended.
