### ISSUE TITLE
Running "conda skeleton pypi pystan" fails with AttributeError: PROTOCOL_TLS

### ISSUE THREAD

**Issue by jjramsey** [conda/conda-build#2055]
After attempting to run the command "conda skeleton pypi pystan", I get the following errors:
```
Applying patch: '/tmp/tmpvuletw2vconda_skeleton_pystan-2.15.0.1.tar.gz/pypi-distutils.patch'
patching file core.py
Hunk #1 succeeded at 167 with fuzz 2 (offset 1 line).
Traceback (most recent call last):
  File "setup.py", line 239, in <module>
    setup_package()
  File "setup.py", line 223, in setup_package
    metadata['ext_modules'] = cythonize(extensions)
  File "/usr/cta/CSE/Release/anaconda3-4.2.0/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 790, in cythonize
    ctx = c_options.create_context()
  File "/usr/cta/CSE/Release/anaconda3-4.2.0/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 585, in create_context
    self.cplus, self.language_level, options=self)
  File "/usr/cta/CSE/Release/anaconda3-4.2.0/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 75, in __init__
    from . import Builtin, CythonScope
  File "/usr/cta/CSE/Release/anaconda3-4.2.0/lib/python3.5/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/usr/cta/CSE/Release/anaconda3-4.2.0/lib/python3.5/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/usr/cta/CSE/Release/anaconda3-4.2.0/lib/python3.5/site-packages/Cython/Compiler/TreeFragment.py", line 17, in <module>
    from .Visitor import VisitorTransform
  File "Cython/Compiler/Visitor.py", line 15, in init Cython.Compiler.Visitor (/home/ilan/minonda/conda-bld/work/Cython-0.24.1/Cython/Compiler/Visitor.c:19168)
  File "/usr/cta/CSE/Release/anaconda3-4.2.0/lib/python3.5/site-packages/Cython/Compiler/ExprNodes.py", line 40, in <module>
    from .Annotate import AnnotationItem
  File "/usr/cta/CSE/Release/anaconda3-4.2.0/lib/python3.5/site-packages/Cython/Compiler/Annotate.py", line 13, in <module>
    from xml.sax.saxutils import escape as html_escape
  File "/home/jjramsey/conda-bld/skeleton_1495644298097/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.5/xml/sax/saxutils.py", line 6, in <module>
    import os, urllib.parse, urllib.request
  File "/home/jjramsey/conda-bld/skeleton_1495644298097/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.5/urllib/request.py", line 88, in <module>
    import http.client
  File "/home/jjramsey/conda-bld/skeleton_1495644298097/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.5/http/client.py", line 1218, in <module>
    import ssl
  File "/home/jjramsey/conda-bld/skeleton_1495644298097/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.5/ssl.py", line 135, in <module>
    PROTOCOL_SSLv23 = _SSLMethod.PROTOCOL_SSLv23 = _SSLMethod.PROTOCOL_TLS
  File "/home/jjramsey/conda-bld/skeleton_1495644298097/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.5/enum.py", line 274, in __getattr__
    raise AttributeError(name) from None
AttributeError: PROTOCOL_TLS
$PYTHONPATH = /tmp/tmpvuletw2vconda_skeleton_pystan-2.15.0.1.tar.gz/pystan-2.15.0.1:/usr/cta/CSE/Release/tcltk-8.5.19/lib:/usr/cta/CSE/Release/anaconda3-4.2.0/lib/python3.5/site-packages:/usr/cta/CSE/Release/anaconda3-4.2.0/lib/python3.5/lib-dynload:/usr/cta/CSE/Release/anaconda3-4.2.0/lib:/usr/cta/CSE/Datamodels/netcdf-4.3.3/lib:/usr/cta/CSE/Datamodels/hdf5-1.8.13/lib:/usr/cta/CSE/Release/qt-4.8.7/lib:/usr/cta/CSE/Release/flex-2.6.3/lib:/usr/cta/CSE/Release/graphviz-2.36.0/lib:/usr/cta/CSE/Release/boost-1.63.0/lib:/home/jjramsey/script-bin:/data/Projects/FED3/scripts
Error: command failed: /home/jjramsey/conda-bld/skeleton_1495644298097/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python setup.py install
```
So far, I cannot find any file on my system that has the same contents as the "ssl.py" in the directory "home/jjramsey/conda-bld/skeleton_1495644298097/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.5/." Nor does pystan even appear to *have* an "ssl" Python module. It seems bizarre.

**Comment by msarahan** [comment]
I believe the problem is that you have Cython coming from your root environment, not the build environment.  You can specify extra libraries for the skeleton build environment like this:

```
conda skeleton pypi pystan --extra-specs cython --extra-specs numpy
```

This is a pretty recent conda-build addition, so make sure your conda-build version is up to date.  Current version is 2.1.15.

**Comment by jjramsey** [comment]
Or, to be more precise, Cython is coming from my root environment, but the ssl.py module is part of some build environment that conda has cooked up from ... somewhere.

Unfortunately, I can't confirm that your proposed workaround will work. My Anaconda installation was installed by a sysadmin, not me.

**Comment by msarahan** [comment]
I recommend copying the pystan recipe from conda-forge: https://github.com/conda-forge/pystan-feedstock

**Comment by jjramsey** [comment]
Thanks for the tip.

BTW, the more I think about it, the explanation about the problem being Cython coming from my root environment doesn't seem to make much sense. Cython's contribution to the problem is in importing a module that imports another module that imports another module ... that eventually imports the ssl.py file from that long directory "_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.5". Python then chokes on a line in that ssl.py file that assumes that PROTOCOL_TLS is an attribute of _SSLMethod when it isn't. If a different Cython were used that still indirectly imported the ssl.py file, I'd likely have the same problem.

**Comment by jjramsey** [comment]
Copying the pystan recipe was only a marginal help. Conda does build a package, but when it goes to *test* the package, I get the same problem with ssl.py that I did before. Note that I don't have these problems with a manually installed version of PyStan.

(Conda also insists on creating unnecessary dependencies, like installing new versions of Cython and Python, for the created package. Not sure if that issue is tangled up with this one or not.)

**Comment by msarahan** [comment]
This really seems like a PYTHONPATH issue.  The build and test environments should have absolutely no way to find things in the root environment.  Do you have PYTHONPATH or PYTHONHOME set?

**Comment by jjramsey** [comment]
PYTHONPATH is set by the module (i.e. the sort of module used in "module load ..." "module avail" that's used to set and unset environment variables) that the sysadmins use for Anaconda.

**Comment by msarahan** [comment]
Please ask your sysadmins not to set PYTHONPATH.  That's highly likely to break lots of stuff.  Activating conda environments should be adequate.

where they say ```export PYTHONPATH=...```, it would be better if they instead said ```source activate <path to anaconda root install>```

**Comment by jjramsey** [comment]
As a check, I unset PYTHONPATH before running "conda skeleton pypi pystan" and "conda build python".

For "conda skeleton pypi pystan", I got the error "Cython>=0.22 and NumPy are required."

When running "conda build python" in the root environment, the package was built, but at the testing phase, I get the error "Could not open '/usr/cta/CSE/Release/anaconda3-4.2.0/pkgs/pystan-2.15.0.1-mod_jj.tar.bz2.part' for writing" Not sure why a *build* should be touching the root environment at all, especially since the documentation for conda-build doesn't indicate that it should be touched at all.

When running "conda build python" in a clone of the root environment, everything seems to have gotten built and tested correctly. Building the package still seems to involve installing unnecessarily new versions of several packages into some temporary environment, e.g. Cython 0.25.2 is installed even when the version I have as part of the regular Anaconda installation, 0.24.1, suffices. Not sure what that's about.

Still, unsetting PYTHONPATH seems to have addressed the problem.
