### ISSUE TITLE
`conda build` and `conda render` fail with relative git url if run in a non-root environment without `m2-msys2-runtime` installed

### ISSUE THREAD

**Issue by cfobel** [conda/conda-build#2062]
# Setup

Relevant Conda info:

```
Current conda install:

               platform : win-32
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.1.10
         python version : 2.7.12.final.0
       requests version : 2.13.0
       root environment : C:\Users\chris\Miniconda2  (writable)
    default environment : C:\Users\chris\Miniconda2\envs\test-dropbot
```

Steps:

 1. Create empty environment:

        conda create -n test-env

 2. Activate new environment: `activte test-env`
 3. Run `conda render <recipe path>` on a Conda recipe path containing a relative `git_url` path.

# Expected behaviour

Rendered Conda build recipe is printed to `stdout`.

# Observed behaviour

The following error message occurs:

```
Traceback (most recent call last):
  File "C:\Users\chris\Miniconda2\Scripts\conda-render-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_render.main())
  File "C:\Users\chris\Miniconda2\lib\site-packages\conda_build\cli\main_render.py", line 130, in main
    return execute(sys.argv[1:])
  File "C:\Users\chris\Miniconda2\lib\site-packages\conda_build\cli\main_render.py", line 122, in execute
    config=config)
  File "C:\Users\chris\Miniconda2\lib\site-packages\conda_build\render.py", line 156, in render_recipe
    config=config)
  File "C:\Users\chris\Miniconda2\lib\site-packages\conda_build\render.py", line 90, in parse_or_try_download
    metadata.parse_again(config=config, permit_undefined_jinja=False)
  File "C:\Users\chris\Miniconda2\lib\site-packages\conda_build\metadata.py", line 469, in parse_again
    self.meta = parse(self._get_contents(permit_undefined_jinja, config=config),
  File "C:\Users\chris\Miniconda2\lib\site-packages\conda_build\metadata.py", line 819, in _get_contents
    permit_undefined_jinja=permit_undefined_jinja))
  File "C:\Users\chris\Miniconda2\lib\site-packages\conda_build\jinja_context.py", line 213, in context_processor
    ctx = get_environ(config=config, m=initial_metadata)
  File "C:\Users\chris\Miniconda2\lib\site-packages\conda_build\environ.py", line 229, in get_dict
    d.update(meta_vars(m, config))
  File "C:\Users\chris\Miniconda2\lib\site-packages\conda_build\environ.py", line 343, in meta_vars
    git_url = utils.convert_unix_path_to_win(git_url)
  File "C:\Users\chris\Miniconda2\lib\site-packages\conda_build\utils.py", line 457, in convert_unix_path_to_win
    path = subprocess.check_output(cmd.split()).rstrip().rstrip("\\")
  File "C:\Users\chris\Miniconda2\lib\subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Users\chris\Miniconda2\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Users\chris\Miniconda2\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

# Cause

This error occurs because of the way `cygpath` is executed in the `conda_build.utils.convert_unix_path_to_win` function (see [the relevant lines in `conda_build/utils.py`][code]):

```python
def convert_unix_path_to_win(path):
    if external.find_executable('cygpath'):
        cmd = "cygpath -w {0}".format(path)
        if PY3:
            path = subprocess.getoutput(cmd)
        else:
            path = subprocess.check_output(cmd.split()).rstrip().rstrip("\\")

    else:
        path = unix_path_to_win(path)
    return path
```

Note that **the `subprocess` commands are NOT using the full path of the `cygpath` executable**.

Since the `PATH` of an empty Conda environment will not include the `cygpath` executable, an exception occurs (the `cygpath` found by the `external.find_executable` function finds the `cygpath` in the **`root`** environment, but this file is located on the `PATH` of the **`test-env`** environment).

# Proposed fix

This issue can be resolved by using the full path to the `cygpath` executable.  For example:

```python
def convert_unix_path_to_win(path):
    cygpath = external.find_executable('cygpath')
    if cygpath:
        cmd = [cygpath, '-w', path]
        if PY3:
            path = subprocess.getoutput()
        else:
            path = subprocess.check_output(cmd).rstrip().rstrip("\\")

    else:
        path = unix_path_to_win(path)
    return path
```

Note that the `subprocess` commands in the above code use the **full path** returned by `external.find_executable`, rather than simply using `external.find_executable` to determine if `cygpath` is available _somewhere_, including in the root environment.

**A similar fix should also be applied to the [`conda_build.utils.convert_win_path_to_unix` function][code2].**

# Temporary workaround

As a workaround, the `m2-msys2-runtime` package in the `test-env` environment, since this package includes the `cygpath` executable **and** adds it to the `PATH` when the `test-env` environment is activated.

[code]: https://github.com/conda/conda-build/blob/5f46d74919db63a0a5b2ee5e5d70777665f0e579/conda_build/utils.py#L506-L516
[code2]: https://github.com/conda/conda-build/blob/5f46d74919db63a0a5b2ee5e5d70777665f0e579/conda_build/utils.py#L519-L529

**Comment by msarahan** [comment]
Thanks for the very detailed writeup.  Do you mind submitting a PR with a test case and your proposed fix?
