### ISSUE TITLE
KeyError: 'subdir' when running conda index

### ISSUE THREAD

**Issue by waltonseymour** [conda/conda-build#2077]
Stack trace: 

```
Traceback (most recent call last):
  File "/Users/wseymour/miniconda2/bin/conda-index", line 11, in <module>
    load_entry_point('conda-build==3.0.0b1+24.gdaebb67f', 'console_scripts', 'conda-index')()
  File "/Users/wseymour/miniconda2/lib/python2.7/site-packages/conda_build-3.0.0b1+24.gdaebb67f-py2.7.egg/conda_build/cli/main_index.py", line 66, in main
    return execute(sys.argv[1:])
  File "/Users/wseymour/miniconda2/lib/python2.7/site-packages/conda_build-3.0.0b1+24.gdaebb67f-py2.7.egg/conda_build/cli/main_index.py", line 62, in execute
    check_md5=args.check_md5, remove=args.remove)
  File "/Users/wseymour/miniconda2/lib/python2.7/site-packages/conda_build-3.0.0b1+24.gdaebb67f-py2.7.egg/conda_build/api.py", line 348, in update_index
    update_index(path, config, force=force, check_md5=check_md5, remove=remove)
  File "/Users/wseymour/miniconda2/lib/python2.7/site-packages/conda_build-3.0.0b1+24.gdaebb67f-py2.7.egg/conda_build/index.py", line 128, in update_index
    subdir = d['subdir']
KeyError: 'subdir'
```

**Comment by msarahan** [comment]
Thanks for testing the beta! Please update to rc2. I don't specifically remember this problem (or a fix), but let's start there.

Beyond that, this may be caused by a faulty package built by a buggy conda build. Does the error occur with all folders you try to index? Are you able to isolate one or more packages that cause the traceback?

**Comment by waltonseymour** [comment]
It appears to be all directories. I fixed this through in https://github.com/conda/conda-build/commit/a1014c9f3eede5e8b1153116b2fa5739c5242210 .
It's assigned and never read so seems like a bug.

**Comment by msarahan** [comment]
Thank you @waltonseymour.  I'll incorporate your changes in the 3.0.0 release.
