### ISSUE TITLE
Unsatisfiable dependency in test phase has misleading error message

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#2083]
From @gbrener via flowdock:

I'm having an issue with conda-build that only happens for Python 3.6 on Ubuntu 14 (also tested in 3.5 and 2.7 - 3.5 and 2.7 pass on OSX and Ubuntu, all 3 versions pass on OSX). The failure happens right after the TEST section starts (output is from a Travis-CI machine):

```
TEST START: /home/travis/miniconda/conda-bld/linux-64/elm-0.2.0-py36_59.tar.bz2
Deleting work directory, /home/travis/miniconda/conda-bld/elm_1496784092513/work
Missing dependency elm, but found recipe directory, so building elm first
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build\
.py", line 334, in main
    execute(sys.argv[1:])
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build\
.py", line 325, in execute
    noverify=args.no_verify)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/api.py", line \
97, in build
    need_source_download=need_source_download, config=config)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/build.py", lin\
e 1501, in build_tree
    config=config)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/render.py", li\
ne 145, in render_recipe
    m = MetaData(recipe_dir, config=config)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/metadata.py", \
line 422, in __init__
    self.meta_path = find_recipe(path)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/utils.py", lin\
e 726, in find_recipe
    raise IOError("No meta.yaml or conda.yaml files found in %s" % path)
OSError: No meta.yaml or conda.yaml files found in /home/travis/build/ContinuumIO/elm/elm
```

The directory it's looking in for the meta.yaml is incorrect (it should be /home/travis/build/ContinuumIO/elm/conda.recipe), but the failure seems to be happening before that due to a dependency conflict. conda doesn't say what the conflict is, however.
I've tried running conda build with the --debug flag and am investigating two possible causes:
In the Python 3.6's debug output, it says "Locally invalidating cached repodata", which may be causing conda-build to forget about the package it just built
In the python 3.5 build, conda-build shows a "caching error" in the debug output, manually removing the package to compensate... This looked strange and wasn't happening in the 3.6 build

**Comment by msarahan** [comment]
We have determined that the problem was a dependency that was not available for Python 3.6.  Conda-build needs to present this information more clearly, rather than that inscrutable traceback.

**Comment by gbrener** [comment]
Thanks for following up @msarahan .

**Comment by j3mdamas** [comment]
Hi all,

I get a similar error, but putting python as the missing dependency, which is quite puzzling:

```
Missing dependency python, but found recipe directory, so building python first
Traceback (most recent call last):
  File "/home/joao/miniconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/joao/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 340, in main
    execute(sys.argv[1:])
  File "/home/joao/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 331, in execute
    noverify=args.no_verify)
  File "/home/joao/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 183, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/joao/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1598, in build_tree
    bypass_env_check=True)
  File "/home/joao/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 510, in render_recipe
    m = MetaData(recipe_dir, config=config)
  File "/home/joao/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 672, in __init__
    self.meta_path = find_recipe(path)
  File "/home/joao/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 787, in find_recipe
    raise IOError("No meta.yaml or conda.yaml files found in %s" % path)
OSError: No meta.yaml or conda.yaml files found in <snipped-folder-path>
Missing dependency python, but found recipe directory, so building python first
Traceback (most recent call last):
  File "/home/joao/miniconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/joao/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 340, in main
    execute(sys.argv[1:])
  File "/home/joao/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 331, in execute
    noverify=args.no_verify)
  File "/home/joao/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 183, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/joao/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1598, in build_tree
    bypass_env_check=True)
  File "/home/joao/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 510, in render_recipe
    m = MetaData(recipe_dir, config=config)
  File "/home/joao/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 672, in __init__
    self.meta_path = find_recipe(path)
  File "/home/joao/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 787, in find_recipe
    raise IOError("No meta.yaml or conda.yaml files found in %s" % path)
OSError: No meta.yaml or conda.yaml files found in <snipped-folder-path>
make: *** [all] Error 1
```

I am using conda 3.0.3. If I downgrade to 2.1.17, it works fine. The folder path that I omit is the source in the `meta.yaml` file.

Do you guys think it's related?
