### ISSUE TITLE
3.0.5 python x.x use throws exception

### ISSUE THREAD

**Issue by jhunkeler** [conda/conda-build#2197]
💥 

## Relevant example recipe bits:

```yaml
package:
  name: example_pkg
  version: 1.0.0

requirements:
  build:
    - numpy
    - python x.x

  run:
    - numpy
    - python x.x
```

## Fails with

```python
conda.exceptions.NoPackagesFoundError: Package missing in current osx-64 channels:
  - python x.x.*
```

and 

```python
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: ['python']
```

## Full traceback

```python
$ conda build example_pkg --python=3.5 --numpy=1.12

Leaving build/test directories:
  Work:	 ../../../../home/jhunk/anaconda3/conda-bld/work
  Test:	 ../../../../home/jhunk/anaconda3/conda-bld/test_tmp
Leaving build/test environments:
  Test:	source activate  ../../../../home/jhunk/anaconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
  Build:	source activate  ../../../../home/jhunk/anaconda3/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh


Traceback (most recent call last):
  File "/home/jhunk/anaconda3/lib/python3.5/site-packages/conda_build/environ.py", line 700, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/jhunk/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/home/jhunk/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 634, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/home/jhunk/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 811, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/home/jhunk/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 850, in solve
    reduced_index = self.get_reduced_index(specs)
  File "/home/jhunk/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 376, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/home/jhunk/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 302, in verify_specs
    raise NoPackagesFoundError(bad_deps)
conda.exceptions.NoPackagesFoundError: Package missing in current osx-64 channels:
  - python x.x.*

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jhunk/anaconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/jhunk/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/home/jhunk/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/home/jhunk/anaconda3/lib/python3.5/site-packages/conda_build/api.py", line 183, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/jhunk/anaconda3/lib/python3.5/site-packages/conda_build/build.py", line 1615, in build_tree
    built_packages=built_packages,
  File "/home/jhunk/anaconda3/lib/python3.5/site-packages/conda_build/build.py", line 928, in build
    channel_urls=tuple(m.config.channel_urls))
  File "/home/jhunk/anaconda3/lib/python3.5/site-packages/conda_build/environ.py", line 702, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: ['python']
```

**Comment by msarahan** [comment]
I think you're confusing numpy x.x with python x.x.  python x.x has never been supported.  There are issues with numpy x.x, and I'm working on those now.

**Comment by jhunkeler** [comment]
Ok crap -- I guess I learn something new every day with this thing. We've been doing it wrong for years then.

In older versions if/when you specified `- python x.x` in the recipe but didn't issue `--python=[some_version]` then `conda build` would halt with a message like: "python x.x missing argument" or something that effect.

Logic: At some point in 2015 `--python=` didn't work correctly so we used the `x.x` selector method as "insurance" to force conda build to grab the correct version of python at build-time.

**Comment by msarahan** [comment]
I'm going to have to go back and search the source to understand why python x.x used to work.  The original "x.x" PR was https://github.com/conda/conda-build/pull/573

This comment especially is interesting: https://github.com/conda/conda-build/pull/573/files#r39464074

I think variants in conda-build 3 will make your life much better: https://conda.io/docs/building/variants.html

**Comment by msarahan** [comment]
This does work on the 2.1.x, so I guess it was an undocumented feature.  I think it's not much effort to fix this.  I'll try to go ahead and make it work again, but it'll show a deprecation warning.

**Comment by msarahan** [comment]
Hmm... so sort of half-fixed it.  It no longer throws any error, and it respects any --python argument you pass.  The issue is that it never raises an error - even if --python is missing.  How much of a problem will that be for you?  Basically, it doesn't work anymore because we're always setting it to the variant value, and there are always defaults for that, so it never raises an error.  There's no way to say "if x.x is present and python isn't set in the variant" because python is always set in the variant.

**Comment by jhunkeler** [comment]
Thanks for keeping my special bug alive... at least for a while longer. Looks like we're going to try to transition away from the 'x.x' selector before the new "variants" feature take over the world. 😏
