### ISSUE TITLE
Unexpected error with conda skeleton pypi Spfpm

### ISSUE THREAD

**Issue by xanderhsia** [conda/conda-build#220]
I got an unexpected error when using skeleton on a pypi package spfpm
The exception is TypeError: unorderable types: str() < int()
Posted the error message and the conda info below.

(bigbang)~ 7379 conda skeleton pypi SPFPM                                                                        1 ↵
SPFPM not found, trying Spfpm
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda-build/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/ahhsia/.miniconda/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/Users/ahhsia/.miniconda/lib/python3.4/site-packages/conda_build/main_skeleton.py", line 125, in main
    args_func(args, p)
  File "/Users/ahhsia/.miniconda/lib/python3.4/site-packages/conda_build/main_build.py", line 307, in args_func
    args.func(args, p)
  File "/Users/ahhsia/.miniconda/lib/python3.4/site-packages/conda_build/main_skeleton.py", line 136, in execute
    pypi.main(args, parser)
  File "/Users/ahhsia/.miniconda/lib/python3.4/site-packages/conda_build/pypi.py", line 332, in main
    print("Using url %s (%s) for %s." % (urls[n]['url'], human_bytes(urls[n]['size']),
  File "/Users/ahhsia/.miniconda/lib/python3.4/site-packages/conda/utils.py", line 50, in human_bytes
    if n < 1024:
TypeError: unorderable types: str() < int()
## conda info:

Current conda install:

```
         platform : osx-64
    conda version : 3.7.0
```

  conda-build version : 1.7.0
       python version : 3.4.1.final.0
     requests version : 2.4.1
     root environment : /Users/ahhsia/.miniconda  (writable)
  default environment : /Users/ahhsia/.miniconda/envs/bigbang
     envs directories : /Users/ahhsia/.miniconda/envs
        package cache : /Users/ahhsia/.miniconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
                        https://conda.binstar.org/t/<TOKEN>/xanderhsia/osx-64/
          config file : /Users/ahhsia/.condarc
    is foreign system : False

**Comment by msarahan** [comment]
Seems to work today.  Closing.
