### ISSUE TITLE
conda-build 3.0.6 fails with numpy x.x in host and at least one entity in build section

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#2208]
Minimal example to reproduce:
```yaml
package:
  name: foobar

requirements:
  host:
    - numpy x.x
  build:
    - {{ compiler('c') }}
```

**Comment by msarahan** [comment]
This recipe makes no sense.  You can't have ``numpy x.x`` without numpy in your run requirements.  ``x.x`` is a way of saying "pin this matching requirement in the run reqs to the value that is present at build time".

I'll look into this error, regardless.  If adding numpy to the run requirements fixes this error, then I'll try to see if I can show a better message.

Next time, please also post the traceback.

**Comment by nehaljwani** [comment]
Adding `numpy x.x` in the run time requirements does not fix the error.
With this...
```yaml
package:
  name: foobar

requirements:
  host:
    - numpy x.x
  build:
    - {{ compiler('c') }}
  run:
    - numpy x.x
```
...the traceback is same as before:
```py
source tree in: /conda/conda-bld/foobar_1500223926740/work
Attempting to finalize metadata for foobar
INFO:conda_build.metadata:Attempting to finalize metadata for foobar
BUILD START: ['foobar--np111h3e996bd_0.tar.bz2']
Packaging foobar
INFO:conda_build.build:Packaging foobar

Leaving build/test directories:
  Work:  ../../conda/conda-bld/work 
  Test:  ../../conda/conda-bld/test_tmp 
Leaving build/test environments:
  Test: source activate  ../../conda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol 
  Build:        source activate  ../../conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p 


Traceback (most recent call last):
  File "/conda/lib/python3.6/site-packages/conda_build/environ.py", line 703, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/conda/lib/python3.6/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/conda/lib/python3.6/site-packages/conda/plan.py", line 634, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/conda/lib/python3.6/site-packages/conda/resolve.py", line 811, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/conda/lib/python3.6/site-packages/conda/resolve.py", line 850, in solve
    reduced_index = self.get_reduced_index(specs)
  File "/conda/lib/python3.6/site-packages/conda/resolve.py", line 376, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/conda/lib/python3.6/site-packages/conda/resolve.py", line 302, in verify_specs
    raise NoPackagesFoundError(bad_deps)
conda.exceptions.NoPackagesFoundError: Package missing in current linux-64 channels: 
  - numpy x.x

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/conda/lib/python3.6/site-packages/conda_build/api.py", line 183, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/conda/lib/python3.6/site-packages/conda_build/build.py", line 1615, in build_tree
    built_packages=built_packages,
  File "/conda/lib/python3.6/site-packages/conda_build/build.py", line 1170, in build
    channel_urls=tuple(m.config.channel_urls))
  File "/conda/lib/python3.6/site-packages/conda_build/environ.py", line 705, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: ['numpy']
```

**Comment by mingwandroid** [comment]
For new recipes forked from conda-forge we want to use conda-build 3 pinning instead of this `x.x` special case hack (of course).

Better let's not pin numpy in this way at all! See pandas from conda-forge (though admittedly we need to test this on macOS and Windows first).
