### ISSUE TITLE
Conda build fails with numpy?

### ISSUE THREAD

**Issue by CJ-Wright** [conda/conda-build#2224]
I got the following error with conda build. Thoughts?
```sh
(pac) christopher@christopher-ubuntu ~/dev/staged-recipes/recipes/silx slix $ conda build . --nump
............................................................................. y 1.12

Leaving build/test directories:
  Work:	 ../../../../mc/envs/pac/conda-bld/work 
  Test:	 ../../../../mc/envs/pac/conda-bld/test_tmp 
Leaving build/test environments:
  Test:	source activate  ../../../../mc/envs/pac/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place 
  Build:	source activate  ../../../../mc/envs/pac/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol 


Traceback (most recent call last):
  File "/home/christopher/dev/conda-build/conda_build/environ.py", line 699, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/christopher/mc/envs/pac/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/plan.py", line 459, in install_actions
    update_deps, pinned)
  File "/home/christopher/mc/envs/pac/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/plan.py", line 634, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/home/christopher/mc/envs/pac/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/resolve.py", line 802, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/home/christopher/mc/envs/pac/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/resolve.py", line 841, in solve
    reduced_index = self.get_reduced_index(specs)
  File "/home/christopher/mc/envs/pac/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/resolve.py", line 376, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/home/christopher/mc/envs/pac/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/resolve.py", line 302, in verify_specs
    raise NoPackagesFoundError(bad_deps)
conda.exceptions.NoPackagesFoundError: Package missing in current linux-64 channels: 
  - numpy x.x.*

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/christopher/mc/envs/pac/bin/conda-build", line 11, in <module>
    load_entry_point('conda-build', 'console_scripts', 'conda-build')()
  File "/home/christopher/dev/conda-build/conda_build/cli/main_build.py", line 340, in main
    execute(sys.argv[1:])
  File "/home/christopher/dev/conda-build/conda_build/cli/main_build.py", line 331, in execute
    noverify=args.no_verify)
  File "/home/christopher/dev/conda-build/conda_build/api.py", line 183, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/christopher/dev/conda-build/conda_build/build.py", line 1615, in build_tree
    built_packages=built_packages,
  File "/home/christopher/dev/conda-build/conda_build/build.py", line 928, in build
    channel_urls=tuple(m.config.channel_urls))
  File "/home/christopher/dev/conda-build/conda_build/environ.py", line 701, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: ['numpy']
```

conda env
```
asn1crypto                0.22.0                   py35_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                    py35_1    conda-forge
beautifulsoup4            4.5.3                    py35_0    conda-forge
blas                      1.1                    openblas    conda-forge
ca-certificates           2017.1.23                     0    conda-forge
certifi                   2017.4.17                py35_0    conda-forge
cffi                      1.10.0                   py35_0    conda-forge
conda                     4.3.16                    <pip>
conda-verify              2.0.0                    py35_0    conda-forge
coverage                  4.3.4                    py35_0    conda-forge
cryptography              1.8.1                    py35_0  
cython                    0.25.2                   py35_1    conda-forge
decorator                 4.0.11                   py35_0    conda-forge
feedstockrot              1.0.0                    py35_1    conda-forge
fire                      0.1.1                    py35_1    conda-forge
flake8                    3.3.0                    py35_0    conda-forge
flake8-import-order       0.12                     py35_0    conda-forge
gitdb                     0.6.4                    py35_1    conda-forge
gitpython                 2.1.1                    py35_0    conda-forge
hkdf                      0.0.3                    py35_0    conda-forge
idna                      2.5                      py35_0    conda-forge
ipython                   5.4.1                    py35_0    conda-forge
ipython_genutils          0.2.0                    py35_0    conda-forge
jedi                      0.10.0                   py35_0    conda-forge
jinja2                    2.9.5                    py35_0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgfortran               3.0.0                         1  
markupsafe                1.0                      py35_0    conda-forge
mccabe                    0.6.1                    py35_0    conda-forge
ncurses                   5.9                          10    conda-forge
numpy                     1.12.1          py35_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.19                        2    conda-forge
openssl                   1.0.2k                        0    conda-forge
packaging                 16.8                     py35_0    conda-forge
pep8-naming               0.4.1                    py35_0    conda-forge
pexpect                   4.2.1                    py35_0    conda-forge
pickleshare               0.7.3                    py35_0    conda-forge
pip                       9.0.1                    py35_0    conda-forge
pkginfo                   1.4.1                     <pip>
prompt_toolkit            1.0.14                   py35_0    conda-forge
ptyprocess                0.5.1                    py35_0    conda-forge
pycodestyle               2.3.1                    py35_0    conda-forge
pycosat                   0.6.1                     <pip>
pycparser                 2.17                     py35_0    conda-forge
pyflakes                  1.5.0                    py35_0    conda-forge
pygithub                  1.34                     py35_0    conda-forge
pygments                  2.2.0                    py35_0    conda-forge
pyjwt                     1.5.0                    py35_0    conda-forge
pyparsing                 2.2.0                    py35_0    conda-forge
python                    3.5.3                         1    conda-forge
pyyaml                    3.12                     py35_1    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.13.0                   py35_0    conda-forge
ruamel.yaml               0.15.18                  py35_0    conda-forge
setuptools                33.1.1                   py35_0    conda-forge
simplegeneric             0.8.1                    py35_0    conda-forge
six                       1.10.0                   py35_1    conda-forge
smmap                     2.0.1                    py35_0    conda-forge
spake2                    0.7                           1    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        1    conda-forge
traitlets                 4.3.2                    py35_0    conda-forge
wcwidth                   0.1.7                    py35_0    conda-forge
wheel                     0.29.0                   py35_0    conda-forge
xonda                     0.1.6                     <pip>
xz                        5.2.2                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
```

conda info
```
Current conda install:

               platform : linux-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : 2.1.17
         python version : 3.5.3.final.0
       requests version : 2.18.1
       root environment : /home/christopher/mc  (writable)
    default environment : /home/christopher/mc/envs/pac
       envs directories : /home/christopher/mc/envs
                          /home/christopher/.conda/envs
          package cache : /home/christopher/mc/pkgs
                          /home/christopher/.conda/pkgs
           channel URLs : http://conda.anaconda.org/diffpy/linux-64
                          http://conda.anaconda.org/diffpy/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/lightsource2-tag/linux-64
                          https://conda.anaconda.org/lightsource2-tag/noarch
                          https://conda.anaconda.org/soft-matter/linux-64
                          https://conda.anaconda.org/soft-matter/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/diffpy/linux-64
                          https://conda.anaconda.org/diffpy/noarch
            config file : /home/christopher/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.18.1 CPython/3.5.3 Linux/4.4.0-83-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000
```
[meta.yaml](https://github.com/conda-forge/staged-recipes/pull/3339/files#diff-d870422a88e3b328ee684bf494bb07fe)

**Comment by msarahan** [comment]
That's a bug.  You can try to work around it by only saying x.x only on your runtime dependency.

https://github.com/conda/conda-build/pull/650

If conda-build 3 is an option for you, the bug should be fixed there already.

**Comment by msarahan** [comment]
Sorry, I'm guessing you have a corrupt conda-build installation.  I tested with mac and linux on conda-build 2.1.17, and both worked fine.  The error you report is very much like bugs I've seen with the 3.0 branch.  Maybe you have a development install that is interfering?

```
[root@b73b72fc1154 code]# conda build slix/ --numpy 1.12 -c conda-forge
BUILD START: silx-0.5.0-np112py36_0
    (actual version deferred until further download or env creation)
updating index in: /opt/miniconda/conda-bld/linux-64
updating index in: /opt/miniconda/conda-bld/noarch

The following NEW packages will be INSTALLED:

    appdirs:         1.4.3-py36_0                  conda-forge
    blas:            1.1-openblas                  conda-forge
    ca-certificates: 2017.4.17-0                   conda-forge
    certifi:         2017.4.17-py36_0              conda-forge
    cffi:            1.10.0-py36_0                 conda-forge
    decorator:       4.1.1-py36_0                  conda-forge
    libffi:          3.2.1-3                       conda-forge
    libgfortran:     3.0.0-1                       https://repo.continuum.io/pkgs/free
    mako:            1.0.7-py36_0                  conda-forge
    markupsafe:      1.0-py36_0                    conda-forge
    ncurses:         5.9-10                        conda-forge
    numpy:           1.12.1-py36_blas_openblas_200 conda-forge                         [blas_openblas]
    ocl-icd:         2.2.9-4                       conda-forge
    openblas:        0.2.19-2                      conda-forge
    openssl:         1.0.2l-0                      conda-forge
    pycparser:       2.18-py36_0                   conda-forge
    pyopencl:        2017.2-py36_0                 conda-forge
    python:          3.6.1-3                       conda-forge
    pytools:         2017.4-py36_0                 conda-forge
    readline:        6.2-0                         conda-forge
    setuptools:      33.1.1-py36_0                 conda-forge
    six:             1.10.0-py36_1                 conda-forge
    sqlite:          3.13.0-1                      conda-forge
    tk:              8.5.19-1                      conda-forge
    toolchain:       2.0.0-0                       conda-forge
    xz:              5.2.2-0                       conda-forge
    zlib:            1.2.11-0                      conda-forge


WARNING: conda-build appears to be out of date. You have version 2.1.17 but the
latest version is 3.0.8. Run

conda update -n root conda-build

to get the latest version.
```

**Comment by msarahan** [comment]
closing due to inactivity.  If this continues to be a problem for you, please comment, reopen, or file a new issue.
