### ISSUE TITLE
Problem: Conda build --croot --test failes to to missing builded package

### ISSUE THREAD

**Issue by argltuc** [conda/conda-build#2245]
On our Docker CI workflow we work with two seperate stages for build and test a package. The builded conda packages are transfered by gitlab runner artifacts.

The build command is `conda build path/to/recipe --croot $(pwd)/builds --no-test` while test stage is run by `conda build path/to/recipe --croot $(pwd)/builds --test`.
While the build stage runs successfully and provide the compiled packages as artifacts, the test stage will failed with following errors:
```
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/site-packages/conda_build/environ.py", line 680, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/opt/miniconda3/lib/python3.5/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/opt/miniconda3/lib/python3.5/site-packages/conda/plan.py", line 634, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/opt/miniconda3/lib/python3.5/site-packages/conda/resolve.py", line 809, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/opt/miniconda3/lib/python3.5/site-packages/conda/resolve.py", line 849, in solve
    reduced_index = self.get_reduced_index(specs)
  File "/opt/miniconda3/lib/python3.5/site-packages/conda/resolve.py", line 374, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/opt/miniconda3/lib/python3.5/site-packages/conda/resolve.py", line 300, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound:
  - sw-package 1.0 sw_package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/opt/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 329, in execute
    outputs = [action(recipe, config) for recipe in args.recipe]
  File "/opt/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 329, in <listcomp>
    outputs = [action(recipe, config) for recipe in args.recipe]
  File "/opt/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 277, in test_action
    return api.test(recipe, move_broken=False, config=config)
  File "/opt/miniconda3/lib/python3.5/site-packages/conda_build/api.py", line 205, in test
    move_broken=move_broken)
  File "/opt/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 1422, in test
    channel_urls=tuple(metadata.config.channel_urls))
  File "/opt/miniconda3/lib/python3.5/site-packages/conda_build/environ.py", line 682, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: ['sw-package']
```

This behaviour also occours localy, even if you run `conda build --croot --no-test` and `conda build --croot --test` seperately without cleanup the `croot` folder.

We work with Conda 4.3.23, Conda Build 3.0.8 under ubuntu linux 64 and windows 64

**Comment by argltuc** [comment]
After checking the build logs we just recognoize some strange behaviour of the new build hashes.
The build string of our package `sw-package` is defined as `sw_package` but its finally built as `BUILD START: ['sw-package-1.0-swhab75df8_package.tar.bz2']`. So our build string is split by the build hash.
Could be this behaviour the problem for the missing package exception?
It seems so, because the test stage is locking for `sw-package 1.0 sw_package` but `sw-package 1.0 swhab75df8_package` is provided.

**Comment by msarahan** [comment]
Thanks for reporting.  This seems to point to a bug in the regex here: https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L1077-L1096

I'll take a look when I can, but feel free to submit a PR if you have time and need a quick fix.
