### ISSUE TITLE
conda-build -t is broken in 3.0.9

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#2260]
@msarahan I think in 3.0.9 the flag `-t` broke again :/

recipe for th test... It also happens if I specify a test section...
```
package:
  name: "testpkg"
  version: "1.0.0"
```

build only with `--no-test`
```
gabm@pc-klosi /t/testpkg  $ conda build . --no-test
Attempting to finalize metadata for testpkg
INFO:conda_build.metadata:Attempting to finalize metadata for testpkg
BUILD START: ['testpkg-1.0.0-h36134e3_0.tar.bz2']
source tree in: /home/gabm/miniconda3/conda-bld/testpkg_1501944800516/work
Packaging testpkg
INFO:conda_build.build:Packaging testpkg
Packaging testpkg-1.0.0-h36134e3_0
INFO:conda_build.build:Packaging testpkg-1.0.0-h36134e3_0
number of files: 0
Fixing permissions
Fixing permissions
updating: testpkg-1.0.0-h36134e3_0.tar.bz2
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /home/gabm/miniconda3/conda-bld/linux-64/testpkg-1.0.0-h36134e3_0.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []



####################################################################################
Source and build intermediates have been left in /home/gabm/miniconda3/conda-bld.
There are currently 57 accumulated.
To remove them, you can run the ```conda build purge``` command
```

The test stage fails:
```
 gabm@pc-klosi /t/testpkg  $ conda build . -t

Leaving build/test directories:
  Work:  ../../home/gabm/miniconda3/conda-bld/work 
  Test:  ../../home/gabm/miniconda3/conda-bld/test_tmp 
Leaving build/test environments:
  Test: source activate  ../../home/gabm/miniconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla 
  Build:        source activate  ../../home/gabm/miniconda3/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh 


Traceback (most recent call last):
  File "/home/gabm/miniconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/gabm/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 387, in main
    execute(sys.argv[1:])
  File "/home/gabm/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 357, in execute
    action(recipe, config)
  File "/home/gabm/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 297, in test_action
    return api.test(recipe, move_broken=False, config=config)
  File "/home/gabm/miniconda3/lib/python3.5/site-packages/conda_build/api.py", line 204, in test
    test_result = test(recipedir_or_package_or_metadata, config=config, move_broken=move_broken)
  File "/home/gabm/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 1400, in test
    config)
  File "/home/gabm/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 1315, in construct_metadata_for_test
    with open(os.path.join(info_dir, 'index.json')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/testpkg/info/index.json'
```

**Comment by msarahan** [comment]
Sorry.  Testing really works better with passing the package to test,
rather than passing the recipe to test.

```
conda build -t
/Users/msarahan/miniconda3/conda-bld/osx-64/testpkg-1.0.0-h36134e3_0.tar.bz2
Nothing to test for:
/Users/msarahan/miniconda3/conda-bld/osx-64/testpkg-1.0.0-h36134e3_0.tar.bz2
--dirty flag and --keep-old-work not specified.Removing build/test folder
after successful build/test.

INFO conda_build.config:__exit__(609): --dirty flag and --keep-old-work not
specified.Removing build/test folder after successful build/test.

All tests passed
```

This said, it is a bug that testing using the recipe doesn't work, and I'll
fix it for the next bug-fix release.  Thanks for the report.

**Comment by mingwandroid** [comment]
I likely had a hand in breaking this, sorry.

**Comment by msarahan** [comment]
Adding the test files to packages so that any package, even those without
recipes embedded, can be tested in airgapped environments is a big
improvement. Minor egg to break here to make that omelette.  Besides, I
think we should deprecate the behavior here. Testing based on a recipe is
terribly indirect and not intuitive.  We should instead allow URL arguments
to the packages list, or provide some behavior to look for packages on
provided anaconda.org channels, since people may not have package files
locally.

**Comment by gabm** [comment]
@msarahan thank you for quickly fixing this - we are gradually upgrading to the suggested behavior of "testing artifacts" instead of "testing recipes - with an artifact somewhere"..

Anyway, it'll take time to fix our scripts, as we are using this procedure in our test stages for many months now. Could you ship the next conda-build version, so that existing test-stages (and pipelines) are working again? 

Thank you!

**Comment by msarahan** [comment]
Yes, I'll try to tag a version later today.  Tomorrow at the latest.
