### ISSUE TITLE
Unsatisfiable dependencies for platform linux-64

### ISSUE THREAD

**Issue by pdp10** [conda/conda-build#2286]
Hello, 

After upgrading the last conda-build, I can no longer build my package, but it worked fine 
Could you let me know what I need to add / remove in my conda recipe, please? 

https://github.com/pdp10/sbpipe/blob/master/conda_recipe/meta.yaml
```
{% set data = load_setup_py_data() %}

package:
  name: sbpipe
  version: {{ data.get('version') }}

about:
  summary: Pipelines for systems modelling of biological networks
  home: https://github.com/pdp10/sbpipe
  readme: README.md
  license: LGPL-3.0
  license_file: LICENSE

build:
  number: 1
  script: python setup.py install
  noarch_python: True
  entry_points:
    - sbpipe = sbpipe.__main__:main

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
  run:
    - colorlog
    - nose
    - pandas
    - pyaml
    - python
    - numpy
    - scipy
    - setuptools
    - r-essentials
    - r-hmisc
    
test:
  requires:
    - nose
  run:
    - tests/test_suite.py
```

And here the error message: 
```
dallepep@bi1766:~/local_software/sbpipe$ conda build conda_recipe/meta.yaml
Copying /home/dallepep/local_software/sbpipe to /home/dallepep/miniconda3/conda-bld/sbpipe_1502893212199/work
Attempting to finalize metadata for sbpipe
INFO:conda_build.metadata:Attempting to finalize metadata for sbpipe
BUILD START: ['sbpipe-3.24.0-pyh1667e3d_1.tar.bz2']

Leaving build/test directories:
  Work:  ../../miniconda3/conda-bld/work 
  Test:  ../../miniconda3/conda-bld/test_tmp 
Leaving build/test environments:
  Test: source activate  ../../miniconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold 
  Build:        source activate  ../../miniconda3/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl 


Traceback (most recent call last):
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 686, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 634, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 809, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 849, in solve
    reduced_index = self.get_reduced_index(specs)
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 374, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 300, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - colorlog
  - pyaml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dallepep/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 387, in main
    execute(sys.argv[1:])
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 378, in execute
    noverify=args.no_verify)
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 184, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1733, in build_tree
    notest=notest,
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 997, in build
    raise e
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 988, in build
    channel_urls=tuple(m.config.channel_urls))
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 688, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'pyaml', 'colorlog'}
```

pyaml and colorlog are available for linux-64 as shown below: 

- https://anaconda.org/conda-forge/pyaml
- https://anaconda.org/conda-forge/colorlog

conda info:
```
Current conda install:

               platform : linux-64
          conda version : 4.3.24
       conda is private : False
      conda-env version : 4.3.24
    conda-build version : 3.0.10
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /home/dallepep/miniconda3  (writable)
    default environment : /home/dallepep/miniconda3/envs/local
       envs directories : /home/dallepep/miniconda3/envs
                          /home/dallepep/.conda/envs
          package cache : /home/dallepep/miniconda3/pkgs
                          /home/dallepep/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/dallepep/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.24 requests/2.14.2 CPython/3.6.1 Linux/4.4.0-78-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000
```

conda list: 
```
# packages in environment at /home/dallepep/miniconda3/envs/local:
#
blas                      1.1                    openblas    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.4.17                     0    conda-forge
cairo                     1.14.8                        0  
certifi                   2017.4.17                py36_0    conda-forge
colorlog                  3.0.1                    py36_0    conda-forge
curl                      7.52.1                        0    conda-forge
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
glib                      2.50.2                        1  
gsl                       2.2.1           blas_openblas_2  [blas_openblas]  conda-forge
harfbuzz                  0.9.39                        2  
icu                       54.1                          0  
jpeg                      9b                            0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          4    conda-forge
libpng                    1.6.28                        0    conda-forge
libtiff                   4.0.6                         7    conda-forge
libxml2                   2.9.4                         0  
ncurses                   5.9                          10    conda-forge
nose                      1.3.7                    py36_2    conda-forge
numpy                     1.12.1          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.19                        2    conda-forge
openssl                   1.0.2k                        0    conda-forge
pandas                    0.20.1              np112py36_0    conda-forge
pango                     1.40.3                        1  
pcre                      8.39                          0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pixman                    0.34.0                        0    conda-forge
pyaml                     16.12.2                  py36_0    conda-forge
python                    3.6.1                         3    conda-forge
python-dateutil           2.6.0                    py36_0    conda-forge
pytz                      2017.2                   py36_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
r-acepack                 1.4.1                  r3.3.2_0    r
r-assertthat              0.1                    r3.3.2_4    r
r-base                    3.3.2                         1    r
r-cluster                 2.0.5                  r3.3.2_0    r
r-colorspace              1.3_1                  r3.3.2_0    r
r-curl                    2.3                    r3.3.2_0    r
r-data.table              1.10.0                 r3.3.2_0    r
r-devtools                1.12.0                 r3.3.2_0    r
r-dichromat               2.0_0                  r3.3.2_2    r
r-digest                  0.6.10                 r3.3.2_0    r
r-evaluate                0.10                   r3.3.2_0    r
r-foreign                 0.8_67                 r3.3.2_0    r
r-formula                 1.2_1                  r3.3.2_0    r
r-ggplot2                 2.2.0                  r3.3.2_0    r
r-git2r                   0.16.0                 r3.3.2_0    r
r-gridextra               2.2.1                  r3.3.2_0    r
r-gtable                  0.2.0                  r3.3.2_0    r
r-highr                   0.6                    r3.3.2_0    r
r-hmisc                   4.0_0                  r3.3.2_0    r
r-htmltable               1.7                    r3.3.2_0    r
r-htmltools               0.3.5                  r3.3.2_0    r
r-httr                    1.2.1                  r3.3.2_0    r
r-jsonlite                1.1                    r3.3.2_0    r
r-knitr                   1.15.1                 r3.3.2_0    r
r-labeling                0.3                    r3.3.2_2    r
r-lattice                 0.20_34                r3.3.2_0    r
r-latticeextra            0.6_28                 r3.3.2_0    r
r-lazyeval                0.2.0                  r3.3.2_0    r
r-magrittr                1.5                    r3.3.2_2    r
r-markdown                0.7.7                  r3.3.2_2    r
r-mass                    7.3_45                 r3.3.2_0    r
r-matrix                  1.2_7.1                r3.3.2_0    r
r-memoise                 1.0.0                  r3.3.2_0    r
r-mime                    0.5                    r3.3.2_0    r
r-munsell                 0.4.3                  r3.3.2_0    r
r-nnet                    7.3_12                 r3.3.2_0    r
r-openssl                 0.9.5                  r3.3.2_0    r
r-plyr                    1.8.4                  r3.3.2_0    r
r-r6                      2.2.0                  r3.3.2_0    r
r-rcolorbrewer            1.1_2                  r3.3.2_3    r
r-rcpp                    0.12.8                 r3.3.2_0    r
r-reshape2                1.4.2                  r3.3.2_0    r
r-rpart                   4.1_10                 r3.3.2_0    r
r-rstudioapi              0.6                    r3.3.2_0    r
r-scales                  0.4.1                  r3.3.2_0    r
r-stringi                 1.1.2                  r3.3.2_0    r
r-stringr                 1.1.0                  r3.3.2_0    r
r-survival                2.40_1                 r3.3.2_0    r
r-tibble                  1.2                    r3.3.2_0    r
r-viridis                 0.3.4                  r3.3.2_0    r
r-whisker                 0.3_2                  r3.3.2_2    r
r-withr                   1.0.2                  r3.3.2_0    r
r-yaml                    2.1.14                 r3.3.2_0    r
readline                  6.2                           0    conda-forge
scipy                     0.19.0          np112py36_blas_openblas_200  [blas_openblas]  conda-forge
setuptools                33.1.1                   py36_0    conda-forge
six                       1.10.0                   py36_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        1    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
xz                        5.2.2                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
```

Thanks, 
Piero

**Comment by msarahan** [comment]
Seems like a bug with noarch.  You might get further by changing

noarch_python: True

to

noarch: python

More info at
https://conda.io/docs/building/meta-yaml.html#architecture-independent-packages

On Wed, Aug 16, 2017 at 8:24 AM, Piero Dalle Pezze <notifications@github.com

**Comment by pdp10** [comment]
thank you for your swift reply. :) 
Unfortunately, I still receive the same error message:

```
dallepep@bi1766:~/local_software/sbpipe$ conda build conda_recipe/meta.yaml
Copying /home/dallepep/local_software/sbpipe to /home/dallepep/miniconda3/conda-bld/sbpipe_1502894231646/work
Attempting to finalize metadata for sbpipe
INFO:conda_build.metadata:Attempting to finalize metadata for sbpipe
BUILD START: ['sbpipe-3.24.0-pyhe5da2bc_1.tar.bz2']

Leaving build/test directories:
  Work:  ../../miniconda3/conda-bld/work 
  Test:  ../../miniconda3/conda-bld/test_tmp 
Leaving build/test environments:
  Test: source activate  ../../miniconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold 
  Build:        source activate  ../../miniconda3/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl 


Traceback (most recent call last):
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 686, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 634, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 809, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 849, in solve
    reduced_index = self.get_reduced_index(specs)
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 374, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 300, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - colorlog
  - pyaml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dallepep/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 387, in main
    execute(sys.argv[1:])
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 378, in execute
    noverify=args.no_verify)
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 184, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1733, in build_tree
    notest=notest,
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 997, in build
    raise e
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 988, in build
    channel_urls=tuple(m.config.channel_urls))
  File "/home/dallepep/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 688, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'colorlog', 'pyaml'}
```

**Comment by msarahan** [comment]
Sorry, it does seem to be a bug with how noarch is handled.  Specifically,
it is only looking for packages belonging to the noarch subdir.  What
version of conda-build is this?  3.0.10 is current.

If you are using the current version, it's a bug, and I'll try to look into
it soon.  Unfortunately I'm slammed right now and it could be a week or so.

On Wed, Aug 16, 2017 at 8:36 AM, Piero Dalle Pezze <notifications@github.com

**Comment by pdp10** [comment]
Thanks Mike for your help. Yes, it is the 3.0.10 (I added the output of for `conda info` and `conda list` in my first post). 

Interestingly, it seems I can create the package if I explicitly add the conda-forge channel: 
```
conda build conda_recipe/meta.yaml -c conda-forge
```

Is there a way to add the channel inside the meta.yaml file?

**Comment by msarahan** [comment]
No, you can't add channels in the meta.yaml file.  You can, however add
them to condarc, and conda-build will respect that:

conda config --add channels conda-forge

Conda 4.4 adds some very nice ways of specifying channel on a per-package
basis, and conda-build will add support for those specs in meta.yaml
sometime soon.  Conda 4.4 is available on the conda-canary channel as an
early release right now.

On Wed, Aug 16, 2017 at 8:53 AM, Piero Dalle Pezze <notifications@github.com

**Comment by pdp10** [comment]
Thank you for letting me know this. 

Anyway, the command above works fine at least with package. 
Just tested on Travis, and all fine :) 

See: https://travis-ci.org/pdp10/sbpipe/builds/265169945
