### ISSUE TITLE
conda build boost: unexpected error

### ISSUE THREAD

**Issue by hansdewinter** [conda/conda-build#232]
Dear,

when trying to build the boost package on my OS X 10.10 system, I got an unexpected error. The output of the command is given below:

Downloading source to cache: boost_1_55_0.tar.bz2
boost_1_55_0.t 100% |################################################################################################################| Time: 0:01:57 493.10 kB/s
Extracting download
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda-build/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/hans/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/hans/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 110, in main
    args_func(args, p)
  File "/Users/hans/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 312, in args_func
    args.func(args, p)
  File "/Users/hans/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 272, in execute
    build.build(m, verbose=not args.quiet, post=post)
  File "/Users/hans/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 283, in build
    source.provide(m.path, m.get_section('source'))
  File "/Users/hans/anaconda/lib/python2.7/site-packages/conda_build/source.py", line 225, in provide
    unpack(meta)
  File "/Users/hans/anaconda/lib/python2.7/site-packages/conda_build/source.py", line 65, in unpack
    tar_xf(src_path, WORK_DIR)
  File "/Users/hans/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 66, in tar_xf
    t.extractall(path=dir_path)
  File "/Users/hans/anaconda/lib/python2.7/tarfile.py", line 2051, in extractall
    self.extract(tarinfo, path)
  File "/Users/hans/anaconda/lib/python2.7/tarfile.py", line 2088, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/Users/hans/anaconda/lib/python2.7/tarfile.py", line 2164, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/Users/hans/anaconda/lib/python2.7/tarfile.py", line 2205, in makefile
    copyfileobj(source, target)
  File "/Users/hans/anaconda/lib/python2.7/tarfile.py", line 265, in copyfileobj
    shutil.copyfileobj(src, dst)
  File "/Users/hans/anaconda/lib/python2.7/shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
  File "/Users/hans/anaconda/lib/python2.7/tarfile.py", line 818, in read
    buf += self.fileobj.read(size - len(buf))
  File "/Users/hans/anaconda/lib/python2.7/tarfile.py", line 736, in read
    return self.readnormal(size)
  File "/Users/hans/anaconda/lib/python2.7/tarfile.py", line 745, in readnormal
    return self.fileobj.read(size)
EOFError: compressed file ended before the logical end-of-stream was detected

Output from 'condo info' is given below:

conda-rdkit> conda info
Current conda install:

```
         platform : osx-64
    conda version : 3.7.1
```

  conda-build version : 1.9.0
       python version : 2.7.8.final.0
     requests version : 2.4.3
     root environment : /Users/hans/anaconda  (writable)
  default environment : /Users/hans/anaconda
     envs directories : /Users/hans/anaconda/envs
        package cache : /Users/hans/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
          config file : None
    is foreign system : False

Any clues?

Kind regards,
Hans

**Comment by Xunius** [comment]
Hi,
I got a similar error when using conda-build. I've tried to remove everything under ~/anaconda/conda-bld/ and re-run conda-build, but still get the same error. Please help.

**Comment by mandeep** [comment]
@Xunius can you paste the command you entered and the full traceback as well as the output from conda info?

**Comment by Xunius** [comment]
@mandeep: the error happend when I tried to build something I made and probably because I forced terminating it by Ctrl-C, because it hanged without printing any output.
This is the command and full traceback:

```
$conda-build menotexport
Attempting to finalize metadata for menotexport
INFO:conda_build.metadata:Attempting to finalize metadata for menotexport
Traceback (most recent call last):
  File "/home/guangzhi/anaconda2/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/guangzhi/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/home/guangzhi/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 379, in execute
    noverify=args.no_verify)
  File "/home/guangzhi/anaconda2/lib/python2.7/site-packages/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/guangzhi/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 1763, in build_tree
    notest=notest,
  File "/home/guangzhi/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 883, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/home/guangzhi/anaconda2/lib/python2.7/site-packages/conda_build/render.py", line 543, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/home/guangzhi/anaconda2/lib/python2.7/site-packages/conda_build/metadata.py", line 1755, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/guangzhi/anaconda2/lib/python2.7/site-packages/conda_build/metadata.py", line 638, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/guangzhi/anaconda2/lib/python2.7/site-packages/conda_build/render.py", line 292, in finalize_metadata
    extra_run_specs_from_build = get_upstream_pins(m, build_actions, 'build')
  File "/home/guangzhi/anaconda2/lib/python2.7/site-packages/conda_build/render.py", line 248, in get_upstream_pins
    legacy_specs = utils.package_has_file(pkg_file, 'info/run_exports')
  File "/home/guangzhi/anaconda2/lib/python2.7/site-packages/conda/utils.py", line 45, in __call__
    value = self.func(*args, **kw)
  File "/home/guangzhi/anaconda2/lib/python2.7/site-packages/conda_build/utils.py", line 722, in package_has_file
    text = t.extractfile(file_path).read()
  File "/home/guangzhi/anaconda2/lib/python2.7/tarfile.py", line 2145, in extractfile
    tarinfo = self.getmember(member)
  File "/home/guangzhi/anaconda2/lib/python2.7/tarfile.py", line 1827, in getmember
    tarinfo = self._getmember(name)
  File "/home/guangzhi/anaconda2/lib/python2.7/tarfile.py", line 2396, in _getmember
    members = self.getmembers()
  File "/home/guangzhi/anaconda2/lib/python2.7/tarfile.py", line 1838, in getmembers
    self._load()        # all members, we first have to
  File "/home/guangzhi/anaconda2/lib/python2.7/tarfile.py", line 2419, in _load
    tarinfo = self.next()
  File "/home/guangzhi/anaconda2/lib/python2.7/tarfile.py", line 2350, in next
    self.fileobj.seek(self.offset - 1)
EOFError: compressed file ended before the logical end-of-stream was detected
```

This is the output from `conda info`:

```
Current conda install:

               platform : linux-64
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : 3.0.15
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /home/guangzhi/anaconda2  (writable)
    default environment : /home/guangzhi/anaconda2/envs/pdf
       envs directories : /home/guangzhi/anaconda2/envs
                          /home/guangzhi/.conda/envs
          package cache : /home/guangzhi/anaconda2/pkgs
                          /home/guangzhi/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.14.2 CPython/2.7.13 Linux/4.9.39-1-MANJARO / glibc/2.25    
                UID:GID : 1000:1000
```
I tried empyting the `anaconda/conda-bld` folder as well as the `anaconda/pkgs/cache/` folder but didn't help. I managed to the package built by doing this on another machine though.

**Comment by jruizaranguren** [comment]
@mandeep, @Xunius, @asmeurer  I am getting the same error when trying to build https://github.com/conda-forge/opencv-feedstock.

I execute the following command:

```
conda-build recipe -c conda-forge
```

Result:

```
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for opencv
INFO:conda_build.metadata:Attempting to finalize metadata for opencv
Solving environment: ...working... done
Traceback (most recent call last):
  File "/home/javier/anaconda2/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 407, in execute
    outputs = [action(recipe, config) for recipe in args.recipe]
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 334, in check_action
    return api.check(recipe, config=config)
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/api.py", line 141, in check
    config=config, variants=variants)
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/api.py", line 50, in render
    permit_undefined_jinja=not finalize):
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/metadata.py", line 1861, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/metadata.py", line 680, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/render.py", line 379, in finalize_metadata
    exclude_pattern)
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/render.py", line 293, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/render.py", line 284, in _read_upstream_pin_files
    extra_run_specs = get_upstream_pins(m, actions, env)
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/render.py", line 271, in get_upstream_pins
    specs = _read_specs_from_package(pkg_loc, pkg_dist)
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda/exports.py", line 175, in __call__
    value = self.func(*args, **kw)
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/render.py", line 204, in _read_specs_from_package
    specs_yaml = utils.package_has_file(pkg_loc, 'info/run_exports.yaml')
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda/exports.py", line 175, in __call__
    value = self.func(*args, **kw)
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/utils.py", line 934, in package_has_file
    text = t.extractfile(file_path).read()
  File "/home/javier/anaconda2/lib/python2.7/tarfile.py", line 2145, in extractfile
    tarinfo = self.getmember(member)
  File "/home/javier/anaconda2/lib/python2.7/tarfile.py", line 1827, in getmember
    tarinfo = self._getmember(name)
  File "/home/javier/anaconda2/lib/python2.7/tarfile.py", line 2396, in _getmember
    members = self.getmembers()
  File "/home/javier/anaconda2/lib/python2.7/tarfile.py", line 1838, in getmembers
    self._load()        # all members, we first have to
  File "/home/javier/anaconda2/lib/python2.7/tarfile.py", line 2419, in _load
    tarinfo = self.next()
  File "/home/javier/anaconda2/lib/python2.7/tarfile.py", line 2350, in next
    self.fileobj.seek(self.offset - 1)
EOFError: compressed file ended before the logical end-of-stream was detected

```

And the result of my conda info:

```
active environment : None
            shell level : 0
       user config file : /home/javier/.condarc
 populated config files : 
          conda version : 4.4.11
    conda-build version : 3.7.0
         python version : 2.7.14.final.0
       base environment : /home/javier/anaconda2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/javier/anaconda2/pkgs
                          /home/javier/.conda/pkgs
       envs directories : /home/javier/anaconda2/envs
                          /home/javier/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/2.7.14 Linux/4.4.0-116-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

``` 

I have tried to delete contents from `/home/javier/anaconda2/pkgs` executed `conda-build purge-all` and manually deleted the conda-bld directory.

**Comment by Xunius** [comment]
@jruizaranguren I sort of remember how I solved it. I added a pdb break point in the file `anaconda2/lib/python2.7/tarfile.py` to let it stop at the line where it failed, and print out the file it is processing, and in my case it was `~/anaconda/pkgs/numpy-1.11.3-py27_0.tar.bz2`. So I searched this file and deleted it, then it works.

I can't be sure this will solve your problem but maybe give it a try.

**Comment by msarahan** [comment]
``conda clean -ay``

will clear out your package cache.  It's heavy handed, but it should work.

**Comment by jruizaranguren** [comment]
```
conda clean -ay
```
Made the trick.  Thanks @msarahan and @Xunius .

Unfortunately I get a new error, but I guess I will have to start a new issue:

```
Traceback (most recent call last):
  File "/home/javier/anaconda2/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/api.py", line 199, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 2074, in build_tree
    notest=notest,
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 1347, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/utils.py", line 294, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/javier/anaconda2/lib/python2.7/site-packages/conda_build/utils.py", line 273, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/javier/anaconda2/conda-bld/opencv_1520423380626/work/conda_build.sh']' returned non-zero exit status 1

```

**Comment by msarahan** [comment]
That looks like an error happened while running your build script.  Errors in build scripts are recipe errors, not problems with conda-build (unless conda-build is not providing the env vars that we say should be there).
