### ISSUE TITLE
conda-build cannot import move_to_trash

### ISSUE THREAD

**Issue by gautier-krings** [conda/conda-build#2374]
I'm not sure what's going wrong here...
I executed the following command in the terminal:
`conda-build .`
in the same folder as my files required to create a conda package. 
Here's the traceback I got:
```
Traceback (most recent call last):
  File "/Users/gautier/tools/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/gautier/tools/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 190, in main
    args_func(args, p)
  File "/Users/gautier/tools/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/Users/gautier/tools/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 262, in execute
    import conda_build.build as build
  File "/Users/gautier/tools/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 22, in <module>
    from conda.install import prefix_placeholder, linked, move_to_trash
ImportError: cannot import name move_to_trash
```
Here's my current conda install
```
Current conda install:

               platform : osx-64
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : 1.18.2
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /Users/gautier/tools/anaconda  (writable)
    default environment : /Users/gautier/tools/anaconda
       envs directories : /Users/gautier/tools/anaconda/envs
                          /Users/gautier/.conda/envs
          package cache : /Users/gautier/tools/anaconda/pkgs
                          /Users/gautier/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.12.4 CPython/2.7.12 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
```

**Comment by msarahan** [comment]
You have updated conda, but not conda-build.  Your conda-build version is ancient.  Please update conda-build and try again.  3.0.17 is the latest.  2.1.17 is the earliest still-supported release.
