### ISSUE TITLE
`conda skeleton` leads to `ImportError: cannot import name 'NoPackagesFound'`

### ISSUE THREAD

**Issue by andreas-h** [conda/conda-build#2396]
I'm running into this error:

    $ conda skeleton pypi --output-dir conda emiprep
    Traceback (most recent call last):
      File "/home2/hilboll/.local/easybuild/software/Anaconda3/4.2.0/bin/conda-skeleton", line 4, in <module>
        import conda_build.cli.main_skeleton
      File "/home2/hilboll/.local/easybuild/software/Anaconda3/4.2.0/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 15, in <module>
        from conda_build.conda_interface import ArgumentParser
      File "/home2/hilboll/.local/easybuild/software/Anaconda3/4.2.0/lib/python3.5/site-packages/conda_build/conda_interface.py", line 21, in <module>
        from conda.resolve import MatchSpec, NoPackagesFound, Resolve, Unsatisfiable, normalized_version  # NOQA
    ImportError: cannot import name 'NoPackagesFound'

I'm using conda 4.3.25:

    $ conda --version
    conda 4.3.25

and this is my environment:

    $ conda info                   
    Current conda install:
    
                   platform : linux-64
              conda version : 4.3.25
           conda is private : False
          conda-env version : 4.3.25
        conda-build version : 2.0.2
             python version : 3.5.2.final.0
           requests version : 2.14.2
           root environment : /home2/hilboll/.local/easybuild/software/Anaconda3/4.2.0  (writable)
        default environment : /home2/hilboll/.local/easybuild/software/Anaconda3/4.2.0
           envs directories : /home2/hilboll/.local/easybuild/software/Anaconda3/4.2.0/envs
                              /home2/hilboll/.conda/envs
              package cache : /home2/hilboll/.local/easybuild/software/Anaconda3/4.2.0/pkgs
                              /home2/hilboll/.conda/pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                              https://repo.continuum.io/pkgs/free/noarch
                              https://repo.continuum.io/pkgs/r/linux-64
                              https://repo.continuum.io/pkgs/r/noarch
                              https://repo.continuum.io/pkgs/pro/linux-64
                              https://repo.continuum.io/pkgs/pro/noarch
                              https://conda.anaconda.org/conda-forge/linux-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://conda.anaconda.org/andreas-h/linux-64
                              https://conda.anaconda.org/andreas-h/noarch
                config file : /home2/hilboll/.condarc
                 netrc file : None
               offline mode : False
                 user-agent : conda/4.3.25 requests/2.14.2 CPython/3.5.2 Linux/4.12.0-13.1-liquorix-amd64 debian/buster/sid glibc/2.24    
                    UID:GID : 1059:1059

**Comment by andreas-h** [comment]
Works flawlessly after updating conda-build to 3.0.19.  Sorry for the noise.
