### ISSUE TITLE
OSError: [Errno 17] File exists

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda/conda-build#243]
Hi all, 

I have got this error when building a package with conda:

Traceback (most recent call last):
  File "/sebastian/anaconda-test/test-cgat-1/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/sebastian/anaconda-test/test-cgat-1/lib/python2.7/site-packages/conda_build/main_build.py", line 110, in main
    args_func(args, p)
  File "/sebastian/anaconda-test/test-cgat-1/lib/python2.7/site-packages/conda_build/main_build.py", line 312, in args_func
    args.func(args, p)
  File "/sebastian/anaconda-test/test-cgat-1/lib/python2.7/site-packages/conda_build/main_build.py", line 272, in execute
    build.build(m, verbose=not args.quiet, post=post)
  File "/sebastian/anaconda-test/test-cgat-1/lib/python2.7/site-packages/conda_build/build.py", line 333, in build
    post_process(preserve_egg_dir=bool(m.get_value('build/preserve_egg_dir')))
  File "/sebastian/anaconda-test/test-cgat-1/lib/python2.7/site-packages/conda_build/post.py", line 136, in post_process
    remove_easy_install_pth(preserve_egg_dir=preserve_egg_dir)
  File "/sebastian/anaconda-test/test-cgat-1/lib/python2.7/site-packages/conda_build/post.py", line 95, in remove_easy_install_pth
    utils.copy_into(join(egg_path, fn), join(sp_dir, fn))
  File "/sebastian/anaconda-test/test-cgat-1/lib/python2.7/site-packages/conda_build/utils.py", line 28, in copy_into
    shutil.copytree(srcname, dstname)
  File "/sebastian/anaconda-test/test-cgat-1/lib/python2.7/shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "/sebastian/anaconda-test/test-cgat-1/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/sebastian/anaconda-test/test-cgat-1/envs/_build/lib/python2.7/site-packages/sphinx/ext'

Anything that I could try?

Many thanks!

PD: Here is conda information:
Current conda install:
             platform : linux-64
        conda version : 3.7.3
  conda-build version : 1.9.0
       python version : 2.7.8.final.0
     requests version : 2.4.3
     root environment : /sebastian/anaconda-test/test-cgat-1  (writable)
  default environment : /sebastian/anaconda-test/test-cgat-1
     envs directories : /sebastian/anaconda-test/test-cgat-1/envs
        package cache : /sebastian/anaconda-test/test-cgat-1/pkgs
         channel URLs : https://conda.binstar.org/cgat/linux-64/
                        http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : /ifs/home/sebastian/.condarc
    is foreign system : False

**Comment by hargup** [comment]
@asmeurer #240 was merged, this issue should be closed now.

**Comment by sebastian-luna-valero** [comment]
Thanks!
