### ISSUE TITLE
--no-include-recipe breaks build when run_test.sh is present

### ISSUE THREAD

**Issue by maddenp** [conda/conda-build#2457]
Doing `conda build .` is fine, but `conda build --no-include-recipe .` fails with
```
Traceback (most recent call last):
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda_build/environ.py", line 680, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda/plan.py", line 631, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda/resolve.py", line 813, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda/resolve.py", line 853, in solve
    reduced_index = self.get_reduced_index(specs)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda/resolve.py", line 374, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda/resolve.py", line 300, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - condatest 0.0.1 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/pmadden/o/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 379, in execute
    verify=args.verify)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1782, in build_tree
    test(pkg, config=metadata.config)
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1556, in test
    channel_urls=tuple(metadata.config.channel_urls))
  File "/media/pmadden/o/miniconda/lib/python3.6/site-packages/conda_build/environ.py", line 682, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: ['condatest 0.0.1 0']
```
Background info:
```
% cat meta.yaml
package:
  name: condatest
  version: '0.0.1'

requirements:
  run:
    - numpy 1.13.3.*

% cat run_test.sh 
true

% conda build --version
conda-build 3.0.27
```

**Comment by bencherian** [comment]
I can reproduce the same problem with package installation during test on Windows by setting `include_recipe` to false in the meta.yaml file for any recipe that otherwise works fine.
