### ISSUE TITLE
build failes due to load_setup_py_data

### ISSUE THREAD

**Issue by tovop** [conda/conda-build#2458]
Hi

I believe I have a similiar problem as reported in #2181 

I store the recipe in the repo I am trying to build and use versioneer to version everything. Seems to me the problem happens when loading version number from setup.py. The setup.py imports numpy which is not available at that time. I have included the meta.yaml and the traceback below.

I use _conda-build 3.0.27._

Am I doing something wrong?

**meta.yaml**

{% set data = load_setup_py_data() %}

package:
  name: "qats"
  version: {{ data.get('version') }}

source:
  git_url: .
  git_tag:

build:
  string: py{{ PY_VER }}
  include_recipe: False
  script: python setup.py install

requirements:
  build:
    - python >=3.5,<4.0
    - setuptools >=36,<37
    - matplotlib >=1,<3
    - numpy >=1,<2
    - scipy >=0,<1
  run:
    - python >=3.5,<4.0
    - setuptools >=36,<37
    - matplotlib >=1,<3
    - numpy >=1,<2
    - scipy >=0,<1
    - h5py >=2.7,<3
    - hdf5 >=1.8,<2
    - qt >=5.6.0,<6
    - pyqt >=5.6.0,<6

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}

extra:
  maintainers:
   - {{ data.get('author') }}

**Traceback**

 Traceback (most recent call last):
   File "/tmp/miniconda/bin/conda-build", line 11, in <module>
     sys.exit(main())
   File "/tmp/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 388, in main
     execute(sys.argv[1:])
   File "/tmp/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 379, in execute
     verify=args.verify)
   File "/tmp/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 185, in build
     need_source_download=need_source_download, config=config, variants=variants)
   File "/tmp/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1757, in build_tree
     bypass_env_check=True)
   File "/tmp/miniconda/lib/python3.6/site-packages/conda_build/render.py", line 628, in render_recipe
     allow_no_other_outputs=True, bypass_env_check=bypass_env_check)
   File "/tmp/miniconda/lib/python3.6/site-packages/conda_build/render.py", line 451, in distribute_variants
     bypass_env_check=True)
   File "/tmp/miniconda/lib/python3.6/site-packages/conda_build/metadata.py", line 774, in parse_again
     bypass_env_check=bypass_env_check),
   File "/tmp/miniconda/lib/python3.6/site-packages/conda_build/metadata.py", line 1345, in _get_contents
     rendered = template.render(environment=env)
   File "/tmp/miniconda/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
     return original_render(self, *args, **kwargs)
   File "/tmp/miniconda/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
     return self.environment.handle_exception(exc_info, True)
   File "/tmp/miniconda/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
     reraise(exc_type, exc_value, tb)
   File "/tmp/miniconda/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
     raise value.with_traceback(tb)
   File "/opt/vsts/work/1/s/meta.yaml", line 2, in top-level template code
     # It uses load_setup_py_data from conda_build.jinja_context to populate some fields
   File "/tmp/miniconda/lib/python3.6/site-packages/conda_build/jinja_context.py", line 106, in load_setup_py_data
     permit_undefined_jinja=permit_undefined_jinja)
   File "/tmp/miniconda/lib/python3.6/site-packages/conda_build/_load_setup_py_data.py", line 85, in load_setup_py_data
     exec(code, ns, ns)
   File "/tmp/cbuild/qats_1508702889465/work/setup.py", line 4, in <module>
     import numpy as np
 ModuleNotFoundError: No module named 'numpy'

**Comment by msarahan** [comment]
I don't think #2181 is related.  I think your issue is a regression in some new-ish behavior, which requires that conda-build make two passes at parsing setup.py data.  The first is done with the root environment, since we often need to parse setup.py before we even think about creating the build environment.  The build environment is generally created much later, after all other variables have been resolved.  There's a second pass that's supposed to happen, that seems to be not happening right now.  That second pass is supposed to happen with the build environment's python, not the root env's python.

Short term workaround: ``conda install numpy`` in your root env, and it should work.  I'll try to find time to debug why this broke, and why tests didn't catch it, soon.

**Comment by msarahan** [comment]
PS: unless you are using numpy's distutils stuff, I strongly advise you to prevent numpy from being imported at build time.  At best, it will take much longer for your package to build (from downloading numpy and mkl), and at worst, people who pip-install your package may pick up numpy from pypi, which may clobber conda's numpy in terrible ways.

**Comment by tovop** [comment]
Thanks a lot @msarahan for the speedy reply and the advices!

The reason for numpy being imported at build time is that setup.py imports my package to get the __name__, __license__, etc. from the package __init__.py. And one of the modules imported into __init__.py import numpy.

Maybe I am approaching this the wrong way. The way I see it, I have to duplicate the package meta-data (keeping it in __ini__.py and in setup.py) to avoid importing numpy at build time. Is this what you would recommend?

**Comment by luc-j-bourhis** [comment]
I am also seeing this in a recipe I am developing. My `meta.yaml` is

```yaml
{% set data = load_setup_py_data() %}

package:
    name: gpyfft
    version: "{{ data.version }}"

source:
  git_url: https://github.com/geggo/gpyfft
  git_rev: 3ed258f2ec2a2e6b4157e00d071bd861a0f42afd

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - clfft
  run:
    - python
    - pyopencl
    - numpy
```

As you can see, `cython` is a build dependency because it is used in the `setup.py`. Any distutils-based package parts of which are built with Cython would be so, obviously. So when conda imports `setup.py` to fill in the templated bits of `meta.yaml`, I get the stack trace below.

```
Traceback (most recent call last):
  File "/Users/luc/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/luc/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/Users/luc/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/Users/luc/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 199, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/luc/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2078, in build_tree
    bypass_env_check=True)
  File "/Users/luc/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 665, in render_recipe
    allow_no_other_outputs=True, bypass_env_check=bypass_env_check)
  File "/Users/luc/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 558, in distribute_variants
    if mv.needs_source_for_render and mv.variant_in_source:
  File "/Users/luc/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 1649, in variant_in_source
    bypass_env_check=True)
  File "/Users/luc/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 840, in parse_again
    bypass_env_check=bypass_env_check),
  File "/Users/luc/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 1401, in _get_contents
    rendered = template.render(environment=env)
  File "/Users/luc/miniconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/luc/miniconda3/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/luc/miniconda3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/luc/miniconda3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/luc/Developer/conda-recipies/gpyfft/meta.yaml", line 1, in top-level template code
    {% set data = load_setup_py_data() %}
  File "/Users/luc/miniconda3/lib/python3.6/site-packages/conda_build/jinja_context.py", line 127, in load_setup_py_data
    permit_undefined_jinja=permit_undefined_jinja)
  File "/Users/luc/miniconda3/lib/python3.6/site-packages/conda_build/_load_setup_py_data.py", line 93, in load_setup_py_data
    exec(code, ns, ns)
  File "/Users/luc/miniconda3/conda-bld/gpyfft_1521724031450/work/setup.py", line 5, in <module>
    from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
```

**Comment by msarahan** [comment]
Thanks for re-raising this issue.  We'll try to fix it soon.

**Comment by dhirschfeld** [comment]
From gitter - https://gitter.im/conda/conda-build?at=5baad5a4fe37781110f9c495

> *AFAICS it makes it impossible to have any automated build worker because if you don't know ahead of time what you will be building and what it's setup.py dependencies are your build just won't work*

I'd perhaps suggest a multi-phase approach where you try loading the setup.py data first and if that doesn't work then, rather than quitting, make a best attempt at creating a build env and then try re-parsing the setup.py data in the initial build env and updating the env with anything which was missed initially:

![image](https://user-images.githubusercontent.com/881019/46115503-95af8580-c23a-11e8-9f80-0e0463e839bf.png)

**Comment by dhirschfeld** [comment]
Would love to but finding time might be difficult since it's not on my critical path

It'd be nice if it Just Worked but given the workaround is to just install everything into root that's the path of least resistance; at least for now...

I am curious though - you don't use `load_setup_py_data` internally?

**Comment by msarahan** [comment]
Almost not at all.  That's a develop-time feature, and we are very much focused on building only tagged, released software, where the model is that you provide the information in meta.yaml that you would ordinarily load from setup.py.  Very few of Anaconda's internal projects release development (nightly/per-commit) builds in the form of conda packages.

**Comment by karl-az** [comment]
I have a related issue; data.get("version") works for me, but when I try to pull in the name (data.get("name")) from setup.py it only works partially. boa tries to create a correctly named package, but fails to create the build environment. Instead of using the package name it uses none as prefix. The environment is never created. Other environments looks to be correctly prefixed.
