### ISSUE TITLE
Recursive recipe build has been broken from 3.0.23+

### ISSUE THREAD

**Issue by lambdalisue** [conda/conda-build#2467]
Recursive recipe build has been broken from 3.0.23+ (3.0.23 is OK, I could not test 3.0.24 while the package is missing, 3.0.25-27 are broken).

I'm using the following structure and script

```
recipes
    +- recipeA -- depends on recipeAA
    +- recipeAA -- depends on recipeAAA
    +- recipeAAA
    +- recipeB
```

```sh
(cd recipe; conda build \
    --no-anaconda-upload \
    --python=3.6 \
    --channel="file://{CHANNEL_DIRECTORY}" \
    --channel=defaults \
    --channel=conda-forge \
    --override-channels \
    --output-folder="${CHANNEL_DIRECTORY}" \
    recipeA recipeB)
```

and `conda-build 3.0.25 to 3.0.27` shows the following exception

```
Attempting to finalize metadata for recipeA
INFO:conda_build.metadata:Attempting to finalize metadata for recipeA
BUILD START: ['recipeA.brabrabra.tar.bz2']

Leaving build/test directories:
  Work:  /opt/miniconda3/conda-bld/work
  Test:  /opt/miniconda3/conda-bld/test_tmp
Leaving build/test environments:
  Test: source activate  /opt/miniconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
hold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
  Build:        source activate  /opt/miniconda3/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl


Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 679, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/opt/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/opt/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 631, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/opt/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 813, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/opt/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 853, in solve
    reduced_index = self.get_reduced_index(specs)
  File "/opt/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 374, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/opt/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 300, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound:
  - recipeAA

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/opt/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 379, in execute
    noverify=args.no_verify)
  File "/opt/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/opt/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1772, in build_tree
    notest=notest,
  File "/opt/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 995, in build
    raise e
  File "/opt/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 986, in build
    channel_urls=tuple(m.config.channel_urls))
  File "/opt/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 681, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: ['recipeAA']
```

**Comment by msarahan** [comment]
Sorry.  A PR would be gladly accepted here, but we don't use this functionality and can't spend much time on it.  We have a separate tool, http://github.com/conda/conda-concourse-ci that we use for building up dependency trees and dispatching jobs.

**Comment by lambdalisue** [comment]
So what is the proper way to build recipes which depends on other recipes? Your linked app seems a bit overkill for simple building.

**Comment by msarahan** [comment]
list them all at the command line.  They need to be in the right order at the CLI: left-most entry built first.  Conda-build is too dumb to do any kind of dependency ordering right now.  It would be nice to fix that, but again, I can't justify the time, since I'm using conda-concourse-ci to drive my build system.
