### ISSUE TITLE
conda build fails with python traceback for UnicodeEncodeError

### ISSUE THREAD

**Issue by sstncr** [conda/conda-build#2480]
I'm trying to build my own package on Ubuntu 16.04. Build step seems to work fine but it fails on packaging with:

```Packaging my-toolchain
INFO:conda_build.build:Packaging my-toolchain
Packaging my-toolchain-1.0.0-mystring0
INFO:conda_build.build:Packaging my-toolchain-1.0.0-mystring0
number of files: 95702
Fixing permissions
Skipping binary relocation logic
Making absolute symlink sdk/sysroots/linux-gnueabi/usr/lib/libgstadaptivedemux-1.0.so.0 -> libgstadaptivedemux-1.0.so.0.1003.0 relative
...
Making absolute symlink sdk/sysroots/linux-gnueabi/usr/lib/libopencv_aruco.so -> libopencv_aruco.so.3.2 relative
Fixing permissions
Traceback (most recent call last):
  File "/data/miniconda2/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/data/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/data/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 379, in execute
    noverify=args.no_verify)
  File "/data/miniconda2/lib/python2.7/site-packages/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/data/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 1771, in build_tree
    notest=notest,
  File "/data/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 1239, in build
    built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env)
  File "/data/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 729, in bundle_conda
    output['checksums'] = create_info_files(metadata, files, prefix=metadata.config.host_prefix)
  File "/data/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 500, in create_info_files
    write_info_files_file(m, files)
  File "/data/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 346, in write_info_files_file
    fo.write(f + '\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 67: ordinal not in range(128)


$ cat meta.yaml 
package:
  name: my-toolchain
  version: "1.0.0"

build:
  string: my-string0
  binary_relocation: False

requirements:
    build:
    run:

source:
  url: glibc-x86_64-toolchain.sh # [linux64]
  sha1: 8901ce56be524fcc605cd36622a4c919c351bab9

$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.19
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /data/miniconda2  (writable)
    default environment : /data/miniconda2
       envs directories : /data/miniconda2/envs
                          /home/ubuntu/.conda/envs
          package cache : /data/miniconda2/pkgs
                          /home/ubuntu/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/2.7.13 Linux/4.4.0-98-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000```

**Comment by sstncr** [comment]
I've added some prints in build.py:

Fixing permissions
FAILED in sysroots/cortexa7hf-neon-poky-linux-gnueabi/etc/ssl/certs/AC_Raíz_Certicámara_S.A..pem
FAILED in sysroots/cortexa7hf-neon-poky-linux-gnueabi/etc/ssl/certs/Certinomis_-_Autorité_Racine.pem
FAILED in sysroots/cortexa7hf-neon-poky-linux-gnueabi/etc/ssl/certs/EBG_Elektronik_Sertifika_Hizmet_Sağlayıcısı.pem


So, yeah, I have files that contain Unicode characters...

**Comment by msarahan** [comment]
As a hack for now, try removing those files at the end of your build.sh script.

Longer term, we'll try to fix this issue, but anything you can do, as far as providing a nice test case to develop against, will speed up that process.

**Comment by sstncr** [comment]
Sure, removing those files was on my list. I'll try and send a patch as well, if I can.
There is another issue with dead symlinks as well. If you have symlink that points to something that doesn't yet exist (for reasons...)  it will fail when trying to record the size of it...
