### ISSUE TITLE
conda skeleton pypi numexpr fail with numpy distutils

### ISSUE THREAD

**Issue by braindevices** [conda/conda-build#2508]
It seems the numpy distutils still has problem?
```
Applying patch: '/tmp/tmp4id8ju_8conda_skeleton_numexpr-2.6.4.tar.gz/pypi-distutils.patch'
Trying to apply patch as-is
INFO:conda_build.source:Trying to apply patch as-is
patching file core.py
Hunk #1 succeeded at 167 with fuzz 2 (offset 1 line).
Traceback (most recent call last):
  File "setup.py", line 227, in <module>
    setup_package()
  File "setup.py", line 223, in setup_package
    setup(**metadata)
  File "xx/anaconda3/conda-bld/skeleton_1510866606373/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.6/site-packages/numpy/distutils/core.py", line 130, in setup
    if dist.help or not _command_line_ok():
AttributeError: 'NoneType' object has no attribute 'help'
```
what should I do?

**Comment by msarahan** [comment]
This is a well-established recipe.  Get it from conda-forge (https://github.com/conda-forge/numexpr-feedstock) or us (https://github.com/anacondarecipes/numexpr-feedstock).  There's no point in skeletonizing things for which much better recipes already exist.
