### ISSUE TITLE
Build tests always run against python 2.7

### ISSUE THREAD

**Issue by DarthShoge** [conda/conda-build#2516]
I am having an issue where my unit tests are failing in the build becuase conda is using the python 2.7 interpreter in the test env. 
 the following error is produced at build time

```
======================================================================
ERROR: test_impliedViews_utilities (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_impliedViews_utilities
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\conda-bld\medh_1511260280384\_test_env\lib\unit
test\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\ProgramData\Anaconda3\conda-bld\medh_1511260280384\_test_env\lib\unit
test\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "C:\ProgramData\Anaconda3\conda-bld\medh_1511260280384\test_tmp\test\test
_impliedViews_utilities.py", line 7, in <module>
    from medh.impliedViews import DiscretionaryImpliedViews as DIV
  File "C:\ProgramData\Anaconda3\conda-bld\medh_1511260280384\_test_env\lib\site
-packages\medh-_version_-py3.6.egg\medh\__init__.py", line 1, in <module>
    from medh.MEDH import MEDH
  File "C:\ProgramData\Anaconda3\conda-bld\medh_1511260280384\_test_env\lib\site
-packages\medh-_version_-py3.6.egg\medh\MEDH.py", line 20
    def calculate_signal(self, market_data: PandasDataframe, positions: PandasDa
taframe, spots : PandasDataframe) -> List[PandasDataframe]:
                                          ^
SyntaxError: invalid syntax
```

I think it is doing this because one of the test dependencies are for python 2.7* but this dependency works with python 3*. My question however is. Is there a way of forcing the test env that conda generates to use a specific version of python?

my recipe is as follows

```
package:
  name: medh
  version: "0.0.0.1"

source:
  path: ../

#  patches:
   # List any patch files here
   # - fix.patch

build:
  script: python setup.py install


requirements:
  build:
    - pandas
    - numpy
    - matplotlib

  run:
    - pandas
    - numpy
    - matplotlib

test:
#  run_test.py
  source_files:
    - test/.
  requires:
    - nose
    - teamcity-messages # This requires 2.7* #
```
This is being run on a Windows 7 Enterprise box on Conda version 4.3.30

**Comment by msarahan** [comment]
You have no explicit python dependency, so conda is free to do whatever it wants to try to satisfy your other dependencies.  It is important to list python explicitly, so that conda-build locks it down correctly.  Try this:

```
build:
  script: python setup.py install
  skip: True  # [py < 34]

requirements:
  build:
    - python
    - pandas
    - numpy
    - matplotlib

  run:
   - python
    - pandas
    - numpy
    - matplotlib
```

**Comment by DarthShoge** [comment]
I tried a similar thing earlier the only issue is that the 2.7 dependant package is blocking the build. So with the meta.yaml as above I now get this output 
 ```
 File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\build.py", line 1
772, in build_tree
    notest=notest,
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\build.py", line 9
86, in build
    channel_urls=tuple(m.config.channel_urls))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\environ.py", line
 715, in get_install_actions
    channel_urls=tuple(channel_urls))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\environ.py", line
 715, in get_install_actions
    channel_urls=tuple(channel_urls))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\environ.py", line
 715, in get_install_actions
    channel_urls=tuple(channel_urls))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\environ.py", line
 679, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\plan.py", line 461, in
install_actions
    update_deps, pinned)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\plan.py", line 631, in
get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\resolve.py", line 813,
in install
    pkgs = self.solve(specs, returnall=returnall)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\resolve.py", line 868,
in solve
    self.find_conflicts(specs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\resolve.py", line 369,
in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to
be in conflict:
  - python 3.6.*
  - teamcity-messages -> python 2.7*
Use "conda info <package>" to see the dependencies for each package.

(pytest) C:\temp\sigtradetest\medh\conda-recipe>
```
Just for posterity here is the exact meta.yaml

```
package:
  name: medh
  version: "0.0.0.1"

source:
  path: ../


build:
  script: python setup.py install
  skip: True  # [py < 34]


requirements:
  build:
    - python
    - pandas
    - numpy
    - matplotlib

  run:
    - python
    - pandas
    - numpy
    - matplotlib

test:
  source_files:
    - test/.
  requires:
    - nose
    - teamcity-messages

```
I get that the package has a dependency on 2.7* but works for 2.7 > so do i have to change the dependency or can i force it to still use this package?

**Comment by msarahan** [comment]
No.  You need a matching build for your desired python version.  Conda packages include .pyc files, and thus are specific to a python version.

You can try noarch python packages, but no matter what, you'll need to rebuild the teamcity-messages package so that it supports your desired python version.
