### ISSUE TITLE
Error: setuptools cannot depend on itself

### ISSUE THREAD

**Issue by tomashek** [conda/conda-build#2540]
When trying to build the setuptools recipe in AnacondaRecipes/aggregate (ec1dbc30ab989fe2a65ed4d79a7b45ac6cb76d3a) I am getting the error "setuptools cannot depend on itself."  Setuptools is not directly listed as needed in the recipe, so it must be coming from another package. Calling "api.render" directly gives a potentially useful stacktrace before issuing "RuntimeError: setuptools cannot depend on itself":
```
>>> retdata = render(os.getcwd())
Attempting to finalize metadata for setuptools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/localdisk/work/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 49, in render
    permit_undefined_jinja=not finalize):
  File "/localdisk/work/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 1799, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/localdisk/work/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 683, in finalize_outputs_pass
    permit_unsatisfiable_variants)
  File "/localdisk/work/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 683, in finalize_outputs_pass
    permit_unsatisfiable_variants)
  File "/localdisk/work/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 678, in finalize_outputs_pass
    fm = finalize_metadata(m, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/localdisk/work/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 309, in finalize_metadata
    add_upstream_pins(m)
  File "/localdisk/work/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 271, in add_upstream_pins
    merge_build_host_on_same_platform=False)
  File "/localdisk/work/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 62, in get_env_dependencies
    specs = [ms.spec for ms in m.ms_depends(env)]
  File "/localdisk/work/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 1037, in ms_depends
    raise RuntimeError("%s cannot depend on itself" % self.name())
RuntimeError: setuptools cannot depend on itself
```
conda list output:
```
$ conda list
# packages in environment at /localdisk/work/miniconda3:
#
anaconda-client           1.6.6            py36h59e3ba0_0  
asn1crypto                0.23.0           py36h4639342_0  
attrs                     17.3.0           py36h5ab58ff_0  
beautifulsoup4            4.6.0            py36h49b8c8c_1  
ca-certificates           2017.08.26           h1d4fec5_0  
certifi                   2017.11.5        py36hf29ccca_0  
cffi                      1.11.2           py36h2825082_0  
chardet                   3.0.4            py36h0f667ec_1  
clyent                    1.2.2            py36h7e57e65_1  
conda                     4.3.30           py36h5d9f9f4_0  
conda-build               3.0.31           py36h269c84b_0  
conda-env                 2.6.0                h36134e3_1  
conda-verify              2.0.0            py36h98955d8_0  
constructor               2.0.1            py36hb4fd3a0_0  
coverage                  4.4.2            py36hca7c4c5_0  
cryptography              2.1.4            py36hd09be54_0  
curl                      7.55.1               h78862de_4  
decorator                 4.1.2            py36hd076ac8_0  
expat                     2.2.5                he0dffb1_0  
filelock                  2.0.13           py36h646ffb5_0  
git                       2.15.0          pl526h838b92b_0  
glob2                     0.6              py36he249c77_0  
hypothesis                3.38.5           py36h196a6cc_0  
idna                      2.6              py36h82fb2a8_1  
ipython_genutils          0.2.0            py36hb52b0d5_0  
jinja2                    2.10             py36ha16c418_0  
jsonschema                2.6.0            py36h006f8b5_0  
jupyter_core              4.4.0            py36h7c827e3_0  
libconda                  4.0.3                    py36_0  
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                h7cc24e2_2  
libssh2                   1.8.0                h2d05a93_3  
libstdcxx-ng              7.2.0                h7a57d05_2  
markupsafe                1.0              py36hd9260cd_1  
mock                      2.0.0            py36h3c5bf6c_0  
nbformat                  4.4.0            py36h31c9010_0  
ncurses                   6.0                  h9df7e31_2  
nose                      1.3.7            py36hcdf7029_2  
openssl                   1.0.2m               h26d622b_1  
patchelf                  0.9                  hf79760b_2  
pbr                       3.1.1            py36hb5f6b33_0  
perl                      5.26.0               hae598fd_0  
pip                       9.0.1            py36h6c6f9ce_4  
pkginfo                   1.4.1            py36h215d178_1  
pluggy                    0.6.0            py36hb689045_0  
py                        1.5.2            py36h29bf505_0  
pyasn1                    0.4.2            py36h4d1db45_0  
pycosat                   0.6.3            py36h0a5515d_0  
pycparser                 2.18             py36hf9f622e_1  
pycrypto                  2.6.1            py36h6998063_1  
pympler                   0.5              py36h6b12e4d_0  
pyopenssl                 17.5.0           py36h20ba746_0  
pysocks                   1.6.7            py36hd97a5b1_1  
pytest                    3.3.0            py36h23ce9bc_0  
python                    3.6.3                h6c0c0dc_5  
python-dateutil           2.6.1            py36h88d3b88_1  
pytz                      2017.3           py36h63b9c63_0  
pyyaml                    3.12             py36hafb9ca4_1  
readline                  7.0                  ha6073c6_4  
requests                  2.18.4           py36he2e5f8d_1  
ruamel_yaml               0.11.14          py36ha2fb22d_2  
setuptools                36.5.0           py36he42e2e1_0  
six                       1.11.0           py36h372c433_1  
sqlite                    3.20.1               hb898158_2  
tk                        8.6.7                hc745277_3  
traitlets                 4.3.2            py36h674d592_0  
urllib3                   1.22             py36hbe7ace6_0  
wheel                     0.30.0           py36hfd4bba0_1  
xlrd                      1.1.0            py36h1db9f0c_1  
xz                        5.2.3                h55aa19d_2  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               ha838bed_2  
zope                      1.0                      py36_0  
zope.interface            4.4.3            py36h0ccbf34_0 
```

**Comment by msarahan** [comment]
We always keep our build systems with add_pip_as_python_dependency set to off.  This is important for situations like exactly this one.

https://conda.io/docs/user-guide/configuration/use-condarc.html#add-pip-as-python-dependency-add-pip-as-python-dependency

The alternative is build/disable_pip in meta.yaml, which is meant to do the same thing, but does it in a crappier way.

**Comment by tomashek** [comment]
Thank you, that fixed my problem.
