### ISSUE TITLE
Wrong addition of vc package?

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#2559]
This is happening only with 3.1.2 and not with 3.1.1

I suspect the commit which caused this is: https://github.com/conda/conda-build/commit/2a71071d8fab8dc83d7d4a08d4c3df201a611899

Steps to reproduce:

```
(root) F:\nwani\aggregate\test-feedstock>type meta.yaml
package:
  name: test
  version: 1.0.0

requirements:
  host:
    - openssl
  build:
    - {{ compiler('c') }}

(root) F:\nwani\aggregate\test-feedstock>type conda_build_config.yaml
c_compiler:
  - vs2008                     # [win]
  - vs2015                     # [win]
cross_compiler_target_platform:
  - win-32                     # [win]
  - win-64                     # [win]
target_platform:
  - win-64                     # [win]
  - win-32                     # [win]
vc:
  - 9
  - 14
zip_keys:
  -                             # [win]
    - vc                        # [win]
    - c_compiler                # [win]
```

```
(root) F:\nwani\aggregate\test-feedstock>conda build . -m conda_build_config.yaml
Attempting to finalize metadata for test
INFO:conda_build.metadata:Attempting to finalize metadata for test
failed to get install actions, retrying.  exception was: The following specifications were found to be in conflict:
  - vc 14 h2379b0c_2
  - vc 9.*
Use "conda info <package>" to see the dependencies for each package.
WARNING:conda_build.environ:failed to get install actions, retrying.  exception was: The following specifications were found to be i
  - vc 14 h2379b0c_2
  - vc 9.*
Use "conda info <package>" to see the dependencies for each package.
Failed to get install actions, max retries exceeded.
ERROR:conda_build.environ:Failed to get install actions, max retries exceeded.
Traceback (most recent call last):
  File "f:\nwani\conda-build\conda_build\environ.py", line 691, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "F:\nwani\mc3\lib\site-packages\conda\plan.py", line 461, in install_actions
    update_deps, pinned)
  File "F:\nwani\mc3\lib\site-packages\conda\plan.py", line 631, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "F:\nwani\mc3\lib\site-packages\conda\resolve.py", line 813, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "F:\nwani\mc3\lib\site-packages\conda\resolve.py", line 868, in solve
    self.find_conflicts(specs)
  File "F:\nwani\mc3\lib\site-packages\conda\resolve.py", line 369, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - vc 14 h2379b0c_2
  - vc 9.*
Use "conda info <package>" to see the dependencies for each package.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\nwani\conda-build\conda_build\environ.py", line 691, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "F:\nwani\mc3\lib\site-packages\conda\plan.py", line 461, in install_actions
    update_deps, pinned)
  File "F:\nwani\mc3\lib\site-packages\conda\plan.py", line 631, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "F:\nwani\mc3\lib\site-packages\conda\resolve.py", line 813, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "F:\nwani\mc3\lib\site-packages\conda\resolve.py", line 868, in solve
    self.find_conflicts(specs)
  File "F:\nwani\mc3\lib\site-packages\conda\resolve.py", line 369, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - vc 14 h2379b0c_2
  - vc 9.*
Use "conda info <package>" to see the dependencies for each package.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\nwani\conda-build\conda_build\environ.py", line 691, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "F:\nwani\mc3\lib\site-packages\conda\plan.py", line 461, in install_actions
    update_deps, pinned)
  File "F:\nwani\mc3\lib\site-packages\conda\plan.py", line 631, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "F:\nwani\mc3\lib\site-packages\conda\resolve.py", line 813, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "F:\nwani\mc3\lib\site-packages\conda\resolve.py", line 868, in solve
    self.find_conflicts(specs)
  File "F:\nwani\mc3\lib\site-packages\conda\resolve.py", line 369, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - vc 14 h2379b0c_2
  - vc 9.*
Use "conda info <package>" to see the dependencies for each package.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\nwani\mc3\Scripts\conda-build-script.py", line 11, in <module>
    load_entry_point('conda-build', 'console_scripts', 'conda-build')()
  File "f:\nwani\conda-build\conda_build\cli\main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "f:\nwani\conda-build\conda_build\cli\main_build.py", line 379, in execute
    verify=args.verify)
  File "f:\nwani\conda-build\conda_build\api.py", line 187, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "f:\nwani\conda-build\conda_build\build.py", line 1828, in build_tree
    notest=notest,
  File "f:\nwani\conda-build\conda_build\build.py", line 916, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "f:\nwani\conda-build\conda_build\render.py", line 621, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "f:\nwani\conda-build\conda_build\metadata.py", line 1770, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "f:\nwani\conda-build\conda_build\metadata.py", line 655, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "f:\nwani\conda-build\conda_build\render.py", line 390, in finalize_metadata
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "f:\nwani\conda-build\conda_build\render.py", line 119, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "f:\nwani\conda-build\conda_build\environ.py", line 727, in get_install_actions
    channel_urls=tuple(channel_urls))
  File "f:\nwani\conda-build\conda_build\environ.py", line 727, in get_install_actions
    channel_urls=tuple(channel_urls))
  File "f:\nwani\conda-build\conda_build\environ.py", line 727, in get_install_actions
    channel_urls=tuple(channel_urls))
  File "f:\nwani\conda-build\conda_build\environ.py", line 691, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "F:\nwani\mc3\lib\site-packages\conda\plan.py", line 461, in install_actions
    update_deps, pinned)
  File "F:\nwani\mc3\lib\site-packages\conda\plan.py", line 631, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "F:\nwani\mc3\lib\site-packages\conda\resolve.py", line 813, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "F:\nwani\mc3\lib\site-packages\conda\resolve.py", line 868, in solve
    self.find_conflicts(specs)
  File "F:\nwani\mc3\lib\site-packages\conda\resolve.py", line 369, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - vc 14 h2379b0c_2
  - vc 9.*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by msarahan** [comment]
Sorry, can confirm.  Will fix ASAP.
