### ISSUE TITLE
render failure with variant and jinja2 dict

### ISSUE THREAD

**Issue by AntoineD** [conda/conda-build#2567]
Hello,

the following `conda_build_config.yaml` was working with `conda-build 3.0.27`, it fails now after I have updated to 3.1.2:
```
variant:
    -
        platform: X
        version: 1
        root: path-X
    -
        platform: Y
        version: 2
        root: path-Y
```

The error I get now:
```
Traceback (most recent call last):
  File "/anaconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 379, in execute
    verify=args.verify)
  File "/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 187, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1809, in build_tree
    bypass_env_check=True)
  File "/anaconda/lib/python2.7/site-packages/conda_build/render.py", line 703, in render_recipe
    allow_no_other_outputs=True, bypass_env_check=bypass_env_check)
  File "/anaconda/lib/python2.7/site-packages/conda_build/render.py", line 609, in distribute_variants
    (mv, need_source_download, None)
TypeError: unhashable type: 'dict'
```

If that's not a bug, how could I reproduce the same behavior as before?

**Comment by msarahan** [comment]
That's not really a bug, unfortunately.  You were using behavior that was never officially supported.  Only string values are supported for variants.  The equivalent notion to what you have is:

```
platform:
  - X
  - Y
version:
  - 1
  - 2
root:
  - path-X
  - path-Y
zip_keys:
  -
    - platform
    - version
    - root
```

It is essential that values are hashable for the sake of set operations and comparison across different configurations.  If you disagree, please submit a PR that keeps the current functionality but does not depend on sets.

**Comment by AntoineD** [comment]
Thanks @msarahan, unfortunately I was expecting this, I will loose the nice grouping of information from the old behavior.

**Comment by msarahan** [comment]
Yes, I agree.  I also don't really like it.  I just don't have ideas or time to do something better right now. =(
