### ISSUE TITLE
DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64

### ISSUE THREAD

**Issue by jlstevens** [conda/conda-build#2568]
I am getting the following nested exception when using conda-build version 3.1.2, which appears very shortly after running ``conda build .``:

```
Traceback (most recent call last):
  File "/Users/jstevens/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 691, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/Users/jstevens/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/Users/jstevens/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 631, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/Users/jstevens/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 813, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/Users/jstevens/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 853, in solve
    reduced_index = self.get_reduced_index(specs)
  File "/Users/jstevens/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 374, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/Users/jstevens/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 300, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound:
  - bokeh 0.12.13.*

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jstevens/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/jstevens/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/Users/jstevens/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 379, in execute
    verify=args.verify)
  File "/Users/jstevens/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 187, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/Users/jstevens/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1828, in build_tree
    notest=notest,
  File "/Users/jstevens/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1025, in build
    raise e
  File "/Users/jstevens/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1016, in build
    channel_urls=tuple(m.config.channel_urls))
  File "/Users/jstevens/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 693, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: {'bokeh 0.12.13.*'}
```
Here is the corresponding [meta.yaml](https://github.com/ioam/holoviews/blob/master/meta.yaml):

```yaml
package:
  name: holoviews
  version: 1.9.2

source:
  path: .

extra:
  channels:
    - conda-forge
    
requirements:
  build:
    - python
    - param
    - numpy
    - setuptools
  run:
    - python
    - param >=1.5.1,<2.0
    - numpy
    - matplotlib
    - bokeh ==0.12.13
    - jupyter
    - notebook
    - ipython

test:
  imports:
    - holoviews

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  license: BSD 3-Clause
```

My current workaround is to downgrade to version 2.1.18 from conda-forge which builds the package just fine. Any idea why this meta.yaml would not work with the newer conda-build version?

**Comment by msarahan** [comment]
I believe this is a problem with noarch packages.  They technically live on a separate channel from the platform-native packages, and I have had bugs in the past where noarch packages were not getting included in the appropriate indices.  I'll try to write a test to suss this out.

**Comment by msarahan** [comment]
I tested noarch stuff with conda-build 3.1.2, but it all worked OK.

I think you're expecting your extra/channels thing to add channels for you.  That's not actually valid code.  It might do something extra for conda-forge, but by definition, anything in ``extra`` is not used by conda-build.

**Comment by msarahan** [comment]
Yeah, one day we'll have better exception handling.  Hard hats required right now.  I'm very lucky to run a project that is used almost exclusively by developers!

**Comment by Danceiny** [comment]
So, how to solve this? Same case occured on me .

**Comment by msarahan** [comment]
This issue was a misunderstanding about valid inputs to a recipe.  You may have the same traceback, but it probably comes about for different reasons.  Please file a new issue, and provide all information that the issue template asks for.

**Comment by Chris-Lowe-Integrity** [comment]
I'm running into this problem. Any solution?
