### ISSUE TITLE
noarch python-scripts/script_name not in info/files

### ISSUE THREAD

**Issue by CJ-Wright** [conda/conda-build#2575]
I ran into the following exception while trying to build a noarch version of [bluesky](https://github.com/conda-forge/staged-recipes/pull/4620)
```python
'python-scripts/bluesky-0MQ-proxy' not in info/files
Traceback (most recent call last):
  File "/home/christopher/mc/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/christopher/mc/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/home/christopher/mc/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/home/christopher/mc/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/home/christopher/mc/lib/python3.6/site-packages/conda_build/build.py", line 1524, in build_tree
    config=config)
  File "/home/christopher/mc/lib/python3.6/site-packages/conda_build/build.py", line 1159, in build
    built_package = bundlers[output_dict.get('type', 'conda')](output_dict, m, config, env)
  File "/home/christopher/mc/lib/python3.6/site-packages/conda_build/build.py", line 931, in bundle_conda
    tarcheck.check_all(tmp_path)
  File "/home/christopher/mc/lib/python3.6/site-packages/conda_build/tarcheck.py", line 90, in check_all
    x.info_files()
  File "/home/christopher/mc/lib/python3.6/site-packages/conda_build/tarcheck.py", line 55, in info_files
    raise Exception('info/files')
Exception: info/files
```

The file is listed under scripts in the [repo](https://github.com/NSLS-II/bluesky/tree/master/scripts).
What is going wrong?

**Comment by msarahan** [comment]
What kind of noarch were you trying?  Old style or new style?  It looks like probably new style.  I don't know off the top of my head.  It's highly likely that other conda-forge people who have done more with noarch packages might know.  It may be that conda-build simply doesn't handle those scripts right now.  I know it handles entry points, but those scripts are a little different.

**Comment by CJ-Wright** [comment]
I used `noarch: python` I'm running `conda-build 2.17.1` (so I'm in line with conda-forge (mostly)).

**Comment by dirmeier** [comment]
Hello, did you manage to fix this @CJ-Wright  or did you just drop the `noarch`?

**Comment by CJ-Wright** [comment]
I think this will be fixed in conda build 3. I just dropped the noarch.
