### ISSUE TITLE
Wrong dependencies to different python version 

### ISSUE THREAD

**Issue by verdimrc** [conda/conda-build#2582]
I found that `conda build` will fail if the local repo (`$HOME/miniconda3/conda-bld`) contains packages for a different Python version.

The example below successfully builds python-3.6 packages, but then fails to build with python 2.7.  

## Build python 3.6 packages

```bash
$ conda skeleton pypi /tmp awscli botocore
$ conda build /tmp/awscli /tmp/botocore

$ ls -al $HOME/miniconda3/conda-bld/linux-64/
-rw-rw-r-- 1 xxx xxx  801810 Dec 15 08:36 awscli-1.14.10-py36_0.tar.bz2
-rw-rw-r-- 1 xxx xxx 3017388 Dec 15 08:35 botocore-1.8.14-py36_0.tar.bz2
-rw-rw-r-- 1 xxx xxx    1367 Dec 15 08:40 repodata.json
-rw-rw-r-- 1 xxx xxx     637 Dec 15 08:40 repodata.json.bz2
```

## Now build python 2.7, which will fail.

```bash
$ rm -fr /tmp/awscli /tmp/botocore
$ conda skeleton pypi /tmp --python-version 2.7 awscli botocore
$ conda build --python 2.7 /tmp/awscli /tmp/botocore
Attempting to finalize metadata for awscli
INFO:conda_build.metadata:Attempting to finalize metadata for awscli
failed to get install actions, retrying.  exception was: The following specifications were found to be in conflict:
  - botocore ==1.8.14 -> python >=3.6,<3.7.0a0
  - python 2.7.*
Use "conda info <package>" to see the dependencies for each package.
WARNING:conda_build.environ:failed to get install actions, retrying.  exception was: The following specifications were found to be in conflict:
  - botocore ==1.8.14 -> python >=3.6,<3.7.0a0
  - python 2.7.*
Use "conda info <package>" to see the dependencies for each package.
Failed to get install actions, max retries exceeded.
ERROR:conda_build.environ:Failed to get install actions, max retries exceeded.
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 691, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 631, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 813, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 868, in solve
    self.find_conflicts(specs)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 369, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - botocore ==1.8.14 -> python >=3.6,<3.7.0a0
  - python 2.7.*
Use "conda info <package>" to see the dependencies for each package.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 691, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 631, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 813, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 868, in solve
    self.find_conflicts(specs)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 369, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - botocore ==1.8.14 -> python >=3.6,<3.7.0a0
  - python 2.7.*
Use "conda info <package>" to see the dependencies for each package.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 691, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 631, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 813, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 868, in solve
    self.find_conflicts(specs)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 369, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - botocore ==1.8.14 -> python >=3.6,<3.7.0a0
  - python 2.7.*
Use "conda info <package>" to see the dependencies for each package.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 393, in main
    execute(sys.argv[1:])
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 384, in execute
    verify=args.verify)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 187, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1842, in build_tree
    notest=notest,
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 944, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 623, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 1775, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 660, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 372, in finalize_metadata
    exclude_pattern)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 296, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 284, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 119, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 727, in get_install_actions
    channel_urls=tuple(channel_urls))
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 727, in get_install_actions
    channel_urls=tuple(channel_urls))
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 727, in get_install_actions
    channel_urls=tuple(channel_urls))
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 691, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 631, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 813, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 868, in solve
    self.find_conflicts(specs)
  File "/home/ec2-user/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 369, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - botocore ==1.8.14 -> python >=3.6,<3.7.0a0
  - python 2.7.*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by mingwandroid** [comment]
`conda build --python 2.7 /tmp/awscli /tmp/botocore`

You are building your packages in the wrong order.

`conda-build` does not reorder into dependency order. If you swap you command line to:

`conda build --python 2.7 /tmp/botocore /tmp/awscli`

.. then this problem should go away.

Please close if that is the case.

**Comment by verdimrc** [comment]
Your workaround does work. However, I still feel it's strange for conda to allow dependencies across Python version. I don't recall ever seeing `conda install` pulls such thing.

I've also found build variant to solve the problem without the need to reorder the cli. But, this does not work for certain packages. `s3transfer` is the prime example: it needs a skeleton generated with `conda skeleton pypi --python-version 2.7 ...`.

**Comment by mingwandroid** [comment]
It is not a workaround, simply that's how conda-build works.

Conda is *not* allowing dependencies across Python versions, the opposite in fact, it is telling you that they conflict and refusing to do this, clearly:

```
The following specifications were found to be in conflict:
  - botocore ==1.8.14 -> python >=3.6,<3.7.0a0
  - python 2.7.*
```

Reordering the command line is the correct approach here.
