### ISSUE TITLE
IndexError: list index out of range since 3.1.4

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda-build#2591]
I have attached the broken recipe which worked with 3.1.3:

[troubled-mpi4py.tar.gz](https://github.com/conda/conda-build/files/1569742/troubled-mpi4py.tar.gz)

Looks like the variants expansion has changed in an incompatible way since 3.1.4. The problem affects 3.1.6 as well. 

The command line is
```
 conda build --skip-existing -m variants/python-3.6.yaml platform/mpi4py
Traceback (most recent call last):
  File "/home/yfeng1/anaconda3/install/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 393, in main
    execute(sys.argv[1:])
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 384, in execute
    verify=args.verify)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/api.py", line 186, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/build.py", line 1828, in build_tree
    bypass_env_check=True)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/render.py", line 682, in render_recipe
    allow_no_other_outputs=True, bypass_env_check=bypass_env_check)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/render.py", line 514, in distribute_variants
    used_variables = mv.get_used_loop_vars()
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/metadata.py", line 1807, in get_used_loop_vars
    add_zip_keys=False)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/metadata.py", line 1812, in get_used_vars
    meta_yaml_reqs = self._get_used_vars_meta_yaml(force_top_level=force_top_level)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/metadata.py", line 1860, in _get_used_vars_meta_yaml
    build_reqs = {req.split()[0].replace('-', '_') for req in build_reqs}
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/metadata.py", line 1860, in <setcomp>
    build_reqs = {req.split()[0].replace('-', '_') for req in build_reqs}
IndexError: list index out of range
```

**Comment by rainwoodman** [comment]
Apparently the newer conda-build refuses to pass along the variants variables defined in the variants file to the recipes.

**Comment by msarahan** [comment]
fixed in https://github.com/conda/conda-build/pull/2590/commits/3aa3462e9fa5f43f6fc5fd2031fbdacf8487b388#diff-c86934c27c2f25579540ddb447fa45bdR1866

Rendering and jinja2 variable insertion is handled in multiple phases.  You were eventually going to get the right answer, but in an early phase, you had an empty variable.  We needed to ignore that early on, and trust that it will be there later.
