### ISSUE TITLE
Cannot install conda-build 3.2.0

### ISSUE THREAD

**Issue by AntoineD** [conda/conda-build#2600]
Hello,

I am on a REHL 5.5 with anaconda 4.4, I was able to install recent version of conda-build by [hand ](https://github.com/conda/conda-build/issues/2450#issuecomment-337625349) but with the version 3.2.0 it fails:
```
 conda install /scratch/xxx/anaconda/pkgs/conda-build-3.2.0-py27_0.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : 3.1.3
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /scratch/xxx/anaconda  (writable)
    default environment : /scratch/xxx/anaconda
       envs directories : /scratch/xxx/conda-envs
                          /scratch/xxx/anaconda/envs
                          /home/xxx/.conda/envs
          package cache : /scratch/xxx/anaconda/pkgs
                          /home/xxx/.conda/pkgs
           channel URLs : file:///scratch/xxx/conda-bld/linux-64
                          file:///scratch/xxx/conda-bld/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /home/xxx/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.14.2 CPython/2.7.13 Linux/2.6.18-422.el5 Red Hat Enterprise Linux Server/5.11 glibc/2.5
                UID:GID : 7679:107679

`$ /scratch/xxx/anaconda/bin/conda install /scratch/xxx/anaconda/pkgs/conda-build-3.2.0-py27_0.tar.bz2`


    Traceback (most recent call last):
      File "/scratch/xxx/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/scratch/xxx/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/scratch/xxx/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/scratch/xxx/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 210, in install
        explicit(args_packages, prefix, verbose=not context.quiet)
      File "/scratch/xxx/anaconda/lib/python2.7/site-packages/conda/misc.py", line 110, in explicit
        execute_actions(actions, index, verbose=verbose)
      File "/scratch/xxx/anaconda/lib/python2.7/site-packages/conda/plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/scratch/xxx/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/scratch/xxx/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/scratch/xxx/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 125, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/scratch/xxx/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 125, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/scratch/xxx/anaconda/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 95, in read_package_info
        paths_data=paths_data,
      File "/scratch/xxx/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/scratch/xxx/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/scratch/xxx/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 831, in __setattr__
        super(ImmutableEntity, self).__setattr__(attribute, value)
      File "/scratch/xxx/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/scratch/xxx/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Value for url cannot be None.
```
Is it expected?

**Comment by msarahan** [comment]
This is a conda issue.  Installing packages from files as you are doing makes the installation much less standard - it doesn't install dependencies, for example.  Something is definitely going wrong, but the conda issue tracker is the better place to discuss what it might be.  I'll move this issue for you.

**Comment by msarahan** [comment]
Issue moved to [conda/conda #6537](https://github.com/conda/conda/issues/6537) via [**ZenHub**](https://www.zenhub.com/)
