### ISSUE TITLE
Unable to use compiler activation scripts in split packages

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#2605]
Given the following recipe...
```
(base) [root@eb29c4d90e4d recipe]# cat meta.yaml 
package:
  name: test
  version: 1.0.0

outputs:
  - name: test-split1
    script: build-split1.sh
    requirements:
      build:
        - {{ compiler('c') }}
```
...with the following build script:
```
(base) [root@eb29c4d90e4d recipe]# cat build-split1.sh 
#!/bin/bash
set -eux
echo $CC
```
...it fails with:
```
(base) [root@eb29c4d90e4d recipe]# conda build .
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /root/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /root/conda_build_config.yaml
Attempting to finalize metadata for test-split1
INFO:conda_build.metadata:Attempting to finalize metadata for test-split1
Solving environment: done
Solving environment: done
BUILD START: ['test-split1-1.0.0-h14c3975_0.tar.bz2']
source tree in: /opt/conda/conda-bld/test_1514396605175/work
Packaging test-split1
INFO:conda_build.build:Packaging test-split1
Solving environment: done

## Package Plan ##

  environment location: /opt/conda/conda-bld/test_1514396605175/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol


The following NEW packages will be INSTALLED:

    binutils_impl_linux-64: 2.28.1-h04c84fa_2
    binutils_linux-64:      7.2.0-19         
    gcc_impl_linux-64:      7.2.0-hc5ce805_2 
    gcc_linux-64:           7.2.0-19         
    libstdcxx-ng:           7.2.0-h7a57d05_2 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Packaging test-split1-1.0.0-h14c3975_0
INFO:conda_build.build:Packaging test-split1-1.0.0-h14c3975_0
/opt/conda/conda-bld/test_1514396605175/work/build-split1.sh: line 3: CC: unbound variable
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 393, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 384, in execute
    verify=args.verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 186, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1885, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1321, in build
    built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 782, in bundle_conda
    cwd=metadata.config.work_dir, env=env_output)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 677, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 673, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', '/opt/conda/conda-bld/test_1514396605175/work/build-split1.sh']' returned non-zero exit status 1.
```
Am I doing something wrong or is this expected?

**Comment by nehaljwani** [comment]
```
(base) [root@eb29c4d90e4d recipe]# conda -V
conda 4.4.4
(base) [root@eb29c4d90e4d recipe]# conda build -V
conda-build 3.2.0
```

**Comment by nehaljwani** [comment]
Ah, I looked at the boost recipe, looks like we need to activate the build environment manually.

**Comment by jjhelmus** [comment]
@nehaljwani Yes, the output install scripts need to activate the build/host environments manually if they wish to make use of the packages they contain.  

I believe this was an intentional decision.  The main use case for the output install scripts is to move and copy a set of files from the work directory into the output directory.  This does not require that the build or host environment be activated.

The following snippet can be used to activate both the build and host environments with the host environment "stacked" on top of the build environment:

``` bash
# activate the build environment
. activate "${BUILD_PREFIX}"

# "stack" the host environment on top of the build env
mkdir -p "${PREFIX}/conda-meta"
touch "${PREFIX}/conda-meta/history"
unset CONDA_PATH_BACKUP
export CONDA_MAX_SHLVL=2
source ${BUILD_PREFIX}/bin/activate "${PREFIX}"
```

**Comment by msarahan** [comment]
Yes, it was more or less intentional.  The main reason behind it was that the packaging scripts can be any kind of script, so we don't necessarily know how to add activation to them.  We could special-case a few common kinds (.sh, .bat) to add activation to them, but it's so rarely necessary that the stuff @jjhelmus posted is good enough for now.
