### ISSUE TITLE
conda skeleton cpan Object::InsideOut fails

### ISSUE THREAD

**Issue by nathanweeks** [conda/conda-build#2610]
Error:

```
$ conda skeleton cpan --recursive Object::InsideOut
Processing dependencies for Object::InsideOut......INFO:fetch.start:('Exception-Clas', 1235)
INFO:fetch.update:1235
INFO:fetch.stop:None
Traceback (most recent call last):
  File "/tmp/miniconda/bin/conda-skeleton", line 6, in <module>
    sys.exit(conda_build.cli.main_skeleton.main())
  File "/tmp/miniconda/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 66, in main
    return execute(sys.argv[1:])
  File "/tmp/miniconda/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 62, in execute
    version=args.version, config=config)
  File "/tmp/miniconda/lib/python3.5/site-packages/conda_build/api.py", line 208, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/tmp/miniconda/lib/python3.5/site-packages/conda_build/skeletons/cpan.py", line 278, in skeletonize
    recursive=recursive, config=config)
  File "/tmp/miniconda/lib/python3.5/site-packages/conda_build/skeletons/cpan.py", line 514, in deps_for_package
    dep_version, perl_version, dependency=True, config=config)
  File "/tmp/miniconda/lib/python3.5/site-packages/conda_build/skeletons/cpan.py", line 637, in get_release_info
    new_rel_dict['version'] = str(new_rel_dict['version']).lstrip()
KeyError: 'version'
```

Platform info:

```
$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : 2.1.16
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /tmp/miniconda  (writable)
    default environment : /tmp/miniconda
       envs directories : /tmp/miniconda/envs
                          /Users/foo/.conda/envs
          package cache : /tmp/miniconda/pkgs
                          /Users/foo/.conda/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.12.4 CPython/3.5.2 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 502:20
```

**Comment by msarahan** [comment]
conda-build 2.1.x is no longer supported.  Please try again with a current version (3.2.0 is the latest).

**Comment by msarahan** [comment]
Closing due to inactivity.
