### ISSUE TITLE
Conda Skeleton RPM: Problem with valid_depends()

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#2626]
Attempt to create a CDT package for libselinux-devel for ppc64le:
```
[root@e8b78a05dc12 tmp]# conda skeleton rpm --recursive libselinux-devel --architecture ppc64le --distro centos7
Source cache directory is: /opt/conda/conda-bld/src_cache
No hash (md5, sha1, sha256) provided.  Source download forced.  Add hash to recipe to use source cache.
WARNING:conda_build.source:No hash (md5, sha1, sha256) provided.  Source download forced.  Add hash to recipe to use source cache.
Source cache directory is: /opt/conda/conda-bld/src_cache
Found source in cache: ba509e6a0bc99d1461701886a7e76bce03bd45a931ba2293462d72f917ed40c0
Source cache directory is: /opt/conda/conda-bld/src_cache
Found source in cache: libselinux-devel-2.5-11.el7.ppc64le.rpm
Source cache directory is: /opt/conda/conda-bld/src_cache
Found source in cache: libselinux-2.5-11.el7.src.rpm
--dirty flag and --keep-old-work not specified.Removing build/test folder after successful build/test.

INFO:conda_build.config:--dirty flag and --keep-old-work not specified.Removing build/test folder after successful build/test.
```

The recipe doesn't specify a runtime requirement on libselinux and when I try to build it:
```
Making absolute symlink powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib64/libselinux.so -> libselinux.so.1 relative
Fixing permissions
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 399, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 390, in execute
    verify=args.verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 188, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1916, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1348, in build
    built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 822, in bundle_conda
    output['checksums'] = create_info_files(metadata, files, prefix=metadata.config.host_prefix)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 562, in create_info_files
    checksums = create_info_files_json_v1(m, m.config.info_dir, prefix, files, files_with_prefix)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 664, in create_info_files_json_v1
    files_json_files = build_info_files_json_v1(m, prefix, files, files_with_prefix)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 644, in build_info_files_json_v1
    "size_in_bytes": os.path.getsize(path),
  File "/opt/conda/lib/python3.6/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/conda-bld/libselinux-devel-cos7-ppc64le_1515930435255/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib64/libselinux.so'
```

But this doesn't happen when I try to do the same for x86_64. Let's compare the rpm requirements:
```
[root@e8b78a05dc12 tmp]# paste -d '|' <(rpm -qpR libselinux-devel-2.0.94-7.el6.x86_64.rpm 2>/dev/null) <(rpm -qpR libselinux-devel-2.5-11.el7.ppc64le.rpm 2>/dev/null)
/usr/bin/pkg-config  |/usr/bin/pkg-config  
libselinux = 2.0.94-7.el6|libselinux(ppc-64) = 2.5-11.el7        <-------------------
libselinux.so.1()(64bit)  |libselinux.so.1()(64bit)  
libsepol-devel >= 2.0.32-1|libsepol-devel(ppc-64) >= 2.5-6   <-------------------
pkgconfig(libsepol)  |pkgconfig(libpcre)  
rpmlib(CompressedFileNames) <= 3.0.4-1|pkgconfig(libsepol)  
rpmlib(FileDigests) <= 4.6.0-1|rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1|rpmlib(FileDigests) <= 4.6.0-1
rpmlib(VersionedDependencies) <= 3.0.3-1|rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1|rpmlib(PayloadIsXz) <= 5.2-1
```
`libselinux(ppc-64)` and `libsepol-devel(ppc-64)` are valid requirements, which are being rejected, so I think the culprit line is: https://github.com/conda/conda-build/blob/3.2.2/conda_build/skeletons/rpm.py#L440

I would've sent a PR, but I don't know what the right fix is or whether removing that line will break something else.

**Comment by mingwandroid** [comment]
I basically guessed at much of the implementation of this and it was done in a hurry.

There's a command line argument to add dependencies though which you can use to work around these issues (please see my build-in-order script which uses it). I won't have time to investigate a proper fix anytime soon.
