### ISSUE TITLE
attribute error during check_overlinking in conda-build-3.3.0

### ISSUE THREAD

**Issue by marscher** [conda/conda-build#2651]
A long working recipe now fails with the recent conda-build release.
recipe: https://github.com/markovmodel/PyEMMA/blob/a004721bfdcbcf97da861e7c7f1b894cb026e795/devtools/conda-recipe/meta.yaml

travis log: https://travis-ci.org/markovmodel/PyEMMA/jobs/333273095#L1740

```
WARNING (pyemma-dev,_ext.cpython-36m-x86_64-linux-gnu.so): lib/libstdc++.so.6 found in multiple packages:
WARNING (pyemma-dev,_ext.cpython-36m-x86_64-linux-gnu.so): defaults::gcc-4.8.5-7
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 413, in main
    execute(sys.argv[1:])
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 404, in execute
    verify=args.verify)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 188, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1913, in build_tree
    notest=notest,
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1343, in build
    built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 806, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 707, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/post.py", line 592, in post_build
    check_overlinking(m, files)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/post.py", line 528, in check_overlinking
    _inspect_file_linking(m, path, files, errors, pkg_name, run_reqs, sysroots)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/post.py", line 505, in _inspect_file_linking
    msg_prelude, info_prelude)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda_build/post.py", line 440, in _find_needed_dso_in_prefix
    if pkg.dist_name not in m.meta.requirements.host:
AttributeError: 'dict' object has no attribute 'requirements'
```

**Comment by marscher** [comment]
forgot to mention that I'm using conda-forge as highest priority channel.

**Comment by mingwandroid** [comment]
Ah ok, this is my fault. This codepath was probably never exercised. Working on a fix now.

**Comment by marscher** [comment]
Looks good. Thank you!

**Comment by msarahan** [comment]
Fixed in #2652, new release coming soon.

**Comment by Colelyman** [comment]
I am experiencing the same problem. Is there an ETA for the new release with this fix?

**Comment by msarahan** [comment]
@Colelyman later today.  Sorry for the inconvenience.

**Comment by msarahan** [comment]
@Colelyman conda-build 3.4.0 is available now.
