### ISSUE TITLE
Improve conda-build error message when the build.sh script fails

### ISSUE THREAD

**Issue by nh13** [conda/conda-build#2660]
`conda-build` should echo the error from standard error when running the build script.  This would speed up debugging of conda recipes.  I believe we need to customize the `check_call` invocation somewhere around here:

https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1214

```python
                    cmd = [shell_path] + (['-x'] if m.config.debug else []) + ['-e', work_file]
                    # this should raise if any problems occur while building
                    utils.check_call_env(cmd, env=env, cwd=src_dir)
                    utils.remove_pycache_from_scripts(m.config.host_prefix)
```

**Comment by msarahan** [comment]
I'm not sure what you're hoping to see.  Stdout and stderr are already dumped to the console.  What's being swallowed might be the return code, but everything else should already be showing up.  Can you come up with an example recipe that shows some text that isn't showing up in the console?

**Comment by msarahan** [comment]
PS: much of the time, the relevant debugging info isn't on stderr at all.  ``config.log`` is a very common place that I have to go digging, for example.  It strongly depends on what software you're building - how they have their build scripts set up.

**Comment by nh13** [comment]
Bad conda-recipe: https://github.com/nh13/bfx-qc-reporter/commit/6790f116d7e785fd367c5dabdb4820e38f656b65
Fixed conda-recipe: https://github.com/nh13/bfx-qc-reporter/commit/6fb51accb92f02c57158c5f427f7714eef8bd14d

Once I looked at the temporary build script, and ran each line one-by-one it was obvious, I got a 'coverage not found' error message.  This error message wasn't output by `conda-build`, instead, all I got was a CalledProcessError from `subprocess.check_call` that it failed calling the `bash -x -c ...build.sh` script.  I would rather have the message that `coverage` was not found.

Thanks for your help in advance!

**Comment by msarahan** [comment]
What conda-build version are you running?  I don't think they change this behavior over time, but you should be seeing this error:

```
conda_build.exceptions.CondaBuildException: Found a build.sh script and a build/script sectioninside meta.yaml. Either remove the build.sh script or remove the build/script section in meta.yaml.
```

**Comment by msarahan** [comment]
also, my output does show the error (look just above the traceback):

```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Source cache directory is: /opt/conda/conda-bld/src_cache
Found source in cache: 79f16c5_daa6d0ce98.tar.gz
Extracting download
source tree in: /opt/conda/conda-bld/bfx-qc-reporter_1517006695118/work
/opt/conda/conda-bld/bfx-qc-reporter_1517006695118/work/conda_build.sh: line 62: coverage: command not found
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 413, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 404, in execute
    verify=args.verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 188, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1913, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1213, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 678, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 674, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/opt/conda/conda-bld/bfx-qc-reporter_1517006695118/work/conda_build.sh']' returned non-zero exit status 127.
```

Now, would it be better to not show the traceback?  Perhaps, but that's sugar that I don't have time for right now.

**Comment by nh13** [comment]
An old version could be the issue. Weird since I installed the latest conda in my docker image using miniconda and then installed conda build (`condal install -q -y conda-build`).  I am not sure why it is so outdated!  I am glad the error is right before the stacktrace in 3.3.0.

Here's the relevant output:
```
WARNING: conda-build appears to be out of date. You have version 2.1.18 but the
latest version is 3.3.0. Run

conda update -n root conda-build

to get the latest version.

BUILD START: bfx-qc-reporter-0.0.1a-py36_0
    (actual version deferred until further download or env creation)

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.11.5-0      conda-forge
    certifi:         2017.11.5-py36_0 conda-forge
    ncurses:         5.9-10           conda-forge
    openssl:         1.0.2n-0         conda-forge
    pip:             9.0.1-py36_1     conda-forge
    python:          3.6.4-0          conda-forge
    readline:        7.0-0            conda-forge
    setuptools:      38.4.0-py36_0    conda-forge
    sqlite:          3.20.1-2         conda-forge
    tk:              8.6.7-0          conda-forge
    wheel:           0.30.0-py36_2    conda-forge
    xz:              5.2.3-0          conda-forge
    zlib:            1.2.11-0         conda-forge

Source cache directory is: /root/miniconda3/conda-bld/src_cache
Downloading source to cache: 79f16c5.tar.gz
Downloading https://github.com/nh13/bfx-qc-reporter/archive/79f16c5.tar.gz
79f16c5.tar.gz 100% |###############################| Time: 0:00:00 306.46 kB/s
Success
Extracting download
BUILD START (revised): bfx-qc-reporter-0.0.1a-py36_0
Package: bfx-qc-reporter-0.0.1a-py36_0
source tree in: /root/miniconda3/conda-bld/bfx-qc-reporter_1517000501675/work/bfx-qc-reporter-79f16c536a0cf99f4fdebdbcd3e0811f8aae48c3
Traceback (most recent call last):
  File "/root/miniconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/root/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/root/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/root/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/root/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1524, in build_tree
    config=config)
  File "/root/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1147, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/root/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 628, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 624, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/root/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/root/miniconda3/conda-bld/bfx-qc-reporter_1517000501675/work/bfx-qc-reporter-79f16c536a0cf99f4fdebdbcd3e0811f8aae48c3/conda_build.sh']' returned non-zero exit status 127.
The command '/bin/sh -c cd /build/bfx-qc-rep...
```

**Comment by msarahan** [comment]
2.1.18 is the latest in that release series, but it's pretty out of date.  There have been a few things cherry-picked back from the 3 series, but not much.  It's really not worth the effort to maintain, because I have really tried to make the 3 series releases be backwards-compatible with software written against conda-build 2.x.

I know conda-forge is very close to adopting conda-build 3.  If you got your docker image from another organization, you should ask them why they're stuck on conda-build 2.1.x, and what they need in order to move to current conda-build.

**Comment by nh13** [comment]
the Docket build is mine. I am installing the latest Miniconda using their install script. Looks like that must be outdated. Thanks for your help and I think I can close this issue!!!
