### ISSUE TITLE
"ValueError: substring not found" in pylld.py

### ISSUE THREAD

**Issue by sscherfke** [conda/conda-build#2674]
The following recipe used to build in conda build 3.2.2 but not in 3.3.0 and 3.4.0

```yaml
# meta.yaml
{% set version = '6.2.0' %}
{% set sha256 = 'e99cbf7a74aa341b2e9015e3bab980f3094b96bf7f40f43971f412917eda24fb' %}

package:
  name: filebeat
  version: '{{ version }}'

source:
  url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ version }}-linux-x86_64.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

test:
  commands:
    - filebeat --version

about:
  summary: Filebeat is an open source file harvester, mostly used to fetch logs files and feed them into logstash.
  home: https://www.elastic.co/products/beats/filebeat
  license: Apache2

extra:
  changelog_url: https://www.elastic.co/guide/en/beats/libbeat/master/release-notes.html
```
```bash
# build.sh
mkdir -p $PREFIX/share/filebeat
mv filebeat $PREFIX/bin/
mv * $PREFIX/share/filebeat/
```
### Actual Behavior

```console
$ conda build filebeat
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for filebeat
INFO:conda_build.metadata:Attempting to finalize metadata for filebeat
BUILD START: ['filebeat-6.2.0-0.tar.bz2']
Source cache directory is: /opt/emsconda/conda-bld/src_cache
Found source in cache: filebeat-6.2.0-linux-x86_64_e99cbf7a74.tar.gz
Extracting download
source tree in: /opt/emsconda/conda-bld/filebeat_1518080462264/work
Packaging filebeat
INFO:conda_build.build:Packaging filebeat
Packaging filebeat-6.2.0-0
INFO:conda_build.build:Packaging filebeat-6.2.0-0
number of files: 241
Fixing permissions
patchelf: file: /opt/emsconda/conda-bld/filebeat_1518080462264/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/filebeat
    setting rpath to: $ORIGIN/../lib
Traceback (most recent call last):
  File "/opt/emsconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/emsconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 413, in main
    execute(sys.argv[1:])
  File "/opt/emsconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 404, in execute
    verify=args.verify)
  File "/opt/emsconda/lib/python3.6/site-packages/conda_build/api.py", line 193, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/opt/emsconda/lib/python3.6/site-packages/conda_build/build.py", line 1944, in build_tree
    notest=notest,
  File "/opt/emsconda/lib/python3.6/site-packages/conda_build/build.py", line 1374, in build
    built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env)
  File "/opt/emsconda/lib/python3.6/site-packages/conda_build/build.py", line 815, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/opt/emsconda/lib/python3.6/site-packages/conda_build/build.py", line 711, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/opt/emsconda/lib/python3.6/site-packages/conda_build/post.py", line 593, in post_build
    check_overlinking(m, files)
  File "/opt/emsconda/lib/python3.6/site-packages/conda_build/post.py", line 529, in check_overlinking
    _inspect_file_linking(m, path, files, errors, pkg_name, run_reqs, host_reqs, sysroots)
  File "/opt/emsconda/lib/python3.6/site-packages/conda_build/post.py", line 501, in _inspect_file_linking
    needed = inspect_linkages(path, resolve_filenames=True, recurse=False)
  File "/opt/emsconda/lib/python3.6/site-packages/conda_build/os_utils/pyldd.py", line 1023, in inspect_linkages
    filename, sysroot=sysroot, arch=arch)
  File "/opt/emsconda/lib/python3.6/site-packages/conda_build/os_utils/pyldd.py", line 982, in _inspect_linkages_this
    cf = codefile(f, arch)
  File "/opt/emsconda/lib/python3.6/site-packages/conda_build/os_utils/pyldd.py", line 916, in codefile
    return elffile(file, list(initial_rpaths_transitive))
  File "/opt/emsconda/lib/python3.6/site-packages/conda_build/os_utils/pyldd.py", line 831, in __init__
    es.postprocess(self, file)
  File "/opt/emsconda/lib/python3.6/site-packages/conda_build/os_utils/pyldd.py", line 763, in postprocess
    end = r + strsec.table[r:].index('\0')
ValueError: substring not found
```

### Expected Behavior

```console
$ conda build filebeat
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for filebeat
INFO:conda_build.metadata:Attempting to finalize metadata for filebeat
BUILD START: ['filebeat-6.2.0-0.tar.bz2']
Source cache directory is: /opt/emsconda/conda-bld/src_cache
Found source in cache: filebeat-6.2.0-linux-x86_64_e99cbf7a74.tar.gz
Extracting download
source tree in: /opt/emsconda/conda-bld/filebeat_1518080567753/work
Packaging filebeat
INFO:conda_build.build:Packaging filebeat
Packaging filebeat-6.2.0-0
INFO:conda_build.build:Packaging filebeat-6.2.0-0
number of files: 241
Fixing permissions
patchelf: file: /opt/emsconda/conda-bld/filebeat_1518080567753/_h_env_placehold_placehold_placehold_placehold_placehol
d_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
old_placehold_placehold_placehold_p/bin/filebeat
    setting rpath to: $ORIGIN/../lib
Fixing permissions
Detected hard-coded path in text file share/filebeat/conda_build.sh
updating: filebeat-6.2.0-0.tar.bz2
```

### Steps to Reproduce

Try to build the recipe pasted above

##### `Output of conda info`

```
Current conda install:

               platform : linux-64
          conda version : 4.3.31
       conda is private : False
      conda-env version : 4.3.31
    conda-build version : 3.4.0
         python version : 3.6.4.final.0
       requests version : 2.18.4
       root environment : /opt/emsconda  (writable)
    default environment : /opt/emsconda
       envs directories : /opt/emsconda/envs
                          /root/.conda/envs
          package cache : /opt/emsconda/pkgs
                          /root/.conda/pkgs
           channel URLs : .../conda/stable/linux-64
                          .../conda/stable/noarch
            config file : /opt/emsconda/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.31 requests/2.18.4 CPython/3.6.4 Linux/4.11.8-300.fc26.x86_64 CentOS Linux/7.4.170
8 glibc/2.17
                UID:GID : 0:0
```

**Comment by msarahan** [comment]
Thanks for the report.  At first glance, pyldd is guessing the filetype wrong somehow, and expecting a null terminator where there isn't any (because it's a text file?)

We'll fix this ASAP, but we're in the middle of preparing the next Anaconda release, so it might be a little while.

**Comment by mingwandroid** [comment]
I took a quick look. The file is reasonable, just an elf. For some reason the DT_RPATH entry exceeds the string table size. I need to figure out how and why that's happened:

```
dt_rpath is 4319832
len(strsec.table is 4318337)
```

.. I've not seen this before having run many many binaries through pyldd.py by now.

**Comment by sscherfke** [comment]
There's always a first time :-)

Thx for the feedback!

**Comment by sscherfke** [comment]
Is there any news or a workaround for this issue?

**Comment by mingwandroid** [comment]
I need to add an option to skip this check I think.

**Comment by sscherfke** [comment]
A flag in the recipe would be nice, too.

**Comment by mingwandroid** [comment]
I decided to just warn when I detect these failures instead because I do not want to skip all these checks just because there's a single broken binary in a package.

**Comment by sscherfke** [comment]
This would also be okay for me.

**Comment by sscherfke** [comment]
This still seems to be an issue. The [pre-build binary of open policy agent](https://github.com/open-policy-agent/opa/releases/download/v0.15.1/opa_linux_amd64) lets pyllld crash.

The conda recipe just copies the file into `$PREFIX/bin/`:
```sh
chmod +x opa_linux_amd64
mkdir -p $PREFIX/bin
mv opa_linux_amd64 $PREFIX/bin/opa
```

**Comment by chrisburr** [comment]
Skipping of binaries has stopped working since conda-build 3.17. It seems to be a quirk of binaries built with `go`.

Traceback from https://github.com/conda-forge/singularity-feedstock/pull/20:

```python
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 469, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 460, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2344, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1643, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1002, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 867, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 1150, in post_build
    check_overlinking(m, files)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 1087, in check_overlinking
    m.config.enable_static)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 999, in check_overlinking_impl
    build_prefix, build_prefix_substitution)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 686, in _collect_needed_dsos
    envroot=run_prefix)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 948, in __call__
    value = self.func(*args, **kw)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 977, in get_linkages_memoized
    recurse=recurse, sysroot=sysroot, envroot=envroot, arch=arch)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 481, in get_linkages
    sysroot=sysroot, arch=arch)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/os_utils/pyldd.py", line 1145, in inspect_linkages
    filename, sysroot=sysroot, arch=arch)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/os_utils/pyldd.py", line 1089, in _inspect_linkages_this
    cf = codefile(ReadCheckWrapper(f), arch)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/os_utils/pyldd.py", line 1006, in codefile
    return elffile(file, list(initial_rpaths_transitive))
  File "/opt/conda/lib/python3.7/site-packages/conda_build/os_utils/pyldd.py", line 877, in __init__
    es.postprocess(self, file)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/os_utils/pyldd.py", line 806, in postprocess
    end = r + strsec.table[r:].index('\0')
ValueError: substring not found
```

**Comment by gusostow** [comment]
Are there any workarounds for this issue? I'm hitting pretty much exactly the same problem while trying to build filebeat also.

**Comment by chrisburr** [comment]
You can roll back to conda-build 3.16?
