### ISSUE TITLE
unexpected keywork argument 'link_dists'

### ISSUE THREAD

**Issue by zachcp** [conda/conda-build#2676]
### Actual Behavior

Crash during building of a conda recipe with the error related to a keyword argument 'link_dists' in the `render.py` file.  I have recently updated to conda 4.4  and according to [render.py](https://github.com/conda/conda-build/blob/master/conda_build/render.py#L257) there was a change between conda 4.3 and 4.4.  I think I have some conda 4.4 <--> conda-build incompatibility but the normal `update --all` hasn't solved the issue.

### Expected Behavior

Clean build of the package

### Steps to Reproduce

```
± |antismashsmiles → upstream/master {1} U:1 ?:1 ✗| → conda build .



Solving environment: done
Solving environment: done

## Package Plan ##

  environment location: /Users/zach/miniconda2/conda-bld/antismash_1518119429796/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p


The following NEW packages will be INSTALLED:

    ca-certificates: 2017.11.5-0      conda-forge
    certifi:         2017.11.5-py27_0 conda-forge
    ncurses:         5.9-10           conda-forge
    openssl:         1.0.2n-0         conda-forge
    pip:             9.0.1-py27_1     conda-forge
    python:          2.7.14-4         conda-forge
    readline:        7.0-0            conda-forge
    setuptools:      38.4.0-py27_0    conda-forge
    sqlite:          3.20.1-2         conda-forge
    tk:              8.6.7-0          conda-forge
    wheel:           0.30.0-py27_2    conda-forge
    zlib:            1.2.11-0         conda-forge

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Source cache directory is: /Users/zach/miniconda2/conda-bld/src_cache
Found source in cache: antismash-4.0.2.tar.gz
Extracting download
Applying patch: u'/Users/zach/Projects/Software/bioconda-recipes/recipes/antismash/smiles.patch'
Trying to apply patch as-is
INFO:conda_build.source:Trying to apply patch as-is
patching file antismash/output_modules/html/structure_drawer.py
Hunk #1 succeeded at 97 (offset 12 lines).
Hunk #2 succeeded at 106 (offset 12 lines).
source tree in: /Users/zach/miniconda2/conda-bld/antismash_1518119429796/work
Attempting to finalize metadata for antismash
INFO:conda_build.metadata:Attempting to finalize metadata for antismash
Solving environment: done
Traceback (most recent call last):
  File "/Users/zach/miniconda2/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/zach/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 340, in main
    execute(sys.argv[1:])
  File "/Users/zach/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 331, in execute
    noverify=args.no_verify)
  File "/Users/zach/miniconda2/lib/python2.7/site-packages/conda_build/api.py", line 183, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/Users/zach/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 1613, in build_tree
    built_packages=built_packages,
  File "/Users/zach/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 996, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/Users/zach/miniconda2/lib/python2.7/site-packages/conda_build/render.py", line 469, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/Users/zach/miniconda2/lib/python2.7/site-packages/conda_build/metadata.py", line 1613, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/zach/miniconda2/lib/python2.7/site-packages/conda_build/metadata.py", line 620, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/zach/miniconda2/lib/python2.7/site-packages/conda_build/render.py", line 264, in finalize_metadata
    extra_run_specs = get_upstream_pins(m, build_actions, 'build')
  File "/Users/zach/miniconda2/lib/python2.7/site-packages/conda_build/render.py", line 211, in get_upstream_pins
    index=index)
TypeError: __init__() got an unexpected keyword argument 'link_dists'
```

#####  Output of conda info

```
± |antismashsmiles → upstream/master {1} U:1 ?:1 ✗| → conda info

     active environment : None
            shell level : 0
       user config file : /Users/zach/.condarc
 populated config files : /Users/zach/miniconda2/.condarc
                          /Users/zach/.condarc
          conda version : 4.4.9
    conda-build version : 3.0.1
         python version : 2.7.14.final.0
       base environment : /Users/zach/miniconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-canary/osx-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/zach/miniconda2/pkgs
                          /Users/zach/.conda/pkgs
       envs directories : /Users/zach/miniconda2/envs
                          /Users/zach/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.9 requests/2.13.0 CPython/2.7.14 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
CC @kalefranz

**Comment by msarahan** [comment]
Yes, that appears to be a regression.  Thanks for the report.

**Comment by msarahan** [comment]
Ah, wait, that's a really old conda-build version.  You should try updating conda-build.  If you still have issues, please reopen this issue.

**Comment by zachcp** [comment]
hmmmm. it seems that conda-canary may have pinned the conda-build version.

note: i added the conda-canary channel on recommendation of the recent intro-to-conda-4.4 post. 

```
# installs 3.4.1
conda install -c anaconda conda-build 

conda update --all
The following packages will be DOWNGRADED:

    conda-build: 3.4.1-py36_0 anaconda --> 3.0.1-py36hb01f007_0   conda-canary
```

```
#.condarc
channels:
  - conda-canary
  - bioconda
  - conda-forge
  - defaults
```

**Comment by msarahan** [comment]
I don't recommend keeping conda-canary in your channels.  For now, I will remove conda-build from the conda-canary channel so that this is no longer a problem.  Thanks for pointing this out.

**Comment by zachcp** [comment]
duly noted; link to post as a reference: https://www.anaconda.com/blog/developer-blog/how-to-get-ready-for-the-release-of-conda-4-4/

**Comment by msarahan** [comment]
Yes, this was definitely my fault for bad hygiene.  We do need to be removing packages from conda-canary once they have been formally released.

**Comment by msarahan** [comment]
PS: my recommendation was more to use conda-canary as a temporary channel.

something like:

``conda install conda -c conda-canary``

(instead of adding it to .condarc)

You may also find the auto_update_conda setting for condarc helpful - it's a pain to have conda always wanting to change itself to be the highest version on any given channel.

**Comment by kalefranz** [comment]
> I don't recommend keeping conda-canary in your channels.

No! Please don't say that.  If we need to transition conda-build versions out of the `main` tag, let's do that.  Or use a different channel for canary releases of `conda-build`.

I upload *every* conda version to canary first.  People need to be using canary.

**Comment by kalefranz** [comment]
> my recommendation was more to use conda-canary as a temporary channel.

No Mike!  I've worked really hard to get people to start using canary.  I'll move the old conda-bulid versions out now.

**Comment by msarahan** [comment]
OK.  I'll keep conda-build off of it.  I already removed it some time ago.  People's channels are their choice, and I commend anyone who volunteers to help catch bugs in conda.

**Comment by zachcp** [comment]
I can see there is strong consensus on conda-canary ...... 😃 😄 😄

**Comment by mbargull** [comment]
@kalefranz, BTW, the `ruamel_yaml` on `conda-canary` is older than the one on `main` as of a few weeks 😉
