### ISSUE TITLE
Variants based on `r-base` is disallowed.

### ISSUE THREAD

**Issue by isuruf** [conda/conda-build#2688]
### Actual Behavior
```
Traceback (most recent call last):
  File "/home/isuru/miniconda3/bin/conda-smithy", line 11, in <module>
    load_entry_point('conda-smithy', 'console_scripts', 'conda-smithy')()
  File "/home/isuru/projects/conda-smithy/conda_smithy/cli.py", line 246, in main
    args.subcommand_func(args)
  File "/home/isuru/projects/conda-smithy/conda_smithy/cli.py", line 187, in __call__
    no_check_uptodate=args.no_check_uptodate, commit=args.commit)
  File "/home/isuru/projects/conda-smithy/conda_smithy/configure_feedstock.py", line 714, in main
    render_circle(env, config, forge_dir)
  File "/home/isuru/projects/conda-smithy/conda_smithy/configure_feedstock.py", line 452, in render_circle
    extra_platform_files=extra_platform_files)
  File "/home/isuru/projects/conda-smithy/conda_smithy/configure_feedstock.py", line 296, in _render_ci_provider
    channel_urls=forge_config.get('channels', {}).get('sources', []))
  File "/home/isuru/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 44, in render
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/isuru/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 658, in render_recipe
    variants = get_package_variants(m, variants=variants)
  File "/home/isuru/miniconda3/lib/python3.6/site-packages/conda_build/variants.py", line 485, in get_package_variants
    raise ValueError("Error in config {}: {}".format(f, str(e)))
ValueError: Error in config /home/isuru/miniconda3/conda_build_config.yaml: Variant configuration errors: 
['"-" is a disallowed character in variant keys.  Key was: r-base']
```
### Steps to Reproduce

Use a `conda_build_config.yaml` with
```
r-base:
  - 3.3.2
  - 3.4.1
```

##### `Output of conda info`

```
Current conda install:

               platform : linux-64
          conda version : 4.3.34
       conda is private : False
      conda-env version : 4.3.34
    conda-build version : 3.4.2
         python version : 3.6.4.final.0
       requests version : 2.14.2
       root environment : /home/isuru/miniconda3  (writable)
    default environment : /home/isuru/miniconda3
       envs directories : /home/isuru/miniconda3/envs
                          /home/isuru/.conda/envs
          package cache : /home/isuru/miniconda3/pkgs
                          /home/isuru/.conda/pkgs
           channel URLs : https://conda.anaconda.org/symengine/linux-64
                          https://conda.anaconda.org/symengine/noarch
                          https://conda.anaconda.org/inducer/linux-64
                          https://conda.anaconda.org/inducer/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/isuru/.condarc
             netrc file : /home/isuru/.netrc
           offline mode : False
             user-agent : conda/4.3.34 requests/2.14.2 CPython/3.6.4 Linux/4.13.0-32-generic debian/stretch/sid glibc/2.23 
```

**Comment by mingwandroid** [comment]
`-` is disallowed for obvious reasons, I use `r_base` then e.g. `  - r-base {{ r_base }}` for this.

**Comment by isuruf** [comment]
I didn't realize `r_base` was equivalent to `r-base`. Thanks

**Comment by mingwandroid** [comment]
It's not equivalent AFAIK. But you can use these values in jinja2 expressions which is what I do here.

**Comment by isuruf** [comment]
@msarahan told me that `r_base` was equivalent to `r-base` and just having `- r-base` was enough. I just confirmed that I get a matrix with just `- r-base` without the need of jinja2 expressions like above.

**Comment by msarahan** [comment]
https://github.com/conda/conda-build/blob/master/conda_build/utils.py#L1483

**Comment by mingwandroid** [comment]
Ah ok
