### ISSUE TITLE
CB deletes directory inside tarball with same name as package

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#2691]
Bob is back from vacation. As usual, Bob has been assigned the task to create a conda package for another team in his company. But being an unlucky fella, he stumbles upon yet another bug in Conda Build. His vacation mood vanishes in the first five minutes of work starting on a Wednesday.

The tarball of the other team has the following contents:
```
[bob@nutcasecompany testcase ]$ unzip -l mypkg.zip 
Archive:  mypkg.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2018-02-21 16:57   mypkg/
       74  2018-02-21 16:56   mypkg/libmypkg.c
        0  2018-02-21 16:53   mypkg/mypkg/
       22  2018-02-21 16:53   mypkg/mypkg/awesomeheader.h
---------                     -------
       96                     4 files
```

Bob has reduced the build script to the following example:
```
[bob@nutcasecompany testcase ]$ cat build.sh 
find $SRC_DIR -type f
if [[ ! -f "$SRC_DIR/mypkg/awesomeheader.h" ]]; then
    exit 1
fi
exit 0

[bob@nutcasecompany testcase ]$ cat meta.yaml 
package:
  name: mypkg
  version: 1.0.0

source:
  url: file:///tmp/testcase/mypkg.zip
```

Bob has attached the package [mypkg.zip](https://github.com/conda/conda-build/files/1743886/mypkg.zip) in the testcase.

Conda Build fails with:
```
[bob@nutcasecompany testcase ]$ conda build .
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for mypkg
INFO:conda_build.metadata:Attempting to finalize metadata for mypkg
BUILD START: [u'mypkg-1.0.0-0.tar.bz2']
Source cache directory is: /opt/conda/conda/root/conda-bld/src_cache
No hash (md5, sha1, sha256) provided.  Source download forced.  Add hash to recipe to use source cache.
WARNING:conda_build.source:No hash (md5, sha1, sha256) provided.  Source download forced.  Add hash to recipe to use source cache.
Downloading source to cache: mypkg.zip
Downloading file:///tmp/testcase/mypkg.zip
Success
Extracting download
source tree in: /opt/conda/conda/root/conda-bld/mypkg_1519214647277/work
/opt/conda/conda/root/conda-bld/mypkg_1519214647277/work/libmypkg.c
/opt/conda/conda/root/conda-bld/mypkg_1519214647277/work/conda_build.sh
Traceback (most recent call last):
  File "/opt/conda/conda/root/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/conda/root/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 413, in main
    execute(sys.argv[1:])
  File "/opt/conda/conda/root/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 404, in execute
    verify=args.verify)
  File "/opt/conda/conda/root/lib/python2.7/site-packages/conda_build/api.py", line 193, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/opt/conda/conda/root/lib/python2.7/site-packages/conda_build/build.py", line 1944, in build_tree
    notest=notest,
  File "/opt/conda/conda/root/lib/python2.7/site-packages/conda_build/build.py", line 1240, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/opt/conda/conda/root/lib/python2.7/site-packages/conda_build/utils.py", line 678, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/opt/conda/conda/root/lib/python2.7/site-packages/conda_build/utils.py", line 674, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/opt/conda/conda/root/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/opt/conda/conda/root/conda-bld/mypkg_1519214647277/work/conda_build.sh']' returned non-zero exit status 1
```

Somehow, CB eats up the file `awesomeheader.h`. Bob blames it on the function:
 [hoist_single_extracted_folder](https://github.com/conda/conda-build/blob/3.5.0/conda_build/source.py#L115)

**Comment by msarahan** [comment]
Thanks for the test, @nehaljwani.  I'll incorporate this into the test suite.  This function has been a problem before - sorry we didn't have a better test already.

**Comment by msarahan** [comment]
Previous test was at https://github.com/conda/conda-build/blob/master/tests/test_source.py#L106

It's not covering the situation where there's other files at the top level of the folder.  I'll add that to the test.

**Comment by msarahan** [comment]
```
def test_hoist_same_name_with_toplevel_files(testing_workdir):
    testdir = os.path.join(testing_workdir, 'test', 'test')
    outer_dir = os.path.join(testing_workdir, 'test')
    os.makedirs(testdir)
    with open(os.path.join(testdir, 'somefile'), 'w') as f:
        f.write('weeeee')
    with open(os.path.join(outer_dir, 'some_other_file'), 'w') as f:
        f.write('weeeee')
    source.hoist_single_extracted_folder(testdir)
    assert os.path.isfile(os.path.join(testdir, 'somefile'))
    assert os.path.isfile(os.path.join(outer_dir, 'some_other_file'))
    assert os.path.isdir(testdir)
```
