### ISSUE TITLE
empty preprocessed conda_build_config.yaml gives error

### ISSUE THREAD

**Issue by isuruf** [conda/conda-build#2728]
### Actual Behavior

```
Traceback (most recent call last):
  File "/home/isuru/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/isuru/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 415, in main
    execute(sys.argv[1:])
  File "/home/isuru/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 406, in execute
    verify=args.verify)
  File "/home/isuru/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 199, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/isuru/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2004, in build_tree
    bypass_env_check=True)
  File "/home/isuru/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 658, in render_recipe
    variants = get_package_variants(m, variants=variants)
  File "/home/isuru/miniconda3/lib/python3.6/site-packages/conda_build/variants.py", line 473, in get_package_variants
    specs[f] = parse_config_file(f, config)
  File "/home/isuru/miniconda3/lib/python3.6/site-packages/conda_build/variants.py", line 116, in parse_config_file
    trim_empty_keys(content)
  File "/home/isuru/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 1110, in trim_empty_keys
    for k, v in dict_.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

### Expected Behavior
no error

### Steps to Reproduce
```yaml
asd: # [osx]
  - 1  # [osx]
```
Use above file as a variant config file

##### `Output of conda info`

```
               platform : linux-64
          conda version : 4.3.34
       conda is private : False
      conda-env version : 4.3.34
    conda-build version : 3.5.1
         python version : 3.6.4.final.0
       requests version : 2.14.2
```

**Comment by isuruf** [comment]
Thanks @msarahan
