### ISSUE TITLE
conda-build fails on symbolic links inside tarballs

### ISSUE THREAD

**Issue by leonid-butenko** [conda/conda-build#2755]
### Actual Behavior
for example in the following tar ball:
https://software.ecmwf.int/wiki/download/attachments/45757960/eccodes-2.7.0-Source.tar.gz

there is a symbolic link:
lrwxrwxrwx  1 7 Dez  6 15:12 COPYING -> LICENSE

```
Found source in cache: eccodes-2.7.0-Source_118f46cf6f.tar.gz
Extracting download
Traceback (most recent call last):
  File "/space/linux-64/conda/3.2/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/space/linux-64/conda/3.2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/space/linux-64/conda/3.2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/space/linux-64/conda/3.2/lib/python2.7/site-packages/conda_build/api.py", line 199, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/space/linux-64/conda/3.2/lib/python2.7/site-packages/conda_build/build.py", line 2097, in build_tree
    notest=notest,
  File "/space/linux-64/conda/3.2/lib/python2.7/site-packages/conda_build/build.py", line 1303, in build
    try_download(m, no_download_source=False, raise_error=True)
  File "/space/linux-64/conda/3.2/lib/python2.7/site-packages/conda_build/render.py", line 470, in try_download
    source.provide(metadata)
  File "/space/linux-64/conda/3.2/lib/python2.7/site-packages/conda_build/source.py", line 623, in provide
    timeout=metadata.config.timeout, locking=metadata.config.locking)
  File "/space/linux-64/conda/3.2/lib/python2.7/site-packages/conda_build/source.py", line 159, in unpack
    hoist_single_extracted_folder(folder)
  File "/space/linux-64/conda/3.2/lib/python2.7/site-packages/conda_build/source.py", line 124, in hoist_single_extracted_folder
    shutil.move(os.path.join(nested_folder, entry), os.path.join(tmpdir, entry))
  File "/space/linux-64/conda/3.2/lib/python2.7/shutil.py", line 316, in move
    copy2(src, real_dst)
  File "/space/linux-64/conda/3.2/lib/python2.7/shutil.py", line 144, in copy2
    copyfile(src, dst)
  File "/space/linux-64/conda/3.2/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/space/linux-64/conda/3.2/conda-bld/tmp4_TrSF/eccodes-2.7.0-Source/COPYING'
```

### Expected Behavior

should not crash

### Steps to Reproduce

here is my meta.yaml

```
package:
  name:    ecmwf-eccodes-python
  version: 2.7.0

source:
   url: https://software.ecmwf.int/wiki/download/attachments/45757960/eccodes-2.7.0-Source.tar.gz
   sha256: 118f46cf6f800585580a5bc838128537ab0879073e9fcded49cd374e4c8d8e6a

build:
  number: 0
  skip: True  # [win or py3k]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - python {{ python }}
    - numpy {{ numpy }}
    - boost {{ boost }}
    - jasper
    - libpng >=1.6.32,<1.6.35
    - libnetcdf {{ libnetcdf }}
    - hdf5 {{ hdf5 }}
    - perl-threaded {{ perl_threaded }}
    - ecmwf-eccodes 2.7.0
  run:
    - python
    - numpy >=1.14
    - jasper
    - libpng >=1.6.32,<1.6.35
    - libnetcdf {{ libnetcdf }}.*
    - hdf5 {{ hdf5 }}.*
    - eccodes 2.7.0
```

##### `Output of conda info`

```
>conda info

     active environment : None
            shell level : 0
       user config file : /space/home/.condarc
 populated config files : /space/linux-64/conda/3.2/.condarc
          conda version : 4.4.11
    conda-build version : 3.7.1
         python version : 2.7.14.final.0
       base environment : /space/linux-64/conda/3.2  (writable)
           channel URLs : https://conda.anaconda.org/eumetsat/linux-64
                          https://conda.anaconda.org/eumetsat/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda/linux-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /space/linux-64/conda/3.2/pkgs
                          /space/home/.conda/pkgs
       envs directories : /space/linux-64/conda/3.2/envs
                          /space/home/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/2.7.14 Linux/4.4.0-116-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:207
             netrc file : None
           offline mode : False

```

**Comment by msarahan** [comment]
Thanks for reporting.  I didn't realize shutil.move was broken for symlinks.  We'll try to find a different way.  PRs welcome, but we'll try to get to this soon, too.

**Comment by msarahan** [comment]
And of course, it doesn't crash for me.

```
Found source in cache: eccodes-2.7.0-Source_118f46cf6f.tar.gz
Extracting download
source tree in: /opt/conda/conda-bld/ecmwf-eccodes-python_1521080859503/work
```

I've tried this on OSX and linux (docker container), with python 2.7 and 3.6.  No crashes.  Do you have any other more complicated filesystem issues at play here?

**Comment by msarahan** [comment]
Found this: https://bugs.python.org/issue9993

Should be fixed in current py3.x versions, but they don't explicitly mention py2.x as having the fix.  I suspect this may be related to going across filesystems, which may be why I can't reproduce it.

**Comment by leonid-butenko** [comment]
> I've tried this on OSX and linux (docker container), with python 2.7 and 3.6. No crashes. Do you have any other more complicated filesystem issues at play here?
No, I'm doing this on vanilla ubuntu 16.04 with installed build-essential and python 2.7.13 as system ones. Filesystem /space is a standard ext4 system mount. The whole thing is running in VirtualBox under windows.

**Comment by msarahan** [comment]
Thanks.  Maybe try with miniconda3 as your root installation.  You can
still build python 2 software with miniconda 3.  Failing that, I'll take
another look next week.
