### ISSUE TITLE
FEATURE_NOMKL=1 conda build . broken

### ISSUE THREAD

**Issue by tvandera** [conda/conda-build#2769]
### Actual Behavior

When I try to build a package with `FEATURE_NOMKL=1` (any package), I get an error.

### Steps to Reproduce

```
wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
sh Miniconda3-latest-MacOSX-x86_64.sh -b
export PATH=$HOME/miniconda3/bin:$PATH
conda install conda-build
cd tmp
git clone git@github.com:ContinuumIO/anaconda-recipes.git
cd anaconda-recipes/numpy-1.13
FEATURE_NOMKL=1 conda build .
```
### Output of conda build command:
```
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for numpy
INFO:conda_build.metadata:Attempting to finalize metadata for numpy
Solving environment: ...working... failed
Traceback (most recent call last):
  File "/Users/vanderaa/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 199, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2097, in build_tree
    notest=notest,
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1160, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 583, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 1863, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 680, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 379, in finalize_metadata
    exclude_pattern)
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 293, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 281, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 117, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 706, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda/common/io.py", line 46, in decorated
    return f(*args, **kwds)
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 542, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 504, in solve_for_transaction
    force_remove, force_reinstall)
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 437, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 317, in solve_final_state
    conflicting_specs = r.get_conflicting_specs(tuple(final_environment_specs))
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 703, in get_conflicting_specs
    reduced_index = self.get_reduced_index(specs)
  File "/Users/vanderaa/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 333, in get_reduced_index
    reduced_index[dist] = self.index[dist]
KeyError: Dist(channel='@', dist_name='nomkl@', name='nomkl@', version='', build_string='', build_number=0, base_url=None, platform=None)
```
### Expected Behavior

`conda build` should work.

##### Output of conda info

```
     active environment : None
       user config file : /Users/vanderaa/.condarc
 populated config files : /Users/vanderaa/.condarc
          conda version : 4.4.11
    conda-build version : 3.7.1
         python version : 3.6.4.final.0
       base environment : /Users/vanderaa/miniconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/vanderaa/miniconda3/pkgs
                          /Users/vanderaa/.conda/pkgs
       envs directories : /Users/vanderaa/miniconda3/envs
                          /Users/vanderaa/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/3.6.4 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
Thanks for reporting this.  This is coming in because of the old hacks to handle "features."  We're moving away from those, and using metapackages and conda-build 3 variants instead.  See our numpy recipe at https://github.com/AnacondaRecipes/numpy-feedstock/blob/master/recipe/meta.yaml#L28

Our variants are defined in https://github.com/AnacondaRecipes/aggregate/blob/master/conda_build_config.yaml

We'll try to fix the old features behavior here, but I'm not sure yet how ugly it might be.  It might be a casualty of the conda-build 3 transition, and if you need to depend on that, you may need to use the 2.1.x release series until you can update your recipe.

**Comment by msarahan** [comment]
fix in https://github.com/conda/conda-build/issues/2769

Note, though, that you were trying to use the new recipe with the old feature stuff.  The old feature stuff is totally gone in that recipe.  Look at the selectors.  There's no nomkl anywhere in them, but it's what used to be the main way that that feature was used.  So, with #2769 you will no longer error out, but FEATURE_NOMKL probably won't have the effect that you're hoping for.  Instead, you need to read up on variants and use those instead, or stick to older recipes.

**Comment by tvandera** [comment]
Clear. I'll adapt my recipes.
