### ISSUE TITLE
Unable to copy the build file for a conda package

### ISSUE THREAD

**Issue by mayankbro** [conda/conda-build#2778]
### Actual Behavior

Actually it should copy the build file
### Steps to Reproduce

I am using conda-build <filename> command and it gives me this.
##### `Output of conda info`

```Copying /home/mayank to /home/mayank/anaconda/conda-bld/ajcse_1521808674261/work
Traceback (most recent call last):
  File "/home/mayank/anaconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 239, in main
    execute(sys.argv[1:])
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 231, in execute
    already_built=None, config=config)
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 83, in build
    need_source_download=need_source_download, config=config)
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 998, in build_tree
    config=recipe_config)
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 590, in build
    config=config)
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda_build/render.py", line 86, in parse_or_try_download
    source.provide(metadata.path, metadata.get_section('source'), config=config)
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda_build/source.py", line 511, in provide
    copy_into(abspath(join(recipe_dir, meta.get('path'))), config.work_dir, config.timeout)
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 101, in copy_into
    merge_tree(src, dst, symlinks)
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 128, in merge_tree
    new_files = copy_tree(src, dst, preserve_symlinks=symlinks, dry_run=True)
  File "/home/mayank/anaconda/lib/python2.7/distutils/dir_util.py", line 163, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/home/mayank/anaconda/lib/python2.7/distutils/dir_util.py", line 163, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/home/mayank/anaconda/lib/python2.7/distutils/dir_util.py", line 167, in copy_tree
    dry_run=dry_run)
  File "/home/mayank/anaconda/lib/python2.7/distutils/file_util.py", line 110, in copy_file
    "can't copy '%s': doesn't exist or not a regular file" % src)
distutils.errors.DistutilsFileError: can't copy '/home/mayank/.config/google-chrome/SingletonLock': doesn't exist or not a regular file

```

**Comment by msarahan** [comment]
Please post your recipe and the rest of the information requested by the issue template.

**Comment by mayankbro** [comment]
Conda.recipe
bld.bat
`PYTHON setup.py install --single-version-externally-managed --record=record.txt
if errorlevel 1 exit 1

del %SCRIPTS%\conda-init
if errorlevel 1 exit 1

copy bdist_conda.py %PREFIX%\Lib\distutils\command\
if errorlevel 1 exit 1`
Build.sh
`#!/bin/bash


$PYTHON setup.py install --single-version-externally-managed --record=record.txt


cp bdist_conda.py ${PREFIX}/lib/python${PY_VER}/distutils/command

`
