### ISSUE TITLE
numpy-1.14.2 build error

### ISSUE THREAD

**Issue by nick-youngblut** [conda/conda-build#2795]
I'm trying to create a conda package for `nanopack`. I'm runing `conda skeleton pypi nanopack --recursive` and getting the following error:

```
# many lines of output...
Applying patch: '/tmp/tmpw692xrc4conda_skeleton_numpy-1.14.2.zip/pypi-distutils.patch'
patching file core.py
Hunk #1 succeeded at 167 with fuzz 2 (offset 1 line).
Running from numpy source directory.

Note: if you need reliable uninstall behavior, then install
with pip instead of using `setup.py install`:

  - `pip install .`       (from a git repo or downloaded source
                           release)
  - `pip install numpy`   (last NumPy release on PyPi)


Traceback (most recent call last):
  File "setup.py", line 394, in <module>
    setup_package()
  File "setup.py", line 386, in setup_package
    setup(**metadata)
  File "/tmp/tmpw692xrc4conda_skeleton_numpy-1.14.2.zip/numpy-1.14.2/numpy/distutils/core.py", line 130, in setup
    if dist.help or not _command_line_ok():
AttributeError: 'NoneType' object has no attribute 'help'
$PYTHONPATH = /tmp/tmpw692xrc4conda_skeleton_numpy-1.14.2.zip/numpy-1.14.2

Leaving build/test directories:
  Work:	 /ebio/abt3_projects/software/dev/miniconda3_dev/conda-bld/skeleton_1522480590389/work
  Test:	 /ebio/abt3_projects/software/dev/miniconda3_dev/conda-bld/skeleton_1522480590389/test_tmp
Leaving build/test environments:
  Test:	source activate  /ebio/abt3_projects/software/dev/miniconda3_dev/conda-bld/skeleton_1522480590389/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
  Build:	source activate  /ebio/abt3_projects/software/dev/miniconda3_dev/conda-bld/skeleton_1522480590389/_build_env


Error: command failed: /ebio/abt3_projects/software/dev/miniconda3_dev/conda-bld/skeleton_1522480590389/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python setup.py install
```

Is there anything that I can do about the `AttributeError: 'NoneType' object has no attribute 'help'`?

```
$ conda info

     active environment : R_pkg_build
    active env location : /ebio/abt3_projects/software/dev/miniconda3_dev/envs/R_pkg_build
            shell level : 1
       user config file : /ebio/abt3/nyoungblut/.condarc
 populated config files : /ebio/abt3_projects/software/dev/miniconda3_dev/.condarc
                          /ebio/abt3/nyoungblut/.condarc
          conda version : 4.5.0
    conda-build version : 3.7.2
         python version : 3.6.4.final.0
       base environment : /ebio/abt3_projects/software/dev/miniconda3_dev  (writable)
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/qiime2/linux-64
                          https://conda.anaconda.org/qiime2/noarch
          package cache : /ebio/abt3_projects/software/dev/miniconda3_dev/pkgs
                          /ebio/abt3/nyoungblut/.conda/pkgs
       envs directories : /ebio/abt3_projects/software/dev/miniconda3_dev/envs
                          /ebio/abt3/nyoungblut/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.4 Linux/4.4.67 ubuntu/16.04 glibc/2.23
                UID:GID : 6354:350
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
--recursive is finding that it needs to build numpy somehow.  You should really never build numpy.  It looks like nanomath is the one responsible:

```
Preparing transaction: ...working... done
Executing transaction: ...working... done
Applying patch: '/var/folders/94/cb44zrcj06n_vj5zgxvjpb0h0000gp/T/tmp4xyhtdw2conda_skeleton_nanomath-0.21.0.tar.gz/pypi-distutils.patch'
patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 1 line).
Warning, the following versions were found for numpy
```

I don't understand why it's recursing into building numpy, and that's a bug, but unfortunately not a very high priority one.  I advise you to ctrl-c it to prevent it from trying to build numpy, and take the recipes you have already obtained.  If you need others, re-attempt the recursive build down below nanomath in the chain.

**Comment by rodgomesc** [comment]
same error for me in numpy-1.14.3

**Comment by msarahan** [comment]
@rodgomesc if you are trying to build numpy itself, you need a different recipe.  You absolutely will not succeed with the skeleton generator for numpy.  It is a much more complicated beast.

**Comment by rodgomesc** [comment]
complicated hmm. so iam trying build it for android

here is my build.sh


```
export HOSTPYTHON=$PYTHON
export ARCHS=("x86_64 x86 arm arm64")
export NDK="$HOME/Android/Sdk/ndk-bundle"

if [ "$PY3K" == "1" ]; then
    export PY_LIB_VER="3.6m"
else
    export PY_LIB_VER="2.7"
fi

patch -t -d $SRC_DIR -p1 -i $RECIPE_DIR/numpy.patch

for ARCH in $ARCHS
do

    if [ "$ARCH" == "arm" ]; then
        export TARGET_HOST="arm-linux-androideabi"
        export TARGET_ABI="armeabi-v7a"
    elif [ "$ARCH" == "arm64" ]; then
        export TARGET_HOST="aarch64-linux-android"
        export TARGET_ABI="arm64-v8a"
    elif [ "$ARCH" == "x86" ]; then
        export TARGET_HOST="i686-linux-android"
        export TARGET_ABI="x86"
    elif [ "$ARCH" == "x86_64" ]; then
        export TARGET_HOST="x86_64-linux-android"
        export TARGET_ABI="x86_64"
    fi

    export ANDROID_TOOLCHAIN="$NDK/standalone/$ARCH"
    export APP_ROOT="$PREFIX/android/$ARCH"
    export PATH="$PATH:$ANDROID_TOOLCHAIN/bin"
    export AR="$TARGET_HOST-ar"
    export CC="$TARGET_HOST-gcc -D__ANDROID_API__=21"
    export CXX="$TARGET_HOST-g++"
    export LD="$TARGET_HOST-ld"
    export STRIP="$TARGET_HOST-strip"
    export CFLAGS="-I$APP_ROOT/include/python$PY_LIB_VER"
    export LDFLAGS="-L$APP_ROOT/lib"
    export LDSHARED="$CC -shared"
    export CROSS_COMPILE="$ARCH"
    export CROSS_COMPILE_TARGET='yes'
    export _PYTHON_HOST_PLATFORM="android-$ARCH"

    # Build
    python setup.py build -j$CPU_COUNT

    # Rename and move all so files to lib
    cd build/lib.android-$ARCH-$PY_VER/
        find * -type f -name "*.so" -exec rename 's!/!.!g' {} \;
        rename 's/^/lib./' *.so; rename 's/\.cpython-.+\.so/\.so/' *.so;
    cd $SRC_DIR

    # Copy to install
    mkdir -p $PREFIX/android/$ARCH/python/site-packages/
    cp -RL build/lib.android-$ARCH-$PY_VER/numpy $PREFIX/android/$ARCH/python/site-packages/
    cp -RL build/lib.android-$ARCH-$PY_VER/*.so $PREFIX/android/$ARCH/lib

    # Clean

done
```
