### ISSUE TITLE
Swig: did not find libc.so.6, libm.so.6, libgcc_s.so.1, etc.

### ISSUE THREAD

**Issue by romainmartinez** [conda/conda-build#2803]
Hello,

I try to build a python package with conda-build, swig and cmake but get some errors.
- source code: [link](https://github.com/pyomeca/BTKCore)
- `meta.yaml`: [link](https://github.com/romainmartinez/cookbook/blob/master/python/recipes/btk/meta.yaml)
- `build.sh`: [link](https://github.com/romainmartinez/cookbook/blob/master/python/recipes/btk/build.sh)

### Actual Behavior
- Building CXX objects and target with cmake seems OK (no errors)
- Some warnings and info are displayed during packaging:
```
Packaging btk
INFO:conda_build.build:Packaging btk
Packaging btk-0.3-py36_0
INFO:conda_build.build:Packaging btk-0.3-py36_0
number of files: 398
Making absolute symlink lib/btk-0.4dev/libBTKBasicFilters.so -> libBTKBasicFilters.so.0.4dev relative
Making absolute symlink lib/btk-0.4dev/libBTKCommon.so -> libBTKCommon.so.0.4dev relative
Making absolute symlink lib/btk-0.4dev/libBTKIO.so -> libBTKIO.so.0.4dev relative
Making absolute symlink lib/btk-0.4dev/libBTKBasicFilters.so.0.4dev -> libBTKBasicFilters.so.0.4dev.0 relative
Making absolute symlink lib/btk-0.4dev/libBTKIO.so.0.4dev -> libBTKIO.so.0.4dev.0 relative
Making absolute symlink lib/btk-0.4dev/libBTKCommon.so.0.4dev -> libBTKCommon.so.0.4dev.0 relative
patchelf: file: /home/romain/miniconda3/conda-bld/btk_1522792670182/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/btk-0.4dev/libBTKIO.so.0.4dev.0
    setting rpath to: $ORIGIN/.:$ORIGIN/..
patchelf: file: /home/romain/miniconda3/conda-bld/btk_1522792670182/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/btk-0.4dev/libBTKCommon.so.0.4dev.0
    setting rpath to: $ORIGIN/.:$ORIGIN/..
patchelf: file: /home/romain/miniconda3/conda-bld/btk_1522792670182/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/btk-0.4dev/libBTKBasicFilters.so.0.4dev.0
    setting rpath to: $ORIGIN/.:$ORIGIN/..
WARNING (btk,lib/btk-0.4dev/libBTKIO.so.0.4dev.0): did not find - or even know where to look for: libc.so.6
WARNING (btk,lib/btk-0.4dev/libBTKIO.so.0.4dev.0): did not find - or even know where to look for: libm.so.6
   INFO (btk,lib/btk-0.4dev/libBTKIO.so.0.4dev.0): lib/btk-0.4dev/libBTKCommon.so.0.4dev found in this package
WARNING (btk,lib/btk-0.4dev/libBTKIO.so.0.4dev.0): did not find - or even know where to look for: libgcc_s.so.1
WARNING (btk,lib/btk-0.4dev/libBTKIO.so.0.4dev.0): did not find - or even know where to look for: libstdc++.so.6
WARNING (btk,lib/btk-0.4dev/libBTKCommon.so.0.4dev.0): did not find - or even know where to look for: libgcc_s.so.1
WARNING (btk,lib/btk-0.4dev/libBTKCommon.so.0.4dev.0): did not find - or even know where to look for: libc.so.6
WARNING (btk,lib/btk-0.4dev/libBTKCommon.so.0.4dev.0): did not find - or even know where to look for: libm.so.6
WARNING (btk,lib/btk-0.4dev/libBTKCommon.so.0.4dev.0): did not find - or even know where to look for: libstdc++.so.6
WARNING (btk,lib/btk-0.4dev/libBTKBasicFilters.so.0.4dev.0): did not find - or even know where to look for: libc.so.6
WARNING (btk,lib/btk-0.4dev/libBTKBasicFilters.so.0.4dev.0): did not find - or even know where to look for: libm.so.6
   INFO (btk,lib/btk-0.4dev/libBTKBasicFilters.so.0.4dev.0): lib/btk-0.4dev/libBTKCommon.so.0.4dev found in this package
WARNING (btk,lib/btk-0.4dev/libBTKBasicFilters.so.0.4dev.0): did not find - or even know where to look for: libgcc_s.so.1
WARNING (btk,lib/btk-0.4dev/libBTKBasicFilters.so.0.4dev.0): did not find - or even know where to look for: libstdc++.so.6
Fixing permissions
Detected hard-coded path in text file share/btk-0.4dev/BTKLibraryDepends.cmake
updating: btk-0.3-py36_0.tar.bz2
```

### Expected Behavior
- Swig did not generate any python files. Am I wrong with my recipes?

### Steps to Reproduce
- Download [meta.yaml](https://github.com/romainmartinez/cookbook/blob/master/python/recipes/btk/meta.yaml) and [build.sh](https://github.com/romainmartinez/cookbook/blob/master/python/recipes/btk/build.sh) into a folder
- `conda build folder`

##### `Output of conda info`
```
Current conda install:

               platform : linux-64
          conda version : 4.3.34
       conda is private : False
      conda-env version : 4.3.34
    conda-build version : 3.8.0
         python version : 3.6.4.final.0
       requests version : 2.18.4
       root environment : /home/romain/miniconda3  (writable)
    default environment : /home/romain/miniconda3
       envs directories : /home/romain/miniconda3/envs
                          /home/romain/.conda/envs
          package cache : /home/romain/miniconda3/pkgs
                          /home/romain/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/romain/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.34 requests/2.18.4 CPython/3.6.4 Linux/4.13.0-37-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000
```

**Comment by mingwandroid** [comment]
You should use our compilers to get rid of the warnings about libc and libm not being found (otherwise it will be linking to your system ones and that is less portable).

To use them:

```
build:
  - {{ compiler('cxx') }}
```

swig and cmake both have bugs in how they find Python (they ignore sysconfig's `LDSHARED` value and assume you need to link to libpython), it looks like you are trying to work around some of these failures in cmake and swig by passing values explicitly to cmake but your fix is problematic; you are [linking to libpython DSOs](https://github.com/romainmartinez/cookbook/blob/master/python/recipes/btk/build.sh#L7-L11) which you should not do since our Python interpreter is statically linked.

I helped someone else out with some very similar problems earlier today. Please see https://github.com/ContinuumIO/anaconda-issues/issues/9078#issuecomment-378278392

**Comment by romainmartinez** [comment]
Thank you,

1. I used `{{ compiler('cxx') }}` but get the following error:

```
source tree in: /home/romain/miniconda3/conda-bld/btk_1522853493826/work
INFO: activate-gxx_linux-64.sh made the following environmental changes:
+CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/romain/miniconda3/conda-bld/btk_1522853493826/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix
+CXX=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++
+DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe -I/home/romain/miniconda3/conda-bld/btk_1522853493826/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix
+GXX=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-g++
+HOST=x86_64-conda_cos6-linux-gnu
INFO: activate-binutils_linux-64.sh made the following environmental changes:
+ADDR2LINE=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-addr2line
+AR=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-ar
+AS=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-as
+CXXFILT=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++filt
+ELFEDIT=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-elfedit
+GPROF=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-gprof
+LD_GOLD=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-ld.gold
+LD=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-ld
+NM=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-nm
+OBJCOPY=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-objcopy
+OBJDUMP=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-objdump
+RANLIB=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-ranlib
+READELF=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-readelf
+SIZE=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-size
+STRINGS=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-strings
+STRIP=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-strip
INFO: activate-gcc_linux-64.sh made the following environmental changes:
+CC=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc
+CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/romain/miniconda3/conda-bld/btk_1522853493826/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix
+_CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
+CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2
+CPP=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-cpp
+DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe -I/home/romain/miniconda3/conda-bld/btk_1522853493826/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix
+DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og
+GCC_AR=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-gcc-ar
+GCC=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-gcc
+GCC_NM=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-gcc-nm
+GCC_RANLIB=/home/romain/miniconda3/conda-bld/btk_1522853493826/_build_env/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib
+LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/romain/miniconda3/conda-bld/btk_1522853493826/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -L/home/romain/miniconda3/conda-bld/btk_1522853493826/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib
/home/romain/miniconda3/conda-bld/btk_1522853493826/work/conda_build.sh: line 62: -c: command not found
Traceback (most recent call last):
  File "/home/romain/miniconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/romain/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/home/romain/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/home/romain/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 199, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/romain/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2105, in build_tree
    notest=notest,
  File "/home/romain/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1377, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/home/romain/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 301, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/romain/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 280, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/romain/miniconda3/conda-bld/btk_1522853493826/work/conda_build.sh']' returned non-zero exit status 127.
```

2. I looked to the issue [#9078](https://github.com/ContinuumIO/anaconda-issues/issues/9078#issuecomment-378278392) and I have a hard time seeing what I need to change in the cmake at the [root](https://github.com/pyomeca/BTKCore/blob/master/CMakeLists.txt) and the cmake in the [python wrapping](https://github.com/pyomeca/BTKCore/blob/master/Wrapping/Python/CMakeLists.txt).
Sorry, I have very little experience in cmake.
If I understand correctly, the changes you made allow you to get `PYTHON_EXECUTABLE` and` PYTHON_LIBRARIES` in the cmake.

Is there a way to do that in the `build.sh` file?

**Comment by mingwandroid** [comment]
Please read https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html carefully.

`$PYTHON` is not set because you don't have a `host:` section containing `python`.

**Comment by romainmartinez** [comment]
I change the following files:

1. `meta.yml`
```yml
package:
  name: btk
  version: "0.3"

source:
  git_url: https://github.com/pyomeca/BTKCore.git

build:
  number: 0
  detect_binary_files_with_prefix: True

requirements:
  host:
    - python
    - numpy
    - setuptools
    - swig
  build:
    - {{ compiler('cxx') }}
  run:
    - python
    - numpy

about:
  home: https://github.com/pyomeca/BTKCore
  summary: Read, modify, process, and write acquisition data recorded by a motion capture system

extra:
    recipe-maintainers:
        - mrtnz
```

2. `build.sh`
```bash
#!/bin/bash
mkdir build
cd build

cmake ../ \
      -DCMAKE_INSTALL_PREFIX=$PREFIX \
      -DBUILD_SHARED_LIBS=ON \
      -DBTK_WRAP_PYTHON=ON \
      -DPYTHON_EXECUTABLE=$PYTHON \

make -j $CPU_COUNT
make install
```

And still get the same errors (swig did not generate the python files and same error as my previous post with `{{ compiler('cxx') }}`).

However, cmake seems to find the right paths:

```
-- Found SWIG: /home/romain/miniconda3/conda-bld/btk_1523203131139/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/swig (found suitable version "3.0.12", minimum required is "2.0") 
-- Found PythonLibs: /home/romain/miniconda3/conda-bld/btk_1523203131139/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libpython3.so (found version "3.6.5") 
-- Found NumPy: /home/romain/miniconda3/conda-bld/btk_1523203131139/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages/numpy/core/include (found version "1.11.3") 
-- NumPy ver. 1.11.3 found (include: /home/romain/miniconda3/conda-bld/btk_1523203131139/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages/numpy/core/include)
```

**Comment by mingwandroid** [comment]
Swig is a build tool, not a host tool. Not sure that'll fix this but it's probably in the wrong section here.

**Comment by mingwandroid** [comment]
Also you are not using our CMake. We modify our build tools to fix various bugs in them and you should always use our versions. This also gains you reproducibility and atomicity.

**Comment by romainmartinez** [comment]
Still get the errors by moving swig and cmake to the build sections.

```yml
package:
  name: btk
  version: "0.3"

source:
  git_url: https://github.com/pyomeca/BTKCore.git

build:
  number: 0
  detect_binary_files_with_prefix: True

requirements:
  host:
    - python
    - numpy
    - setuptools
    - cmake

  build:
    - {{ compiler('cxx') }}
    - swig
    - cmake
  run:
    - python
    - numpy

about:
  home: https://github.com/pyomeca/BTKCore
  summary: Read, modify, process, and write acquisition data recorded by a motion capture system

extra:
    recipe-maintainers:
        - mrtnz

```

**Comment by mingwandroid** [comment]
Did you read https://github.com/ContinuumIO/anaconda-issues/issues/9078#issuecomment-378278392

As I said, both Swig and CMake mishandle Python (in a way that they only work correctly with very 'vanilla' builds of Python). I expect you are running into these issues but I'll see what more I can determine from trying to reproduce this.

**Comment by romainmartinez** [comment]
I read carefully the issue you linked, but unfortunately I never wrote a cmake file and the changes I made did not work.
I imagine that the changes to make cmake and swig work properly with python are minor since I am able to build the package successfully when I run the build from my cmake, but it crashes with conda build.

If you ever have a little time to reproduce, these are the steps:

```bash
$ git clone git@github.com:pyomeca/BTKCore.git
$ conda build conda.recipe/
```
A big thank you for your patience.

**Comment by mingwandroid** [comment]
I don't get the same result as you. With a minor change:

`$ cat build.sh`
```
#!/bin/bash
mkdir build
cd build

# Filter out -std=.* from CXXFLAGS as it disrupts checks for C++ language levels.
re='(.*[[:space:]])\-std\=[^[:space:]]*(.*)'
if [[ "${CXXFLAGS}" =~ $re ]]; then
  export CXXFLAGS="${BASH_REMATCH[1]}-std=c++14${BASH_REMATCH[2]}"
fi

cmake ../ \
      -DCMAKE_INSTALL_PREFIX=$PREFIX \
      -DBUILD_SHARED_LIBS=ON \
      -DBTK_WRAP_PYTHON=ON \
      -DPYTHON_EXECUTABLE=$PYTHON \

make -j $CPU_COUNT ${VERBOSE_CM}
```

`$ cat meta.yaml`
```
package:
  name: btk
  version: "0.3"

source:
  git_url: https://github.com/pyomeca/BTKCore.git

build:
  number: 0
  detect_binary_files_with_prefix: True

requirements:
  host:
    - python
    - numpy
    - setuptools
    - swig
  build:
    - {{ compiler('cxx') }}
    - cmake
  run:
    - python
    - numpy

about:
  home: https://github.com/pyomeca/BTKCore
  summary: Read, modify, process, and write acquisition data recorded by a motion capture system

extra:
    recipe-maintainers:
        - mrtnz
```

.. I get a package built at least. You can test with `conda create -n btk-py27 -c rdonnelly btk --override-channels -c rdonnelly -c https://repo.continuum.io/pkgs/main`

Here is my [btk-linux.log](https://github.com/conda/conda-build/files/1887943/btk-linux.log) in case it is useful.

I don't know if it works though as I don't know anything about this software and the recipe doesn't contain any tests:

```
Nothing to test for: /opt/conda/conda-bld/linux-64/btk-0.3-py27hcfd39f1_0.tar.bz2
```

You should add a python import test at least. It seems like the python extension module got built but not installed because I see:

```
cd /opt/conda/conda-bld/btk_1523219720608/work/build/Wrapping/Python && /opt/conda/conda-bld/btk_1523219720608/_build_env/bin/cmake -E cmake_link_script CMakeFiles/_btk.dir/link.txt --verbose=1
/opt/conda/conda-bld/btk_1523219720608/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++ -fPIC -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/opt/conda/conda-bld/btk_1523219720608/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix -O3 -DNDEBUG -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/opt/conda/conda-bld/btk_1523219720608/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib -L/opt/conda/conda-bld/btk_1523219720608/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib -shared  -o ../../bin/_btk.so CMakeFiles/_btk.dir/__/__/bin/btkSwigPYTHON_wrap.cxx.o CMakeFiles/_btk.dir/btkCommonSwig.cpp.o CMakeFiles/_btk.dir/btkIOSwig.cpp.o CMakeFiles/_btk.dir/btkBasicFiltersSwig.cpp.o -Wl,-rpath,/opt/conda/conda-bld/btk_1523219720608/work/build/bin -lpython2.7 ../../bin/libBTKIO.so.0.4dev.0 ../../bin/libBTKBasicFilters.so.0.4dev.0 ../../bin/libBTKCommon.so.0.4dev.0
```

.. but no further reference to `../../bin/_btk.so`. This is likely due to a missing INSTALL target or maybe another bug in CMake's Python integration.

 I did spot that it finds Python libs that it thinks needs to be linked to when it does should not link to any (our Python executable links statically to the core Python code on Linux and macOS, this CMake FindPython bug is more serious on macOS than Linux though in that you can get away with it on Linux up until you try to submit a wheel with any extension modules linked in this way to the PyPA whereas on macOS you get a crash because it runs the shared library's python code instead of the executable's python code).

I saw all of these warnings from CMake that really need to addressed too:

```
-- Found SWIG: /opt/conda/conda-bld/btk_1523204699649/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/swig (found suitable version "3.0.12", minimum required is "2.0")
-- Found PythonLibs: /opt/conda/conda-bld/btk_1523204699649/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/libpython2.7.so (found version "2.7.14")
-- Found NumPy: /opt/conda/conda-bld/btk_1523204699649/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/numpy/core/include (found version "1.9.3")
-- NumPy ver. 1.9.3 found (include: /opt/conda/conda-bld/btk_1523204699649/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/numpy/core/include)
CMake Deprecation Warning at /opt/conda/conda-bld/btk_1523204699649/_build_env/share/cmake-3.9/Modules/UseSWIG.cmake:228 (message):
  SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
  Wrapping/Python/CMakeLists.txt:35 (SWIG_ADD_MODULE)


CMake Warning (dev) at Packaging/CMakeLists.txt:1 (ADD_CUSTOM_TARGET):
  Policy CMP0037 is not set: Target names should not be reserved and should
  match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The target name "package" is reserved or not valid for certain CMake
  features, such as generator expressions, and may result in undefined
  behavior.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at Packaging/CMakeLists.txt:6 (GET_TARGET_PROPERTY):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "BTKCommon".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at Packaging/CMakeLists.txt:6 (GET_TARGET_PROPERTY):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "BTKBasicFilters".
  Use the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at Packaging/CMakeLists.txt:6 (GET_TARGET_PROPERTY):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "BTKIO".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at Packaging/CMakeLists.txt:24 (GET_TARGET_PROPERTY):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "_btk".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:373 (EXPORT_LIBRARY_DEPENDENCIES):
  Policy CMP0033 is not set: The export_library_dependencies command should
  not be called.  Run "cmake --help-policy CMP0033" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

Looking at the github repo it seems you added all these CMake files but they've not been updated in a very long time, by and large. IMHO you really will need to learn CMake pretty well to be able to work on a project that uses CMake so heavily. FWIW, personally, I'd avoid CMake when dealing with Python parts as much as possible. Use it for the things it was designed for (making C and C++ stuff) and discard it for everything else, but you'd need to be familiar with Python's normal packaging for that. You'd use CMake custom commands to run setuptools instead basically.

Anyway, you may be able to update the CMake stuff and my previous [comment](https://github.com/ContinuumIO/anaconda-issues/issues/9078#issuecomment-378278392) gives enough hints about what needs to be done, briefly you need to run Python to see if it's a shared or a static build and change the extension module linking configuration depending on that result (or just ignore shared, I don't think it's useful since any shared Python interpreter will load the DSO beforehand anyway).

Also you are using `conda-forge` as your highest priority channel which means you are not building software that is binary compatible with `Anaconda Defaults` nor using the `Anaconda Defaults` build tools with all the latest fixes (I have had to patch bugs in things like `pkg-config`, `libtool` and `CMake`).

It is also unclear that the libraries take from `conda-forge` will be compatible with those from `Anaconda Defaults`; in my experience, probably not (this is something we're all trying to improve or even fix in the future). You can verify which packages are coming from which by adding `show_channel_urls: true` to your `~/.condarc` file and re-running the build.

Best of luck.

**Comment by romainmartinez** [comment]
I ended up writing my own c++ library rather than using someone's outdated library.
Everything works fine now, I no longer use swig and my cmake is cleaner.
Thank you for your time!
