### ISSUE TITLE
zip_keys misbehavior

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#2829]
Observed with conda-build 3.8.1, on openblas-feedstock from https://github.com/AnacondaRecipes/openblas-feedstock/

```
Traceback (most recent call last):
  File "/Users/msarahan/miniconda3/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 238, in main
    args.subcommand_func(args)
  File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 182, in __call__
    exclusive_config_file=args.exclusive_config_file)
  File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 824, in main
    render_appveyor(env, config, forge_dir)
  File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 613, in render_appveyor
    platform_specific_setup=_appveyor_specific_setup)
  File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 355, in _render_ci_provider
    configs.extend(dump_subspace_config_files(metas, forge_dir, platform))
  File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 232, in dump_subspace_config_files
    configs, top_level_loop_vars = _collapse_subpackage_variants(metas)
  File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 214, in _collapse_subpackage_variants
    'ignore_version', 'ignore_build_only_deps'})
  File "/Users/msarahan/code/conda-build/conda_build/variants.py", line 392, in dict_of_lists_to_list_of_dicts
    for group in _get_zip_groups(dict_of_lists):
  File "/Users/msarahan/code/conda-build/conda_build/variants.py", line 358, in _get_zip_groups
    groups.append(_get_zip_dict_of_lists(combined_variant, group))
  File "/Users/msarahan/code/conda-build/conda_build/variants.py", line 341, in _get_zip_dict_of_lists
    key, combined_variant[key]))
ValueError: zip field python (('3.6', '2.7', '3.5')) length does not match zip field c_compiler (('vs2015', 'vs2008')) length.  All zip fields within a group must be the same length.
```

This is wrong, because python isn't a used variable at all, and the c_compiler has been collapsed accordingly to its unique values.  This didn't propagate correctly to the other zip_keys (python), and so we have this error.

**Comment by msarahan** [comment]
fixed by #2832
