### ISSUE TITLE
What's the recommended alternative to use '-' in keys in CBC.yaml ?

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#2885]
I wanted to add `mysql-connector-c`, which provides `libmysqlclient.so`
```
(base) [nwani@somemachine 1526468208 ]$ conda build . -m conda_build_config.yaml 
Traceback (most recent call last):
  File "/spare/local/nwani/conda/root/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/spare/local/nwani/conda/root/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/spare/local/nwani/conda/root/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/spare/local/nwani/conda/root/lib/python2.7/site-packages/conda_build/api.py", line 199, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/spare/local/nwani/conda/root/lib/python2.7/site-packages/conda_build/build.py", line 2078, in build_tree
    bypass_env_check=True)
  File "/spare/local/nwani/conda/root/lib/python2.7/site-packages/conda_build/render.py", line 659, in render_recipe
    variants = get_package_variants(m, variants=variants)
  File "/spare/local/nwani/conda/root/lib/python2.7/site-packages/conda_build/variants.py", line 487, in get_package_variants
    raise ValueError("Error in config {}: {}".format(f, str(e)))
ValueError: Error in config /spare/scratch/1526468208/conda_build_config.yaml: Variant configuration errors: 
['"-" is a disallowed character in variant keys.  Key was: some-pkg']
```

**Comment by msarahan** [comment]
conda-build matches package names with keys from CBC.yaml by treating - and _ as equivalent.  Use - where appropriate for package names, and use _ in CBC.yaml.

Side note: this is not true for pin_run_as_build, which conda-forge has recently pointed out.  For pin_run_as_build, the package name keys must match the keys under pin_run_as_build.  Discussion at https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/58#discussion_r187400569
