### ISSUE TITLE
`AttributeError: 'NoneType' object has no attribute 'split'`

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda-build#2900]
conda-build 3.10.4 fails on previously working script with error:

```
(base) [yfeng1@waterfall conda-channel-bccp]$ conda build -m variants/pc/python-3.6.yaml -c bccp platform/cfastpm
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from variants/pc/python-3.6.yaml
INFO:conda_build.variants:Adding in variants from variants/pc/python-3.6.yaml
Traceback (most recent call last):
  File "/home/yfeng1/anaconda3/install/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/build.py", line 2146, in build_tree
    bypass_env_check=True)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/render.py", line 740, in render_recipe
    allow_no_other_outputs=True, bypass_env_check=bypass_env_check)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/render.py", line 646, in distribute_variants
    bypass_env_check=bypass_env_check)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/metadata.py", line 946, in parse_until_resolved
    bypass_env_check=bypass_env_check)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/metadata.py", line 885, in parse_again
    bypass_env_check=bypass_env_check),
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/metadata.py", line 1421, in _get_contents
    env.globals.update(environ.get_dict(m=self))
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/environ.py", line 252, in get_dict
    d.update(python_vars(m))
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/environ.py", line 313, in python_vars
    build_or_host = 'host' if metadata.is_cross else 'build'
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/metadata.py", line 818, in is_cross
    return (bool(self.get_depends_top_and_out('host')) or
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/metadata.py", line 1097, in get_depends_top_and_out
    req_names = set(req.split()[0] for req in meta_requirements)
  File "/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/conda_build/metadata.py", line 1097, in <genexpr>
    req_names = set(req.split()[0] for req in meta_requirements)
AttributeError: 'NoneType' object has no attribute 'split'
```

I am attaching a tarball of the failed script. The error occurred before building actually has started.

[cfastpm.tar.gz](https://github.com/conda/conda-build/files/2023386/cfastpm.tar.gz)

**Comment by rainwoodman** [comment]
It appears that the variants are not yet replaced at this stage -- `{ mpi }` is replaced with None rather than the value declared in the variant file.

**Comment by msarahan** [comment]
Thanks for reporting.  3.10.4 got rid of a lot of the agressive trimming of recipes, which might be what led to this.  It was necessary to support https://github.com/conda/conda-build/issues/2887

This should work, though, and I'll look into it for 3.10.5

**Comment by rainwoodman** [comment]
Thanks. It would be nice to have a test case for this when it is fixed. We'll pin to 3.10.3 for now.

**Comment by msarahan** [comment]
It would be nice if you submitted a PR for such a test case.
