### ISSUE TITLE
tarfile.ReadError: file could not be opened successfully

### ISSUE THREAD

**Issue by chienhsiang** [conda/conda-build#294]
Traceback (most recent call last):
  File "/home/chsu/anaconda3/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/home/chsu/anaconda3/lib/python3.4/site-packages/conda_build/main_build.py", line 110, in main
    args_func(args, p)
  File "/home/chsu/anaconda3/lib/python3.4/site-packages/conda_build/main_build.py", line 312, in args_func
    args.func(args, p)
  File "/home/chsu/anaconda3/lib/python3.4/site-packages/conda_build/main_build.py", line 272, in execute
    build.build(m, verbose=not args.quiet, post=post)
  File "/home/chsu/anaconda3/lib/python3.4/site-packages/conda_build/build.py", line 310, in build
    source.provide(m.path, m.get_section('source'))
  File "/home/chsu/anaconda3/lib/python3.4/site-packages/conda_build/source.py", line 234, in provide
    unpack(meta)
  File "/home/chsu/anaconda3/lib/python3.4/site-packages/conda_build/source.py", line 65, in unpack
    tar_xf(src_path, WORK_DIR)
  File "/home/chsu/anaconda3/lib/python3.4/site-packages/conda_build/utils.py", line 65, in tar_xf
    t = tarfile.open(tarball, mode)
  File "/home/chsu/anaconda3/lib/python3.4/tarfile.py", line 1553, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

**Comment by asmeurer** [comment]
This usually means you either got a partial download (try removing it from the cache in `/home/chsu/anaconda3/conda-bld/src_cache`, or the file is not really the type that the extension says it is, in which case change the `fn` to the correct type.

**Comment by sparshgarg** [comment]
@asmeurer I'm a beginner in python and find this really confusing. Can you please explain how to overcome this error faced by @chienhsiang ??
