### ISSUE TITLE
Trouble fixing linkages on macOS

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2943]
### Actual Behavior

Seeing a failure when trying to fix the linkages of libraries in a `scikit-learn` build.

```
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2177, in build_tree
    notest=notest,
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1571, in build
    built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env, stats)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 938, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 800, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/post.py", line 648, in post_build
    post_process_shared_lib(m, f, prefix_files)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/post.py", line 598, in post_process_shared_lib
    mk_relative_osx(path, m.config.host_prefix, m.config.build_prefix, files=files)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/post.py", line 346, in mk_relative_osx
    names = macho.otool(path)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/os_utils/macho.py", line 167, in otool
    raise CalledProcessError
TypeError: __init__() missing 2 required positional arguments: 'returncode' and 'cmd'
```

ref: https://travis-ci.org/conda-forge/scikit-learn-feedstock/jobs/387290313

### Expected Behavior

Fixing linkages should proceed without issue.

### Steps to Reproduce

Encountered this when trying to build `scikit-learn` in PR ( https://github.com/conda-forge/scikit-learn-feedstock/pull/66 ), which is trying to move from `conda-build` 2 to `conda-build` 3. Seeing similar issues when trying to build off `master` locally using `conda-build` 3.

##### `Output of conda info`

```
     active environment : base
    active env location : /Users/travis/miniconda3
            shell level : 1
       user config file : /Users/travis/.condarc
 populated config files : /Users/travis/.condarc
          conda version : 4.5.4
    conda-build version : 3.10.7
         python version : 3.6.5.final.0
       base environment : /Users/travis/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/travis/miniconda3/pkgs
                          /Users/travis/.conda/pkgs
       envs directories : /Users/travis/miniconda3/envs
                          /Users/travis/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Darwin/14.5.0 OSX/10.10.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by jakirkham** [comment]
Any thoughts here? This is blocking a rebuild of `scikit-learn` with `conda-build` 3.

**Comment by msarahan** [comment]
The bug is in the handling of some other error:

```
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/os_utils/macho.py", line 167, in otool
    raise CalledProcessError
TypeError: __init__() missing 2 required positional arguments: 'returncode' and 'cmd'
```

That CalledProcessError has insufficient arguments.  The error that caused the CalledProcessError is what you need to look into more.  You may need to fix the insufficient arguments issue in order to get insight into the root cause of the problem.

**Comment by jakirkham** [comment]
The `CalledProcessError` was introduced as part of PR ( https://github.com/conda/conda-build/pull/2635 ). Not really sure what the intent was there (not being familiar with that code really at all). Maybe someone else can comment. @mingwandroid?
