### ISSUE TITLE
conda-pipbuild fails on Python 3

### ISSUE THREAD

**Issue by pitrou** [conda/conda-build#297]
```
$ conda pipbuild funcsigs
Fetching package metadata: ....
Creating standard recipe for funcsigs-0.4
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/antoine/miniconda3/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/home/antoine/miniconda3/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 77, in main
    args_func(args, p)
  File "/home/antoine/miniconda3/lib/python3.4/site-packages/conda_build/main_build.py", line 312, in args_func
    args.func(args, p)
  File "/home/antoine/miniconda3/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 350, in execute
    build_package(package, version)
  File "/home/antoine/miniconda3/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 300, in build_package
    directory = build_recipe(package, version=version)
  File "/home/antoine/miniconda3/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 161, in build_recipe
    output = result.strip().split('\n')
TypeError: Type str doesn't support the buffer API
```

**Comment by spitz-dan-l** [comment]
Same experience here

**Comment by jetsnguns** [comment]
Same issue here. Package: python-levenshtein
```
C:\Anaconda3>conda pipbuild python-levenshtein
Package search: {'name': 'python-Levenshtein', 'version': '0.10.2', '_pypi_order
ing': 1, 'summary': 'Python extension computing string distances and similaritie
s.'}
Fetching package metadata: ....
Creating standard recipe for python-levenshtein-0.12.0
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-pipbuild-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda_build\main_pipbuild.py", line 77, i
n main
    args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda_build\main_build.py", line 329, in
args_func
    args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda_build\main_pipbuild.py", line 363,
in execute
    build_package(package, version)
  File "C:\Anaconda3\lib\site-packages\conda_build\main_pipbuild.py", line 304,
in build_package
    directory = build_recipe(package, version=version)
  File "C:\Anaconda3\lib\site-packages\conda_build\main_pipbuild.py", line 163,
in build_recipe
    output = result.strip().split('\n')
TypeError: 'str' does not support the buffer interface
```

Output of conda info command:
```
C:\Anaconda3>conda info
Current conda install:

             platform : win-64
        conda version : 3.10.1
  conda-build version : 1.12.0
       python version : 3.4.3.final.0
     requests version : 2.6.0
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by msarahan** [comment]
pipbuild no longer exists.  You need to do (at least) 2 steps now:

1. conda skeleton pypi (package name)
2. try building with ``conda build (package name)``
3. troubleshoot as necessary, or if it worked, great, go use your package
