### ISSUE TITLE
Wrong package cache is used on Linux

### ISSUE THREAD

**Issue by Bezier89** [conda/conda-build#2980]
First, set a package cache location by running a command like this (replace [CONDA_ROOT] with root folder of conda installation):

`[CONDA_ROOT]/bin/conda config --system --prepend pkgs_dirs /tmp/path`

As an easy way to test that this setting is honored, make the conda root folder read-only by running the following command:

`chmod -R 555 [CONDA_ROOT]`

Then, run a command such as follows:

`[CONDA_ROOT]/bin/conda skeleton pypi certifi`

The error is as follows:

```
Warning, the following versions were found for certifi
0
0.0.1
0.0.2
0.0.3
0.0.4
0.0.5
0.0.6
0.0.7
0.0.8
1.0.0
1.0.1
14.05.14
2015.04.28
2015.9.6
2015.9.6.1
2015.9.6.2
2015.11.20
2015.11.20.1
2016.2.28
2016.8.2
2016.8.8
2016.8.31
2016.9.26
2017.1.23
2017.4.17
2017.7.27
2017.7.27.1
2017.11.5
2018.1.18
2018.4.16
Using 2018.4.16
Use --version to specify a different version.
Using url https://files.pythonhosted.org/packages/4d/9c/46e950a6f4d6b4be571ddcae21e7bc846fcbb88f1de3eff0f6dd0a6be55d/certifi-2018.4.16.tar.gz (146 KB) for certifi.
Downloading certifi
PyPI URL:  https://files.pythonhosted.org/packages/4d/9c/46e950a6f4d6b4be571ddcae21e7bc846fcbb88f1de3eff0f6dd0a6be55d/certifi-2018.4.16.tar.gz
Using cached download
Unpacking certifi...
done
working in /tmp/tmp49sl85z1conda_skeleton_certifi-2018.4.16.tar.gz

Leaving build/test directories:
  Work:  /home/jsexton/conda-bld/skeleton_1529514542814/work
  Test:  /home/jsexton/conda-bld/skeleton_1529514542814/test_tmp
Leaving build/test environments:
  Test: source activate  /home/jsexton/conda-bld/skeleton_1529514542814/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol
  Build:        source activate  /home/jsexton/conda-bld/skeleton_1529514542814/_build_env


Traceback (most recent call last):
  File "[CONDA_ROOT]/lib/python3.5/site-packages/conda_build/api.py", line 281, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "[CONDA_ROOT]/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 274, in skeletonize
    setup_options=setup_options)
  File "[CONDA_ROOT]/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 665, in get_package_metadata
    config=config)
  File "[CONDA_ROOT]/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 968, in get_pkginfo
    setup_options=setup_options)
  File "[CONDA_ROOT]/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 1005, in run_setuppy
    subdir=config.host_subdir, clear_cache=False, config=config)
  File "[CONDA_ROOT]/lib/python3.5/site-packages/conda_build/environ.py", line 782, in create_env
    locks = utils.get_conda_operation_locks(config)
  File "[CONDA_ROOT]/lib/python3.5/site-packages/conda_build/utils.py", line 586, in get_conda_operation_locks
    os.makedirs(folder)
  File "[CONDA_ROOT]/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '[CONDA_ROOT]/pkgs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[CONDA_ROOT]/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File "[CONDA_ROOT]/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "[CONDA_ROOT]/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    version=args.version, config=config)
  File "[CONDA_ROOT]/lib/python3.5/site-packages/conda_build/api.py", line 281, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "[CONDA_ROOT]/lib/python3.5/site-packages/conda_build/config.py", line 738, in __exit__
    self.clean(remove_folders=False)
  File "[CONDA_ROOT]/lib/python3.5/site-packages/conda_build/config.py", line 713, in clean
    for lock in get_conda_operation_locks(self.locking, self.bldpkgs_dirs):
  File "[CONDA_ROOT]/lib/python3.5/site-packages/conda_build/utils.py", line 586, in get_conda_operation_locks
    os.makedirs(folder)
  File "[CONDA_ROOT]/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '[CONDA_ROOT]/pkgs'
```

The above command works as expected if using conda-build 3.9.2, but is broken with the above strack trace in conda-build 3.10.0 or greater (up to 3.10.9). Note that setting pkgs_dir via an environment variable as follows:

`export CONDA_PKGS_DIRS=/tmp/path`

still works even in conda-build 3.10.* Also note that the same issue does not appear to reproduce at all on Windows.

**Comment by Bezier89** [comment]
After some investigation:

1) This only happens if the "pkgs" folder doesn't exist in CONDA_ROOT (even though it should be unused). An empty folder [CONDA_ROOT]/pkgs will suffice for suppressing this error.

2) There is some interaction between conda and conda-build. conda=4.5.2 + conda-build=3.10.9 exhibits the issue, but conda=4.5.3 + conda-build=3.10.9 does not. It remains fixed as of the latest versions (conda=4.5.8 + conda-build=3.11.0). I'm marking this issue as closed, as it appears to have been resolved along with https://github.com/conda/conda/issues/7240.
