### ISSUE TITLE
load_npm() attempts to load 'package.json' from CWD, rather than source dir

### ISSUE THREAD

**Issue by tjd2002** [conda/conda-build#2990]
When using the `load_npm()` jinja2 macro, conda build fails if it is run from anywhere but the source directory (dir containing the package.json file). I believe this is because of the following lines, which apparently attempt to load 'package.json' from the CWD, rather than from a location relative to the recipe:
https://github.com/conda/conda-build/blob/93a3dcb523b977bb24f6b496c4611f12b1fcd118/conda_build/jinja_context.py#L155-L159

`conda build --check` **succeeds** from the top-level directory:
```$ conda build --check conda-recipe/meta.yaml
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for mountainlab-js
INFO:conda_build.metadata:Attempting to finalize metadata for mountainlab-js
Solving environment: ...working... done
Solving environment: ...working... done
```

`conda build --check` **fails** from anywhere else (that doesn't contain a package.json) file:
```$ cd ..
eena:Src tjd$ conda build --check mountainlab-js/conda-recipe/meta.yaml
Traceback (most recent call last):
  File "/Users/tjd/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/tjd/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/Users/tjd/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 407, in execute
    outputs = [action(recipe, config) for recipe in args.recipe]
  File "/Users/tjd/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 407, in <listcomp>
    outputs = [action(recipe, config) for recipe in args.recipe]
  File "/Users/tjd/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 334, in check_action
    return api.check(recipe, config=config)
  File "/Users/tjd/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 142, in check
    config=config, variants=variants)
  File "/Users/tjd/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 44, in render
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/tjd/anaconda3/lib/python3.6/site-packages/conda_build/render.py", line 705, in render_recipe
    m = MetaData(recipe_dir, config=config)
  File "/Users/tjd/anaconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 834, in __init__
    self.parse_again(permit_undefined_jinja=True, allow_no_other_outputs=True)
  File "/Users/tjd/anaconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 907, in parse_again
    bypass_env_check=bypass_env_check),
  File "/Users/tjd/anaconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 1475, in _get_contents
    rendered = template.render(environment=env)
  File "/Users/tjd/anaconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/tjd/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/tjd/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tjd/anaconda3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "mountainlab-js/conda-recipe/meta.yaml", line 1, in top-level template code
    #Automaticly generating npm conda package
  File "/Users/tjd/anaconda3/lib/python3.6/site-packages/conda_build/jinja_context.py", line 158, in load_npm
    with open('package.json', **mode_dict) as pkg:
FileNotFoundError: [Errno 2] No such file or directory: 'package.json'
```

I'm sure the fix is quite simple (just an os.join to the source directory?) but I'm not familiar enough with the location of things during the build. If someone gives me a pointer, I can work on a PR.

My conda-recipe/meta.yaml (below) is based off the template at https://github.com/conda/conda-build/blob/master/conda_build/templates/npm.yaml:
```
#Automaticly generating npm conda package
{% set data = load_npm() %}
package:
  name: {{data.get('name').lower()}}
  version: {{data.get('version')}}

source:
  git_url: .. # relative to recipe dir
  git_rev:

build:
  number: {% block build_number %}1{% endblock %}
  script:
    - tgzfile=$(npm pack)
    - npm install -g $tgzfile

requirements:
  build:
    - nodejs

  run:
    - nodejs

test:
  commands:
    - npm list -g mountainlab-js
    - ml-config
  requires:
    - nodejs

about:
  home: {{data.get('repository').get('url')}}
  license: {{data.get('license')}}

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
```

**Comment by tjd2002** [comment]
Looks like this was fixed in an unmarked PR from 2016 by @srossross  https://github.com/conda/conda-build/pull/1147

**Comment by analog-cbarber** [comment]
All that function does is load a JSON file. Why not simply make a `load_json` function that takes a file path argument?

**Comment by tjd2002** [comment]
The fix proposed at #1147 was never merged, in main, `load_npm` still appears to look in the CWD, so I think this issue is not stale.
