### ISSUE TITLE
Weird error when using "conda convert --platform all"

### ISSUE THREAD

**Issue by MyVanitar** [conda/conda-build#3013]
When I try to convert a package to all platforms, I got this weird error:

```python
(test) D:\>conda convert -f --platform all D:\tensorboard\win-64\tensorboard-1.8.0-py36_0.tar.bz2 -o tensorboard\
Converting tensorboard-1.8.0-py36_0.tar.bz2 from win-64 to osx-64
Traceback (most recent call last):
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\test\Scripts\conda-convert-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\test\lib\site-packages\conda_build\cli\main_convert.py", line 130, in main
    return execute(sys.argv[1:])
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\test\lib\site-packages\conda_build\cli\main_convert.py", line 126, in execute
    api.convert(f, **args.__dict__)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\test\lib\site-packages\conda_build\api.py", line 304, in convert
    dry_run=dry_run, dependencies=dependencies)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\test\lib\site-packages\conda_build\convert.py", line 787, in conda_convert
    dependencies, verbose)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\test\lib\site-packages\conda_build\convert.py", line 717, in convert_from_windows_to_unix
    update_paths_file(temp_dir, target_platform='unix')
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\test\lib\site-packages\conda_build\convert.py", line 398, in update_paths_file
    path['sha256'] = update_executable_sha(temp_dir, path['_path'])
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\test\lib\site-packages\conda_build\convert.py", line 318, in update_executable_sha
    with open(os.path.join(package_directory, executable_path), 'rb') as script_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Hesam\\AppData\\Local\\Temp\\tmprh35ymar\\bin/tensorboard
```
```
# Name                    Version                   Build  Channel
anaconda-client           1.6.14                   py36_0
conda                     4.5.8                    py36_0
conda-build               3.10.9                   py36_0
conda-env                 2.6.0                h36134e3_1
conda-verify              2.0.0            py36h065de53_0

```

What's the reason behind this?

**Comment by VanitarNordic** [comment]
Downgrading to 

`conda-build               3.4.1                    py36_0 `

fixed the issue and it made all conversions.

Please fix it as soon as possible

**Comment by mandeep** [comment]
Thanks for reporting this. It looks like an error in parsing here: https://github.com/conda/conda-build/blob/master/conda_build/convert.py#L305-L306

I'll submit a fix soon.
