### ISSUE TITLE
build fails without specific debug info

### ISSUE THREAD

**Issue by paskino** [conda/conda-build#3066]
#### Actual behaviour

I'm building a package on Windows but encounter the error
`EOFError: Compressed file ended before the end-of-stream marker was reached`

The stack trace below doesn't contain specific info. It is impossible to debug. So the only solution was [experience](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/WxOAThwVwvg)

The problem was a corrupt file in the cache, solved by `conda clean -a`. 

### Expected Behavior
The stack trace should give some more informations, e.g. the name of the file in the cache which is corrupt.

```
conda build Wrappers\python\conda-recipe --python 3.5 --numpy 1.12
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
C:\Apps\miniconda3\lib\site-packages\conda_build\environ.py:377: UserWarning: The environment variable 'CIL_VERSION' is being passed through with value 0.10.1.  If you are splitting build and test phases with --no-test, please ensure that this value is also set similarly at test time.
  UserWarning
Attempting to finalize metadata for ccpi-reconstruction
INFO:conda_build.metadata:Attempting to finalize metadata for ccpi-reconstruction
Traceback (most recent call last):
  File "C:\Apps\miniconda3\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Apps\miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 413, in main
    execute(sys.argv[1:])
  File "C:\Apps\miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 404, in execute
    verify=args.verify)
  File "C:\Apps\miniconda3\lib\site-packages\conda_build\api.py", line 193, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "C:\Apps\miniconda3\lib\site-packages\conda_build\build.py", line 1962, in build_tree
    notest=notest,
  File "C:\Apps\miniconda3\lib\site-packages\conda_build\build.py", line 1040, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "C:\Apps\miniconda3\lib\site-packages\conda_build\render.py", line 582, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "C:\Apps\miniconda3\lib\site-packages\conda_build\metadata.py", line 1845, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "C:\Apps\miniconda3\lib\site-packages\conda_build\metadata.py", line 670, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "C:\Apps\miniconda3\lib\site-packages\conda_build\render.py", line 379, in finalize_metadata
    exclude_pattern)
  File "C:\Apps\miniconda3\lib\site-packages\conda_build\render.py", line 293, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "C:\Apps\miniconda3\lib\site-packages\conda_build\render.py", line 284, in _read_upstream_pin_files
    extra_run_specs = get_upstream_pins(m, actions, env)
  File "C:\Apps\miniconda3\lib\site-packages\conda_build\render.py", line 271, in get_upstream_pins
    specs = _read_specs_from_package(pkg_loc, pkg_dist)
  File "C:\Apps\miniconda3\lib\site-packages\conda\utils.py", line 47, in __call__
    value = self.func(*args, **kw)
  File "C:\Apps\miniconda3\lib\site-packages\conda_build\render.py", line 204, in _read_specs_from_package
    specs_yaml = utils.package_has_file(pkg_loc, 'info/run_exports.yaml')
  File "C:\Apps\miniconda3\lib\site-packages\conda\utils.py", line 47, in __call__
    value = self.func(*args, **kw)
  File "C:\Apps\miniconda3\lib\site-packages\conda_build\utils.py", line 724, in package_has_file
    text = t.extractfile(file_path).read()
  File "C:\Apps\miniconda3\lib\tarfile.py", line 2073, in extractfile
    tarinfo = self.getmember(member)
  File "C:\Apps\miniconda3\lib\tarfile.py", line 1747, in getmember
    tarinfo = self._getmember(name)
  File "C:\Apps\miniconda3\lib\tarfile.py", line 2332, in _getmember
    members = self.getmembers()
  File "C:\Apps\miniconda3\lib\tarfile.py", line 1758, in getmembers
    self._load()        # all members, we first have to
  File "C:\Apps\miniconda3\lib\tarfile.py", line 2355, in _load
    tarinfo = self.next()
  File "C:\Apps\miniconda3\lib\tarfile.py", line 2286, in next
    self.fileobj.seek(self.offset - 1)
  File "C:\Apps\miniconda3\lib\bz2.py", line 278, in seek
    return self._buffer.seek(offset, whence)
  File "C:\Apps\miniconda3\lib\_compression.py", line 143, in seek
    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
  File "C:\Apps\miniconda3\lib\_compression.py", line 99, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Comment by msarahan** [comment]
This now raises a more friendly error:

```
    except (tarfile.ReadError, IOError, EOFError):
        raise RuntimeError("Could not extract metadata from %s. File probably corrupt.  "
                           "Please manually remove this file and try again." % package_path)
```
