### ISSUE TITLE
conda-build does not ignore `conda` binaries in `bin`

### ISSUE THREAD

**Issue by hmaarrfk** [conda/conda-build#3090]
I have an `outputs:` section in a `meta.yaml` that includes
```
outputs:
  files:
   - bin
```
After a conversation with @mingwandroid I was told that conda-build should automatically ignore the conda specific files.

However, it seems that it does not and fails with:
```
Traceback (most recent call last):
  File "/home/mark/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/mark/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 424, in main
    execute(sys.argv[1:])
  File "/home/mark/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 415, in execute
    verify=args.verify)
  File "/home/mark/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/mark/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2209, in build_tree
    notest=notest,
  File "/home/mark/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1600, in build
    built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env, stats)
  File "/home/mark/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 948, in bundle_conda
    assert 'bin/conda' not in files and 'Scripts/conda.exe' not in files, ("Bug in conda-build "
AssertionError: Bug in conda-build has included conda binary in package. Please report this on the conda-build issue tracker.
```

I would expect that the conda files be ignored.

**Comment by msarahan** [comment]
When you include all files, that's bypassing everything else.  I'd actually say this error shouldn't even be raised.  If you manually specify files, you should know what you are doing.  This is not a bug.  If you want the behavior to change, please submit a PR.

**Comment by hmaarrfk** [comment]
ok. That is what I thought but my conversation with @mingwandroid made me think otherwise.
