### ISSUE TITLE
Error: 'conda' can only be installed into root environment

### ISSUE THREAD

**Issue by peter1000** [conda/conda-build#31]
if a recipe has a build/run requirement of `conda` itself I get this `Error: 'conda' can only be installed into root environment`

**e.g. conda-build requires 'conda'**

if I remove 'conda' from the requirement I get:

```
Searching for conda
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    install_requires = ['conda'],
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/distutils/dist.py", line 929, in run_commands
    self.run_command(cmd)
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/distutils/dist.py", line 948, in run_command
    cmd_obj.run()
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/site-packages/setuptools-2.1-py3.3.egg/setuptools/command/install.py", line 74, in run
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/site-packages/setuptools-2.1-py3.3.egg/setuptools/command/install.py", line 97, in do_egg_install
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/site-packages/setuptools-2.1-py3.3.egg/setuptools/command/easy_install.py", line 358, in run
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/site-packages/setuptools-2.1-py3.3.egg/setuptools/command/easy_install.py", line 574, in easy_install
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/site-packages/setuptools-2.1-py3.3.egg/setuptools/command/easy_install.py", line 625, in install_item
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/site-packages/setuptools-2.1-py3.3.egg/setuptools/command/easy_install.py", line 671, in process_distribution
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/site-packages/setuptools-2.1-py3.3.egg/pkg_resources.py", line 564, in resolve
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/site-packages/setuptools-2.1-py3.3.egg/pkg_resources.py", line 802, in best_match
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/site-packages/setuptools-2.1-py3.3.egg/pkg_resources.py", line 814, in obtain
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/site-packages/setuptools-2.1-py3.3.egg/setuptools/command/easy_install.py", line 581, in easy_install
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/site-packages/setuptools-2.1-py3.3.egg/setuptools/package_index.py", line 593, in fetch_distribution
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/site-packages/setuptools-2.1-py3.3.egg/setuptools/package_index.py", line 431, in find_packages
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/site-packages/setuptools-2.1-py3.3.egg/setuptools/package_index.py", line 771, in scan_url
  File "/home/workerm/miniconda3/envs/_build/lib/python3.3/site-packages/setuptools-2.1-py3.3.egg/setuptools/package_index.py", line 283, in process_url
RuntimeError: Setuptools downloading is disabled in conda build  url=https://pypi.python.org/simple/conda/r
+ exit
Command failed: /bin/bash -x -e /home/workerm/miniconda3/conda-recipes-own/conda_build/build.sh
```

May I ask how one does that in the correct manner?

**Comment by peter1000** [comment]
closing my old issues - at the moment I do not use conda
