### ISSUE TITLE
Exception("not a valid source") on conda skeleton pypi python-graph-core

### ISSUE THREAD

**Issue by rhishi** [conda/conda-build#310]
I'm trying to build PyPI package named "python-graph-core", and I get an exception saying "not a valid source".

[macbook ~> conda skeleton pypi python-graph-core 
Using url http://code.google.com/p/python-graph/downloads/list (0 B) for python-graph-core.
Downloading python-graph-core (use --no-download to skip this step)
Unpacking python-graph-core...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/me/anaconda/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/Users/me/anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 131, in main
    args_func(args, p)
  File "/Users/me/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 312, in args_func
    args.func(args, p)
  File "/Users/me/anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 144, in execute
    pypi.main(args, parser)
  File "/Users/me/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 372, in main
    get_package_metadata(args, package, d, data)
  File "/Users/me/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 424, in get_package_metadata
    unpack(join(SRC_CACHE, d['filename']), tempdir)
  File "/Users/me/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 634, in unpack
    raise Exception("not a valid source")
Exception: not a valid source

--------------------

My conda info:

```
             platform : osx-64
        conda version : 3.7.4
  conda-build version : 1.10.0
       python version : 2.7.9.final.0
     requests version : 2.5.1
     root environment : /Users/me/anaconda  (writable)
  default environment : /Users/me/anaconda
     envs directories : /Users/me/anaconda/envs
        package cache : /Users/me/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
          config file : None
    is foreign system : False
```

**Comment by asmeurer** [comment]
I'd say this is an upstream problem for the python-graph-core guys. The download url on their page, http://code.google.com/p/python-graph/downloads/list, is indeed not a valid source. And now that pip no longer crawls webpages by default, people won't even be able to pip install that library. 

As a workaround, find the actual source code for the tarball and pass that to conda skeleton pypi (like `conda skeleton pypi https://python-graph.googlecode.com/files/python-graph-core-1.8.2.tar.gz`)
