### ISSUE TITLE
Building Windows R packages fails when R version restricted

### ISSUE THREAD

**Issue by cbrueffer** [conda/conda-build#3105]
### Actual Behavior

For R packages in conda-forge, when restricting the R version as below, Appveyor Windows builds fail, as e.g. in https://ci.appveyor.com/project/conda-forge/r-partykit-feedstock/build/1.0.5

This behaviour is reproducible and I have seen it in several R feedstocks now. Removing the R restriction allows the build to succeed.

```
[...]
TEST END: C:\bld\win-64\r-partykit-1.2_2-r341h6115d3f_0.tar.bz2
Renaming work directory,  C:\bld\r-partykit_1535805746551\work  to  C:\bld\r-partykit_1535805746551\work_moved_r-partykit-1.2_2-r<35h6115d3f_0_win-64_main_build_loop
Traceback (most recent call last):
  File "C:\Miniconda36-x64\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\bld\\r-partykit_1535805746551\\work' -> 'C:\\bld\\r-partykit_1535805746551\\work_moved_r-partykit-1.2_2-r<35h6115d3f_0_win-64_main_build_loop'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Miniconda36-x64\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 424, in main
    execute(sys.argv[1:])
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 415, in execute
    verify=args.verify)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 2273, in build_tree
    shutil.move(metadata.config.work_dir, dest)
  File "C:\Miniconda36-x64\lib\shutil.py", line 555, in move
    symlinks=True)
  File "C:\Miniconda36-x64\lib\shutil.py", line 315, in copytree
    os.makedirs(dst)
  File "C:\Miniconda36-x64\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\bld\\r-partykit_1535805746551\\work_moved_r-partykit-1.2_2-r<35h6115d3f_0_win-64_main_build_loop'
Command exited with code 1
```

### Expected Behavior

Builds should succeed, which they do when the version is not restricted.

### Steps to Reproduce

Restrict the R version in the host and run sections like so:

```
  host:
    - r-base <3.5
  run:
    - r-base <3.5
```

See e.g. the https://github.com/conda-forge/r-partykit-feedstock/pull/2 `r-partykit` PR.

##### `Output of conda info`

Current standard conda-forge build setup (conda-smithy 3.1.12 and pinning 2018.08.31).

**Comment by cbrueffer** [comment]
@msarahan : @mbargull said you'd be interested in this

**Comment by cbrueffer** [comment]
Another example for this issue: https://github.com/conda-forge/staged-recipes/pull/6750
