### ISSUE TITLE
error when building pygobject

### ISSUE THREAD

**Issue by licode** [conda/conda-build#3124]
When I try to build pygobject (https://github.com/conda-forge/pygobject-feedstock) locally 
```
conda build .  -c conda-forge
```
I got following error:
```
', '-Wl,--export-dynamic', '-lgmodule-2.0', '-pthread', '-lrt', '-lglib-2.0', '-Wl,-O2', '-Wl,--sort-common', '-Wl,--as-needed', '-Wl,-z,relro', '-Wl,-z,now', '-Wl,--disable-new-dtags', '-Wl,-rpath,/home/lili/conda-bld/pygobject_1536347321861/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib', '-L/home/lili/conda-bld/pygobject_1536347321861/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib']' returned non-zero exit status 1.
make[2]: *** [Makefile:897: Regress-1.0.gir] Error 1
make[2]: Leaving directory '/home/lili/conda-bld/pygobject_1536347321861/work/tests'
make[1]: *** [Makefile:757: check-am] Error 2
make[1]: Leaving directory '/home/lili/conda-bld/pygobject_1536347321861/work/tests'
make: *** [Makefile:686: check-recursive] Error 1
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 413, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 404, in execute
    verify=args.verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 193, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1944, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1240, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 678, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 674, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/lili/conda-bld/pygobject_1536347321861/work/conda_build.sh']' returned non-zero exit status 2.
```

Can someone help me on this? thanks!

my conda info is
```
active environment : None
       user config file : /home/lili/.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : /opt/conda  (read only)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /opt/conda/pkgs
                          /home/lili/.conda/pkgs
       envs directories : /home/lili/.conda/envs
                          /opt/conda/envs
               platform : linux-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Linux/3.10.0-862.9.1.el7.x86_64 rhel/7.5 glibc/2.17
                UID:GID : 32055:32055
             netrc file : None
           offline mode : False
```

**Comment by licode** [comment]
I think the issue should be moved here. https://github.com/conda-forge/pygobject-feedstock/issues/9
