### ISSUE TITLE
conda-build fails with pyhamcrest-1.9.0-py_2.tar.bz2

### ISSUE THREAD

**Issue by eddy-ojb** [conda/conda-build#3141]
Hi,

conda-build repeatadly fails to unzip the pyhamcrest packages. I have tried on mulitple occasions two different versions and for different architectures. Although this is not necessarily an issue with conda-build but with the package itself, the latest releases of conda-build are not suitable in providing feedback to the command line user. For instance, I could not debug it was pyhamcrest giving me the issue until I regressed back to conda-build=3.10. The traceback for all tried conda-builds is:

```
Traceback (most recent call last):
  File "C:\Users\TS127TT\AppData\Local\Continuum\anaconda3\Scripts\conda-index-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\TS127TT\AppData\Local\Continuum\anaconda3\lib\site-packages\conda_build\cli\main_index.py", line 75, in main
    return execute(sys.argv[1:])
  File "C:\Users\TS127TT\AppData\Local\Continuum\anaconda3\lib\site-packages\conda_build\cli\main_index.py", line 71, in execute
    channel_name=args.channel_name)
  File "C:\Users\TS127TT\AppData\Local\Continuum\anaconda3\lib\site-packages\conda_build\api.py", line 386, in update_index
    locking=config.locking, timeout=config.timeout, channel_name=channel_name)
  File "C:\Users\TS127TT\AppData\Local\Continuum\anaconda3\lib\site-packages\conda_build\index.py", line 147, in update_index
    channel_name)
  File "C:\Users\TS127TT\AppData\Local\Continuum\anaconda3\lib\site-packages\conda_build\index.py", line 223, in update_subdir_index
    path, lock=lock, locking=locking, timeout=timeout
  File "C:\Users\TS127TT\AppData\Local\Continuum\anaconda3\lib\site-packages\conda_build\index.py", line 288, in _read_index_tar
    with tarfile.open(tar_path) as t:
  File "C:\Users\TS127TT\AppData\Local\Continuum\anaconda3\lib\tarfile.py", line 1573, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

```

which is useless. However in 3.10 the preceding message was:

```updating: `pyhamcrest-1.9.0-py_2.tar.bz2```

Handy.

I understand that in conda-build=3.14 you now have a progress bar when indexing. The part where I use conda-build has given me a lot of grief over the last couple of years. Moving forward, please could a debug mode be provided, or an option for more detailed information as per 3.10? Developers probably do not want a progress bar but want to know specifically what packages have been indexed.

**Comment by msarahan** [comment]
That seems like a corrupt tarball.  It's strange that earlier conda-build versions would work.

Conda-build does have a debug mode and a verbose mode.  These may differ between subcommands.  For example, the build command has --debug, where the index command has --verbose.

```
usage: conda-build [-h] [-V] [-n] [--output] [--python PYTHON] [--perl PERL]
                   [--numpy NUMPY] [--R R_BASE] [--lua LUA]
                   [--bootstrap BOOTSTRAP]
                   [--append-file APPEND_SECTIONS_FILE]
                   [--clobber-file CLOBBER_SECTIONS_FILE]
                   [-m VARIANT_CONFIG_FILES] [-e EXCLUSIVE_CONFIG_FILES]
                   [--old-build-string] [--check] [--no-anaconda-upload]
                   [--no-include-recipe] [-s] [-t] [--no-test] [-b] [-p]
                   [--skip-existing] [--keep-old-work] [--dirty] [-q]
                   [--debug] [--token TOKEN] [--user USER] [--label LABELS]
                   [--no-force-upload] [--password PASSWORD] [--sign SIGN]
                   [--sign-with SIGN_WITH] [--identity IDENTITY]
                   [--config-file CONFIG_FILE] [--repository REPOSITORY]
                   [--no-activate] [--no-build-id] [--croot CROOT] [--verify]
                   [--output-folder OUTPUT_FOLDER]
                   [--no-prefix-length-fallback] [--prefix-length-fallback]
                   [--prefix-length _PREFIX_LENGTH] [--no-locking]
                   [--no-remove-work-dir] [--error-overlinking]
                   [--no-error-overlinking] [--long-test-prefix]
                   [--no-long-test-prefix] [--keep-going]
                   [--cache-dir CACHE_DIR] [--no-copy-test-source-files]
                   [--merge-build-host] [--stats-file STATS_FILE]
                   [--extra-deps EXTRA_DEPS [EXTRA_DEPS ...]] [-c CHANNEL]
                   [--override-channels]
                   RECIPE_PATH [RECIPE_PATH ...]

Tool for building conda packages. A conda package is a binary tarball
containing system-level libraries, Python modules, executable programs, or
other components. conda keeps track of dependencies between packages and
platform specifics, making it simple to create working environments from
different sets of packages.

positional arguments:
  RECIPE_PATH           Path to recipe directory. Pass 'purge' here to clean
                        the work and test intermediates.

optional arguments:
  -h, --help            Show this help message and exit.
  -V, --version         Show the conda-build version number and exit.
  -n, --no-source       When templating can't be completed, do not obtain the
                        source to try fill in related template variables.
  --output              Output the conda package filename which would have
                        been created
  --python PYTHON       Set the Python version used by conda build.
  --perl PERL           Set the Perl version used by conda build.
  --numpy NUMPY         Set the NumPy version used by conda build.
  --R R_BASE            Set the R version used by conda build.
  --lua LUA             Set the Lua version used by conda build.
  --bootstrap BOOTSTRAP
                        Provide initial configuration in addition to recipe.
                        Can be a path to or name of an environment, which will
                        be emulated in the package.
  --append-file APPEND_SECTIONS_FILE
                        Append data in meta.yaml with fields from this file.
                        Jinja2 is not done on appended fields
  --clobber-file CLOBBER_SECTIONS_FILE
                        Clobber data in meta.yaml with fields from this file.
                        Jinja2 is not done on clobbered fields.
  -m VARIANT_CONFIG_FILES, --variant-config-files VARIANT_CONFIG_FILES
                        Additional variant config files to add. These yaml
                        files can contain keys such as `c_compiler` and
                        `target_platform` to form a build matrix.
  -e EXCLUSIVE_CONFIG_FILES, --exclusive-config-files EXCLUSIVE_CONFIG_FILES, --exclusive-config-file EXCLUSIVE_CONFIG_FILES
                        Exclusive variant config files to add. Providing files
                        here disables searching in your home directory and in
                        cwd. The files specified here come at the start of the
                        order, as opposed to the end with --variant-config-
                        files. Any config files in recipes and any config
                        files specified with --variant-config-files will
                        override values from these files.
  --old-build-string    Disable hash additions to filenames to distinguish
                        package variants from one another. NOTE: any filename
                        collisions are yours to handle. Any variants with
                        overlapping names within a build will clobber each
                        other.
  --check               Only check (validate) the recipe.
  --no-anaconda-upload  Do not ask to upload the package to anaconda.org.
  --no-include-recipe   Don't include the recipe inside the built package.
  -s, --source          Only obtain the source (but don't build).
  -t, --test            Test package (assumes package is already built).
                        RECIPE_DIR argument can be either recipe directory, in
                        which case source download may be necessary to resolve
                        package version, or path to built package .tar.bz2
                        file, in which case no source is necessary.
  --no-test             Do not test the package.
  -b, --build-only      Only run the build, without any post processing or
                        testing. Implies --no-test and --no-anaconda-upload.
  -p, --post            Run the post-build logic. Implies --no-test and --no-
                        anaconda-upload.
  --skip-existing       Skip recipes for which there already exists an
                        existing build (locally or in the channels).
  --keep-old-work       Do not remove anything from environment, even after
                        successful build and test.
  --dirty               Do not remove work directory or _build environment, to
                        speed up debugging. Does not apply patches or download
                        source.
  -q, --quiet           do not display progress bar
  --debug               Show debug output from source checkouts and conda
  --token TOKEN         Token to pass through to anaconda upload
  --user USER           User/organization to upload packages to on
                        anaconda.org or pypi
  --label LABELS        Label argument to pass through to anaconda upload
  --no-force-upload     Disable force upload to anaconda.org, preventing
                        overwriting any existing packages
  --no-activate         do not activate the build and test envs; just prepend
                        to PATH
  --no-build-id         do not generate unique build folder names. Use if
                        having issues with paths being too long.
  --croot CROOT         Build root folder. Equivalent to CONDA_BLD_PATH, but
                        applies only to this call of conda-build.
  --verify              do not run verification on recipes or packages when
                        building
  --output-folder OUTPUT_FOLDER
                        folder to dump output package to. Package are moved
                        here if build or test succeeds. Destination folder
                        must exist prior to using this.
  --no-prefix-length-fallback
                        Disable fallback to older 80 character prefix length
                        if environment creation fails due to insufficient
                        prefix length in dependency packages
  --prefix-length-fallback
                        Disable fallback to older 80 character prefix length
                        if environment creation fails due to insufficient
                        prefix length in dependency packages
  --prefix-length _PREFIX_LENGTH
                        length of build prefix. For packages with binaries
                        that embed the path, this is critical to ensuring that
                        your package can run as many places as possible.
                        Notethat this value can be altered by the OS below
                        conda-build (e.g. encrypted filesystems on Linux), and
                        you should prefer to set --croot to a non-encrypted
                        location instead, so that you maintain a known prefix
                        length.
  --no-locking          Disable locking, to avoid unresolved race condition
                        issues. Unsafe to run multiple builds at once on one
                        system with this set.
  --no-remove-work-dir  Disable removal of the work dir before testing. Be
                        careful using this option, as you package may depend
                        on files that are not included in the package, and may
                        pass tests, but ultimately fail on installed systems.
  --error-overlinking   Enable error when shared libraries from transitive
                        dependencies are directly linked to any executables or
                        shared libraries in built packages. This is disabled
                        by default, but will be enabled by default in conda-
                        build 4.0.
  --no-error-overlinking
                        Disable error when shared libraries from transitive
                        dependencies are directly linked to any executables or
                        shared libraries in built packages. This is currently
                        the default behavior, but will change in conda-build
                        4.0.
  --long-test-prefix    Use a long prefix for the test prefix, as well as the
                        build prefix. Affects only Linux and Mac. Prefix
                        length matches the --prefix-length flag. This is on by
                        default in conda-build 3.0+
  --no-long-test-prefix
                        Do not use a long prefix for the test prefix, as well
                        as the build prefix. Affects only Linux and Mac.
                        Prefix length matches the --prefix-length flag.
  --keep-going, -k      When running tests, keep going after each failure.
                        Default is to stop on the first failure.
  --cache-dir CACHE_DIR
                        Path to store the source files (archives, git clones,
                        etc.) during the build.
  --no-copy-test-source-files
                        Disables copying the files necessary for testing the
                        package into the info/test folder. Passing this
                        argument means it may not be possible to test the
                        package without internet access. There is also a
                        danger that the source archive(s) containing the files
                        could become unavailable sometime in the future.
  --merge-build-host    Merge the build and host directories, even when host
                        section or compiler jinja2 is present
  --stats-file STATS_FILE
                        File path to save build statistics to. Stats are in
                        JSON format
  --extra-deps EXTRA_DEPS [EXTRA_DEPS ...]
                        Extra dependencies to add to all environment creation
                        steps. This is only enabled for testing with the -t or
                        --test flag. Change meta.yaml or use templates
                        otherwise.
  -c CHANNEL, --channel CHANNEL
                        Additional channel to search for packages. These are
                        URLs searched in the order they are given (including
                        file:// for local directories). Then, the defaults or
                        channels from .condarc are searched (unless
                        --override-channels is given). You can use 'defaults'
                        to get the default packages for conda, and 'system' to
                        get the system packages, which also takes .condarc
                        into account. You can also use any name and the
                        .condarc channel_alias value will be prepended. The
                        default channel_alias is http://conda.anaconda.org/.
  --override-channels   Do not search default or .condarc channels. Requires
                        --channel.

PyPI upload parameters (twine):
  --password PASSWORD   password to use when uploading packages to pypi
  --sign SIGN           sign files when uploading to pypi
  --sign-with SIGN_WITH
                        program to use to sign files when uploading to pypi
  --identity IDENTITY   GPG identity to use to sign files when uploading to
                        pypi
  --config-file CONFIG_FILE
                        path to .pypirc file to use when uploading to pypi
  --repository REPOSITORY, -r REPOSITORY
                        PyPI repository to upload to
```

```
conda index -h
cusage: conda-index [-h] [-c] [-n CHANNEL_NAME] [-s SUBDIR] [-t THREADS]
                   [-p PATCH_GENERATOR]
                   [--hotfix-source-repo HOTFIX_SOURCE_REPO] [--verbose]
                   [--no-progress]
                   [dir [dir ...]]

Update package index metadata files in given directories.

Options:

positional arguments:
  dir                   Directory that contains an index to be updated.

optional arguments:
  -h, --help            Show this help message and exit.
  -c, --check-md5       Use hash values instead of file modification times for
                        determining if a package's metadata needs to be
                        updated.
  -n CHANNEL_NAME, --channel-name CHANNEL_NAME
                        Customize the channel name listed in each channel's
                        index.html.
  -s SUBDIR, --subdir SUBDIR
                        Optional. The subdir to index. Can be given multiple
                        times. If not provided, will default to all of
                        linux-64, linux-32, linux-ppc64le, linux-armv6l,
                        linux-armv7l, linux-aarch64, win-64, win-32, osx-64,
                        zos-z, noarch. If provided, will not create
                        channeldata.json for the channel.
  -t THREADS, --threads THREADS
  -p PATCH_GENERATOR, --patch-generator PATCH_GENERATOR
                        Path to Python file that outputs metadata patch
                        instructions
  --hotfix-source-repo HOTFIX_SOURCE_REPO
                        URL of git repo that hosts your metadata patch
                        instructions
  --verbose             show extra debugging info
  --no-progress         Hide progress bars
```

Keep in mind that conda-build is an open-source project, and we're very open to community contributions.  If you have trouble with something, feel free to improve it.  Our efforts on it serve our needs of the tool, and we don't have much time to make the tool what other people want it to be.

**Comment by msarahan** [comment]
There's more output now when packages are corrupt.  Closing.

**Comment by eddy-ojb** [comment]
On your previous point on community contributions, I am super appreciative of the awesome work you guys are doing and am keen to help out in the future. There are a couple of things i want to help out with, like storing of passwords in plain text in corporate settings which is a massive no no from me but i appreciate it isnt trivial. I currently have my head stuck in another couple of projects at the moment but will get stuck in when i can.

**Comment by msarahan** [comment]
Great!  We'll look forward to hearing more from you in the future.  Let us know if you need help getting started.

**Comment by eddy-ojb** [comment]
I know this specific issue is closed but more broadly, are you able to direct me as to where I should be reporting corrupt conda files? Would you prefer me to open a separate issue each time? I am not sure where the responsibility lies as there is no contact link for the upload authors.

In my case, I tried to use the [m2w64-gcc-libgfortran: 5.3.0-6,](https://anaconda.org/msys2/m2w64-gcc-libgfortran) which I believe Jupyter Notebook requires on Windows, but this is corrupt when I go to index it.

**Comment by msarahan** [comment]
Corrupt packages are almost always a client problem.  If you download it multiple times, and it always comes out with the same sha, and is always corrupt, then maybe it's a problem on our side.  The burden of proof here is on you, though, and it is more than just "I tried to use this once and it didn't work."
