### ISSUE TITLE
3.14.x test gives 404 for run dependencies on private channels

### ISSUE THREAD

**Issue by s22chan** [conda/conda-build#3146]
### Actual Behavior

For a `meta.yaml` that requires a private package:
```yaml
requirements:
  run:
    - private-pkg
```

conda build results in 

```
The following NEW packages will be INSTALLED:
...
    private-pkg:                0.11.4-py27h6bb024c_0             private-channel
...
Traceback (most recent call last):
  File "/root/anaconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 424, in main
    execute(sys.argv[1:])
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 415, in execute
    verify=args.verify)
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 201, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 2199, in build_tree
    test(pkg, config=metadata.config.copy(), stats=stats)
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1955, in test
    is_conda=metadata.name() == 'conda')
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/environ.py", line 854, in create_env
    execute_actions(actions, index, verbose=config.debug)
  File "/root/anaconda/lib/python2.7/site-packages/conda/common/io.py", line 46, in decorated
    return f(*args, **kwds)
  File "/root/anaconda/lib/python2.7/site-packages/conda/plan.py", line 390, in execute_actions
    execute_instructions(plan, index, verbose)
  File "/root/anaconda/lib/python2.7/site-packages/conda/plan.py", line 600, in execute_instructions
    cmd(state, arg)
  File "/root/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 64, in PROGRESSIVEFETCHEXTRACT_CMD
    progressive_fetch_extract.execute()
  File "/root/anaconda/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 605, in execute
    raise CondaMultiError(exceptions)
conda.CondaMultiError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/private-channel/linux-64/private-pkg-0.11.4-py27h6bb024c_0.tar.bz2>
Elapsed: 00:00.093158
CF-RAY: 459d172a3d6757a1-IAD

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

`conda-build=3.13.x` is fine.

### Expected Behavior

private pkgs in test requirements respect the anaconda token as in prior versions.

### Steps to Reproduce

make a private channel and setup a pkg as above.

##### `Output of conda info`
```
     active environment : base
    active env location : /root/anaconda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.5.11
    conda-build version : 3.14.4
         python version : 2.7.15.final.0
       base environment : /root/anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/private-channel/linux-64
                          https://conda.anaconda.org/private-channel/noarch
          package cache : /root/anaconda/pkgs
                          /root/.conda/pkgs
       envs directories : /root/anaconda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/2.7.15 Linux/4.4.0-134-generic debian/9 glibc/2.24
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
Update conda-build.  3.14.4 is the current version.

**Comment by s22chan** [comment]
This was me trying to bisect the version that was broken. 3.14.0-3.14.4 is still broken.

**Comment by msarahan** [comment]
Sorry, that was close to another unrelated issue.  I'll look into why private channel tokens are no longer being used correctly.
