### ISSUE TITLE
`conda index -s` fails with TypeError

### ISSUE THREAD

**Issue by chenghlee** [conda/conda-build#3173]
### Expected Behavior

`conda index -s` should generate and/or update `index.html`, `repodata.json`, etc. in the target subdirectories.

### Actual Behavior

The application dies with the following error:
```
Traceback (most recent call last):
  File "/home/clee/.miniconda3-x86_64/bin/conda-index", line 11, in <module>
    sys.exit(main())
  File "/home/clee/.miniconda3-x86_64/lib/python3.6/site-packages/conda_build/cli/main_index.py", line 75, in main
    return execute(sys.argv[1:])
  File "/home/clee/.miniconda3-x86_64/lib/python3.6/site-packages/conda_build/cli/main_index.py", line 71, in execute
    verbose=args.verbose, progress=args.progress, hotfix_source_repo=args.hotfix_source_repo)
  File "/home/clee/.miniconda3-x86_64/lib/python3.6/site-packages/conda_build/api.py", line 386, in update_index
    threads=threads, verbose=verbose, progress=progress)
  File "/home/clee/.miniconda3-x86_64/lib/python3.6/site-packages/conda_build/index.py", line 251, in update_subdir_index
    subdir, verbose=verbose, progress=progress)
  File "/home/clee/.miniconda3-x86_64/lib/python3.6/site-packages/conda_build/index.py", line 850, in index_subdir
    subdir_path = join(self.channel_root, subdir)
  File "/home/clee/.miniconda3-x86_64/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/clee/.miniconda3-x86_64/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'list'
```

### Steps to Reproduce

1. If needed, create the target subdirectories: `mkdir -p noarch linux-64`.
1. Run `conda index -s noarch -s linux-64` or `conda index -s noarch`.

Note that the same error also occurs for the non-empty directories.

### Output of `conda info`

```
     active environment : None
       user config file : /home/clee/.condarc
 populated config files : /home/clee/.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.6.5.final.0
       base environment : /home/clee/.miniconda3-x86_64  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/clee/.miniconda3-x86_64/pkgs
                          /home/clee/.conda/pkgs
       envs directories : /home/clee/.miniconda3-x86_64/envs
                          /home/clee/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.5 Linux/4.15.0-34-generic ubuntu/18.04 glibc/2.27
                UID:GID : 7001:7000
             netrc file : None
           offline mode : False
```

**Comment by chenghlee** [comment]
Is the plan to remove support for indexing individual subdirectories? If so, please feel free to close this ticket.

(We ran across this issue because our CI system currently assumes `conda index`'s old behavior and indexes each subdirectory as builds for a platform complete. However, adapting our system to run `conda index` just once after _all_ platform builds are complete is pretty easy, so this is by no means a major issue.)

**Comment by msarahan** [comment]
The support should be there, but it should be something of a speed optimization only, not commonly used.  This is a bug that needs to be fixed.
