### ISSUE TITLE
KeyError: 0

### ISSUE THREAD

**Issue by sscherfke** [conda/conda-build#3218]
### Actual Behavior

`conda index <channel-path>` fails with an exception:
```console
$ ~/conda/bin/conda index stable
Subdir: noarch: 100%|████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  2.00s/it]
Traceback (most recent call last):: 0it [00:00, ?it/s].bz2: 100%|██████████████████| 12/12 [00:01<00:00,  6.70it/s]
  File "/home/user/conda/lib/python3.6/site-packages/conda_build/index.py", line 346, in _clear_newline_chars
    record[field_name] = record[field_name].strip().replace('\n', ' ')
AttributeError: 'dict' object has no attribute 'strip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/conda/bin/conda-index", line 11, in <module>
    sys.exit(main())
  File "/home/user/conda/lib/python3.6/site-packages/conda_build/cli/main_index.py", line 75, in main
    return execute(sys.argv[1:])
  File "/home/user/conda/lib/python3.6/site-packages/conda_build/cli/main_index.py", line 71, in execute
    verbose=args.verbose, progress=args.progress, hotfix_source_repo=args.hotfix_source_repo)
  File "/home/user/conda/lib/python3.6/site-packages/conda_build/api.py", line 390, in update_index
    hotfix_source_repo=hotfix_source_repo)
  File "/home/user/conda/lib/python3.6/site-packages/conda_build/index.py", line 273, in update_index
    patch_generator=patch_generator, verbose=verbose, progress=progress, hotfix_source_repo=hotfix_source_repo)
  File "/home/user/conda/lib/python3.6/site-packages/conda_build/index.py", line 844, in index
    channel_data, package_mtimes = self._build_channeldata(subdirs, reference_packages)
  File "/home/user/conda/lib/python3.6/site-packages/conda_build/index.py", line 1188, in _build_channeldata
    data = future.result()
  File "/home/user/conda/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/user/conda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/user/conda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/conda/lib/python3.6/site-packages/conda_build/index.py", line 1104, in _load_all_from_cache
    _clear_newline_chars(data, 'summary')
  File "/home/user/conda/lib/python3.6/site-packages/conda_build/index.py", line 349, in _clear_newline_chars
    record[field_name] = record[field_name][0].strip().replace('\n', ' ')
KeyError: 0
```

### Expected Behavior
 
`conda index <channel-path>` indexes the channel

### Steps to Reproduce

It does not fail deterministically, but when it fails once, it will continue to fail for that channel.

##### `Output of conda info`

```
     active environment : None
            shell level : 0
       user config file : /home/user/.condarc
 populated config files : /home/user/conda/.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.6.6.final.0
       base environment : /home/user/conda  (writable)
           channel URLs : http://.../conda/stable/linux-64
                          http://.../conda/stable/noarch
          package cache : /home/user/conda/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/conda/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.6.6 Linux/3.10.0-327.18.2.el7.x86_64centos/7 glib
c/2.17
                UID:GID : 500:500
             netrc file : None
           offline mode : False

```

**Comment by sscherfke** [comment]
The problem still exists and is caused by older packages that have `dict` typed summary in their `meta.yaml`:
```yaml
about:
  summary:
    description: Lorem ipsum ...
```
I know that this is not a valid format but the packages were successfully built with an older version of conda and now cause `conda index` to fail.

**Comment by sscherfke** [comment]
Editing `~/emsconda/lib/python3.7/site-packages/conda_build/index.py:353` like this is a workaround:
```python
        except AttributeError:
            # sometimes description gets added as a list instead of just a string
            try:
                record[field_name] = record[field_name][0].strip().replace('\n', ' ')
            except KeyError:
                record[field_name] = record[field_name]['description'].strip().replace('\n', ' ')
```

**Comment by analog-cbarber** [comment]
This can also happen if you have a colon in your package description in your setup.py and use jinja templates to copy the description into your recipe:

```python
# setup.py
setup(...
   description='Warning: this will break conda build!'
)
```

```yaml
# meta.yaml
...
about:
  summary: {{ data['description'] }}
```

Even worse, this stays in the build cache and prevents further builds from working
even if you fix the summary string. I had to grovel the `conda-bld/.cache` directory
and manually clean up the broken package.
