### ISSUE TITLE
conda build fails in miniconda root env but works in anaconda root env

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda-build#324]
The following build error occurred while using a miniconda installation.  If I switch to a anaconda installation the build works.

```
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/fast/pyHome/o611420/._f3build/miniconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/fast/pyHome/o611420/._f3build/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 110, in main
    args_func(args, p)
  File "/fast/pyHome/o611420/._f3build/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 312, in args_func
    args.func(args, p)
  File "/fast/pyHome/o611420/._f3build/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 272, in execute
    build.build(m, verbose=not args.quiet, post=post)
  File "/fast/pyHome/o611420/._f3build/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 335, in build
    print("BUILD START:", m.dist())
  File "/fast/pyHome/o611420/._f3build/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 369, in dist
    return '%s-%s-%s' % (self.name(), self.version(), self.build_id())
  File "/fast/pyHome/o611420/._f3build/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 365, in build_id
    res.append('%d' % self.build_number())
  File "/fast/pyHome/o611420/._f3build/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 311, in build_number
    return int(self.get_value('build/number', 0))
TypeError: int() argument must be a string or a number, not 'NoneType'

o611420@vsin3d1073 /fast/pyHome/o611420/._f3build/cbbf3cv3lib/conda.recipe




o611420@vsin3d1073 /fast/pyHome/o611420/._f3build/cbbf3cv3lib/conda.recipe
          $ conda info
Current conda install:

             platform : linux-64
        conda version : 3.8.4
  conda-build version : 1.10.1
       python version : 2.7.9.final.0
     requests version : 2.5.1
     root environment : /fast/pyHome/o611420/._f3build/miniconda  (writable)
  default environment : /fast/pyHome/o611420/._f3build/miniconda
     envs directories : /fast/pyHome/o611420/._f3build/miniconda/envs
        package cache : /fast/pyHome/o611420/._f3build/miniconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/linux-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False


o611420@vsin3d1073 /fast/pyHome/o611420/._f3build/cbbf3cv3lib/conda.recipe
          $ conda list
# packages in environment at /fast/pyHome/o611420/._f3build/miniconda:
#
conda                     3.8.4                    py27_0
conda-build               1.10.1                   py27_0
conda-env                 2.1.0                    py27_0
jinja2                    2.7.3                    py27_1
markupsafe                0.23                     py27_0
openssl                   1.0.1k                        0
patchelf                  0.6                           0
pycosat                   0.6.1                    py27_0
python                    2.7.9                         1
pyyaml                    3.11                     py27_0
readline                  6.2                           2
requests                  2.5.1                    py27_0
setuptools                12.0.5                   py27_0
sqlite                    3.8.4.1                       0
system                    5.8                           1
tk                        8.5.15                        0
yaml                      0.1.4                         0
zlib                      1.2.8                         0

o611420@vsin3d1073 /fast/pyHome/o611420/._f3build/cbbf3cv3lib/conda.recipe
          $
```

**Comment by bkreider** [comment]
@joelhullcio The fact that the code is doing `int(self.get_value('build/number', 0))` and you are still getting a NoneType, makes me suspicious that the yaml is getting parsed in a way that it thinks it is None.  

Can you remove the build number completely from the meta.yaml and see if that fixes it or reveals a new problem?

**Comment by joelhullcio** [comment]
Brad
We are using versioneer for this package, so the build number in the meta.yaml looks like this

build:
  number: {{ environ.get(‘GIT_DESCRIBE_NUMBER’, 0) }}
  string: {{ environ.get(‘GIT_BUILD_STR’, ‘’) }}

I changed the version number to be this and it worked!

build:
  number: 99
  string: {{ environ.get(‘GIT_BUILD_STR’, ‘’) }}

The weird things is the original meta.yaml works fine with our anaconda root env on the same box???

Any other ideas?

Thanks.

**Comment by tswicegood** [comment]
You need to set the describe number to be an int. Aaron actually just fixed an issued yesterday in master that solves the underlying issue here. A work around is to check for an empty string, then use 0.

**Comment by tswicegood** [comment]
Back at my computer now, cc @asmeurer

**Comment by asmeurer** [comment]
With the next version, it may be necessary for you to change your meta.yaml to match http://conda.pydata.org/docs/build.html#git-environment-variables (in particular, use `environ.get`).

**Comment by tswicegood** [comment]
@joelhullcio two things: 1) I edited your initial report to get the code block working correctly; 2) did the latest release from @asmeurer fix your issue?  Want to get this closed out if it did.

**Comment by jakirkham** [comment]
BTW, versioneer has been upgraded to 0.14. ( https://pypi.python.org/pypi/versioneer/0.14 ) This applies a very important fix to non-release versions to ensure PEP440 compliance.

**Comment by jakirkham** [comment]
I think this should be closed out. Pretty sure this is working by now or is something still broken @joelhullcio?
