### ISSUE TITLE
Skeleton for rpm broken

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#3244]
I tried to create a conda skeleton for an rpm package "kernel-devel" and build it. I generated it using:

```
conda skeleton rpm --distro=centos6 --architecture=x86_64 kernel-devel
```

That worked fine... then I build it with:

```
conda-build kernel-devel-cos6-x86_64/
```

(pls don't judge me for trying to package kernel-devel, as I'm not even sure it makes sense - but i think it should work anyway)

### Actual Behavior

The build doesnt work:

```
conda-build kernel-devel-cos6-x86_64/
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /root/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /root/conda_build_config.yaml
Attempting to finalize metadata for kernel-devel-cos6-x86_64
INFO:conda_build.metadata:Attempting to finalize metadata for kernel-devel-cos6-x86_64
BUILD START: ['kernel-devel-cos6-x86_64-2.6.32-0.tar.bz2']
Source cache directory is: /root/miniconda3/conda-bld/src_cache
Found source in cache: kernel-devel-2.6.32-754.el6.x86_64_906745681e.rpm
Extracting download
Source cache directory is: /root/miniconda3/conda-bld/src_cache
No hash (md5, sha1, sha256) provided for kernel-2.6.32-754.el6.src.rpm.  Source download forced.  Add hash to recipe to use source cache.
WARNING:conda_build.source:No hash (md5, sha1, sha256) provided for kernel-2.6.32-754.el6.src.rpm.  Source download forced.  Add hash to recipe to use source cache.
Found source in cache: kernel-2.6.32-754.el6.src.rpm
Extracting download
source tree in: /root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541277753796/work
no package supplied
cpio: premature end of archive
Traceback (most recent call last):
  File "/root/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 439, in main
    execute(sys.argv[1:])
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 430, in execute
    verify=args.verify, variants=args.variants)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 201, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 2234, in build_tree
    notest=notest,
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 1471, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/utils.py", line 319, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/utils.py", line 299, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541277753796/work/conda_build.sh']' returned non-zero exit status 1.
```

This is because the rpm is downloaded _and_ extracted by conda. So the binary folder (that is created by the skeleton) does **not** contain the rpm as expected, but it contains the extracted rpm...

### Expected Behavior

It should build just fine...

### Steps to Reproduce

```
conda skeleton rpm --distro=centos6 --architecture=x86_64
conda-build kernel-devel-cos6-x86_64/
```

##### `Output of conda info`

```

```

**Comment by gabm** [comment]
I don't understand that much of all this, but when I have time, I can create a PR if you give me some indications what to do...

**Comment by mingwandroid** [comment]
I believe you need a newer conda-build with this PR applied (maybe you can try it locally?):

https://github.com/conda/conda-build/pull/3221

In particular you need:

https://github.com/conda/conda-build/pull/3221/commits/cb15f3f317553df7107eeb875fd459c259a371c5

**Comment by gabm** [comment]
kinda works...

```
root@e94ce86fb721:~/dev# conda-build kernel-devel-cos6-x86_64/
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /root/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /root/conda_build_config.yaml
Attempting to finalize metadata for kernel-devel-cos6-x86_64
INFO:conda_build.metadata:Attempting to finalize metadata for kernel-devel-cos6-x86_64
BUILD START: ['kernel-devel-cos6-x86_64-2.6.32-0.tar.bz2']
Source cache directory is: /root/miniconda3/conda-bld/src_cache
Found source in cache: kernel-devel-2.6.32-754.el6.x86_64_906745681e.rpm
Extracting download
Source cache directory is: /root/miniconda3/conda-bld/src_cache
No hash (md5, sha1, sha256) provided for kernel-2.6.32-754.el6.src.rpm.  Source download forced.  Add hash to recipe to use source cache.
WARNING:conda_build.source:No hash (md5, sha1, sha256) provided for kernel-2.6.32-754.el6.src.rpm.  Source download forced.  Add hash to recipe to use source cache.
Downloading source to cache: kernel-2.6.32-754.el6.src.rpm
Downloading http://vault.centos.org/6.10/os/Source/SPackages/kernel-2.6.32-754.el6.src.rpm
Success
Extracting download
source tree in: /root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541314781452/work

Resource usage statistics from building kernel-devel-cos6-x86_64:
   Process count: 1
   CPU time: unavailable
   Memory: 2.9M
   Disk usage: 177.6K
   Time elapsed: 0:00:02.2

Packaging kernel-devel-cos6-x86_64
INFO:conda_build.build:Packaging kernel-devel-cos6-x86_64
Packaging kernel-devel-cos6-x86_64-2.6.32-0
INFO:conda_build.build:Packaging kernel-devel-cos6-x86_64-2.6.32-0
number of files: 8347
patchelf: file: /root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541314781452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/x86_64-conda_cos6-linux-gnu/sysroot/usr/src/kernels/2.6.32-754.el6.x86_64/scripts/unifdef
    setting rpath to: $ORIGIN/../../../../../../../lib
patchelf: file: /root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541314781452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/x86_64-conda_cos6-linux-gnu/sysroot/usr/src/kernels/2.6.32-754.el6.x86_64/scripts/conmakehash
    setting rpath to: $ORIGIN/../../../../../../../lib
patchelf: file: /root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541314781452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/x86_64-conda_cos6-linux-gnu/sysroot/usr/src/kernels/2.6.32-754.el6.x86_64/scripts/genksyms/genksyms
    setting rpath to: $ORIGIN/../../../../../../../../lib
patchelf: file: /root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541314781452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/x86_64-conda_cos6-linux-gnu/sysroot/usr/src/kernels/2.6.32-754.el6.x86_64/scripts/selinux/genheaders/genheaders
    setting rpath to: $ORIGIN/../../../../../../../../../lib
patchelf: file: /root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541314781452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/x86_64-conda_cos6-linux-gnu/sysroot/usr/src/kernels/2.6.32-754.el6.x86_64/scripts/mod/mk_elfconfig
    setting rpath to: $ORIGIN/../../../../../../../../lib
patchelf: file: /root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541314781452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/x86_64-conda_cos6-linux-gnu/sysroot/usr/src/kernels/2.6.32-754.el6.x86_64/scripts/mod/mod-extract
    setting rpath to: $ORIGIN/../../../../../../../../lib
patchelf: file: /root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541314781452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/x86_64-conda_cos6-linux-gnu/sysroot/usr/src/kernels/2.6.32-754.el6.x86_64/scripts/pnmtologo
    setting rpath to: $ORIGIN/../../../../../../../lib
patchelf: file: /root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541314781452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/x86_64-conda_cos6-linux-gnu/sysroot/usr/src/kernels/2.6.32-754.el6.x86_64/scripts/kallsyms
    setting rpath to: $ORIGIN/../../../../../../../lib
patchelf: file: /root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541314781452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/x86_64-conda_cos6-linux-gnu/sysroot/usr/src/kernels/2.6.32-754.el6.x86_64/scripts/basic/docproc
    setting rpath to: $ORIGIN/../../../../../../../../lib
patchelf: file: /root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541314781452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/x86_64-conda_cos6-linux-gnu/sysroot/usr/src/kernels/2.6.32-754.el6.x86_64/scripts/basic/fixdep
    setting rpath to: $ORIGIN/../../../../../../../../lib
patchelf: file: /root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541314781452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/x86_64-conda_cos6-linux-gnu/sysroot/usr/src/kernels/2.6.32-754.el6.x86_64/scripts/selinux/mdp/mdp
    setting rpath to: $ORIGIN/../../../../../../../../../lib
patchelf: file: /root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541314781452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/x86_64-conda_cos6-linux-gnu/sysroot/usr/src/kernels/2.6.32-754.el6.x86_64/scripts/mod/modpost
    setting rpath to: $ORIGIN/../../../../../../../../lib
patchelf: file: /root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541314781452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/x86_64-conda_cos6-linux-gnu/sysroot/usr/src/kernels/2.6.32-754.el6.x86_64/scripts/kconfig/conf
    setting rpath to: $ORIGIN/../../../../../../../../lib
patchelf: file: /root/miniconda3/conda-bld/kernel-devel-cos6-x86_64_1541314781452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/x86_64-conda_cos6-linux-gnu/sysroot/usr/src/kernels/2.6.32-754.el6.x86_64/scripts/basic/hash
    setting rpath to: $ORIGIN/../../../../../../../../lib
Traceback (most recent call last):
  File "/root/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 453, in main
    execute(sys.argv[1:])
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 444, in execute
    verify=args.verify, variants=args.variants)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 201, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 2275, in build_tree
    notest=notest,
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 1654, in build
    newly_built_packages = bundlers[output_d.get('type', 'conda')](output_d, m, env, stats)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 961, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 823, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/post.py", line 923, in post_build
    check_overlinking(m, files)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/post.py", line 863, in check_overlinking
    files)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/post.py", line 524, in check_overlinking_impl
    if packages[-1] in lib_packages:
IndexError: list index out of range
```

**Comment by gabm** [comment]
It seems packages was empty, just disabled the test here: https://github.com/conda/conda-build/pull/3221/files#diff-60400bbbdb51124a0a8a06ca17ecec5cR524


Now I get: 

```
Traceback (most recent call last):
  File "/root/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 453, in main
    execute(sys.argv[1:])
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 444, in execute
    verify=args.verify, variants=args.variants)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 201, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 2275, in build_tree
    notest=notest,
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 1654, in build
    newly_built_packages = bundlers[output_d.get('type', 'conda')](output_d, m, env, stats)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 961, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 823, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/post.py", line 923, in post_build
    check_overlinking(m, files)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/post.py", line 863, in check_overlinking
    files)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/post.py", line 621, in check_overlinking_impl
    envroot=run_prefix)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 586, in __call__
    value = self.func(*args, **kw)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 615, in get_linkages_memoized
    recurse=recurse, sysroot=sysroot, envroot=envroot, arch=arch)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 403, in get_linkages
    sysroot=sysroot, envroot=envroot, arch=arch)
  File "/root/miniconda3/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 326, in inspect_linkages_lief
    binary = lief.parse(filename)
NameError: name 'lief' is not defined
```

**Comment by mingwandroid** [comment]
Yeah I need to ensure the non-lief cases work. Or we make it a hard dep..  If you cherry pick the single commit though it should be ok.

**Comment by gabm** [comment]
yep.. the non-lief cases don't work yet... I'll try that..

**Comment by kmpaul** [comment]
@gabm Sort of out of the blue, here, but did you ever get your `kernel-devel` package working?  It doesn't look like there is a conda `kernel-devel` package available for install, not on conda-forge, so I was just wondering if you hit a roadblock on this and couldn't do it, or if you were planning to do it "some day."

**Comment by gabm** [comment]
honestly, I don't remember anymore :/ I think I got it to work eventually but I can't tell you anymore.. sorry

**Comment by kmpaul** [comment]
@gabm No worries.  I was just wondering if you were in the middle of something that I could help with, or if this was something that I would need to start from scratch.  I didn't want to step on anyone's toes.

**Comment by gabm** [comment]
you didn't, no offense taken :)

**Comment by kmpaul** [comment]
Turns out I probably don't need this.  I can specify `kernel-devel` in the `yum_requirements.txt` file and it achieves the same thing.

**Comment by kmpaul** [comment]
...Well, not exactly the *same* thing, but it's close enough for my needs.
