### ISSUE TITLE
Unsatisfiable dependency of "os" module during conda build

### ISSUE THREAD

**Issue by caozhichongchong** [conda/conda-build#3261]
version
conda 4.5.11
python 3.7 and 2.7

I'm trying to build and upload a package, but it always raises DependencyNeedsBuildingError (exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: **Unsatisfiable dependencies for platform osx-64: {'os'}**

I tried:
conda-build .
conda-build -c conda-forge .
conda-build --python 3.7 -c conda-forge .

**I attached my meta.yaml here.**

{% set name = "arg_ranker" %}
{% set version = "1.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "1d25f8b15b0e66570f30c4758d299367232ad86c83c46da2a9281461ec28c3b7" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'
  git_rev: v1.0
  git_url: https://github.com/caozhichongchong/arg_ranker.git
  folder: arg_ranker

build:
  number: 0
  entry_points:
    - arg_ranker = arg_ranker.__main__:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - pandas

test:
  imports:
    - arg_ranker
  commands:
    - arg_ranker --help
  requires:
    - pytest

about:
  home: https://github.com/caozhichongchong/arg_ranker
  license: MIT
  license_family: MIT
  license_file: 'LICENSE.txt'
  summary: Ranking the risk of antibiotic resistance for metagenomes
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''

**And the full error track here:**
No numpy version specified in conda_build_config.yaml. Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml. Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for arg_ranker
INFO:conda_build.metadata:Attempting to finalize metadata for arg_ranker
Solving environment: ...working... done
Solving environment: ...working... done
BUILD START: ['arg_ranker-1.0-py37_0.tar.bz2']
Solving environment: ...working... done

Package Plan
environment location: /Users/caozhichongchong/miniconda2/envs/py37/conda-bld/arg_ranker_1542319520726/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol
The following NEW packages will be INSTALLED:

ca-certificates: 2018.10.15-ha4d7672_0 conda-forge
certifi:         2018.10.15-py37_1000  conda-forge
libffi:          3.2.1-hfc679d8_5      conda-forge
ncurses:         6.1-hfc679d8_1        conda-forge
openssl:         1.0.2p-h470a237_1     conda-forge
pip:             18.1-py37_1000        conda-forge
python:          3.7.1-h46c1a51_0      conda-forge
readline:        7.0-haf1bffa_1        conda-forge
setuptools:      40.6.2-py37_0         conda-forge
sqlite:          3.25.3-hb1c47c0_0     conda-forge
tk:              8.6.8-ha92aebf_0      conda-forge
wheel:           0.32.2-py37_0         conda-forge
xz:              5.2.4-h470a237_1      conda-forge
zlib:            1.2.11-h470a237_3     conda-forge
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Solving environment: ...working... failed

Leaving build/test directories:
Work:
/Users/caozhichongchong/miniconda2/envs/py37/conda-bld/work
Test:
/Users/caozhichongchong/miniconda2/envs/py37/conda-bld/test_tmp
Leaving build/test environments:
Test:
source activate /Users/caozhichongchong/miniconda2/envs/py37/conda-bld/test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
Build:
source activate /Users/caozhichongchong/miniconda2/envs/py37/conda-bld/_build_env

Traceback (most recent call last):
File "/Users/caozhichongchong/miniconda2/envs/py37/lib/python3.7/site-packages/conda_build/environ.py", line 749, in get_install_actions
actions = install_actions(prefix, index, specs, force=True)
File "/Users/caozhichongchong/miniconda2/envs/py37/lib/python3.7/site-packages/conda/common/io.py", line 46, in decorated
return f(*args, **kwds)
File "/Users/caozhichongchong/miniconda2/envs/py37/lib/python3.7/site-packages/conda/plan.py", line 541, in install_actions
txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
File "/Users/caozhichongchong/miniconda2/envs/py37/lib/python3.7/site-packages/conda/core/solve.py", line 518, in solve_for_transaction
force_remove, force_reinstall)
File "/Users/caozhichongchong/miniconda2/envs/py37/lib/python3.7/site-packages/conda/core/solve.py", line 451, in solve_for_diff
final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
File "/Users/caozhichongchong/miniconda2/envs/py37/lib/python3.7/site-packages/conda/core/solve.py", line 331, in solve_final_state
conflicting_specs = r.get_conflicting_specs(tuple(final_environment_specs))
File "/Users/caozhichongchong/miniconda2/envs/py37/lib/python3.7/site-packages/conda/resolve.py", line 705, in get_conflicting_specs
reduced_index = self.get_reduced_index(specs)
File "/Users/caozhichongchong/miniconda2/envs/py37/lib/python3.7/site-packages/conda/resolve.py", line 254, in get_reduced_index
specs, features = self.verify_specs(specs)
File "/Users/caozhichongchong/miniconda2/envs/py37/lib/python3.7/site-packages/conda/resolve.py", line 172, in verify_specs
raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound:
os

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/Users/caozhichongchong/miniconda2/envs/py37/bin/conda-build", line 11, in 
sys.exit(main())
File "/Users/caozhichongchong/miniconda2/envs/py37/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 439, in main
execute(sys.argv[1:])
File "/Users/caozhichongchong/miniconda2/envs/py37/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 430, in execute
verify=args.verify, variants=args.variants)
File "/Users/caozhichongchong/miniconda2/envs/py37/lib/python3.7/site-packages/conda_build/api.py", line 201, in build
notest=notest, need_source_download=need_source_download, variants=variants)
File "/Users/caozhichongchong/miniconda2/envs/py37/lib/python3.7/site-packages/conda_build/build.py", line 2275, in build_tree
notest=notest,
File "/Users/caozhichongchong/miniconda2/envs/py37/lib/python3.7/site-packages/conda_build/build.py", line 1398, in build
raise e
File "/Users/caozhichongchong/miniconda2/envs/py37/lib/python3.7/site-packages/conda_build/build.py", line 1389, in build
channel_urls=tuple(m.config.channel_urls))
File "/Users/caozhichongchong/miniconda2/envs/py37/lib/python3.7/site-packages/conda_build/environ.py", line 751, in get_install_actions
raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: {'os'}

**Thanks a lot!**

**Comment by msarahan** [comment]
You have cross-posted to https://github.com/conda/conda-docs/issues/637 as well as emailed me personally.  That's very disrespectful of our time.  I'm closing this issue.  You'll need to spend more time looking at other recipes to figure out your problem.  I recommend the docs at https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#source-section - your source section does not look quite right.  You should only have one of (url, git_url).

The OS error looks like something completely unrelated.  There is no "os" dependency listed in your recipe (good, it is a python built-in and should not be a dependency), thus this error reflects some recipe other than the one you've pasted here.  Nothing I see here could cause that error.
