### ISSUE TITLE
bld.bat not found in compiler packages

### ISSUE THREAD

**Issue by peterjc123** [conda/conda-build#3285]
### Actual Behavior

It failed and claimed that `bld.bat` is not found. However, it should not be called since it is a compiler package.

### Expected Behavior

It should build the compiler package and run `install_runtime.bat` defined in the `meta.yaml`.

### Steps to Reproduce

1. Use the package introduced in #2541
2. Install miniconda and `conda install conda-build` (3.17.0 got selected automatically)
2. `conda build vs2017`
3. It fails with the following error:
```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from D:\_work\1\s\conda\vs2017\conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from D:\_work\1\s\conda\vs2017\conda_build_config.yaml
Attempting to finalize metadata for vs2017_runtime
D:\_work\1\s\tmp_conda_3.7_082039\conda\lib\site-packages\conda_build\environ.py:422: UserWarning: The environment variable 'VSDEVCMD_ARGS' is being passed through with value -vcvars_ver=14.11.  If you are splitting build and test phases with --no-test, please ensure that this value is also set similarly at test time.
  UserWarning
INFO:conda_build.metadata:Attempting to finalize metadata for vs2017_runtime
Attempting to finalize metadata for vs2017_win-64
INFO:conda_build.metadata:Attempting to finalize metadata for vs2017_win-64
Attempting to finalize metadata for vc
INFO:conda_build.metadata:Attempting to finalize metadata for vc
Using legacy MSVC compiler setup.  This will be removed in conda-build 4.0. If this recipe does not use a compiler, this message is safe to ignore.  Otherwise, use {{compiler('<language>')}} jinja2 in requirements/build.
WARNING:conda_build.windows:Using legacy MSVC compiler setup.  This will be removed in conda-build 4.0. If this recipe does not use a compiler, this message is safe to ignore.  Otherwise, use {{compiler('<language>')}} jinja2 in requirements/build.
'bld.bat' is not recognized as an internal or external command,
operable program or batch file.
BUILD START: ['vs2017_runtime-15.4.27004.2010-0.tar.bz2', 'vs2017_win-64-15.4.27004.2010-h55c1224_0.tar.bz2', 'vc-14.1-h21ff451_0.tar.bz2']
source tree in: D:\_work\1\s\tmp_conda_3.7_082039\conda\conda-bld\vs2017_1543739001614\work
Rewriting env in output: {'BUILD_PREFIX': 'D:\\_work\\1\\s\\tmp_conda_3.7_082039\\conda\\conda-bld\\vs2017_1543739001614\\_h_env',
 'PREFIX': 'D:\\_work\\1\\s\\tmp_conda_3.7_082039\\conda\\conda-bld\\vs2017_1543739001614\\_h_env',
 'SRC_DIR': 'D:\\_work\\1\\s\\tmp_conda_3.7_082039\\conda\\conda-bld\\vs2017_1543739001614\\work'}
Traceback (most recent call last):
  File "D:\_work\1\s\tmp_conda_3.7_082039\conda\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\_work\1\s\tmp_conda_3.7_082039\conda\lib\site-packages\conda_build\cli\main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "D:\_work\1\s\tmp_conda_3.7_082039\conda\lib\site-packages\conda_build\cli\main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "D:\_work\1\s\tmp_conda_3.7_082039\conda\lib\site-packages\conda_build\api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "D:\_work\1\s\tmp_conda_3.7_082039\conda\lib\site-packages\conda_build\build.py", line 2310, in build_tree
    notest=notest,
  File "D:\_work\1\s\tmp_conda_3.7_082039\conda\lib\site-packages\conda_build\build.py", line 1444, in build
    windows.build(m, build_file, stats=build_stats, provision_only=provision_only)
  File "D:\_work\1\s\tmp_conda_3.7_082039\conda\lib\site-packages\conda_build\windows.py", line 342, in build
    check_call_env(cmd, cwd=m.config.work_dir, stats=stats, rewrite_stdout_env=rewrite_env)
  File "D:\_work\1\s\tmp_conda_3.7_082039\conda\lib\site-packages\conda_build\utils.py", line 374, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "D:\_work\1\s\tmp_conda_3.7_082039\conda\lib\site-packages\conda_build\utils.py", line 354, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['cmd.exe', '/c', 'bld.bat']' returned non-zero exit status 1.
```

##### `Output of conda info`

```
     active environment : base
    active env location : C:\a\w\2\s\windows\conda
            shell level : 1
       user config file : C:\Users\pytorch\.condarc
 populated config files : C:\Users\pytorch\.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : C:\a\w\2\s\windows\conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\a\w\2\s\windows\conda\pkgs
                          C:\Users\pytorch\AppData\Local\conda\conda\pkgs
       envs directories : C:\a\w\2\s\windows\conda\envs
                          C:\Users\pytorch\AppData\Local\conda\conda\envs
                          C:\Users\pytorch\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/2012ServerR2 Windows/6.3.9600
          administrator : True
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
Thanks for reporting.  This came as part of the separation work in #3237.  We'll fix it for the next release.  Hopefully soon, but it'll probably be a few days before we can get to it.
