### ISSUE TITLE
vcvarsall.bat: The syntax of the command is incorrect.

### ISSUE THREAD

**Issue by jschueller** [conda/conda-build#3286]
conda build 3.15.1 errors on windows when calling the vc environement script
I got this error for the lp_solve migration PR: https://github.com/conda-forge/lp_solve-feedstock/pull/8
log: https://ci.appveyor.com/project/conda-forge/lp-solve-feedstock/builds/20723114

```
CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\..\..\VC\vcvarsall.bat" amd64  
The syntax of the command is incorrect.
Traceback (most recent call last):
  File "C:\Miniconda36-x64\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 438, in main
    execute(sys.argv[1:])
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 429, in execute
    verify=args.verify)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\api.py", line 201, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 2204, in build_tree
    notest=notest,
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 1394, in build
    windows.build(m, build_file, stats=build_stats)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\windows.py", line 316, in build
    check_call_env(cmd, cwd=src_dir, stats=stats)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\utils.py", line 313, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\utils.py", line 293, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['cmd.exe', '/c', 'bld.bat']' returned non-zero exit status 1.
```

**Comment by msarahan** [comment]
Sorry, you'll need to figure out a way to update conda-build or figure this out for yourself.  We don't actively support old versions of conda-build.

**Comment by jschueller** [comment]
Ok, but why is it the one used by conda-forge jobs then ? That migration PR is fresh. I see it's used in other jobs without this problem.

**Comment by msarahan** [comment]
Take that up with conda-forge.  This is the conda-build issue tracker.
