### ISSUE TITLE
LIEF error on Windows

### ISSUE THREAD

**Issue by xiaoqiangwang** [conda/conda-build#3287]
I have a project used to build Ok on conda-build 3.6. And now it gives error in a post build check in LIEF module.
Here is the build log of the project on AppVeyor https://ci.appveyor.com/project/xiaoqiangwang/cachannel/build/job/8haogg5ochd2qmh4#L628

**Comment by msarahan** [comment]
Thanks for reporting.  I think we'll need to back off of that new feature for a bit until @mingwandroid is more available.  I'll disable it on Windows and push a new release.

**Comment by marscher** [comment]
I have a similar error but on Linux (no build.sh as well), whereas it tries to invoke nm, which is not present.
https://circleci.com/gh/markovmodel/PyEMMA/621

**Comment by msarahan** [comment]
@marscher for you, I believe the best course of action is to install nm with yum or whatever.  In the long term, we'll package nm and include it as a dep as necessary, but it'll take us some time to do that.

**Comment by marscher** [comment]
OK thanks for the explaination. IMHO it should not fail, if the tools is not installed.

**Comment by jjhelmus** [comment]
`nm` is used to find the exported symbols from static libraries (.a or .lib) on linux and osx in conda-build.  I do not believe this information is currently being used in the over-linking or under-linking checks so it should be safe to add a guard to the `subprocess.Popen` call to allow the build to continue when this command fails. I'll put together a PR for this shortly.

**Comment by isuruf** [comment]
I'm also seeing some issues with lief,

```
  (using lief)
Traceback (most recent call last):
  File "/home/conda/.ci_support/build_all.py", line 82, in <module>
    build_all(args.recipes_dir, args.arch)
  File "/home/conda/.ci_support/build_all.py", line 72, in build_all
    conda_build.api.build(list(d.keys()), config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2310, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1628, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 954, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 818, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/post.py", line 1008, in post_build
    check_overlinking(m, files)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/post.py", line 947, in check_overlinking
    m.config.channel_urls)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/post.py", line 875, in check_overlinking_impl
    build_prefix, build_prefix_substitution)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/post.py", line 597, in _collect_needed_dsos
    envroot=run_prefix)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/liefldd.py", line 597, in __call__
    value = self.func(*args, **kw)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/liefldd.py", line 626, in get_linkages_memoized
    recurse=recurse, sysroot=sysroot, envroot=envroot, arch=arch)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/liefldd.py", line 414, in get_linkages
    sysroot=sysroot, envroot=envroot, arch=arch)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/liefldd.py", line 373, in inspect_linkages_lief
    sysroot)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/liefldd.py", line 127, in get_rpaths
    rpaths.append(exe_dirname.replace('\\', '/'))
AttributeError: 'NoneType' object has no attribute 'replace'
```

ref: https://circleci.com/gh/conda-forge/staged-recipes/32151

**Comment by sodre** [comment]
In case you need [another example](https://github.com/conda-forge/staged-recipes/pull/7153), this is happening on 
  - [linux/cicleci](
https://circleci.com/gh/sodre/staged-recipes/113?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
```
...
Packaging go1.4-bootstrap
INFO:conda_build.build:Packaging go1.4-bootstrap
Packaging go1.4-bootstrap-20171003-h26a2512_0
INFO:conda_build.build:Packaging go1.4-bootstrap-20171003-h26a2512_0
number of files: 4579
Skipping binary relocation logic
Traceback (most recent call last):
  File "/home/conda/.ci_support/build_all.py", line 82, in <module>
    build_all(args.recipes_dir, args.arch)
  File "/home/conda/.ci_support/build_all.py", line 72, in build_all
    conda_build.api.build(list(d.keys()), config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2310, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1628, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 954, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 818, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/post.py", line 1008, in post_build
    check_overlinking(m, files)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/post.py", line 947, in check_overlinking
    m.config.channel_urls)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/post.py", line 875, in check_overlinking_impl
    build_prefix, build_prefix_substitution)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/post.py", line 597, in _collect_needed_dsos
    envroot=run_prefix)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/liefldd.py", line 597, in __call__
    value = self.func(*args, **kw)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/liefldd.py", line 626, in get_linkages_memoized
    recurse=recurse, sysroot=sysroot, envroot=envroot, arch=arch)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/liefldd.py", line 414, in get_linkages
    sysroot=sysroot, envroot=envroot, arch=arch)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/liefldd.py", line 359, in inspect_linkages_lief
    uniqueness_key = get_uniqueness_key(binary)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/os_utils/liefldd.py", line 246, in get_uniqueness_key
    return binary.soname
AttributeError: '_pylief.ELF.Binary' object has no attribute 'soname'
Exited with code 1
```
  - [travis/osx](
https://travis-ci.org/conda-forge/staged-recipes/builds/463142044?utm_source=github_status&utm_medium=notification)
```
...
Packaging go1.4-bootstrap
INFO:conda_build.build:Packaging go1.4-bootstrap
Packaging go1.4-bootstrap-20171003-h26a2512_0
INFO:conda_build.build:Packaging go1.4-bootstrap-20171003-h26a2512_0
number of files: 4777
Skipping binary relocation logic
Traceback (most recent call last):
  File ".ci_support/build_all.py", line 82, in <module>
    build_all(args.recipes_dir, args.arch)
  File ".ci_support/build_all.py", line 72, in build_all
    conda_build.api.build(list(d.keys()), config=config)
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 2310, in build_tree
    notest=notest,
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 1628, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 954, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 818, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/post.py", line 1008, in post_build
    check_overlinking(m, files)
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/post.py", line 947, in check_overlinking
    m.config.channel_urls)
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/post.py", line 875, in check_overlinking_impl
    build_prefix, build_prefix_substitution)
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/post.py", line 597, in _collect_needed_dsos
    envroot=run_prefix)
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 597, in __call__
    value = self.func(*args, **kw)
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 626, in get_linkages_memoized
    recurse=recurse, sysroot=sysroot, envroot=envroot, arch=arch)
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 414, in get_linkages
    sysroot=sysroot, envroot=envroot, arch=arch)
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 359, in inspect_linkages_lief
    uniqueness_key = get_uniqueness_key(binary)
  File "/Users/travis/miniconda/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 246, in get_uniqueness_key
    return binary.soname
AttributeError: '_pylief.ELF.Binary' object has no attribute 'soname'

travis_time:end:2c14814d:start=1543896264000000000,finish=1543896517000000000,duration=253000000000
[0K[31;1mThe command "if [ -n "$GH_TOKEN" ]; then echo "Creating feedstocks from the recipe(s)."; git config --global user.name "Travis-CI on github.com/conda-forge/staged-recipes"; git config --global user.email "conda-forge@googlegroups.com"; source ./.travis_scripts/create_feedstocks; else echo "Building all recipes."; source ./.travis_scripts/build_all; fi" exited with 1.[0m

```

**Comment by marscher** [comment]
Seems like this pylief stuff has been released barely tested. I wonder if this is a new policy to let the community test it (I would be fine with that, if it is on a "unstable" channel, like canary) or somebody just made a mistake like everybody of us do sometimes?

**Comment by msarahan** [comment]
@mingwandroid tested it himself for months as he was developing it.  Should it have seen more testing?  Probably.  We should have been dog-fooding it on our build servers.  Conda-forge is a completely different beast from defaults, as far as how many corner cases get exercised.  It's just a much bigger, much more demanding system.

Having a staging mechanism for conda-forge, as mentioned in https://github.com/conda-forge/staged-recipes/pull/7164 will be the best way to do this.  Please channel grumbling productively towards work on that staging plan.

**Comment by marscher** [comment]
On 12/6/18 3:56 PM, Mike Sarahan wrote:
> @mingwandroid <https://github.com/mingwandroid> tested it himself for 
> months as he was developing it. Should it have seen more testing? 
Locally presumably :)
> Probably. We should have been dog-fooding it on our build servers. 
> Conda-forge is a completely different beast from defaults, as far as how 
> many corner cases get exercised. It's just a much bigger, much more 
> demanding system.
This affects defaults as well, I choose to install conda and conda-build 
from defaults still.
> 
> Having a staging mechanism for conda-forge, as mentioned in 
> conda-forge/staged-recipes#7164 
> <https://github.com/conda-forge/staged-recipes/pull/7164> will be the 
> best way to do this. Please channel grumbling productively towards work 
> on that staging plan.
I general a staging mechanism would be great, but I guess it is overkill 
for a rolling release distribution. But we should think about having the 
core in a stage, which can be tested prior releasing into the wild.
For instance there was an erroneous Python build on CF, which broke 
things badly. This could have easily prevented by staging such mission 
crucial pieces in the first place. Hotfixing this directly on the 
channel seems an alternative, but causes more hassle in the long term.

Sorry for getting off-topic.
