### ISSUE TITLE
conda-build 3.17.1 fails with SSL error

### ISSUE THREAD

**Issue by zgoda-mobica** [conda/conda-build#3295]
### Actual Behavior

Package build fails with SSL error:

```
Attempting to finalize metadata for pyadsclientlib
INFO:conda_build.metadata:Attempting to finalize metadata for pyadsclientlib
Traceback (most recent call last):
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 444, in wrap_socket
    cnx.do_handshake()
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1907, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
    _raise_current_error()
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 450, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo_host', port=443): Max retries exceeded with url: /channeldata.json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/tomcat/miniconda_temp/1544092798/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/conda_build/build.py", line 2311, in build_tree
    notest=notest,
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/conda_build/build.py", line 1324, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/conda_build/render.py", line 735, in expand_outputs
    for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/conda_build/metadata.py", line 2034, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/conda_build/metadata.py", line 721, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/conda_build/render.py", line 509, in finalize_metadata
    exclude_pattern)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/conda_build/render.py", line 371, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/conda_build/render.py", line 359, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/conda_build/render.py", line 143, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/conda_build/environ.py", line 736, in get_install_actions
    locking=locking, timeout=timeout)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/conda_build/index.py", line 265, in get_build_index
    channel_content = _download_channeldata(channel.base_url + '/channeldata.json')
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/conda/exports.py", line 181, in __call__
    value = self.func(*args, **kw)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/conda_build/index.py", line 168, in _download_channeldata
    return requests.get(channel_url)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/tomcat/miniconda_temp/1544092798/lib/python3.7/site-packages/requests/adapters.py", line 511, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='repo_host', port=443): Max retries exceeded with url: /channeldata.json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

### Expected Behavior

Package should be build succesfully.

### Steps to Reproduce

IDK what causes this exactly and the environment is non-reproductible. Building on my machine succeeds but fails on Jenkins.

##### `Output of conda info`

I do not have shell access to this machine.

Repo host has self-signed certificate, conda is configured to not verify ssl certs with `conda config --set ssl_verify "false"`. Downgrading to 3.16.2 fixes this issue.

**Comment by svenski** [comment]
I'm seeing a similar issue where the `proxy_servers` settings in the .condarc file are being ignored in jenkins. Setting them manually on the command line before running `conda build` works as expected. 

It was similar enough to tack in on here, but let me know if it's different enough to warrant a ticket on its own. 

Downgrading to 3.16.3 worked for me, whereas all the 3.17.+ versions are broken in this regard.

**Comment by msarahan** [comment]
This is happening because the new approach used requests directly, rather than going via conda's download functionality.  We need to fix this so that conda's configuration is respected.
