### ISSUE TITLE
`conda skeleton pypi django-forms-builder --recursive` triggers "AttributeError: 'NoneType' object has no attribute 'rsplit'"

### ISSUE THREAD

**Issue by amfarrell** [conda/conda-build#330]
running `conda skeleton pypi django-forms-builder --recursive` from the root environment
results in the traceback 
```
Traceback (most recent call last):
  File "//anaconda/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "//anaconda/lib/python3.4/site-packages/conda_build/main_skeleton.py", line 188, in main
    args_func(args, p)
  File "//anaconda/lib/python3.4/site-packages/conda_build/main_build.py", line 312, in args_func
    args.func(args, p)
  File "//anaconda/lib/python3.4/site-packages/conda_build/main_skeleton.py", line 202, in execute
    pypi.main(args, parser)
  File "//anaconda/lib/python3.4/site-packages/conda_build/pypi.py", line 328, in main
    urls[0]['filename'] = U.path.rsplit('/')[-1]
AttributeError: 'NoneType' object has no attribute 'rsplit'
```

`conda info` says
```
Current conda install:

             platform : osx-64
        conda version : 3.9.0
  conda-build version : 1.10.2
       python version : 3.4.2.final.0
     requests version : 2.5.1
     root environment : //anaconda  (writable)
  default environment : //anaconda
     envs directories : //anaconda/envs
        package cache : //anaconda/pkgs
         channel URLs : https://conda.binstar.org/t/<TOKEN>/binstar/osx-64/
                        https://conda.binstar.org/t/<TOKEN>/binstar/noarch/
                        https://conda.binstar.org/t/<TOKEN>/binstar/osx-64/
                        https://conda.binstar.org/t/<TOKEN>/binstar/noarch/
                        https://conda.binstar.org/t/<TOKEN>/asmeurer/osx-64/
                        https://conda.binstar.org/t/<TOKEN>/asmeurer/noarch/
                        http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/osx-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.binstar.org/t/<TOKEN>/conda/c/dev/osx-64/
                        https://conda.binstar.org/t/<TOKEN>/conda/c/dev/noarch/
          config file : /Users/afarrell/.condarc
    is foreign system : False
```
This also occurs on Ubuntu.
Traceback:
```
Traceback (most recent call last):
  File "/home/web/miniconda/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/home/web/miniconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 188, in main
    args_func(args, p)
  File "/home/web/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 312, in args_func
    args.func(args, p)
  File "/home/web/miniconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 202, in execute
    pypi.main(args, parser)
  File "/home/web/miniconda/lib/python2.7/site-packages/conda_build/pypi.py", line 328, in main
    urls[0]['filename'] = U.path.rsplit('/')[-1]
AttributeError: 'NoneType' object has no attribute 'rsplit'
```
`conda info` printout:
```
Current conda install:

             platform : linux-64
        conda version : 3.9.0
  conda-build version : 1.10.2
       python version : 2.7.9.final.0
     requests version : 2.5.1
     root environment : /home/web/miniconda  (writable)
  default environment : /home/web/miniconda
     envs directories : /home/web/miniconda/envs
        package cache : /home/web/miniconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/linux-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by asmeurer** [comment]
It looks like the problem is with django. It only has a wheel, which skeleton pypi does not support yet.
