### ISSUE TITLE
six module not found, even though it is installed

### ISSUE THREAD

**Issue by scopatz** [conda/conda-build#3317]
### Actual Behavior

conda-build seems to error out, even for simple commands such as help:

```console
scopatz@artemis ~ $ conda build --help
Traceback (most recent call last):
  File "/home/scopatz/miniconda/bin/conda-build", line 7, in <module>
    from conda_build.cli.main_build import main
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 18, in <module>
    import conda_build.api as api
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 22, in <module>
    from conda_build.config import Config, get_or_merge_config, DEFAULT_PREFIX_LENGTH as _prefix_length
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/conda_build/config.py", line 17, in <module>
    from .variants import get_default_variant
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/conda_build/variants.py", line 12, in <module>
    import six
ModuleNotFoundError: No module named 'six'
scopatz@artemis ~ $ conda list six 
# packages in environment at /home/scopatz/miniconda:
#
# Name                    Version                   Build  Channel
six                       1.12.0                py36_1000    conda-forge
scopatz@artemis ~ $ conda list conda-build
# packages in environment at /home/scopatz/miniconda:
#
# Name                    Version                   Build  Channel
conda-build               3.17.4                   py36_0    conda-forge
conda-build-all           1.1.3                      py_0    conda-forge
```

### Expected Behavior

Not to error

### Steps to Reproduce

`conda build --help`

##### `Output of conda info`

```
scopatz@artemis ~ $ conda info

     active environment : None
       user config file : /home/scopatz/.condarc
 populated config files : /home/scopatz/.condarc
          conda version : 4.5.11
    conda-build version : 3.17.4
         python version : 3.6.7.final.0
       base environment : /home/scopatz/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/scopatz/miniconda/pkgs
                          /home/scopatz/.conda/pkgs
       envs directories : /home/scopatz/miniconda/envs
                          /home/scopatz/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.21.0 CPython/3.6.7 Linux/4.15.0-42-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

**Comment by scopatz** [comment]
Must have been on my end.  `conda install -f six` fixed it.
