### ISSUE TITLE
RPM Skeleton Path Join Errors

### ISSUE THREAD

**Issue by paxsonsa** [conda/conda-build#3340]
### Actual Behavior
Attempting to use the skeleton feature with RPMs. It looks like some the checksum function is being passed in.
```
> conda skeleton rpm --distro=centos6 --architecture=x86_64 kernel-devel
No hash (md5, sha1, sha256) provided for <built-in function openssl_sha256>.  Source download forced.  Add hash to recipe to use source cache.
WARNING:conda_build.source:No hash (md5, sha1, sha256) provided for <built-in function openssl_sha256>.  Source download forced.  Add hash to recipe to use source cache.
No hash (md5, sha1, sha256) provided for 8a106b58d2b45b4757ebba9f431cfcd6197392b5ee7640ab288b062fa754822c.  Source download forced.  Add hash to recipe to use source cache.
WARNING:conda_build.source:No hash (md5, sha1, sha256) provided for 8a106b58d2b45b4757ebba9f431cfcd6197392b5ee7640ab288b062fa754822c.  Source download forced.  Add hash to recipe to use source cache.

Leaving build/test directories:
  Work:
 /dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/conda-bld/skeleton_1546541525865/work
  Test:
 /dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/conda-bld/skeleton_1546541525865/test_tmp
Leaving build/test environments:
  Test:
source activate  /dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/conda-bld/skeleton_1546541525865/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
  Build:
source activate  /dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/conda-bld/skeleton_1546541525865/_build_env


Traceback (most recent call last):
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/site-packages/conda_build/skeletons/rpm.py", line 332, in get_repo_dict
    xml_file, xml_csum = cache_file(src_cache, xml_file, cdt['checksummer'])
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/site-packages/conda_build/skeletons/rpm.py", line 205, in cache_file
    cached_path, _ = download_to_cache(src_cache, '', source)
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/site-packages/conda_build/source.py", line 60, in download_to_cache
    path = join(cache_folder, fn)
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'builtin_function_or_method'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/shutil.py", line 557, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/conda-bld/src_cache/8a106b58d2b45b4757ebba9f431cfcd6197392b5ee7640ab288b062fa754822c' ->'/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5_8a106b58d2.12/conda-bld/src_cache/8a106b58d2b45b4757ebba9f431cfcd6197392b5ee7640ab288b062fa754822c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    version=args.version, config=config)
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/site-packages/conda_build/api.py", line 289, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/site-packages/conda_build/skeletons/rpm.py", line 677, in skeletonize
    override_arch, dependency_add, config)
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/site-packages/conda_build/skeletons/rpm.py", line 661, in write_conda_recipe
    config.src_cache)
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/site-packages/conda_build/skeletons/rpm.py", line 338, in get_repo_dict
    csum, cdt['checksummer'])
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/site-packages/conda_build/skeletons/rpm.py", line 205, in cache_file
    cached_path, _ = download_to_cache(src_cache, '', source)
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/site-packages/conda_build/source.py", line 115, in download_to_cache
    shutil.move(path, dest_path)
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/shutil.py", line 571, in move
    copy_function(src, real_dst)
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/dept/pe/dev/apaxson/projects/software_managment/conda/v4.5_8a106b58d2.12/conda-bld/src_cache/8a106b58d2b45b4757ebba9f431cfcd6197392b5ee7640ab288b062fa754822c'
```

### Expected Behavior
Should attempt to build just fine.

### Steps to Reproduce
conda skeleton rpm --distro=centos6 --architecture=x86_64 kernel-devel

##### `Output of conda info`

```
active environment : None
            shell level : 0
       user config file : /home/apaxson/.condarc
 populated config files : /dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/.condarc
                          /home/apaxson/.condarc
          conda version : 4.5.12
    conda-build version : 3.17.5
         python version : 3.7.1.final.0
       base environment : /dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          file:///dept/pe/devops/projects/conda-channels/ilm_base/linux-64
                          file:///dept/pe/devops/projects/conda-channels/ilm_base/noarch
          package cache : /dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/pkgs
                          /home/apaxson/.conda/pkgs
       envs directories : /dept/pe/dev/apaxson/projects/software_managment/conda/v4.5.12/envs
                          /home/apaxson/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.19.1 CPython/3.7.1 Linux/3.10.0-693.21.1.el7.x86_64 centos/7 glibc/2.17
                UID:GID : 14383:55
             netrc file : None
           offline mode : False
```

**Comment by paxsonsa** [comment]
Looks like this is an area 

https://github.com/conda/conda-build/blob/5067e6f61ec32fa2990d80103f92d77d1131bb18/conda_build/skeletons/rpm.py#L332

**Comment by mingwandroid** [comment]
Hi @paxsonsa, I cannot reproduce this. Could it be a local connection issue? My output (tested on macOS and Linux using conda-build 3.17.6) is:

```
conda skeleton rpm --distro=centos6 --architecture=x86_64 kernel-devel
No hash (md5, sha1, sha256) provided for <built-in function openssl_sha256>.  Source download forced.  Add hash to recipe to use source cache.
WARNING:conda_build.source:No hash (md5, sha1, sha256) provided for <built-in function openssl_sha256>.  Source download forced.  Add hash to recipe to use source cache.
No hash (md5, sha1, sha256) provided for 8a106b58d2b45b4757ebba9f431cfcd6197392b5ee7640ab288b062fa754822c.  Source download forced.  Add hash to recipe to use source cache.
WARNING:conda_build.source:No hash (md5, sha1, sha256) provided for 8a106b58d2b45b4757ebba9f431cfcd6197392b5ee7640ab288b062fa754822c.  Source download forced.  Add hash to recipe to use source cache.
No hash (md5, sha1, sha256) provided for kernel-devel-2.6.32-754.el6.x86_64.rpm.  Source download forced.  Add hash to recipe to use source cache.
WARNING:conda_build.source:No hash (md5, sha1, sha256) provided for kernel-devel-2.6.32-754.el6.x86_64.rpm.  Source download forced.  Add hash to recipe to use source cache.
No hash (md5, sha1, sha256) provided for kernel-2.6.32-754.el6.src.rpm.  Source download forced.  Add hash to recipe to use source cache.
WARNING:conda_build.source:No hash (md5, sha1, sha256) provided for kernel-2.6.32-754.el6.src.rpm.  Source download forced.  Add hash to recipe to use source cache.
--dirty flag and --keep-old-work not specified. Removing build/test folder after successful build/test.

INFO:conda_build.config:--dirty flag and --keep-old-work not specified. Removing build/test folder after successful build/test.
```

The files generated are:

kernel-devel-cos6-x86_64/meta.yaml
```
package:
  name: kernel-devel-cos6-x86_64
  version: 2.6.32

source:
  - url: http://mirror.centos.org/centos/6.10/os/x86_64/Packages/kernel-devel-2.6.32-754.el6.x86_64.rpm
    sha256: 906745681e365f32d1bc2fee1e164f2b8d5de95db1de7c0d2c68d4af529594b3
    folder: binary
  - url: http://vault.centos.org/6.10/os/Source/SPackages/kernel-2.6.32-754.el6.src.rpm
    folder: source

build:
  missing_dso_whitelist:
    - '*'



outputs:
  - name: kernel-devel-cos6-x86_64
    build:
      noarch: generic

    about:
      home: http://www.kernel.org/
      license: GPLv2
      license_family: GPL2
      summary: "(CDT) Development package for building kernel modules to match the kernel"
      description: |
        This package provides kernel headers and makefiles sufficient to build modules
        against the kernel package.
```

kernel-devel-cos6-x86_64/build.sh
```
#!/bin/bash

RPM=$(find ${PWD}/binary -name "*.rpm")
mkdir -p ${PREFIX}/x86_64-conda_cos6-linux-gnu/sysroot/usr
pushd ${PREFIX}/x86_64-conda_cos6-linux-gnu/sysroot/usr > /dev/null 2>&1
if [[ -n "${RPM}" ]]; then
  "${RECIPE_DIR}"/rpm2cpio "${RPM}" | cpio -idmv
  popd > /dev/null 2>&1
else
  cp -Rf "${SRC_DIR}"/binary/* .
fi
```

kernel-devel-cos6-x86_64/rpm2cpio
```
#!/bin/sh

# Based on:
# https://www.redhat.com/archives/rpm-list/2003-June/msg00367.html
# Modified to also support xz compression.

pkg=$1
if [ "$pkg" = "" -o ! -e "$pkg" ]; then
    echo "no package supplied" 1>&2
   exit 1
fi

leadsize=96
o=`expr $leadsize + 8`
set `od -j $o -N 8 -t u1 $pkg`
il=`expr 256 \* \( 256 \* \( 256 \* $2 + $3 \) + $4 \) + $5`
dl=`expr 256 \* \( 256 \* \( 256 \* $6 + $7 \) + $8 \) + $9`

sigsize=`expr 8 + 16 \* $il + $dl`
o=`expr $o + $sigsize + \( 8 - \( $sigsize \% 8 \) \) \% 8 + 8`
set `od -j $o -N 8 -t u1 $pkg`
il=`expr 256 \* \( 256 \* \( 256 \* $2 + $3 \) + $4 \) + $5`
dl=`expr 256 \* \( 256 \* \( 256 \* $6 + $7 \) + $8 \) + $9`

hdrsize=`expr 8 + 16 \* $il + $dl`
o=`expr $o + $hdrsize`

hdr=`dd if=$pkg ibs=$o skip=1 count=1 2>/dev/null | od -N 2 -t x1 -An`
# macOS dd and Linux od give different results
hdr="${hdr#"${hdr%%[![:space:]]*}"}"
# remove trailing whitespace characters
hdr="${hdr%"${hdr##*[![:space:]]}"}"
if [[ "$hdr" == "1f 8b" ]] || [[ "$hdr" == "1f  8b" ]]; then
  dd if=$pkg ibs=$o skip=1 2>/dev/null | gunzip
else
  dd if=$pkg ibs=$o skip=1 2>/dev/null | xz -d
fi
```
```

**Comment by paxsonsa** [comment]
Ok thanks for running that for me! I will have a look on my end!

Closing as cannot reproduce.
