### ISSUE TITLE
AttributeError: 'MatchSpec' object has no attribute 'namespace'

### ISSUE THREAD

**Issue by parente** [conda/conda-build#3366]
### Actual Behavior

Running conda-build 3.14.4 in a Python 2.7 environment with conda 4.6.1 installed results in:

```
01:52:27 Traceback (most recent call last):
01:52:27   File "/opt/miniconda/bin/conda-build", line 11, in <module>
01:52:27     sys.exit(main())
01:52:27   File "/opt/miniconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 424, in main
01:52:27 compiling .pyc files...
01:52:27 number of files: 50
01:52:27 Fixing permissions
01:52:27     execute(sys.argv[1:])
01:52:27   File "/opt/miniconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 415, in execute
01:52:27     verify=args.verify)
01:52:27   File "/opt/miniconda/lib/python2.7/site-packages/conda_build/api.py", line 201, in build
01:52:27     notest=notest, need_source_download=need_source_download, variants=variants)
01:52:27   File "/opt/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 2205, in build_tree
01:52:27     notest=notest,
01:52:27   File "/opt/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 1599, in build
01:52:27     built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env, stats)
01:52:27   File "/opt/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 1030, in bundle_conda
01:52:27     update_index(os.path.dirname(output_folder), verbose=metadata.config.verbose)
01:52:27   File "/opt/miniconda/lib/python2.7/site-packages/conda_build/index.py", line 270, in update_index
01:52:27     patch_generator=patch_generator, verbose=verbose, progress=progress)
01:52:27   File "/opt/miniconda/lib/python2.7/site-packages/conda_build/index.py", line 776, in index
01:52:27     augmented_repodata = _augment_repodata(subdirs, patched_repodata, patch_instructions)
01:52:27   File "/opt/miniconda/lib/python2.7/site-packages/conda_build/index.py", line 587, in _augment_repodata
01:52:27     for dep in info['depends']]
01:52:27   File "/opt/miniconda/lib/python2.7/site-packages/conda_build/index.py", line 504, in _add_namespace_to_spec
01:52:27     if spec.namespace:
01:52:27 AttributeError: 'MatchSpec' object has no attribute 'namespace'
```

### Expected Behavior

If Python 2.7 is still supported, the exception is not hit and the build succeeds. (If Python 2.7 is not supported anymore, that's fine.)

### Steps to Reproduce

Internal build running `conda build python=2.7 my-package.yaml`. I can try to reproduce with an open source package if necessary.

##### `Output of conda info`

Not handy at the moment (Jenkins job).

**Comment by parente** [comment]
FWIW, the problem does not occur with conda-build 3.14.4 and conda 4.5.12.

**Comment by parente** [comment]
Scratch all that. Something snuck a pin file for conda-build <=3.15 into the environment. I see conda 3.17.x is the latest which probably works fine. Closing.
