### ISSUE TITLE
build fails OS-X after attempting to copy object files after build is completed. 

### ISSUE THREAD

**Issue by weinbe58** [conda/conda-build#3367]
### Actual Behavior

I'm trying to do a dry run conda-build  for branch `dev_0.3.1` of my python package before I distribute it(source found here: https://github.com/weinbe58/QuSpin/tree/dev_0.3.1)  I'm not having any issues on Linux however on OS-X I'm having trouble during the build. If you download the source and after running the following command from the directory: ~/Documents/ED_python in my machine:

`conda build QuSpin-dev_0.3.1/`

after the extensions are compiled I get the following error:

```
Traceback (most recent call last):
  File "/Users/Arden/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 487, in _copy_with_shell_fallback
    stderr=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/Users/Arden/anaconda3/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cp -a /Users/Arden/Documents/ED_python/QuSpin/build/temp.macosx-10.7-x86_64-3.6quspin/basis/basis_1d/_basis_1d_core/hcp_ops.o.d /Users/Arden/anaconda3/conda-bld/quspin_1548687044068/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/info/recipe/build/temp.macosx-10.7-x86_64-3.6quspin/basis/basis_1d/_basis_1d_core/hcp_ops.o.d' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Arden/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/Arden/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/Users/Arden/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/Users/Arden/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/Arden/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/Users/Arden/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1628, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/Users/Arden/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 967, in bundle_conda
    output['checksums'] = create_info_files(metadata, files, prefix=metadata.config.host_prefix)
  File "/Users/Arden/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 660, in create_info_files
    copy_recipe(m)
  File "/Users/Arden/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 296, in copy_recipe
    _copy_top_level_recipe(m.path, m.config, recipe_dir)
  File "/Users/Arden/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 262, in _copy_top_level_recipe
    locking=config.locking, clobber=True)
  File "/Users/Arden/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 557, in copy_into
    _copy_with_shell_fallback(src, dst_fn)
  File "/Users/Arden/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 490, in _copy_with_shell_fallback
    raise OSError("Failed to copy {} to {}.  Error was: {}".format(src, dst, e))
OSError: Failed to copy /Users/Arden/Documents/ED_python/QuSpin/build/temp.macosx-10.7-x86_64-3.6quspin/basis/basis_1d/_basis_1d_core/hcp_ops.o.d to /Users/Arden/anaconda3/conda-bld/quspin_1548687044068/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/info/recipe/build/temp.macosx-10.7-x86_64-3.6quspin/basis/basis_1d/_basis_1d_core/hcp_ops.o.d.  Error was: Command 'cp -a /Users/Arden/Documents/ED_python/QuSpin/build/temp.macosx-10.7-x86_64-3.6quspin/basis/basis_1d/_basis_1d_core/hcp_ops.o.d /Users/Arden/anaconda3/conda-bld/quspin_1548687044068/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/info/recipe/build/temp.macosx-10.7-x86_64-3.6quspin/basis/basis_1d/_basis_1d_core/hcp_ops.o.d' returned non-zero exit status 1.

```

### Expected Behavior

expected Behaior is the build should continue to the test and then finished.

### Steps to Reproduce
To Reproduce this just download the source code and run conda-build on it. 

##### `Output of conda info`
N/A

Thanks! I tried to make a smaller recipe to reproduce the same issues however it doesn't seem to work. Please let me know if there is any other info you need!

**Comment by weinbe58** [comment]
Hello again, I'm also trying to do this same build on Windows 10 and it seems to be giving a very similar error. I'm wondering if this is something really stupid having to do with permissions of directories?

**Comment by weinbe58** [comment]
actually this is not an issue with conda-build my apologies I forgot to remove some extra files for the directory.
