### ISSUE TITLE
Conda-build Unsatisfiable dependencies for platform linux-64: set(['python=3.6', 'python=3.5'])

### ISSUE THREAD

**Issue by weinbe58** [conda/conda-build#3379]
I'm trying to build my recipe: https://github.com/weinbe58/QuSpin_recipes

### Actual Behavior
running the command: 
```
$ conda build QuSpin_recipes 
```
gives:

```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /home/phillip/Documents/ED_python/QuSpin_recipes/quspin-openmp/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /home/phillip/Documents/ED_python/QuSpin_recipes/quspin-openmp/conda_build_config.yaml
Attempting to finalize metadata for quspin-openmp
INFO:conda_build.metadata:Attempting to finalize metadata for quspin-openmp
Collecting package metadata: ...working... done
Solving environment: ...working... failed

Leaving build/test directories:
  Work:
 /home/phillip/anaconda2/conda-bld/work 
  Test:
 /home/phillip/anaconda2/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/phillip/anaconda2/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p 
  Build:
source activate  /home/phillip/anaconda2/conda-bld/_build_env 


Traceback (most recent call last):
  File "/home/phillip/anaconda2/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/phillip/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/home/phillip/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/home/phillip/anaconda2/lib/python2.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/phillip/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/home/phillip/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 1324, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/home/phillip/anaconda2/lib/python2.7/site-packages/conda_build/render.py", line 735, in expand_outputs
    for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/home/phillip/anaconda2/lib/python2.7/site-packages/conda_build/metadata.py", line 2038, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/home/phillip/anaconda2/lib/python2.7/site-packages/conda_build/metadata.py", line 718, in finalize_outputs_pass
    parent_metadata.parse_until_resolved()
  File "/home/phillip/anaconda2/lib/python2.7/site-packages/conda_build/metadata.py", line 1015, in parse_until_resolved
    bypass_env_check=bypass_env_check)
  File "/home/phillip/anaconda2/lib/python2.7/site-packages/conda_build/metadata.py", line 937, in parse_again
    bypass_env_check=bypass_env_check),
  File "/home/phillip/anaconda2/lib/python2.7/site-packages/conda_build/metadata.py", line 1525, in _get_contents
    rendered = template.render(environment=env)
  File "/home/phillip/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/phillip/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/phillip/Documents/ED_python/QuSpin_recipes/quspin-openmp/meta.yaml", line 26, in top-level template code
    - llvm-openmp # [osx]
  File "/home/phillip/anaconda2/lib/python2.7/site-packages/conda_build/jinja_context.py", line 230, in pin_compatible
    pins, _, _ = get_env_dependencies(m, 'host', m.config.variant)
  File "/home/phillip/anaconda2/lib/python2.7/site-packages/conda_build/render.py", line 143, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/home/phillip/anaconda2/lib/python2.7/site-packages/conda_build/environ.py", line 755, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: set(['python=3.6', 'python=3.5'])
```

### Expected Behavior

I would expect the build to run and not crash? 

### Steps to Reproduce

run conda build with this meta.yaml:

```
{% set version = "0.3.1" %}

package:
  name: quspin-openmp
  version: {{ version }}

source:
  url: https://github.com/weinbe58/QuSpin/archive/dev_{{ version }}.zip


build:
  number: 0
  script: python setup.py install --omp


requirements:
  build:
    - {{compiler('cxx')}}

  host:
    - llvm-openmp # [osx]
    - python {{ python }}
    - numpy 1.10.*
 
  run:
    - llvm-openmp # [osx]
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - scipy >=0.19.0
    - six
    - joblib
    - dill
    - gmpy2 
    - numba
    
test:
  imports:
    - quspin 

about:
  home: https://github.com/weinbe58/QuSpin.git
  license: BSD-3
```
and this conda_build_config.yaml:

```
python:
  - 2.7 # [not win]
  - 3.5 # [not win]
  - 3.6
  - 3.7
```

##### `Output of conda info`

```
     active environment : None
       user config file : /home/phillip/.condarc
 populated config files : 
          conda version : 4.6.2
    conda-build version : 3.17.7
         python version : 2.7.15.final.0
       base environment : /home/phillip/anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/phillip/anaconda2/pkgs
                          /home/phillip/.conda/pkgs
       envs directories : /home/phillip/anaconda2/envs
                          /home/phillip/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.2 requests/2.20.1 CPython/2.7.15 Linux/4.15.0-45-generic ubuntu/18.04.1 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

Lastly an interesting observation is that I can run: `conda build --python=x.x QuSpin_recipe/` and it builds just fine. This seems to point to that I have no idea what I am doing in terms of the meta data! any help would be appreciated!

**Comment by weinbe58** [comment]
oh shoot! it was my numpy dependency it would appear! sorry again!!!!
