### ISSUE TITLE
libstdc++.so.6 error: Links to obsolete system version by default, instead of conda's own curated version

### ISSUE THREAD

**Issue by danielkrizian** [conda/conda-build#3385]
### Actual Behavior
Error produced:
```
(base) [dk@s ~]$ conda build
Traceback (most recent call last):
  File "/opt/miniconda3/bin/conda-build", line 7, in <module>
    from conda_build.cli.main_build import main
  File "/opt/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 18, in <module>
    import conda_build.api as api
  File "/opt/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 22, in <module>
    from conda_build.config import Config, get_or_merge_config, DEFAULT_PREFIX_LENGTH as _prefix_length
  File "/opt/miniconda3/lib/python3.6/site-packages/conda_build/config.py", line 17, in <module>
    from .variants import get_default_variant
  File "/opt/miniconda3/lib/python3.6/site-packages/conda_build/variants.py", line 15, in <module>
    from conda_build.utils import ensure_list, trim_empty_keys, get_logger
  File "/opt/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 9, in <module>
    import libarchive
  File "/opt/miniconda3/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/opt/miniconda3/lib/python3.6/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/opt/miniconda3/lib/python3.6/site-packages/libarchive/ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "/opt/miniconda3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/opt/miniconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/miniconda3/lib/././libicuuc.so.58)
```
Analysis: `libstdc++.so.6` links to `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`, which in turn is symbolic link to old `libstdc++.so.6.0.20`:
```
(base) [dk@s ~]$ ldd /opt/miniconda3/lib/libicuuc.so.58
/opt/miniconda3/lib/libicuuc.so.58: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/miniconda3/lib/libicuuc.so.58)
        linux-vdso.so.1 (0x00007ffef1da2000)
        libicudata.so.58 => /opt/miniconda3/lib/./libicudata.so.58 (0x00007f3b7c590000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3b7c373000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3b7c16f000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3b7be64000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3b7bb63000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3b7b94d000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3b7b5a2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3b7e43e000)
```

```
(base) [dk@s ~]$ ls -l /usr/lib/x86_64-linux-gnu/libstdc++.so.6
lrwxrwxrwx 1 root root 19 Jan 31  2018 /usr/lib/x86_64-linux-gnu/libstdc++.so.6 -> libstdc++.so.6.0.20
```

### Expected Behavior

 In conda-build version 3.17.8, `conda build` commands should run successfully, automatically preferring anaconda's own library path `/opt/miniconda3/lib` to system's `/usr/lib` path, which could be obsolete.

```
(base) [dk@s ~]$ strings /opt/miniconda3/lib/libstdc++.so.6.0.25 | grep ABI_1.3.9
CXXABI_1.3.9
CXXABI_1.3.9
```

##### `Output of conda info`

```
(base) [dk@s ~]$ conda info

     active environment : base
    active env location : /opt/miniconda3
            shell level : 1
       user config file : /home/dk/.condarc
 populated config files : /opt/miniconda3/.condarc
                          /home/dk/.condarc
          conda version : 4.6.3
    conda-build version : 3.17.8
         python version : 3.6.7.final.0
       base environment : /opt/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/anaconda/linux-64
                          https://conda.anaconda.org/anaconda/noarch
                          file://opt/channel/linux-64
                          file://opt/channel/noarch
                          https://conda.anaconda.org/jmcmurray/linux-64
                          https://conda.anaconda.org/jmcmurray/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/dk/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /home/dk/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.3 requests/2.21.0 CPython/3.6.7 Linux/3.16.0-4-amd64 debian/8 glibc/2.19
                UID:GID : 1002:1003
             netrc file : None
           offline mode : False
```

##### `Output of conda list`
```
(base) [dk@s ~]$ conda list
# packages in environment at /opt/miniconda3:
#
# Name                    Version                   Build  Channel
anaconda-client           1.7.1                      py_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
attrs                     18.2.0                     py_0    conda-forge
beautifulsoup4            4.7.1                 py36_1001    conda-forge
binutils_impl_linux-64    2.31.1               h6176602_1  
binutils_linux-64         2.31.1               h6176602_6  
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
conda                     4.6.3                    py36_0    conda-forge
conda-build               3.17.8                   py36_0    conda-forge
conda-env                 2.6.0                         1  
cryptography              2.4.2            py36h1ba5d50_0  
decorator                 4.3.0                      py_0    conda-forge
expat                     2.1.0                         1    omgarcia
filelock                  3.0.10                     py_0    conda-forge
future                    0.17.1                py36_1000    conda-forge
gcc_impl_linux-64         7.3.0                habb00fd_1  
gcc_linux-64              7.3.0                h553295d_6  
glob2                     0.6                        py_0    conda-forge
gmp                       6.1.0                         1    omgarcia
gxx_impl_linux-64         7.3.0                hdf63c60_1  
gxx_linux-64              7.3.0                h553295d_6  
icu                       58.2                 h9c2bf20_1  
idna                      2.8                   py36_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isl                       0.17.1                        1    conda-forge
jinja2                    2.10                     py36_0  
jsonschema                3.0.0a3               py36_1000    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
libarchive                3.3.3                h5d8350f_5  
libcxx                    7.0.1             h6bb024c_1000    conda-forge
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                h4deb6c0_3    anaconda
libgcc-ng                 8.2.0                hdf63c60_1  
libiconv                  1.14                          1    omgarcia
liblief                   0.9.0                h7725739_1  
libstdcxx-ng              8.2.0                hdf63c60_1  
libxml2                   2.9.8                h26e45fe_1  
lz4-c                     1.8.1.2              h14c3975_0  
lzo                       2.10                 h49e0be7_2  
markupsafe                1.1.0            py36h470a237_0    conda-forge
mpc                       1.0.1                         0    omgarcia
mpfr                      3.1.2                         0    omgarcia
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  hf484d3e_0  
openssl                   1.1.1a            h14c3975_1000    conda-forge
patchelf                  0.9                  he6710b0_3  
pip                       18.1                  py36_1000    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
psutil                    5.4.8            py36h470a237_0    conda-forge
py-lief                   0.9.0            py36h7725739_1  
pycosat                   0.6.3            py36h470a237_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyrsistent                0.14.9           py36h470a237_0    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
python                    3.6.7                h0371630_0  
python-dateutil           2.7.5                      py_0    conda-forge
python-libarchive-c       2.8                   py36_1004    conda-forge
pytz                      2018.9                     py_0    conda-forge
pyyaml                    3.13             py36h470a237_1    conda-forge
q                         3.6                           0    file://opt/channel
qhttps                    0.0.1                         1    jmcmurray
qib                       0.0.1                         0    file://opt/channel
qlic                      2018.11.25                    0    file://opt/channel
qutil                     3.2.1                         0    file://opt/channel
readline                  7.0                  h7b6447c_5    anaconda
requests                  2.21.0                py36_1000    conda-forge
ruamel_yaml               0.15.71          py36h470a237_0    conda-forge
setuptools                40.6.3                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
soupsieve                 1.7.1                 py36_1000    conda-forge
sqlite                    3.25.3               h7b6447c_0    anaconda
tk                        8.6.8                hbc83047_0    anaconda
tqdm                      4.29.1                     py_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
urllib3                   1.24.1                py36_1000    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                h96e3832_1    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
zstd                      1.3.7                h0b5b093_0  
```

**Comment by mingwandroid** [comment]
Can you please provide a full reproducer, preferably in the form of a Dockerfile that starts from nothing? Alternatively, please print out the value of `libarchive_path` in /opt/miniconda3/lib/python3.6/site-packages/libarchive/ffi.py just before line 27.

**Comment by danielkrizian** [comment]
Line 26 and 27 respectively:
```
libarchive_path = os.environ.get('LIBARCHIVE') or find_library('archive')                                                                             
libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
```

And:

```
(base) [dk@s ~]$ echo $LIBARCHIVE

(base) [dk@s ~]$ 
```

This could be reproduced by simply installing only `conda v4.6.3` and `conda-build v3.17.8` on Debian 8 (Jessie), which has quite old libraries in `/usr/lib` by default.

```
(base) [dk@s ~]$ uname -a
Linux s 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux
```

For some reason, `conda-build` prefers `/usr/lib` to its own `/opt/miniconda3/lib`

**Comment by danielkrizian** [comment]
Hacky fix (that pollutes `.bashrc`) is exporting  the correct conda's library :

```
export LD_PRELOAD=/opt/miniconda3/lib/libstdc++.so.6.0.25
```
and then the conda build works:
```
[dk@s110519 ~]$ conda build --version
conda-build 3.17.8
```

But I would assume that `conda-build` would give preference to `/opt/miniconda3/lib` path by default?

**Comment by mingwandroid** [comment]
Thanks @danielkrizian

> Line 26 and 27 respectively:

I am asking you to change the code so that it prints out the value of `libarchive_path` as returned from `find_library('archive')`

> This could be reproduced by simply installing only `conda v4.6.3` and `conda-build v3.17.8` on Debian 8 (Jessie), which has quite old libraries in `/usr/lib` by default.

I'm sorry to say this is not the case (and those are far from reproduction steps). I have provided a Dockerfile and install_miniconda.sh script that does this (except I don't use conda 4.6.3 since that's not on Anaconda `defaults`; having said that running `conda install -y conda-forge::conda` does get me 4.6.3 but does not exhibit this issue). You are using many different channels (defaults, conda-forge, omgarcia, jmcmurray and some local packages (file://opt/channel) here.

I believe you'll be unable to get me a reproducer because I believe your failure depends upon local packages being installed (and/or packages that have been built with a C++ compiler but without using our compilers). I'm betting that's what's causing the old `libstdc++` to get loaded by your python interpreter.

If you can get me a reproducer then I can try to help further.

`Dockerfile`
```
FROM debian:8.11

WORKDIR /build_scripts
COPY install_miniconda.sh /build_scripts
RUN apt-get update -y && apt-get install -y curl bzip2 && ./install_miniconda.sh

ENV PATH="/opt/conda/bin:${PATH}"

CMD [ "/bin/bash" ]
```

`install_miniconda.sh`
```
#!/bin/bash
set -euxo pipefail

fname="Miniconda3-latest-Linux-x86_64.sh"
curl -LO https://repo.continuum.io/miniconda/$fname
bash -x $fname -bfp /opt/conda

/opt/conda/bin/conda config --set show_channel_urls True
/opt/conda/bin/conda update --yes --quiet --all
/opt/conda/bin/conda install --yes --quiet git conda-build curl anaconda-client
/opt/conda/bin/conda install --yes --quiet gcc_linux-64 gxx_linux-64
/opt/conda/bin/pip install https://github.com/conda/conda-concourse-ci/archive/master.zip
/opt/conda/bin/conda config --set add_pip_as_python_dependency False
/opt/conda/bin/conda clean -ptiy
rm -rf Miniconda*
```

**Comment by danielkrizian** [comment]
> value of `libarchive_path` as returned from `find_library('archive')`
```
[dk@s ~]$ sed -n 26,28p /opt/miniconda3/lib/python3.6/site-packages/libarchive/ffi.py
   libarchive_path = os.environ.get('LIBARCHIVE') or find_library('archive')
   print("This is the printed value: " + libarchive_path)
   libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
[dk@s ~]$ conda build
   This is the printed value: /opt/miniconda3/lib/libarchive.so.13
...
```
I noticed that `/opt/miniconda3/lib/libarchive.so.13` is linked to `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`
```
[dk@s /home/dk/dockerbuilds]$ ldd /opt/miniconda3/lib/libarchive.so.13
/opt/miniconda3/lib/libarchive.so.13: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/miniconda3/lib/././libicuuc.so.58)
        linux-vdso.so.1 (0x00007ffc3f39b000)
        libcrypto.so.1.1 => /opt/miniconda3/lib/./libcrypto.so.1.1 (0x00007f8124f5f000)
        liblzo2.so.2 => /opt/miniconda3/lib/./liblzo2.so.2 (0x00007f8124d1c000)
        libzstd.so.1.3.7 => /opt/miniconda3/lib/./libzstd.so.1.3.7 (0x00007f8125313000)
        liblz4.so.1 => /opt/miniconda3/lib/./liblz4.so.1 (0x00007f8124af8000)
        libbz2.so.1.0 => /opt/miniconda3/lib/./libbz2.so.1.0 (0x00007f81248e6000)
        libxml2.so.2 => /opt/miniconda3/lib/./libxml2.so.2 (0x00007f812457f000)
        libz.so.1 => /opt/miniconda3/lib/./libz.so.1 (0x00007f81252f2000)
        liblzma.so.5 => /opt/miniconda3/lib/./liblzma.so.5 (0x00007f8124359000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f812413c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8123d91000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8123b8d000)
        libicuuc.so.58 => /opt/miniconda3/lib/././libicuuc.so.58 (0x00007f81237df000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f81234de000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f81232d6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8125256000)
        libicudata.so.58 => /opt/miniconda3/lib/./././libicudata.so.58 (0x00007f81217d6000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f81214cb000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f81212b5000)
```
I have installed docker on my Debian Jessie and have created the scripts:
```
[dk@s /home/dk/dockerbuilds]$ ls myconda
Dockerfile  install_miniconda.sh
```
I've never used docker before, so forgive me for asking, what are the next reproducible steps?

> You are using many different channels - defaults, conda-forge, omgarcia, jmcmurray and some local packages (file://opt/channel) here.
I believe you'll be unable to get me a reproducer because I believe your failure depends upon local packages being installed (and/or packages that have been built with a C++ compiler but without using our compilers).

I can remove these from the (base) environment to simplify it.

**Comment by rossimattia** [comment]
Hello, I have the same issue. In my Conda environment, the scipy package uses the system libstdc++ rather then the local Conda one, but the system one is outdated:

```ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/miniconda3/envs/projectA/lib/python3.9/site-packages/scipy/spatial/_ckdtree.cpython-39-x86_64-linux-gnu.so)```

In ```/home/miniconda3/envs/projectA/lib``` there is the required version of libstdc++, but this is not used unless I export the previous path ```export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/miniconda3/envs/projectA/lib/```. This fix is neither clean nor desirable, as mentioned here [https://docs.conda.io/projects/conda-build/en/stable/resources/use-shared-libraries.html](url)

**Comment by ChenYuhang243** [comment]
> Hello, I have the same issue on Ubuntu 20.04. In my Conda 23.1.0 environment, the scipy package uses the system libstdc++ rather then the local Conda one, but the system one is outdated:
> 
> `` ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/miniconda3/envs/projectA/lib/python3.9/site-packages/scipy/spatial/_ckdtree.cpython-39-x86_64-linux-gnu.so) ``
> 
> In `/home/miniconda3/envs/projectA/lib` there is the required version of libstdc++, but this is not used unless I export the previous path `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/miniconda3/envs/projectA/lib/`. This fix is neither clean nor desirable, as mentioned here [https://docs.conda.io/projects/conda-build/en/stable/resources/use-shared-libraries.html](url)

I stuck in exact the same issue which seems like caused by conda installed scipy on Ubuntu 18.04.  Using `**pip install scipy==1.10.0**` solved the issue. Hope it can help someone else with the same issue.
