### ISSUE TITLE
conda build modulegraph fails

### ISSUE THREAD

**Issue by Manmadescience** [conda/conda-build#340]
Building `modulegraph` package as usual: `conda skeleton pypi modulegraph && conda build modulegraph` fails when building.

Here's the output of `conda build modulegraph`:

```
Traceback (most recent call last):
  File "D:\Python\Anaconda3\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "D:\Python\Anaconda3\lib\site-packages\conda_build\main_build.py", line 112, in main
    args_func(args, p)
  File "D:\Python\Anaconda3\lib\site-packages\conda_build\main_build.py", line 321, in args_func
    args.func(args, p)
  File "D:\Python\Anaconda3\lib\site-packages\conda_build\main_build.py", line 280, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "D:\Python\Anaconda3\lib\site-packages\conda_build\build.py", line 397, in build
    create_entry_points(m.get_value('build/entry_points'))
  File "D:\Python\Anaconda3\lib\site-packages\conda_build\scripts.py", line 59, in create_entry_points
    for cmd, module, func in iter_entry_points(items):
  File "D:\Python\Anaconda3\lib\site-packages\conda_build\scripts.py", line 32, in iter_entry_points
    m = entry_pat.match(item)
TypeError: expected string or buffer
```

The output of `conda info --all`:
```
Current conda install:

             platform : win-64
        conda version : 3.9.1
  conda-build version : 1.11.0
       python version : 3.4.1.final.0
     requests version : 2.5.3
     root environment : D:\Python\Anaconda3  (writable)
  default environment : D:\Python\Anaconda3
     envs directories : D:\Python\Anaconda3\envs
        package cache : D:\Python\Anaconda3\pkgs
         channel URLs : https://conda.binstar.org/t/<TOKEN>/manmadescience/win-64/
                        https://conda.binstar.org/t/<TOKEN>/manmadescience/noarch/
                        http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/win-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\MRYETTI\.condarc
    is foreign system : False

# conda environments:
#
_build                   D:\Python\Anaconda3\envs\_build
_test                    D:\Python\Anaconda3\envs\_test
root                  *  D:\Python\Anaconda3

sys.version: 3.4.1 |Anaconda 2.1.0 (64-bit)| (default...
sys.prefix: D:\Python\Anaconda3
sys.executable: D:\Python\Anaconda3\python.exe
conda location: D:\Python\Anaconda3\lib\site-packages\conda
conda-build: D:\Python\Anaconda3\Scripts\conda-build.exe
conda-convert: D:\Python\Anaconda3\Scripts\conda-convert.exe
conda-develop: D:\Python\Anaconda3\Scripts\conda-develop.exe
conda-env: D:\Python\Anaconda3\Scripts\conda-env.exe
conda-index: D:\Python\Anaconda3\Scripts\conda-index.exe
conda-inspect: D:\Python\Anaconda3\Scripts\conda-inspect.exe
conda-metapackage: D:\Python\Anaconda3\Scripts\conda-metapackage.exe
conda-pipbuild: D:\Python\Anaconda3\Scripts\conda-pipbuild.exe
conda-server: D:\Python\Anaconda3\Scripts\conda-server.exe
conda-skeleton: D:\Python\Anaconda3\Scripts\conda-skeleton.exe
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
PATH: C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;D:\cygwin64\bin\;D:\Python\Anaconda3;D:\Python\Anaconda3\Scripts
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license
```

I googled a lot and it seems in most cases the errors are being caused by wrong or missing settings in meta.yaml, but I can't find the error source here.

**Comment by asmeurer** [comment]
Looks like the problem is with the way modulegraph has its setup.py (it has a newline after the `=` in its `setup.cfg`). See https://bitbucket.org/ronaldoussoren/modulegraph/src/1e8f74ef92a5d317619c1ba81b358124dbaca284/setup.py?at=default. To fix the recipe, remove the empty `-` in the `entry_points` section.

**Comment by Manmadescience** [comment]
That did the trick, also the recipe for macholib had the same issue. Thanks again!
