### ISSUE TITLE
conda build traceback in _combine_spec_dictionaries

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#3404]
Don't have a MWE yet, but hit this on CI with CB v3.17.8 on Windows:
```Traceback (most recent call last):
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\lib\site-packages\conda_build\cli\main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\lib\site-packages\conda_build\cli\main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\lib\site-packages\conda_build\api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\lib\site-packages\conda_build\build.py", line 2292, in build_tree
    bypass_env_check=True)
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\lib\site-packages\conda_build\render.py", line 803, in render_recipe
    variants = get_package_variants(m, variants=variants)
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\lib\site-packages\conda_build\variants.py", line 517, in get_package_variants
    combined_spec = combine_specs(specs, log_output=config.verbose)
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\lib\site-packages\conda_build\variants.py", line 277, in combine_specs
    log_output=log_output)
  File "C:\ci\containers\000037pqvih\tmp\build\80754af9\mc\lib\site-packages\conda_build\variants.py", line 245, in _combine_spec_dictionaries
    values[k] = v.copy()
AttributeError: 'str' object has no attribute 'copy'
```

**Comment by 183amir** [comment]
This happens with `zip_keys` in a variant file like below:
```yaml
c_compiler_version:            # [unix]
  - 11                         # [osx]
  - 9                          # [linux]
cxx_compiler_version:          # [unix]
  - 11                         # [osx]
  - 9                          # [linux]
fortran_compiler_version:      # [unix or win64]
  - 11                         # [osx and arm64]
  - 9                          # [osx and x86_64]
  - 9                          # [linux]
  - 5                          # [win64]


python:
  # part of a zip_keys: python, python_impl, numpy
  - 3.8.* *_cpython
python_impl:
  # part of a zip_keys: python, python_impl, numpy
  - cpython

zip_keys:
  -                             # [unix]
    - c_compiler_version        # [unix]
    - cxx_compiler_version      # [unix]
    - fortran_compiler_version  # [unix]
-
   - python
   - numpy
   - python_impl

numpy:
  # part of a zip_keys: python, python_impl, numpy
  - 1.19.5
```
I don't understand why, but, commenting:
```yaml
-
   - python
   - numpy
   - python_impl
```
fixed it.
