### ISSUE TITLE
conda build fails when collecting build statistics

### ISSUE THREAD

**Issue by tigarmo** [conda/conda-build#3405]
### Actual Behavior

`conda build` fails when handling the statistics of the build itself, during the step that I assume is after building and before testing:

```
12:00:21 -- Installing: S:/Miniconda/conda-bld/vtk_1550759924047/_h_env/Lib/site-packages/vtk/vtkViewsInfovisPython.pyd
12:00:21 
12:00:21 (%BUILD_PREFIX%) %SRC_DIR%\build>if errorlevel 1 exit 1 
12:00:21 
12:00:21 Resource usage statistics from building vtk:
12:00:21    Process count: 20
12:00:21    CPU time: Sys=0:01:12.3, User=0:02:56.0
12:00:21    Memory: 669.4M
12:00:21    Disk usage: 9.8G
12:00:21    Time elapsed: 0:20:36.0
12:00:21 
12:00:21 Traceback (most recent call last):
12:00:21   File "S:\Miniconda\Scripts\conda-build-script.py", line 10, in <module>
12:00:21     sys.exit(main())
12:00:21   File "S:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 456, in main
12:00:21     execute(sys.argv[1:])
12:00:21   File "S:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 447, in execute
12:00:21     verify=args.verify, variants=args.variants)
12:00:21   File "S:\Miniconda\lib\site-packages\conda_build\api.py", line 208, in build
12:00:21     notest=notest, need_source_download=need_source_download, variants=variants)
12:00:21   File "S:\Miniconda\lib\site-packages\conda_build\build.py", line 2314, in build_tree
12:00:21     notest=notest,
12:00:21   File "S:\Miniconda\lib\site-packages\conda_build\build.py", line 1482, in build
12:00:21     stats[stats_key(m, 'build')] = build_stats
12:00:21   File "S:\Miniconda\lib\site-packages\conda_build\build.py", line 96, in stats_key
12:00:21     used_loop_vars = metadata.get_used_loop_vars()
12:00:21   File "S:\Miniconda\lib\site-packages\conda_build\metadata.py", line 2062, in get_used_loop_vars
12:00:21     force_global=force_global)
12:00:21   File "S:\Miniconda\lib\site-packages\conda_build\metadata.py", line 2063, in <setcomp>
12:00:21     if var in self.get_loop_vars()}
12:00:21   File "S:\Miniconda\lib\site-packages\conda_build\metadata.py", line 2058, in get_loop_vars
12:00:21     return variants.get_vars(_variants, loop_only=True)
12:00:21   File "S:\Miniconda\lib\site-packages\conda_build\variants.py", line 542, in get_vars
12:00:21     special_keys.update(set(ensure_list(variants[0].get('extend_keys'))))
12:00:21 TypeError: 'NoneType' object is not subscriptable
```
### Expected Behavior

Expected the package to build normally.

### Steps to Reproduce

This is my [meta.yaml](https://gist.github.com/tigarmo/e2ca75e083bbe46945804723e2a63f9b). It's taken from the recipe for VTK 7.1.1 from conda-forge, with the modifications where I removed the `toolchain` dependency, modified the features and build number and added the `vs2015_win-64` dependency.

##### `Output of conda info`

```
    active environment : None
      user config file : C:\Users\jenkins\.condarc
populated config files : S:\Miniconda\.condarc
                         S:\WS\.condarc
         conda version : 4.6.3
   conda-build version : 3.17.8
        python version : 3.7.1.final.0
      base environment : S:\Miniconda  (writable)
          channel URLs : https://internal/conda-channel/esss/win-64
                         https://internal/conda-channel/esss/noarch
                         https://internal/conda-channel/mirror-main/win-64
                         https://internal/conda-channel/mirror-main/noarch
                         https://internal/conda-channel/mirror-conda-forge/win-64
                         https://internal/conda-channel/mirror-conda-forge/noarch
         package cache : S:\Miniconda\pkgs
                         C:\Users\jenkins\.conda\pkgs
                         C:\Users\jenkins\AppData\Local\conda\conda\pkgs
      envs directories : S:\Miniconda\envs
                         C:\Users\jenkins\.conda\envs
                         C:\Users\jenkins\AppData\Local\conda\conda\envs
              platform : win-64
            user-agent : conda/4.6.3 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
         administrator : True
            netrc file : None
          offline mode : False
```

We have a custom channel there but conda-build comes from conda-forge. Thank you for your time and let me know if I can provide more info.

**Comment by tigarmo** [comment]
We figured it out: removing the `extra` section from the recipe wholesale caused the build to work fine. I don't know why but it might be relevant to you.
Thanks and sorry for the noise!
