### ISSUE TITLE
Build issue for pipbuild

### ISSUE THREAD

**Issue by vfilimonov** [conda/conda-build#341]
When doing `conda pipbuild odo` the following exception was raised:

```
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-pipbuild-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 77, in
 main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda_build\main_build.py", line 308, in a
rgs_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 350, i
n execute
    build_package(package, version)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 313, i
n build_package
    build_package(depend)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 303, i
n build_package
    directory, dependencies = make_recipe(package, version)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 245, i
n make_recipe
    depends = get_all_dependencies(package, version)
  File "C:\Anaconda\lib\site-packages\conda_build\main_pipbuild.py", line 215, i
n get_all_dependencies
    ret = subprocess.Popen(cmd2.split()).wait()
  File "C:\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

Result of `conda info`:

```
Current conda install:

             platform : win-64
        conda version : 3.9.1
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.5.3
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/win-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by vfilimonov** [comment]
Possible duplicate of an issue #331

**Comment by msarahan** [comment]
pipbuild no longer exists.  You need to do (at least) 2 steps now:

1. conda skeleton pypi (package name)
2. try building with ``conda build (package name)``
3. troubleshoot as necessary, or if it worked, great, go use your package
