### ISSUE TITLE
Combination of Python 3.7.1 + Conda Build 3.17.8 + Sacred 0.7.4 causing conda build --test to fail 

### ISSUE THREAD

**Issue by huamichaelchen** [conda/conda-build#3431]
**NOTE**: The way I invoke conda test is as following: 

```bash
conda build --test --no-long-test-prefix --python=37 --channel "file://work/dist/conda" --channel conda-forge ./dist/conda/linux-64/kyber-evaluation-0.2.2+63.g25bb6a2.dirty-py37_0.tar.bz2
```
The reasoning being after conda build 3.16.0, conda no longer offers conda build --test on conda.recipes. See more details here: #3421 

### Actual Behavior

</details>

<details><summary>Actual Errors</summary>

```bash
conda build --test --no-long-test-prefix --python=37 --channel "file://work/dist/conda" --channel conda-forge ./dist/conda/linux-64/kyber-evaluation-0.2.2+63.g25bb6a2.dirty-py37_0.tar.bz2 
TEST START: ./dist/conda/linux-64/kyber-evaluation-0.2.2+63.g25bb6a2.dirty-py37_0.tar.bz2
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Renaming work directory,  /opt/conda/conda-bld/work  to  /opt/conda/conda-bld/work_moved_kyber-evaluation-0.2.2+63.g25bb6a2.dirty-py37_0_linux-64
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda/conda-bld/_test_env


The following NEW packages will be INSTALLED:

    appdirs:          1.4.3-py_1                          conda-forge            
    asn1crypto:       0.24.0-py37_1003                    conda-forge            
    atomicwrites:     1.3.0-py_0                          conda-forge            
    attrs:            19.1.0-py_0                         conda-forge            
    beautifulsoup4:   4.7.1-py37_1001                     conda-forge            
    blas:             1.1-openblas                        conda-forge            
    bzip2:            1.0.6-h14c3975_1002                 conda-forge            
    c-ares:           1.15.0-h14c3975_1001                conda-forge            
    ca-certificates:  2018.11.29-ha4d7672_0               conda-forge            
    certifi:          2018.11.29-py37_1000                conda-forge            
    cffi:             1.12.2-py37h9745a5d_0               conda-forge            
    chardet:          3.0.4-py37_1003                     conda-forge            
    click:            7.0-py_0                            conda-forge            
    cryptography:     2.5-py37hb7f436b_1                  conda-forge            
    docker-py:        3.7.0-py37_1000                     conda-forge            
    docker-pycreds:   0.4.0-py_0                          conda-forge            
    docopt:           0.6.2-py_1                          conda-forge            
    geos:             3.7.1-hf484d3e_1000                 conda-forge            
    gitdb2:           2.0.5-py_0                          conda-forge            
    gitpython:        2.1.11-py_0                         conda-forge            
    grpcio:           1.16.0-py37h4f00d22_1000            conda-forge            
    icu:              58.2-hf484d3e_1000                  conda-forge            
    idna:             2.8-py37_1000                       conda-forge            
    jsonpickle:       1.1-py_0                            conda-forge            
    kyber-evaluation: 0.2.2+63.g25bb6a2.dirty-py37_0      file:///work/dist/conda
    libffi:           3.2.1-hf484d3e_1005                 conda-forge            
    libgcc-ng:        7.3.0-hdf63c60_0                    conda-forge            
    libgfortran-ng:   7.2.0-hdf63c60_3                    conda-forge            
    libiconv:         1.15-h14c3975_1004                  conda-forge            
    libprotobuf:      3.7.0-hdbcaa40_0                    conda-forge            
    libstdcxx-ng:     7.3.0-hdf63c60_0                    conda-forge            
    libxml2:          2.9.8-h143f9aa_1005                 conda-forge            
    libxslt:          1.1.32-h4785a14_1002                conda-forge            
    lxml:             4.3.2-py37h23eabaa_0                conda-forge            
    more-itertools:   4.3.0-py37_1000                     conda-forge            
    munch:            2.3.2-py_0                          conda-forge            
    mypy:             0.670-py_0                          conda-forge            
    mypy_extensions:  0.4.1-py37_1000                     conda-forge            
    ncurses:          6.1-hf484d3e_1002                   conda-forge            
    numpy:            1.16.2-py37_blas_openblash1522bff_0 conda-forge             [blas_openblas]
    openblas:         0.3.3-h9ac9557_1001                 conda-forge            
    openssl:          1.0.2r-h14c3975_0                   conda-forge            
    osi3:             3.1.2-py37_0                        local                  
    packaging:        19.0-py_0                           conda-forge            
    pandas:           0.24.1-py37hf484d3e_0               conda-forge            
    pip:              19.0.3-py37_0                       conda-forge            
    pluggy:           0.9.0-py_0                          conda-forge            
    protobuf:         3.7.0-py37hf484d3e_0                conda-forge            
    psutil:           5.4.8-py37h14c3975_1000             conda-forge            
    py:               1.8.0-py_0                          conda-forge            
    py-cpuinfo:       4.0.0-py_0                          conda-forge            
    pycparser:        2.19-py_0                           conda-forge            
    pyopenssl:        19.0.0-py37_0                       conda-forge            
    pyparsing:        2.3.1-py_0                          conda-forge            
    pysocks:          1.6.8-py37_1002                     conda-forge            
    pytest:           4.3.0-py37_0                        conda-forge            
    python:           3.7.1-hd21baee_1001                 conda-forge            
    python-dateutil:  2.8.0-py_0                          conda-forge            
    pytz:             2018.9-py_0                         conda-forge            
    pyyaml:           3.13-py37h14c3975_1001              conda-forge            
    readline:         7.0-hf8c457e_1001                   conda-forge            
    requests:         2.21.0-py37_1000                    conda-forge            
    sacred:           0.7.4-py37_0                        file:///work/dist/conda
    setuptools:       40.8.0-py37_0                       conda-forge            
    shapely:          1.6.4-py37h092830f_1002             conda-forge            
    six:              1.12.0-py37_1000                    conda-forge            
    smmap2:           2.0.5-py_0                          conda-forge            
    soupsieve:        1.8-py37_0                          conda-forge            
    sqlite:           3.26.0-h67949de_1000                conda-forge            
    tabulate:         0.8.3-py_0                          conda-forge            
    tinydb:           3.12.2-py_0                         conda-forge            
    tk:               8.6.9-h84994c4_1000                 conda-forge            
    tqdm:             4.31.1-py_0                         conda-forge            
    typed-ast:        1.2.0-py37h14c3975_1000             conda-forge            
    typing:           3.6.4-py37_0                                               
    urllib3:          1.24.1-py37_1000                    conda-forge            
    websocket-client: 0.55.0-py37_0                       conda-forge            
    wheel:            0.33.1-py37_0                       conda-forge            
    wrapt:            1.11.1-py37h14c3975_0               conda-forge            
    xz:               5.2.4-h14c3975_1001                 conda-forge            
    yaml:             0.1.7-h14c3975_1001                 conda-forge            
    zlib:             1.2.11-h14c3975_1004                conda-forge            

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
WARNING: symlink_conda() is deprecated.
export PREFIX=/opt/conda/conda-bld/_test_env
export SRC_DIR=/opt/conda/conda-bld/test_tmp
import: 'kyber.evaluation'
+ python -c 'import kyber.evaluation as pkg; assert pkg.__version__=='\''0.2.2+63.g25bb6a2.dirty'\'''
+ kcl --help
Traceback (most recent call last):
  File "/opt/conda/conda-bld/_test_env/bin/kcl", line 7, in <module>
    from kyber.evaluation.cli import main
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/kyber/evaluation/cli/__init__.py", line 3, in <module>
    from .experiments import experiments
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/kyber/evaluation/cli/experiments.py", line 6, in <module>
    from kyber.evaluator.experiments import exp_exp
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/kyber/evaluator/experiments.py", line 12, in <module>
    from kyber.evaluator.evaluator import run_evaluator
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/kyber/evaluator/evaluator.py", line 11, in <module>
    eval_exp = Experiment()
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/sacred/experiment.py", line 80, in __init__
    _caller_globals=caller_globals)
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/sacred/ingredient.py", line 55, in __init__
    gather_sources_and_dependencies(_caller_globals, self.base_dir)
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/sacred/dependencies.py", line 487, in gather_sources_and_dependencies
    sources = gather_sources(globs, base_dir)
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/sacred/dependencies.py", line 438, in get_sources_from_imported_modules
    return get_sources_from_modules(iterate_imported_modules(globs), base_path)
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/sacred/dependencies.py", line 407, in get_sources_from_modules
    filename = os.path.abspath(mod.__file__)
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/posixpath.py", line 371, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Leaving build/test directories:
  Work:
 /opt/conda/conda-bld/work 
  Test:
 /opt/conda/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /opt/conda/conda-bld/_test_env 
  Build:
source activate  /opt/conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho 


TESTS FAILED: kyber-evaluation-0.2.2+63.g25bb6a2.dirty-py37_0.tar.bz2
```

</details>

### My Suspicion what could be the issue

It seems that during a `conda build --test`, conda will 
1. copy the stuff needs to be tested to a separate temp directory 
```bash
/opt/conda/conda-bld$ ls
_test_env  broken  channeldata.json  icons  index.html  linux-64  noarch  rss.xml  src_cache  test_tmp  work  work_moved_kyber-evaluation-0.2.2+63.g25bb6a2.dirty-py37_0_linux-64
```
2. generate some bash scripts on the fly 
```bash
/opt/conda/conda-bld/test_tmp$ ls
conda_test_env_vars.sh  conda_test_runner.sh  run_test.py  run_test.sh  sample_data  setup.cfg  test_time_dependencies.json  tests
```
3. create and activate a separate conda environment just to run the test 
```bash
/opt/conda/conda-bld/test_tmp$ cat conda_test_env_vars.sh 
set -e
source "/opt/conda/bin/activate" "/opt/conda/conda-bld/_test_env"
```
4. Then according to the test error message above, it seems that somehow Python 3.7 has a different way to deal with filepath, where the combination of `sacred 0.7.4 + python3.7 + conda-build 3.17.8 + conda 4.6.7` will not work happily together? 

```bash
Traceback (most recent call last):
  File "/opt/conda/conda-bld/_test_env/bin/kcl", line 7, in <module>
    from kyber.evaluation.cli import main
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/kyber/evaluation/cli/__init__.py", line 3, in <module>
    from .experiments import experiments
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/kyber/evaluation/cli/experiments.py", line 6, in <module>
    from kyber.evaluator.experiments import exp_exp
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/kyber/evaluator/experiments.py", line 12, in <module>
    from kyber.evaluator.evaluator import run_evaluator
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/kyber/evaluator/evaluator.py", line 11, in <module>
    eval_exp = Experiment()
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/sacred/experiment.py", line 80, in __init__
    _caller_globals=caller_globals)
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/sacred/ingredient.py", line 55, in __init__
    gather_sources_and_dependencies(_caller_globals, self.base_dir)
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/sacred/dependencies.py", line 487, in gather_sources_and_dependencies
    sources = gather_sources(globs, base_dir)
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/sacred/dependencies.py", line 438, in get_sources_from_imported_modules
    return get_sources_from_modules(iterate_imported_modules(globs), base_path)
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/site-packages/sacred/dependencies.py", line 407, in get_sources_from_modules
    filename = os.path.abspath(mod.__file__)
  File "/opt/conda/conda-bld/_test_env/lib/python3.7/posixpath.py", line 371, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Expected Behavior

<details><summary>With everything else equal, as in, conda-build 3.17.8, sacred 0.7.4, but if I change to use python 3.6.x, the conda bulid --test will pass </summary>

```bash
TEST START: /builds/kyber/evaluation/kyber-evaluation/dist/conda/linux-64/kyber-evaluation-0.2.2+63.g25bb6a2-py36_0.tar.bz2
Renaming work directory,  /opt/conda/conda-bld/work  to  /opt/conda/conda-bld/work_moved_kyber-evaluation-0.2.2+63.g25bb6a2-py36_0_linux-64
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda/conda-bld/_test_env


The following NEW packages will be INSTALLED:

    appdirs:          1.4.3-py_1                          conda-forge                                                
    asn1crypto:       0.24.0-py36_1003                    conda-forge                                                
    atomicwrites:     1.3.0-py_0                          conda-forge                                                
    attrs:            19.1.0-py_0                         conda-forge                                                
    beautifulsoup4:   4.7.1-py36_1001                     conda-forge                                                
    blas:             1.1-openblas                        conda-forge                                                
    c-ares:           1.15.0-h14c3975_1001                conda-forge                                                
    ca-certificates:  2018.11.29-ha4d7672_0               conda-forge                                                
    certifi:          2018.11.29-py36_1000                conda-forge                                                
    cffi:             1.12.2-py36h9745a5d_0               conda-forge                                                
    chardet:          3.0.4-py36_1003                     conda-forge                                                
    click:            7.0-py_0                            conda-forge                                                
    cryptography:     2.5-py36hb7f436b_1                  conda-forge                                                
    docker-py:        3.7.0-py36_1000                     conda-forge                                                
    docker-pycreds:   0.4.0-py_0                          conda-forge                                                
    docopt:           0.6.2-py_1                          conda-forge                                                
    geos:             3.7.1-hf484d3e_1000                 conda-forge                                                
    gitdb2:           2.0.5-py_0                          conda-forge                                                
    gitpython:        2.1.11-py_0                         conda-forge                                                
    grpcio:           1.16.0-py36h4f00d22_1000            conda-forge                                                
    icu:              58.2-hf484d3e_1000                  conda-forge                                                
    idna:             2.8-py36_1000                       conda-forge                                                
    jsonpickle:       1.1-py_0                            conda-forge                                                
    kyber-evaluation: 0.2.2+63.g25bb6a2-py36_0            file:///builds/kyber/evaluation/kyber-evaluation/dist/conda
    libffi:           3.2.1-hf484d3e_1005                 conda-forge                                                
    libgcc-ng:        7.3.0-hdf63c60_0                    conda-forge                                                
    libgfortran-ng:   7.2.0-hdf63c60_3                    conda-forge                                                
    libiconv:         1.15-h14c3975_1004                  conda-forge                                                
    libprotobuf:      3.7.0-hdbcaa40_0                    conda-forge                                                
    libstdcxx-ng:     7.3.0-hdf63c60_0                    conda-forge                                                
    libxml2:          2.9.8-h143f9aa_1005                 conda-forge                                                
    libxslt:          1.1.32-h4785a14_1002                conda-forge                                                
    lxml:             4.3.2-py36h23eabaa_0                conda-forge                                                
    more-itertools:   4.3.0-py36_1000                     conda-forge                                                
    munch:            2.3.2-py_0                          conda-forge                                                
    mypy:             0.670-py_0                          conda-forge                                                
    mypy_extensions:  0.4.1-py36_1000                     conda-forge                                                
    ncurses:          6.1-hf484d3e_1002                   conda-forge                                                
    numpy:            1.16.2-py36_blas_openblash1522bff_0 conda-forge                                                 [blas_openblas]
    openblas:         0.3.3-h9ac9557_1001                 conda-forge                                                
    openssl:          1.0.2r-h14c3975_0                   conda-forge                                                
    osi3:             3.1.2-py36_0                        file:///builds/kyber/evaluation/kyber-evaluation/dist/conda
    packaging:        19.0-py_0                           conda-forge                                                
    pandas:           0.24.1-py36hf484d3e_0               conda-forge                                                
    pip:              19.0.3-py36_0                       conda-forge                                                
    pluggy:           0.9.0-py_0                          conda-forge                                                
    protobuf:         3.7.0-py36hf484d3e_0                conda-forge                                                
    psutil:           5.4.8-py36h14c3975_1000             conda-forge                                                
    py:               1.8.0-py_0                          conda-forge                                                
    py-cpuinfo:       4.0.0-py_0                          conda-forge                                                
    pycparser:        2.19-py_0                           conda-forge                                                
    pyopenssl:        19.0.0-py36_0                       conda-forge                                                
    pyparsing:        2.3.1-py_0                          conda-forge                                                
    pysocks:          1.6.8-py36_1002                     conda-forge                                                
    pytest:           4.3.0-py36_0                        conda-forge                                                
    python:           3.6.7-hd21baee_1002                 conda-forge                                                
    python-dateutil:  2.8.0-py_0                          conda-forge                                                
    pytz:             2018.9-py_0                         conda-forge                                                
    pyyaml:           3.13-py36h14c3975_1001              conda-forge                                                
    readline:         7.0-hf8c457e_1001                   conda-forge                                                
    requests:         2.21.0-py36_1000                    conda-forge                                                
    sacred:           0.7.4-py36_0                        file:///builds/kyber/evaluation/kyber-evaluation/dist/conda
    setuptools:       40.8.0-py36_0                       conda-forge                                                
    shapely:          1.6.4-py36h092830f_1002             conda-forge                                                
    six:              1.12.0-py36_1000                    conda-forge                                                
    smmap2:           2.0.5-py_0                          conda-forge                                                
    soupsieve:        1.8-py36_0                          conda-forge                                                
    sqlite:           3.26.0-h67949de_1000                conda-forge                                                
    tabulate:         0.8.3-py_0                          conda-forge                                                
    tinydb:           3.12.2-py_0                         conda-forge                                                
    tk:               8.6.9-h84994c4_1000                 conda-forge                                                
    tqdm:             4.31.1-py_0                         conda-forge                                                
    typed-ast:        1.2.0-py36h14c3975_1000             conda-forge                                                
    typing:           3.6.4-py36_0                        conda-forge                                                
    urllib3:          1.24.1-py36_1000                    conda-forge                                                
    websocket-client: 0.55.0-py36_0                       conda-forge                                                
    wheel:            0.33.1-py36_0                       conda-forge                                                
    wrapt:            1.11.1-py36h14c3975_0               conda-forge                                                
    xz:               5.2.4-h14c3975_1001                 conda-forge                                                
    yaml:             0.1.7-h14c3975_1001                 conda-forge                                                
    zlib:             1.2.11-h14c3975_1004                conda-forge                                                

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ python -c 'import kyber.evaluation as pkg; assert pkg.__version__=='\''0.2.2+63.g25bb6a2'\'''
+ PYTHONDONTWRITEBYTECODE=1
+ pytest tests
+ kcl --help
+ exit 0
export PREFIX=/opt/conda/conda-bld/_test_env
export SRC_DIR=/opt/conda/conda-bld/test_tmp
import: 'kyber.evaluation'
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-4.3.0, py-1.8.0, pluggy-0.9.0
rootdir: $SRC_DIR, inifile: setup.cfg
collected 25 items

tests/test_cli.py ...                                                    [ 12%]
tests/test_messages.py ..                                                [ 20%]
tests/evaluation/test_experiments.py .                                   [ 24%]
tests/evaluator/test_events_in_sketchpad.py ...                          [ 36%]
tests/evaluator/test_metrics.py ............                             [ 84%]
tests/evaluator/test_trigger_manager.py ....                             [100%]

========================= 25 passed in 109.33 seconds ==========================
```

</details>

### Steps to Reproduce
The error log above is the easiest way to "reproduce" it, however, if you truly want to reproduce it, I think you can try with a simple new project setup. 

1. Spin up a docker container 
2. which has python 3.7.x installed, conda-build 3.17.x installed, conda 4.6.x installed, sacred 0.7.4 installed
3. with a simple project code where it imports sacred and create an instance of scared's Experiment() object 
4. create a test case for testing the import 
With this setup, you should get the same error as above. 

##### `Output of conda info`
NOTE: everything runs inside a docker container which maps to the host docker daemon through docker socket, however, I don't think this would matter tho :)  

<details><summary>Environment Info Dump</summary>

```bash
$ python -V
Python 3.7.1
$ pip -V
pip 19.0.3 from /opt/conda/envs/kyber-evaluation/lib/python3.7/site-packages/pip (python 3.7)
$ conda -V
conda 4.6.7
$ conda build -V
conda-build 3.17.8
```

**Comment by jjhelmus** [comment]
Does the `kcl --help` command fail if you install the package into a conda environment and run in outside of the conda build environment?   If so then this is not an issue with conda-build but rather a bug in sacred.

**Comment by huamichaelchen** [comment]
Hi @jjhelmus , thanks for taking a look again :pray: 

I'm sorry, I forgot to close this issue. Yes, we found the bug in sacred version 0.7.4, this is not a conda issue. I will close this issue if I can :smile: 

In master, it takes into account of [this](https://github.com/IDSIA/sacred/blob/master/sacred/dependencies.py#L404), whereas in their 0.7.4 version they didn't take into account of [this](https://github.com/IDSIA/sacred/blob/0.7.4/sacred/dependencies.py#L404)

**Comment by malbergo** [comment]
Hi,

I am having this problem now. Is there a newer version of sacred to pip install? when I pip install sacred now, I still get 0.7.4
