### ISSUE TITLE
3.17.x does not work on ppc64le

### ISSUE THREAD

**Issue by isuruf** [conda/conda-build#3445]
### Actual Behavior

Following happens when conda-build is fixing a package.

```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1628, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 954, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 818, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 1018, in post_build
    check_overlinking(m, files)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 955, in check_overlinking
    m.config.channel_urls)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 882, in check_overlinking_impl
    build_prefix, build_prefix_substitution)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 603, in _collect_needed_dsos
    envroot=run_prefix)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 606, in __call__
    value = self.func(*args, **kw)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 635, in get_linkages_memoized
    recurse=recurse, sysroot=sysroot, envroot=envroot, arch=arch)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 417, in get_linkages
    sysroot=sysroot, envroot=envroot, arch=arch)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/os_utils/liefldd.py", line 340, in inspect_linkages_lief
    binary = lief.parse(filename)
NameError: name 'lief' is not defined
```

### Expected Behavior

Work fine

### Steps to Reproduce

Install conda-build from conda-forge channel and build conda-feedstock from conda-forge

##### `Output of conda info`

```

```

**Comment by isuruf** [comment]
Note that `py-lief` doesn't exist on ppc64le as there are build issues on ppc64le
