### ISSUE TITLE
Unsatisfiable dependencies for platform linux-64: {"xz[version='>=5.2.4,<5.3.0a0']", "libgcc-ng[version='>=7.3.0']", "openssl[version='>=1.1.1a,<1.1.2a']", "sqlite[version='>=3.26.0,<4.0a0']", "libstdcxx-ng[version='>=7.3.0']", "tk[version='>=8.6.9,<8.7.0a0']"}

### ISSUE THREAD

**Issue by khur12** [conda/conda-build#3456]
### Actual Behavior
I'm getting the following error when I try to build my conda package.
```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Copying /opt/github/ra to /opt/miniconda3/conda-bld/ra_1553279342709/work
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for ra
INFO:conda_build.metadata:Attempting to finalize metadata for ra
Collecting package metadata: ...working... done
Solving environment: ...working... failed

Leaving build/test directories:
  Work:
 /opt/miniconda3/conda-bld/work 
  Test:
 /opt/miniconda3/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /opt/miniconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold 
  Build:
source activate  /opt/miniconda3/conda-bld/_build_env 


Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/conda_build/environ.py", line 753, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 85, in decorated
    return f(*args, **kwds)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/plan.py", line 473, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 107, in solve_for_transaction
    force_remove, force_reinstall)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 145, in solve_for_diff
    force_remove)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 242, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 85, in decorated
    return f(*args, **kwds)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 465, in _run_sat
    conflicting_specs = ssc.r.get_conflicting_specs(tuple(final_environment_specs))
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 852, in get_conflicting_specs
    reduced_index = self.get_reduced_index(specs)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 85, in decorated
    return f(*args, **kwds)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 356, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 244, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - python=3.7.1 -> libgcc-ng[version='>=7.3.0']
  - python=3.7.1 -> libstdcxx-ng[version='>=7.3.0']
  - python=3.7.1 -> openssl[version='>=1.1.1a,<1.1.2a']
  - python=3.7.1 -> sqlite[version='>=3.26.0,<4.0a0']
  - python=3.7.1 -> tk[version='>=8.6.9,<8.7.0a0']
  - python=3.7.1 -> xz[version='>=5.2.4,<5.3.0a0']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/opt/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/opt/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 1324, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/opt/miniconda3/lib/python3.7/site-packages/conda_build/render.py", line 735, in expand_outputs
    for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/opt/miniconda3/lib/python3.7/site-packages/conda_build/metadata.py", line 2038, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda_build/metadata.py", line 721, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda_build/render.py", line 509, in finalize_metadata
    exclude_pattern)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda_build/render.py", line 371, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda_build/render.py", line 359, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda_build/render.py", line 143, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/opt/miniconda3/lib/python3.7/site-packages/conda_build/environ.py", line 755, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"xz[version='>=5.2.4,<5.3.0a0']", "libgcc-ng[version='>=7.3.0']", "openssl[version='>=1.1.1a,<1.1.2a']", "sqlite[version='>=3.26.0,<4.0a0']", "libstdcxx-ng[version='>=7.3.0']", "tk[version='>=8.6.9,<8.7.0a0']"}
```

### Steps to Reproduce

I'm simply running conda build <directory> and I run into this issue. This was working perfectly fine before about a week ago when I tried to run it then, so I'm wondering whether the issue is not on my end.

##### `Output of conda info`

```
 active environment : base
    active env location : /opt/miniconda3
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.6.8
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
       base environment : /opt/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/3.7.1 Linux/3.10.0-957.1.3.el7.x86_64 centos/7.6.1810 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False


```

**Comment by msarahan** [comment]
It looks like you have none of the defaults channels in your mix, and you've actually edited your post to hide some internal channel.  Those packages are not available because they're not on your channels.  Please don't exclude our channels then complain about missing packages.
