### ISSUE TITLE
Unable to build on a fresh Windows environment with source.git_url

### ISSUE THREAD

**Issue by tswicegood** [conda/conda-build#346]
Ran into this while trying to build the Anaconda Launcher on Win-64.

```
C:\Users\builder\anaconda-launcher>conda build conda.recipe
Removing old build directory
Removing old work directory
BUILD START: anaconda-launcher-0.2.0alpha-GIT_STUB
Fetching package metadata: ........
Solving package specifications: .
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    nwjs-0.12.0.3alpha         |                1        38.0 MB
    gulp-3.8.11                |                0         417 KB
    ------------------------------------------------------------
                                           Total:        38.4 MB

The following NEW packages will be INSTALLED:

    bower: 1.3.12-0
    gulp:  3.8.11-0
    iojs:  1.2.0-1
    nwjs:  0.12.0.3alpha-1

Fetching packages ...
nwjs-0.12.0.3a 100% |###############################| Time: 0:00:00  94.36 MB/s
gulp-3.8.11-0. 100% |###############################| Time: 0:00:01 364.45 kB/s
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
[      COMPLETE      ] |#################################################| 100%
Removing old work directory
Cloning into bare repository '/cygdrive/c/Users/builder/Miniconda/conda-bld/git_
cache/Users_builder_anaconda-launcher'...
done.
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\builder\Miniconda\Scripts\conda-build-script.py", line 4, in <m
odule>
    sys.exit(main())
  File "C:\Users\builder\Miniconda\lib\site-packages\conda_build\main_build.py",
 line 112, in main
    args_func(args, p)
  File "C:\Users\builder\Miniconda\lib\site-packages\conda_build\main_build.py",
 line 321, in args_func
    args.func(args, p)
  File "C:\Users\builder\Miniconda\lib\site-packages\conda_build\main_build.py",
 line 280, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "C:\Users\builder\Miniconda\lib\site-packages\conda_build\build.py", line
 347, in build
    source.provide(m.path, m.get_section('source'))
  File "C:\Users\builder\Miniconda\lib\site-packages\conda_build\source.py", lin
e 250, in provide
    git_source(meta, recipe_dir)
  File "C:\Users\builder\Miniconda\lib\site-packages\conda_build\source.py", lin
e 115, in git_source
    assert isdir(cache_repo)
AssertionError
```

Output of `conda info`:

```

C:\Users\builder\anaconda-launcher>conda info
Current conda install:

             platform : win-64
        conda version : 3.9.1
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.5.3
     root environment : C:\Users\builder\Miniconda  (writable)
  default environment : C:\Users\builder\Miniconda
     envs directories : C:\Users\builder\Miniconda\envs
        package cache : C:\Users\builder\Miniconda\pkgs
         channel URLs : https://conda.binstar.org/t/<TOKEN>/javascript/win-64/
                        https://conda.binstar.org/t/<TOKEN>/javascript/noarch/
                        http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/win-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\builder\.condarc
    is foreign system : False
```

Output of `conda list`:

```
C:\Users\builder\anaconda-launcher>conda list
# packages in environment at C:\Users\builder\Miniconda:
#
binstar                   0.10.1                    <pip>
clyent                    0.3.2                    py27_0
conda                     3.9.1                    py27_0
conda-build               1.11.0                   py27_0
conda-env                 2.1.3                    py27_0
dateutil                  2.1                      py27_2
jinja2                    2.7.3                    py27_1
markupsafe                0.23                     py27_0
menuinst                  1.0.4                    py27_0
pip                       6.0.8                    py27_0
psutil                    2.2.1                    py27_0
pycosat                   0.6.1                    py27_0
python                    2.7.9                         1
python-dateutil           1.5                       <pip>
pytz                      2014.9                   py27_0
pyyaml                    3.11                     py27_0
requests                  2.5.3                    py27_0
setuptools                14.0                     py27_0
six                       1.9.0                    py27_0
```

I ran `conda update --all` to make sure everything was current.  `clyent` is now at 0.3.4, instead of 0.3.2, but that's it.  After updating, I ran `conda build conda.recipe` again and ended up with this:

```
C:\Users\builder\anaconda-launcher>conda build conda.recipe
Removing old build directory
Removing old work directory
BUILD START: anaconda-launcher-0.2.0alpha-GIT_STUB
Fetching package metadata: ........
Solving package specifications: .
The following NEW packages will be INSTALLED:

    bower: 1.3.12-0
    gulp:  3.8.11-0
    iojs:  1.2.0-1
    nwjs:  0.12.0.3alpha-1

Linking packages ...
[      COMPLETE      ] |#################################################| 100%
Removing old work directory
fatal: destination path '/cygdrive/c/Users/builder/Miniconda/conda-bld/git_cache
/Users_builder_anaconda-launcher' already exists and is not an empty directory.
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\builder\Miniconda\Scripts\conda-build-script.py", line 4, in <m
odule>
    sys.exit(main())
  File "C:\Users\builder\Miniconda\lib\site-packages\conda_build\main_build.py",
 line 112, in main
    args_func(args, p)
  File "C:\Users\builder\Miniconda\lib\site-packages\conda_build\main_build.py",
 line 321, in args_func
    args.func(args, p)
  File "C:\Users\builder\Miniconda\lib\site-packages\conda_build\main_build.py",
 line 280, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "C:\Users\builder\Miniconda\lib\site-packages\conda_build\build.py", line
 347, in build
    source.provide(m.path, m.get_section('source'))
  File "C:\Users\builder\Miniconda\lib\site-packages\conda_build\source.py", lin
e 250, in provide
    git_source(meta, recipe_dir)
  File "C:\Users\builder\Miniconda\lib\site-packages\conda_build\source.py", lin
e 114, in git_source
    check_call([git, 'clone', '--mirror', git_url, cache_repo_arg], cwd=recipe_d
ir)
  File "C:\Users\builder\Miniconda\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\Git\\cmd\\git
.exe', 'clone', '--mirror', u'../', u'/cygdrive/c/Users/builder/Miniconda/conda-
bld/git_cache/Users_builder_anaconda-launcher']' returned non-zero exit status 1
28
```

I've installed Git via the official installer.  The first install was for the Git GUI, the second install had it add the minimal commands to the Windows Command Prompt.  I think that might be what's causing the `cygdrive` code to appear.  I get the same error message when running via Git Bash and CMD.

Going to try upgrading to Git for Windows v2.3 and see if that solves this issue.

**Comment by asmeurer** [comment]
The appearance of cygdrive is strange. That should be coming from `abspath(expanduser('~/conda-bld'))`.
