### ISSUE TITLE
build failure when tarball contains symlink to directory

### ISSUE THREAD

**Issue by tschoonj** [conda/conda-build#3461]
### Actual Behavior

I am trying to write a recipe for Geant4, but ran into trouble just after the extraction phase:

```
Extracting download
Traceback (most recent call last):
  File "/dls_sw/apps/python/anaconda/1.7.0/64/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-packages/conda_build/build.py", line 1407, in build
    try_download(m, no_download_source=False, raise_error=True)
  File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-packages/conda_build/render.py", line 617, in try_download
    source.provide(metadata)
  File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-packages/conda_build/source.py", line 653, in provide
    timeout=metadata.config.timeout, locking=metadata.config.locking)
  File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-packages/conda_build/source.py", line 161, in unpack
    hoist_single_extracted_folder(folder)
  File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-packages/conda_build/source.py", line 130, in hoist_single_extracted_folder
    shutil.move(os.path.join(nested_folder, entry), os.path.join(tmpdir, entry))
  File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/shutil.py", line 314, in move
    rmtree(src)
  File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/shutil.py", line 246, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/shutil.py", line 244, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link
```

This is due to the unpacked tarball containing a softlink to a directory:

```
lrwxrwxrwx.  1 xol73553 xol73553   12 Mar 26 11:02 CHANGELOG -> ReleaseNotes
drwxrwxr-x.  4 xol73553 xol73553 4096 Dec  7 14:15 cmake
-rw-rw-r--.  1 xol73553 xol73553 2137 Dec  7 14:15 CMakeLists.txt
drwxrwxr-x.  3 xol73553 xol73553 4096 Dec  7 14:15 config
-rw-rw-r--.  1 xol73553 xol73553   70 Dec  7 14:15 CONTRIBUTING.md
drwxrwxr-x.  5 xol73553 xol73553 4096 Dec  7 14:15 environments
drwxrwxr-x.  6 xol73553 xol73553 4096 Dec  7 14:15 examples
-rw-rw-r--.  1 xol73553 xol73553 4029 Dec  7 14:15 LICENSE
drwxrwxr-x.  2 xol73553 xol73553 4096 Dec  7 14:15 ReleaseNotes
drwxrwxr-x. 24 xol73553 xol73553 4096 Dec  7 14:15 source
```

### Expected Behavior

It should just work...

### Steps to Reproduce

Use my recipe for geant4 on Linux:

```yaml
{% set version  = "10.5.0" %}

package:
    name: geant4
    version: {{ version }}
source:
    url: https://github.com/Geant4/geant4/archive/v{{ version }}.tar.gz
    sha256: f0233373da27e47911a527a1912f164739c31cb3eb70c311a8d19ecde585aaf7
build:
    number: '0'
requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make
    host:
        - cmake
    #run:
        #- libgcc-ng
        #- libstdcxx-ng >=7.3.0
        # - qt
        # - xerces-c
about:
    description: 'Geant4 is a toolkit for the simulation of the passage of particles through matter.'
    dev_url: https://github.com/Geant4/geant4
    doc_url: http://geant4.web.cern.ch/support
    home: http://github.com/Geant4/geant4
    license_file: LICENSE
    summary: Geant4 toolkit for the simulation of the passage of particles through
        matter - NIM A 506 (2003) 250-303
extra:
    recipe-maintainers:
        - tschoonj
```
and `build.sh`:

```bash
#!/bin/bash

CMAKE_PLATFORM_FLAGS+=(-DCMAKE_TOOLCHAIN_FILE="${RECIPE_DIR}/cross-linux.cmake")

if [[ ${DEBUG_C} == yes ]]; then
  CMAKE_BUILD_TYPE=Debug
else
  CMAKE_BUILD_TYPE=Release
fi

mkdir geant4-build
cd geant4-build

cmake                                                  \
      -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}  \
      -DCMAKE_INSTALL_PREFIX=${PREFIX}                           \
      -DBUILD_SHARED_LIBS=ON                                   \
      -DBUILD_STATIC_LIBS=ON                                   \
      -DGEANT4_INSTALL_EXAMPLES=ON                             \
      -DGEANT4_INSTALL_DATA=ON                                 \
      -DGEANT4_BUILD_MULTITHREADED=ON                          \
      -DGEANT4_USE_GDML=ON                                     \
      ${CMAKE_PLATFORM_FLAGS[@]} \
      ${SRC_DIR}

make -j${CPU_COUNT} ${VERBOSE_CM}
make install -j${CPU_COUNT}
```

##### `Output of conda info`

```
     active environment : None
       user config file : /home/xol73553/.condarc
 populated config files : /home/xol73553/.condarc
          conda version : 4.6.8
    conda-build version : 3.17.8
         python version : 2.7.15.final.0
       base environment : /dls_sw/apps/python/anaconda/1.7.0/64  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /scratch/conda-pkgs
       envs directories : /home/xol73553/.conda/envs
                          /dls_sw/apps/python/anaconda/1.7.0/64/envs
               platform : linux-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/2.7.15 Linux/2.6.32-754.10.1.el6.x86_64 rhel/6.10 glibc/2.12
                UID:GID : 1213050:1213050
             netrc file : None
           offline mode : False


```

**Comment by shoemakerdr** [comment]
Looks like this duplicates issue #2755, so this issue can probably be closed.

**Comment by jjhelmus** [comment]
> Looks like this duplicates issue #2755, so this issue can probably be closed.

Agreed, closing
