### ISSUE TITLE
KeyError during conda build - v3.18.2

### ISSUE THREAD

**Issue by mstabrin** [conda/conda-build#3546]
Hello, I was trying to build a package but it failed with a KeyError.
It still worked in 3.17.8

### Actual Behavior

The process crashes with a KeyError after not finding needed_dsos_for_file[f]

Seems to be related to 6de42f5 
```
Packaging fftw-mpi
INFO:conda_build.build:Packaging fftw-mpi
Packaging fftw-mpi-3.3.6-0
INFO:conda_build.build:Packaging fftw-mpi-3.3.6-0
number of files: 43
...
...
ERROR :: get_rpaths_raw()=[] and patchelf=/home/participant/LOCAL_INSTALL/SPHIRE/conda-bld/fftw-mpi_1560751508276/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib disagree for /home/participant/LOCAL_INSTALL/SPHIRE/conda-bld/fftw-mpi_1560751508276/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/fftwf-wisdom :: 
ERROR :: get_rpaths_raw()=[] and patchelf=/home/participant/LOCAL_INSTALL/SPHIRE/conda-bld/fftw-mpi_1560751508276/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib disagree for /home/participant/LOCAL_INSTALL/SPHIRE/conda-bld/fftw-mpi_1560751508276/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libfftw3_mpi.so.3.5.6 :: 
Traceback (most recent call last):
  File "/home/participant/LOCAL_INSTALL/SPHIRE/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/participant/LOCAL_INSTALL/SPHIRE/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/home/participant/LOCAL_INSTALL/SPHIRE/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/home/participant/LOCAL_INSTALL/SPHIRE/lib/python3.6/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/participant/LOCAL_INSTALL/SPHIRE/lib/python3.6/site-packages/conda_build/build.py", line 2299, in build_tree
    notest=notest,
  File "/home/participant/LOCAL_INSTALL/SPHIRE/lib/python3.6/site-packages/conda_build/build.py", line 1596, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/home/participant/LOCAL_INSTALL/SPHIRE/lib/python3.6/site-packages/conda_build/build.py", line 958, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/home/participant/LOCAL_INSTALL/SPHIRE/lib/python3.6/site-packages/conda_build/build.py", line 823, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/home/participant/LOCAL_INSTALL/SPHIRE/lib/python3.6/site-packages/conda_build/post.py", line 1070, in post_build
    check_overlinking(m, files)
  File "/home/participant/LOCAL_INSTALL/SPHIRE/lib/python3.6/site-packages/conda_build/post.py", line 1009, in check_overlinking
    m.config.channel_urls)
  File "/home/participant/LOCAL_INSTALL/SPHIRE/lib/python3.6/site-packages/conda_build/post.py", line 930, in check_overlinking_impl
    needed = needed_dsos_for_file[f]
KeyError: 'lib/libfftw3f_threads.so.3.5.6'
```

### Expected Behavior

The process works. 

### Steps to Reproduce

It happens during the installation of our software:
http://sphire.mpg.de/wiki/doku.php?id=downloads:sphire_1_2&redirect=1#source_code_installation_with_its_own_anaconda_installation
in the reinstallation step:
http://sphire.mpg.de/wiki/doku.php?id=downloads:sphire_1_2&redirect=1#build_pydusa

##### `Output of conda info`

```
     active environment : sphire_2
    active env location : /home/participant/LOCAL_INSTALL/SPHIRE/envs/sphire_2
            shell level : 1
       user config file : /home/participant/.condarc
 populated config files : 
          conda version : 4.6.14
    conda-build version : 3.18.2
         python version : 3.6.8.final.0
       base environment : /home/participant/LOCAL_INSTALL/SPHIRE  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/participant/LOCAL_INSTALL/SPHIRE/pkgs
                          /home/participant/.conda/pkgs
       envs directories : /home/participant/LOCAL_INSTALL/SPHIRE/envs
                          /home/participant/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.18.4 CPython/3.6.8 Linux/4.15.0-1040-aws ubuntu/18.04.2 glibc/2.27
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

**Comment by isuruf** [comment]
Same issue in https://github.com/conda-forge/coq-feedstock/pull/3

**Comment by mjscosta** [comment]
I'm also having the same issue, building a custom version of zeromq-feedstock ...

**Comment by isuruf** [comment]
3.18.7 fixed the error I had. Maybe this bug is fixed now

**Comment by msarahan** [comment]
I'll close it, but let me know if it comes up again.
