### ISSUE TITLE
Trouble running tests in CDT

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#3553]
### Actual Behavior

```bash
...
TEST START: /home/conda/feedstock_root/build_artifacts/noarch/libnl-cos6-x86_64-1.1.4-0.tar.bz2
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from /tmp/tmp7nah042m/info/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /tmp/tmp7nah042m/info/recipe/conda_build_config.yaml
Renaming work directory,  /home/conda/feedstock_root/build_artifacts/libnl-cos6-x86_64_1560901741574/work  to  /home/conda/feedstock_root/build_artifacts/libnl-cos6-x86_64_1560901741574/work_moved_libnl-cos6-x86_64-1.1.4-0_noarch
Collecting package metadata: ...working... done                                 
Solving environment: ...working... done
Traceback (most recent call last):                                              
  File "/home/conda/.ci_support/build_all.py", line 131, in <module>
    build_all(args.recipes_dir, args.arch)
  File "/home/conda/.ci_support/build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File "/home/conda/.ci_support/build_all.py", line 121, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2305, in build_tree
    test(pkg, config=metadata.config.copy(), stats=stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2110, in test
    is_conda=metadata.name() == 'conda')
  File "/opt/conda/lib/python3.7/site-packages/conda_build/environ.py", line 861, in create_env
    display_actions(actions, index)
  File "/opt/conda/lib/python3.7/site-packages/conda/exports.py", line 229, in display_actions
    actions['LINK'] = [index[d] for d in actions['LINK']]
  File "/opt/conda/lib/python3.7/site-packages/conda/exports.py", line 229, in <listcomp>
    actions['LINK'] = [index[d] for d in actions['LINK']]
KeyError: Dist(channel='file:///home/conda/feedstock_root/build_artifacts', dist_name='libnl-cos6-x86_64-1.1.4-0', name='libnl-cos6-x86_64', version='1.1.4', build_string='0', build_number=0, base_url=None, platform=None)
```

### Expected Behavior

Test environment is created with the package and tests run without issues.

### Steps to Reproduce

Build the following `libnl-cos6-x86_64` recipe on Linux with the tests uncommented. The issue vanishes when the tests are commented. Also this does not happen on macOS.

<details open>
<summary><code>libnl-cos6-x86_64/meta.yaml</code></summary>

```yaml
package:
  name: libnl-cos6-x86_64
  version: 1.1.4

source:
  - url: http://mirror.centos.org/centos/6.10/os/x86_64/Packages/libnl-1.1.4-2.el6.x86_64.rpm
    sha256: 03a7235e747695208a2633fd6515a39377a9b06b7aa866bda1a1e1eabf418869
    folder: binary
  - url: http://vault.centos.org/6.10/os/Source/SPackages/libnl-1.1.4-2.el6.src.rpm
    folder: source

build:
  number: 0
  noarch: generic
  missing_dso_whitelist:
    - '*'


### Uncomment below to trigger failure.
#test:
#  commands:
#    - test -d "${PREFIX}/x86_64-conda_cos6-linux-gnu/sysroot"

about:
  home: http://www.infradead.org/~tgr/libnl/
  license: LGPLv2
  license_family: LGPL
  summary: "(CDT) Convenience library for kernel netlink sockets"
  description: |
        This package contains a convenience library to simplify using the Linux
        kernel's netlink sockets interface for network manipulation
```

</details>

<details>
<summary><code>libnl-cos6-x86_64/build.sh </code></summary>

```bash
#!/bin/bash

mkdir -p ${PREFIX}/x86_64-conda_cos6-linux-gnu/sysroot
cd ${PREFIX}/x86_64-conda_cos6-linux-gnu/sysroot > /dev/null 2>&1
cp -Rf "${SRC_DIR}"/binary/* .
```

</details>

##### `Output of conda info`

```
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/conda/.condarc
 populated config files : /home/conda/.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/conda/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/conda/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.9.125-linuxkit centos/6.10 glibc/2.12
                UID:GID : 9001:9001
             netrc file : None
           offline mode : False
```

**Comment by jakirkham** [comment]
Seems like there have been a few issues similar to this one with Conda.

* https://github.com/conda/conda/issues/6698
* https://github.com/conda/conda/issues/6846
* https://github.com/conda/conda/issues/7116
* https://github.com/conda/conda/issues/7317
* https://github.com/conda/conda/issues/7920

**Comment by isuruf** [comment]
I can't seem to reproduce this.
```
     active environment : base
    active env location : /home/isuru/miniconda3
            shell level : 1
       user config file : /home/isuru/.condarc
 populated config files : /home/isuru/miniconda3/.condarc
                          /home/isuru/.condarc
          conda version : 4.7.5
    conda-build version : 3.18.6
         python version : 3.6.7.final.0
       virtual packages : 
       base environment : /home/isuru/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/isuru/miniconda3/pkgs
                          /home/isuru/.conda/pkgs
       envs directories : /home/isuru/miniconda3/envs
                          /home/isuru/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.6.7 Linux/4.15.0-51-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : /home/isuru/.netrc
           offline mode : False
```

**Comment by isuruf** [comment]
@jakirkham, can you try with an updated conda-build?

**Comment by jakirkham** [comment]
Sure added PR ( https://github.com/conda-forge/libnl-cos6-x86_64-feedstock/pull/2 ). Let's see what happens.

**Comment by jakirkham** [comment]
Yep, seems to work now. Closing.

**Comment by jakirkham** [comment]
Hmm...I see now there is [still a failure on `staged-recipes`]( https://github.com/conda-forge/staged-recipes/runs/160268302 ). It could be conda-forge's tooling. Though it does seem a bit strange. Going to keep this open.
