### ISSUE TITLE
Windows ValueError: need at most 63 handles, got a sequence of length 64

### ISSUE THREAD

**Issue by cometchaser** [conda/conda-build#3576]
### Actual Behavior

The build of our conda package fails on a Windows maschine with the following message:
```
[31/31] Cythonizing my_app/type_conversions.pyx  
Attempting to finalize metadata for my_app  
INFO:conda_build.metadata:Attempting to finalize metadata for my_app  
Exception in thread Thread-117:  
Traceback (most recent call last):  
  File "C:\Users\MyUser\AppData\Local\Continuum\miniconda3\envs\my_app_build_36_win\lib\threading.py", line 916, in _bootstrap_inner  
    self.run()  
  File "C:\Users\MyUser\AppData\Local\Continuum\miniconda3\envs\my_app_build_36_win\lib\threading.py", line 864, in run  
    self._target(*self._args, **self._kwargs)  
  File "C:\Users\MyUser\AppData\Local\Continuum\miniconda3\envs\my_app_build_36_win\lib\concurrent\futures\process.py", line 270, in _queue_management_worker  
    ready = wait([reader] + sentinels)  
  File "C:\Users\MyUser\AppData\Local\Continuum\miniconda3\envs\my_app_build_36_win\lib\multiprocessing\connection.py", line 859, in wait  
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)  
  File "C:\Users\MyUser\AppData\Local\Continuum\miniconda3\envs\my_app_build_36_win\lib\multiprocessing\connection.py", line 791, in _exhaustive_wait  
    res = _winapi.WaitForMultipleObjects(L, False, timeout)  
ValueError: need at most 63 handles, got a sequence of length 64
```
As far as I can see, the conda build creates several python instances, not sure if > 60, before it crashes. So it might be possible that this issue [https://bugs.python.org/issue26903](https://bugs.python.org/issue26903) is related to the problem here. However, I couldn't find an option of conda-build to reduce the number of instances. 

From the `conda env export`
  - conda=4.7.5=py36_0
  - conda-build=3.18.5=py36_0

### Expected Behavior

Previous builds were all successful.
The last build used the following versions:
conda-4.6.14-py36_0
conda-build-3.17.8-py36_0

##### `Output of conda info`

```
active environment : my_app_build_36_win
    active env location : C:\Users\MyUser\AppData\Local\Continuum\miniconda3\envs\my_app_build_36_win
            shell level : 1
       user config file : C:\Users\MyUser\.condarc
 populated config files : C:\Users\MyUser\.condarc
          conda version : 4.7.5
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
       virtual packages :
       base environment : C:\Users\MyUser\AppData\Local\Continuum\miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\MyUser\AppData\Local\Continuum\miniconda3\pkgs
                          C:\Users\MyUser\.conda\pkgs
                          C:\Users\MyUser\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\MyUser\AppData\Local\Continuum\miniconda3\envs
                          C:\Users\MyUser\.conda\envs
                          C:\Users\MyUser\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.7.1 Windows/10 Windows/10.0.14393
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by cometchaser** [comment]
Nearly the same happens when creating the conda index with conda-build in version 3.18.5. 
A downgrade to version 3.17.8 "solves" to issue
