### ISSUE TITLE
Can you rely on the shebang of an installed command during build?

### ISSUE THREAD

**Issue by hakonhagland** [conda/conda-build#3592]
I am trying to create my first conda package. It is a simple perl module:
```
package:
  name: perl-hello
  version: "1.0"

source:
  path: ../src

requirements:
  build:
    - perl 5.26.2
    - make

  run:
    - perl 5.26.2

about:
  license: Artistic
  summary: Simple perl function
```
The source tree: `../src`:
```
$ tree ../src
../src
├── lib
│   └── My
│       └── Module.pm
└── Makefile.PL

2 directories, 2 files
```
The perl module (`Module.pm`) in the source tree uses a CPAN module that must be installed during conda build. So I tried with the following `build.sh`:
```
# PERL_MM_USE_DEFAULT=1  -> utomatically answer "yes" on config questions
PERL_MM_USE_DEFAULT=1 cpan App::cpanminus  # Installs the installer cpanm
cpanm Data::Dump  # Installs the CPAN module
perl Makefile.PL INSTALLDIRS=site
make
make install
```
I now ran build:
```
$ conda-build .
[...]
/home/hakon/miniconda3/conda-bld/perl-hello_1562281041434/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/cpanm: line 20: BEGIN: command not found
/home/hakon/miniconda3/conda-bld/perl-hello_1562281041434/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/cpanm: line 21: my: command not found
/home/hakon/miniconda3/conda-bld/perl-hello_1562281041434/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/cpanm: line 23: syntax error near unexpected token `('
/home/hakon/miniconda3/conda-bld/perl-hello_1562281041434/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/cpanm: line 23: `$fatpacked{"App/cpanminus.pm"} = '#line '.(1+__LINE__).' "'.__FILE__."\"\n".<<'APP_CPANMINUS';'
Traceback (most recent call last):
  File "/home/hakon/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/hakon/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/home/hakon/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/home/hakon/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/hakon/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 2313, in build_tree
    notest=notest,
  File "/home/hakon/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 1461, in build
    cwd=src_dir, stats=build_stats)
  File "/home/hakon/miniconda3/lib/python3.7/site-packages/conda_build/utils.py", line 397, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/hakon/miniconda3/lib/python3.7/site-packages/conda_build/utils.py", line 377, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/hakon/miniconda3/conda-bld/perl-hello_1562281041434/work/conda_build.sh']' returned non-zero exit status 2.
```
So `conda-build` fails here. I think this fails because the shebang of the installed `cpanm` (see `build.sh`) has been modified to:
```
$ head -1  /home/hakon/miniconda3/conda-bld/perl-hello_1562281041434/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/cpanm 
#!/home/hakon/miniconda3/conda-bld/perl-hello_1562281041434/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/perl
```
instead of its original shebang of `#!/usr/bin/env perl`. The new shebang is 267 characters long.
Note that the new shebang is above the shebang line limit of 127 characters, see [Shebang line limit in bash and linux kernel](https://stackoverflow.com/q/10813538/2173773).

What did I miss here? I read in the documentation about [the PREFIX enviroment variable](https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html), and changed the line running `cpanm` in  `build.sh` to:
```
perl ${PREFIX}/bin/cpanm Data::Dump
```
then `conda-build` worked fine. 
I could not find anything in the documentation about not relying on shebang during build, so I wondered if this is this the preferred way of running installed commands during build? Or am I missing something?

**Comment by timsnyder** [comment]
Hi @hakonhagland .

The preferred way of doing this would be to use `conda skeleton cpan Data::Dump` to create a `perl-data-dump` recipe for the CPAN module that you need during the build and then change your `perl-hello` recipe to look like:
```
package:
  name: perl-hello
  version: "1.0"

source:
  path: ../src

requirements:
  build:
    - perl 5.26.2
    - perl-data-dump
    - make

  run:
    - perl 5.26.2

about:
  license: Artistic
  summary: Simple perl function
```

And conda-build will install the `Data::Dump` cpan package for you in the build environment and you won't need to use `cpanm`.

The advantage to this method is that you can easily see the build time dependencies in the recipe's `meta.yaml` and there are tools that will create the dependency graph and build things in the correct order when  you need to build something more complicated.

Finally, if you [search for perl-data-dump on Anaconda.org](https://anaconda.org/search?q=perl-data-dump), you'll see that the `bioconda` channel has `perl-data-dump` already built as a conda package.

One last thing, if you still have problems with the prefix length being over 127 characters, you can use the `--prefix-length` option to `conda build` to say how long you want the prefix to be.  I haven't encountered the 127 character limit in the last decade or so.  Which linux distro are you running?
