### ISSUE TITLE
conda_build.api.render() failing on attempt to write to read-only directory

### ISSUE THREAD

**Issue by pmspire** [conda/conda-build#3640]
### Actual Behavior

Trying to render a simple recipe:

```
>>> conda_build.api.render('.')
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
Attempting to finalize metadata for foo
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/api.py", line 52, in render
    bypass_env_check=bypass_env_check):
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/metadata.py", line 2047, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/metadata.py", line 721, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 527, in finalize_metadata
    exclude_pattern)
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 390, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 381, in _read_upstream_pin_files
    extra_run_specs = get_upstream_pins(m, actions, env)
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 368, in get_upstream_pins
    run_exports = _read_specs_from_package(loc, dist)
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda/exports.py", line 198, in __call__
    value = self.func(*args, **kw)
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 258, in _read_specs_from_package
    specs_yaml = utils.package_has_file(pkg_loc, 'info/run_exports.yaml')
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/utils.py", line 1135, in package_has_file
    conda_package_handling.api.extract(package_path, cache_path, 'info')
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_package_handling/api.py", line 43, in extract
    _os.makedirs(dest_dir)
  File "/home/user1/miniconda/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/user1/miniconda/pkgs/gfortran_linux-64-7.3.0-h553295d_7'
```
### Expected Behavior

No `PermisionError` and a rendered recipe.

### Steps to Reproduce

This is happening when using a shared Miniconda installation owned by another user, a setup we've been using without (this particular) issue for a couple years.

I created a simple reproducer on a fresh AWS EC2 instance. I created two users. Here's the setup for `user1`, who owns the Miniconda installation:

```
$ whoami
user1
$ curl -sS https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
$ bash ./miniconda.sh -bfp miniconda
$ source miniconda/etc/profile.d/conda.sh
$ conda activate
(base) $ conda install --yes conda-build conda-verify
(base) $ conda update --all --yes
(base) $ find miniconda -type d -exec chmod a+rx '{}' \;
(base) $ find miniconda -type f -exec chmod a+r '{}' \;
(base) $ chmod 755 .
```

So, we've got a Miniconda installation with `conda-build` installed, updated to the latest everything, with permissions that allow read-only access by other users. This mirrors our actual operational use context where this issue surfaced.

Here's what happens to `user2` trying to render a recipe while using this Miniconda:

```
$ whoami
user2
$ source ~user1/miniconda/etc/profile.d/conda.sh
$ conda activate
(base) $ cat meta.yaml
package:
  name: foo
  version: 0
requirements:
  build:
    - {{ compiler('fortran') }}
about:
  license: OTHER
(base) $ rm -rf ~/conda-bld ~/.conda
(base) $ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import conda_build.api
>>> conda_build.api.render('.')
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
Attempting to finalize metadata for foo
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/api.py", line 52, in render
    bypass_env_check=bypass_env_check):
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/metadata.py", line 2047, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/metadata.py", line 721, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 527, in finalize_metadata
    exclude_pattern)
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 390, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 381, in _read_upstream_pin_files
    extra_run_specs = get_upstream_pins(m, actions, env)
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 368, in get_upstream_pins
    run_exports = _read_specs_from_package(loc, dist)
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda/exports.py", line 198, in __call__
    value = self.func(*args, **kw)
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 258, in _read_specs_from_package
    specs_yaml = utils.package_has_file(pkg_loc, 'info/run_exports.yaml')
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_build/utils.py", line 1135, in package_has_file
    conda_package_handling.api.extract(package_path, cache_path, 'info')
  File "/home/user1/miniconda/lib/python3.7/site-packages/conda_package_handling/api.py", line 43, in extract
    _os.makedirs(dest_dir)
  File "/home/user1/miniconda/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/user1/miniconda/pkgs/gfortran_linux-64-7.3.0-h553295d_7'
>>> 
```

Why is `conda-build` trying to `mkdir` in `user1`'s space? Shouldn't it fall back to its own `~/.conda/pkgs` or something similar?

##### `Output of conda info`

```
     active environment : base
    active env location : /home/user1/miniconda
            shell level : 1
       user config file : /home/user2/.condarc
 populated config files : 
          conda version : 4.7.10
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /home/user1/miniconda  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/user1/miniconda/pkgs
                          /home/user2/.conda/pkgs
       envs directories : /home/user2/.conda/envs
                          /home/user1/miniconda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Linux/4.14.123-111.109.amzn2.x86_64 amzn/2 glibc/2.26
                UID:GID : 1002:1002
             netrc file : None
           offline mode : False
```

**Comment by jjhelmus** [comment]
`conda.api.render` needs to download packages to examine them for `run_export` entries so there is going to be a need to write to a directory when rendering a recipe.  Why conda is choosing user1 package directory rather than user2 is confusing and likely a bug.

**Comment by pmspire** [comment]
This continues to cause problems for our users. It seems that, if the privileged user who owns the Miniconda installation hasn't already downloaded a particular package (e.g. when a newer package version is called for by some recipe, and a user of the shared installation is the first one to try to build a recipe using it), users cannot build recipes.

**Comment by pmspire** [comment]
As it has been over 5 months since I reported this, I wanted to check in and see if this is on anyone's radar. I have been watching release notes to see if anything potentially addressing this might have been mentioned, but I haven't seen anything.

Has anyone tried reproducing this?

**Comment by pmspire** [comment]
I don't have a minimal reproducer for it yet, but I'm seeing a similar error in a different context, conda this time trying to write to a JSON file in `pkgs/cache`, in a shared installation that it should not be writing to. I think you can safely ignore the first two frames in the longer stack trace, as the problem again occurs inside `conda_build.api.render()`:
```
Traceback (most recent call last):
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 269, in _load
    with io_open(self.cache_path_json, 'w') as fh:
PermissionError: [Errno 13] Permission denied: '/home/spire/spire/sw/conda/pkgs/cache/497deca9.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spire/spire/sw/conda/bin/meta", line 11, in <module>
    load_entry_point('swgpydev==0', 'console_scripts', 'meta')()
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/swgpydev/meta.py", line 87, in main
    print(Meta(dirs.recipe).collect(attrs))
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/swgpydev/meta.py", line 21, in __init__
    self.meta = conda_build.api.render(self.recipe, channel_urls=channels, verbose=False)[0][0]
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda_build/api.py", line 52, in render
    bypass_env_check=bypass_env_check):
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda_build/metadata.py", line 2048, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda_build/metadata.py", line 722, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda_build/render.py", line 527, in finalize_metadata
    exclude_pattern)
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda_build/render.py", line 390, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda_build/render.py", line 378, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda_build/render.py", line 154, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda_build/environ.py", line 742, in get_install_actions
    locking=locking, timeout=timeout)
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda_build/index.py", line 185, in get_build_index
    platform=subdir)
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda/exports.py", line 250, in get_index
    index = _get_index(channel_urls, prepend, platform, use_local, use_cache, unknown, prefix)
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda/core/index.py", line 63, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, repodata_fn=repodata_fn)
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda/core/index.py", line 80, in fetch_index
    index.update((rec, rec) for rec in f.iter_records())
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 194, in iter_records
    self.load()
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 174, in load
    _internal_state = self._load()
  File "/home/spire/spire/sw/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 273, in _load
    raise NotWritableError(self.cache_path_json, e.errno, caused_by=e)
conda.exceptions.NotWritableError: The current user does not have write permissions to a required path.
  path: /home/spire/spire/sw/conda/pkgs/cache/497deca9.json
  uid: 5090
  gid: 5018
```

**Comment by forrestwaters** [comment]
By default, the pkg cache is within the miniconda/anaconda install: https://docs.anaconda.com/anaconda/user-guide/tasks/shared-pkg-cache/

If you do not want this because users have read-only access to the primary conda install, then your users can configure `pkgs_dirs` to a path writable by them. Worth noting that this will use more disk space, but I think that is what you're wanting in this case?

**Comment by pmspire** [comment]
@forrestwaters Thank you, this seems to be a workable solution to the problem. The extra disk space is a wash, as the alternative is to have each user install a personal Miniconda, which uses just as much (and probably more) disk space and is less convenient. Since we're in an HPC environment and provide the shared conda installation via environment modules, I found it convenient to use the `CONDA_PKGS_DIRS` environment variable described in [here](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#specify-pkg-directories) rather than having each user configure a `.condarc`. This is great, and makes a shared install usable again.

For what it's worth, I'll say that the behavior reported in this ticket wasn't always the default: By whatever means, conda-build used to (as far as I can tell, unless I was just getting lucky with several installs misconfigured with too-open permissions, which seems unlikely) conveniently use the shared package cache by default, falling back to... something (`~/conda-bld`?) as necessary. That fallback to `~/conda-bld` seems still to be in use for package builds: We've never seen a problem using a shared conda installation and doing package builds -- `.bz2` package files end up in the user's e.g. `~/conda-bld/linux-64` directory.

So, though I'm grateful for a workaround, the mismatch between build and render fallback behavior and the surprising errors with (to my users) inscrutable stack traces still seems like a bug to me. Yesterday one of my users sent me the output of a simple `conda search` command that failed with a `NotWritableError` and advice to `chown` a file in `pkgs/cache` in the shared conda installation. I assume the underlying issue is the same and that the `pkgs_dirs` setting will help with this, too, but if conda installations are meant to be shareable (which is extremely useful), maybe something still needs to be "fixed".
