### ISSUE TITLE
bdist_conda packaging stopped working

### ISSUE THREAD

**Issue by bilderbuchi** [conda/conda-build#3641]
Using current conda-build (3.18.9), my usage of `python setup.py bdist_conda` has stopped creating packages out of a pure Python setuptools-based package without a conda recipe. Before, this was working without problems. 
The only output I get is the following, then nothing happens anymore until I Ctrl-C:

```
python setup.py bdist_conda
running bdist_conda
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Attempting to finalize metadata for ae_utils
INFO:conda_build.metadata:Attempting to finalize metadata for ae_utils
running bdist_conda
running bdist_conda
running bdist_conda
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
running bdist_conda
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaultsINFO:conda_build.variants:Adding in variants from config.variant
Adding in variants from config.variant

INFO:conda_build.variants:Adding in variants from config.variant
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11

WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Attempting to finalize metadata for ae_utils
INFO:conda_build.metadata:Attempting to finalize metadata for ae_utils
Attempting to finalize metadata for ae_utils
INFO:conda_build.metadata:Attempting to finalize metadata for ae_utils
Attempting to finalize metadata for ae_utils
INFO:conda_build.metadata:Attempting to finalize metadata for ae_utils
Attempting to finalize metadata for ae_utils
INFO:conda_build.metadata:Attempting to finalize metadata for ae_utils
```

So, conda-build 3.18.9 does not work. By installing different versions, I have verified that using conda-build 3.17.8 works, but 3.18.5 is already broken. I would have liked to nail this down more precisely, but the intermediate releases 3.18.x<5 are not available via conda. 
Unfortunately, 3.17.8 does not include the fix for an earlier issue I encountered, #3455, which only landed in 3.18.0. :-(

I cannot even find out what goes wrong here. How can I troubleshoot this in more detail? The package in question is not public, so I can't provide it.

The numpy thing mentioned is probably #3333. 
Built conda packages are made available in a custom local channel (see below), which has been working without hitch for quite some time..

##### `Output of conda info`
```
     active environment : base
    active env location : C:\Continuum\miniconda3
            shell level : 1
       user config file : C:\Users\buchner\.condarc
 populated config files : C:\Users\buchner\.condarc
          conda version : 4.7.10
    conda-build version : 3.18.9
         python version : 3.6.8.final.0
       virtual packages : __cuda=9.1
       base environment : C:\Continuum\miniconda3  (writable)
           channel URLs : file:///P:/AE/ae_conda_channel/win-64
                          file:///P:/AE/ae_conda_channel/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Continuum\miniconda3\pkgs
                          C:\Users\buchner\.conda\pkgs
                          C:\Users\buchner\AppData\Local\conda\conda\pkgs
       envs directories : C:\Continuum\miniconda3\envs
                          C:\Users\buchner\.conda\envs
                          C:\Users\buchner\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.6.8 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by jjhelmus** [comment]
Can you create a minimal example `setup.py` that shows the behavior?  Then it should be possible to use `git bisect` to find the commit that caused the change in behavior.

**Comment by bilderbuchi** [comment]
Sure! That turned out to be surprisingly minimal, my setup.py is just
``` 
from setuptools import setup
setup(name='test')
```
It is the only file in the folder, and if I say ` python setup.py bdist_conda` it shows the above behaviour.
I am in my base environment in a miniconda install with conda 4.7.10, conda-build 3.18.9, conda-package-handling 1.3.11, conda-verify 3.4.2, Python 3.6.8 on Windows 10.

**Comment by bilderbuchi** [comment]
So, I tried to run my setup.py against a clone of conda-build (to take a shot at git-bisecting), but ran into problems:
* can't work in a separate environment as conda and conda-build are only available in `base`. OK, fair enough.
* I cloned both conda-build and conda_build_test_recipe as written in the readme for testing. But then, I could not find a way to locally install the conda-build from the repo instead of the one in my base environment, so that I can register the entrypoint/`bdist_conda` CLI arg.
* I tried to do  `conda develop .`, but heh, conda develop is only available if you have conda-build, catch 22.
* At least with the search function on github I could not find a test that I could run instead that exercises `bdist_conda`.

So, at this point I am a bit stumped how to proceed on this. Help please?

**Comment by bilderbuchi** [comment]
Can anybody give some guidance on how to git-bisect this locally? 
How do I locally install conda-build from repo?
Alternatively, what kind of test do I have to write to execute the codepath active in `python setup.py bdist_conda`?

**Comment by bilderbuchi** [comment]
I have found out that, if I leave it running for a long time (> 10 minutes), I finally get a traceback:
```
(base) PS Z:\temp> python setup.py bdist_conda
running bdist_conda
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Attempting to finalize metadata for temp
INFO:conda_build.metadata:Attempting to finalize metadata for temp
running bdist_conda
running bdist_conda
running bdist_conda
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
Adding in variants from internal_defaultsNo numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
INFO:conda_build.variants:Adding in variants from internal_defaults

WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11Adding in variants from config.variant

INFO:conda_build.variants:Adding in variants from config.variant
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
running bdist_conda
Attempting to finalize metadata for tempAttempting to finalize metadata for tempAttempting to finalize metadata for temp

INFO:conda_build.metadata:Attempting to finalize metadata for temp
INFO:conda_build.metadata:Attempting to finalize metadata for temp
INFO:conda_build.metadata:Attempting to finalize metadata for temp

Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Attempting to finalize metadata for temp
INFO:conda_build.metadata:Attempting to finalize metadata for temp
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Continuum\miniconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Continuum\miniconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Continuum\miniconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Continuum\miniconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Continuum\miniconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Continuum\miniconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Continuum\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "Z:\temp\setup.py", line 2, in <module>
    setup(name='temp')
  File "C:\Continuum\miniconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Continuum\miniconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Continuum\miniconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Continuum\miniconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Continuum\miniconda3\lib\distutils\command\bdist_conda.py", line 266, in run
    api.build(m, build_only=True, notest=True)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\build.py", line 2313, in build_tree
    notest=notest,
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\build.py", line 1322, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 736, in expand_outputs
    for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\metadata.py", line 2047, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\metadata.py", line 721, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 517, in finalize_metadata
    exclude_pattern)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 380, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 368, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 154, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\environ.py", line 742, in get_install_actions
    locking=locking, timeout=timeout)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\index.py", line 192, in get_build_index
    update_index(output_folder, verbose=debug)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\index.py", line 293, in update_index
    current_index_versions=current_index_versions)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\index.py", line 788, in index
    with utils.try_acquire_locks([utils.get_lock(self.channel_root)], timeout=900):
  File "C:\Continuum\miniconda3\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\utils.py", line 486, in try_acquire_locks
    raise BuildLockError('Failed to acquire all locks')
conda_build.exceptions.BuildLockError: Failed to acquire all locks
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "C:\Continuum\miniconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "<string>", line 1, in <module>
    exitcode = _main(fd)
  File "C:\Continuum\miniconda3\lib\multiprocessing\spawn.py", line 114, in _main
  File "C:\Continuum\miniconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
        prepare(preparation_data)exitcode = _main(fd)

  File "C:\Continuum\miniconda3\lib\multiprocessing\spawn.py", line 225, in prepare
  File "C:\Continuum\miniconda3\lib\multiprocessing\spawn.py", line 114, in _main
    _fixup_main_from_path(data['init_main_from_path'])
prepare(preparation_data)  File "C:\Continuum\miniconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path

  File "C:\Continuum\miniconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    run_name="__mp_main__")
_fixup_main_from_path(data['init_main_from_path'])  File "C:\Continuum\miniconda3\lib\runpy.py", line 263, in run_path

  File "C:\Continuum\miniconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
        pkg_name=pkg_name, script_name=fname)run_name="__mp_main__")

  File "C:\Continuum\miniconda3\lib\runpy.py", line 96, in _run_module_code
  File "C:\Continuum\miniconda3\lib\runpy.py", line 263, in run_path
    mod_name, mod_spec, pkg_name, script_name)
      File "C:\Continuum\miniconda3\lib\runpy.py", line 85, in _run_code
pkg_name=pkg_name, script_name=fname)
exec(code, run_globals)  File "C:\Continuum\miniconda3\lib\runpy.py", line 96, in _run_module_code

      File "Z:\temp\setup.py", line 2, in <module>
mod_name, mod_spec, pkg_name, script_name)
  File "C:\Continuum\miniconda3\lib\runpy.py", line 85, in _run_code
        setup(name='temp')exec(code, run_globals)

  File "C:\Continuum\miniconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
  File "Z:\temp\setup.py", line 2, in <module>
        return distutils.core.setup(**attrs)setup(name='temp')

  File "C:\Continuum\miniconda3\lib\distutils\core.py", line 148, in setup
  File "C:\Continuum\miniconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
        dist.run_commands()return distutils.core.setup(**attrs)

  File "C:\Continuum\miniconda3\lib\distutils\dist.py", line 955, in run_commands
  File "C:\Continuum\miniconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()self.run_command(cmd)

  File "C:\Continuum\miniconda3\lib\distutils\dist.py", line 955, in run_commands
  File "C:\Continuum\miniconda3\lib\distutils\dist.py", line 974, in run_command
    self.run_command(cmd)
  File "C:\Continuum\miniconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Continuum\miniconda3\lib\distutils\command\bdist_conda.py", line 266, in run
        cmd_obj.run()api.build(m, build_only=True, notest=True)

  File "C:\Continuum\miniconda3\lib\distutils\command\bdist_conda.py", line 266, in run
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\api.py", line 209, in build
    api.build(m, build_only=True, notest=True)
      File "C:\Continuum\miniconda3\lib\site-packages\conda_build\api.py", line 209, in build
notest=notest, need_source_download=need_source_download, variants=variants)
      File "C:\Continuum\miniconda3\lib\site-packages\conda_build\build.py", line 2313, in build_tree
notest=notest, need_source_download=need_source_download, variants=variants)
      File "C:\Continuum\miniconda3\lib\site-packages\conda_build\build.py", line 2313, in build_tree
notest=notest,
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\build.py", line 1322, in build
    notest=notest,
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\build.py", line 1322, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 736, in expand_outputs
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 736, in expand_outputs
        for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):

  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\metadata.py", line 2047, in get_output_metadata_set
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\metadata.py", line 2047, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\metadata.py", line 721, in finalize_outputs_pass
    bypass_env_check=bypass_env_check)
      File "C:\Continuum\miniconda3\lib\site-packages\conda_build\metadata.py", line 721, in finalize_outputs_pass
permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 517, in finalize_metadata
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 517, in finalize_metadata
exclude_pattern)
exclude_pattern)  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 380, in add_upstream_pins

  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 380, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
      File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 368, in _read_upstream_pin_files
permit_unsatisfiable_variants, exclude_pattern)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 368, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
permit_unsatisfiable_variants=permit_unsatisfiable_variants)  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 154, in get_env_dependencies

      File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 154, in get_env_dependencies
channel_urls=tuple(m.config.channel_urls))
channel_urls=tuple(m.config.channel_urls))  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\environ.py", line 742, in get_install_actions

  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\environ.py", line 742, in get_install_actions
        locking=locking, timeout=timeout)locking=locking, timeout=timeout)

  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\index.py", line 192, in get_build_index
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\index.py", line 192, in get_build_index
    update_index(output_folder, verbose=debug)
update_index(output_folder, verbose=debug)  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\index.py", line 293, in update_index

  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\index.py", line 293, in update_index
    current_index_versions=current_index_versions)
      File "C:\Continuum\miniconda3\lib\site-packages\conda_build\index.py", line 788, in index
current_index_versions=current_index_versions)
with utils.try_acquire_locks([utils.get_lock(self.channel_root)], timeout=900):  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\index.py", line 788, in index

      File "C:\Continuum\miniconda3\lib\contextlib.py", line 81, in __enter__
with utils.try_acquire_locks([utils.get_lock(self.channel_root)], timeout=900):
return next(self.gen)  File "C:\Continuum\miniconda3\lib\contextlib.py", line 81, in __enter__

      File "C:\Continuum\miniconda3\lib\site-packages\conda_build\utils.py", line 486, in try_acquire_locks
return next(self.gen)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\utils.py", line 486, in try_acquire_locks
    raise BuildLockError('Failed to acquire all locks')
    conda_build.exceptionsraise BuildLockError('Failed to acquire all locks').
BuildLockErrorconda_build.exceptions: .Failed to acquire all locksBuildLockError
: Failed to acquire all locks
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Continuum\miniconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Continuum\miniconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Continuum\miniconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Continuum\miniconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Continuum\miniconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Continuum\miniconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Continuum\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "Z:\temp\setup.py", line 2, in <module>
    setup(name='temp')
  File "C:\Continuum\miniconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Continuum\miniconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Continuum\miniconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Continuum\miniconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Continuum\miniconda3\lib\distutils\command\bdist_conda.py", line 266, in run
    api.build(m, build_only=True, notest=True)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\build.py", line 2313, in build_tree
    notest=notest,
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\build.py", line 1322, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 736, in expand_outputs
    for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\metadata.py", line 2047, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\metadata.py", line 721, in finalize_outputs_pass
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Continuum\miniconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Continuum\miniconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Continuum\miniconda3\lib\concurrent\futures\process.py", line 295, in _queue_management_worker
    shutdown_worker()
  File "C:\Continuum\miniconda3\lib\concurrent\futures\process.py", line 253, in shutdown_worker
    call_queue.put_nowait(None)
  File "C:\Continuum\miniconda3\lib\multiprocessing\queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "C:\Continuum\miniconda3\lib\multiprocessing\queues.py", line 83, in put
    raise Full
queue.Full

Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    setup(name='temp')
  File "C:\Continuum\miniconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Continuum\miniconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Continuum\miniconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Continuum\miniconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Continuum\miniconda3\lib\distutils\command\bdist_conda.py", line 266, in run
    api.build(m, build_only=True, notest=True)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\build.py", line 2313, in build_tree
    notest=notest,
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\build.py", line 1322, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 736, in expand_outputs
    for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\metadata.py", line 2047, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\metadata.py", line 721, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 517, in finalize_metadata
    exclude_pattern)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 380, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 368, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\render.py", line 154, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\environ.py", line 742, in get_install_actions
    locking=locking, timeout=timeout)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\index.py", line 192, in get_build_index
    update_index(output_folder, verbose=debug)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\index.py", line 293, in update_index
    current_index_versions=current_index_versions)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\index.py", line 804, in index
    subdir, verbose=verbose, progress=progress)
  File "C:\Continuum\miniconda3\lib\site-packages\conda_build\index.py", line 943, in index_subdir
    fn, mtime, size, index_json = future.result()
  File "C:\Continuum\miniconda3\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Continuum\miniconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by bilderbuchi** [comment]
@jjhelmus  @msarahan any pointers on how I can contrinue troubleshooting this?

**Comment by msarahan** [comment]
Might be a deadlock. Try changing the default threads for indexing to 1.
May need to backport the dummy executor from conda any use it's map
function instead of submit and as_completed.

**Comment by bilderbuchi** [comment]
Thanks for the suggestion about indexing, but isn't this already the default? (see 2b76886fdfc8214c5968af48b683a58222c9c6e4 by you which landed in 3.18.7)

**Comment by bilderbuchi** [comment]
I am still seeing this with conda-build 3.18.10, and don't know how to proceed further here.

**Comment by bilderbuchi** [comment]
So, with 3.18.11 (and on a new pc/install) I don't see this anymore. As I was the only one seeing this issue, I think this can be closed.
