### ISSUE TITLE
conda skeleton pypi crashes with KeyError: 'platform_system'

### ISSUE THREAD

**Issue by notestaff** [conda/conda-build#3642]
### Actual Behavior

```
Leaving build/test directories:
  Work:
 /ilya/miniconda3/conda-bld/skeleton_1564608704340/work
  Test:
 /ilya/miniconda3/conda-bld/skeleton_1564608704340/test_tmp
Leaving build/test environments:
  Test:
source activate  /ilya/miniconda3/conda-bld/skeleton_1564608704340/_test_env_placehold_placehold_placehold_placehold_placehold_placeho\
ld_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p\
la
  Build:
source activate  /ilya/miniconda3/conda-bld/skeleton_1564608704340/_build_env


Traceback (most recent call last):
  File "/ilya/miniconda3/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File "/ilya/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/ilya/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    version=args.version, config=config)
  File "/ilya/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 290, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/ilya/miniconda3/lib/python3.7/site-packages/conda_build/skeletons/pypi.py", line 295, in skeletonize
    setup_options=setup_options)
  File "/ilya/miniconda3/lib/python3.7/site-packages/conda_build/skeletons/pypi.py", line 771, in get_package_metadata
    dep, marker = parse_dep_with_env_marker(dep)
  File "/ilya/miniconda3/lib/python3.7/site-packages/conda_build/skeletons/pypi.py", line 686, in parse_dep_with_env_marker
    match.group("env_mark_constraint"))
  File "/ilya/miniconda3/lib/python3.7/site-packages/conda_build/skeletons/pypi.py", line 673, in env_mark_lookup
    marker = " ".join((env_mark_table[env_mark_name]["repl"],
KeyError: 'platform_system'
```

### Expected Behavior

Create a skeleton conda recipe for `datalad 0.11.6`

### Steps to Reproduce

`conda skeleton pypi datalad --version=0.11.6`

##### `Output of conda info`

```
     active environment : master_env_v149_py36
    active env location : /ilya/miniconda3/envs/master_env_v149_py36
            shell level : 5
       user config file : /home/ilya/.condarc
 populated config files : /home/ilya/.condarc
          conda version : 4.7.10
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /ilya/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/broad-viral/linux-64
                          https://conda.anaconda.org/broad-viral/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/notestaff/linux-64
                          https://conda.anaconda.org/notestaff/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
          package cache : /ilya/miniconda3/pkgs
                          /home/ilya/.conda/pkgs
       envs directories : /ilya/miniconda3/envs
                          /home/ilya/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Linux/4.14.133-113.105.amzn2.x86_64 amzn/2 glibc/2.26
                UID:GID : 1002:1002
             netrc file : None
           offline mode : False


```

**Comment by notestaff** [comment]
may be related to https://github.com/conda/conda-build/blob/master/conda_build/skeletons/pypi.py#L670

**Comment by chris-n-self** [comment]
I am getting this error too, trying to do the same for a different pypi package using the `--recursive` option on skeleton. Did you find a solution or a fix?

**Comment by dmnapolitano** [comment]
I encountered something extremely similar doing `conda skeleton pypi --noarch-python allennlp`:

```python
Traceback (most recent call last):
  File "/home/dnapolitano/miniconda3/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File "/home/dnapolitano/miniconda3/lib/python3.8/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/home/dnapolitano/miniconda3/lib/python3.8/site-packages/conda_build/cli/main_skeleton.py", line 60, in execute
    api.skeletonize(args.packages, args.repo, output_dir=args.output_dir, recursive=args.recursive,
  File "/home/dnapolitano/miniconda3/lib/python3.8/site-packages/conda_build/api.py", line 276, in skeletonize
    skeleton_return = module.skeletonize(packages, output_dir=output_dir, version=version,
  File "/home/dnapolitano/miniconda3/lib/python3.8/site-packages/conda_build/skeletons/pypi.py", line 317, in skeletonize
    get_package_metadata(package, d, data, output_dir, python_version,
  File "/home/dnapolitano/miniconda3/lib/python3.8/site-packages/conda_build/skeletons/pypi.py", line 734, in get_package_metadata
    list_deps = get_dependencies(requires, is_setuptools_enabled(pkginfo))
  File "/home/dnapolitano/miniconda3/lib/python3.8/site-packages/conda_build/skeletons/pypi.py", line 840, in get_dependencies
    dep, marker = parse_dep_with_env_marker(dep_orig)
  File "/home/dnapolitano/miniconda3/lib/python3.8/site-packages/conda_build/skeletons/pypi.py", line 709, in parse_dep_with_env_marker
    env_mark = env_mark_lookup(match.group("env_mark_name"),
  File "/home/dnapolitano/miniconda3/lib/python3.8/site-packages/conda_build/skeletons/pypi.py", line 697, in env_mark_lookup
    marker = " ".join((env_mark_table[env_mark_name]["repl"],
KeyError: 'sys.platform'
```

At line 697 I added:

```python
if env_mark_name == "sys.platform":
    env_mark_name = "python_version"
```

Super hack-y (until there's a fix) but my command finished successfully.

I have `conda-build` 3.20.5 with Python 3.8.6 on Windows Subsystem for Linux (Debian woody).

**Comment by gvwilson** [comment]
Getting the same behavior with conda-build 3.21.8 (see #4451).
