### ISSUE TITLE
Conda build now requires Conda 4.5 or later

### ISSUE THREAD

**Issue by scw** [conda/conda-build#3643]
### Actual Behavior

Building a package with an older version of conda (4.3) causes a
traceback:

```
Traceback (most recent call last):
  File "C:\bin\conda_4.3\Scripts\conda-build-script.py", line 6, in <module>
    from conda_build.cli.main_build import main
  File "C:\bin\conda_4.3\lib\site-packages\conda_build\cli\main_build.py", line 18, in <module>
    import conda_build.api as api
  File "C:\bin\conda_4.3\lib\site-packages\conda_build\api.py", line 22, in <module>
    from conda_build.config import (Config, get_or_merge_config, get_channel_urls,
  File "C:\bin\conda_4.3\lib\site-packages\conda_build\config.py", line 17, in <module>
    from .variants import get_default_variant
  File "C:\bin\conda_4.3\lib\site-packages\conda_build\variants.py", line 15, in <module>
    from conda_build.utils import ensure_list, trim_empty_keys, get_logger
  File "C:\bin\conda_4.3\lib\site-packages\conda_build\utils.py", line 43, in <module>
    from conda.api import PackageCacheData
ImportError: cannot import name 'PackageCacheData'
```

### Expected Behavior

Conda build dependencies are set to require the same version of the
Conda API as it is using. From at least the above traceback, this can be
simply fixed by raising the minimum conda version to 4.5 in the package
metadata, though I haven't investigated closely if there are other
pieces that rely on specific versions of the Conda API.

### Steps to Reproduce

Stand up a conda 4.3 or 4.4 root environment. Install the latest conda
build, then try to run `conda build` on a package.

**Comment by marcelotrevisani** [comment]
Closing this issue in favor of #3664

**Comment by msarahan** [comment]
Thanks @marcelotrevisani.  I am also changing the recipes at anacondarecipes and on conda-forge.  I may need to do some repodata hotfixing as well.

**Comment by msarahan** [comment]
https://github.com/conda-forge/conda-build-feedstock/pull/111

**Comment by msarahan** [comment]
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/17
