### ISSUE TITLE
Setting a variant value using an environment variable

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#3666]
Am interested in using an environment variable to set a variant's value. The environment variable is something I may change external to the build, but would like it to propagate in. The following is a dummy example that attempts this and an issue encountered. If there's another way to accomplish what I'm trying to do, that would be more useful than fixing this case per se.

### Actual Behavior

```
$ BAR="BAR" conda build .
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Traceback (most recent call last):
  File "/Users/jkirkham/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 2321, in build_tree
    bypass_env_check=True)
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 813, in render_recipe
    variants = get_package_variants(m, variants=variants)
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/conda_build/variants.py", line 548, in get_package_variants
    combined_spec, specs = get_package_combined_spec(recipedir_or_metadata, config=config, variants=variants)
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/conda_build/variants.py", line 505, in get_package_combined_spec
    specs[f] = parse_config_file(f, config)
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/conda_build/variants.py", line 120, in parse_config_file
    content = yaml.load(contents, Loader=yaml.loader.BaseLoader) or {}
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/yaml/composer.py", line 129, in compose_mapping_node
    item_key = self.compose_node(node, None)
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/yaml/parser.py", line 550, in parse_flow_mapping_key
    "expected ',' or '}', but got %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a flow mapping
  in "<unicode string>", line 2, column 4:
    - {{ environ['BAR'] }}
       ^
expected ',' or '}', but got '['
  in "<unicode string>", line 2, column 13:
    - {{ environ['BAR'] }}
                ^
```

### Expected Behavior

`bar` gets the value `"BAR"`

### Steps to Reproduce

```yaml
# filename: meta.yaml
package:
  name: foo
  version: 1
```

```yaml
# filename: conda_build_config.yaml
bar:
- {{ environ['BAR'] }}
```

##### `Output of conda info`

```
     active environment : base
    active env location : /Users/jkirkham/miniconda
            shell level : 1
       user config file : /Users/jkirkham/.condarc
 populated config files : /Users/jkirkham/.condarc
          conda version : 4.7.10
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /Users/jkirkham/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/jkirkham/miniconda/pkgs
                          /Users/jkirkham/.conda/pkgs
       envs directories : /Users/jkirkham/miniconda/envs
                          /Users/jkirkham/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 523832026:1019530959
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
conda_build_config.yaml is not a templated file.  I guess it could be.  This isn't something Anaconda can work on, but if you'd like to get it working and submit a PR, I think it would be fine.

**Comment by jakirkham** [comment]
I see. So Jinja is not supported in `conda_build_config.yaml`.

**Comment by jjhelmus** [comment]
https://conda.io/projects/conda-build/en/latest/resources/variants.html#using-variants-with-the-conda-build-api indicates Jinja is not allowed in `conda_build_config.yaml`:

> Jinja is not allowed in conda_build_config.yaml, though. It is the source of information to feed into other jinja templates, and the buck has to stop somewhere.

**Comment by jakirkham** [comment]
If there were another way to inject that environment variable, that would also be sufficient. Not attached to Jinja as the solution.

**Comment by mingwandroid** [comment]
What about https://github.com/AnacondaRecipes/python-feedstock/blob/master/recipe/meta.yaml#L3

**Comment by jakirkham** [comment]
Yeah that's sort of what we are doing now. Though we end up duplicating this value in other places for other reasons.

Anyways I'm ok with the answer this isn't possible today. Just wasn't clear to me from the outset.

Thanks all! 😄

**Comment by jakirkham** [comment]
Idk if conda-build should do this. Though it is worth noting that [conda-forge has started doing its own templating with environment variables]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/4f8057b606f991183403e836d643cdbb764c074d/recipe/conda_build_config.yaml#L146-L150 )
