### ISSUE TITLE
building pybass from pypi

### ISSUE THREAD

**Issue by sakhan007** [conda/conda-build#367]
$ conda skeleton pypi pybass
    An unexpected error has occurred, please consider sending the
    following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues
    Traceback (most recent call last):
    File "/home/sohail/anaconda/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
    File "/home/sohail/anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 188, in main
    args_func(args, p)
    File "/home/sohail/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 329, in args_func
    args.func(args, p)
    File "/home/sohail/anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 202, in execute
    pypi.main(args, parser)
    File "/home/sohail/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 332, in main
    urls[0]['filename'] = U.path.rsplit('/')[-1]
    AttributeError: 'NoneType' object has no attribute 'rsplit'

    $ conda info
    Current conda install:
        platform : linux-64
       conda version : 3.10.1
       conda-build version : 1.12.0
       python version : 2.7.9.final.0
       requests version : 2.6.0
       root environment : /home/sohail/anaconda  (writable)
       default environment : /home/sohail/anaconda
       envs directories : /home/sohail/anaconda/envs
       package cache : /home/sohail/anaconda/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                                 https://repo.continuum.io/pkgs/free/noarch/
                                 https://repo.continuum.io/pkgs/pro/linux-64/
                                 https://repo.continuum.io/pkgs/pro/noarch/
       config file : /home/sohail/.condarc
       is foreign system : False

**Comment by asmeurer** [comment]
The error message needs to be better, but it's because pybass has no download file or download url on PyPI https://pypi.python.org/pypi/pybass.
