### ISSUE TITLE
conda index 3.18.* crashes on corrupt package with only an obscure error message

### ISSUE THREAD

**Issue by y2kbugger** [conda/conda-build#3685]
### Actual Behavior
```
hash & extract packages for win-64:   0%|          | 0/1 [00:00<?, ?it/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\ProgramData\CooperConda\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\CooperConda\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\CooperConda\lib\concurrent\futures\process.py", line 272, in _queue_management_worker
    result_item = reader.recv()
  File "C:\ProgramData\CooperConda\lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 1 required positional argument: 'msg'
```

### Expected Behavior

Not crash, and give error message similar to the 3.17.* series. Downgrading is how I finally determined that their was a problem package.

>     Package win-64/bokeh-1.3.4-py37_0.tar.bz2 appears to be corrupt.  Please remove it and re-download it
>     ERROR:conda_build.index:Package` win-64/bokeh-1.3.4-py37_0.tar.bz2 appears to be corrupt.
>     Please remove it and re-download it

### Steps to Reproduce

[Ex.zip](https://github.com/conda/conda-build/files/3530275/Ex.zip)

1. Extract the zip file.
2.     $ cd Ex
       $ conda index .

##### `Output of conda info`
```
$ conda info

     active environment : base
    active env location : C:\ProgramData\CooperConda
            shell level : 1
       user config file : C:\Users\zdkohler\.condarc
 populated config files : C:\ProgramData\CooperConda\.condarc
          conda version : 4.7.11
    conda-build version : 3.18.9
         python version : 3.6.9.final.0
       virtual packages : __cuda=9.1
       base environment : C:\ProgramData\CooperConda  (writable)
           channel URLs : http://technicalwebdev/CooperConda/Internal/win-64
                          http://technicalwebdev/CooperConda/Internal/noarch
                          http://technicalwebdev/CooperConda/External/win-64
                          http://technicalwebdev/CooperConda/External/noarch
          package cache : C:\ProgramData\CooperConda\pkgs
                          C:\Users\zdkohler\.conda\pkgs
                          C:\Users\zdkohler\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\CooperConda\envs
                          C:\Users\zdkohler\.conda\envs
                          C:\Users\zdkohler\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.6.9 Windows/10 Windows/10.0.17134
          administrator : True
             netrc file : None
           offline mode : False
```

**Comment by marcelotrevisani** [comment]
Thanks, @y2kbugger and @prusse-martin for reporting it!
I might take a look at it!

**Comment by marcelotrevisani** [comment]
That's fine! No problem at all for me!

If it is already in your plans you can take it then! :)
