### ISSUE TITLE
conda-build failed for some unknown reasons

### ISSUE THREAD

**Issue by peterjc123** [conda/conda-build#3736]
### Actual Behavior

We are building torchvision through conda-build and experience the following error:
```
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' not in tarball
Traceback (most recent call last):
  File "C:\tools\miniconda3\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\tools\miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "C:\tools\miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "C:\tools\miniconda3\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\tools\miniconda3\lib\site-packages\conda_build\build.py", line 2343, in build_tree
    notest=notest,
  File "C:\tools\miniconda3\lib\site-packages\conda_build\build.py", line 1642, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "C:\tools\miniconda3\lib\site-packages\conda_build\build.py", line 1034, in bundle_conda
    tarcheck.check_all(tmp_path, metadata.config)
  File "C:\tools\miniconda3\lib\site-packages\conda_build\tarcheck.py", line 89, in check_all
    x.info_files()
  File "C:\tools\miniconda3\lib\site-packages\conda_build\tarcheck.py", line 53, in info_files
    raise Exception('info/files')
Exception: info/files
Exited with code 1
```
More details https://circleci.com/gh/pytorch/vision/11090?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

### Expected Behavior

Build pass.

### Steps to Reproduce

Powershell:
```powershell
git clone https://github.com/pytorch/vision.git
cd vision
choco install miniconda3
$env:PATH = "C:\tools\miniconda3;C:\tools\miniconda3\Library\usr\bin;C:\tools\miniconda3\Scripts;C:\tools\miniconda3\bin" + $env:PATH
conda install -yq conda-build
bash packaging/build_conda.sh
```

##### `Output of conda info`

```
It should be the latest conda-build. I'll fill this in later.
```

**Comment by msarahan** [comment]
This is because of a bug in conda package handling regarding Unicode on windows. We hope to have a fix later today. Pinning conda-package-handling to <1.15 should avoid the issue.

**Comment by peterjc123** [comment]
Thanks! I'll try.

**Comment by peterjc123** [comment]
@msarahan It works, thanks. May I ask another question? How to disable the following test/check?:
```
number of files: 3334
   INFO (pytorch,Lib\site-packages\torch\lib\c10_cuda.dll): Needed DSO $SYSROOT\System32\api-ms-win-crt-string-l1-1-0.dll found in the whitelist
   INFO (pytorch,Lib\site-packages\torch\lib\c10_cuda.dll): Needed DSO $SYSROOT\System32\api-ms-win-crt-runtime-l1-1-0.dll found in the whitelist
   INFO (pytorch,Lib\site-packages\torch\lib\c10_cuda.dll): Needed DSO $SYSROOT\System32\KERNEL32.dll found in the whitelist
   INFO (pytorch,Lib\site-packages\torch\lib\c10_cuda.dll): Needed DSO $SYSROOT\System32\api-ms-win-crt-heap-l1-1-0.dll found in the whitelist
WARNING (pytorch,Lib\site-packages\torch\lib\c10_cuda.dll): $RPATH\c10.dll not found in sysroot, is this binary repackaging? .. do you need to use install_name_tool/patchelf?
WARNING (pytorch,Lib\site-packages\torch\lib\c10_cuda.dll): Needed DSO C:\Windows\System32\MSVCP140.dll not found in any CDT/compiler package, nor the whitelist?!
WARNING (pytorch,Lib\site-packages\torch\lib\c10_cuda.dll): Needed DSO C:\Windows\System32\VCRUNTIME140.dll not found in any CDT/compiler package, nor the whitelist?!
   INFO (pytorch,Lib\site-packages\torch\test\common_test.exe): Needed DSO $SYSROOT\System32\api-ms-win-crt-time-l1-1-0.dll found in the whitelist
   INFO (pytorch,Lib\site-packages\torch\test\common_test.exe): Needed DSO $SYSROOT\System32\api-ms-win-crt-string-l1-1-0.dll found in the whitelist
   INFO (pytorch,Lib\site-packages\torch\test\common_test.exe): Needed DSO $SYSROOT\System32\api-ms-win-crt-filesystem-l1-1-0.dll found in the whitelist
   INFO (pytorch,Lib\site-packages\torch\test\common_test.exe): Needed DSO $SYSROOT\System32\api-ms-win-crt-environment-l1-1-0.dll found in the whitelist
   INFO (pytorch,Lib\site-packages\torch\test\common_test.exe): Needed DSO $SYSROOT\System32\api-ms-win-crt-runtime-l1-1-0.dll found in the whitelist
```
It's taking more than 30 min, which is too long for us.
