### ISSUE TITLE
Symbol not found: _libiconv

### ISSUE THREAD

**Issue by jsolbrig** [conda/conda-build#3770]
### Actual Behavior

Running `conda-build` for any of my packages produces the error shown below.  This occurs on OSX (Mojave in my case), but not on either Debian or Alpine.  `conda` was installed using the command line installer from anaconda.com.  The symbol `_libiconv` appears to be missing in `libarchive.dylib`, but is present in both `libiconv.2.dylib` and `libiconv.a`.

```
Traceback (most recent call last):
  File "/Users/jsolbrig/anaconda3/envs/cshdfeos/bin/conda-build", line 7, in <module>
    from conda_build.cli.main_build import main
  File "/Users/jsolbrig/anaconda3/envs/cshdfeos/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 18, in <module>
    import conda_build.api as api
  File "/Users/jsolbrig/anaconda3/envs/cshdfeos/lib/python3.7/site-packages/conda_build/api.py", line 22, in <module>
    from conda_build.config import (Config, get_or_merge_config, get_channel_urls,
  File "/Users/jsolbrig/anaconda3/envs/cshdfeos/lib/python3.7/site-packages/conda_build/config.py", line 17, in <module>
    from .variants import get_default_variant
  File "/Users/jsolbrig/anaconda3/envs/cshdfeos/lib/python3.7/site-packages/conda_build/variants.py", line 15, in <module>
    from conda_build.utils import ensure_list, trim_empty_keys, get_logger
  File "/Users/jsolbrig/anaconda3/envs/cshdfeos/lib/python3.7/site-packages/conda_build/utils.py", line 9, in <module>
    import libarchive
  File "/Users/jsolbrig/anaconda3/envs/cshdfeos/lib/python3.7/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/Users/jsolbrig/anaconda3/envs/cshdfeos/lib/python3.7/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/Users/jsolbrig/anaconda3/envs/cshdfeos/lib/python3.7/site-packages/libarchive/ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "/Users/jsolbrig/anaconda3/envs/cshdfeos/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/Users/jsolbrig/anaconda3/envs/cshdfeos/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/jsolbrig/anaconda3/envs/cshdfeos/bin/../lib/libarchive.dylib, 6): Symbol not found: _libiconv
  Referenced from: /Users/jsolbrig/anaconda3/envs/cshdfeos/bin/../lib/libarchive.dylib
  Expected in: /usr/lib/libiconv.2.dylib
 in /Users/jsolbrig/anaconda3/envs/cshdfeos/bin/../lib/libarchive.dylib
```

#### Output of `nm libarchive.dynlib | grep _libiconv`
```
                 U _libiconv
                 U _libiconv_close
                 U _libiconv_open
```

#### Output of `nm libiconv.2.dynlib | grep _libiconv`
```
00000000000e0258 D __libiconv_version
0000000000002a00 T _libiconv
0000000000002a30 T _libiconv_close
0000000000001480 T _libiconv_open
0000000000002a40 T _libiconv_open_into
00000000000164e0 t _libiconv_relocate
0000000000016420 T _libiconv_set_relocation_prefix
0000000000002f40 T _libiconvctl
0000000000003050 T _libiconvlist
```

#### Output of `nm libiconv.a | grep _libiconv`
```
00000000000de758 D __libiconv_version
0000000000001710 T _libiconv
0000000000001740 T _libiconv_close
0000000000000190 T _libiconv_open
0000000000001750 T _libiconv_open_into
0000000000001c50 T _libiconvctl
0000000000001d60 T _libiconvlist
00000000000000c0 T _libiconv_relocate
0000000000000000 T _libiconv_set_relocation_prefix
```

### Expected Behavior

`libarchive.dynlib` should have `_libiconv` defined I think?

### Steps to Reproduce

Install conda on OSX then run (this should be independent of which package is being built):

```
conda update conda
conda install conda-build
conda-build .
```

##### `Output of conda info`

```
     active environment : cshdfeos
    active env location : /Users/jsolbrig/anaconda3/envs/cshdfeos
            shell level : 2
       user config file : /Users/jsolbrig/.condarc
 populated config files : /Users/jsolbrig/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /Users/jsolbrig/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/jsolbrig/anaconda3/pkgs
                          /Users/jsolbrig/.conda/pkgs
       envs directories : /Users/jsolbrig/anaconda3/envs
                          /Users/jsolbrig/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

#### `output of conda list`

```
# packages in environment at /Users/jsolbrig/anaconda3/envs/cshdfeos:
#
# Name                    Version                   Build  Channel
asn1crypto                1.0.1                    py37_0    conda-forge
beautifulsoup4            4.8.1                    py37_0    conda-forge
bzip2                     1.0.8                h01d97ff_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cffi                      1.12.3           py37hccf1714_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
conda                     4.7.12                   py37_0    conda-forge
conda-build               3.18.9                   py37_5    conda-forge
conda-package-handling    1.6.0            py37h01d97ff_0    conda-forge
cryptography              2.7              py37h212c5bf_0    conda-forge
filelock                  3.0.10                     py_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
libarchive                3.3.3             h5c473cc_1006    conda-forge
libblas                   3.8.0               13_openblas    conda-forge
libcblas                  3.8.0               13_openblas    conda-forge
libcxx                    9.0.0                         0    conda-forge
libcxxabi                 9.0.0                         0    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
liblapack                 3.8.0               13_openblas    conda-forge
liblief                   0.9.0                h2a1bed3_1    conda-forge
libopenblas               0.3.7                h4bb4525_1    conda-forge
libxml2                   2.9.9                h12c6b28_5    conda-forge
llvm-openmp               9.0.0                h40edb58_0    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
lzo                       2.10              h1de35cc_1000    conda-forge
markupsafe                1.1.1            py37h1de35cc_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.17.2           py37h6b0580a_0    conda-forge
openssl                   1.1.1c               h01d97ff_0    conda-forge
pip                       19.2.3                   py37_0    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
psutil                    5.6.3            py37h01d97ff_0    conda-forge
py-lief                   0.9.0            py37h6d6d4d2_1    conda-forge
pycosat                   0.6.3           py37h1de35cc_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.3                h93065d6_1    conda-forge
python-libarchive-c       2.8                   py37_1004    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.1.2            py37h01d97ff_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
ripgrep                   11.0.2               h01d97ff_3    conda-forge
ruamel_yaml               0.15.71         py37h1de35cc_1000    conda-forge
setuptools                41.4.0                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
soupsieve                 1.9.4                    py37_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
tk                        8.6.9             h2573ce8_1003    conda-forge
tqdm                      4.36.1                     py_0    conda-forge
urllib3                   1.25.6                   py37_0    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.0                ha9f0a20_0    conda-forge
```

**Comment by Tobias-Fischer** [comment]
Hi @jsolbrig, I am running into the same problem - were you able to fix it?

**Comment by jsolbrig** [comment]
@Tobias-Fischer Unfortunately, no, the only thing I have been able to do to "solve" the problem is run this inside the miniconda docker container. I don't get the same error there.

**Comment by Tobias-Fischer** [comment]
It seems that `conda upgrade conda-build` might have resolved this for me - give it a go.
