### ISSUE TITLE
conda-index throws an error if ran as a different user and from a conda-environment that is not "base"

### ISSUE THREAD

**Issue by anjos** [conda/conda-build#3783]
### Actual Behavior

If conda-build is installed on a environment that is different than `base`, and `conda-index` executed from this environment to index an existing channel, by an user which cannot write on this directory, then indexing crashes with the following logs:

```txt
Traceback (most recent call last):
  File "/opt/conda/envs/bdt/lib/python3.7/site-packages/conda/gateways/disk/update.py", line 113, in touch
    fh = open(path, 'a')
PermissionError: [Errno 13] Permission denied: '/opt/conda/envs/bdt/pkgs/urls.txt'
```

The directory `/opt/conda/envs/bdt/pkgs/` does not exist as this is not the base environment.

If I manually create the directory and touch `urls.txt` on that directory, then `conda-index` gets happy and runs without problems.  After checking, conda-index does not write anything on this file, so I'm not sure why it needs checking if it is writeable or not.

I also tried setting the `pkgs_dir` variable to the base pkgs directory in the condarc for that particular environment.  That did not help either and it excepts at:

```txt
  File "/opt/conda/envs/bdt/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 165, in first_writable
    raise NoWritablePkgsDirError(pkgs_dirs)
conda.exceptions.NoWritablePkgsDirError: No writeable pkgs directories configured.
  - /opt/conda/pkgs
```

### Expected Behavior

Indexing a conda channel should not require writeability to the conda installation itself.

### Steps to Reproduce

1. Install miniconda as user "A"
2. Create a separate environment (say "test"), still as user "A" that contains "conda-build"
3. Login as user "B"
4. Just for sanity, check that $CONDA_ROOT/envs/test/pkgs does not exist
5. Index a local repo as user "B", that cannot write to the conda installation of "A" (crash should occur)

##### `Output of conda info`

```
     active environment : bdt
    active env location : /opt/conda/envs/bdt
            shell level : 1
       user config file : /var/www/.condarc
 populated config files : /opt/conda/condarc
                          /opt/conda/envs/bdt/condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /opt/conda  (read only)
           channel URLs : http://bobconda.lab.idiap.ch/public/conda/label/beta/linux-64
                          http://bobconda.lab.idiap.ch/public/conda/label/beta/noarch
                          http://bobconda.lab.idiap.ch/public/conda/linux-64
                          http://bobconda.lab.idiap.ch/public/conda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /tmp
       envs directories : /var/www/.conda/envs
                          /opt/conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Linux/4.19.67-2-kvm-amd64 debian/10 glibc/2.28
                UID:GID : 33:33
             netrc file : None
           offline mode : False
```

**Comment by anjos** [comment]
Note: Setting `pkgs_dir` to `/tmp` made it work.  It creates both `urls` and `urls.txt`, that are left empty.
