### ISSUE TITLE
Issue using pipbuild on current (1.3.1) version of sphinx (spec parsing/reconstruction error)

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#380]
Seems to have some error parsing `snowballstemmer >=1.1` and properly reconstructing the spec.

```
$ conda pipbuild sphinx
Package search: {'_pypi_ordering': 50, 'version': '1.3.1', 'name': 'Sphinx', 'summary': 'Python documentation generator'}
Fetching package metadata: ....
Creating standard recipe for sphinx-1.3.1
Converting recipe in /xopt_ilastik/local/src/nanshe-git/docs/sphinx
package = Sphinx
   dependencies = [u'six >=1.4', u'jinja2 >=2.3', u'pygments >=2.0', u'docutils >=0.11', u'snowballstemmer >=1.1', u'babel >=1.3', u'alabaster >=0.7,<0.8', u'sphinx_rtd_theme >=0.1,<0.2']
Creating standard recipe for snowballstemmer->=1.1
Error: Version >=1.1 of snowballstemmer is not available on PyPI.

conda create -n _pipbuild_ --yes python pip
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /zopt/conda/envs/_pipbuild_:

The following NEW packages will be INSTALLED:

    openssl:    1.0.1k-1    
    pip:        6.1.1-py27_0
    python:     2.7.9-1     
    readline:   6.2-2       
    setuptools: 15.0-py27_0 
    sqlite:     3.8.4.1-1   
    tk:         8.5.18-0    
    zlib:       1.2.8-0     

Linking packages ...
[      COMPLETE      ]|###################################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate _pipbuild_
#
# To deactivate this environment, use:
# $ source deactivate
#
/zopt/conda/envs/_pipbuild_/bin/pip install snowballstemmer==>=1.1
Exception:
Traceback (most recent call last):
  File "/zopt/conda/envs/_pipbuild_/lib/python2.7/site-packages/pip/basecommand.py", line 246, in main
    status = self.run(options, args)
  File "/zopt/conda/envs/_pipbuild_/lib/python2.7/site-packages/pip/commands/install.py", line 308, in run
    name, None, isolated=options.isolated_mode,
  File "/zopt/conda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req/req_install.py", line 220, in from_line
    isolated=isolated)
  File "/zopt/conda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req/req_install.py", line 79, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/zopt/conda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2960, in parse
    reqs = list(parse_requirements(s))
  File "/zopt/conda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2904, in parse_requirements
    "version spec")
  File "/zopt/conda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2869, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'snowballstemmer==>=1.1', 'at', '==>=1.1')

Error: Could not pip install snowballstemmer==>=1.1
```

**Comment by jakirkham** [comment]
Due to the issue with building sphinx via `pipbuild` ( https://github.com/conda/conda-build/issues/380 ), I used `pipbuild` on all of sphinx's dependencies and uploaded them to a binstar channel that is in my config file. In other words, they should install easily.

Now when running `conda pipbuild sphinx`, it seems to fail when trying to find `sphinx-rtd-theme` even though it has been successfully installed. I am suspicious that it is related to a cyclic dependency between `sphinx` and `sphinx-rtd-theme`.

    Package search: {'_pypi_ordering': 50, 'version': '1.3.1', 'name': 'Sphinx', 'summary': 'Python documentation generator'}
    Fetching package metadata: ......
    Creating standard recipe for sphinx-1.3.1
    Error: directory already exists: ./sphinx
    
    conda create -n _pipbuild_ --yes python pip
    Error: prefix already exists: /zopt/conda/envs/_pipbuild_
    /zopt/conda/envs/_pipbuild_/bin/pip install Sphinx==1.3.1
    Collecting Sphinx==1.3.1
      Using cached Sphinx-1.3.1-py2.py3-none-any.whl
    Collecting sphinx-rtd-theme<0.2,>=0.1 (from Sphinx==1.3.1)
      Using cached sphinx_rtd_theme-0.1.7-py2-none-any.whl
    Collecting snowballstemmer>=1.1 (from Sphinx==1.3.1)
      Using cached snowballstemmer-1.2.0.tar.gz
    Collecting six>=1.4 (from Sphinx==1.3.1)
      Using cached six-1.9.0-py2.py3-none-any.whl
    Collecting Pygments>=2.0 (from Sphinx==1.3.1)
      Using cached Pygments-2.0.2-py2-none-any.whl
    Collecting docutils>=0.11 (from Sphinx==1.3.1)
      Using cached docutils-0.12.tar.gz
    Collecting babel>=1.3 (from Sphinx==1.3.1)
      Using cached Babel-1.3.tar.gz
    Collecting Jinja2>=2.3 (from Sphinx==1.3.1)
      Using cached Jinja2-2.7.3.tar.gz
    Collecting alabaster<0.8,>=0.7 (from Sphinx==1.3.1)
      Using cached alabaster-0.7.3.tar.gz
    Collecting pytz>=0a (from babel>=1.3->Sphinx==1.3.1)
      Using cached pytz-2015.2-py2.py3-none-any.whl
    Collecting markupsafe (from Jinja2>=2.3->Sphinx==1.3.1)
      Using cached MarkupSafe-0.23.tar.gz
    Installing collected packages: sphinx-rtd-theme, snowballstemmer, six, Pygments, docutils, pytz, babel, markupsafe, Jinja2, alabaster, Sphinx
      Running setup.py install for snowballstemmer
      Running setup.py install for docutils
      Running setup.py install for babel
      Running setup.py install for markupsafe
      Running setup.py install for Jinja2
      Running setup.py install for alabaster
    Successfully installed Jinja2-2.7.3 Pygments-2.0.2 Sphinx-1.3.1 alabaster-0.7.3 babel-1.3 docutils-0.12 markupsafe-0.23 pytz-2015.2 six-1.9.0 snowballstemmer-1.2.0 sphinx-rtd-theme-0.1.7
    Getting dependencies...
    Fetching package metadata: ......
    
    Package plan for package removal in environment /zopt/conda/envs/_pipbuild_:
    
    The following packages will be REMOVED:
    
        openssl:    1.0.1k-1    
        pip:        6.1.1-py27_0
        python:     2.7.9-1     
        readline:   6.2-2       
        setuptools: 15.0-py27_0 
        sqlite:     3.8.4.1-1   
        tk:         8.5.18-0    
        zlib:       1.2.8-0     
    
    Unlinking packages ...
    [      COMPLETE      ]|###############################################################################################################################################################################################################| 100%
    package = Sphinx
       dependencies = ['sphinx-rtd-theme', 'snowballstemmer', 'six', 'pygments', 'docutils', 'babel', 'jinja2', 'alabaster']
    Creating standard recipe for sphinx-rtd-theme
    Error: Could not find any versions of package sphinx-rtd-theme
    
    Error: Empty releases for sphinx-rtd-theme

**Comment by snth** [comment]
I have the same issue trying to `conda pipbuild` the packages  `zerorpc` or `gevent`. `conda pipbuild greenlet` worked fine. I also `conda install`ed `greenlet` before trying to `pipbuild` `gevent` again but that made no difference.  

I am using `conda-build 1.14.0` with `conda 3.14.0` on an Ubuntu 12.04 linux-64 system.

```
$ uname -a
Linux 803baf5685c8 3.13.0-55-generic #92~precise1-Ubuntu SMP Sun Jun 14 18:32:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ conda list
# packages in environment at /opt/anaconda:
#
alabaster                 0.7.3                    py27_0  
babel                     1.3                      py27_0  
backports.ssl-match-hostname 3.4.0.2                   <pip>
binstar                   0.11.0                   py27_0  
cairo                     1.12.18                       4  
certifi                   14.05.14                 py27_0  
clyent                    0.3.4                    py27_0  
conda                     3.14.0                   py27_0  
conda-build               1.14.0                   py27_0  
conda-env                 2.2.1                    py27_0  
...

$ conda pipbuild zerorpc
Package search: {'_pypi_ordering': False, 'version': '0.5.1', 'name': 'zerorpc', 'summary': 'zerorpc is a flexible RPC based on zeromq.'}
Creating standard recipe for zerorpc-0.5.1
Converting recipe in /home/argo/zerorpc
package = zerorpc
   dependencies = [u'gevent >=1.0', u'msgpack-python', u'pyzmq >=13.1.0']
Creating standard recipe for gevent->=1.0
Error: Version >=1.0 of gevent is not available on PyPI.

conda create -n _pipbuild_ --yes python pip
Error: prefix already exists: /opt/anaconda/envs/_pipbuild_
/opt/anaconda/envs/_pipbuild_/bin/pip install gevent==>=1.0
Exception:
Traceback (most recent call last):
  File "/opt/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/opt/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/commands/install.py", line 268, in run
    wheel_cache
  File "/opt/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/basecommand.py", line 268, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/opt/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req/req_install.py", line 207, in from_line
    wheel_cache=wheel_cache)
  File "/opt/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req/req_install.py", line 66, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/opt/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2960, in parse
    reqs = list(parse_requirements(s))
  File "/opt/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2904, in parse_requirements
    "version spec")
  File "/opt/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2869, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'gevent==>=1.0', 'at', '==>=1.0')

Error: Could not pip install gevent==>=1.0

$ conda pipbuild gevent
Package search: {'_pypi_ordering': False, 'version': '1.0.2', 'name': 'gevent', 'summary': 'Coroutine-based network library'}
Creating standard recipe for gevent-1.0.2
Converting recipe in /home/argo/gevent
package = gevent
   dependencies = [u'greenlet >=0.4.7']
Creating standard recipe for greenlet->=0.4.7
Error: Version >=0.4.7 of greenlet is not available on PyPI.

conda create -n _pipbuild_ --yes python pip
Error: prefix already exists: /opt/anaconda/envs/_pipbuild_
/opt/anaconda/envs/_pipbuild_/bin/pip install greenlet==>=0.4.7
Exception:
Traceback (most recent call last):
  File "/opt/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/opt/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/commands/install.py", line 268, in run
    wheel_cache
  File "/opt/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/basecommand.py", line 268, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/opt/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req/req_install.py", line 207, in from_line
    wheel_cache=wheel_cache)
  File "/opt/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req/req_install.py", line 66, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/opt/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2960, in parse
    reqs = list(parse_requirements(s))
  File "/opt/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2904, in parse_requirements
    "version spec")
  File "/opt/anaconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2869, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'greenlet==>=0.4.7', 'at', '==>=0.4.7')

Error: Could not pip install greenlet==>=0.4.7
```

**Comment by jakirkham** [comment]
Closing as pipbuild is no longer a thing FWICT.
