### ISSUE TITLE
serious flaw: relative git_url deletes stuff it shouldn't 

### ISSUE THREAD

**Issue by marscher** [conda/conda-build#3829]
After trying to build a recipe with a git_url given as a relative path like this:

source:
  git_url: ../../

Conda-build invoked rmtree on the Miniconda root, yielding all environments + conda itself deleted.
Since I cannot get a version info anymore, but know that I just updated conda-build from conda-forge, it should have been version 3.18.11 .... :puke:

Here is the output of conda-build trying to build the recipe:

```
(base) marscher@goose:~/sources/scikit-time$ conda build devtools/
/srv/public/marscher/software/miniconda3/lib/python3.7/site-packages/conda_build/utils.py:1209: UserWarning: RECIPE_PATH received is a file. File: devtools/conda-recipe/meta.yaml
It should be a path to a folder. 
Forcing conda-build to use the recipe file.
  UserWarning
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Failed to update local git cache. Deleting local cached repo: /srv/public/marscher/software/miniconda3/conda-bld/git_cache/../.. 
Traceback (most recent call last):
  File "/srv/public/marscher/software/miniconda3/lib/python3.7/site-packages/conda_build/source.py", line 218, in git_mirror_checkout_recursive
  File "/srv/public/marscher/software/miniconda3/lib/python3.7/site-packages/conda_build/utils.py", line 399, in check_call_env
  File "/srv/public/marscher/software/miniconda3/lib/python3.7/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
  File "/srv/public/marscher/software/miniconda3/lib/python3.7/subprocess.py", line 347, in check_call
subprocess.CalledProcessError: Command '['/usr/bin/git', 'fetch', 'origin', '+HEAD:_conda_cache_origin_head']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/public/marscher/software/miniconda3/bin/conda-build", line 11, in <module>
  File "/srv/public/marscher/software/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 449, in main
  File "/srv/public/marscher/software/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 440, in execute
  File "/srv/public/marscher/software/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
  File "/srv/public/marscher/software/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 2317, in build_tree
  File "/srv/public/marscher/software/miniconda3/lib/python3.7/site-packages/conda_build/render.py", line 802, in render_recipe
  File "/srv/public/marscher/software/miniconda3/lib/python3.7/site-packages/conda_build/render.py", line 628, in try_download
  File "/srv/public/marscher/software/miniconda3/lib/python3.7/site-packages/conda_build/source.py", line 655, in provide
  File "/srv/public/marscher/software/miniconda3/lib/python3.7/site-packages/conda_build/source.py", line 328, in git_source
  File "/srv/public/marscher/software/miniconda3/lib/python3.7/site-packages/conda_build/source.py", line 228, in git_mirror_checkout_recursive
  File "/srv/public/marscher/software/miniconda3/lib/python3.7/shutil.py", line 495, in rmtree
  File "/srv/public/marscher/software/miniconda3/lib/python3.7/shutil.py", line 493, in rmtree
FileNotFoundError: [Errno 2] No such file or directory: '/srv/public/marscher/software/miniconda3/conda-bld/git_cache/../..'
```
and 
```
(base) marscher@goose:~/sources/scikit-time$ conda build devtools/
bash: /srv/public/marscher/software/miniconda3/bin/conda: No such file or directory
```

Invoking rmtree, without checking paths is an absolute no-go, I'd submit a PR for it, but I will have to spent my time now on restoring backups and updating again.

@thempel fyi

**Comment by marcelotrevisani** [comment]
for your case, should it be?
```yaml
source:
    path: ../../
```
But I agree that it would be good to raise an error in your case instead of doing that

**Comment by marcelotrevisani** [comment]
I think I didn't understand it properly, could you please share the recipe? is this a public project? How are you building it?

**Comment by marscher** [comment]
The recipe is contained in a git repo within two subdirectories:
$PROJECT_ROOT/devtools/conda-recipe/meta.yaml

the recipe contents are irrelevant for this except for the relative git url, which I expected to point to $PROJECT_ROOT in this case.

I will setup a minimum example, probably in a docker container, so nobody screws their installation while playing around with this bug.

**Comment by marscher** [comment]
> for your case, should it be?
> 
> ```yaml
> source:
>     path: ../../
> ```
This is what I used before, and I guess most people use. But the behaviour is different, since the plain past just copies over everything, while git does a clone. The plain copy will drag in undesired files like already built python extensions etc. The git clone on the other hand is clean.

**Comment by marscher** [comment]
I've created a Docker recipe to show/proof that the conda-root directory is being deleted by the reported pattern: https://github.com/marscher/conda-build-3829

I also have to admit, that this use case is probably super rare. However one should never recursively delete things, without checking that the root is a sane location! :skull_and_crossbones:
