### ISSUE TITLE
$CONDA_PREFIX/bin/python can be different from $PYTHON in build.sh/bld.bat

### ISSUE THREAD

**Issue by cmeyer** [conda/conda-build#3914]
### Actual Behavior

The environment active when `build.sh` or `bld.bat` is run has an inconsistent $CONDA_PREFIX, maybe different Python than the environment within the $PYTHON or %PYTHON% environment variable.

### Expected Behavior

$CONDA_PREFIX should point to the environment of $PYTHON.

See [Environment variables set during the build process](https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#environment-variables-that-affect-the-build-process)

### Steps to Reproduce

Use a recipe:

```
{% set name = "mypackage" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [py2k or python_impl == 'pypy']

requirements:
  host:
    - python 3.6.*
  run:
    - python
```

and `build.sh`:

```
#!/bin/bash

conda info
"${PYTHON}" --version
"${CONDA_PREFIX}"/bin/python --version
```
Add a basic `conda-forge.yml` "{}".

Render the environment. Used conda smithy 3.6.15.

`conda smithy rerender --feedstock_directory .`

Build it.

`conda build .`

Examine the output from `build.sh`. On my machine, here is the relevant output from `build.sh`:

```

     active environment : $BUILD_PREFIX
    active env location : $BUILD_PREFIX
            shell level : 3
       user config file : /Users/cmeyer/.condarc
 populated config files : /Users/cmeyer/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/cmeyer/Developer/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/cmeyer/Developer/miniconda3/pkgs
                          /Users/cmeyer/.conda/pkgs
       envs directories : /Users/cmeyer/Developer/miniconda3/envs
                          /Users/cmeyer/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

Python 3.6.10 :: Anaconda, Inc.
/Users/cmeyer/Developer/miniconda3/conda-bld/bad_1585196748893/work/conda_build.sh: line 7: /Users/cmeyer/Developer/miniconda3/conda-bld/bad_1585196748893/_build_env/bin/python: No such file or directory
Traceback (most recent call last):
  File "/Users/cmeyer/Developer/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/cmeyer/Developer/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 469, in main
    execute(sys.argv[1:])
  File "/Users/cmeyer/Developer/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 460, in execute
    verify=args.verify, variants=args.variants)
  File "/Users/cmeyer/Developer/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/cmeyer/Developer/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 2344, in build_tree
    notest=notest,
  File "/Users/cmeyer/Developer/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 1492, in build
    cwd=src_dir, stats=build_stats)
  File "/Users/cmeyer/Developer/miniconda3/lib/python3.7/site-packages/conda_build/utils.py", line 398, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/cmeyer/Developer/miniconda3/lib/python3.7/site-packages/conda_build/utils.py", line 378, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
```

The conda info environment shows 3.7 or 3.8. The Python version using $PYTHON shows 3.6. $CONDA_PREFIX seems invalid.

##### `Output of conda info`

```

     active environment : smithy
    active env location : /Users/cmeyer/Developer/miniconda3/envs/smithy
            shell level : 2
       user config file : /Users/cmeyer/.condarc
 populated config files : /Users/cmeyer/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/cmeyer/Developer/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/cmeyer/Developer/miniconda3/pkgs
                          /Users/cmeyer/.conda/pkgs
       envs directories : /Users/cmeyer/Developer/miniconda3/envs
                          /Users/cmeyer/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

See https://github.com/conda-forge/conda-forge.github.io/pull/1015 too.

**Comment by mingwandroid** [comment]
This is not a bug. Conda lives in its own environment. This is the version that conda info always reports.

For can see this for yourself with some tests. If condabin is on PATH it the shell scripts are registered in your shell correctly then, from a completely unactivated state, conda info reports the base envs python. If you then create a python env for 3.8 where the base env has 3.7 (for example), then conda info still shows 3.7.

This is what we care about mostly when we get bug reports. We want to know the python version that's running the show, not the python version in some random env.

Python is just a package like any other. To see the version installed in any given env you need to use conda list.

Perhaps we could rename this field in the output so it is less confusing though, but that'd likely cause a lot of disruption to automated systems.

**Comment by mingwandroid** [comment]
Further, that it's only listing base env versions can be seen from the fact it's in a block of versions, conda, conda-build, python. The first two can *only* be installed in the base env!
