### ISSUE TITLE
conda-build python 3.8 issue with cuda driver. 

### ISSUE THREAD

**Issue by weinbe58** [conda/conda-build#3938]
I'm running a linux-64 build for my package [QuSpin](https://github.com/weinbe58/QuSpin)

### Actual Behavior
This issue happens after running `conda build --no-anaconda-upload ./conda.recipe` in the top directory of my repo.

I should mention that this package makes no use of cuda directly in the code it only comes in from Numba if I had to guess. 

During the first part of the build matrix, namely for python 3.8, the build fails to render and I get conflicts but during the output for the conflicts there is another exception so the output does not get to finish.

### Expected Behavior

I would expect that the build runs normally, either giving me some issues due to conflicts in the recipe or just finish the build. 

### Steps to Reproduce

```
git clone https://github.com/weinbe58/QuSpin.git
cd QuSpin
condo build --no-anaconda-upload ./conda.recipe
```
gives the following output:
```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /home/phillip/Documents/ED_python/sources/QuSpin/conda.recipe/quspin/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /home/phillip/Documents/ED_python/sources/QuSpin/conda.recipe/quspin/conda_build_config.yaml
Attempting to finalize metadata for quspin
INFO:conda_build.metadata:Attempting to finalize metadata for quspin
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                        

Leaving build/test directories:
  Work:
 /home/phillip/anaconda3/conda-bld/work 
  Test:
 /home/phillip/anaconda3/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/phillip/anaconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold 
  Build:
source activate  /home/phillip/anaconda3/conda-bld/_build_env 


Traceback (most recent call last):
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda_build/environ.py", line 757, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda/plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 808, in _run_sat
    should_retry_solve=ssc.should_retry_solve
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 1318, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 351, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package ca-certificates conflicts for:
boost -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
cython -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
python=3.8 -> openssl[version='>=1.1.1e,<1.1.2a'] -> ca-certificates

Package setuptools conflicts for:
cython -> setuptools
python=3.8 -> pip -> setuptools

Package python conflicts for:
boost -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']
numpy=1.17.2 -> mkl-service[version='>=2,<3.0a0'] -> python[version='>=2.7,<2.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0']
cython -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0']
python=3.8
numpy=1.17.2 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Package numpy conflicts for:
numpy=1.17.2
boost -> py-boost==1.71.0=py38h962f231_0 -> numpy[version='>=1.11.3,<2.0a0|>=1.9.3,<2.0a0']

Package _libgcc_mutex conflicts for:
numpy=1.17.2 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
python=3.8 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
cython -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==9.1=0
  - feature:|@/linux-64::__cuda==9.1=0

Your installed CUDA driver is: 9.1


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phillip/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 469, in main
    execute(sys.argv[1:])
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 460, in execute
    verify=args.verify, variants=args.variants)
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda_build/build.py", line 2344, in build_tree
    notest=notest,
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda_build/build.py", line 1335, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda_build/render.py", line 746, in expand_outputs
    for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda_build/metadata.py", line 2048, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda_build/metadata.py", line 719, in finalize_outputs_pass
    parent_metadata.parse_until_resolved()
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda_build/metadata.py", line 1018, in parse_until_resolved
    bypass_env_check=bypass_env_check)
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda_build/metadata.py", line 940, in parse_again
    bypass_env_check=bypass_env_check),
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda_build/metadata.py", line 1528, in _get_contents
    rendered = template.render(environment=env)
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/phillip/Documents/ED_python/sources/QuSpin/conda.recipe/quspin/meta.yaml", line 30, in top-level template code
    - {{ pin_compatible('numpy') }} 
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda_build/jinja_context.py", line 230, in pin_compatible
    pins, _, _ = get_env_dependencies(m, 'host', m.config.variant)
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda_build/render.py", line 154, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/home/phillip/anaconda3/lib/python3.7/site-packages/conda_build/environ.py", line 759, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'feature:/linux-64::__cuda==9.1=0', 'feature:|@/linux-64::__cuda==9.1=0'}

```

##### `Output of conda info`

```
     active environment : py38
    active env location : /home/phillip/anaconda3/envs/py38
            shell level : 2
       user config file : /home/phillip/.condarc
 populated config files : /home/phillip/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.7.final.0
       virtual packages : __cuda=9.1
                          __glibc=2.27
       base environment : /home/phillip/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/phillip/anaconda3/pkgs
                          /home/phillip/.conda/pkgs
       envs directories : /home/phillip/anaconda3/envs
                          /home/phillip/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.7 Linux/4.15.0-96-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

**Comment by mingwandroid** [comment]
This is a conda issue, would you agree @kalefranz ?

**Comment by sodre** [comment]
I am experiencing a similar issue on an almost brand-new box with conda install using the .deb files.

**Comment by sodre** [comment]
I did a little bit more digging.... I think the solver is failing because there is no `conda-build` for osx or linux out of the [anaconda channel.](https://anaconda.org/anaconda/conda-build/files?version=3.18.11)

**Comment by s22chan** [comment]
This is basically the same issue as #3956
