### ISSUE TITLE
AssertionError: assert isdir(mirror_dir)

### ISSUE THREAD

**Issue by jschueller** [conda/conda-build#3992]
conda-build throws an error on windows with this simple recipe with a git repo (see https://github.com/conda-forge/r-destinie-feedstock/blob/master/recipe/meta.yaml):
```
source:
  git_url: https://github.com/nosretraites/Destinie-2.git
  git_rev: 588198941ced3926fcb57c360d41a82e588bef77
```

it throws with:
```
Executing transaction: ...working... done
Cloning into bare repository '/d/bld/git_cache/github.com/nosretraites/Destinie-2.git'...
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 465, in execute
    verify=args.verify, variants=args.variants)
  File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 2864, in build_tree
    notest=notest,
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1921, in build
    try_download(m, no_download_source=False, raise_error=True)
  File "C:\Miniconda\lib\site-packages\conda_build\render.py", line 639, in try_download
    source.provide(metadata)
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 657, in provide
    verbose=metadata.config.verbose)
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 330, in git_source
    git_depth=git_depth, is_top_level=True, verbose=verbose)
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 248, in git_mirror_checkout_recursive
    assert isdir(mirror_dir)
AssertionError
##[error]Cmd.exe exited with code '1'.
Finishing: Build recipe
```

the recipe builds fine on linux/osx

full log:
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/187455/logs/33

**Comment by dnanto** [comment]
Got the same error: might have to do with [building from repos](https://conda-forge.org/docs/maintainer/adding_pkgs.html#tarballs-no-repos). Trying this soon.

**Comment by dnanto** [comment]
For the record, this resolved the assertion error in my case.

**Comment by kumaraditya303** [comment]
@dnanto How did you resolve the assertion ?

**Comment by dnanto** [comment]
build from tar, not repo: 

in my case, for r-bactdating,

changed this:
  git_url: https://github.com/xavierdidelot/BactDating
  git_tag: v1.0

to this:
  url: https://github.com/xavierdidelot/BactDating/archive/v1.0.tar.gz
  sha256: add9c391709e4d340d173cfb29d30ec6815d5ce89ff8038cea981260be01b151

build from tar, not repo
