### ISSUE TITLE
FileNotFoundError when running conda skeleton pypi [my package name]

### ISSUE THREAD

**Issue by jammerware** [conda/conda-build#4022]
### Actual Behavior

When I attempt to use `conda skeleton` to produce a conda package from my package on PyPI, I receive the log below. Note that it reports working in `%TEMP%/tmplvmmurg3`, and note the apparent missing slash in the file path at the bottom of the log.

```
Jammer@Command-Center MINGW64 ~
$ conda skeleton pypi pandashape
Warning, the following versions were found for pandashape
0.0.1
0.0.2
0.0.3
0.0.4
Using 0.0.4
Use --version to specify a different version.
Using url https://files.pythonhosted.org/packages/a8/c7/d7e8e476049fae19e3f4fd37f1fc14860da06b40f142af7922f7a2b4ac4f/pandashape-0.0.4.tar.gz (9 KB) for pandashape.
Downloading pandashape
PyPI URL:  https://files.pythonhosted.org/packages/a8/c7/d7e8e476049fae19e3f4fd37f1fc14860da06b40f142af7922f7a2b4ac4f/pandashape-0.0.4.tar.gz
Using cached download
Unpacking pandashape...
done
working in C:\Users\Jammer\AppData\Local\Temp\tmplvmmurg3conda_skeleton_pandashape-0.0.4.tar.gz

Leaving build/test directories:
  Work:
 D:\Anaconda3\conda-bld\skeleton_1597917055159\work
  Test:
 D:\Anaconda3\conda-bld\skeleton_1597917055159\test_tmp
Leaving build/test environments:
  Test:
source activate  D:\Anaconda3\conda-bld\skeleton_1597917055159\_test_env
  Build:
source activate  D:\Anaconda3\conda-bld\skeleton_1597917055159\_build_env


Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\conda-skeleton-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\Anaconda3\lib\site-packages\conda_build\cli\main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "D:\Anaconda3\lib\site-packages\conda_build\cli\main_skeleton.py", line 61, in execute
    version=args.version, config=config)
  File "D:\Anaconda3\lib\site-packages\conda_build\api.py", line 290, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "D:\Anaconda3\lib\site-packages\conda_build\skeletons\pypi.py", line 319, in skeletonize
    setup_options=setup_options)
  File "D:\Anaconda3\lib\site-packages\conda_build\skeletons\pypi.py", line 726, in get_package_metadata
    config=config)
  File "D:\Anaconda3\lib\site-packages\conda_build\skeletons\pypi.py", line 1127, in get_pkginfo
    setup_options=setup_options)
  File "D:\Anaconda3\lib\site-packages\conda_build\skeletons\pypi.py", line 1155, in run_setuppy
    with open(os.path.join(src_dir, "setup.py")) as setup:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Jammer\\AppData\\Local\\Temp\\tmplvmmurg3conda_skeleton_pandashape-0.0.4.tar.gz\\pandashape-0.0.4\\setup.py'
```

### Expected Behavior

I expect no error message and that the conda skeleton PyPI recipe be run.

### Steps to Reproduce

In any directory, run `conda skeleton pypi pandashape`.

**OS**: Windows 10.0.19041
**Shell**: Tested both in git bash and in cmd

##### `Output of conda info`

```
active environment : base
    active env location : D:\Anaconda3
            shell level : 1
       user config file : C:\Users\Jammer\.condarc
 populated config files : C:\Users\Jammer\.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=11.0
       base environment : D:\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda3\pkgs
                          C:\Users\Jammer\.conda\pkgs
                          C:\Users\Jammer\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda3\envs
                          C:\Users\Jammer\.conda\envs
                          C:\Users\Jammer\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
```

**Comment by shoemakerdr** [comment]
Looks to me like [the pandashape package](https://github.com/jammerware/pandashape) is formatted in a non-standard way as far as Python packages go. Usually the setup.py is in the top level of the project. This has it in a `scripts` subdir. You probably want to move it to the top level of the project to be more in line with [Python packaging standards](https://packaging.python.org/tutorials/packaging-projects/).
