### ISSUE TITLE
Error while creating conda recipe

### ISSUE THREAD

**Issue by mulianananaconda** [conda/conda-build#4108]
Error occurs when I tried to generate a recipe for one package from Pypi using skeleton.
When I run the command `conda skeleton pypi openshift`, KeyError is raised:

```
Traceback (most recent call last):
  File ".../miniconda3/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File ".../miniconda3/lib/python3.7/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File ".../miniconda3/lib/python3.7/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    version=args.version, config=config)
  File ".../miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 290, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File ".../miniconda3/lib/python3.7/site-packages/conda_build/skeletons/pypi.py", line 319, in skeletonize
    setup_options=setup_options)
  File ".../miniconda3/lib/python3.7/site-packages/conda_build/skeletons/pypi.py", line 733, in get_package_metadata
    list_deps = get_dependencies(requires, is_setuptools_enabled(pkginfo))
  File ".../miniconda3/lib/python3.7/site-packages/conda_build/skeletons/pypi.py", line 803, in get_dependencies
    dep, marker = parse_dep_with_env_marker(dep)
  File ".../miniconda3/lib/python3.7/site-packages/conda_build/skeletons/pypi.py", line 709, in parse_dep_with_env_marker
    match.group("env_mark_constraint"))
  File ".../miniconda3/lib/python3.7/site-packages/conda_build/skeletons/pypi.py", line 696, in env_mark_lookup
    marker = " ".join((env_mark_table[env_mark_name]["repl"],
KeyError: '~'
```

I think this is related to the line in the requirements
```
requirements:
  run:
    - kubernetes ~=11.0.0
```

### Actual Behavior

KeyError occurs

### Expected Behavior

recipe created successfully

### Steps to Reproduce

1. Create and activate conda environment
2. Install conda-build
3. Run command: conda skeleton pypi openshift

##### `Output of conda info`

```
     active environment : base
    active env location : /Users/mulia/miniconda3
            shell level : 1
       user config file : /Users/mulia/.condarc
 populated config files : /Users/mulia/.condarc
          conda version : 4.8.4
    conda-build version : 3.18.11
         python version : 3.7.4.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/mulia/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/mulia/miniconda3/pkgs
                          /Users/mulia/.conda/pkgs
       envs directories : /Users/mulia/miniconda3/envs
                          /Users/mulia/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.7.4 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 2008416210:188724832
             netrc file : None
           offline mode : False
```

**Comment by marcelotrevisani** [comment]
If you want to, you can try to use [Grayskull](https://github.com/conda-incubator/grayskull) to generate this recipe for you :)

**Comment by mingwandroid** [comment]
@marcelotrevisani , while I appreciate your work here, this is the conda-build issue tracker, not the advise-people-with-conda-build-issues-to-use-a-different-tool tracker.

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani, while I appreciate your work here on Grayskull, this is the conda-build issue tracker, not the advise-people-with-conda-build-issues-to-use-a-different-tool tracker.

Sure, I was proposing just a workaround. Specially now that grayskull is under conda-incubator and it is a community effort to improve the conda ecosystem.

**Comment by mingwandroid** [comment]
Part one of the my proposed fix: https://github.com/conda/conda/pull/10313

**Comment by mingwandroid** [comment]
Please help review. There's another PR needed to conda-build after this one.

**Comment by mingwandroid** [comment]
Part 2 of the fix (covers using older condas): https://github.com/conda/conda-build/pull/4113

**Comment by mingwandroid** [comment]
conda-build has been released now. You should see in meta.yaml e.g. `    - kubernetes >=11.0.0,==11.0.*`
