### ISSUE TITLE
Building a rust application on a centos7+miniconda docker container failed at compiling `openssl-sys v0.9.58`

### ISSUE THREAD

**Issue by zhangzhen** [conda/conda-build#4127]
### Actual Behavior
I've developed a home-grown rust app. It can be compiled and run successfully via cargo run. I'm trying to make it a conda package using a docker container, but I'm stuck at compiling and ask for a help.
pkg-config and openssl-devel had been installed via yum before launching conda build.
Ran the following command in the top directory of this project within the container:
conda build -c conda-forge .

The code snippet for meta.yaml:
```
requirements:
  build:
    - rust >=1.43
    - clangdev
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - curl
    - openssl
    - zlib
    - bzip2
    - xz
    - clangdev
```

The error log is listed below:
```
error: failed to run custom build command for `openssl-sys v0.9.58`

Caused by:
  process didn't exit successfully: `/usr/local/conda-bld/famitag_1605343848989/work/target/release/build/openssl-sys-d587e206c2a48e41/build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = Some("/usr/local/conda-bld/famitag_1605343848989/_build_env/bin/x86_64-conda-linux-gnu-cc")
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = Some("-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /usr/local/conda-bld/famitag_1605343848989/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -fdebug-prefix-map=/usr/local/conda-bld/famitag_1605343848989/work=/usr/local/src/conda/famitag-0.0 -fdebug-prefix-map=/usr/local/conda-bld/famitag_1605343848989/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place=/usr/local/src/conda-prefix")
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running "perl" "./Configure" "--prefix=/usr/local/conda-bld/famitag_1605343848989/work/target/release/build/openssl-sys-f23d21a8fd7de1f2/out/openssl-build/install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-shared" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-march=nocona" "-mtune=haswell" "-ftree-vectorize" "-fPIC" "-fstack-protector-strong" "-fno-plt" "-O2" "-ffunction-sections" "-pipe" "-isystem" "/usr/local/conda-bld/famitag_1605343848989/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include" "-fdebug-prefix-map=/usr/local/conda-bld/famitag_1605343848989/work=/usr/local/src/conda/famitag-0.0" "-fdebug-prefix-map=/usr/local/conda-bld/famitag_1605343848989/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place=/usr/local/src/conda-prefix"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.12.0+1.1.1h/src/lib.rs:411:39
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
     1: core::panicking::panic_fmt
               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
     2: core::option::expect_none_failed
               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
     3: core::result::Result<T,E>::unwrap
     4: openssl_src::Build::run_command
     5: openssl_src::Build::build
     6: build_script_main::find_vendored::get_openssl
     7: build_script_main::find_openssl
     8: build_script_main::main
     9: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `famitag v0.1.1 (/usr/local/conda-bld/famitag_1605343848989/work)`, intermediate artifacts can be found at `/usr/local/conda-bld/famitag_1605343848989/work/target`
```
### Expected Behavior
Building finishes successfully.

### Steps to Reproduce
Starts the docker container and runs the following command in the rust project folder:
conda build -c conda-forge .

##### `Output of conda info`

```
     active environment : None
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.9.2
    conda-build version : 3.13.0
         python version : 3.7.9.final.0
       virtual packages : __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local  (writable)
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          http://172.16.110.157:5000/conda/stable/linux-64
                          http://172.16.110.157:5000/conda/stable/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.7.9 Linux/3.10.0-514.el7.x86_64 centos/7.6.1810 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

**Comment by mingwandroid** [comment]
Use {{ compiler('rust') }}

**Comment by mingwandroid** [comment]
You don't need to specify clangdev either,  i expect.

**Comment by m-rossi** [comment]
I am seeing the same issues at https://github.com/conda-forge/starship-feedstock/pull/2

@zhangzhen did you find a solution?
