### ISSUE TITLE
Anaconda not opening on windows 10 

### ISSUE THREAD

**Issue by ifexy** [conda/conda-build#4212]
### Actual Behavior
Anaconda refusing to open either from the prompt or by clicking the icon 

Nothing it just doesn't respond 

### Expected Behavior
Launch anaconda home page to access all apps 

I think it should launch the home screen for anaconda 
### Steps to Reproduce

anaconda-navigator

##### `Output of conda info`

```
Traceback (most recent call last):
  File "C:\Users\Chux\anaconda3\lib\site-packages\qtpy\__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Chux\anaconda3\Scripts\anaconda-navigator-script.py", line 6, in <module>
    from anaconda_navigator.app.main import main
  File "C:\Users\Chux\anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "C:\Users\Chux\anaconda3\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Users\Chux\anaconda3\lib\site-packages\qtpy\__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

**Comment by njalerikson** [comment]
This is not a `conda-build` issue (or `conda` for that matter). You're better off asking this question [at the Anaconda issues project](https://github.com/ContinuumIO/anaconda-issues/issues).

But it looks like your Anaconda install has gotten corrupt and either the Qt bindings have been deleted/moved or were not correctly installed. The easiest solution is likely to reinstall Anaconda.

**Comment by jezdez** [comment]
Yep, what @njalerikson said. Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues).
