### ISSUE TITLE
os_utils.macho.otool(...) crashes if xdotool is installed on the system

### ISSUE THREAD

**Issue by PhilippvK** [conda/conda-build#4213]
### Actual Behavior

`conda build` crashed with the following error message:

```
...
compiling .pyc files...
number of files: 1365
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/tvm-build/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/usr/local/Caskroom/miniconda/base/envs/tvm-build/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/usr/local/Caskroom/miniconda/base/envs/tvm-build/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 465, in execute
    verify=args.verify, variants=args.variants)
  File "/usr/local/Caskroom/miniconda/base/envs/tvm-build/lib/python3.7/site-packages/conda_build/api.py", line 195, in build
    variants=variants
  File "/usr/local/Caskroom/miniconda/base/envs/tvm-build/lib/python3.7/site-packages/conda_build/build.py", line 3013, in build_tree
    notest=notest,
  File "/usr/local/Caskroom/miniconda/base/envs/tvm-build/lib/python3.7/site-packages/conda_build/build.py", line 2291, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/usr/local/Caskroom/miniconda/base/envs/tvm-build/lib/python3.7/site-packages/conda_build/build.py", line 1584, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/usr/local/Caskroom/miniconda/base/envs/tvm-build/lib/python3.7/site-packages/conda_build/build.py", line 1430, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/usr/local/Caskroom/miniconda/base/envs/tvm-build/lib/python3.7/site-packages/conda_build/post.py", line 1318, in post_build
    post_process_shared_lib(m, f, prefix_files, host_prefix)
  File "/usr/local/Caskroom/miniconda/base/envs/tvm-build/lib/python3.7/site-packages/conda_build/post.py", line 1266, in post_process_shared_lib
    mk_relative_osx(path, host_prefix, m.config.build_prefix, files=files, rpaths=rpaths)
  File "/usr/local/Caskroom/miniconda/base/envs/tvm-build/lib/python3.7/site-packages/conda_build/post.py", line 401, in mk_relative_osx
    names = macho.otool(path, prefix)
  File "/usr/local/Caskroom/miniconda/base/envs/tvm-build/lib/python3.7/site-packages/conda_build/os_utils/macho.py", line 195, in otool
    stderr=STDOUT).decode('utf-8')
  File "/usr/local/Caskroom/miniconda/base/envs/tvm-build/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/Caskroom/miniconda/base/envs/tvm-build/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/xdotool', '-l', '/usr/local/Caskroom/miniconda/base/envs/tvm-build/conda-bld/tvm-package_1616363348572/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/tvm/_ffi/_cy3/core.cpython-36m-darwin.so']' returned non-zero exit status 1.
```

This makes sense because `/usr/local/bin/xdotool -l ...` is the wrong tool used here.

### Expected Behavior

I would expect `/usr/bin/otool` to be used here which would not result in an error.

### Steps to Reproduce

Step 4.-7. are the minimal way to reproduce the error. I stumbled across the error running `conda build --output-folder=conda/pkg  conda/recipe` in the [`tvm-build`](https://github.com/apache/tvm/blob/main/conda/build-environment.yaml) environment but that's a rather time-consuming process.

1. Use MacOS
2. Install Homebrew. See: https://brew.sh
3. Install `xdotool` via Homebrew `brew install xdotool`
4. Clone `conda-build` repository `git clone https://github.com/conda/conda-build.git`
5. Enter directory: `cd conda-build`
6. Run interactive python shell: `python3` and do the following:
```
from conda_build.os_utils.macho import otool
otool("")
```
7. Inspect error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Philipp/src/conda-build/conda_build/os_utils/macho.py", line 194, in otool
    stderr=STDOUT).decode('utf-8')
  File "/usr/local/Caskroom/miniconda/base/envs/tvm-build/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/Caskroom/miniconda/base/envs/tvm-build/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/xdotool', '-l', '']' returned non-zero exit status 1.
```
See that `/usr/local/bin/xdotool` is used which has no `-l` option.
8. Uninstall `xdotool`: `brew uninstall xdotool`
9. Repeat steps 5.-6.
10. Now there is still an error because `""` is not an valid input for `otool` but i.e. with `otool("/usr/local/Caskroom/miniconda/base/envs/tvm-build/conda-bld/tvm-package_1616363348572/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/tvm/_ffi/_cy3/core.cpython-36m-darwin.so")` everything works as expected.

I also manually edited `conda_build/os_utils/macho.py` to print out the list of tools found by `tools = find_preferably_prefixed_executable(name, build_prefix, all_matches=True)` and the output is as follows if `xdotool` is installed

```
['/usr/local/bin/xdotool', '/usr/local/bin/xdotool', '/usr/local/bin/xdotool', '/usr/bin/otool']
```

and `['/usr/bin/otool']` if it is not installed.

My crappy workaround looks like this:

```
tools = find_preferably_prefixed_executable(name, build_prefix, all_matches=True)
tools = list(filter(lambda tool: tool != '/usr/local/bin/xdotool', tools))
```

##### Output of `conda info`

```

     active environment : tvm-build
    active env location : /usr/local/Caskroom/miniconda/base/envs/tvm-build
            shell level : 4
       user config file : /Users/Philipp/.condarc
 populated config files :
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local/Caskroom/miniconda/base  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/Caskroom/miniconda/base/pkgs
                          /Users/Philipp/.conda/pkgs
       envs directories : /usr/local/Caskroom/miniconda/base/envs
                          /Users/Philipp/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Darwin/20.2.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by PhilippvK** [comment]
An alternative workaround is of course to uninstall xdotool. :)
