### ISSUE TITLE
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'tensorflow_probability'}

### ISSUE THREAD

**Issue by NEGU93** [conda/conda-build#4230]
So the error is very similar to [this](https://github.com/conda/conda-build/issues/2286) post and also [this](https://stackoverflow.com/questions/45866648/conda-build-unsatisfiable-dependencies-error-with-pint) stackoverflow question but the solution does not work for me.

I have the following [code](https://anaconda.org/negu93/cvnn) that I was updating on anaconda without a problem until I added the [tensorflow-probability](https://anaconda.org/conda-forge/tensorflow-probability) package. Here the link to the [meta.yaml](https://github.com/NEGU93/cvnn/blob/master/conda.recipe/meta.yaml) file.

The accepted solution, running `conda config --add channels conda-forge` throws the following message: `Warning: 'conda-forge' already in 'channels' list, moving to the top` and does not solve the issue, furthermore, `conda config --get channels` command gives:

```
--add channels 'defaults'   # lowest priority
--add channels 'conda-forge'   # highest priority
```
Full error message when using `conda build .`:

```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Copying /home/barrachina/Documents/cvnn to /home/barrachina/anaconda3/conda-bld/cvnn_1621517251993/work/
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for cvnn
INFO:conda_build.metadata:Attempting to finalize metadata for cvnn
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['cvnn-1.1.53-py_0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/barrachina/anaconda3/conda-bld/cvnn_1621517251993/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl


The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-conda_forge             conda-forge
    _openmp_mutex:    4.5-1_gnu                   conda-forge
    ca-certificates:  2020.12.5-ha878542_0        conda-forge
    certifi:          2020.12.5-py37h89c1867_1    conda-forge
    ld_impl_linux-64: 2.35.1-hea4e1c9_2           conda-forge
    libffi:           3.3-h58526e2_2              conda-forge
    libgcc-ng:        9.3.0-h2828fa1_19           conda-forge
    libgomp:          9.3.0-h2828fa1_19           conda-forge
    libstdcxx-ng:     9.3.0-h6de172a_19           conda-forge
    ncurses:          6.2-h58526e2_4              conda-forge
    openssl:          1.1.1k-h7f98852_0           conda-forge
    pip:              21.1.1-pyhd8ed1ab_0         conda-forge
    python:           3.7.10-hffdb5ce_100_cpython conda-forge
    python_abi:       3.7-1_cp37m                 conda-forge
    readline:         8.1-h46c0cb4_0              conda-forge
    setuptools:       49.6.0-py37h89c1867_3       conda-forge
    sqlite:           3.35.5-h74cdb3f_0           conda-forge
    tk:               8.6.10-h21135ba_1           conda-forge
    wheel:            0.36.2-pyhd3deb0d_0         conda-forge
    xz:               5.2.5-h516909a_1            conda-forge
    zlib:             1.2.11-h516909a_1010        conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

Leaving build/test directories:
  Work:
 /home/barrachina/anaconda3/conda-bld/work 
  Test:
 /home/barrachina/anaconda3/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/barrachina/anaconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh 
  Build:
source activate  /home/barrachina/anaconda3/conda-bld/_build_env 


Traceback (most recent call last):
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda_build/environ.py", line 757, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda/plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 275, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 565, in _add_specs
    explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 555, in _get_package_pool
    pool = self.get_reduced_index(specs)
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 576, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 288, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - tensorflow_probability

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/barrachina/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 469, in main
    execute(sys.argv[1:])
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 460, in execute
    verify=args.verify, variants=args.variants)
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda_build/build.py", line 2344, in build_tree
    notest=notest,
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda_build/build.py", line 1408, in build
    create_build_envs(top_level_pkg, notest)
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda_build/build.py", line 1292, in create_build_envs
    raise e
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda_build/build.py", line 1282, in create_build_envs
    channel_urls=tuple(m.config.channel_urls))
  File "/home/barrachina/anaconda3/lib/python3.7/site-packages/conda_build/environ.py", line 759, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'tensorflow_probability'}
```

Output of `conda info`:

```
active environment : tf-2-gpu
    active env location : /home/barrachina/anaconda3/envs/tf-2-gpu
            shell level : 2
       user config file : /home/barrachina/.condarc
 populated config files : /home/barrachina/.condarc
          conda version : 4.9.2
    conda-build version : 3.18.11
         python version : 3.7.10.final.0
       virtual packages : __cuda=11.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/barrachina/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/barrachina/anaconda3/pkgs
                          /home/barrachina/.conda/pkgs
       envs directories : /home/barrachina/anaconda3/envs
                          /home/barrachina/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.22.0 CPython/3.7.10 Linux/5.4.0-73-generic ubuntu/20.04.2 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

Output of `conda list`:

```
#  packages in environment at /home/barrachina/anaconda3/envs/tf-2-gpu:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
_tflow_select             2.1.0                       gpu  
absl-py                   0.11.0           py38h578d9bd_0    conda-forge
aiohttp                   3.7.4            py38h497a2fe_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               20.1.0           py38h497a2fe_2    conda-forge
arrow                     1.0.3            py38h578d9bd_0    conda-forge
astroid                   2.5              py38h578d9bd_1    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
audioread                 2.1.9            py38h578d9bd_0    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
blas                      2.3                    openblas    conda-forge
bleach                    3.3.0              pyh44b312d_0    conda-forge
blinker                   1.4                        py_1    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cachetools                4.2.1              pyhd8ed1ab_0    conda-forge
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
cffi                      1.14.5           py38ha65f79e_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
colorlog                  4.0.2                 py38_1000    conda-forge
commonmark                0.9.1                      py_0    conda-forge
cookiecutter              1.7.2              pyh9f0ad1d_0    conda-forge
coverage                  5.5              py38h497a2fe_0    conda-forge
cryptography              3.4.5            py38ha5dfef3_1    conda-forge
cudatoolkit               10.1.243             h036e899_8    conda-forge
cudnn                     7.6.5.32             hc0a50b0_1    conda-forge
cupti                     10.1.168                      0  
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               hfdff14a_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.3              pyhd8ed1ab_0    conda-forge
dm-tree                   0.1.5            py38h51da96c_2    conda-forge
docutils                  0.16             py38h578d9bd_3    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.2.10               h9c3ff4c_0    conda-forge
ffmpeg                    4.3.1                hca11adc_2    conda-forge
fontconfig                2.13.1            hba837de_1004    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
future                    0.18.2           py38h578d9bd_3    conda-forge
gast                      0.4.0              pyh9f0ad1d_0    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
glib                      2.66.7               h9c3ff4c_1    conda-forge
glib-tools                2.66.7               h9c3ff4c_1    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
google-auth               1.24.0             pyhd3deb0d_0    conda-forge
google-auth-oauthlib      0.4.1                      py_2    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
googleapis-common-protos  1.52.0           py38h578d9bd_1    conda-forge
grpcio                    1.36.1           py38hdd6454d_0    conda-forge
gst-plugins-base          1.18.3               h04508c2_0    conda-forge
gstreamer                 1.18.3               h3560a44_0    conda-forge
h5py                      2.10.0          nompi_py38h7442b35_105    conda-forge
hdf5                      1.10.6          nompi_h7c3c948_1111    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.8                      pypi_0    pypi
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        3.7.2            py38h578d9bd_0    conda-forge
importlib_metadata        3.7.2                hd8ed1ab_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
ipykernel                 5.5.0            py38h81c977d_1    conda-forge
ipython                   7.21.0           py38h81c977d_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
isort                     5.7.0              pyhd8ed1ab_0    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.18.0           py38h578d9bd_2    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jinja2-time               0.2.0                      py_2    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_console           6.2.0                      py_0    conda-forge
jupyter_core              4.7.1            py38h578d9bd_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
kiwisolver                1.3.1            py38h1fd1430_1    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lame                      3.100             h7f98852_1001    conda-forge
lazy-object-proxy         1.5.2            py38h497a2fe_1    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                3_openblas    conda-forge
libcblas                  3.9.0                3_openblas    conda-forge
libclang                  11.1.0          default_ha53f305_0    conda-forge
libcurl                   7.75.0               hc4aaa36_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libflac                   1.3.3                h9c3ff4c_1    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            7.5.0               h14aa051_18    conda-forge
libgfortran4              7.5.0               h14aa051_18    conda-forge
libglib                   2.66.7               h3e27bee_1    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                3_openblas    conda-forge
liblapacke                3.9.0                3_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libllvm11                 11.1.0               hf817b99_0    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     13.1                 hfd2b0eb_2    conda-forge
libprotobuf               3.15.5               h780b84a_0    conda-forge
librosa                   0.8.0              pyh9f0ad1d_0    conda-forge
libsndfile                1.0.31               h9c3ff4c_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.41.0               h7f98852_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.2.0                h7f98852_0    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.10               h72842e0_3    conda-forge
llvm-openmp               11.0.1               h4bd325d_0    conda-forge
llvmlite                  0.35.0           py38h4630a5e_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
markdown                  3.3.4              pyhd8ed1ab_0    conda-forge
markupsafe                1.1.1            py38h497a2fe_3    conda-forge
matplotlib                3.3.4            py38h578d9bd_0    conda-forge
matplotlib-base           3.3.4            py38h0efea84_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py38h497a2fe_1003    conda-forge
more-itertools            8.7.0              pyhd8ed1ab_0    conda-forge
multidict                 5.1.0            py38h497a2fe_1    conda-forge
mysql-common              8.0.23               ha770c72_1    conda-forge
mysql-libs                8.0.23               h935591d_1    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py38h578d9bd_3    conda-forge
nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
nbsphinx                  0.8.1              pyh44b312d_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
nodejs                    15.11.0              h92b4a50_0    conda-forge
notebook                  6.2.0            py38h578d9bd_0    conda-forge
notify-run                0.0.13                   pypi_0    pypi
nspr                      4.29                 h9c3ff4c_1    conda-forge
nss                       3.62                 hb5efdd6_0    conda-forge
numba                     0.52.0           py38h51da96c_0    conda-forge
numpy                     1.20.1           py38h18fd61f_0    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openh264                  2.1.1                h780b84a_0    conda-forge
openpyxl                  3.0.6              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
opt_einsum                3.3.0                      py_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.1.3            py38he6710b0_0    anaconda
pandoc                    2.12                 h7f98852_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.8.1              pyhd8ed1ab_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.0            py38h9a89aac_0    anaconda
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
plotly                    4.14.3             pyh44b312d_0    conda-forge
plotly-orca               3.4.2                         0    conda-forge
pluggy                    0.13.1           py38h578d9bd_4    conda-forge
pooch                     1.3.0              pyhd8ed1ab_0    conda-forge
poyo                      0.5.0                      py_0    conda-forge
prettytable               2.0.0              pyhd8ed1ab_0    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
promise                   2.3              py38h578d9bd_3    conda-forge
prompt-toolkit            3.0.16             pyha770c72_0    conda-forge
prompt_toolkit            3.0.16               hd8ed1ab_0    conda-forge
protobuf                  3.15.5           py38h709712a_0    conda-forge
psutil                    5.7.2            py38h7b6447c_0    anaconda
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydub                     0.23.1                     py_0    conda-forge
pygments                  2.8.1              pyhd8ed1ab_0    conda-forge
pyjwt                     2.0.1              pyhd8ed1ab_0    conda-forge
pylint                    2.6.0                    py38_0    anaconda
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqrcode                  1.2.1                    pypi_0    pypi
pyqt                      5.12.3           py38h578d9bd_7    conda-forge
pyqt-impl                 5.12.3           py38h7400c14_7    conda-forge
pyqt5-sip                 4.19.18          py38h709712a_7    conda-forge
pyqtchart                 5.12             py38h7400c14_7    conda-forge
pyqtwebengine             5.12.1           py38h7400c14_7    conda-forge
pyrsistent                0.17.3           py38h497a2fe_2    conda-forge
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
pysoundfile               0.10.3.post1       pyhd3deb0d_0    conda-forge
pytest                    6.1.1                    py38_0    anaconda
pytest-cov                2.11.0             pyh44b312d_0    conda-forge
pytest-runner             5.2                        py_0    anaconda
python                    3.8.5                h7579374_1    anaconda
python-dateutil           2.8.1                      py_0    conda-forge
python-flatbuffers        1.12               pyhd8ed1ab_0    conda-forge
python-slugify            4.0.1              pyh9f0ad1d_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyzmq                     22.0.3           py38h2035c66_1    conda-forge
qt                        5.12.9               hda022c4_4    conda-forge
qtconsole                 5.0.2              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
recommonmark              0.7.1              pyhd8ed1ab_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
resampy                   0.2.2                      py_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
rise                      5.6.1                    py38_0    anaconda
rsa                       4.7.2              pyh44b312d_0    conda-forge
scikit-learn              0.24.1           py38h658cfdd_0    conda-forge
scipy                     1.6.1            py38hf56f3a7_0  
seaborn                   0.11.1               hd8ed1ab_1    conda-forge
seaborn-base              0.11.1             pyhd8ed1ab_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
sphinx                    3.5.2              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
statsmodels               0.12.2           py38h5c078b8_0    conda-forge
tensorboard               2.4.1              pyhd8ed1ab_0    conda-forge
tensorboard-plugin-wit    1.8.0              pyh44b312d_0    conda-forge
tensorflow                2.4.1           gpu_py38h8a7d6ce_0  
tensorflow-base           2.4.1           gpu_py38h29c2da4_0  
tensorflow-datasets       1.2.0                    py38_0    anaconda
tensorflow-estimator      2.4.1              pyheb71bc4_0  
tensorflow-examples       e7c03e3203165b2864c5dd0255ed9ac3c379fb96-          pypi_0    pypi
tensorflow-gpu            2.4.1                h30adc30_0  
tensorflow-metadata       0.14.0             pyhe6710b0_1  
tensorflow-probability    0.12.2             pyhd8ed1ab_1    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.9.2            py38h578d9bd_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tikzplotlib               0.9.6              pyhd8ed1ab_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py38h497a2fe_1    conda-forge
tqdm                      4.56.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
unidecode                 1.2.0              pyhd8ed1ab_0    conda-forge
urllib3                   1.25.11                  pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
whichcraft                0.6.1                      py_0    conda-forge
widgetsnbextension        3.5.1            py38h578d9bd_4    conda-forge
wrapt                     1.12.1           py38h497a2fe_3    conda-forge
x264                      1!161.3030           h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yarl                      1.6.3            py38h497a2fe_1    conda-forge
zeromq                    4.3.4                h9c3ff4c_0    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge
```

**Comment by charlesdarkwind** [comment]
Same here but I get this, 

`conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'system'}`

have you found a solution for this?
