### ISSUE TITLE
Post build fails on broken symlinks

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#425]
```
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/main_build.py", line 127, in main
    args_func(args, p)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/main_build.py", line 346, in args_func
    args.func(args, p)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/main_build.py", line 305, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/build.py", line 404, in build
    include_recipe=bool(m.path))
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/build.py", line 181, in create_info_files
    files_with_prefix = sorted(have_prefix_files(files))
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/build.py", line 96, in have_prefix_files
    with open(path, 'rb') as fi:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/aaronmeurer/anaconda/envs/_build/bin/pydoc'
```

The problem is that pydoc is a symlink to pydoc3.4, which doesn't exist.

**Comment by asmeurer** [comment]
These days it fails like

```

Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 244, in main
    execute(sys.argv[1:])
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 236, in execute
    already_built=None, config=config, noverify=args.no_verify)
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/conda_build/api.py", line 75, in build
    need_source_download=need_source_download, config=config)
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 1227, in build_tree
    config=recipe_config)
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 921, in build
    create_info_files(m, pkg_files, config=config, prefix=config.build_prefix)
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 469, in create_info_files
    create_info_files_json(m, config.info_dir, prefix, files, files_with_prefix)
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 569, in create_info_files_json
    files_json_files = build_info_files_json(m, prefix, files, files_with_prefix)
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 546, in build_info_files_json
    "size_in_bytes": os.path.getsize(path),
  File "/Users/travis/miniconda3/lib/python3.5/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
NotADirectoryError: [Errno 20] Not a directory: '/Users/travis/miniconda3/conda-bld/recipe_1481621812545/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/ctags'
```

(see e.g., https://travis-ci.org/conda-forge/emacs-feedstock/builds/183488479)

conda build ought to check for bad interpackage symlinks when it does its symlink stuff (I guess out-of-package symlinks should be ignored if they don't point to a real file).

**Comment by msarahan** [comment]
Sorry, but can you please provide an explicit example of how one can test for this?  How does such a link end up being created?  Can you provide a simple build.sh for a recipe that creates such a link?

I'm happy to add a try/except wrapper in build_info_files_json, but that seems like it might miss other potential problems.

**Comment by asmeurer** [comment]
Create a link to a file that doesn't exist in the build.sh. Like `ln -s $PREFIX/doesntexist $PREFIX/link`.
