### ISSUE TITLE
.DS_Store breaks conda build

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#426]
```
Fixing permissions
BUILD END: python-3.5.0b2-0
'lib/.DS_Store' not in info/files
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/main_build.py", line 127, in main
    args_func(args, p)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/main_build.py", line 346, in args_func
    args.func(args, p)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/main_build.py", line 305, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/build.py", line 421, in build
    tarcheck.check_all(path)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/tarcheck.py", line 59, in check_all
    x.info_files()
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/tarcheck.py", line 46, in info_files
    raise Exception('info/files')
Exception: info/files
```

**Comment by dfroger** [comment]
I have a similar problem [here](https://github.com/conda-forge/staged-recipes/pull/2189)
