### ISSUE TITLE
Downstream testing against datalad:  build_tree IndexError: list index out of range

### ISSUE THREAD

**Issue by yarikoptic** [conda/conda-build#4263]
### Actual Behavior

Happened in trying to boost downstream testing version of datalad to 0.14.7 (instead of 0.14.3) in https://github.com/conda-forge/git-annex-feedstock/pull/124#issuecomment-895253436

```
Testing downstream package: datalad=0.14.7
INFO:conda_build.build:Testing downstream package: datalad=0.14.7
INFO conda_build.build:build_tree(3095): Testing downstream package: datalad=0.14.7
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 481, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 470, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3120, in build_tree
    test(list(local_file.values())[0][0],
IndexError: list index out of range
##[error]Bash exited with code '1'.
```

probably relates somehow to switch to use versioneer and auto-mating releasing for datalad which happened in 0.14.5

### Expected Behavior

run testing against datalad as we did before

### Steps to Reproduce

see https://github.com/conda-forge/git-annex-feedstock/pull/124

##### `Output of conda info`

as found in "raw" log
```
2021-08-06T21:57:45.1555776Z ++ conda info
2021-08-06T21:57:45.3980591Z 
2021-08-06T21:57:45.3981720Z      active environment : base
2021-08-06T21:57:45.3982226Z     active env location : /opt/conda
2021-08-06T21:57:45.3982706Z             shell level : 1
2021-08-06T21:57:45.3983187Z        user config file : /home/conda/.condarc
2021-08-06T21:57:45.3983688Z  populated config files : /home/conda/.condarc
2021-08-06T21:57:45.3984174Z           conda version : 4.10.3
2021-08-06T21:57:45.3985207Z     conda-build version : 3.21.4
2021-08-06T21:57:45.3985934Z          python version : 3.8.10.final.0
2021-08-06T21:57:45.3986476Z        virtual packages : __linux=5.8.0=0
2021-08-06T21:57:45.3986956Z                           __glibc=2.12=0
2021-08-06T21:57:45.3987394Z                           __unix=0=0
2021-08-06T21:57:45.3987855Z                           __archspec=1=x86_64
2021-08-06T21:57:45.3988350Z        base environment : /opt/conda  (writable)
2021-08-06T21:57:45.3988859Z       conda av data dir : /opt/conda/etc/conda
2021-08-06T21:57:45.3989346Z   conda av metadata url : None
2021-08-06T21:57:45.3990120Z            channel URLs : https://conda.anaconda.org/conda-forge/linux-64
2021-08-06T21:57:45.3990963Z                           https://conda.anaconda.org/conda-forge/noarch
2021-08-06T21:57:45.3991774Z                           https://repo.anaconda.com/pkgs/main/linux-64
2021-08-06T21:57:45.3992480Z                           https://repo.anaconda.com/pkgs/main/noarch
2021-08-06T21:57:45.3993272Z                           https://repo.anaconda.com/pkgs/r/linux-64
2021-08-06T21:57:45.3993860Z                           https://repo.anaconda.com/pkgs/r/noarch
2021-08-06T21:57:45.3994401Z           package cache : /opt/conda/pkgs
2021-08-06T21:57:45.3994924Z                           /home/conda/.conda/pkgs
2021-08-06T21:57:45.3995428Z        envs directories : /opt/conda/envs
2021-08-06T21:57:45.3995912Z                           /home/conda/.conda/envs
2021-08-06T21:57:45.3996768Z                platform : linux-64
2021-08-06T21:57:45.3997780Z              user-agent : conda/4.10.3 requests/2.26.0 CPython/3.8.10 Linux/5.8.0-1039-azure centos/6.10 glibc/2.12
2021-08-06T21:57:45.3998420Z                 UID:GID : 1001:1001
2021-08-06T21:57:45.3998898Z              netrc file : None
2021-08-06T21:57:45.3999332Z            offline mode : False
```

**Comment by yarikoptic** [comment]
@jwodder , may be you have ideas on what or migration (most likely) to versioneer and auto releases might have caused this?

**Comment by jwodder** [comment]
@yarikoptic I have no such idea.
