### ISSUE TITLE
conda-build should report artifacts build, not rendered

### ISSUE THREAD

**Issue by cjmartian** [conda/conda-build#4286]
### Actual Behavior

When building a multi-output recipe where some of the outputs are noarch with the `--skip-existing` flag, conda-build will incorrectly say it has built something that is really hasn't. This leads to the following stack:

```
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:


# To have conda build upload to anaconda.org automatically, use
# conda config --set anaconda_upload yes
anaconda upload \
/upload/linux-s390x/importlib-metadata-4.8.1-py38ha847dfd_0.tar.bz2 \
/upload/noarch/importlib_metadata-4.8.1-hd3eb1b0_0.tar.bz2 \
/upload/linux-s390x/importlib-metadata-4.8.1-py39ha847dfd_0.tar.bz2 \
/upload/linux-s390x/importlib-metadata-4.8.1-py37ha847dfd_0.tar.bz2
anaconda_upload is not set.  Not uploading wheels: []
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/conda_package_handling/tarball.py", line 146, in extract
_tar_xf(fn, dest_dir)
  File "/opt/conda/lib/python3.8/site-packages/conda_package_handling/tarball.py", line 98, in _tar_xf
archive_utils.extract_file(tarball)
  File "/opt/conda/lib/python3.8/site-packages/conda_package_handling/archive_utils.py", line 15, in extract_file
raise InvalidArchiveError(tarball, error_str.decode('utf-8'))
conda_package_handling.exceptions.InvalidArchiveError: Error with archive /upload/noarch/importlib_metadata-4.8.1-hd3eb1b0_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:

Failed to open '/upload/noarch/importlib_metadata-4.8.1-hd3eb1b0_0.tar.bz2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 481, in main
execute(sys.argv[1:])
  File "/opt/conda/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 470, in execute
outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
return build_tree(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3235, in build_tree
hash_inputs = get_hash_input(tarballs)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/inspect_pkg.py", line 338, in get_hash_input
hash_input = package_has_file(pkg, '/hash_input.json')
  File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 1157, in package_has_file
conda_package_handling.api.extract(package_path, dest_dir=td, components='')
  File "/opt/conda/lib/python3.8/site-packages/conda_package_handling/api.py", line 58, in extract
SUPPORTED_EXTENSIONS[ext].extract(fn, dest_dir, components=components)
  File "/opt/conda/lib/python3.8/site-packages/conda_package_handling/tarball.py", line 151, in extract
_tar_xf_no_libarchive(fn, dest_dir)
  File "/opt/conda/lib/python3.8/site-packages/conda_package_handling/tarball.py", line 105, in _tar_xf_no_libarchive
with open(tarball_full_path, 'rb') as fileobj:
FileNotFoundError: [Errno 2] No such file or directory: '/upload/noarch/importlib_metadata-4.8.1-hd3eb1b0_0.tar.bz2'
```

### Expected Behavior

conda-build should only list artifacts that it actually builds, not artifacts that it renders from a recipe.

### Steps to Reproduce

`conda-build importlib_metadata-feedstock --skip-existing`

##### `Output of conda info`

```
     active environment : None
       user config file : /root/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 4.10.3
    conda-build version : 3.21.5
         python version : 3.8.11.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=s390x
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-s390x
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-s390x
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-s390x
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.8.11 Linux/3.10.0-957.el7.s390x centos/7.7.1908 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

**Comment by crisbal** [comment]
I am not much of an expert with this source code, but it looks like there is already a list of `skipped` packages being updated in the `build()` function ( https://github.com/conda/conda-build/blob/master/conda_build/build.py#L2059 )

This list of skipped packages probably needs to be "propagated" up to the `build_tree()` function ( https://github.com/conda/conda-build/blob/master/conda_build/build.py#L3227 ).

But I am not sure if `build()` just needs to return `packages - skipped` or maybe both `packages, skipped`, and thus some more convoluted changes are required in other places of the codebase.

**Comment by crisbal** [comment]
This exception/error/stacktrace was introduced with commit https://github.com/conda/conda-build/pull/4120/commits/b3b868c232b5fb31eb7c82191dd07f0611732a22 by @mingwandroid in 3.20.6

Since `get_hash_input(tarballs)` (or the code just before) does not check if the tarball exists or not, it will try to compute the hash of a file that does not exists.

The easy fix should be replacing [this line](https://github.com/conda/conda-build/blob/master/conda_build/build.py#L3226) with 
```python
tarballs = [f for f in built_packages if f.endswith(CONDA_PACKAGE_EXTENSIONS) and os.path.isfile(f)]
```  
explicitally removing files that don't exist on disk. 

This should also fix getting an upload command that points to unexistent files

**Comment by crisbal** [comment]
I sent in this patch: https://github.com/conda/conda-build/pull/4316
