### ISSUE TITLE
conda skeleton pypi on packages without setup.py

### ISSUE THREAD

**Issue by mwtoews** [conda/conda-build#4313]
### Summary
Since [PEP 517](https://www.python.org/dev/peps/pep-0517/), Python packages do not require a `setup.py` file anymore. Static project information can simply be stored in a `setup.cfg` file. However, it seems that `conda skeleton pypi` assumes there is always a `setup.py` file present.

### Actual Behavior
I was investigating `conda skeleton pypi` with a package of mine with a recent version:
```
$ conda skeleton pypi surface-water-network --version 0.4
Using url https://files.pythonhosted.org/packages/4b/01/e1fa8581b04c1225d0631eab02665565f8b637ffdf24432496928e97788d/surface-water-network-0.4.tar.gz (87 KB) for surface-water-network.
Downloading surface-water-network
PyPI URL:  https://files.pythonhosted.org/packages/4b/01/e1fa8581b04c1225d0631eab02665565f8b637ffdf24432496928e97788d/surface-water-network-0.4.tar.gz
Using cached download
Unpacking surface-water-network...
done
working in /tmp/tmpqaqetqj1conda_skeleton_surface-water-network-0.4.tar.gz

Leaving build/test directories:
  Work:
 /home/mtoews/miniconda3/conda-bld/skeleton_1635413839046/work 
  Test:
 /home/mtoews/miniconda3/conda-bld/skeleton_1635413839046/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/mtoews/miniconda3/conda-bld/skeleton_1635413839046/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh 
  Build:
source activate  /home/mtoews/miniconda3/conda-bld/skeleton_1635413839046/_build_env 


Traceback (most recent call last):
  File "/home/mtoews/miniconda3/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File "/home/mtoews/miniconda3/lib/python3.9/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/home/mtoews/miniconda3/lib/python3.9/site-packages/conda_build/cli/main_skeleton.py", line 60, in execute
    api.skeletonize(args.packages, args.repo, output_dir=args.output_dir, recursive=args.recursive,
  File "/home/mtoews/miniconda3/lib/python3.9/site-packages/conda_build/api.py", line 276, in skeletonize
    skeleton_return = module.skeletonize(packages, output_dir=output_dir, version=version,
  File "/home/mtoews/miniconda3/lib/python3.9/site-packages/conda_build/skeletons/pypi.py", line 317, in skeletonize
    get_package_metadata(package, d, data, output_dir, python_version,
  File "/home/mtoews/miniconda3/lib/python3.9/site-packages/conda_build/skeletons/pypi.py", line 743, in get_package_metadata
    pkginfo = get_pkginfo(package,
  File "/home/mtoews/miniconda3/lib/python3.9/site-packages/conda_build/skeletons/pypi.py", line 1197, in get_pkginfo
    run_setuppy(src_dir, tempdir, python_version, extra_specs=extra_specs, config=config,
  File "/home/mtoews/miniconda3/lib/python3.9/site-packages/conda_build/skeletons/pypi.py", line 1229, in run_setuppy
    with open(os.path.join(src_dir, "setup.py")) as setup:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpqaqetqj1conda_skeleton_surface-water-network-0.4.tar.gz/surface-water-network-0.4/setup.py'
```

### Expected Behavior

Expected command to succeed. Projects without a `setup.py` file can use [pip](https://packaging.python.org/key_projects/#pip) and [build](https://packaging.python.org/key_projects/#build).

Looking at `run_setuppy` in `conda_build/skeletons/pypi.py`, here are a few comments:
- This should be renamed to something like `run_setuptools`
- Numpy dependencies could alternatively be checked in `setup.cfg` and/or `pyproject.toml`, if they exist.
- `python setup.py install` should be replaced with `python -m pip install .`

Workarounds for projects without a `setup.py` is to run setuptools directly like this:
```
$ python -c "from setuptools import setup; setup()" --help
```
or create a small shim `setup.py` file with these commands.

##### `Output of conda info`

```
     active environment : pyforge
    active env location : /home/mtoews/miniconda3/envs/pyforge
            shell level : 2
       user config file : /home/mtoews/.condarc
 populated config files : /home/mtoews/.condarc
                          /home/mtoews/miniconda3/envs/pyforge/.condarc
          conda version : 4.10.3
    conda-build version : 3.21.5
         python version : 3.9.7.final.0
       virtual packages : __linux=4.15.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/mtoews/miniconda3  (writable)
      conda av data dir : /home/mtoews/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/mtoews/miniconda3/pkgs
                          /home/mtoews/.conda/pkgs
       envs directories : /home/mtoews/miniconda3/envs
                          /home/mtoews/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Linux/4.15.0-159-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 2978:2978
             netrc file : None
           offline mode : False
```

**Comment by ForgottenProgramme** [comment]
Hey, @mwtoews! 
You might want to try [Grayskull](https://github.com/conda-incubator/grayskull). It's a community-developed, stand-alone conda recipe generator. 
You can install Grayskull simply with `conda install -c conda-forge grayskull` 
and then run `grayskull pypi surface-water-network=0.4` to generate the recipe.
