### ISSUE TITLE
`--skip-existing` and `--croot` interact in non-obvious(?) ways

### ISSUE THREAD

**Issue by chenghlee** [conda/conda-build#4345]
### Actual Behavior

Adding `--skip-existing` to the `conda build` command link seems to implicitly add `$CONDA_PREFIX/conda-bld` as a channel. This is potentially confusing and can create unintentional side effects (including errors & crashes) for build systems that use `--croot` to provide some level of build isolation. See the "Steps to Reproduce" section below for an example.

### Expected Behavior

Up for discussion, but I think `--croot` (and `$CONDA_BLD_PATH`) should completely override what `conda build` adds as a local channel; in such cases, `--skip-existing` should _only_ look in the `--croot` directory instead of both there and the `$CONDA_PREFIX/conda-bld` directory.

### Steps to Reproduce

Minimal reproducing recipe:
```
package:
  name: "test-recipe"
  version: "0.1.0"
```

1. Create an empty `$CONDA_PREFIX/conda-bld` directory, without running `conda index` on it. Alternatively, remove the `$CONDA_PREFIX/conda-bld/noarch` subdirectory from.
2. Run `conda build --skip-existing --croot=$PWD/_build` on the above recipe.

conda-build will fail with:
```
$ conda build --croot=$PWD/_build --skip-existing minimal
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for test-minimal
INFO:conda_build.metadata:Attempting to finalize metadata for test-minimal
Traceback (most recent call last):
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda/core/subdir_data.py", line 705, in fetch_repodata_remote_request
    resp.raise_for_status()
  File "$CONDA_PREFIX/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: None for url: file://$CONDA_PREFIX/conda-bld/noarch/repodata.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$CONDA_PREFIX/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 481, in main
    execute(sys.argv[1:])
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 470, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/build.py", line 3085, in build_tree
    packages_from_this = build(metadata, stats,
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/build.py", line 2058, in build
    if om.skip() or (m.config.skip_existing and is_package_built(om, 'host')):
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/build.py", line 3407, in is_package_built
    return bool(SubdirData.query_all(spec, channels=urls, subdirs=(subdir, "noarch")))
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda/api.py", line 214, in query_all
    return tuple(_SubdirData.query_all(package_ref_or_match_spec, channels, subdirs))
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda/core/subdir_data.py", line 140, in query_all
    result = tuple(concat(executor.map(subdir_query, channel_urls)))
  File "$CONDA_PREFIX/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "$CONDA_PREFIX/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "$CONDA_PREFIX/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "$CONDA_PREFIX/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda/core/subdir_data.py", line 132, in <lambda>
    subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda/core/subdir_data.py", line 145, in query
    self.load()
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda/core/subdir_data.py", line 210, in load
    _internal_state = self._load()
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda/core/subdir_data.py", line 375, in _load
    raw_repodata_str = fetch_repodata_remote_request(
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda/core/subdir_data.py", line 736, in fetch_repodata_remote_request
    raise UnavailableInvalidChannel(Channel(dirname(url)), status_code)
conda.exceptions.UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: home/chl/.miniconda3-x86_64/conda-bld
  channel url: file://$CONDA_PREFIX/conda-bld
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. Use `conda index $CONDA_PREFIX/conda-bld`, or create `noarch/repodata.json`
and associated `noarch/repodata.json.bz2`.
```

##### `Output of conda info`

```
     active environment : base
    active env location : $HOME/.miniconda3-x86_64
            shell level : 1
       user config file : $HOME/.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : 3.21.5
         python version : 3.8.11.final.0
       virtual packages : __cuda=11.0=0
                          __linux=5.4.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : $HOME/.miniconda3-x86_64  (writable)
      conda av data dir : $HOME/.miniconda3-x86_64/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : $HOME/.miniconda3-x86_64/pkgs
                          $HOME/.conda/pkgs
       envs directories : $HOME/.miniconda3-x86_64/envs
                          $HOME/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.8.11 Linux/5.4.0-91-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 1000:100
             netrc file : $HOME/.netrc
           offline mode : False
```

**Comment by dkomisar** [comment]
I'm not sure it is directly related to --skip-existing. In the attached log search for the string `envs` and you will see exactly where in the log it switches over from using the supplied croot to the default (incorrect) one
[sip-feedstock.log](https://github.com/conda/conda-build/files/7756410/sip-feedstock.log)
.
