### ISSUE TITLE
conda-pipbuild fails if package home page is not available

### ISSUE THREAD

**Issue by hargup** [conda/conda-build#437]
``` python
$ conda pipbuild 'python-glanceclient
Package search: {'_pypi_ordering': False, 'version': '0.17.1', 'name': 'python-glanceclient', 'summary': 'OpenStack Image API Client Library'}
Fetching package metadata: ....
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Creating standard recipe for python-glanceclient-0.17.1
Converting recipe in /home/ubuntu/pypi-conda-builds/python-glanceclient
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-pipbuild", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 75, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 346, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 361, in execute
    build_package(package, version)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 303, in build_package
    dependencies = convert_recipe(directory, package)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 198, in convert_recipe
    d['homeurl'] = meta['about']['home']
KeyError: 'home'
```

**Comment by msarahan** [comment]
pipbuild no longer exists.  You need to do (at least) 2 steps now:

1. conda skeleton pypi (package name)
2. try building with ``conda build (package name)``
3. troubleshoot as necessary, or if it worked, great, go use your package
