### ISSUE TITLE
Conda build produces ArchiveCreationError on Windows with non-ascii characters in file name

### ISSUE THREAD

**Issue by ChristianZimpelmann** [conda/conda-build#4437]
### Actual Behavior

- I have a package wich contains non-ascii characters in some file names (ä, ö, ü).
- `conda build .` works as expected under Linux.
- Under Windows 10, the following error appears:

<details>

```
...
found egg dir: C:\.conda\envs\gettsim\conda-bld\gettsim_1650523943658\_h_env\Lib\site-packages\gettsim-0.5.0-py3.9.egg
number of files: 141
Fixing permissions
Packaged license file/s.
INFO :: Time taken to mark (prefix)
        0 replacements in 0 files was 0.79 seconds
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(143): Could not remove or rename C:\Users\CHRIST~1\AppData\Local\Temp\tmporjxs318\gettsim-0.5.0-py_0.tar.bz2.  Please remove this file manually (you may need to reboot to free file handles)
Traceback (most recent call last):
  File "C:\.conda\envs\gettsim\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\.conda\envs\gettsim\lib\site-packages\conda_build\cli\main_build.py", line 488, in main
    execute(sys.argv[1:])
  File "C:\.conda\envs\gettsim\lib\site-packages\conda_build\cli\main_build.py", line 477, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "C:\.conda\envs\gettsim\lib\site-packages\conda_build\api.py", line 186, in build
    return build_tree(
  File "C:\.conda\envs\gettsim\lib\site-packages\conda_build\build.py", line 3088, in build_tree
    packages_from_this = build(metadata, stats,
  File "C:\.conda\envs\gettsim\lib\site-packages\conda_build\build.py", line 2371, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "C:\.conda\envs\gettsim\lib\site-packages\conda_build\build.py", line 1692, in bundle_conda
    conda_package_handling.api.create(metadata.config.host_prefix, files,
  File "C:\.conda\envs\gettsim\lib\site-packages\conda_package_handling\api.py", line 88, in create
    raise err
  File "C:\.conda\envs\gettsim\lib\site-packages\conda_package_handling\api.py", line 82, in create
    out = SUPPORTED_EXTENSIONS[ext].create(prefix, file_list, out_fn, out_folder, **kw)
  File "C:\.conda\envs\gettsim\lib\site-packages\conda_package_handling\tarball.py", line 160, in create
    out_file = create_compressed_tarball(prefix, file_list, out_folder,
  File "C:\.conda\envs\gettsim\lib\site-packages\conda_package_handling\tarball.py", line 88, in create_compressed_tarball
    _create_libarchive(fullpath, files, compression_filter, filter_opts)
  File "C:\.conda\envs\gettsim\lib\site-packages\conda_package_handling\tarball.py", line 74, in _create_libarchive
    archive_utils.create_archive(fullpath, files, compression_filter, filter_opts)
  File "C:\.conda\envs\gettsim\lib\site-packages\conda_package_handling\archive_utils.py", line 29, in create_archive
    raise ArchiveCreationError(message)
conda_package_handling.exceptions.ArchiveCreationError: : Couldn't visit directory while writing file: site-packages\gettsim\transfers\benefit_checks\vermögens_checks.py
```
</details>

- The package that is built under Linux and uploaded to `conda-forge` cannot be installed on Windows machines:

<details>

```
Preparing transaction: done
Verifying transaction: failed

SafetyError: The package for numpy_groupies located at C:\Users\Christian Zimpelmann\.conda\pkgs\numpy_groupies-0.9.14-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/numpy_groupies/aggregate_numpy.py'
has an incorrect size.
  reported size: 11842 bytes
  actual size: 11737 bytes

CondaVerificationError: The package for gettsim located at C:\Users\Christian Zimpelmann\.conda\pkgs\gettsim-0.5.0-py_0
appears to be corrupted. The path 'site-packages/gettsim/parameters/eink_st_abzüge.yaml'
specified in the package manifest cannot be found.

CondaVerificationError: The package for gettsim located at C:\Users\Christian Zimpelmann\.conda\pkgs\gettsim-0.5.0-py_0
appears to be corrupted. The path 'site-packages/gettsim/taxes/zu_verst_eink/freibeträge.py'
specified in the package manifest cannot be found.

CondaVerificationError: The package for gettsim located at C:\Users\Christian Zimpelmann\.conda\pkgs\gettsim-0.5.0-py_0
appears to be corrupted. The path 'site-packages/gettsim/transfers/benefit_checks/vermögens_checks.py'
specified in the package manifest cannot be found.

ClobberError: The package 'conda-forge/win-64::xorg-xproto-7.0.31-hcd874cb_1007' cannot be installed due to a
path collision for 'library/include/x11/deckeysym.h'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.


ClobberError: The package 'conda-forge/win-64::xorg-xproto-7.0.31-hcd874cb_1007' cannot be installed due to a
path collision for 'library/include/x11/hpkeysym.h'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.


ClobberError: The package 'conda-forge/win-64::xorg-xproto-7.0.31-hcd874cb_1007' cannot be installed due to a
path collision for 'library/include/x11/sunkeysym.h'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.


ClobberError: The package 'conda-forge/win-64::xorg-xproto-7.0.31-hcd874cb_1007' cannot be installed due to a
path collision for 'library/include/x11/x.h'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.


ClobberError: The package 'conda-forge/win-64::xorg-xproto-7.0.31-hcd874cb_1007' cannot be installed due to a
path collision for 'library/include/x11/xf86keysym.h'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.


ClobberError: The package 'conda-forge/win-64::xorg-xproto-7.0.31-hcd874cb_1007' cannot be installed due to a
path collision for 'library/include/x11/xatom.h'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.


ClobberError: The package 'conda-forge/win-64::xorg-xproto-7.0.31-hcd874cb_1007' cannot be installed due to a
path collision for 'library/include/x11/xfuncproto.h'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.


ClobberError: The package 'conda-forge/win-64::xorg-xproto-7.0.31-hcd874cb_1007' cannot be installed due to a
path collision for 'library/include/x11/ap_keysym.h'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.


ClobberError: The package 'conda-forge/win-64::xorg-xproto-7.0.31-hcd874cb_1007' cannot be installed due to a
path collision for 'library/include/x11/keysym.h'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.


ClobberError: The package 'conda-forge/win-64::xorg-xproto-7.0.31-hcd874cb_1007' cannot be installed due to a
path collision for 'library/include/x11/keysymdef.h'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.


ClobberError: The package 'conda-forge/win-64::xorg-libx11-1.7.2-hcd874cb_0' cannot be installed due to a
path collision for 'library/include/x11/xlib.h'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.


ClobberError: The package 'conda-forge/win-64::xorg-libx11-1.7.2-hcd874cb_0' cannot be installed due to a
path collision for 'library/include/x11/xutil.h'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.


ClobberError: The package 'conda-forge/win-64::xorg-libx11-1.7.2-hcd874cb_0' cannot be installed due to a
path collision for 'library/include/x11/cursorfont.h'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.
```
</details>

### Expected Behavior

`conda build .` doesn't produce an error and the uploaded package can be installed.
### Steps to Reproduce

- Create package with non-ascii characters in file names (let me know if I should put together an example)
- `conda build .`

##### `Output of conda info`
```
     active environment : gettsim
    active env location : C:\.conda\envs\gettsim
            shell level : 2
       user config file : C:\Users\Christian Zimpelmann\.condarc
 populated config files : C:\Users\Christian Zimpelmann\.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.9.final.0
       virtual packages : __cuda=11.4=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\ProgramData\Miniconda3  (writable)
      conda av data dir : C:\ProgramData\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\Christian Zimpelmann\.conda\pkgs
                          C:\Users\Christian Zimpelmann\AppData\Local\conda\conda\pkgs
       envs directories : C:\.conda\envs
                          C:\ProgramData\Miniconda3\envs
                          C:\Users\Christian Zimpelmann\.conda\envs
                          C:\Users\Christian Zimpelmann\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.9 Windows/10 Windows/10.0.19044
          administrator : True
             netrc file : None
           offline mode : False
```

**Comment by travishathaway** [comment]
I was able to reproduce this bug. Here's the recipe I used:

[issue-4437-conda-recipe.zip](https://github.com/conda/conda-build/files/8531525/issue-4437-conda-recipe.zip)
