### ISSUE TITLE
"GIT_ASKPASS" breaks expansion of cbc-supplied variables in source URLs.

### ISSUE THREAD

**Issue by chenghlee** [conda/conda-build#4454]
### Actual Behavior

If the string literal "GIT_ASKPASS" appears anywhere in a recipe, conda build fails to expand variables in `source/url` elements, when values for those variables are supplied via `conda_build_config.yaml`.

### Steps to Reproduce

Recipe `meta.yaml`:
```
{% set version = "4.1" %}

package:
  name: mypkg
  version: "{{ version }}"

source:
  url: {{ my_mirror }}/src/mypkg_{{ version }}.tar.gz

# Totally innocuous GIT_ASKPASS in a comment
```

Recipe `conda_build_config.yaml`:
```
my_mirror: http://localhost
```

`conda render`-ing the above recipe results in:
```
WARNING:conda_build.source:No hash (md5, sha1, sha256) provided for mypkg_4.1.tar.gz.  Source download forced.  Add hash to recipe to use source cache.
Error: HTTP 404 CONNECTION FAILED for url <file:///src/mypkg_4.1.tar.gz>
Elapsed: 00:00.000397

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
WARNING:conda_build.source:Error: HTTP 404 CONNECTION FAILED for url <file:///src/mypkg_4.1.tar.gz>
Elapsed: 00:00.000397

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Traceback (most recent call last):
  File "${CONDA_PREFIX}/bin/conda-render", line 11, in <module>
    sys.exit(main())
  File "${CONDA_PREFIX}/lib/python3.8/site-packages/conda_build/cli/main_render.py", line 229, in main
    return execute(sys.argv[1:])
  File "${CONDA_PREFIX}/lib/python3.8/site-packages/conda_build/cli/main_render.py", line 197, in execute
    metadata_tuples = api.render(args.recipe, config=config,
  File "${CONDA_PREFIX}/lib/python3.8/site-packages/conda_build/api.py", line 42, in render
    metadata_tuples = render_recipe(recipe_path, bypass_env_check=bypass_env_check,
  File "${CONDA_PREFIX}/lib/python3.8/site-packages/conda_build/render.py", line 845, in render_recipe
    try_download(m, no_download_source=no_download_source)
  File "${CONDA_PREFIX}/lib/python3.8/site-packages/conda_build/render.py", line 649, in try_download
    source.provide(metadata)
  File "${CONDA_PREFIX}/lib/python3.8/site-packages/conda_build/source.py", line 859, in provide
    unpack(source_dict, src_dir, metadata.config.src_cache, recipe_path=metadata.path,
  File "${CONDA_PREFIX}/lib/python3.8/site-packages/conda_build/source.py", line 139, in unpack
    src_path, unhashed_fn = download_to_cache(cache_folder, recipe_path, source_dict, verbose)
  File "${CONDA_PREFIX}/lib/python3.8/site-packages/conda_build/source.py", line 95, in download_to_cache
    raise RuntimeError("Could not download %s" % url)
RuntimeError: Could not download file:///src/mypkg_4.1.tar.gz
```

The `source_url` being rendered as `/src/mypkg_4.1.tar.gz` indicates that the `my_mirror` variable is either being ignored or set to an empty string, even though a value has been provided in conda_build_config.yaml.

Note that removing the literal "GIT_ASKPASS" from recipe comment, and `conda render`-ing produces the expected output:
```
--------------
Hash contents:
--------------
{'my_mirror': 'http://localhost', 'target_platform': 'osx-64'}
----------
meta.yaml:
----------
package:
  name: mypkg
  version: '4.1'
source:
  url: http://localhost/src/mypkg_4.1.tar.gz
build: {}
requirements:
  build: []
  run: []
about: {}
extra:
  copy_test_source_files: true
  final: true
```

### Output of `conda info`

```
     active environment : base
    active env location : ${HOME}/Applications/miniconda3
            shell level : 1
       user config file : ${HOME}/.condarc
 populated config files : ${HOME}/.condarc
          conda version : 4.12.0
    conda-build version : 3.21.8
         python version : 3.8.12.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=skylake
       base environment : ${HOME}/Applications/miniconda3  (writable)
      conda av data dir : ${HOME}/Applications/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : ${HOME}/tmp/pkgs
       envs directories : ${HOME}/Applications/miniconda3/envs
                          ${HOME}/.conda/envs
               platform : osx-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.8.12 Darwin/20.6.0 OSX/10.16
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

**Comment by chenghlee** [comment]
The issue is in the [`Metadata.uses_vcs_in_meta` property](https://github.com/conda/conda-build/blob/1295594/conda_build/metadata.py#L1673-L1691). This property's current implementation leads `conda-build` to conclude that if the pattern `(GIT|SVN|HG)_[^\.\s\'\"]+` occurs _anywhere_ in `meta.yaml` (regardless of context), the package's source must be in some VCS repository. This:

* Leads to the [`Metadata.needs_source_for_render` property](https://github.com/conda/conda-build/blob/1295594/conda_build/metadata.py#L1660-L1662) returning `True`; which
* Leads to an [attempt to download the source](https://github.com/conda/conda-build/blob/1295594/conda_build/render.py#L844-L845); which
* Leads to this failure because the [substitution of CBC-supplied variables](https://github.com/conda/conda-build/blob/1295594/conda_build/render.py#L855-L862) (i.e., "variants") only happens _after_ the source download attempt.

The overly-broad regex means it's not just `GIT_ASKPASS` that can trigger this behavior; something like `GIT_😨`, `HG_😱`, or `SVN_😭` randomly appearing in `meta.yaml` will trigger this behavior.

It's currently not clear how easy this will be to actually fix, as doing so will likely involve changing how `meta.yaml` is parsed, and that always carries the risk of breaking existing recipes; e.g., the fix may break a source specification like:
```
source:
  {{ vcs }}_url: {{ source_url }}
```
where values for `vcs` and `source_url` could be defined in various places (e.g., inline as Jinja `set` directives or as values in cbc.yaml). That said, there's probably also an argument to be made that we should just flat out disallow such shenanigans in recipes.

**Comment by chenghlee** [comment]
Bumping to keep active. We're running into this bug again.
