### ISSUE TITLE
CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team

### ISSUE THREAD

**Issue by avilondhe** [conda/conda-build#4473]
### Actual Behavior

command:
C:\Users\usr_abc\..\Documents\my_project>conda env list

results:
C:\Users\usr_abc\AppData\Roaming\Python\Python36\site-packages\OpenSSL\crypto.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography import utils, x509
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 111, in _main
    imported = importlib.import_module(module)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_search.py", line 14, in <module>
    from ..api import get_index
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\api.py", line 1, in <module>
    from .core.index import get_index
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 48, in <module>
    from cryptography.hazmat.backends.openssl import backend as openssl_backend
  File "C:\Users\usr_abc\AppData\Roaming\Python\Python36\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Users\usr_abc\AppData\Roaming\Python\Python36\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 132, in <module>
    class Backend:
  File "C:\Users\usr_abc\AppData\Roaming\Python\Python36\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1188, in Backend
    def _handle_key_loading_error(self) -> typing.NoReturn:
AttributeError: module 'typing' has no attribute 'NoReturn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 179, in main
    return conda_exception_handler(_main, *args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 636, in conda_exception_handler
    return handle_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 48, in <module>
    from cryptography.hazmat.backends.openssl import backend as openssl_backend
  File "C:\Users\usr_abc\AppData\Roaming\Python\Python36\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Users\usr_abc\AppData\Roaming\Python\Python36\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 132, in <module>
    class Backend:
  File "C:\Users\usr_abc\AppData\Roaming\Python\Python36\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1188, in Backend
    def _handle_key_loading_error(self) -> typing.NoReturn:
AttributeError: module 'typing' has no attribute 'NoReturn'

### Expected Behavior

list all python environments

##### `Output of conda info`

```

```

**Comment by jezdez** [comment]
I think this is a packaging issues of the cryptography packages, I've opened https://github.com/AnacondaRecipes/cryptography-feedstock/pull/14 to fix this.
