### ISSUE TITLE
Package Install Errors with Conda

### ISSUE THREAD

**Issue by mamidi85** [conda/conda-build#4528]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

We added nexus url channel to the conda config, all of a sudden it stopped working and we are unable to install packages..

(base) n295562@srvsprkivlsu03:~$ conda install  matplotlib
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 704, in fetch_repodata_remote_request
        resp.raise_for_status()
      File "/opt/miniconda3/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://nexus.ocpapps.us.corp/repository/conda-anaconda/noarch/current_repodata.json

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/miniconda3/lib/python3.7/site-packages/requests/models.py", line 971, in json
        return complexjson.loads(self.text, **kwargs)
      File "/opt/miniconda3/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
        return _default_decoder.decode(s)
      File "/opt/miniconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
        obj, end = self.raw_decode(s)
      File "/opt/miniconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.errors.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1114, in __call__
        return func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 90, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 263, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 155, in solve_for_transaction
        should_retry_solve)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 196, in solve_for_diff
        force_remove, should_retry_solve)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 300, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 86, in decorated
        return f(*args, **kwds)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 463, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 1059, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 288, in get_reduced_index
        repodata_fn=repodata_fn)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 139, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/opt/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
        yield fs.pop().result()
      File "/opt/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
        return self.__get_result()
      File "/opt/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/opt/miniconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 132, in <lambda>
        package_ref_or_match_spec))
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 144, in query
        self.load()
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 209, in load
        _internal_state = self._load()
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 378, in _load
        repodata_fn=self.repodata_fn)
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 738, in fetch_repodata_remote_request
        response=e.response,
      File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 460, in __init__
        body = response.json()
      File "/opt/miniconda3/lib/python3.7/site-packages/requests/models.py", line 975, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

`$ /opt/miniconda3/bin/conda install matplotlib`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/opt/miniconda3/bin/conda
             CONDA_PREFIX=/opt/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/opt/miniconda3/bin/python
               CONDA_ROOT=/opt/miniconda3
              CONDA_SHLVL=1
             CONDA_SUBDIR=osx-arm64
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=:/opt/cloudera/hiveodbc/lib/64/:/usr/local/lib:/usr/lib/jvm/java-1.8.0
                          -openjdk-1.8.0.322.b06-1.el7_9.x86_64/jre/lib/amd64:/usr/lib/jvm/java-
                          1.8.0-openjdk-1.8.0.322.b06-1.el7_9.x86_64/jre/lib/amd64/server:/usr/l
                          ocal/lib:/opt/cloudera/hiveodbc/lib/64/:/usr/local/lib
                     PATH=/opt/miniconda3/bin:/opt/miniconda3/bin:/opt/miniconda3/condabin:/usr/
                          local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/n295562/bin:/u
                          sr/bin:/bin:/sbin:/usr/sbin:/usr/local/sbin:/opt/sparkbeyond/embedded/
                          lib/R/bin:/usr/local/bin:/opt/miniconda3/bin/conda:/home/n295562/bin:/
                          usr/bin/:/bin:/sbin:/usr/sbin:/usr/local/sbin/:/opt/sparkbeyond/embedd
                          ed/lib/R/bin/:/usr/local/bin
          PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /opt/miniconda3
            shell level : 1
       user config file : /home/n295562/.condarc
 populated config files : /home/n295562/.condarc
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.7.12.final.0
       virtual packages : __osx=7.9=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /opt/miniconda3  (writable)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://nexus.ocpapps.us.corp/repository/conda-anaconda/osx-arm64
                          https://nexus.ocpapps.us.corp/repository/conda-anaconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/n295562/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /home/n295562/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.13.0 requests/2.28.1 CPython/3.7.12 Linux/3.10.0-1160.66.1.el7.x86_64 rhel/7.9 glibc/2.17
                UID:GID : 1297:100
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:
Timeout reached. No report sent.

### Conda Info

```shell
(base) n295562@srvsprkivlsu03:~$ conda info

     active environment : base
    active env location : /opt/miniconda3
            shell level : 1
       user config file : /home/n295562/.condarc
 populated config files : /home/n295562/.condarc
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.7.12.final.0
       virtual packages : __osx=7.9=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /opt/miniconda3  (writable)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://nexus.ocpapps.us.corp/repository/conda-anaconda/osx-arm64
                          https://nexus.ocpapps.us.corp/repository/conda-anaconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/n295562/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /home/n295562/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.13.0 requests/2.28.1 CPython/3.7.12 Linux/3.10.0-1160.66.1.el7.x86_64 rhel/7.9 glibc/2.17
                UID:GID : 1297:100
             netrc file : None
           offline mode : False

(base) n295562@srvsprkivlsu03:~$
```

### Conda Config

```shell
(base) n295562@srvsprkivlsu03:~$ conda config --show-sources
==> /home/n295562/.condarc <==
ssl_verify: False
channels:
  - https://nexus.ocpapps.us.corp/repository/conda-anaconda/
  - defaults

==> envvars <==
subdir: osx-arm64
```

### Conda list

```shell
(base) n295562@srvsprkivlsu03:~$ conda list --show-channel-urls
# packages in environment at /opt/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    https://nexus.ocpapps.us.corp/repository/conda-forge
_openmp_mutex             4.5                       2_gnu    https://nexus.ocpapps.us.corp/repository/conda-forge
anyio                     3.5.0                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
attrs                     21.4.0             pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    https://nexus.ocpapps.us.corp/repository/conda-forge
backports                 1.0                        py_2    https://nexus.ocpapps.us.corp/repository/conda-forge
backports-zoneinfo        0.2.1                    pypi_0    pypi
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
beautifulsoup4            4.11.1                   pypi_0    pypi
bert-tensorflow           1.0.1              pyh9f0ad1d_0    <unknown>
bleach                    5.0.0                    pypi_0    pypi
brotlipy                  0.7.0           py37h540881e_1004    https://nexus.ocpapps.us.corp/repository/conda-forge
ca-certificates           2022.6.15            ha878542_0    https://nexus.ocpapps.us.corp/repository/conda-forge
certifi                   2022.6.15        py37h89c1867_0    https://nexus.ocpapps.us.corp/repository/conda-forge
cffi                      1.15.1           py37h43b0acd_0    https://nexus.ocpapps.us.corp/repository/conda-forge
charset-normalizer        2.1.0              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
click                     8.1.3            py37h89c1867_0    https://nexus.ocpapps.us.corp/repository/conda-forge
cloudpickle               2.1.0              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
conda                     4.13.0           py37h89c1867_1    https://nexus.ocpapps.us.corp/repository/conda-forge
conda-package-handling    1.8.1            py37h540881e_1    https://nexus.ocpapps.us.corp/repository/conda-forge
cryptography              36.0.0           py37h9ce1e76_0    defaults
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.6.0            py37hd23a5d3_0    https://nexus.ocpapps.us.corp/repository/conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
defusedxml                0.7.1                    pypi_0    pypi
distlib                   0.3.4              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
entrypoints               0.4                pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
fastjsonschema            2.15.3                   pypi_0    pypi
filelock                  3.7.1              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
fonttools                 4.33.0                   pypi_0    pypi
future                    0.18.2           py37h89c1867_5    https://nexus.ocpapps.us.corp/repository/conda-forge
genson                    1.2.2              pyh9f0ad1d_0    https://nexus.ocpapps.us.corp/repository/conda-forge
greenlet                  1.1.2                    pypi_0    pypi
idna                      3.3                pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
importlib-metadata        4.11.4           py37h89c1867_0    https://nexus.ocpapps.us.corp/repository/conda-forge
importlib-resources       5.7.1                    pypi_0    pypi
importlib_resources       5.8.0              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
ipykernel                 6.13.0                   pypi_0    pypi
ipython                   7.32.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.7.0                    pypi_0    pypi
jedi                      0.18.1           py37h89c1867_1    https://nexus.ocpapps.us.corp/repository/conda-forge
jinja2                    3.1.1                    pypi_0    pypi
joblib                    1.1.0              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
json5                     0.9.6                    pypi_0    pypi
jsonschema                4.6.1              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            7.2.2                    pypi_0    pypi
jupyter-console           6.4.3                    pypi_0    pypi
jupyter-server            1.16.0                   pypi_0    pypi
jupyter_client            7.3.4              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
jupyter_core              4.10.0           py37h89c1867_0    https://nexus.ocpapps.us.corp/repository/conda-forge
jupyterlab                3.3.4                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.12.0                   pypi_0    pypi
jupyterlab-widgets        1.1.0                    pypi_0    pypi
jupyterthemes             0.20.0                   pypi_0    pypi
keras                     2.6.0              pyhd3eb1b0_0    https://nexus.ocpapps.us.corp/repository/conda-anaconda
kiwisolver                1.4.2                    pypi_0    pypi
ld_impl_linux-64          2.36.1               hea4e1c9_2    https://nexus.ocpapps.us.corp/repository/conda-forge
lesscpy                   0.15.0                   pypi_0    pypi
libblas                   3.9.0           15_linux64_openblas    https://nexus.ocpapps.us.corp/repository/conda-forge
libcblas                  3.9.0           15_linux64_openblas    https://nexus.ocpapps.us.corp/repository/conda-forge
libffi                    3.4.2                h7f98852_5    https://nexus.ocpapps.us.corp/repository/conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    https://nexus.ocpapps.us.corp/repository/conda-forge
libgfortran-ng            12.1.0              h69a702a_16    https://nexus.ocpapps.us.corp/repository/conda-forge
libgfortran5              12.1.0              hdcd56e2_16    https://nexus.ocpapps.us.corp/repository/conda-forge
libgomp                   12.1.0              h8d9b700_16    https://nexus.ocpapps.us.corp/repository/conda-forge
liblapack                 3.9.0           15_linux64_openblas    https://nexus.ocpapps.us.corp/repository/conda-forge
libnsl                    2.0.0                h7f98852_0    https://nexus.ocpapps.us.corp/repository/conda-forge
libopenblas               0.3.20          pthreads_h78a6416_0    https://nexus.ocpapps.us.corp/repository/conda-forge
libsodium                 1.0.18               h36c2ea0_1    https://nexus.ocpapps.us.corp/repository/conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    https://nexus.ocpapps.us.corp/repository/conda-forge
libzlib                   1.2.12               h166bdaf_1    https://nexus.ocpapps.us.corp/repository/conda-forge
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.1                    pypi_0    pypi
matplotlib-inline         0.1.3              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
mistune                   0.8.4                    pypi_0    pypi
nbclassic                 0.3.7                    pypi_0    pypi
nbclient                  0.6.0                    pypi_0    pypi
nbconvert                 6.5.0                    pypi_0    pypi
nbformat                  5.3.0                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    https://nexus.ocpapps.us.corp/repository/conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
nltk                      3.7                pyhd3eb1b0_0    https://nexus.ocpapps.us.corp/repository/conda-anaconda
notebook                  6.4.10                   pypi_0    pypi
notebook-shim             0.1.0                    pypi_0    pypi
numpy                     1.21.6           py37h976b520_0    https://nexus.ocpapps.us.corp/repository/conda-forge
openssl                   3.0.4                h166bdaf_2    https://nexus.ocpapps.us.corp/repository/conda-forge
packaging                 21.3               pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
pandas                    1.3.1            py37h219a48f_0    https://nexus.ocpapps.us.corp/repository/conda-forge
pandocfilters             1.5.0                    pypi_0    pypi
parsedatetime             2.6                pyh9f0ad1d_0    https://nexus.ocpapps.us.corp/repository/conda-forge
parso                     0.8.3              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    https://nexus.ocpapps.us.corp/repository/conda-forge
pickleshare               0.7.5                   py_1003    https://nexus.ocpapps.us.corp/repository/conda-forge
pillow                    9.1.0                    pypi_0    pypi
pip                       22.1.2             pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
platformdirs              2.5.1              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
plotly                    5.9.0                    pypi_0    pypi
ply                       3.11                     pypi_0    pypi
prometheus-client         0.14.1                   pypi_0    pypi
prompt-toolkit            3.0.29                   pypi_0    pypi
psutil                    5.9.0                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3deb0d_0    https://nexus.ocpapps.us.corp/repository/conda-forge
pycosat                   0.6.3           py37h540881e_1010    https://nexus.ocpapps.us.corp/repository/conda-forge
pycparser                 2.21               pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
pygments                  2.11.2                   pypi_0    pypi
pyodbc                    4.0.32                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
pyparsing                 3.0.8                    pypi_0    pypi
pyrsistent                0.18.1           py37h540881e_1    https://nexus.ocpapps.us.corp/repository/conda-forge
pysocks                   1.7.1            py37h89c1867_5    https://nexus.ocpapps.us.corp/repository/conda-forge
python                    3.7.12          hf930737_100_cpython    https://nexus.ocpapps.us.corp/repository/conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
python_abi                3.7                     2_cp37m    https://nexus.ocpapps.us.corp/repository/conda-forge
pytz                      2022.1             pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
pyzmq                     22.3.0                   pypi_0    pypi
qtconsole                 5.3.0                    pypi_0    pypi
qtpy                      2.0.1                    pypi_0    pypi
readline                  8.1.2                h0f457ee_0    https://nexus.ocpapps.us.corp/repository/conda-forge
regex                     2021.8.3         py37h5e8e339_0    https://nexus.ocpapps.us.corp/repository/conda-forge
requests                  2.28.1             pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
ruamel_yaml               0.15.80         py37h540881e_1007    https://nexus.ocpapps.us.corp/repository/conda-forge
scikit-learn              1.0.2            py37h51133e4_1    https://nexus.ocpapps.us.corp/repository/conda-anaconda
scipy                     1.7.3            py37hf2a6cf1_0    https://nexus.ocpapps.us.corp/repository/conda-forge
send2trash                1.8.0                    pypi_0    pypi
setuptools                59.8.0           py37h89c1867_1    https://nexus.ocpapps.us.corp/repository/conda-forge
simplejson                3.17.6           py37h540881e_1    https://nexus.ocpapps.us.corp/repository/conda-forge
six                       1.16.0             pyh6c4a22f_0    https://nexus.ocpapps.us.corp/repository/conda-forge
sniffio                   1.2.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlalchemy                1.4.39                   pypi_0    pypi
sqlite                    3.39.0               h4ff8645_0    https://nexus.ocpapps.us.corp/repository/conda-forge
tabpy-client              0.2              py37h06a4308_1    https://nexus.ocpapps.us.corp/repository/conda-anaconda
tabpy-server              0.2              py37h06a4308_1    https://nexus.ocpapps.us.corp/repository/conda-anaconda
tenacity                  8.0.1                    pypi_0    pypi
terminado                 0.13.3                   pypi_0    pypi
threadpoolctl             3.1.0              pyh8a188c0_0    https://nexus.ocpapps.us.corp/repository/conda-forge
time                      1.8                  h516909a_0    https://nexus.ocpapps.us.corp/repository/conda-forge
tinycss2                  1.1.1                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    https://nexus.ocpapps.us.corp/repository/conda-forge
tornado                   6.2              py37h540881e_0    https://nexus.ocpapps.us.corp/repository/conda-forge
tornado-json              1.3.3                    py37_0    https://nexus.ocpapps.us.corp/repository/conda-anaconda
tqdm                      4.64.0             pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
traitlets                 5.1.1                    pypi_0    pypi
typing-extensions         4.2.0                    pypi_0    pypi
typing_extensions         4.3.0              pyha770c72_0    https://nexus.ocpapps.us.corp/repository/conda-forge
tzdata                    2022.1                   pypi_0    pypi
urllib3                   1.26.9             pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
virtualenv                20.15.0          py37h89c1867_0    https://nexus.ocpapps.us.corp/repository/conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    https://nexus.ocpapps.us.corp/repository/conda-forge
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.3.2                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
widgetsnbextension        3.6.0                    pypi_0    pypi
xz                        5.2.5                h516909a_1    https://nexus.ocpapps.us.corp/repository/conda-forge
yaml                      0.2.5                h7f98852_2    https://nexus.ocpapps.us.corp/repository/conda-forge
yellowbrick               1.4                      pypi_0    pypi
zeromq                    4.3.4                h9c3ff4c_1    https://nexus.ocpapps.us.corp/repository/conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    https://nexus.ocpapps.us.corp/repository/conda-forge
zlib                      1.2.12               h166bdaf_1    https://nexus.ocpapps.us.corp/repository/conda-forge
(base) n295562@srvsprkivlsu03:~$
```

**Comment by ChunjieShawn** [comment]
I met a similar problem when conda building a package, and it's due to the conflict between simplejson=3.17.6 vs built-in json=2.0.9.
The requests module returned a simplejson.errors.JSONDecodeError where conda-build temped to catch json.decoder.JSONDecodeError. I'd be glad to hear any updates on issue, thank you!
