### ISSUE TITLE
Using R Kernel in Ipython

### ISSUE THREAD

**Issue by tvmanikandan** [conda/conda-build#461]
Hello,
I am trying to use R Kernel in IPython. I am using Windows 8.1 and Anaconda distribution of python.
I am getting the below error. Please help.

Traceback (most recent call last):
  File "C:\Users\bumani\Anaconda\lib\site-packages\IPython\html\base\handlers.py", line 365, in wrapper
    result = yield gen.maybe_future(method(self, _args, *_kwargs))
  File "C:\Users\bumani\Anaconda\lib\site-packages\IPython\html\services\sessions\handlers.py", line 53, in post
    model = sm.create_session(path=path, kernel_name=kernel_name)
  File "C:\Users\bumani\Anaconda\lib\site-packages\IPython\html\services\sessions\sessionmanager.py", line 66, in create_session
    kernel_name=kernel_name)
  File "C:\Users\bumani\Anaconda\lib\site-packages\IPython\html\services\kernels\kernelmanager.py", line 84, in start_kernel
    kernel_name=kernel_name, **kwargs)
  File "C:\Users\bumani\Anaconda\lib\site-packages\IPython\kernel\multikernelmanager.py", line 112, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\bumani\Anaconda\lib\site-packages\IPython\kernel\manager.py", line 240, in start_kernel
    *_kw)
  File "C:\Users\bumani\Anaconda\lib\site-packages\IPython\kernel\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, *_kw)
  File "C:\Users\bumani\Anaconda\lib\site-packages\IPython\kernel\launcher.py", line 202, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\bumani\Anaconda\lib\subprocess.py", line 710, in **init**
    errread, errwrite)
  File "C:\Users\bumani\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by asmeurer** [comment]
How did you install R and the R kernel?

**Comment by tvmanikandan** [comment]
Aaron,
Thanks for your mail.
I updated R to latest version from R Console.
Also installed R kernel in R Console.

-Mani

**Comment by tvmanikandan** [comment]
Aaron ,
Please let me know whether you are able to reproduce the issue at your end.

-Mani

**Comment by asmeurer** [comment]
I've only tested using the R installed from conda (`conda install -c r-irkernel`).
