### ISSUE TITLE
Error building skeleton file for mygene package in pypi repository

### ISSUE THREAD

**Issue by zenesh** [conda/conda-build#463]
Hi All,

Had an error when trying to build skeleton for mygene 2.2.0 package in pypi. Not very sure if it is similar to #119 

Any ideas to get it working?

Unpacking mygene...
done
working in C:\Users\ngjs\AppData\Local\Temp\tmpiccqnshnconda_skeleton_mygene-2.2.0.tar
Fetching package metadata: ......
Solving package specifications: .
Applying patch: 'C:\\Users\\ngjs\\AppData\\Local\\Temp\\tmpiccqnshnconda_skeleton_myge
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\ngjs\AppData\Local\Continuum\Anaconda3\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\ngjs\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda_build\main_skeleton.py", line 234, in main
    args_func(args, p)
  File "C:\Users\ngjs\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda_build\main_build.py", line 346, in args_func
    args.func(args, p)
  File "C:\Users\ngjs\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda_build\main_skeleton.py", line 248, in execute
    pypi.main(args, parser)
  File "C:\Users\ngjs\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda_build\pypi.py", line 387, in main
    get_package_metadata(args, package, d, data)
  File "C:\Users\ngjs\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda_build\pypi.py", line 484, in get_package_metadata
    run_setuppy(src_dir, tempdir, args)
  File "C:\Users\ngjs\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda_build\pypi.py", line 750, in run_setuppy
    apply_patch(join(stdlib_dir, 'distutils'), patch)
  File "C:\Users\ngjs\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda_build\source.py", line 233, in apply_patch
    check_call([patch, '-p0', '-i', path], cwd=src_dir)
  File "C:\Users\ngjs\AppData\Local\Continuum\Anaconda3\lib\subprocess.py", line 556, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\ngjs\AppData\Local\Continuum\Anaconda3\lib\subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\ngjs\AppData\Local\Continuum\Anaconda3\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Users\ngjs\AppData\Local\Continuum\Anaconda3\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
OSError: [WinError 740] The requested operation requires elevation

Conda info
Current conda install:

             platform : win-64
        conda version : 3.14.0
  conda-build version : 1.14.0
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : C:\Users\ngjs\AppData\Local\Continuum\Anaconda3  (writable)
  default environment : C:\Users\ngjs\AppData\Local\Continuum\Anaconda3
     envs directories : C:\Users\ngjs\AppData\Local\Continuum\Anaconda3\envs
        package cache : C:\Users\ngjs\AppData\Local\Continuum\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by yoavram** [comment]
I got the same error. I opened a new terminal as administrator, ran it again, and the error went away.

**Comment by msarahan** [comment]
I believe these issues are fixed with the patch package, version 2.5.9, build 1. This bundles the GnuWin32 patch executable with a manifest that tells Windows to not require elevation when running patch.exe.

build 0 did not include the manifest, and Windows has some file name heuristic that ends up making patch.exe require elevation if no manifest explicitly says to not require it.

Closing this issue.  Please reopen or post a new issue if you still have problems.

**Comment by yoavram** [comment]
:+1:
