### ISSUE TITLE
Unsatisfiable dependencies for platform linux-64

### ISSUE THREAD

**Issue by ekushele** [conda/conda-build#4644]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

 Hi,

 have this `meta.yaml`
```
{% set version = "0.6.3" %}
{% set sha256 = "ae0610f93549673b7812dd6470f293d3fdbdd28c5a89e6ed961a574e3a0ab02c" %}

package:
  name: modbam2bed
  version: {{ version }}

source:
  url: https://github.com/epi2me-labs/modbam2bed/archive/refs/tags/v{{ version }}.zip
  sha256: {{ sha256 }}
  # patches:
    # - patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    # - cmake
    - make
    - htslib >=1.16
  run:
    - htslib >=1.16

test:
  commands:
    - modbam2bed

about:
  home: https://github.com/epi2me-labs/modbam2bed
  license: MPL-2.0 license
  license_file: LICENSE
  summary: 'A program to aggregate modified base counts stored in a modified-base BAM (Section 2.1) file to a bedMethyl file'

```

I run `conda build .`
And got:

```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for modbam2bed
INFO:conda_build.metadata:Attempting to finalize metadata for modbam2bed
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

Leaving build/test directories:
  Work:
 /sci/ekushele/icore-home/miniconda3_hurcs/conda-bld/work
  Test:
 /sci/ekushele/icore-home/miniconda3_hurcs/conda-bld/test_tmp
Leaving build/test environments:
  Test:
source activate  /sci/ekushele/icore-home/miniconda3_hurcs/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol
  Build:
source activate  /sci/ekushele/icore-home/miniconda3_hurcs/conda-bld/_build_env


Traceback (most recent call last):
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda_build/environ.py", line 797, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda/common/io.py", line 86, in decorated
    return f(*args, **kwds)
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda/plan.py", line 476, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda/core/solve.py", line 159, in solve_for_transaction
    should_retry_solve)
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda/core/solve.py", line 200, in solve_for_diff
    force_remove, should_retry_solve)
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda/core/solve.py", line 317, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda/core/solve.py", line 607, in _add_specs
    explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda/resolve.py", line 556, in _get_package_pool
    pool = self.get_reduced_index(specs)
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda/common/io.py", line 86, in decorated
    return f(*args, **kwds)
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda/resolve.py", line 577, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda/resolve.py", line 289, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound:
  - htslib[version='>=1.16']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sci/ekushele/icore-home/miniconda3_hurcs/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 494, in main
    execute(sys.argv[1:])
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 484, in execute
    cache_dir=args.cache_dir,
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda_build/api.py", line 189, in build
    variants=variants
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda_build/build.py", line 3099, in build_tree
    notest=notest,
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda_build/build.py", line 2049, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda_build/render.py", line 780, in expand_outputs
    for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda_build/metadata.py", line 2527, in get_output_metadata_set
    bypass_env_check=bypass_env_check,
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda_build/metadata.py", line 887, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants,
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda_build/render.py", line 542, in finalize_metadata
    exclude_pattern)
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda_build/render.py", line 381, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda_build/render.py", line 369, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda_build/render.py", line 142, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/sci/ekushele/icore-home/miniconda3_hurcs/lib/python3.7/site-packages/conda_build/environ.py", line 799, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"htslib[version='>=1.16']"}
```

When I didn't specify any version for htslib, it worked and downloaded htslib in an old version, can't figure out what exactly.

### Conda Info

```shell
active environment : None
            shell level : 0
       user config file : /sci/home/ekushele/.condarc
 populated config files : /sci/home/ekushele/.condarc
          conda version : 22.9.0
    conda-build version : 3.23.1
         python version : 3.7.10.final.0
       virtual packages : __linux=5.10.104=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /sci/ekushele/icore-home/miniconda3_hurcs  (writable)
      conda av data dir : /sci/ekushele/icore-home/miniconda3_hurcs/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /sci/ekushele/icore-home/miniconda3_hurcs/pkgs
                          /sci/home/ekushele/.conda/pkgs
       envs directories : /sci/ekushele/icore-home/miniconda3_hurcs/envs
                          /sci/home/ekushele/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.26.0 CPython/3.7.10 Linux/5.10.104-aufs-3 debian/10 glibc/2.28
                UID:GID : 205349:921
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /sci/home/ekushele/.condarc <==
auto_activate_base: False
```

### Conda list

```shell
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             4.5                       1_gnu    defaults
beautifulsoup4            4.11.1           py37h06a4308_0    defaults
brotlipy                  0.7.0           py37h27cfd23_1003    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2022.10.11           h06a4308_0    defaults
certifi                   2022.9.24        py37h06a4308_0    defaults
cffi                      1.14.6           py37h400218f_0    defaults
chardet                   4.0.0           py37h06a4308_1003    defaults
conda                     22.9.0           py37h06a4308_0    defaults
conda-build               3.23.1           py37h06a4308_0    defaults
conda-package-handling    1.7.3            py37h27cfd23_1    defaults
cryptography              3.4.7            py37hd23ed53_0    defaults
filelock                  3.6.0              pyhd3eb1b0_0    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      2.10               pyhd3eb1b0_0    defaults
jinja2                    2.10.1                   py37_0    defaults
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libarchive                3.6.1                hab531cd_0    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
liblief                   0.11.5               h295c915_1    defaults
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
libxml2                   2.9.14               h74e7548_0    defaults
lz4-c                     1.9.3                h295c915_1    defaults
markupsafe                2.0.1            py37h27cfd23_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
openssl                   1.1.1s               h7f8727e_0    defaults
patch                     2.7.6             h7b6447c_1001    defaults
patchelf                  0.13                 h295c915_0    defaults
pip                       21.1.3           py37h06a4308_0    defaults
pkginfo                   1.8.3            py37h06a4308_0    defaults
psutil                    5.9.0            py37h5eee18b_0    defaults
py-lief                   0.11.5           py37h295c915_1    defaults
pycosat                   0.6.3            py37h27cfd23_0    defaults
pycparser                 2.20                       py_2    defaults
pyopenssl                 20.0.1             pyhd3eb1b0_1    defaults
pysocks                   1.7.1                    py37_1    defaults
python                    3.7.10               h12debd9_4    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
pytz                      2022.1           py37h06a4308_0    defaults
pyyaml                    6.0              py37h7f8727e_1    defaults
readline                  8.1                  h27cfd23_0    defaults
requests                  2.25.1             pyhd3eb1b0_0    defaults
ripgrep                   13.0.0               hbdeaff8_0    defaults
ruamel_yaml               0.15.100         py37h27cfd23_0    defaults
setuptools                52.0.0           py37h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
soupsieve                 2.3.2.post1      py37h06a4308_0    defaults
sqlite                    3.36.0               hc218d9a_0    defaults
tk                        8.6.10               hbc83047_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
toolz                     0.12.0           py37h06a4308_0    defaults
tqdm                      4.61.2             pyhd3eb1b0_1    defaults
urllib3                   1.26.6             pyhd3eb1b0_1    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstd                      1.5.2                ha4553b6_0    defaults
```

**Comment by ekushele** [comment]
solved with adding     - libdeflate >=1.13 to prevent conflicts, and `conda build . -c bioconda -c conda-forge` while building
