### ISSUE TITLE
FileExistsError with package with egg

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#472]
```
Finished processing dependencies for sphinx-rtd-theme==0.1.8
found egg dir: /Users/aaronmeurer/anaconda/envs/_build/lib/python3.4/site-packages/sphinx_rtd_theme-0.1.8-py3.4.egg
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/bin/conda-build", line 7, in <module>


    sys.exit(main())
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/main_build.py", line 130, in main
    args_func(args, p)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/main_build.py", line 350, in args_func
    args.func(args, p)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/main_build.py", line 309, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/build.py", line 400, in build
    post_process(sorted(files2 - files1), preserve_egg_dir=bool(m.get_value('build/preserve_egg_dir')))
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/post.py", line 147, in post_process
    remove_easy_install_pth(files, preserve_egg_dir=preserve_egg_dir)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/post.py", line 104, in remove_easy_install_pth
    utils.copy_into(join(egg_path, fn), join(sp_dir, fn))
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/utils.py", line 34, in copy_into
    shutil.copytree(srcname, dstname)
  File "/Users/aaronmeurer/anaconda/lib/python3.4/shutil.py", line 303, in copytree
    os.makedirs(dst)
  File "/Users/aaronmeurer/anaconda/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/Users/aaronmeurer/anaconda/envs/_build/lib/python3.4/site-packages/sphinx_rtd_theme/__pycache__'
```

This is with sphinx_rtd_theme without the preserve_egg_dir setting.

**Comment by asmeurer** [comment]
I think this is a consequence of https://github.com/conda/conda-build/pull/473. It needs a better error message, though.
