### ISSUE TITLE
error about conda skeleton pypi rpy2     

### ISSUE THREAD

**Issue by austincy** [conda/conda-build#476]
Warning, the following versions were found for rpy2
2.6.0
2.5.6
2.5.5
2.5.4
2.5.3
2.5.2
2.5.1
2.5.0
2.4.4
2.4.3
2.4.2
2.4.1
2.4.0
2.3.10
2.3.9
2.3.8
2.3.7
2.3.6
2.3.5
2.3.4
2.3.3
2.3.2
2.3.1
2.3.0
2.3.0beta1
2.3.0alpha1
2.2.7
2.2.6
2.2.5
2.2.4
2.2.3
2.2.2
2.2.1
2.2.0
2.1.9
2.1.8
2.1.7
2.1.6
2.1.5
2.1.4
2.1.3
2.1.2
2.1.1
2.1.0
2.0.8
Using 2.6.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/r/rpy2/rpy2-2.6.0.tar.gz (167 KB) for rpy2.
Downloading rpy2
Using cached download
Unpacking rpy2...
done
working in C:\Users\ADMINI~1\AppData\Local\Temp\tmpse57uh9vconda_skeleton_rpy2-2.6.0.tar.gz
Fetching package metadata: ......
Solving package specifications: .
Applying patch: 'C:\Users\ADMINI~1\AppData\Local\Temp\tmpse57uh9vconda_skeleton_rpy2-2.6.0.tar.gz\pypi-distutils.patch'
patching file `core.py'
Hunk #1 succeeded at 168 with fuzz 2 (offset 1 line).
patch: **** can't rename`core.py' to `core.py.orig' : File exists
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda-build/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "D:\austin_chenyang\programs\Miniconda3\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "D:\austin_chenyang\programs\Miniconda3\lib\site-packages\conda_build\main_skeleton.py", line 240, in main
    args_func(args, p)
  File "D:\austin_chenyang\programs\Miniconda3\lib\site-packages\conda_build\main_build.py", line 349, in args_func
    args.func(args, p)
  File "D:\austin_chenyang\programs\Miniconda3\lib\site-packages\conda_build\main_skeleton.py", line 254, in execute
    pypi.main(args, parser)
  File "D:\austin_chenyang\programs\Miniconda3\lib\site-packages\conda_build\pypi.py", line 338, in main
    get_package_metadata(args, package, d, data)
  File "D:\austin_chenyang\programs\Miniconda3\lib\site-packages\conda_build\pypi.py", line 475, in get_package_metadata
    python_version=args.python_version)
  File "D:\austin_chenyang\programs\Miniconda3\lib\site-packages\conda_build\pypi.py", line 736, in get_pkginfo
    run_setuppy(src_dir, tempdir, python_version)
  File "D:\austin_chenyang\programs\Miniconda3\lib\site-packages\conda_build\pypi.py", line 783, in run_setuppy
    apply_patch(join(stdlib_dir, 'distutils'), patch)
  File "D:\austin_chenyang\programs\Miniconda3\lib\site-packages\conda_build\source.py", line 235, in apply_patch
    check_call([patch, '-p0', '-i', path], cwd=src_dir)
  File "D:\austin_chenyang\programs\Miniconda3\lib\subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['D:\austin_chenyang\programs\Miniconda3\Scripts\patch.exe', '-p0', '-i', 'C:\Users\ADMINI~1\AppData\Local\Temp\tmpse57uh9vconda_skeleton_rpy2-2.6.0.tar.gz\pypi-dist
utils.patch']' returned non-zero exit status 2
###### 

Current conda install:

```
         platform : win-32
    conda version : 3.14.1
```

  conda-build version : 1.14.1
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : D:\austin_chenyang\programs\Miniconda3  (writable)
  default environment : D:\austin_chenyang\programs\Miniconda3
     envs directories : D:\austin_chenyang\programs\Miniconda3\envs
        package cache : D:\austin_chenyang\programs\Miniconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by Dalar** [comment]
I have the same error when building rpy2 version 2.7.0 on 64-bit Windows 7.
