### ISSUE TITLE
conda-build failed on linux arm64 environment (python=3.8) since Feburary 1st

### ISSUE THREAD

**Issue by nicholasyanghaoran** [conda/conda-build#4777]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I am building conda packages for my project from wheel files, for platforms including linux-arm64, linux-x86, windows, macos-arm64 and macos-x86, for python versions 3.7, 3.8 and 3.9. Everything worked fine until last month, but I was unable to build packages for linux-arm64 python3.8 since beginning of Feburary for unknown reasons. I tried building packages based on previous wheel packages that could successfully build a conda package but still get a failure.

My build.sh:
```
pip install https://ms-release.obs.cn-north-4.myhuaweicloud.com/2.0.0a0/MindSpore/unified/aarch64/mindspore-2.0.0a0-cp38-cp38-linux_aarch64.whl \
   --trusted-host ms-release.obs.cn-north-4.myhuaweicloud.com
```

My meta.yaml:

```yaml
package:
  name: mindspore
  version: "2.0.0a0"

build:
  number: 0
  rpaths:
    - /usr/local/Ascend/latest/lib64


requirements:
  build:
    - python
    - pip
    - setuptools >=40.8.0
    - wheel >=0.32.0
  run:
    - python
    - numpy >=1.17.0
    - protobuf >=3.13.0
    - asttokens >=2.0.4
    - pillow >=6.2.0
    - scipy >=1.5.4
    - decorator >=4.4.0
    - packaging >=20.0
    - psutil >=5.7.0
    - astunparse >=1.6.3

about:
  home: https://www.mindspore.cn/
```

Command I executed:
```
$ source ~/archiconda3/bin/activate py38; conda build --python=3.8 .

And this is the full message I received by running conda-build:
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
Attempting to finalize metadata for mindspore
INFO:conda_build.metadata:Attempting to finalize metadata for mindspore
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['mindspore-2.0.0a0-py38_0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/jenkins/archiconda3/envs/py38/conda-bld/mindspore_1676720951804/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol


The following NEW packages will be INSTALLED:

    _openmp_mutex:   4.5-2_gnu            conda-forge
    bzip2:           1.0.8-hf897c2e_4     conda-forge
    ca-certificates: 2022.12.7-h4fd8a4c_0 conda-forge
    expat:           2.5.0-ha18d298_0     conda-forge
    gdbm:            1.18-h0a1914f_2      conda-forge
    libffi:          3.4.2-h3557bc0_5     conda-forge
    libgcc-ng:       12.2.0-h607ecd0_19   conda-forge
    libgomp:         12.2.0-h607ecd0_19   conda-forge
    libsqlite:       3.40.0-hf9034f9_0    conda-forge
    libstdcxx-ng:    12.2.0-hc13a102_19   conda-forge
    libzlib:         1.2.13-h4e544f5_4    conda-forge
    ncurses:         6.3-headf329_1       conda-forge
    openssl:         3.0.8-hb4cce97_0     conda-forge
    pip:             23.0.1-pyhd8ed1ab_0  conda-forge
    pypy3.8:         7.3.11-hf9a8208_0    conda-forge
    python:          3.8.16-0_73_pypy     conda-forge
    python_abi:      3.8-3_pypy38_pp73    conda-forge
    readline:        8.1.2-h38e3740_0     conda-forge
    setuptools:      67.3.2-pyhd8ed1ab_0  conda-forge
    sqlite:          3.40.0-h69ca7e5_0    conda-forge
    tk:              8.6.12-hd8af866_0    conda-forge
    wheel:           0.38.4-pyhd8ed1ab_0  conda-forge
    xz:              5.2.6-h9cdd2b7_0     conda-forge
    zlib:            1.2.13-h4e544f5_4    conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
source tree in: /home/jenkins/archiconda3/envs/py38/conda-bld/mindspore_1676720951804/work
export PREFIX=/home/jenkins/archiconda3/envs/py38/conda-bld/mindspore_1676720951804/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol
export SRC_DIR=/home/jenkins/archiconda3/envs/py38/conda-bld/mindspore_1676720951804/work
ERROR: mindspore-2.0.0a0-cp38-cp38-linux_aarch64.whl is not a supported wheel on this platform.
Traceback (most recent call last):
  File "/home/jenkins/archiconda3/envs/py38/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 494, in main
    execute(sys.argv[1:])
  File "/home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 474, in execute
    outputs = api.build(
  File "/home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
    return build_tree(
  File "/home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages/conda_build/build.py", line 3093, in build_tree
    packages_from_this = build(metadata, stats,
  File "/home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages/conda_build/build.py", line 2208, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages/conda_build/utils.py", line 402, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages/conda_build/utils.py", line 382, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/jenkins/archiconda3/envs/py38/conda-bld/mindspore_1676720951804/work/conda_build.sh']' returned non-zero exit status 1.

```

### Conda Info

```shell
active environment : py38
    active env location : /home/jenkins/archiconda3/envs/py38
            shell level : 1
       user config file : /home/jenkins/.condarc
 populated config files : /home/jenkins/archiconda3/.condarc
                          /home/jenkins/.condarc
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /home/jenkins/archiconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-aarch64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-aarch64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-aarch64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-aarch64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/c4aarch64/linux-aarch64
                          https://conda.anaconda.org/c4aarch64/noarch
          package cache : /home/jenkins/archiconda3/pkgs
                          /home/jenkins/.conda/pkgs
       envs directories : /home/jenkins/archiconda3/envs
                          /home/jenkins/.conda/envs
               platform : linux-aarch64
             user-agent : conda/4.5.12 requests/2.27.1 CPython/3.7.1 Linux/4.15.0-163-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /home/jenkins/archiconda3/.condarc <==
channels:
  - https://conda.anaconda.org/c4aarch64
  - https://conda.anaconda.org/conda-forge

==> /home/jenkins/.condarc <==
channels:
  - conda-forge
  - defaults
anaconda_upload: True
```

### Conda list

```shell
# packages in environment at /home/jenkins/archiconda3/envs/py38:
#
# Name                    Version                   Build  Channel
_openmp_mutex             4.5                       1_gnu    conda-forge
anaconda-client           1.8.0              pyhd8ed1ab_0    conda-forge
asttokens                 2.2.1                     <pip>
astunparse                1.6.3                     <pip>
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
brotlipy                  0.7.0           py38hdacc76a_1004    conda-forge
bzip2                     1.0.8                hf897c2e_4    conda-forge
ca-certificates           2022.9.24            h4fd8a4c_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.0           py38hc42474b_0    conda-forge
chardet                   4.0.0            py38h2063c64_3    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.1.2            py38he3eb160_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     22.9.0           py38he3eb160_2    conda-forge
conda-build               3.23.0           py38he3eb160_1    conda-forge
conda-package-handling    1.8.1            py38hdacc76a_1    conda-forge
conda-verify              3.1.1           py38h2063c64_1004    conda-forge
cryptography              36.0.0           py38h3d58568_0    defaults
filelock                  3.6.0              pyhd8ed1ab_0    conda-forge
future                    0.18.2           py38h2063c64_5    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       70.1                 ha18d298_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3           py38h2063c64_1    conda-forge
importlib_resources       5.7.1              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.1              pyhd8ed1ab_0    conda-forge
jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.2            py38he3eb160_0    conda-forge
ld_impl_linux-aarch64     2.36.1               h02ad14f_2    conda-forge
libarchive                3.5.2                h3493ebf_1    conda-forge
libffi                    3.4.2                h3557bc0_5    conda-forge
libgcc-ng                 12.2.0              h607ecd0_19    conda-forge
libgomp                   12.2.0              h607ecd0_19    conda-forge
libiconv                  1.16                 h6dd45c4_0    conda-forge
liblief                   0.11.5               h01db608_1    conda-forge
libnsl                    2.0.0                hf897c2e_0    conda-forge
libstdcxx-ng              11.2.0              h0d0a5bb_15    conda-forge
libuuid                   2.32.1            hf897c2e_1000    conda-forge
libxml2                   2.9.13               h370961a_0    conda-forge
libzlib                   1.2.11            h4e544f5_1014    conda-forge
lz4-c                     1.9.3                h01db608_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                2.1.1            py38h81aae68_1    conda-forge
nbformat                  5.3.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  headf329_1    conda-forge
numpy                     1.24.1                    <pip>
openssl                   3.0.7                h4e544f5_0    conda-forge
packaging                 23.0                      <pip>
patch                     2.7.6             hf897c2e_1002    conda-forge
patchelf                  0.14.5               h884eca8_0    conda-forge
Pillow                    9.4.0                     <pip>
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pkginfo                   1.8.2              pyhd8ed1ab_0    conda-forge
protobuf                  4.21.12                   <pip>
psutil                    5.9.0            py38hdacc76a_1    conda-forge
py-lief                   0.11.5           py38h4da49af_1    conda-forge
pycosat                   0.6.3           py38hdacc76a_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1           py38h81aae68_1    conda-forge
pysocks                   1.7.1            py38h2063c64_5    conda-forge
python                    3.8.13          h92ab765_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.15.3             pyhd8ed1ab_0    conda-forge
python-libarchive-c       4.0              py38he3eb160_1    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py38hdacc76a_4    conda-forge
readline                  8.1                  h1a49cc3_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               hc770f70_2    conda-forge
ruamel_yaml               0.15.80         py38h9544abe_1006    conda-forge
scipy                     1.10.0                    <pip>
setuptools                62.1.0           py38h2063c64_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.38.2               hc74f5b8_0    conda-forge
tk                        8.6.12               hd8af866_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h6dd45c4_1    conda-forge
yaml                      0.2.5                hf897c2e_2    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h4e544f5_1014    conda-forge
zstd                      1.5.2                h41fb7a4_0    conda-forge
```

**Comment by nicholasyanghaoran** [comment]
I tried building Linux arm python3.8 packages on 3 different machines using wheel packages built in last year and early this year, but still getting the same error, could someone please help take a look into this?

**Comment by travishathaway** [comment]
HI @nicholasyanghaoran,

Thanks for submitting this bug report. After some initial digging around at this, it's still not immediate clear to me what is going on.

Do you think that this may be a problem with `pip`? It looks like the error is:

```
ERROR: mindspore-2.0.0a0-cp38-cp38-linux_aarch64.whl is not a supported wheel on this platform.
```

I believe this is encountered while running the build script. Perhaps you could try manually running that `pip` command to see if you can recreate that error.

I'll reach out to some others to see if they may have insights.

**Comment by nicholasyanghaoran** [comment]
Hi travis, 
Thank you very much for replying. I have verified installing this package on the same conda environemnt which failed builing conda package and  this is what I get, everything worked fine: (run_check() is a function that verifies whether the package is intalled correctly)
(py38) jenkins@mindspore-jenkins-docker-build-arm:~/yanghaoran$ which python
/home/jenkins/archiconda3/envs/py38/bin/python
(py38) jenkins@mindspore-jenkins-docker-build-arm:~/yanghaoran$ which pip
/home/jenkins/archiconda3/envs/py38/bin/pip
(py38) jenkins@mindspore-jenkins-docker-build-arm:~/yanghaoran$ pip install https://ms-release.obs.cn-north-4.myhuaweicloud.com/2.0.0a0/MindSpore/unified/aarch64/mindspore-2.0.0a0-cp38-cp38-linux_aarch64.whl \
>    --trusted-host ms-release.obs.cn-north-4.myhuaweicloud.com
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting mindspore==2.0.0a0
  Using cached https://ms-release.obs.cn-north-4.myhuaweicloud.com/2.0.0a0/MindSpore/unified/aarch64/mindspore-2.0.0a0-cp38-cp38-linux_aarch64.whl (195.9 MB)
Requirement already satisfied: numpy>=1.17.0 in /home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages (from mindspore==2.0.0a0) (1.24.1)
Requirement already satisfied: protobuf>=3.13.0 in /home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages (from mindspore==2.0.0a0) (4.21.12)
Requirement already satisfied: packaging>=20.0 in /home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages (from mindspore==2.0.0a0) (23.0)
Requirement already satisfied: pillow>=6.2.0 in /home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages (from mindspore==2.0.0a0) (9.4.0)
Requirement already satisfied: psutil>=5.6.1 in /home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages (from mindspore==2.0.0a0) (5.9.0)
Requirement already satisfied: astunparse>=1.6.3 in /home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages (from mindspore==2.0.0a0) (1.6.3)
Requirement already satisfied: asttokens>=2.0.4 in /home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages (from mindspore==2.0.0a0) (2.2.1)
Requirement already satisfied: scipy>=1.5.4 in /home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages (from mindspore==2.0.0a0) (1.10.0)
Requirement already satisfied: six in /home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages (from asttokens>=2.0.4->mindspore==2.0.0a0) (1.16.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages (from astunparse>=1.6.3->mindspore==2.0.0a0) (0.37.1)
Installing collected packages: mindspore
Successfully installed mindspore-2.0.0a0
(py38) jenkins@mindspore-jenkins-docker-build-arm:~/yanghaoran$ python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:56:18) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mindspore
/home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/jenkins/archiconda3/envs/py38/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
>>> mindspore.run_check()
MindSpore version:  2.0.0a0
The result of multiplication calculation is correct, MindSpore has been installed successfully!
>>> quit()

Are there any other details I may have missed out?

**Comment by nicholasyanghaoran** [comment]
hi @travishathaway,
Sorry for interrupting but the problem still exist when I tried building new packages using the same configuration, could you please take a look into this problem?

**Comment by travishathaway** [comment]
Hi @nicholasyanghaoran,

Sorry for the slow reply. We don't officially provide support through this channel, and I personally do not have enough time to debug this further.

You may wish to try our conda build chat room for more help: https://matrix.to/#/#conda_conda-build:gitter.im
