### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by bluecirno** [conda/conda-build#4778]
### Checklist

- [ ] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

```
PS D:\blueproject\NFT\hashlips_art_engine-1.1.2_patch_v6> node index.js
(node:6548) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1390
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'D:\blueproject\NFT\hashlips_art_engine-1.1.2_patch_v6/layers/red/'
    at Object.readdirSync (node:fs:1390:3)
    at getElements (D:\blueproject\NFT\hashlips_art_engine-1.1.2_patch_v6\src\main.js:73:6)
    at D:\blueproject\NFT\hashlips_art_engine-1.1.2_patch_v6\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (D:\blueproject\NFT\hashlips_art_engine-1.1.2_patch_v6\src\main.js:90:30)
    at startCreating (D:\blueproject\NFT\hashlips_art_engine-1.1.2_patch_v6\src\main.js:356:20)
    at D:\blueproject\NFT\hashlips_art_engine-1.1.2_patch_v6\index.js:6:3
    at Object.<anonymous> (D:\blueproject\NFT\hashlips_art_engine-1.1.2_patch_v6\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'D:\\blueproject\\NFT\\hashlips_art_engine-1.1.2_patch_v6/layers/red/'
}
```

what should i do?

**Comment by kenodegard** [comment]
Unfortunately, this is unrelated to the `conda`/`conda-build` projects. Node.js and other JavaScript forums are better suited to help with your question.
