### ISSUE TITLE
conda skeleton completely broken on Windows

### ISSUE THREAD

**Issue by remram44** [conda/conda-build#478]
Installed a fresh Windows 64 VM with a fresh Anaconda 64. Right after running "conda install patch", any attempt to use "conda skeleton pypi" gives out:
```
C:\Users\user\Desktop>conda skeleton pypi reprounzip
Warning, the following versions were found for reprounzip
0.7
0.6.4
0.6.3
0.6
0.5.1
0.5
0.4.1
0.4
0.3.2
0.3
0.2.1
0.2
0.0
Using 0.7
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/r/reprounzip/reprounzip-0.7.tar.gz (38 KB) for reprounzip.
Downloading reprounzip
Using cached download
Unpacking reprounzip...
done
working in c:\users\user\appdata\local\temp\tmplbobcvconda_skeleton_reprounzip-0.7.tar.gz
Fetching package metadata: ......
Solving package specifications: .
Applying patch: 'c:\\users\\user\\appdata\\local\\temp\\tmplbobcvconda_skeleton_reprounzip-0.7.tar.gz\\pypi-distutils.patch'
69 unparsed bytes left at the end of stream
file 1/1:        core.py
 hunk no.1 doesn't match source file at line 165
  expected:
  actual  :                 raise SystemExit, "error: " + str(msg)
source file is different - core.py
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda-64\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda-64\lib\site-packages\conda_build\main_skeleton.py", line 240, in main
    args_func(args, p)
  File "C:\Anaconda-64\lib\site-packages\conda_build\main_build.py", line 349, in args_func
    args.func(args, p)
  File "C:\Anaconda-64\lib\site-packages\conda_build\main_skeleton.py", line 254, in execute
    pypi.main(args, parser)
  File "C:\Anaconda-64\lib\site-packages\conda_build\pypi.py", line 338, in main
    get_package_metadata(args, package, d, data)
  File "C:\Anaconda-64\lib\site-packages\conda_build\pypi.py", line 475, in get_package_metadata
    python_version=args.python_version)
  File "C:\Anaconda-64\lib\site-packages\conda_build\pypi.py", line 736, in get_pkginfo
    run_setuppy(src_dir, tempdir, python_version)
  File "C:\Anaconda-64\lib\site-packages\conda_build\pypi.py", line 783, in run_setuppy
    apply_patch(join(stdlib_dir, 'distutils'), patch)
  File "C:\Anaconda-64\lib\site-packages\conda_build\source.py", line 235, in apply_patch
    check_call([patch, '-p0', '-i', path], cwd=src_dir)
  File "C:\Anaconda-64\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Anaconda-64\\Scripts\\patch.bat', '-p0', '-i', 'c:\\users\\user\\appdata\\local\\temp\\tmplbobcvconda_skeleton_reprounzip-0.7.tar.gz\\pypi-distutils.patch']' returned non-zero exit status -1
```
I cannot build packages on Windows 64. Please address this ASAP.

Possible duplicate of #476

**Comment by remram44** [comment]
I don't know what the hell this patch is about but this is very broken.

Anaconda on Windows 32 also affected.

**Comment by remram44** [comment]
Duplicate of #119
