### ISSUE TITLE
OpenSSL 3.0.8 causes issues for tests

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#4911]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Test suite struggles with updated OpenSSL 3.0.8.

With the following recipe:

```
# recipe/meta.yml
package:
  name: test_resolved_packages_host_build
  version: 1.0

requirements:
  build:
    - numpy
    - nomkl    # [unix]
  host:
    - curl
  run:
  {% for package in resolved_packages('build') %}
    - {{ package }}
  {% endfor %}
  {% for package in resolved_packages('host') %}
    - {{ package }}
  {% endfor %}
```

we get the following error:

```bash
$ conda build recipe/
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for test_resolved_packages_host_build
INFO:conda_build.metadata:Attempting to finalize metadata for test_resolved_packages_host_build
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Traceback (most recent call last):
  File "/Users/kodegard/.conda/arm64/23.3.1/3.10/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/kodegard/.conda/arm64/23.3.1/3.10/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 593, in main
    execute(sys.argv[1:])
  File "/Users/kodegard/.conda/arm64/23.3.1/3.10/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 573, in execute
    outputs = api.build(
  File "/Users/kodegard/.conda/arm64/23.3.1/3.10/lib/python3.10/site-packages/conda_build/api.py", line 253, in build
    return build_tree(
  File "/Users/kodegard/.conda/arm64/23.3.1/3.10/lib/python3.10/site-packages/conda_build/build.py", line 3799, in build_tree
    packages_from_this = build(
  File "/Users/kodegard/.conda/arm64/23.3.1/3.10/lib/python3.10/site-packages/conda_build/build.py", line 2469, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/Users/kodegard/.conda/arm64/23.3.1/3.10/lib/python3.10/site-packages/conda_build/render.py", line 923, in expand_outputs
    for output_dict, m in deepcopy(_m).get_output_metadata_set(
  File "/Users/kodegard/.conda/arm64/23.3.1/3.10/lib/python3.10/site-packages/conda_build/metadata.py", line 2565, in get_output_metadata_set
    conda_packages = finalize_outputs_pass(
  File "/Users/kodegard/.conda/arm64/23.3.1/3.10/lib/python3.10/site-packages/conda_build/metadata.py", line 909, in finalize_outputs_pass
    fm = finalize_metadata(
  File "/Users/kodegard/.conda/arm64/23.3.1/3.10/lib/python3.10/site-packages/conda_build/render.py", line 732, in finalize_metadata
    _simplify_to_exact_constraints(m)
  File "/Users/kodegard/.conda/arm64/23.3.1/3.10/lib/python3.10/site-packages/conda_build/render.py", line 573, in _simplify_to_exact_constraints
    raise ValueError(f"Conflicting exact pins: {exact_pins}")
ValueError: Conflicting exact pins: [['1.1.1t', 'h1a28f6b_0'], ['3.0.8', 'h1a28f6b_0']]
```

**Comment by kenodegard** [comment]
See https://github.com/conda/conda-build/actions/runs/5249068170/jobs/9483425287
