### ISSUE TITLE
BUG: `create_info_files` fails on `git_url` in some circumstances

### ISSUE THREAD

**Issue by h-vetinari** [conda/conda-build#4938]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

While this issue reminded me of #4266, this happens _after_ the build rather than before, but it fails on the same `isdir` function.

Looks like:
```
   INFO (libclang-cpp17,lib/libclang-cpp.so.17git): Needed DSO lib/libgcc_s.so.1 found in conda-forge::libgcc-ng-13.1.0-he5830b7_0
   INFO (libclang-cpp17,lib/libclang-cpp.so.17git): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/libc.so.6 found in CDT/compiler package conda-forge::sysroot_linux-64-2.12-he073ed8_16
   INFO (libclang-cpp17,lib/libclang-cpp.so.17git): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/ld-linux-x86-64.so.2 found in CDT/compiler package conda-forge::sysroot_linux-64-2.12-he073ed8_16
Fixing permissions
Packaged license file/s.
INFO :: Time taken to mark (prefix)
        0 replacements in 0 files was 0.13 seconds
Traceback (most recent call last):
  File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 253, in build
    return build_tree(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3799, in build_tree
    packages_from_this = build(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2875, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2017, in bundle_conda
    output["checksums"] = create_info_files(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 1568, in create_info_files
    source.git_info(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/source.py", line 460, in git_info
    assert isdir(src_dir)
AssertionError
```

I've seem it in two recipes now: https://github.com/conda-forge/clangdev-feedstock/pull/230 & https://github.com/conda-forge/openmp-feedstock/pull/97

### Conda Info

```shell
conda-forge CI linux/osx
```

### Conda Config

```shell
conda-forge CI linux/osx
```

### Conda list

```shell
See recipe
```

**Comment by h-vetinari** [comment]
This is still happening when using
```yaml
  - git_url: https://github.com/llvm/llvm-project.git
    git_rev: 1754651dd150139d64cdae190afe1faabf69a403
```
both in https://github.com/conda-forge/clangdev-feedstock/pull/292 & https://github.com/conda-forge/openmp-feedstock/pull/128

Workaroud is turning the above into
```yaml
  - url: https://github.com/llvm/llvm-project/archive/1754651dd150139d64cdae190afe1faabf69a403.tar.gz
    sha256: e69a1b15a7972a72334229d597b78ee56a5ed16aa62299df23ecd239dfd3a8f5
```
i.e. downloading the archive that github generates for that commit.
