### ISSUE TITLE
Following packaging tutorial on Windows yields error

### ISSUE THREAD

**Issue by MatthiasKauer** [conda/conda-build#495]
Hi,
I was following the packing tutorial from http://conda.pydata.org/docs/build_tutorials/pkgs.html on my Win 7 machine. 

```
C:\dvl>conda info
Current conda install:

             platform : win-32
        conda version : 3.14.1
  conda-build version : 1.14.1
       python version : 2.7.9.final.0
     requests version : 2.7.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

I followed the steps from the web site to the letter until 

```
conda skeleton pypi pyinstrument
```

failed on me saying

```
Warning, the following versions were found for pyinstrument                                                           
0.13.1                                                                                                                
0.13                                                                                                                  
0.12                                                                                                                  
0.11                                                                                                                  
0.10.1                                                                                                                
Using 0.13.1                                                                                                          
Use --version to specify a different version.                                                                         
Using url https://pypi.python.org/packages/source/p/pyinstrument/pyinstrument-0.13.1.tar.gz (44 KB) for pyinstrument. 
Downloading pyinstrument                                                                                              
Unpacking pyinstrument...                                                                                             
done                                                                                                                  
working in c:\users\matthi~1.kau\appdata\local\temp\tmptkgi7mconda_skeleton_pyinstrument-0.13.1.tar.gz                
Fetching package metadata: ......                                                                                     
Solving package specifications: .                                                                                     
The following NEW packages will be INSTALLED:                                                                         

    numpy:      1.9.2-py27_0                                                                                          
    pip:        7.1.0-py27_0                                                                                          
    python:     2.7.10-0                                                                                              
    pyyaml:     3.11-py27_1                                                                                           
    setuptools: 18.0.1-py27_0                                                                                         

Linking packages ...                                                                                                  
[      COMPLETE      ]|##################################################| 100%                                       
Applying patch: 'c:\\users\\matthi~1.kau\\appdata\\local\\temp\\tmptkgi7mconda_skeleton_pyinstrument-0.13.1.tar.gz\\py
pi-distutils.patch'                                                                                                   
An unexpected error has occurred, please consider sending the                                                         
following traceback to the conda GitHub issue tracker at:                                                             

    https://github.com/conda/conda-build/issues                                                                       

Include the output of the command 'conda info' in your report.                                                        


Traceback (most recent call last):                                                                                    
  File "C:\Anaconda\Scripts\conda-skeleton-script.py", line 4, in <module>                                            
    sys.exit(main())                                                                                                  
  File "C:\Anaconda\lib\site-packages\conda_build\main_skeleton.py", line 240, in main                                
    args_func(args, p)                                                                                                
  File "C:\Anaconda\lib\site-packages\conda_build\main_build.py", line 349, in args_func                              
    args.func(args, p)                                                                                                
  File "C:\Anaconda\lib\site-packages\conda_build\main_skeleton.py", line 254, in execute                             
    pypi.main(args, parser)                                                                                           
  File "C:\Anaconda\lib\site-packages\conda_build\pypi.py", line 338, in main                                         
    get_package_metadata(args, package, d, data)                                                                      
  File "C:\Anaconda\lib\site-packages\conda_build\pypi.py", line 475, in get_package_metadata                         
    python_version=args.python_version)                                                                               
  File "C:\Anaconda\lib\site-packages\conda_build\pypi.py", line 736, in get_pkginfo                                  
    run_setuppy(src_dir, tempdir, python_version)                                                                     
  File "C:\Anaconda\lib\site-packages\conda_build\pypi.py", line 783, in run_setuppy                                  
    apply_patch(join(stdlib_dir, 'distutils'), patch)                                                                 
  File "C:\Anaconda\lib\site-packages\conda_build\source.py", line 235, in apply_patch                                
    check_call([patch, '-p0', '-i', path], cwd=src_dir)                                                               
  File "C:\Anaconda\lib\subprocess.py", line 535, in check_call                                                       
    retcode = call(*popenargs, **kwargs)                                                                              
  File "C:\Anaconda\lib\subprocess.py", line 522, in call                                                             
    return Popen(*popenargs, **kwargs).wait()                                                                         
  File "C:\Anaconda\lib\subprocess.py", line 710, in __init__                                                         
    errread, errwrite)                                                                                                
  File "C:\Anaconda\lib\subprocess.py", line 958, in _execute_child                                                   
    startupinfo)                                                                                                      
WindowsError: [Error 740] The requested operation requires elevation                                                  
```

Does this mean that `conda skeleton` needs admin rights?

**Comment by asmeurer** [comment]
conda skeleton tries to use the `patch` command. That is probably what is requiring elevation.

**Comment by MatthiasKauer** [comment]
elevation meaning admin rights?

**Comment by giumas** [comment]
Exactly the same issue on my machine:

```
             platform : win-32
        conda version : 3.18.3
  conda-build version : 1.18.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
```

The same command works if I run it as administrator:

```
C:\__hyo_dev\test_data>conda skeleton pypi pyinstrument
Warning, the following versions were found for pyinstrument
0.13.1
0.13
0.12
0.11
0.10.1
Using 0.13.1
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/p/pyinstrument/pyinstrument-0.13.1.tar.gz (44 KB) for pyinstrument.
Downloading pyinstrument
Using cached download
Unpacking pyinstrument...
done
working in c:\users\xxxxxx\appdata\local\temp\tmpxm6ktkconda_skeleton_pyinstrument-0.13.1.tar.gz
Fetching package metadata: ..............
Solving package specifications: ...............
Applying patch: 'c:\\users\\xxxxxx\\appdata\\local\\temp\\tmpxm6ktkconda_skeleton_pyinstrument-0.13.1.tar.gz\\pypi-distutils.patch'
patching file `core.py'
Hunk #1 succeeded at 169 with fuzz 2 (offset 2 lines).
Writing recipe for pyinstrument
Done
```

**Comment by msarahan** [comment]
Please update your patch package and try again.  This was an issue with patch version 2.5.9-0.  It is fixed in 2.5.9-1.  2.5.9-1 has been available for about 2 weeks on win-64, but it may not yet be available on win-32 due to server issues we've been having.  It should be available very soon if it is not already.

**Comment by giumas** [comment]
After:

```
C:\__hyo_dev\hyo_hdf-compass>conda update patch
Fetching package metadata: ............
Solving package specifications: .............
Package plan for installation in environment C:\Users\xxxxxx\AppData\Local\HyO_x86\py2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    patch-2.5.9                |                1          56 KB

The following packages will be UPDATED:

    patch: 2.5.9-0 --> 2.5.9-1

Proceed ([y]/n)? y

Fetching packages ...
patch-2.5.9-1. 100% |###############################| Time: 0:00:00   1.11 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
```

I got:

```
C:\__hyo_dev\test_data>conda skeleton pypi pyinstrument
Warning, the following versions were found for pyinstrument
0.13.1
0.13
0.12
0.11
0.10.1
Using 0.13.1
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/p/pyinstrument/pyinstrument-0.13.1.tar.gz (44 KB) for pyinstrument.
Downloading pyinstrument
Using cached download
Unpacking pyinstrument...
done
working in c:\users\xxxxxx\appdata\local\temp\tmpbgmf2cconda_skeleton_pyinstrument-0.13.1.tar.gz
Fetching package metadata: ..............
Solving package specifications: ...............
The following NEW packages will be INSTALLED:

    numpy:      1.10.1-py27_0
    pip:        7.1.2-py27_0
    python:     2.7.10-1
    pyyaml:     3.11-py27_2
    setuptools: 18.4-py27_0
    wheel:      0.26.0-py27_1

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
Applying patch: 'c:\\users\\xxxxxx\\appdata\\local\\temp\\tmpbgmf2cconda_skeleton_pyinstrument-0.13.1.tar.gz\\pypi-distutils.patch'
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\xxxxxx\AppData\Local\HyO_x86\py2\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\xxxxxx\AppData\Local\HyO_x86\py2\lib\site-packages\conda_build\main_skeleton.py", line 272, in main
    args_func(args, p)
  File "C:\Users\xxxxxx\AppData\Local\HyO_x86\py2\lib\site-packages\conda_build\main_build.py", line 468, in args_func
    args.func(args, p)
  File "C:\Users\xxxxxx\AppData\Local\HyO_x86\py2\lib\site-packages\conda_build\main_skeleton.py", line 286, in execute
    pypi.main(args, parser)
  File "C:\Users\xxxxxx\AppData\Local\HyO_x86\py2\lib\site-packages\conda_build\pypi.py", line 341, in main
    get_package_metadata(args, package, d, data)
  File "C:\Users\xxxxxx\AppData\Local\HyO_x86\py2\lib\site-packages\conda_build\pypi.py", line 478, in get_package_metadata
    python_version=args.python_version)
  File "C:\Users\xxxxxx\AppData\Local\HyO_x86\py2\lib\site-packages\conda_build\pypi.py", line 741, in get_pkginfo
    run_setuppy(src_dir, tempdir, python_version)
  File "C:\Users\xxxxxx\AppData\Local\HyO_x86\py2\lib\site-packages\conda_build\pypi.py", line 788, in run_setuppy
    apply_patch(join(stdlib_dir, 'distutils'), patch)
  File "C:\Users\xxxxxx\AppData\Local\HyO_x86\py2\lib\site-packages\conda_build\source.py", line 253, in apply_patch
    check_call([patch, ] + patch_args, cwd=src_dir)
  File "C:\Users\xxxxxx\AppData\Local\HyO_x86\py2\lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\xxxxxx\AppData\Local\HyO_x86\py2\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Users\xxxxxx\AppData\Local\HyO_x86\py2\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Users\xxxxxx\AppData\Local\HyO_x86\py2\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 740] The requested operation requires elevation
```

**Comment by msarahan** [comment]
This is very strange.  Can you please check a few things for me:

1. Is patch.exe.manifest in your C:\Users\xxxxxx\AppData\Local\HyO_x86\py2\Library\bin folder?
2. Is C:\Users\xxxxxx\AppData\Local\HyO_x86\py2\Library\bin on your PATH environment variable?
3. what does ```where patch.exe``` show?  (I think this works, I'm much more familiar with the Linux equivalent, which).  See http://stackoverflow.com/questions/304319/is-there-an-equivalent-of-which-on-the-windows-command-line

**Comment by msarahan** [comment]
(I think you have another patch.exe file that is getting found, and this one is lacking the manifest that tells it not to require elevation)

**Comment by giumas** [comment]
The issue is that `unxtools` installs a `patch.exe` that requires elevation in: `C:\Users\xxxxx\AppData\Local\HyO_x86\py2\Scripts\patch.exe`. 

I have installed this package as suggested here: http://conda.pydata.org/docs/build_tutorials/pkgs.html#before-you-start

Should I modify my PATH to have `C:\Users\xxxxx\AppData\Local\HyO_x86\py2\Scripts` after `C:\Users\xxxxxx\AppData\Local\HyO_x86\py2\Library\bin`? 

It is the first time that this makes me troubles..

**Comment by msarahan** [comment]
That's a mess that we need to clean up.  Sorry.  For now, please do any of the following:
 - delete the patch.exe in \Scripts, so that the one in Library\bin (from patch-2.5.9-1 takes precedence)
 - modify your path as you mention
 - copy the patch.exe.manifest from Library\bin into your \scripts folder

The longest-term solution is the first.  UnxUtils is pretty out of date.  I discovered this when trying to use sed for something - unxutils has only version 3, but I wanted version 4 for the sake of in-place modification of strings.  We'll be replacing unxutils over time with gnuwin32 instead.  There is a package available in conda for this, but it may not be complete.  If you try to use that instead, and it is missing anything, please file an issue.  Also, for some of these utilities (like patch) that are used regardless of whether someone wants a Unix-like environment, we are creating separate packages (such as patch).

**Comment by jorisvandenbossche** [comment]
I have exactly the same issue. I then uninstalled `unxutils` and installed `gnuwin32`, and it works!

**Comment by artPlusPlus** [comment]
I ran into this as well. @jorisvandenbossche 's solution worked. I was able to run the skeleton command without admin privileges. I am running Windows 10, 64bit.
