### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'recipe' in version  3.26.1

### ISSUE THREAD

**Issue by acatlett8** [conda/conda-build#4984]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Tried to do a conda build -c conda-forge conda.recipe got the following error:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/rditlar9/miniconda/lib/python3.9/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/Users/rditlar9/miniconda/lib/python3.9/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/Users/rditlar9/miniconda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 115, in do_call
        return args.plugin_subcommand.action(sys.argv[2:])
      File "/Users/rditlar9/miniconda/lib/python3.9/site-packages/conda_build/plugin.py", line 10, in build
        execute(*args, **kwargs)
      File "/Users/rditlar9/miniconda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 516, in execute
        _parser, args = parse_args(args)
      File "/Users/rditlar9/miniconda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 470, in parse_args
        check_recipe(args.recipe)
    AttributeError: 'Namespace' object has no attribute 'recipe'

I was in the directory where the  conda.recipe folder with meta.yaml file was located. I was able to fix this by installing 3.25.0. 

### Conda Info

```shell
active environment : base
    active env location : /Users/rditlar9/miniconda
            shell level : 1
       user config file : /Users/rditlar9/.condarc
 populated config files : /Users/rditlar9/.condarc
          conda version : 23.3.1
    conda-build version : 3.25.0
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=13.5=0
                          __unix=0=0
       base environment : /Users/rditlar9/miniconda  (writable)
      conda av data dir : /Users/rditlar9/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/rditlar9/miniconda/pkgs
                          /Users/rditlar9/.conda/pkgs
       envs directories : /Users/rditlar9/miniconda/envs
                          /Users/rditlar9/.conda/envs
               platform : osx-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.9.16 Darwin/22.6.0 OSX/13.5
                UID:GID : 1714474862:2011572450
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /Users/rditlar9/.condarc <==
auto_activate_base: False
```

### Conda list

```shell
# packages in environment at /Users/rditlar9/miniconda:
#
# Name                    Version                   Build  Channel
anaconda-client           1.8.0              pyhd8ed1ab_0    conda-forge
anaconda-project          0.10.2             pyhd3eb1b0_0    defaults
anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39ha30fb19_3    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
bokeh                     2.4.3                    pypi_0    pypi
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                hb7f2c08_8    conda-forge
brotli-bin                1.0.9                hb7f2c08_8    conda-forge
brotlipy                  0.7.0           py39h9ed2024_1003    defaults
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.19.1               h0dc2134_0    conda-forge
ca-certificates           2023.7.22            h8857fd0_0    conda-forge
cctools                   973.0.1             h40f6528_13    conda-forge
cctools_osx-64            973.0.1             h5676edf_13    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h131948b_3    conda-forge
cftime                    1.6.2                    pypi_0    pypi
chardet                   5.1.0            py39h6e9494a_0    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3                    pypi_0    pypi
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
colorcet                  3.0.1                    pypi_0    pypi
comm                      0.1.3              pyhd8ed1ab_0    conda-forge
conda                     23.3.1           py39h6e9494a_0    conda-forge
conda-build               3.26.1           py39h6e9494a_0    conda-forge
conda-index               0.2.3              pyhd8ed1ab_0    conda-forge
conda-pack                0.7.0              pyh6c4a22f_0    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.7.0              pyhd8ed1ab_1    conda-forge
cryptography              40.0.2           py39hbeae22c_0    conda-forge
debugpy                   1.6.7            py39h7a8716b_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dodcerts                  1.0                      pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
filelock                  3.12.0             pyhd8ed1ab_0    conda-forge
flask                     2.2.2                    pypi_0    pypi
flit-core                 3.9.0              pyhd8ed1ab_0    conda-forge
fmt                       9.1.0                hb8565cd_0    conda-forge
glob2                     0.7                        py_0    conda-forge
helios-workflows          0.3.0                     dev_0    <develop>
holoviews                 1.15.1                   pypi_0    pypi
icu                       72.1                 h7336db1_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.6.0              pyha770c72_0    conda-forge
importlib_metadata        6.6.0                hd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
ipykernel                 6.23.1             pyh736e0ef_0    conda-forge
ipython                   8.13.2             pyhd1c38e8_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter_client            8.2.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.0            py39h6e9494a_0    conda-forge
jupyter_server            1.23.6             pyhd8ed1ab_0    conda-forge
jupyterlab                3.4.3              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.22.1             pyhd8ed1ab_0    conda-forge
krb5                      1.20.1               h049b76e_0    conda-forge
ld64                      609                 ha02d983_13    conda-forge
ld64_osx-64               609                 hbfe4790_13    conda-forge
libarchive                3.6.2                h0b5dc4a_1    conda-forge
libbrotlicommon           1.0.9                hb7f2c08_8    conda-forge
libbrotlidec              1.0.9                hb7f2c08_8    conda-forge
libbrotlienc              1.0.9                hb7f2c08_8    conda-forge
libcurl                   8.1.1                hbee3ae8_0    conda-forge
libcxx                    16.0.4               hd57cbcb_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libiconv                  1.17                 hac89ed1_0    conda-forge
liblief                   0.12.3               hf0c8a7f_0    conda-forge
libllvm16                 16.0.4               he4b1e75_0    conda-forge
libmamba                  1.4.2                h9d281b0_0    conda-forge
libmambapy                1.4.2            py39he664332_0    conda-forge
libnghttp2                1.52.0               he2ab024_0    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libsolv                   0.7.23               hbc0c0cd_0    conda-forge
libsqlite                 3.42.0               h58db7d2_0    conda-forge
libssh2                   1.10.0               h47af595_3    conda-forge
libxml2                   2.11.4               hd95e348_0    conda-forge
libzlib                   1.2.13               hfd90126_4    conda-forge
lz4-c                     1.9.4                hf0c8a7f_0    conda-forge
lzo                       2.10              haf1e3a3_1000    conda-forge
mamba                     1.4.2            py39h412838c_0    conda-forge
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   2.0.5              pyhd8ed1ab_0    conda-forge
mock                      4.0.3                    pypi_0    pypi
more-itertools            10.1.0             pyhd8ed1ab_0    conda-forge
nbclassic                 0.5.6              pyh8b2e9e2_0    conda-forge
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.4.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.8.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
netcdf4                   1.6.1                    pypi_0    pypi
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
numpy                     1.23.4                   pypi_0    pypi
openssl                   3.1.2                h8a1eda9_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    1.5.1                    pypi_0    pypi
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
panel                     0.14.0                   pypi_0    pypi
param                     1.12.2                   pypi_0    pypi
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
patch                     2.7.6             hbcf498f_1002    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0                    pypi_0    pypi
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pkginfo                   1.9.6              pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.5.1              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
pokemon-terminal          1.3.0                    pypi_0    pypi
prometheus_client         0.16.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
psutil                    5.9.0                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py-lief                   0.12.3           py39h7a8716b_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4            py39ha30fb19_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyct                      0.4.8                    pypi_0    pypi
pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
pyobjc-core               9.1.1            py39h0504f80_0    conda-forge
pyobjc-framework-cocoa    9.1.1            py39h0504f80_0    conda-forge
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pyrsistent                0.19.3           py39ha30fb19_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.16          h709bd14_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.17.1             pyhd8ed1ab_0    conda-forge
python-libarchive-c       4.0              py39h6e9494a_2    conda-forge
python.app                3                py39hca72f7f_0    defaults
python_abi                3.9                      3_cp39    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyuit                     0.4.0a5                   dev_0    <develop>
pyviz-comms               2.2.1                    pypi_0    pypi
pyyaml                    6.0              py39ha30fb19_5    conda-forge
pyzmq                     25.0.2           py39hed8f129_0    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
reproc                    14.2.4               hb7f2c08_0    conda-forge
reproc-cpp                14.2.4               hf0c8a7f_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               hbbacdb1_2    conda-forge
ruamel.yaml               0.17.26          py39hdc70f33_0    conda-forge
ruamel.yaml.clib          0.2.7            py39ha30fb19_1    conda-forge
ruamel_yaml               0.15.80         py39ha30fb19_1008    conda-forge
send2trash                1.8.2              pyhd1c38e8_0    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
sigtool                   0.1.3                h88f4db0_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
tapi                      1100.0.11            h9ce4665_0    conda-forge
terminado                 0.17.1             pyhd1c38e8_0    conda-forge
tethysapp-helios          1.2.0a1                   dev_0    <develop>
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.3.2            py39hdc70f33_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.4.0                    pypi_0    pypi
typing_extensions         4.6.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
uit-plus-job              0.3.0a1                   dev_0    <develop>
urllib3                   1.26.16          py39hecd8cb5_0    defaults
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.5.2              pyhd8ed1ab_0    conda-forge
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xarray                    2022.10.0                pypi_0    pypi
xz                        5.2.6                h775f41a_0    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
yaml-cpp                  0.7.0                hf0c8a7f_2    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zstandard                 0.19.0           py39h5bcbcff_1    conda-forge
zstd                      1.5.2                hbc0c0cd_6    conda-forge
```

### Additional Context

note that i have changed conda-build version 3.25.0. However since this is a new update wanted to state there was a bug. I did not see any new guidance on how to implement the conda build command.

**Comment by biocodz** [comment]
Having exact same error with conda 23.3.1 on Windows
```
conda build ./a1/code/conda-staged-recipes/recipes/sortmerna
> c:\users\ak.xps15i9\a1\apps\miniforge3\lib\site-packages\conda_build\cli\main_build.py(474)parse_args()
-> check_recipe(args.recipe)
(Pdb) type(args.recipe)
*** AttributeError: 'Namespace' object has no attribute 'recipe'
(Pdb) type(args)
<class 'argparse.Namespace'>
(Pdb) dir(argparse.Namespace)
['__class__', '__contains__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_get_args', '_get_kwargs']
(Pdb) c

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\ak.xps15i9\a1\apps\miniforge3\lib\site-packages\conda\exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "C:\Users\ak.xps15i9\a1\apps\miniforge3\lib\site-packages\conda\cli\main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "C:\Users\ak.xps15i9\a1\apps\miniforge3\lib\site-packages\conda\cli\conda_argparse.py", line 115, in do_call
        return args.plugin_subcommand.action(sys.argv[2:])
      File "C:\Users\ak.xps15i9\a1\apps\miniforge3\lib\site-packages\conda_build\plugin.py", line 10, in build
        execute(*args, **kwargs)
      File "C:\Users\ak.xps15i9\a1\apps\miniforge3\lib\site-packages\conda_build\cli\main_build.py", line 520, in execute
        _parser, args = parse_args(args)
      File "C:\Users\ak.xps15i9\a1\apps\miniforge3\lib\site-packages\conda_build\cli\main_build.py", line 474, in parse_args
        check_recipe(args.recipe)
    AttributeError: 'Namespace' object has no attribute 'recipe'

`$ C:\Users\ak.xps15i9\a1\apps\miniforge3\Scripts\conda-script.py build ./a1/code/conda-staged-recipes/recipes/sortmerna`

  environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=.;
    CONDA_ALLOW_SOFTLINKS=false
        CONDA_DEFAULT_ENV=sortmerna
                CONDA_EXE=C:\Users\ak.xps15i9\a1\apps\miniforge3\Scripts\conda.exe
               CONDA_HOME=C:\Users\ak.xps15i9\a1\apps\miniforge3
             CONDA_PREFIX=C:\Users\ak.xps15i9\a1\apps\miniforge3\envs\sortmerna
           CONDA_PREFIX_1=C:\Users\ak.xps15i9\a1\apps\miniforge3
    CONDA_PROMPT_MODIFIER=(sortmerna)
         CONDA_PYTHON_EXE=C:\Users\ak.xps15i9\a1\apps\miniforge3\python.exe
               CONDA_ROOT=C:\Users\ak.xps15i9\a1\apps\miniforge3
              CONDA_SHLVL=2
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
           CURL_CA_BUNDLE=<not set>
      FNM_MULTISHELL_PATH=C:\Users\ak.xps15i9\AppData\Local\fnm_multishells\22752_1706655746852
                 HOMEPATH=\Users\ak.xps15i9
               LD_PRELOAD=<not set>
                  LIBPATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\
                          14.37.32822\ATLMFC\lib\x64;C:\Program Files\Microsoft Visual
                          Studio\2022\Community\VC\Tools\MSVC\14.37.32822\lib\x64;C:\Program
                          Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822
                          \lib\x86\store\references;C:\Program Files (x86)\Windows
                          Kits\10\UnionMetadata\10.0.19041.0;C:\Program Files (x86)\Windows Kits
                          \10\References\10.0.19041.0;C:\Windows\Microsoft.NET\Framework64\v4.0.
                          30319
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\tools\git\bin;C:\tools\git\usr\bin;C:\tools\git\mingw64\bin;C:\Prog
                          ram Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin;C:\Program
                          Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp;C:\Program
                          Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64;C:\Program
                          Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822
                          \bin\HostX64\x64;C:\Program Files\Microsoft Visual
                          Studio\2022\Community\Common7\IDE\VC\VCPackages;C:\Program
                          Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensi
                          ons\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022
                          \Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team
                          Explorer;C:\Program Files\Microsoft Visual
                          Studio\2022\Community\MSBuild\Current\bin\Roslyn;C:\Program
                          Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance
                          Tools\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Team
                          Tools\Performance Tools;C:\Program Files (x86)\Windows
                          Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows
                          Kits\10\bin\x64;C:\Program Files\Microsoft Visual Studio\2022\Communit
                          y\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.
                          30319;C:\Program Files\Microsoft Visual
                          Studio\2022\Community\Common7\IDE;C:\Program Files\Microsoft Visual St
                          udio\2022\Community\Common7\Tools;C:\Users\ak.xps15i9\a1\apps\miniforg
                          e3\envs\sortmerna;C:\Users\ak.xps15i9\a1\apps\miniforge3\envs\sortmern
                          a\Library\mingw-
                          w64\bin;C:\Users\ak.xps15i9\a1\apps\miniforge3\envs\sortmerna\Library\
                          usr\bin;C:\Users\ak.xps15i9\a1\apps\miniforge3\envs\sortmerna\Library\
                          bin;C:\Users\ak.xps15i9\a1\apps\miniforge3\envs\sortmerna\Scripts;C:\U
                          sers\ak.xps15i9\a1\apps\miniforge3\envs\sortmerna\bin;C:\Users\ak.xps1
                          5i9\a1\apps\miniforge3\condabin;C:\Users\ak.xps15i9\AppData\Local\fnm_
                          multishells\22752_1706655746852;C:\Program
                          Files\PowerShell\7;C:\VulkanSDK\1.3.275.0\Bin;C:\Program Files\NVIDIA
                          GPU Computing Toolkit\CUDA\v11.8\bin;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v11.8\libnvvp;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v12.0\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v12.0\libnvvp;C:\Program Files\Common Files\Oracle\Java\j
                          avapath;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\system32
                          ;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\OpenSSH;C:\Pr
                          ogram Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program
                          Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\ProgramData\chocolatey\bin;C:\Program
                          Files\VSCodium\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program
                          Files\Java\jdk1.8.0_211\bin;C:\Program
                          Files\dotnet;C:\ProgramData\chocolatey\lib\maven\apache-
                          maven-3.8.6\bin;C:\tools\gsudo\Current;C:\Program Files\NVIDIA
                          Corporation\Nsight Compute 2022.3.0;C:\WINDOWS\system32;C:\WINDOWS;C:\
                          WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WI
                          NDOWS\System32\OpenSSH;C:\Program Files\gs\gs10.01.1\bin;C:\Program
                          Files\nodejs;C:\Program Files\GitHub CLI;C:\Program Files\PowerShell\7
                          ;C:\Users\ak.xps15i9\scoop\shims;C:\Users\ak.xps15i9\.cargo\bin;C:\WIN
                          DOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps
                          ;C:\tools\neovim\Neovim\bin;C:\tools\git\bin;C:\Program
                          Files\Oracle\VirtualBox;C:\Program Files
                          (x86)\Nmap;C:\tools\neovim\nvim-win64\bin;C:\Program Files\Tesseract-O
                          CR;C:\Users\ak.xps15i9\AppData\Roaming\npm;C:\Users\ak.xps15i9\AppData
                          \Local\Programs\Lens\resources\cli\bin;C:\Program Files\Microsoft
                          Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CM
                          ake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\
                          Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program
                          Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\Linux\bin\
                          ConnectionManagerExeC:\Users\ak.xps15i9\AppData\Local\Microsoft\Window
                          sApps;.
             PSMODULEPATH=C:\Users\ak.xps15i9\Documents\PowerShell\Modules;C:\Program
                          Files\PowerShell\Modules;c:\program
                          files\powershell\7\Modules;C:\Program Files\WindowsPowerShell\Modules;
                          C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
              VK_SDK_PATH=C:\VulkanSDK\1.3.275.0
           WINDOWSLIBPATH=C:\Program Files (x86)\Windows
                          Kits\10\UnionMetadata\10.0.19041.0;C:\Program Files (x86)\Windows
                          Kits\10\References\10.0.19041.0
        WINDOWSSDKBINPATH=C:\Program Files (x86)\Windows Kits\10\bin\
     WINDOWSSDKVERBINPATH=C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\
     __VSCMD_PREINIT_PATH=C:\Users\ak.xps15i9\a1\apps\miniforge3;C:\Users\ak.xps15i9\a1\apps\min
                          iforge3\Library\mingw-
                          w64\bin;C:\Users\ak.xps15i9\a1\apps\miniforge3\Library\usr\bin;C:\User
                          s\ak.xps15i9\a1\apps\miniforge3\Library\bin;C:\Users\ak.xps15i9\a1\app
                          s\miniforge3\Scripts;C:\Users\ak.xps15i9\a1\apps\miniforge3\bin;C:\Use
                          rs\ak.xps15i9\a1\apps\miniforge3\condabin;C:\Users\ak.xps15i9\AppData\
                          Local\fnm_multishells\22752_1706655746852;C:\Program
                          Files\PowerShell\7;C:\VulkanSDK\1.3.275.0\Bin;C:\Program Files\NVIDIA
                          GPU Computing Toolkit\CUDA\v11.8\bin;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v11.8\libnvvp;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v12.0\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v12.0\libnvvp;C:\Program Files\Common Files\Oracle\Java\j
                          avapath;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\system32
                          ;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\OpenSSH;C:\Pr
                          ogram Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program
                          Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\ProgramData\chocolatey\bin;C:\Program
                          Files\VSCodium\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program
                          Files\Java\jdk1.8.0_211\bin;C:\Program
                          Files\dotnet;C:\ProgramData\chocolatey\lib\maven\apache-
                          maven-3.8.6\bin;C:\tools\gsudo\Current;C:\Program Files\NVIDIA
                          Corporation\Nsight Compute 2022.3.0;C:\WINDOWS\system32;C:\WINDOWS;C:\
                          WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WI
                          NDOWS\System32\OpenSSH;C:\Program Files\gs\gs10.01.1\bin;C:\Program
                          Files\nodejs;C:\Program Files\GitHub CLI;C:\Program Files\PowerShell\7
                          ;C:\Users\ak.xps15i9\scoop\shims;C:\Users\ak.xps15i9\.cargo\bin;C:\WIN
                          DOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps
                          ;C:\tools\neovim\Neovim\bin;C:\tools\git\bin;C:\Program
                          Files\Oracle\VirtualBox;C:\Program Files
                          (x86)\Nmap;C:\tools\neovim\nvim-win64\bin;C:\Program Files\Tesseract-O
                          CR;C:\Users\ak.xps15i9\AppData\Roaming\npm;C:\Users\ak.xps15i9\AppData
                          \Local\Programs\Lens\resources\cli\bin

     active environment : sortmerna
    active env location : C:\Users\ak.xps15i9\a1\apps\miniforge3\envs\sortmerna
            shell level : 2
       user config file : C:\Users\ak.xps15i9\.condarc
 populated config files : C:\Users\ak.xps15i9\a1\apps\miniforge3\.condarc
                          C:\Users\ak.xps15i9\.condarc
          conda version : 23.3.1
    conda-build version : 3.28.4
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.3=0
                          __win=0=0
       base environment : C:\Users\ak.xps15i9\a1\apps\miniforge3  (writable)
      conda av data dir : C:\Users\ak.xps15i9\a1\apps\miniforge3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/biocore/win-64
                          https://conda.anaconda.org/biocore/noarch
                          https://conda.anaconda.org/bioconda/win-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/biobuilds/win-64
                          https://conda.anaconda.org/biobuilds/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\ak.xps15i9\a1\apps\miniforge3\pkgs
                          C:\Users\ak.xps15i9\.conda\pkgs
                          C:\Users\ak.xps15i9\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\ak.xps15i9\a1\apps\miniforge3\envs
                          C:\Users\ak.xps15i9\.conda\envs
                          C:\Users\ak.xps15i9\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Windows/10 Windows/10.0.22631
          administrator : False
             netrc file : None
           offline mode : False

```
