### ISSUE TITLE
AttributeError: module 'libarchive' has no attribute 'extract'

### ISSUE THREAD

**Issue by mxmlnkn** [conda/conda-build#4992]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

conda build quits because of `AttributeError: module 'libarchive' has no attribute 'extract'`:

```python3
conda-build .
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for rapidgzip
INFO:conda_build.metadata:Attempting to finalize metadata for rapidgzip
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['rapidgzip-0.10.1-py311h2bc3f7f_0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/miniconda3/conda-bld/rapidgzip_1693864024036/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_


The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-main              
    _openmp_mutex:    5.1-1_gnu             
    bzip2:            1.0.8-h7b6447c_0      
    ca-certificates:  2023.05.30-h06a4308_0 
    cython:           3.0.0-py311h5eee18b_0 
    ld_impl_linux-64: 2.38-h1181459_1       
    libffi:           3.4.4-h6a678d5_0      
    libgcc-ng:        11.2.0-h1234567_1     
    libgomp:          11.2.0-h1234567_1     
    libstdcxx-ng:     11.2.0-h1234567_1     
    libuuid:          1.41.5-h5eee18b_0     
    ncurses:          6.4-h6a678d5_0        
    openssl:          3.0.10-h7f8727e_2     
    pip:              23.2.1-py311h06a4308_0
    python:           3.11.4-h955ad1f_0     
    readline:         8.2-h5eee18b_0        
    setuptools:       68.0.0-py311h06a4308_0
    sqlite:           3.41.2-h5eee18b_0     
    tk:               8.6.12-h1ccaba5_0     
    tzdata:           2023c-h04d1e81_0      
    wheel:            0.38.4-py311h06a4308_0
    xz:               5.4.2-h5eee18b_0      
    zlib:             1.2.13-h5eee18b_0     

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/miniconda3/conda-bld/rapidgzip_1693864024036/_build_env


The following NEW packages will be INSTALLED:

    _libgcc_mutex:                        0.1-main          
    _openmp_mutex:                        5.1-1_gnu         
    _sysroot_linux-64_curr_repodata_hack: 3-haa98f57_10     
    binutils_impl_linux-64:               2.38-h2a08ee3_1   
    binutils_linux-64:                    2.38.0-hc2dff05_0 
    gcc_impl_linux-64:                    11.2.0-h1234567_1 
    gcc_linux-64:                         11.2.0-h5c386dc_0 
    gxx_impl_linux-64:                    11.2.0-h1234567_1 
    gxx_linux-64:                         11.2.0-hc2dff05_0 
    kernel-headers_linux-64:              3.10.0-h57e8cba_10
    ld_impl_linux-64:                     2.38-h1181459_1   
    libgcc-devel_linux-64:                11.2.0-h1234567_1 
    libgcc-ng:                            11.2.0-h1234567_1 
    libgomp:                              11.2.0-h1234567_1 
    libstdcxx-devel_linux-64:             11.2.0-h1234567_1 
    libstdcxx-ng:                         11.2.0-h1234567_1 
    sysroot_linux-64:                     2.17-h57e8cba_10  

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Source cache directory is: /opt/miniconda3/conda-bld/src_cache
INFO:conda_build.source:Source cache directory is: /opt/miniconda3/conda-bld/src_cache
Downloading source to cache: rapidgzip-0.10.1_a166b86e7b.tar.gz
INFO:conda_build.source:Downloading source to cache: rapidgzip-0.10.1_a166b86e7b.tar.gz
Downloading https://pypi.io/packages/source/r/rapidgzip/rapidgzip-0.10.1.tar.gz
INFO:conda_build.source:Downloading https://pypi.io/packages/source/r/rapidgzip/rapidgzip-0.10.1.tar.gz
Success
INFO:conda_build.source:Success
Extracting download
Traceback (most recent call last):
  File "/opt/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/miniconda3/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 495, in main
    execute(sys.argv[1:])
  File "/opt/miniconda3/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 475, in execute
    outputs = api.build(
  File "/opt/miniconda3/lib/python3.10/site-packages/conda_build/api.py", line 180, in build
    return build_tree(
  File "/opt/miniconda3/lib/python3.10/site-packages/conda_build/build.py", line 3097, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/miniconda3/lib/python3.10/site-packages/conda_build/build.py", line 2136, in build
    try_download(m, no_download_source=False, raise_error=True)
  File "/opt/miniconda3/lib/python3.10/site-packages/conda_build/render.py", line 643, in try_download
    source.provide(metadata)
  File "/opt/miniconda3/lib/python3.10/site-packages/conda_build/source.py", line 853, in provide
    unpack(source_dict, src_dir, metadata.config.src_cache, recipe_path=metadata.path,
  File "/opt/miniconda3/lib/python3.10/site-packages/conda_build/source.py", line 153, in unpack
    tar_xf(src_path, tmpdir)
  File "/opt/miniconda3/lib/python3.10/site-packages/conda_build/utils.py", line 817, in tar_xf
    flags = libarchive.extract.EXTRACT_TIME | \
AttributeError: module 'libarchive' has no attribute 'extract'
```

I have also tested with 3.23.3. I was not able to downgrade much farther because of conflicts.

### Conda Info

```shell
active environment : base
    active env location : /opt/miniconda3
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.config/conda/condarc
          conda version : 23.7.3
    conda-build version : 3.26.1
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /opt/miniconda3  (writable)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.3 requests/2.31.0 CPython/3.10.12 Linux/5.15.0-76-generic ubuntu/22.04.2 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /home/user/.config/conda/condarc <==
anaconda_upload: False

==> cmd_line <==
debug: False
json: False
```

### Conda list

```shell
conda list --show-channel-urls
# packages in environment at /opt/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
beautifulsoup4            4.12.2          py310h06a4308_0    defaults
boltons                   23.0.0          py310h06a4308_0    defaults
brotlipy                  0.7.0           py310h7f8727e_1002    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2023.05.30           h06a4308_0    defaults
certifi                   2023.7.22       py310h06a4308_0    defaults
cffi                      1.15.1          py310h5eee18b_3    defaults
chardet                   4.0.0           py310h06a4308_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.4           py310h06a4308_0    defaults
conda                     23.7.3          py310h06a4308_0    defaults
conda-build               3.26.1          py310h06a4308_0    defaults
conda-content-trust       0.1.3           py310h06a4308_0    defaults
conda-index               0.2.3           py310h06a4308_0    defaults
conda-package-handling    2.2.0           py310h06a4308_0    defaults
conda-package-streaming   0.9.0           py310h06a4308_0    defaults
cryptography              41.0.2          py310h22a60cf_0    defaults
filelock                  3.9.0           py310h06a4308_0    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
icu                       73.1                 h6a678d5_0    defaults
idna                      3.4             py310h06a4308_0    defaults
jinja2                    3.1.2           py310h06a4308_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libarchive                3.6.2                h6ac8c49_2    defaults
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
liblief                   0.12.3               h6a678d5_0    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
libxml2                   2.10.4               hf1b16e4_1    defaults
lz4-c                     1.9.4                h6a678d5_0    defaults
markupsafe                2.1.1           py310h7f8727e_0    defaults
more-itertools            8.12.0             pyhd3eb1b0_0    defaults
ncurses                   6.4                  h6a678d5_0    defaults
openssl                   3.0.10               h7f8727e_2    defaults
packaging                 23.1            py310h06a4308_0    defaults
patch                     2.7.6             h7b6447c_1001    defaults
patchelf                  0.17.2               h6a678d5_0    defaults
pip                       22.3.1          py310h06a4308_0    defaults
pkginfo                   1.9.6           py310h06a4308_0    defaults
pluggy                    1.0.0           py310h06a4308_1    defaults
psutil                    5.9.0           py310h5eee18b_0    defaults
py-lief                   0.12.3          py310h6a678d5_0    defaults
pycosat                   0.6.4           py310h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.2.0          py310h06a4308_0    defaults
pysocks                   1.7.1           py310h06a4308_0    defaults
python                    3.10.12              h955ad1f_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
pytz                      2022.7          py310h06a4308_0    defaults
pyyaml                    6.0             py310h5eee18b_1    defaults
readline                  8.2                  h5eee18b_0    defaults
requests                  2.31.0          py310h06a4308_0    defaults
ruamel.yaml               0.17.21         py310h5eee18b_0    defaults
ruamel.yaml.clib          0.2.6           py310h5eee18b_1    defaults
setuptools                65.6.3          py310h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
soupsieve                 2.4             py310h06a4308_0    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
tomli                     2.0.1           py310h06a4308_0    defaults
toolz                     0.12.0          py310h06a4308_0    defaults
tqdm                      4.65.0          py310h2f386ee_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.16         py310h06a4308_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.4.2                h5eee18b_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstandard                 0.19.0          py310h5eee18b_0    defaults
zstd                      1.5.5                hc292b87_0    defaults
```

**Comment by mxmlnkn** [comment]
My bad, I had [python-libarchive](https://github.com/smartfile/python-libarchive) installed. After deinstalling that via pip uninstall, conda works. Feel free to close this issue.
