### ISSUE TITLE
Clone cached git repo to work repo fails with `fatal: Could not read from remote repository`

### ISSUE THREAD

**Issue by nicogodet** [conda/conda-build#5003]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

In `meta.yaml`, following source is defined : 
```yaml
source:
  - git_url: https://gitlab.pam-retd.fr/otm/telemac-mascaret.git
  - path: ../src
```
<details>
  <summary>Full meta.yaml</summary>
  
```yaml
{% set name = "telemac-mascaret" %}
{% set version = "v8p4r0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - git_url: https://gitlab.pam-retd.fr/otm/telemac-mascaret.git
  - path: ../src

build:
  number: 0
  # skip: true  # [not win]

requirements:
  build:
    - python <3.11
    - numpy <1.22.0
    - scipy <1.11
    - matplotlib
    - m2w64-gcc
    - m2w64-gcc-fortran
    - m2w64-toolchain
    - msmpi
    - msmpi-compilers
    - m2w64-metis
    - git-lfs
  run:
    - python <3.11
    - numpy <1.22.0
    - scipy <1.11
    - matplotlib
    - m2w64-gcc
    - m2w64-gcc-fortran
    - m2w64-toolchain
    - msmpi
    - msmpi-compilers
    - m2w64-metis

test:
  files:
    - tests/*  # [win]
  requires:
    - python <3.11
    - numpy <1.22.0
    - scipy <1.11
    - matplotlib
    - m2w64-gcc
    - m2w64-gcc-fortran
    - m2w64-toolchain
    - msmpi
    - msmpi-compilers
    - m2w64-metis
  commands:
    - python -m config
    - telemac-debug on
    - python -m config
    # - cd tests/malpasset
    # - python -m telemac2d --ncsize=8 t2d_malpasset-fine.cas

about:
  home: http://www.opentelemac.org/
  license: GPLv3
  summary: Telemac-Mascaret
  description: |
    The TELEMAC-MASCARET system is an integrated suite of solvers for use in the
    field of free-surface flow.
  doc_url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/
  dev_url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/

extra:
  recipe-maintainers:
    - nicogodet

```
  
</details>

Running `conda build .` fails with:
```
Cloning into 'D:\miniforge3\envs\build-telemac\conda-bld\telemac-mascaret_1694707076444\work'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was:
Command '['D:\\miniforge3\\envs\\build-telemac\\Library\\bin\\git.exe', 'clone', 'D:\\miniforge3\\envs\\build-telemac\\conda-bld\\git_cache\\gitlab.pam-retd.fr\\otm\\telemac-mascaret.git', 'D:
\\miniforge3\\envs\\build-telemac\\conda-bld\\telemac-mascaret_1694707076444\\work\\']' returned non-zero exit status 128.
```

<details>
  <summary>Full output</summary>
  
```console
(build-telemac) D:\DEV\LOCAL\opentelemac-mascaret-feedstock>conda build .
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
Adding in variants from internal_defaults
Attempting to finalize metadata for telemac-mascaret
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['telemac-mascaret-v8p4r0-py310_0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: D:\miniforge3\envs\build-telemac\conda-bld\telemac-mascaret_1694707076444\_h_env


The following NEW packages will be INSTALLED:

    appdirs:                        1.4.4-pyhd3eb1b0_0
    blas:                           1.0-mkl
    brotli:                         1.0.9-h2bbff1b_7
    brotli-bin:                     1.0.9-h2bbff1b_7
    brotlipy:                       0.7.0-py310h2bbff1b_1002
    bzip2:                          1.0.8-he774522_0
    ca-certificates:                2023.08.22-haa95532_0
    certifi:                        2023.7.22-py310haa95532_0
    cffi:                           1.15.1-py310h2bbff1b_3
    charset-normalizer:             2.0.4-pyhd3eb1b0_0
    contourpy:                      1.0.5-py310h59b6b97_0
    cryptography:                   41.0.3-py310h89fc84f_0
    cycler:                         0.11.0-pyhd3eb1b0_0
    fonttools:                      4.25.0-pyhd3eb1b0_0
    freetype:                       2.12.1-ha860e81_0
    giflib:                         5.2.1-h8cc25b3_3
    git-lfs:                        2.13.3-haa95532_0
    glib:                           2.69.1-h5dc1a3c_2
    icc_rt:                         2022.1.0-h6049295_2
    icu:                            58.2-ha925a31_3
    idna:                           3.4-py310haa95532_0
    intel-openmp:                   2023.1.0-h59b6b97_46319
    jpeg:                           9e-h2bbff1b_1
    kiwisolver:                     1.4.4-py310hd77b12b_0
    krb5:                           1.20.1-h5b6d351_0
    lerc:                           3.0-hd77b12b_0
    libbrotlicommon:                1.0.9-h2bbff1b_7
    libbrotlidec:                   1.0.9-h2bbff1b_7
    libbrotlienc:                   1.0.9-h2bbff1b_7
    libclang:                       14.0.6-default_hb5a9fac_1
    libclang13:                     14.0.6-default_h8e68704_1
    libdeflate:                     1.17-h2bbff1b_0
    libffi:                         3.4.4-hd77b12b_0
    libiconv:                       1.16-h2bbff1b_2
    libpng:                         1.6.39-h8cc25b3_0
    libpq:                          12.15-h906ac69_1
    libtiff:                        4.5.1-hd77b12b_0
    libwebp:                        1.2.4-hbc33d0d_1
    libwebp-base:                   1.2.4-h2bbff1b_1
    libxml2:                        2.10.4-h0ad7f3c_1
    libxslt:                        1.1.37-h2bbff1b_1
    lz4-c:                          1.9.4-h2bbff1b_0
    m2w64-binutils:                 2.25.1-5
    m2w64-bzip2:                    1.0.6-6
    m2w64-crt-git:                  5.0.0.4636.2595836-2
    m2w64-gcc:                      5.3.0-6
    m2w64-gcc-ada:                  5.3.0-6
    m2w64-gcc-fortran:              5.3.0-6
    m2w64-gcc-libgfortran:          5.3.0-6
    m2w64-gcc-libs:                 5.3.0-7
    m2w64-gcc-libs-core:            5.3.0-7
    m2w64-gcc-objc:                 5.3.0-6
    m2w64-gmp:                      6.1.0-2
    m2w64-headers-git:              5.0.0.4636.c0ad18a-2
    m2w64-isl:                      0.16.1-2
    m2w64-libiconv:                 1.14-6
    m2w64-libmangle-git:            5.0.0.4509.2e5a9a2-2
    m2w64-libwinpthread-git:        5.0.0.4634.697f757-2
    m2w64-make:                     4.1.2351.a80a8b8-2
    m2w64-metis:                    5.1.0-1
    m2w64-mpc:                      1.0.3-3
    m2w64-mpfr:                     3.1.4-4
    m2w64-pkg-config:               0.29.1-2
    m2w64-toolchain:                5.3.0-7
    m2w64-tools-git:                5.0.0.4592.90b8472-2
    m2w64-windows-default-manifest: 6.4-3
    m2w64-winpthreads-git:          5.0.0.4634.697f757-2
    m2w64-zlib:                     1.2.8-10
    matplotlib:                     3.7.2-py310haa95532_0
    matplotlib-base:                3.7.2-py310h4ed8f06_0
    mkl:                            2023.1.0-h6b88ed4_46357
    mkl-service:                    2.4.0-py310h2bbff1b_1
    mkl_fft:                        1.3.6-py310h4ed8f06_1
    mkl_random:                     1.2.2-py310h4ed8f06_1
    mpi:                            1.0-msmpi
    msmpi:                          10.1.1-had4844c_0
    msmpi-compilers:                10.1.2-hf4a77e7_1         nicogodet
    msys2-conda-epoch:              20160418-1
    munkres:                        1.1.4-py_0
    numpy:                          1.21.5-py310h85e1a82_4
    numpy-base:                     1.21.5-py310hb5c95e7_4
    openssl:                        3.0.10-h2bbff1b_2
    packaging:                      23.1-py310haa95532_0
    pcre:                           8.45-hd77b12b_0
    pillow:                         9.4.0-py310hd77b12b_0
    pip:                            23.2.1-py310haa95532_0
    ply:                            3.11-py310haa95532_0
    pooch:                          1.4.0-pyhd3eb1b0_0
    pycparser:                      2.21-pyhd3eb1b0_0
    pyopenssl:                      23.2.0-py310haa95532_0
    pyparsing:                      3.0.9-py310haa95532_0
    pyqt:                           5.15.7-py310hd77b12b_0
    pyqt5-sip:                      12.11.0-py310hd77b12b_0
    pysocks:                        1.7.1-py310haa95532_0
    python:                         3.10.13-he1021f5_0
    python-dateutil:                2.8.2-pyhd3eb1b0_0
    qt-main:                        5.15.2-h879a1e9_9
    qt-webengine:                   5.15.9-h5bd16bc_7
    qtwebkit:                       5.212-h2bbfb41_5
    requests:                       2.31.0-py310haa95532_0
    scipy:                          1.10.1-py310h309d312_1
    setuptools:                     68.0.0-py310haa95532_0
    sip:                            6.6.2-py310hd77b12b_0
    six:                            1.16.0-pyhd3eb1b0_1
    sqlite:                         3.41.2-h2bbff1b_0
    tbb:                            2021.8.0-h59b6b97_0
    tk:                             8.6.12-h2bbff1b_0
    toml:                           0.10.2-pyhd3eb1b0_0
    tornado:                        6.3.2-py310h2bbff1b_0
    tzdata:                         2023c-h04d1e81_0
    urllib3:                        1.26.16-py310haa95532_0
    vc:                             14.2-h21ff451_1
    vs2015_runtime:                 14.27.29016-h5e58377_2
    wheel:                          0.38.4-py310haa95532_0
    win_inet_pton:                  1.1.0-py310haa95532_0
    xz:                             5.4.2-h8cc25b3_0
    zlib:                           1.2.13-h8cc25b3_0
    zstd:                           1.5.5-hd43e919_0

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 11 (delta 10), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), 1.97 KiB | 28.00 KiB/s, done.
From https://gitlab.pam-retd.fr/otm/telemac-mascaret
 * [new ref]                        -> _conda_cache_origin_head
Cloning into 'D:\miniforge3\envs\build-telemac\conda-bld\telemac-mascaret_1694707076444\work'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was:
Command '['D:\\miniforge3\\envs\\build-telemac\\Library\\bin\\git.exe', 'clone', 'D:\\miniforge3\\envs\\build-telemac\\conda-bld\\git_cache\\gitlab.pam-retd.fr\\otm\\telemac-mascaret.git', 'D:
\\miniforge3\\envs\\build-telemac\\conda-bld\\telemac-mascaret_1694707076444\\work\\']' returned non-zero exit status 128.

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\miniforge3\envs\build-telemac\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "D:\miniforge3\envs\build-telemac\Lib\site-packages\conda\cli\main.py", line 64, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "D:\miniforge3\envs\build-telemac\Lib\site-packages\conda\cli\conda_argparse.py", line 143, in do_call
        result = plugin_subcommand.action(getattr(args, "_args", args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\miniforge3\envs\build-telemac\Lib\site-packages\conda_build\plugin.py", line 10, in build
        execute(*args, **kwargs)
      File "D:\miniforge3\envs\build-telemac\Lib\site-packages\conda_build\cli\main_build.py", line 568, in execute
        outputs = api.build(
                  ^^^^^^^^^^
      File "D:\miniforge3\envs\build-telemac\Lib\site-packages\conda_build\api.py", line 253, in build
        return build_tree(
               ^^^^^^^^^^^
      File "D:\miniforge3\envs\build-telemac\Lib\site-packages\conda_build\build.py", line 3804, in build_tree
        packages_from_this = build(
                             ^^^^^^
      File "D:\miniforge3\envs\build-telemac\Lib\site-packages\conda_build\build.py", line 2587, in build
        try_download(m, no_download_source=False, raise_error=True)
      File "D:\miniforge3\envs\build-telemac\Lib\site-packages\conda_build\render.py", line 774, in try_download
        raise RuntimeError(
    RuntimeError: Failed to download or patch source. Please see build log for info.

`$ D:\miniforge3\envs\build-telemac\Scripts\conda-script.py build .`

  environment variables:
                 CIO_TEST=<not set>
                  CMDPATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\Sys
                          tem32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program
                          Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\User
                          s\godet\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\gode
                          t\AppData\Local\Programs\Python\Python311\;C:\Users\godet\AppData\Loca
                          l\Programs\Python\Python39\Scripts\;C:\Users\godet\AppData\Local\Progr
                          ams\Python\Python39\;C:\Users\godet\AppData\Local\Microsoft\WindowsApp
                          s;C:\Users\godet\AppData\Local\GitHubDesktop\bin;C:\Users\godet\AppDat
                          a\Local\Programs\Microsoft VS Code\bin;C:\Windows\sysnative\;C:\Users\
                          godet\AppData\Roaming\MobaXterm\slash\mx86_64b\bin
    CONDA_ALLOW_SOFTLINKS=false
        CONDA_DEFAULT_ENV=build-telemac
                CONDA_EXE=D:\miniforge3\envs\build-telemac\condabin\..\Scripts\conda.exe
               CONDA_EXES="D:\miniforge3\envs\build-telemac\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=D:\miniforge3\envs\build-telemac
           CONDA_PREFIX_1=D:\miniforge3
    CONDA_PROMPT_MODIFIER=(build-telemac)
         CONDA_PYTHON_EXE=D:\miniforge3\python.exe
               CONDA_ROOT=D:\miniforge3\envs\build-telemac
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\godet
          LD_LIBRARY_PATH=C:\Users\godet\AppData\Roaming\MobaXterm\slash\mx86_64b\bin
               LD_PRELOAD=<not set>
                     PATH=D:\miniforge3\envs\build-telemac;D:\miniforge3\envs\build-
                          telemac\Library\mingw-w64\bin;D:\miniforge3\envs\build-
                          telemac\Library\usr\bin;D:\miniforge3\envs\build-
                          telemac\Library\bin;D:\miniforge3\envs\build-
                          telemac\Scripts;D:\miniforge3\envs\build-telemac\bin;D:\miniforge3\con
                          dabin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windo
                          ws\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Prog
                          ram Files\dotnet;C:\Program Files\Git\cmd;C:\Program Files\PuTTY;C:\Us
                          ers\godet\AppData\Local\Programs\Python\Python311\Scripts;C:\Users\god
                          et\AppData\Local\Programs\Python\Python311;C:\Users\godet\AppData\Loca
                          l\Programs\Python\Python39\Scripts;C:\Users\godet\AppData\Local\Progra
                          ms\Python\Python39;C:\Users\godet\AppData\Local\Microsoft\WindowsApps;
                          C:\Users\godet\AppData\Local\GitHubDesktop\bin;C:\Users\godet\AppData\
                          Local\Programs\Microsoft VS Code\bin;C:\Windows\sysnative;C:\Users\god
                          et\AppData\Roaming\MobaXterm\slash\mx86_64b\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
               PYTHONUTF8=1
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=D:\miniforge3\envs\build-telemac\Library\ssl\cacert.pem
                  WINPATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\Sys
                          tem32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program
                          Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\User
                          s\godet\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\gode
                          t\AppData\Local\Programs\Python\Python311\;C:\Users\godet\AppData\Loca
                          l\Programs\Python\Python39\Scripts\;C:\Users\godet\AppData\Local\Progr
                          ams\Python\Python39\;C:\Users\godet\AppData\Local\Microsoft\WindowsApp
                          s;C:\Users\godet\AppData\Local\GitHubDesktop\bin;C:\Users\godet\AppDat
                          a\Local\Programs\Microsoft VS Code\bin;C:\Windows\sysnative\

     active environment : base
    active env location : D:\miniforge3\envs\build-telemac
            shell level : 2
       user config file : C:\Users\godet\.condarc
 populated config files : C:\Users\godet\.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : D:\miniforge3\envs\build-telemac  (writable)
      conda av data dir : D:\miniforge3\envs\build-telemac\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/nicogodet/win-64
                          https://conda.anaconda.org/nicogodet/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\miniforge3\envs\build-telemac\pkgs
                          C:\Users\godet\.conda\pkgs
                          C:\Users\godet\AppData\Local\conda\conda\pkgs
       envs directories : D:\miniforge3\envs\build-telemac\envs
                          C:\Users\godet\.conda\envs
                          C:\Users\godet\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

```

</details>

Note: This repo use git-lfs but it fails with same error on another repo not using lfs...

### Conda Info

```shell
(build-telemac) D:\DEV\LOCAL\opentelemac-mascaret-feedstock>conda info

     active environment : base
    active env location : D:\miniforge3\envs\build-telemac
            shell level : 2
       user config file : C:\Users\godet\.condarc
 populated config files : C:\Users\godet\.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : D:\miniforge3\envs\build-telemac  (writable)
      conda av data dir : D:\miniforge3\envs\build-telemac\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/nicogodet/win-64
                          https://conda.anaconda.org/nicogodet/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\miniforge3\envs\build-telemac\pkgs
                          C:\Users\godet\.conda\pkgs
                          C:\Users\godet\AppData\Local\conda\conda\pkgs
       envs directories : D:\miniforge3\envs\build-telemac\envs
                          C:\Users\godet\.conda\envs
                          C:\Users\godet\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
(build-telemac) D:\DEV\LOCAL\opentelemac-mascaret-feedstock>conda config --show-sources
==> C:\Users\godet\.condarc <==
ssl_verify: True
channels:
  - nicogodet
  - defaults
report_errors: False

==> cmd_line <==
debug: False
json: False
```

### Conda list

```shell
(build-telemac) D:\DEV\LOCAL\opentelemac-mascaret-feedstock>conda list --show-channel-urls
# packages in environment at D:\miniforge3\envs\build-telemac:
#
# Name                    Version                   Build  Channel
backports                 1.1                pyhd3eb1b0_0    defaults
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0    defaults
backports.tempfile        1.0                pyhd3eb1b0_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.12.2          py311haa95532_0    defaults
boltons                   23.0.0          py311haa95532_0    defaults
brotlipy                  0.7.0           py311h2bbff1b_1002    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2023.08.22           haa95532_0    defaults
certifi                   2023.7.22       py311haa95532_0    defaults
cffi                      1.15.1          py311h2bbff1b_3    defaults
chardet                   4.0.0           py311haa95532_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.4           py311haa95532_0    defaults
colorama                  0.4.6           py311haa95532_0    defaults
conda                     23.7.4          py311haa95532_0    defaults
conda-build               3.26.1          py311haa95532_0    defaults
conda-index               0.2.3           py311haa95532_0    defaults
conda-package-handling    2.2.0           py311haa95532_0    defaults
conda-package-streaming   0.9.0           py311haa95532_0    defaults
conda-verify              3.4.2                      py_1    defaults
cryptography              41.0.3          py311h89fc84f_0    defaults
filelock                  3.9.0           py311haa95532_0    defaults
future                    0.18.3          py311haa95532_0    defaults
git                       2.40.1               haa95532_1    defaults
git-lfs                   2.13.3               haa95532_0    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
idna                      3.4             py311haa95532_0    defaults
jinja2                    3.1.2           py311haa95532_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
libarchive                3.6.2                hb62f4d4_2    defaults
libffi                    3.4.4                hd77b12b_0    defaults
libiconv                  1.16                 h2bbff1b_2    defaults
liblief                   0.12.3               hd77b12b_0    defaults
libxml2                   2.10.4               h0ad7f3c_1    defaults
lz4-c                     1.9.4                h2bbff1b_0    defaults
m2-msys2-runtime          2.5.0.17080.65c939c               3    defaults
m2-patch                  2.7.5                         2    defaults
markupsafe                2.1.1           py311h2bbff1b_0    defaults
menuinst                  1.4.19          py311h59b6b97_1    defaults
more-itertools            8.12.0             pyhd3eb1b0_0    defaults
msys2-conda-epoch         20160418                      1    defaults
openssl                   3.0.10               h2bbff1b_2    defaults
packaging                 23.1            py311haa95532_0    defaults
pip                       23.2.1          py311haa95532_0    defaults
pkginfo                   1.9.6           py311haa95532_0    defaults
pluggy                    1.0.0           py311haa95532_1    defaults
psutil                    5.9.0           py311h2bbff1b_0    defaults
py-lief                   0.12.3          py311hd77b12b_0    defaults
pycosat                   0.6.4           py311h2bbff1b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.2.0          py311haa95532_0    defaults
pysocks                   1.7.1           py311haa95532_0    defaults
python                    3.11.5               he1021f5_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
pytz                      2022.7          py311haa95532_0    defaults
pyyaml                    6.0             py311h2bbff1b_1    defaults
requests                  2.31.0          py311haa95532_0    defaults
ruamel.yaml               0.17.21         py311h2bbff1b_0    defaults
setuptools                68.0.0          py311haa95532_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
soupsieve                 2.4             py311haa95532_0    defaults
sqlite                    3.41.2               h2bbff1b_0    defaults
tk                        8.6.12               h2bbff1b_0    defaults
toolz                     0.12.0          py311haa95532_0    defaults
tqdm                      4.65.0          py311h746a85d_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.16         py311haa95532_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wheel                     0.38.4          py311haa95532_0    defaults
win_inet_pton             1.1.0           py311haa95532_0    defaults
xz                        5.4.2                h8cc25b3_0    defaults
yaml                      0.2.5                he774522_0    defaults
zlib                      1.2.13               h8cc25b3_0    defaults
zstandard                 0.19.0          py311h2bbff1b_0    defaults
zstd                      1.5.5                hd43e919_0    defaults
```

**Comment by nicogodet** [comment]
When running in miniforge prompt:
![image](https://github.com/conda/conda-build/assets/39594821/134d55e9-c1c3-42df-876c-502bbf8333af)

missing __locale_ctype_ptr in dll for sh.exe

First attempt was in cmd embedded in Mobaxterm, no pop up

**Comment by nicogodet** [comment]
Installing `m2-base` seems to solve this issue.

A mention in doc could be useful.
