### ISSUE TITLE
matchspec issue during test

### ISSUE THREAD

**Issue by dfroger** [conda/conda-build#501]
Hello,

I'm trying to package a library that depends on sympy, for Python 2.7* .

With this [recipe](https://github.com/dfroger/issue/tree/fd0d979d2fee89e45587476835e628f11280cfef/conda-build-matchspec) and this `conda` installation:

    $ conda info
    Current conda install:

                 platform : linux-64
            conda version : 3.15.0
      conda-build version : 1.15.0
           python version : 2.7.10.final.0
         requests version : 2.7.0
         root environment : /home/david/miniconda  (writable)
      default environment : /home/david/miniconda
         envs directories : /home/david/miniconda/envs
            package cache : /home/david/miniconda/pkgs
             channel URLs : https://conda.anaconda.org/dfroger/linux-64/
                            https://conda.anaconda.org/dfroger/noarch/
                            https://repo.continuum.io/pkgs/free/linux-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/linux-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : /home/david/.condarc
        is foreign system : False

I get the error message when trying `conda build .`:

    (...)

    BUILD END: toto-0.1.0-py27_0
    TEST START: toto-0.1.0-py27_0
    Fetching package metadata: ........
    Solving package specifications: .An unexpected error has occurred, please consider sending the
    following traceback to the conda GitHub issue tracker at:

        https://github.com/conda/conda-build/issues

    Include the output of the command 'conda info' in your report.

    Traceback (most recent call last):
      File "/home/david/miniconda/bin/conda-build", line 5, in <module>
        sys.exit(main())
      File "/home/david/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 173, in main
        args_func(args, p)
      File "/home/david/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 400, in args_func
        args.func(args, p)
      File "/home/david/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 387, in execute
        channel_urls=channel_urls, override_channels=args.override_channels)
      File "/home/david/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 492, in test
        channel_urls=channel_urls, override_channels=override_channels)
      File "/home/david/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 260, in create_env
        actions = plan.install_actions(prefix, index, specs)
      File "/home/david/miniconda/lib/python2.7/site-packages/conda/plan.py", line 397, in install_actions
        config.track_features, minimal_hint=minimal_hint):
      File "/home/david/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 739, in solve
        minimal_hint=minimal_hint)
      File "/home/david/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 484, in solve2
        clauses = set(self.gen_clauses(v, dists, specs, features))
      File "/home/david/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 342, in gen_clauses
        assert len(clause) > 1, '%s %r' % (fn1, ms)
    AssertionError: sympy-0.7.6-py27_0.tar.bz2 MatchSpec(u'fastcache')

Thanks,
David

**Comment by asmeurer** [comment]
When you specify an exact version of a package, you have to specify the exact versions of all its dependencies as well. Unless you really do want that exact build, I recommend leaving out the 2.7 restrictions and just building the package with `conda build --python 2.7`.

**Comment by dfroger** [comment]
Perfect, thanks a lot!
