### ISSUE TITLE
extend_key and zip_key combination causes an exception

### ISSUE THREAD

**Issue by danpetry** [conda/conda-build#5048]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I defined a key (`CONDA_BUILD_SYSROOT`) as an extend_key, in both the higher-priority (recipe) and lower-priority (aggregate) cbc.yaml, and also as a zip_key in the higher priority one. The key, after having been extended from the lower-priority cbc.yaml, should have had the same number of values as the other keys with which it was being zipped. Conda-build threw an exception however:
```
Traceback (most recent call last):
  File "/Users/dpetry/miniconda3/envs/pkg_build/bin/conda-build", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/dpetry/miniconda3/envs/pkg_build/lib/python3.11/site-packages/conda_build/deprecations.py", line 70, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpetry/miniconda3/envs/pkg_build/lib/python3.11/site-packages/conda_build/cli/main_build.py", line 589, in main
    execute(sys.argv[1:])
  File "/Users/dpetry/miniconda3/envs/pkg_build/lib/python3.11/site-packages/conda_build/cli/main_build.py", line 568, in execute
    outputs = api.build(
              ^^^^^^^^^^
  File "/Users/dpetry/miniconda3/envs/pkg_build/lib/python3.11/site-packages/conda_build/api.py", line 253, in build
    return build_tree(
           ^^^^^^^^^^^
  File "/Users/dpetry/miniconda3/envs/pkg_build/lib/python3.11/site-packages/conda_build/build.py", line 3777, in build_tree
    metadata_tuples = render_recipe(
                      ^^^^^^^^^^^^^^
  File "/Users/dpetry/miniconda3/envs/pkg_build/lib/python3.11/site-packages/conda_build/render.py", line 1001, in render_recipe
    variants = get_package_variants(m, variants=variants)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpetry/miniconda3/envs/pkg_build/lib/python3.11/site-packages/conda_build/variants.py", line 696, in get_package_variants
    combined_spec, specs = get_package_combined_spec(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpetry/miniconda3/envs/pkg_build/lib/python3.11/site-packages/conda_build/variants.py", line 665, in get_package_combined_spec
    validate_spec(f, spec)
  File "/Users/dpetry/miniconda3/envs/pkg_build/lib/python3.11/site-packages/conda_build/variants.py", line 187, in validate_spec
    raise ValueError(
ValueError: Variant configuration errors in /Users/dpetry/Sandbox/aggregate/pytorch-feedstock/recipe/conda_build_config.yaml:
  zip fields in zip_key group frozenset({'MACOSX_SDK_VERSION', 'CONDA_BUILD_SYSROOT', 'pytorch_variant'}) are not all the same length
``` 

### Conda Info

```shell
active environment : pkg_build
    active env location : /Users/dpetry/miniconda3/envs/pkg_build
            shell level : 2
       user config file : /Users/dpetry/.condarc
 populated config files : /Users/dpetry/.condarc
          conda version : 23.9.0
    conda-build version : not installed
         python version : 3.9.18.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.6=0
                          __unix=0=0
       base environment : /Users/dpetry/miniconda3  (writable)
      conda av data dir : /Users/dpetry/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/dpetry/Sandbox/distro-incubator/cbousseau/bin/pkgs_cache
       envs directories : /Users/dpetry/miniconda3/envs
                          /Users/dpetry/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.9.0 requests/2.28.1 CPython/3.9.18 Darwin/22.6.0 OSX/13.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /Users/dpetry/.condarc <==
pkgs_dirs:
  - /Users/dpetry/Sandbox/distro-incubator/cbousseau/bin/pkgs_cache
channels:
  - defaults
use_only_tar_bz2: False
report_errors: True
unsatisfiable_hints: True
conda_build:
  matrix_base_dir: ~/Sandbox/automated-build/c3i_configurations/anaconda_public
```

### Conda list

```shell
# packages in environment at /Users/dpetry/miniconda3/envs/pkg_build:
#
# Name                    Version                   Build  Channel
beautifulsoup4            4.12.2          py311hca03da5_0    defaults
boltons                   23.0.0          py311hca03da5_0    defaults
brotlipy                  0.7.0           py311h80987f9_1002    defaults
bzip2                     1.0.8                h620ffc9_4    defaults
c-ares                    1.19.1               h80987f9_0    defaults
ca-certificates           2023.08.22           hca03da5_0    defaults
cctools                   949.0.1             hc179dcd_25    defaults
cctools_osx-arm64         949.0.1             h332cad3_25    defaults
certifi                   2023.7.22       py311hca03da5_0    defaults
cffi                      1.15.1          py311h80987f9_3    defaults
chardet                   4.0.0           py311hca03da5_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.4           py311hca03da5_0    defaults
conda                     23.7.4          py311hca03da5_0    defaults
conda-build               3.26.1          py311hca03da5_0    defaults
conda-index               0.3.0           py311hca03da5_0    defaults
conda-libmamba-solver     23.9.3          py311hca03da5_0    defaults
conda-package-handling    2.2.0           py311hca03da5_0    defaults
conda-package-streaming   0.9.0           py311hca03da5_0    defaults
cryptography              41.0.3          py311hd4332d6_0    defaults
filelock                  3.9.0           py311hca03da5_0    defaults
fmt                       9.1.0                h48ca7d4_0    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
icu                       73.1                 h313beb8_0    defaults
idna                      3.4             py311hca03da5_0    defaults
jinja2                    3.1.2           py311hca03da5_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
krb5                      1.20.1               hf3e1bf2_1    defaults
ld64                      530                 hb29bf3f_25    defaults
ld64_osx-arm64            530                 h001ce53_25    defaults
ldid                      2.1.5                h20b2a84_3    defaults
libarchive                3.6.2                h62fee54_2    defaults
libcurl                   8.4.0                h3e2b118_0    defaults
libcxx                    14.0.6               h848a8c0_0    defaults
libedit                   3.1.20221030         h80987f9_0    defaults
libev                     4.33                 h1a28f6b_1    defaults
libffi                    3.4.4                hca03da5_0    defaults
libiconv                  1.16                 h1a28f6b_2    defaults
liblief                   0.12.3               h313beb8_0    defaults
libllvm14                 14.0.6               h7ec7a93_3    defaults
libmamba                  1.5.1                h15e39b3_0    defaults
libmambapy                1.5.1           py311h1c5506f_0    defaults
libnghttp2                1.57.0               h62f6fdd_0    defaults
libsolv                   0.7.24               h514c7bf_0    defaults
libssh2                   1.10.0               h02f6b3c_2    defaults
libxml2                   2.10.4               h0dcf63f_1    defaults
lz4-c                     1.9.4                h313beb8_0    defaults
markupsafe                2.1.1           py311h80987f9_0    defaults
more-itertools            8.12.0             pyhd3eb1b0_0    defaults
ncurses                   6.4                  h313beb8_0    defaults
openssl                   3.0.11               h1a28f6b_2    defaults
packaging                 23.1            py311hca03da5_0    defaults
patch                     2.7.6             h1a28f6b_1001    defaults
pcre2                     10.42                hb066dcc_0    defaults
pip                       23.2.1          py311hca03da5_0    defaults
pkginfo                   1.9.6           py311hca03da5_0    defaults
pluggy                    1.0.0           py311hca03da5_1    defaults
psutil                    5.9.0           py311h80987f9_0    defaults
py-lief                   0.12.3          py311h313beb8_0    defaults
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.4           py311h80987f9_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.2.0          py311hca03da5_0    defaults
pysocks                   1.7.1           py311hca03da5_0    defaults
python                    3.11.5               hb885b13_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
pytz                      2023.3.post1    py311hca03da5_0    defaults
pyyaml                    6.0             py311h80987f9_1    defaults
readline                  8.2                  h1a28f6b_0    defaults
reproc                    14.2.4               hc377ac9_1    defaults
reproc-cpp                14.2.4               hc377ac9_1    defaults
requests                  2.31.0          py311hca03da5_0    defaults
ruamel.yaml               0.17.21         py311h80987f9_0    defaults
setuptools                68.0.0          py311hca03da5_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
soupsieve                 2.4             py311hca03da5_0    defaults
sqlite                    3.41.2               h80987f9_0    defaults
tapi                      1100.0.11            h8754e6a_1    defaults
tk                        8.6.12               hb8d0fd4_0    defaults
toolz                     0.12.0          py311hca03da5_0    defaults
tqdm                      4.65.0          py311hb6e6a13_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.16         py311hca03da5_0    defaults
wheel                     0.41.2          py311hca03da5_0    defaults
xz                        5.4.2                h80987f9_0    defaults
yaml                      0.2.5                h1a28f6b_0    defaults
yaml-cpp                  0.7.0                hc377ac9_1    defaults
zlib                      1.2.13               h5a0b063_0    defaults
zstandard                 0.19.0          py311h80987f9_0    defaults
zstd                      1.5.5                hd90d995_0    defaults
```

**Comment by danpetry** [comment]
thanks for the reminder. This remains an issue as far as I know
