### ISSUE TITLE
`conda build --help` fails

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#507]
Seems to be a simple issue of an argument (directory) missing from `listdir()`.

The version that I am using.

    $ conda build --version
    conda-build 1.15.0

Here is the traceback.

    $ conda build --help
    Traceback (most recent call last):
      File "/zopt/conda/bin/conda-build", line 5, in <module>
        sys.exit(main())
      File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_build.py", line 172, in main
        args = p.parse_args()
      File "/zopt/conda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 167, in parse_args
        return super(ArgumentParser, self).parse_args(*args, **kwargs)
      File "/zopt/conda/lib/python2.7/argparse.py", line 1701, in parse_args
        args, argv = self.parse_known_args(args, namespace)
      File "/zopt/conda/lib/python2.7/argparse.py", line 1733, in parse_known_args
        namespace, args = self._parse_known_args(args, namespace)
      File "/zopt/conda/lib/python2.7/argparse.py", line 1939, in _parse_known_args
        start_index = consume_optional(start_index)
      File "/zopt/conda/lib/python2.7/argparse.py", line 1879, in consume_optional
        take_action(action, args, option_string)
      File "/zopt/conda/lib/python2.7/argparse.py", line 1807, in take_action
        action(self, namespace, argument_values, option_string)
      File "/zopt/conda/lib/python2.7/argparse.py", line 996, in __call__
        parser.print_help()
      File "/zopt/conda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 157, in print_help
        super(ArgumentParser, self).print_help()
      File "/zopt/conda/lib/python2.7/argparse.py", line 2340, in print_help
        self._print_message(self.format_help(), file)
      File "/zopt/conda/lib/python2.7/argparse.py", line 2314, in format_help
        return formatter.format_help()
      File "/zopt/conda/lib/python2.7/argparse.py", line 281, in format_help
        help = self._root_section.format_help()
      File "/zopt/conda/lib/python2.7/argparse.py", line 211, in format_help
        func(*args)
      File "/zopt/conda/lib/python2.7/argparse.py", line 211, in format_help
        func(*args)
      File "/zopt/conda/lib/python2.7/argparse.py", line 517, in _format_action
        help_text = self._expand_help(action)
      File "/zopt/conda/lib/python2.7/argparse.py", line 601, in _expand_help
        choices_str = ', '.join([str(c) for c in params['choices']])
      File "/zopt/conda/lib/python2.7/site-packages/conda/cli/common.py", line 47, in __iter__
        return iter(self.get_items())
      File "/zopt/conda/lib/python2.7/site-packages/conda/utils.py", line 142, in __call__
        res = cache[key] = self.func(*args, **kw)
      File "/zopt/conda/lib/python2.7/site-packages/conda/cli/common.py", line 39, in get_items
        return self._get_items()
      File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_build.py", line 34, in _get_items
        for path in listdir():
    TypeError: listdir() takes exactly 1 argument (0 given)

**Comment by jakirkham** [comment]
I think this is fixed in master. Could someone confirm?

**Comment by jakirkham** [comment]
Nevermind, dup ( https://github.com/conda/conda-build/issues/502 )
