### ISSUE TITLE
ENH: Wheels support for `conda skeleton pypi`

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#510]
To demonstrate this, try the following.

```
$ conda skeleton pypi sphinxcontrib-argdoc
Warning, the following versions were found for sphinxcontrib-argdoc
0.1.3
0.1.2
0.1.1
Using 0.1.3
Use --version to specify a different version.
Using url http://pypi.python.org/pypi/sphinxcontrib-argdoc (0 B) for sphinxcontrib-argdoc.
Downloading sphinxcontrib-argdoc
Unpacking sphinxcontrib-argdoc...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/zopt/conda/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 272, in main
    args_func(args, p)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_build.py", line 400, in args_func
    args.func(args, p)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 286, in execute
    pypi.main(args, parser)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/pypi.py", line 341, in main
    get_package_metadata(args, package, d, data)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/pypi.py", line 478, in get_package_metadata
    python_version=args.python_version)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/pypi.py", line 734, in get_pkginfo
    unpack(join(SRC_CACHE, filename), tempdir)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/pypi.py", line 669, in unpack
    raise Exception("not a valid source")
Exception: not a valid source
```

Here is my version info.

```
$ conda --version && conda build --version
conda 3.15.1
conda-build 1.15.0
```

**Comment by asmeurer** [comment]
More specifically, when there is only a wheel. conda skeleton pypi only knows how to work with sdists.

**Comment by jakirkham** [comment]
Understood, I don't that it is worthwhile to try and add support for eggs. I'll close this off unless you think otherwise. However, I do think it is worthwhile to take a look at this ( https://github.com/conda/conda-build/issues/511 ).

**Comment by asmeurer** [comment]
I'm not saying that we shouldn't try to support them. Just that the support isn't there yet.

**Comment by jakirkham** [comment]
Ok, sorry. I have rephrased the title to better capture that this isn't a bug, but a needed feature.
