### ISSUE TITLE
Using `conda pipbuild` fails when wheel is present

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#511]
```
$ conda pipbuild sphinxcontrib-argdoc
Package search: {'_pypi_ordering': False, 'version': '0.1.3', 'name': 'sphinxcontrib-argdoc', 'summary': 'Sphinx "argdoc" extension'}
Creating standard recipe for sphinxcontrib-argdoc-0.1.3
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Using url http://pypi.python.org/pypi/sphinxcontrib-argdoc (0 B) for sphinxcontrib-argdoc.
Downloading sphinxcontrib-argdoc
Unpacking sphinxcontrib-argdoc...
Traceback (most recent call last):
  File "/zopt/conda/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 272, in main
    args_func(args, p)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_build.py", line 400, in args_func
    args.func(args, p)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 286, in execute
    pypi.main(args, parser)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/pypi.py", line 341, in main
    get_package_metadata(args, package, d, data)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/pypi.py", line 478, in get_package_metadata
    python_version=args.python_version)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/pypi.py", line 734, in get_pkginfo
    unpack(join(SRC_CACHE, filename), tempdir)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/pypi.py", line 669, in unpack
    raise Exception("not a valid source")
Exception: not a valid source

conda create -n _pipbuild_ --yes python pip
Error: prefix already exists: /zopt/conda/envs/_pipbuild_
/zopt/conda/envs/nanshenv/envs/_pipbuild_/bin/pip install sphinxcontrib-argdoc==0.1.3
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/zopt/conda/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 80, in main
    args_func(args, p)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_build.py", line 400, in args_func
    args.func(args, p)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 360, in execute
    build_package(package, version, noarch_python=args.noarch_python)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 304, in build_package
    noarch_python=noarch_python)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 240, in make_recipe
    depends = get_all_dependencies(package, version)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 208, in get_all_dependencies
    ret = subprocess.Popen(cmd2.split()).wait()
  File "/zopt/conda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/zopt/conda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Here is my version info.

```
$ conda --version && conda build --version
conda 3.15.1
conda-build 1.15.0
```

**Comment by jakirkham** [comment]
Closing as pipbuild is no longer a thing FWICT.
