### ISSUE TITLE
`conda build -h` doesn't work on conda 3.15.1/conda-build 1.15.0

### ISSUE THREAD

**Issue by tdhopper** [conda/conda-build#513]
```
tdhopper@~ $ conda --version
conda 3.15.1
tdhopper@~ $ conda-build --version
conda-build 1.15.0
tdhopper@~ $ conda build
usage: conda-build [-h] [-V] [--check] [--no-binstar-upload] [--output] [-s]
                   [-t] [--no-test] [-b] [-p] [--skip-existing] [-q]
                   [--python PYTHON_VER] [--perl PERL_VER] [--numpy NUMPY_VER]
                   [--R R_VER] [-c CHANNEL] [--override-channels]
                   RECIPE_PATH [RECIPE_PATH ...]
conda-build: error: too few arguments
tdhopper@~ $ conda build -h
Traceback (most recent call last):
  File "/Users/tdhopper/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/tdhopper/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 172, in main
    args = p.parse_args()
  File "/Users/tdhopper/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 167, in parse_args
    return super(ArgumentParser, self).parse_args(*args, **kwargs)
  File "/Users/tdhopper/anaconda/lib/python2.7/argparse.py", line 1701, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/tdhopper/anaconda/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/tdhopper/anaconda/lib/python2.7/argparse.py", line 1939, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/Users/tdhopper/anaconda/lib/python2.7/argparse.py", line 1879, in consume_optional
    take_action(action, args, option_string)
  File "/Users/tdhopper/anaconda/lib/python2.7/argparse.py", line 1807, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Users/tdhopper/anaconda/lib/python2.7/argparse.py", line 996, in __call__
    parser.print_help()
  File "/Users/tdhopper/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 157, in print_help
    super(ArgumentParser, self).print_help()
  File "/Users/tdhopper/anaconda/lib/python2.7/argparse.py", line 2340, in print_help
    self._print_message(self.format_help(), file)
  File "/Users/tdhopper/anaconda/lib/python2.7/argparse.py", line 2314, in format_help
    return formatter.format_help()
  File "/Users/tdhopper/anaconda/lib/python2.7/argparse.py", line 281, in format_help
    help = self._root_section.format_help()
  File "/Users/tdhopper/anaconda/lib/python2.7/argparse.py", line 211, in format_help
    func(*args)
  File "/Users/tdhopper/anaconda/lib/python2.7/argparse.py", line 211, in format_help
    func(*args)
  File "/Users/tdhopper/anaconda/lib/python2.7/argparse.py", line 517, in _format_action
    help_text = self._expand_help(action)
  File "/Users/tdhopper/anaconda/lib/python2.7/argparse.py", line 601, in _expand_help
    choices_str = ', '.join([str(c) for c in params['choices']])
  File "/Users/tdhopper/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 47, in __iter__
    return iter(self.get_items())
  File "/Users/tdhopper/anaconda/lib/python2.7/site-packages/conda/utils.py", line 142, in __call__
    res = cache[key] = self.func(*args, **kw)
  File "/Users/tdhopper/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 39, in get_items
    return self._get_items()
  File "/Users/tdhopper/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 34, in _get_items
    for path in listdir():
TypeError: listdir() takes exactly 1 argument (0 given)
```

**Comment by asmeurer** [comment]
This has been fixed in conda-build master.
