### ISSUE TITLE
conda-build never exits when "No space left on device"

### ISSUE THREAD

**Issue by njzjz** [conda/conda-build#5211]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I am using conda-build with the GitHub Actions. It threw "No space left on device" error, but the GitHub Actions never stopped.
```
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/__setup_conda/bin/constructor", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.11/site-packages/constructor/main.py", line 405, in main
    main_build(dir_path, output_dir=out_dir, platform=args.platform,
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.11/site-packages/constructor/main.py", line 229, in main_build
    create(info, verbose=verbose)
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.11/site-packages/constructor/shar.py", line 191, in create
    fo.write(chunk)
OSError: [Errno 28] No space left on device
```

![image](https://github.com/conda/conda-build/assets/9496702/e79abe39-f76a-481c-a75f-ed4c60036de5)

In another build, it didn't give such an error message but just hanged.

![image](https://github.com/conda/conda-build/assets/9496702/f96fb7b5-805b-4ab1-b809-d8459ed3fd18)

I tried to run `rm -rf /opt/hostedtoolcache` in the beginning to clean the space, per https://github.com/orgs/community/discussions/25678#discussioncomment-5242449. It works.

![image](https://github.com/conda/conda-build/assets/9496702/4b980634-37be-43fd-a7b7-53b2a22b6415)

So, I think the problem is that conda-build cannot properly exit when the "no space left on device" error happens.

### Additional Context

I don't know how to run `conda info` with the GitHub Actions, but I think the link to the GitHub Actions will help: https://github.com/deepmd-kit-recipes/installer/actions/runs/8133687249/job/22225572458

**Comment by njzjz** [comment]
Oh, I found I submitted it to the wrong repo...
