### ISSUE TITLE
conda build fails when any (non-root) conda environment's python.exe is running

### ISSUE THREAD

**Issue by Korijn** [conda/conda-build#524]
Steps to reproduce:

1. Run `conda build` using the root conda environment on some package you want to build
2. Create some conda environment `foo`
3. Run some long running script with the `foo` environment active
4. Repeat first step (with the root conda environment)

It looks like conda build wants to clear the `_build` environment before moving on, but it can't because the files in there are in use by the `foo` environment's `python.exe`. This seems like incorrect behaviour to me?

```
F:\Jenkins\jobs\[...]\workspace>conda build conda-recipe 
Removing old build environment
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Minicondax64\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Minicondax64\lib\site-packages\conda_build\main_build.py", line 173, in main
    args_func(args, p)
  File "C:\Minicondax64\lib\site-packages\conda_build\main_build.py", line 400, in args_func
    args.func(args, p)
  File "C:\Minicondax64\lib\site-packages\conda_build\main_build.py", line 358, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "C:\Minicondax64\lib\site-packages\conda_build\build.py", line 331, in build
    rm_rf(config.short_build_prefix)
  File "C:\Minicondax64\lib\site-packages\conda\install.py", line 186, in rm_rf
    shutil.rmtree(path)
  File "C:\Minicondax64\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Minicondax64\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Minicondax64\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] Access is denied: 'C:\\Minicondax64\\envs\\_build\\DLLs\\pyexpat.pyd'
```

`conda info` output:

```
C:\Users\[...]>conda info
Current conda install:

             platform : win-64
        conda version : 3.15.1
  conda-build version : 1.16.0
       python version : 2.7.9.final.0
     requests version : 2.7.0
     root environment : C:\Minicondax64  (writable)
  default environment : C:\Minicondax64
     envs directories : C:\Minicondax64\envs
        package cache : C:\Minicondax64\pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/ivoflipse/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/ivoflipse/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/prkrekel/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/prkrekel/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\[...]\.condarc
    is foreign system : False
```

These are the files that can't be deleted:

![error2](https://cloud.githubusercontent.com/assets/1882046/9088365/efc4db0e-3b8f-11e5-939e-f2f58a3208b2.PNG)

This is the error I get when I try to delete one of the files manually:

![error](https://cloud.githubusercontent.com/assets/1882046/9088375/fb909e0a-3b8f-11e5-8890-faa39ece0f6d.PNG)

**Comment by asmeurer** [comment]
This should work now after https://github.com/conda/conda-build/pull/521. Let me know if you still get the issue with conda-build 0.17.0 or greater.

**Comment by Korijn** [comment]
Confirmed, our CI is chugging along again. :)
