### ISSUE TITLE
`"safe_dump()" has been removed` error using `conda skeleton pypi pod5`

### ISSUE THREAD

**Issue by Mathias-Boulanger** [conda/conda-build#5258]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Dear conda devs,

It's my first time trying to contribute to conda framework by creating a conda package.
The idea is to just create a package for the Nanopore `pod5` python tool kit available on [PyPi](https://pypi.org/project/pod5/).

For this purpose I used this command: `conda skeleton pypi --version 0.3.10 pod5` but I got this error:
```
Traceback (most recent call last):
  File "/tmp/tmpgogymv1econda_skeleton_pod5-0.3.10.tar.gz/pod5-0.3.10/setup.py", line 15, in <module>
    setuptools.setup()
  File "/g/krebs/boulanger/miniconda3/conda-bld/skeleton_1711470458614/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/g/krebs/boulanger/miniconda3/conda-bld/skeleton_1711470458614/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 220, in setup
    fn.write(yaml.safe_dump(data, encoding=None))
  File "/g/krebs/boulanger/miniconda3/conda-bld/skeleton_1711470458614/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/ruamel/yaml/main.py", line 1260, in safe_dump
    error_deprecation('safe_dump', 'dump', arg="typ='safe', pure=True")
  File "/g/krebs/boulanger/miniconda3/conda-bld/skeleton_1711470458614/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/ruamel/yaml/main.py", line 1039, in error_deprecation
    raise AttributeError(s, name=None)
AttributeError: 
"safe_dump()" has been removed, use

  yaml = YAML(typ='safe', pure=True)
  yaml.dump(...)

instead of file "/g/krebs/boulanger/miniconda3/conda-bld/skeleton_1711470458614/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 220

        fn.write(yaml.safe_dump(data, encoding=None))
```
If I understood correctly this is the `setuptools` package that using a  deprecated syntax `yaml.safe_dump()` from the `ruamel/yaml` package.

Do you have any idea how to fix this? 
Please let me know if I posted this on the wrong repo or if I should address this issue to anyone else...

Thank you for your help.

Full error log:
```
conda skeleton pypi --version 0.3.10 pod5
Using url https://files.pythonhosted.org/packages/69/b0/b5c4ca9cec24b982e72d5c805a9605e7eab4e39333c8cc77295a5eae412d/pod5-0.3.10.tar.gz (64 KB) for pod5.
Downloading pod5
PyPI URL:  https://files.pythonhosted.org/packages/69/b0/b5c4ca9cec24b982e72d5c805a9605e7eab4e39333c8cc77295a5eae412d/pod5-0.3.10.tar.gz
Using cached download
Unpacking pod5...
done
working in /tmp/tmpgogymv1econda_skeleton_pod5-0.3.10.tar.gz
Reloading output folder: ...working... done
Solving environment (_h_env): ...working... done

## Package Plan ##

  environment location: /g/krebs/boulanger/miniconda3/conda-bld/skeleton_1711470458614/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place


The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-conda_forge            conda-forge
    _openmp_mutex:    4.5-2_gnu                  conda-forge
    bzip2:            1.0.8-hd590300_5           conda-forge
    ca-certificates:  2024.2.2-hbcca054_0        conda-forge
    ld_impl_linux-64: 2.40-h41732ed_0            conda-forge
    libffi:           3.4.2-h7f98852_5           conda-forge
    libgcc-ng:        13.2.0-h807b86a_5          conda-forge
    libgomp:          13.2.0-h807b86a_5          conda-forge
    libnsl:           2.0.1-hd590300_0           conda-forge
    libsqlite:        3.45.2-h2797004_0          conda-forge
    libuuid:          2.38.1-h0b41bf4_0          conda-forge
    libxcrypt:        4.4.36-hd590300_1          conda-forge
    libzlib:          1.2.13-hd590300_5          conda-forge
    ncurses:          6.4.20240210-h59595ed_0    conda-forge
    openssl:          3.2.1-hd590300_1           conda-forge
    patch:            2.7.6-h7f98852_1002        conda-forge
    pip:              24.0-pyhd8ed1ab_0          conda-forge
    python:           3.10.14-hd12c33a_0_cpython conda-forge
    python_abi:       3.10-4_cp310               conda-forge
    readline:         8.2-h8228510_1             conda-forge
    ruamel.yaml:      0.18.6-py310h2372a71_0     conda-forge
    ruamel.yaml.clib: 0.2.8-py310h2372a71_0      conda-forge
    setuptools:       69.2.0-pyhd8ed1ab_0        conda-forge
    tk:               8.6.13-noxft_h4845f30_101  conda-forge
    tzdata:           2024a-h0c530f3_0           conda-forge
    wheel:            0.43.0-pyhd8ed1ab_0        conda-forge
    xz:               5.2.6-h166bdaf_0           conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Applying patch: /tmp/tmpgogymv1econda_skeleton_pod5-0.3.10.tar.gz/pypi-distutils.patch
Applying patch: /tmp/tmpgogymv1econda_skeleton_pod5-0.3.10.tar.gz/pypi-distutils.patch with args:
['-Np0', '-i', '/tmp/tmp3o9vl1x7/pypi-distutils.patch.native', '--binary']
checking file core.py
Hunk #1 succeeded at 167 with fuzz 2 (offset 1 line).
patching file core.py
Hunk #1 succeeded at 167 with fuzz 2 (offset 1 line).
Applying patch: /tmp/tmpgogymv1econda_skeleton_pod5-0.3.10.tar.gz/pypi-distutils.patch
Applying patch: /tmp/tmpgogymv1econda_skeleton_pod5-0.3.10.tar.gz/pypi-distutils.patch with args:
['-Np0', '-i', '/tmp/tmpvxaywyu2/pypi-distutils.patch.native', '--binary']
checking file core.py
Hunk #1 succeeded at 187 with fuzz 2 (offset 21 lines).
patching file core.py
Hunk #1 succeeded at 187 with fuzz 2 (offset 21 lines).
Traceback (most recent call last):
  File "/tmp/tmpgogymv1econda_skeleton_pod5-0.3.10.tar.gz/pod5-0.3.10/setup.py", line 15, in <module>
    setuptools.setup()
  File "/g/krebs/boulanger/miniconda3/conda-bld/skeleton_1711470458614/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/g/krebs/boulanger/miniconda3/conda-bld/skeleton_1711470458614/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 220, in setup
    fn.write(yaml.safe_dump(data, encoding=None))
  File "/g/krebs/boulanger/miniconda3/conda-bld/skeleton_1711470458614/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/ruamel/yaml/main.py", line 1260, in safe_dump
    error_deprecation('safe_dump', 'dump', arg="typ='safe', pure=True")
  File "/g/krebs/boulanger/miniconda3/conda-bld/skeleton_1711470458614/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/ruamel/yaml/main.py", line 1039, in error_deprecation
    raise AttributeError(s, name=None)
AttributeError: 
"safe_dump()" has been removed, use

  yaml = YAML(typ='safe', pure=True)
  yaml.dump(...)

instead of file "/g/krebs/boulanger/miniconda3/conda-bld/skeleton_1711470458614/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 220

        fn.write(yaml.safe_dump(data, encoding=None))


$PYTHONPATH = /tmp/tmpgogymv1econda_skeleton_pod5-0.3.10.tar.gz/pod5-0.3.10:/g/krebs/boulanger/Scripts/PythonScripts:

Leaving build/test directories:
  Work:
 /g/krebs/boulanger/miniconda3/conda-bld/skeleton_1711470458614/work 
  Test:
 /g/krebs/boulanger/miniconda3/conda-bld/skeleton_1711470458614/test_tmp 
Leaving build/test environments:
  Test:
source activate  /g/krebs/boulanger/miniconda3/conda-bld/skeleton_1711470458614/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_ 
  Build:
source activate  /g/krebs/boulanger/miniconda3/conda-bld/skeleton_1711470458614/_build_env 


Error: command failed: /g/krebs/boulanger/miniconda3/conda-bld/skeleton_1711470458614/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python setup.py install
```

### Conda Info

```shell
active environment : bioconda
    active env location : /g/krebs/boulanger/miniconda3/envs/bioconda
            shell level : 1
       user config file : /home/boulange/.condarc
 populated config files : /home/boulange/.condarc
          conda version : 24.3.0
    conda-build version : 24.3.0
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen
                          __conda=24.3.0=0
                          __glibc=2.28=0
                          __linux=4.18.0=0
                          __unix=0=0
       base environment : /g/krebs/boulanger/miniconda3  (writable)
      conda av data dir : /g/krebs/boulanger/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /g/krebs/boulanger/miniconda3/pkgs
                          /home/boulange/.conda/pkgs
       envs directories : /g/krebs/boulanger/miniconda3/envs
                          /home/boulange/.conda/envs
               platform : linux-64
             user-agent : conda/24.3.0 requests/2.31.0 CPython/3.10.14 Linux/4.18.0-477.13.1.el8_8.x86_64 rocky/8.8 glibc/2.28 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 24562:718
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /home/boulange/.condarc <==
auto_activate_base: False
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
```

### Conda list

```shell
# packages in environment at /g/krebs/boulanger/miniconda3/envs/bioconda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aiofiles                  0.8.0              pyhd8ed1ab_0    conda-forge
aioftp                    0.12.0                     py_0    conda-forge
aiohttp                   3.8.6            py39hd1e30aa_1    conda-forge
aiohttp-jinja2            1.4.2              pyhd8ed1ab_0    conda-forge
aiohttp-security          0.4.0                      py_0    conda-forge
aiohttp-session           2.7.0                      py_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
alabaster                 0.7.16             pyhd8ed1ab_0    conda-forge
amqp                      5.2.0              pyhd8ed1ab_1    conda-forge
anaconda-client           1.6.14                     py_0    conda-forge
anyio                     3.7.1              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
async-timeout             4.0.3              pyhd8ed1ab_0    conda-forge
atk-1.0                   2.38.0               hd4edc92_1    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
backoff                   2.2.1              pyhd8ed1ab_0    conda-forge
backports.zoneinfo        0.2.1            py39hf3d152e_8    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
billiard                  4.2.0            py39hd1e30aa_0    conda-forge
bioconda-utils            2.13.0             pyh7cba7a3_0    bioconda
boa                       0.15.1             pyhd8ed1ab_0    conda-forge
boltons                   23.1.1             pyhd8ed1ab_0    conda-forge
boto3                     1.34.70            pyhd8ed1ab_0    conda-forge
botocore                  1.34.70         pyge38_1234567_0    conda-forge
brotli-python             1.1.0            py39h3d6467e_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.27.0               hd590300_0    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
cachetools                3.0.0                      py_0    conda-forge
cairo                     1.18.0               h3faef2a_0    conda-forge
celery                    5.3.6              pyhd8ed1ab_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0           py39h7a31438_0    conda-forge
chardet                   5.2.0            py39hf3d152e_1    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
click-didyoumean          0.3.1              pyhd8ed1ab_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
click-repl                0.3.0              pyhd8ed1ab_0    conda-forge
clyent                    1.2.2              pyhd8ed1ab_2    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
colorlog                  4.8.0            py39hf3d152e_3    conda-forge
conda                     23.3.1           py39hf3d152e_0    conda-forge
conda-build               3.24.0           py39hf3d152e_1    conda-forge
conda-forge-pinning       2023.05.06.13.08.41      hd8ed1ab_0    conda-forge
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
conda-verify              3.1.1           py39hf3d152e_1006    conda-forge
containers-common         0.57.0               ha770c72_0    conda-forge
cryptography              42.0.5           py39hd4f0224_0    conda-forge
curl                      8.6.0                hca28451_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
deprecated                1.2.14             pyh1a96a4e_0    conda-forge
diskcache                 5.6.3              pyhd8ed1ab_0    conda-forge
docutils                  0.19             py39hf3d152e_1    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
expat                     2.6.2                h59595ed_0    conda-forge
filelock                  3.13.3             pyhd8ed1ab_0    conda-forge
fmt                       9.1.0                h924138e_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
frozenlist                1.4.1            py39hd1e30aa_0    conda-forge
future                    1.0.0              pyhd8ed1ab_0    conda-forge
galaxy-lib                19.5.2             pyh864c0ab_1    bioconda
gdk-pixbuf                2.42.10              h829c605_5    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gidgethub                 3.0.0                      py_0    conda-forge
giflib                    5.2.1                h0b41bf4_3    conda-forge
git                       2.44.0          pl5321h709897a_0    conda-forge
gitdb2                    3.0.2                      py_0    conda-forge
gitpython                 3.0.8                      py_0    conda-forge
glob2                     0.7                        py_0    conda-forge
gpgme                     1.18.0               h27087fc_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
graphviz                  9.0.0                h78e8752_1    conda-forge
gtk2                      2.24.33              h280cfa0_4    conda-forge
gts                       0.7.6                h977cf35_4    conda-forge
harfbuzz                  8.3.0                h3d44ed6_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        7.1.0              pyha770c72_0    conda-forge
involucro                 1.1.3                ha8f183a_0    conda-forge
jinja2                    2.11.3             pyhd8ed1ab_2    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
json5                     0.9.24             pyhd8ed1ab_0    conda-forge
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               2.4              py39hf3d152e_3    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_core              5.7.2            py39hf3d152e_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kombu                     5.3.5            py39hf3d152e_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libaio                    0.3.113              h166bdaf_0    conda-forge
libarchive                3.6.2                h039dbb9_1    conda-forge
libassuan                 2.5.7                h59595ed_0    conda-forge
libblas                   3.9.0           21_linux64_openblas    conda-forge
libcblas                  3.9.0           21_linux64_openblas    conda-forge
libcurl                   8.6.0                hca28451_0    conda-forge
libdeflate                1.20                 hd590300_0    conda-forge
libdevmapper              2.02.187             h7f98852_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgd                     2.3.3                h119a65a_9    conda-forge
libgfortran-ng            13.2.0               h69a702a_5    conda-forge
libgfortran5              13.2.0               ha4646dd_5    conda-forge
libglib                   2.80.0               hf2295e7_1    conda-forge
libgomp                   13.2.0               h807b86a_5    conda-forge
libgpg-error              1.48                 h71f35ed_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           21_linux64_openblas    conda-forge
liblief                   0.12.3               h27087fc_0    conda-forge
libmamba                  1.4.2                hcea66bb_0    conda-forge
libmambapy                1.4.2            py39hf0aba66_0    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.26          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
librsvg                   2.56.3               he3f83f7_1    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsolv                   0.7.28               hfc55251_1    conda-forge
libsqlite                 3.45.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libtiff                   4.6.0                h1dd3fc0_3    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp                   1.3.2                h658648e_1    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.6               h232c23b_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     1.4.2            py39hc5d2bb1_0    conda-forge
markdown                  3.6                pyhd8ed1ab_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py39h3811e60_1    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
multidict                 6.0.5            py39hd1e30aa_0    conda-forge
nbformat                  5.10.3             pyhd8ed1ab_0    conda-forge
ncurses                   6.4.20240210         h59595ed_0    conda-forge
networkx                  2.8.8              pyhd8ed1ab_0    conda-forge
numpy                     1.19.5           py39hd249d9e_3    conda-forge
openssl                   3.2.1                hd590300_1    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    1.4.4            py39h1832856_0    conda-forge
pango                     1.52.1               ha41ecd1_0    conda-forge
patch                     2.7.6             h7f98852_1002    conda-forge
patchelf                  0.17.2               h58526e2_0    conda-forge
pcre2                     10.43                hcad00b1_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
pkginfo                   1.10.0             pyhd8ed1ab_0    conda-forge
platformdirs              4.2.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.4.0              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
prompt_toolkit            3.0.42               hd8ed1ab_0    conda-forge
psutil                    5.9.8            py39hd1e30aa_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
py-lief                   0.12.3           py39h5a03fae_0    conda-forge
pyaml                     17.12.1                    py_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6            py39hd1e30aa_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygithub                  1.59.1             pyhd8ed1ab_0    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pyjwt                     2.8.0              pyhd8ed1ab_1    conda-forge
pynacl                    1.5.0            py39hd1e30aa_3    conda-forge
pyopenssl                 24.0.0             pyhd8ed1ab_0    conda-forge
pyrsistent                0.20.0           py39hd1e30aa_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.19          h0755675_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.19.1             pyhd8ed1ab_0    conda-forge
python-libarchive-c       5.1              py39hf3d152e_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1            py39hd1e30aa_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
regex                     2022.7.9         py39hb9d737c_0    conda-forge
reproc                    14.2.4.post0         hd590300_1    conda-forge
reproc-cpp                14.2.4.post0         h59595ed_1    conda-forge
requests                  2.29.0             pyhd8ed1ab_0    conda-forge
rich                      13.7.1             pyhd8ed1ab_0    conda-forge
ripgrep                   14.1.0               he8a937b_0    conda-forge
ruamel.yaml               0.17.40          py39hd1e30aa_0    conda-forge
ruamel.yaml.clib          0.2.8            py39hd1e30aa_0    conda-forge
ruamel_yaml               0.15.80         py39hd1e30aa_1009    conda-forge
s3transfer                0.10.1             pyhd8ed1ab_0    conda-forge
setuptools                69.2.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
skopeo                    1.11.2               he5cbd37_0    conda-forge
smmap                     6.0.0              pyhd8ed1ab_1    conda-forge
smmap2                    3.0.1                      py_0    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
sphinx                    5.1.1              pyhd8ed1ab_1    conda-forge
sphinx-autodoc-typehints  1.19.2             pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.8              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.6              pyhd8ed1ab_0    conda-forge
sphinxcontrib-htmlhelp    2.0.5              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-qthelp      1.0.7              pyhd8ed1ab_0    conda-forge
sphinxcontrib-serializinghtml 1.1.10             pyhd8ed1ab_0    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
termcolor                 1.1.0              pyhd8ed1ab_3    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.1             pyhd8ed1ab_0    conda-forge
tqdm                      4.66.2             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.2             pyhd8ed1ab_0    conda-forge
typing-extensions         4.10.0               hd8ed1ab_0    conda-forge
typing_extensions         4.10.0             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
uritemplate               4.1.1              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.18            pyhd8ed1ab_0    conda-forge
vine                      5.1.0              pyhd8ed1ab_0    conda-forge
watchgod                  0.8.2              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.16.0           py39hd1e30aa_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.7                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.7.0                h59595ed_3    conda-forge
yarl                      1.9.4            py39hd1e30aa_0    conda-forge
yaspin                    2.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstandard                 0.22.0           py39h6e5214e_0    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

**Comment by jaimergp** [comment]
As a workaround, can you use [`grayskull`](https://github.com/conda/grayskull) instead of `conda skeleton`?

**Comment by Mathias-Boulanger** [comment]
Yes, I tried `grayskull` and I succeeded to create the recipe (and when through local test) for one of the dependency 
of the `pod5` package called: [`vbz-h5py-plugin`](https://pypi.org/project/vbz-h5py-plugin/).
But the my recipe for the [`pod5`](https://pypi.org/project/pod5/) package fail upon testing mainly due to a dependency called [`lib-pod5`](https://pypi.org/project/lib-pod5/) that is not available on `conda-forge`.

When I try to use `grayskull` to create `lib-pod5` that is available on PyPi I got this error:
```
(condaforge) [boulange@seneca recipes]$ grayskull pypi lib-pod5



#### Initializing recipe for lib-pod5 (pypi) ####

Recovering metadata from pypi...
Traceback (most recent call last):
  File "/g/krebs/boulanger/miniconda3/envs/condaforge/bin/grayskull", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/g/krebs/boulanger/miniconda3/envs/condaforge/lib/python3.12/site-packages/grayskull/main.py", line 277, in main
    generate_recipes_from_list(args.pypi_packages, args)
  File "/g/krebs/boulanger/miniconda3/envs/condaforge/lib/python3.12/site-packages/grayskull/main.py", line 300, in generate_recipes_from_list
    recipe, config = create_python_recipe(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/g/krebs/boulanger/miniconda3/envs/condaforge/lib/python3.12/site-packages/grayskull/main.py", line 335, in create_python_recipe
    GrayskullFactory.create_recipe(
  File "/g/krebs/boulanger/miniconda3/envs/condaforge/lib/python3.12/site-packages/grayskull/base/factory.py", line 46, in create_recipe
    GrayskullFactory.REGISTERED_STRATEGY[repo_type.lower()].fetch_data(
  File "/g/krebs/boulanger/miniconda3/envs/condaforge/lib/python3.12/site-packages/grayskull/strategy/pypi.py", line 62, in fetch_data
    update_recipe(recipe, config, sections or ALL_SECTIONS)
  File "/g/krebs/boulanger/miniconda3/envs/condaforge/lib/python3.12/site-packages/grayskull/strategy/pypi.py", line 499, in update_recipe
    metadata = get_metadata(recipe, config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g/krebs/boulanger/miniconda3/envs/condaforge/lib/python3.12/site-packages/grayskull/strategy/pypi.py", line 350, in get_metadata
    sdist_metadata, pypi_metadata = get_origin_wise_metadata(config)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g/krebs/boulanger/miniconda3/envs/condaforge/lib/python3.12/site-packages/grayskull/strategy/pypi.py", line 234, in get_origin_wise_metadata
    pypi_metadata = get_pypi_metadata(config)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g/krebs/boulanger/miniconda3/envs/condaforge/lib/python3.12/site-packages/grayskull/strategy/pypi.py", line 277, in get_pypi_metadata
    raise AttributeError(f"There is no sdist package on pypi for {config.name}.")
AttributeError: There is no sdist package on pypi for lib-pod5.
```

Thank you for your idea!

**Comment by jaimergp** [comment]
You can try to use the GH repo for `lib-pod5` as a the source. That said, it looks like a C++ heavy package so it won't be one of those trivial packaging tasks :P

**Comment by Mathias-Boulanger** [comment]
Indeed, my first experience trying make conda package is not smooth as I though it would be...

Thank you the suggestion.

**Comment by sfc-gh-srudenko** [comment]
fyi, same happens on `conda skeleton pypi botocore` or `conda skeleton pypi click`, lots of stuff is broken

**Comment by jaimergp** [comment]
As a workaround, try using `grayskull` to generate your recipes from PyPI. `conda skeleton` is not really well maintained these days, as you can see.
