### ISSUE TITLE
build fails on Windows x64: Ninja Multi-Config does not support platform specification, but platform x64 was specified

### ISSUE THREAD

**Issue by biocodz** [conda/conda-build#5391]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Building [sortmerna 4.3.7](https://github.com/sortmerna/sortmerna/releases/tag/v4.3.7) recipe on conda-forge (Windows platform) in context of [PR25438](https://github.com/conda-forge/staged-recipes/pull/25438) fails with
```
CMake Error at CMakeLists.txt:41 (project):
  Generator

    Ninja Multi-Config

-- Configuring incomplete, errors occurred!
  does not support platform specification, but platform

    x64

  was specified.

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
None
None
None
[proc_run] Run time: 0.03125333786010742
[rocksdb_build] failed to build
The system cannot find the path specified.
Traceback (most recent call last):
  File "D:\a\1\s\.ci_support\build_all.py", line 261, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "D:\a\1\s\.ci_support\build_all.py", line 151, in build_all
    build_folders(recipes_dir, folders, arch, channel_urls)
  File "D:\a\1\s\.ci_support\build_all.py", line 207, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "C:\Miniforge\lib\site-packages\conda_build\api.py", line 250, in build
    return build_tree(
  File "C:\Miniforge\lib\site-packages\conda_build\build.py", line 3638, in build_tree
    packages_from_this = build(
  File "C:\Miniforge\lib\site-packages\conda_build\build.py", line 2462, in build
    windows.build(
  File "C:\Miniforge\lib\site-packages\conda_build\windows.py", line 339, in build
    check_call_env(
  File "C:\Miniforge\lib\site-packages\conda_build\utils.py", line 405, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "C:\Miniforge\lib\site-packages\conda_build\utils.py", line 381, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['cmd.exe', '/d', '/c', 'conda_build.bat']' returned non-zero exit status 1.
##[error]Cmd.exe exited with code '1'.
##[section]Finishing: Build recipes
...
```

Somehow the build system sets `CMAKE_GENERATOR_PLATFORM=x64` ignoring the fact that [Ninja Multi-Config generator is specified in CMake presets](https://github.com/sortmerna/sortmerna/blob/v4.3.7/cmake/presets/CMakePresets_rocksdb.json#L12), which does not support the platform specification.

The build works OK on my local machine. It also worked fine on conda-forge just recently. I guess some new changes introduced this bug. 
Not sure though if the bug is in conda-build or in the Azure pipeline.

[the build details are here ](https://github.com/conda-forge/staged-recipes/pull/25438/checks?check_run_id=26709637964)

**Comment by uebian** [comment]
I'm also encountering this issue. Did you figure out a solution?
