### ISSUE TITLE
conda-build 24.7.0 FileNotFoundError on Windows without WSL

### ISSUE THREAD

**Issue by cbouss** [conda/conda-build#5433]
### What happened?

On a windows system without WSL. Getting:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\miniconda3\lib\site-packages\conda\exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
      File "C:\miniconda3\lib\site-packages\conda\cli\main.py", line 84, in main_subshell
        exit_code = do_call(args, parser)
      File "C:\miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 176, in do_call
        result = plugin_subcommand.action(getattr(args, "_args", args))
      File "C:\miniconda3\lib\site-packages\conda_build\plugin.py", line 17, in build
        return execute(args)
      File "C:\miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 589, in execute
        api.build(
      File "C:\miniconda3\lib\site-packages\conda_build\api.py", line 209, in build
        return build_tree(
      File "C:\miniconda3\lib\site-packages\conda_build\build.py", line 3709, in build_tree
        packages_from_this = build(
      File "C:\miniconda3\lib\site-packages\conda_build\build.py", line 2762, in build
        newly_built_packages = bundlers[pkg_type](
      File "C:\miniconda3\lib\site-packages\conda_build\build.py", line 1741, in bundle_conda
        on_win and Path("C:\\Windows\\System32\\bash.exe").samefile(args[0])
      File "C:\miniconda3\lib\pathlib.py", line 1149, in samefile
        st = self.stat()
      File "C:\miniconda3\lib\pathlib.py", line 1232, in stat
        return self._accessor.stat(self)
    FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Windows\\System32\\bash.exe'
```

It seems to be due to https://github.com/conda/conda-build/pull/5367
Issue is not reproducible with conda-build 24.5.1

<details>
<summary><b>Additional Context</b></summary>

````
(base) PS C:\Users\dev-admin> conda build --error-overlinking --error-overdepending --croot=cr2022 .\vs2022-feedstock\
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
Adding in variants from internal_defaults
Adding in variants from C:\Users\dev-admin\conda_build_config.yaml
Adding in variants from C:\Users\dev-admin\vs2022-feedstock\recipe\conda_build_config.yaml
Attempting to finalize metadata for vs2015_runtime
Reloading output folder: ...working... done
Getting pinned dependencies: ...working... done
Attempting to finalize metadata for vs2022_win-64
Reloading output folder: ...working... done
Getting pinned dependencies: ...working... done
Attempting to finalize metadata for vc
BUILD START: ['vs2015_runtime-14.40.33807-hd8d6816_0.tar.bz2', 'vs2022_win-64-19.29.30154-ha9d2c92_0.tar.bz2', 'vc-14.3-h2eaa2aa_0.tar.bz2']

Rendered as:
```yaml
package:
  name: vs2015_runtime
  version: 14.40.33807
build:
  missing_dso_whitelist:
    - '*.dll'
    - '*.DLL'
  no_link:
    - '*.dll

      '
    - Library/bin/*.dll
  number: 0
requirements:
  build:
    - vswhere 2.8.4 haa95532_0
  run: []
outputs:
  - about:
      license: BSD 3-clause
      summary: Activation and version verification of MSVC 14.3 (VS 2022 compiler,
        update 10)
    build:
      run_exports:
        strong:
          - vc >=14.3,<15.0a0
          - vs2015_runtime >=14.40.33807,<15.0a0
      track_features:
        - vc14
    name: vs2022_win-64
    requirements:
      build:
        - m2-sed
      run:
        - vswhere
    script: install_activate.bat
    test:
      commands:
        - cl.exe
    version: 19.29.30154
  - about:
      summary: MSVC runtimes associated with cl.exe version 19.29.30154 (VS 2022 update
        10)
    build:
      missing_dso_whitelist:
        - '*.dll'
        - '*.DLL'
      no_link:
        - '*.dll

          '
        - Library/bin/*.dll
    name: vs2015_runtime
    requirements:
      build:
        - vswhere
    script: install_runtime.bat
    version: 14.40.33807
  - about:
      description: 'This metapackage is used to enforce consistency of runtime

        dependencies within an environment

        '
      dev_url: https://github.com/conda/conda/wiki/VC-features
      doc_url: https://github.com/conda/conda/wiki/VC-features
      home: https://github.com/conda/conda/wiki/VC-features
      license: BSD-3-Clause
      license_family: BSD
      license_file: C:\Users\dev-admin\vs2022-feedstock\recipe/LICENSE
      summary: A meta-package to impose mutual exclusivity among software built with
        different VS versions
    build:
      track_features:
        - vc14
    name: vc
    requirements:
      run:
        - vs2015_runtime >=14.40.33807
    version: '14.3'
about:
  summary: MSVC runtimes associated with cl.exe version 19.29.30154 (VS 2022 update
    10)
extra:
  copy_test_source_files: true
  final: true
  parent_recipe:
    name: vs_activation_and_runtime
    path: C:\Users\dev-admin\vs2022-feedstock\recipe
    version: 1.0.0
```

source tree in: C:\Users\dev-admin\cr2022\vs_activation_and_runtime_1722283240447\work
WARNING: Using legacy MSVC compiler setup.  This will be removed in conda-build 4.0. If this recipe does not use a compiler, this message is safe to ignore.  Otherwise, use {{compiler('<language>')}} jinja2 in requirements/build.
Packaging vs2015_runtime
Reloading output folder: ...working... done
Solving environment (_h_env): ...working... done

## Package Plan ##

  environment location: C:\Users\dev-admin\cr2022\vs_activation_and_runtime_1722283240447\_h_env


The following NEW packages will be INSTALLED:

    vswhere: 2.8.4-haa95532_0 defaults

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Packaging vs2015_runtime-14.40.33807-hd8d6816_0

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\miniconda3\lib\site-packages\conda\exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
      File "C:\miniconda3\lib\site-packages\conda\cli\main.py", line 84, in main_subshell
        exit_code = do_call(args, parser)
      File "C:\miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 176, in do_call
        result = plugin_subcommand.action(getattr(args, "_args", args))
      File "C:\miniconda3\lib\site-packages\conda_build\plugin.py", line 17, in build
        return execute(args)
      File "C:\miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 589, in execute
        api.build(
      File "C:\miniconda3\lib\site-packages\conda_build\api.py", line 209, in build
        return build_tree(
      File "C:\miniconda3\lib\site-packages\conda_build\build.py", line 3709, in build_tree
        packages_from_this = build(
      File "C:\miniconda3\lib\site-packages\conda_build\build.py", line 2762, in build
        newly_built_packages = bundlers[pkg_type](
      File "C:\miniconda3\lib\site-packages\conda_build\build.py", line 1741, in bundle_conda
        on_win and Path("C:\\Windows\\System32\\bash.exe").samefile(args[0])
      File "C:\miniconda3\lib\pathlib.py", line 1149, in samefile
        st = self.stat()
      File "C:\miniconda3\lib\pathlib.py", line 1232, in stat
        return self._accessor.stat(self)
    FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Windows\\System32\\bash.exe'

`$ C:\miniconda3\Scripts\conda-script.py build --error-overlinking --error-overdepending --croot=cr2022 .\vs2022-feedstock\`

  environment variables:
                 CIO_TEST=<not set>
    CONDA_ALLOW_SOFTLINKS=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\miniconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\miniconda3\python.exe
               CONDA_ROOT=C:\miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\dev-admin
               LD_PRELOAD=<not set>
                     PATH=C:\miniconda3;C:\miniconda3\Library\mingw-w64\bin;C:\miniconda3\Librar
                          y\usr\bin;C:\miniconda3\Library\bin;C:\miniconda3\Scripts;C:\miniconda
                          3\bin;C:\miniconda3\condabin;C:\Program Files
                          (x86)\Intel\oneAPI\tbb\latest\redist\intel64\vc_mt;C:\Program Files
                          (x86)\Intel\oneAPI\tbb\latest\redist\ia32\vc_mt;C:\Program Files
                          (x86)\Intel\oneAPI\mpi\latest\bin;C:\Program Files
                          (x86)\Intel\oneAPI\mpi\latest\bin\release;C:\Program Files
                          (x86)\Intel\oneAPI\mpi\latest\libfabric\bin;C:\Program Files
                          (x86)\Intel\oneAPI\mpi\latest\libfabric\bin\utils;C:\Program Files (x8
                          6)\Intel\oneAPI\compiler\latest\windows\redist\intel64_win\compiler;C:
                          \Program Files (x86)\Intel\oneAPI\compiler\latest\windows\redist\ia32_
                          win\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C
                          :\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;
                          C:\Program Files\Amazon\cfn-
                          bootstrap;C:\ProgramData\chocolatey\bin;C:\Program
                          Files\Amazon\AWSCLIV2;C:\Program Files\OpenSSH-Win64;C:\Users\dev-
                          admin\AppData\Local\Microsoft\WindowsApps;C:\Users\dev-
                          admin\.dotnet\tools
             PSMODULEPATH=C:\Users\dev-admin\Documents\WindowsPowerShell\Modules;C:\Windows\syst
                          em32\WindowsPowerShell\v1.0\Modules;C:\Program
                          Files\WindowsPowerShell\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=C:\miniconda3\Library\ssl\cacert.pem

     active environment : base
    active env location : C:\miniconda3
            shell level : 1
       user config file : C:\Users\dev-admin\.condarc
 populated config files : C:\miniconda3\.condarc
                          C:\Users\dev-admin\.condarc
          conda version : 24.7.1
    conda-build version : 24.7.0
         python version : 3.9.18.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake_avx512
                          __conda=24.7.1=0
                          __win=0=0
       base environment : C:\miniconda3  (writable)
      conda av data dir : C:\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\miniconda3\pkgs
                          C:\Users\dev-admin\.conda\pkgs
                          C:\Users\dev-admin\AppData\Local\conda\conda\pkgs
       envs directories : C:\miniconda3\envs
                          C:\Users\dev-admin\.conda\envs
                          C:\Users\dev-admin\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.9.18 Windows/10 Windows/10.0.17763 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.8
          administrator : True
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>
````

</details>

### Conda Details

<details>
<summary><code>conda info</code></summary>

```shell
active environment : base
    active env location : C:\miniconda3
            shell level : 1
       user config file : C:\Users\dev-admin\.condarc
 populated config files : C:\miniconda3\.condarc
                          C:\Users\dev-admin\.condarc
          conda version : 24.7.1
    conda-build version : 24.7.0
         python version : 3.9.18.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake_avx512
                          __conda=24.7.1=0
                          __win=0=0
       base environment : C:\miniconda3  (writable)
      conda av data dir : C:\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\miniconda3\pkgs
                          C:\Users\dev-admin\.conda\pkgs
                          C:\Users\dev-admin\AppData\Local\conda\conda\pkgs
       envs directories : C:\miniconda3\envs
                          C:\Users\dev-admin\.conda\envs
                          C:\Users\dev-admin\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.9.18 Windows/10 Windows/10.0.17763 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.8 aau/0.4.4
          administrator : True
             netrc file : None
           offline mode : False
```

</details>

<details>
<summary><code>conda config</code></summary>

```shell
==> C:\miniconda3\.condarc <==
add_pip_as_python_dependency: False
show_channel_urls: True

==> C:\Users\dev-admin\.condarc <==
report_errors: False
anaconda_upload: False
anaconda_anon_usage: False

==> envvars <==
allow_softlinks: False
```

</details>

<details>
<summary><code>conda list</code></summary>

```shell
(base) PS C:\Users\dev-admin> conda list --show-channel-urls
# packages in environment at C:\miniconda3:
#
# Name                    Version                   Build  Channel
abs-sdk                   0.1.0+1413.g7e11e5da            py_0    file:///C:/prefect/sdk
aiobotocore               2.12.3           py39haa95532_0    defaults
aiohttp                   3.9.5            py39h2bbff1b_0    defaults
aioitertools              0.7.1              pyhd3eb1b0_0    defaults
aiosignal                 1.2.0              pyhd3eb1b0_0    defaults
anaconda-anon-usage       0.4.4           py39hfc23b7f_100    defaults
anaconda-channel-scanner  1.3.0                      py_1    distro-tooling
anaconda-client           1.12.3           py39haa95532_0    defaults
annotated-types           0.6.0            py39haa95532_0    defaults
archspec                  0.2.3              pyhd3eb1b0_0    defaults
async-timeout             4.0.3            py39haa95532_0    defaults
attrs                     23.1.0           py39haa95532_0    defaults
bcrypt                    3.2.0            py39h2bbff1b_1    defaults
beautifulsoup4            4.12.3           py39haa95532_0    defaults
boltons                   23.0.0           py39haa95532_0    defaults
boto3                     1.34.69          py39haa95532_0    defaults
botocore                  1.34.69          py39haa95532_0    defaults
brotli-python             1.0.9            py39hd77b12b_8    defaults
bzip2                     1.0.8                h2bbff1b_6    defaults
ca-certificates           2024.7.2             haa95532_0    defaults
certifi                   2024.7.4         py39haa95532_0    defaults
cffi                      1.16.0           py39h2bbff1b_1    defaults
chardet                   4.0.0           py39haa95532_1003    defaults
charset-normalizer        3.3.2              pyhd3eb1b0_0    defaults
click                     8.1.7            py39haa95532_0    defaults
cloudpickle               3.0.0            py39haa95532_0    defaults
colorama                  0.4.6            py39haa95532_0    defaults
conda                     24.7.1           py39haa95532_0    defaults
conda-build               24.7.0           py39haa95532_0    defaults
conda-content-trust       0.2.0            py39haa95532_1    defaults
conda-index               0.5.0            py39haa95532_0    defaults
conda-libmamba-solver     24.7.0             pyhd3eb1b0_0    defaults
conda-package-handling    2.3.0            py39haa95532_0    defaults
conda-package-streaming   0.10.0           py39haa95532_0    defaults
console_shortcut_miniconda 0.1.1                haa95532_2    defaults
croniter                  0.3.35                     py_0    defaults
cryptography              42.0.5           py39h89fc84f_1    defaults
curl                      8.7.1                he2ea4bf_0    defaults
dask-core                 2024.5.0         py39haa95532_0    defaults
datadog                   0.42.0             pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
deprecated                1.2.13           py39haa95532_0    defaults
distributed               2024.5.0         py39haa95532_0    defaults
distro                    1.9.0            py39haa95532_0    defaults
docker-py                 7.0.0            py39haa95532_0    defaults
filelock                  3.13.1           py39haa95532_0    defaults
fmt                       9.1.0                h6d14046_1    defaults
frozendict                2.4.2            py39h2bbff1b_0    defaults
frozenlist                1.4.0            py39h2bbff1b_0    defaults
fsspec                    2024.3.1         py39haa95532_0    defaults
git                       2.45.2               haa95532_0    defaults
gitdb                     4.0.7              pyhd3eb1b0_0    defaults
gitpython                 3.1.43           py39haa95532_0    defaults
heapdict                  1.0.1              pyhd3eb1b0_0    defaults
idna                      3.7              py39haa95532_0    defaults
importlib-metadata        7.0.1            py39haa95532_0    defaults
importlib_resources       6.4.0            py39haa95532_0    defaults
jinja2                    3.1.4            py39haa95532_0    defaults
jmespath                  1.0.1            py39haa95532_0    defaults
jsonpatch                 1.33             py39haa95532_1    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
jsonschema                4.19.2           py39haa95532_0    defaults
jsonschema-specifications 2023.7.1         py39haa95532_0    defaults
jupyter_core              5.7.2            py39haa95532_0    defaults
libarchive                3.6.2                hb62f4d4_3    defaults
libcurl                   8.7.1                h86230a5_0    defaults
libiconv                  1.16                 h2bbff1b_3    defaults
liblief                   0.12.3               hd77b12b_0    defaults
libmamba                  1.5.8                h99b1521_2    defaults
libmambapy                1.5.8            py39h77c03ed_2    defaults
libsolv                   0.7.24               h23ce68f_1    defaults
libssh2                   1.11.0               h291bd65_0    defaults
libxml2                   2.10.4               h0ad7f3c_2    defaults
locket                    1.0.0            py39haa95532_0    defaults
lz4-c                     1.9.4                h2bbff1b_1    defaults
m2-msys2-runtime          2.5.0.17080.65c939c               3    defaults
m2-patch                  2.7.5                         2    defaults
markupsafe                2.1.3            py39h2bbff1b_0    defaults
marshmallow               3.19.0           py39haa95532_0    defaults
marshmallow-oneofschema   3.0.1            py39haa95532_0    defaults
menuinst                  2.1.1            py39h5da7b33_0    defaults
more-itertools            10.1.0           py39haa95532_0    defaults
msgpack-python            1.0.3            py39h59b6b97_0    defaults
msys2-conda-epoch         20160418                      1    defaults
multidict                 6.0.4            py39h2bbff1b_0    defaults
mypy_extensions           1.0.0            py39haa95532_0    defaults
natsort                   7.1.1              pyhd3eb1b0_0    defaults
nbformat                  5.9.2            py39haa95532_0    defaults
openssl                   3.0.14               h827c3e9_0    defaults
packaging                 24.1             py39haa95532_0    defaults
paramiko                  2.8.1              pyhd3eb1b0_0    defaults
partd                     1.4.1            py39haa95532_0    defaults
pcre2                     10.42                h0ff8eda_1    defaults
pendulum                  2.1.2              pyhd3eb1b0_1    defaults
percy                     0.1.0              pyhd3eb1b0_0    defaults
pip                       24.0             py39haa95532_0    defaults
pkginfo                   1.10.0           py39haa95532_0    defaults
platformdirs              3.10.0           py39haa95532_0    defaults
pluggy                    1.0.0            py39haa95532_1    defaults
powershell_shortcut_miniconda 0.0.1                haa95532_2    defaults
prefect                   1.4.0              pyhd3eb1b0_0    distro-tooling
prefect-cookbook          0+unknown                pypi_0    pypi
psutil                    5.9.0            py39h2bbff1b_0    defaults
py-lief                   0.12.3           py39hd77b12b_0    defaults
pybind11-abi              5                    hd3eb1b0_0    defaults
pycosat                   0.6.6            py39h2bbff1b_1    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pydantic                  2.5.3            py39haa95532_0    defaults
pydantic-core             2.14.6           py39h062c2fa_0    defaults
pygithub                  1.55               pyhd3eb1b0_1    defaults
pyjwt                     2.8.0            py39haa95532_0    defaults
pynacl                    1.5.0            py39h8cc25b3_0    defaults
pyopenssl                 24.0.0           py39haa95532_0    defaults
pysocks                   1.7.1            py39haa95532_0    defaults
python                    3.9.18               h1aa4202_0    defaults
python-box                5.4.1              pyhd3eb1b0_0    distro-tooling
python-dateutil           2.9.0post0       py39haa95532_2    defaults
python-fastjsonschema     2.16.2           py39haa95532_0    defaults
python-json-logger        2.0.7            py39haa95532_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
python-lmdb               1.4.1            py39hd77b12b_0    defaults
python-slugify            5.0.2              pyhd3eb1b0_0    defaults
pytz                      2024.1           py39haa95532_0    defaults
pytzdata                  2020.1             pyhd3eb1b0_0    defaults
pywin32                   305              py39h2bbff1b_0    defaults
pyyaml                    6.0.1            py39h2bbff1b_0    defaults
referencing               0.30.2           py39haa95532_0    defaults
reproc                    14.2.4               hd77b12b_2    defaults
reproc-cpp                14.2.4               hd77b12b_2    defaults
requests                  2.32.3           py39haa95532_0    defaults
requests-toolbelt         1.0.0            py39haa95532_0    defaults
rpds-py                   0.10.6           py39h062c2fa_0    defaults
ruamel.yaml               0.17.21          py39h2bbff1b_0    defaults
ruamel.yaml.clib          0.2.6            py39h2bbff1b_1    defaults
s3transfer                0.10.1           py39haa95532_0    defaults
setuptools                69.5.1           py39haa95532_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
slack-sdk                 3.19.5             pyhaa95532_0    distro-tooling
smmap                     4.0.0              pyhd3eb1b0_0    defaults
sortedcontainers          2.4.0              pyhd3eb1b0_0    defaults
soupsieve                 2.5              py39haa95532_0    defaults
sqlite                    3.45.3               h2bbff1b_0    defaults
tabulate                  0.9.0            py39haa95532_0    defaults
tblib                     1.7.0              pyhd3eb1b0_0    defaults
termcolor                 2.1.0            py39haa95532_0    defaults
text-unidecode            1.3                pyhd3eb1b0_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
tomli                     2.0.1            py39haa95532_0    defaults
toolz                     0.12.0           py39haa95532_0    defaults
tornado                   6.4.1            py39h827c3e9_0    defaults
tqdm                      4.66.4           py39h9909e9c_0    defaults
traitlets                 5.14.3           py39haa95532_0    defaults
typing-extensions         4.11.0           py39haa95532_0    defaults
typing_extensions         4.11.0           py39haa95532_0    defaults
tzdata                    2024a                h04d1e81_0    defaults
unidecode                 1.2.0              pyhd3eb1b0_0    defaults
urllib3                   1.26.19          py39haa95532_0    defaults
vc                        14.2                 h2eaa2aa_4    defaults
vs2015_runtime            14.29.30133          h43f2093_4    defaults
websocket-client          1.8.0            py39haa95532_0    defaults
wheel                     0.43.0           py39haa95532_0    defaults
win_inet_pton             1.1.0            py39haa95532_0    defaults
wrapt                     1.14.1           py39h2bbff1b_0    defaults
xz                        5.4.6                h8cc25b3_1    defaults
yaml                      0.2.5                he774522_0    defaults
yaml-cpp                  0.8.0                hd77b12b_1    defaults
yarl                      1.9.3            py39h2bbff1b_0    defaults
zict                      3.0.0            py39haa95532_0    defaults
zipp                      3.17.0           py39haa95532_0    defaults
zlib                      1.2.13               h8cc25b3_1    defaults
zstandard                 0.22.0           py39h3469f8a_0    defaults
zstd                      1.5.5                hd43e919_2    defaults
```

</details>

**Comment by kenodegard** [comment]
@cbouss thanks for reporting, a fix is in the works: #5434
