### ISSUE TITLE
build fails. RuntimeError: Setuptools downloading is disabled in conda build. 

### ISSUE THREAD

**Issue by arsenovic** [conda/conda-build#547]
i am trying to make a conda package for scikit-rf. 
upon conda build scikit-rf , i get the error showed below.
i in my meta.yaml i have 
```
source:
  path: /home/alex/code/scikit-rf
```

and the neccesary requirements.  could someone give me a hint?

(here is a link to the [setup.py](https://github.com/scikit-rf/scikit-rf/blob/master/setup.py))
```
Installed /home/alex/anaconda/envs/_build/lib/python2.7/site-packages/scikit_rf-0.14.1-py2.7.egg
Processing dependencies for scikit-rf==0.14.1
Searching for mock
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    include_package_data = True,
  File "/home/alex/anaconda/envs/_build/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/alex/anaconda/envs/_build/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/alex/anaconda/envs/_build/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/alex/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/setuptools/command/install.py", line 67, in run
  File "/home/alex/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/setuptools/command/install.py", line 117, in do_egg_install
  File "/home/alex/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/setuptools/command/easy_install.py", line 380, in run
  File "/home/alex/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/setuptools/command/easy_install.py", line 610, in easy_install
  File "/home/alex/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/setuptools/command/easy_install.py", line 661, in install_item
  File "/home/alex/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/setuptools/command/easy_install.py", line 709, in process_distribution
  File "/home/alex/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/pkg_resources/__init__.py", line 836, in resolve
  File "/home/alex/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/pkg_resources/__init__.py", line 1081, in best_match
  File "/home/alex/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/pkg_resources/__init__.py", line 1093, in obtain
  File "/home/alex/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/setuptools/command/easy_install.py", line 617, in easy_install
  File "/home/alex/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/setuptools/package_index.py", line 594, in fetch_distribution
  File "/home/alex/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/setuptools/package_index.py", line 431, in find_packages
  File "/home/alex/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/setuptools/package_index.py", line 765, in scan_url
  File "/home/alex/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg/setuptools/package_index.py", line 283, in process_url
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/mock/r
Command failed: /bin/bash -x -e /home/alex/tmp/conda_pack/scikit-rf/build.sh
```

**Comment by tacaswell** [comment]
It is trying to install `mock`, you need to add it as a build-time dependency in the meta.yml.

**Comment by arsenovic** [comment]
ok thanks!.  i  am not familiar with that package, so it didnt make sense for me that it is a dependency.
