### ISSUE TITLE
Conda Recipe Creation Fails for pygraphviz (Python 3.4/Windows/64-bit)

### ISSUE THREAD

**Issue by bmcguirk** [conda/conda-build#551]
Tried to run `conda pipbuild pygraphviz` on a Windows box running an updated Anaconda, 64-bit installation. Here's the readout: 

    PS C:\> conda pipbuild pygraphviz
    Package search: {'summary': 'Python interface to Graphviz', '_pypi_ordering': False, 'name': 'pygraphviz', 'version': '1
    .3rc2'}
    Creating standard recipe for pygraphviz-1.3rc2
    An unexpected error has occurred, please consider sending the
    following traceback to the conda GitHub issue tracker at:

        https://github.com/conda/conda-build/issues

    Include the output of the command 'conda info' in your report.

    Traceback (most recent call last):
      File "C:\Anaconda3\Scripts\conda-pipbuild-script.py", line 4, in <module>
        sys.exit(main())
      File "C:\Anaconda3\lib\site-packages\conda_build\main_pipbuild.py", line 80, in main
        args_func(args, p)
      File "C:\Anaconda3\lib\site-packages\conda_build\main_build.py", line 349, in args_func
        args.func(args, p)
      File "C:\Anaconda3\lib\site-packages\conda_build\main_pipbuild.py", line 360, in execute
        build_package(package, version, noarch_python=args.noarch_python)
      File "C:\Anaconda3\lib\site-packages\conda_build\main_pipbuild.py", line 299, in build_package
        directory = build_recipe(package, version=version)
      File "C:\Anaconda3\lib\site-packages\conda_build\main_pipbuild.py", line 146, in build_recipe
        output = result.strip().split('\n')
    TypeError: 'str' does not support the buffer interface

**Comment by jakirkham** [comment]
I think this is already fixed in master. See PR referenced above for more details about the fix.
