### ISSUE TITLE
tests are busted due to something with setuptools and ruamel.yaml

### ISSUE THREAD

**Issue by beckermr** [conda/conda-build#5515]
IDK why, but the tests for conda skeleton are now breaking due to the removal of `safe_dump` in `ruamel.yaml >=0.18.0`.

see https://github.com/conda/conda-build/actions/runs/11484656642/job/31962986476

**Comment by zooba** [comment]
I'm seeing the same thing in my own builds:

```
Traceback (most recent call last):
  File "/tmp/tmptxqm3_v0conda_skeleton_azure-eventgrid-4.5.0.zip/azure-eventgrid-4.5.0/setup.py", line 53, in <module>
    setup(
  File "/mnt/vss/_work/1/tools/envs/default/conda-bld/skeleton_1729848074618/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/vss/_work/1/tools/envs/default/conda-bld/skeleton_1729848074618/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 218, in setup
    fn.write(yaml.safe_dump(data, encoding=None))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/vss/_work/1/tools/envs/default/conda-bld/skeleton_1729848074618/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1260, in safe_dump
    error_deprecation('safe_dump', 'dump', arg="typ='safe', pure=True")
  File "/mnt/vss/_work/1/tools/envs/default/conda-bld/skeleton_1729848074618/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1039, in error_deprecation
    raise AttributeError(s, name=None)
AttributeError: 
"safe_dump()" has been removed, use

  yaml = YAML(typ='safe', pure=True)
  yaml.dump(...)

instead of file "/mnt/vss/_work/1/tools/envs/default/conda-bld/skeleton_1729848074618/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 218

        fn.write(yaml.safe_dump(data, encoding=None))
```

I can't find the source of this code anywhere, so I have to assume conda-build/skeleton is doing some kind of patching.

Going to go look for a workaround (probably pinning ruyaml somehow), but if this is coming from a patch then it'd be great to get it fixed upstream (wherever that is).

**Comment by beckermr** [comment]
I think the issue is that some of the recipes in the tests need ruamel.yaml pinned.

**Comment by beckermr** [comment]
NVM. I think I found it here: https://github.com/conda/conda-build/pull/5517
