### ISSUE TITLE
Incompatible with lief=0.15.1

### ISSUE THREAD

**Issue by xhochy** [conda/conda-build#5564]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

In the `py-lief 0.15.x` release there were some changes that break conda-build, e.g.:

```
Traceback (most recent call last):
  File "/home/ubuntu/.pixi/envs/conda-build/bin/conda-build", line 7, in <module>
    from conda_build.cli.main_build import execute
  File "/home/ubuntu/.pixi/envs/conda-build/lib/python3.12/site-packages/conda_build/cli/main_build.py", line 19, in <module>
    from .. import api, build, source, utils
  File "/home/ubuntu/.pixi/envs/conda-build/lib/python3.12/site-packages/conda_build/build.py", line 54, in <module>
    from .post import (
  File "/home/ubuntu/.pixi/envs/conda-build/lib/python3.12/site-packages/conda_build/post.py", line 47, in <module>
    from .inspect_pkg import which_package
  File "/home/ubuntu/.pixi/envs/conda-build/lib/python3.12/site-packages/conda_build/inspect_pkg.py", line 28, in <module>
    from .os_utils.liefldd import codefile_class, machofile
  File "/home/ubuntu/.pixi/envs/conda-build/lib/python3.12/site-packages/conda_build/os_utils/liefldd.py", line 213, in <module>
    elf_dyn_tag=lief.ELF.DYNAMIC_TAGS.RUNPATH,
                ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lief._lief.ELF' has no attribute 'DYNAMIC_TAGS'
```

**Comment by duncanmmacleod** [comment]
This is impacting feedstock builds on macOS: see [build log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1106029&view=logs&j=1dfee543-4d72-5193-7012-7358e3fc4acd&t=344bb75a-1253-525e-defa-7c6fedd7579f) for https://github.com/conda-forge/lal-feedstock/pull/104.
