### ISSUE TITLE
Error in test with comment (?)

### ISSUE THREAD

**Issue by rmcgibbo** [conda/conda-build#558]
I just noticed the following error when `conda-build`(1.17.0, win-64) was running a package test with the following meta.yaml file.
````
# meta.yaml
[... snip ...]
test:
  commands:
    - msmb -h
    - # nosetests msmbuilder -v
```

I assume the problem is the comment. The error is

```
PS> conda build msmbuilder
[... snip ...]
BUILD END: msmbuilder-3.3.0-np18py34_0
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\rmcgibbo\Miniconda3\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "c:\users\rmcgibbo\projects\conda-build\conda_build\main_build.py", line 175, in main
    args_func(args, p)
  File "c:\users\rmcgibbo\projects\conda-build\conda_build\main_build.py", line 409, in args_func
    args.func(args, p)
  File "c:\users\rmcgibbo\projects\conda-build\conda_build\main_build.py", line 396, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "c:\users\rmcgibbo\projects\conda-build\conda_build\build.py", line 486, in test
    shell_files = create_shell_files(tmp_dir, m)
  File "c:\users\rmcgibbo\projects\conda-build\conda_build\create_test.py", line 44, in create_shell_files
    f.write(cmd)
TypeError: must be str, not None
```

**Comment by asmeurer** [comment]
I think this is correct. The yaml is the same as 

```
test:
  commands:
    - msmb -h
    - 
```

which is the same as

```
test:
  commands:
    - msmb -h
    - null
```

Why did you put the comment after the `-`?

**Comment by rmcgibbo** [comment]
I put it there when debugging a failing test. This is a "principle of least surprise" thing, IMO. A null line should be treated as equivalent to the empty string (no command), and not crash the process.

**Comment by asmeurer** [comment]
Maybe. The issue is that # is the comment delimiter for yaml, but you were expecting it to act like a bash script.

**Comment by rmcgibbo** [comment]
Sure. I _understand_ why it doesn't work _now_. I just don't see it as the most user friendly behavior. But my preference isn't strong.
