### ISSUE TITLE
conda-build crashes when build tag is included in run requirements

### ISSUE THREAD

**Issue by pavoljuhas** [conda/conda-build#563]
It seems that dependency build string (e.g., py27_2) is accepted within the build requirements section of meta.yaml, but causes a crash when included for run dependencies:

``` YAML
requirements:
  build:
    - boost 1.56.0 py27_2

  run:
    - boost 1.56.0 py27_2
```

`conda build` completed the BUILD stage, but crashed on creating the TEST environment.

```
...
BUILD END: pyobjcryst-1.0-py27_14
TEST START: pyobjcryst-1.0-py27_14
Fetching package metadata: ..........
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/pjuhas/arch/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/pjuhas/arch/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 190, in main
    args_func(args, p)
  File "/Users/pjuhas/arch/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 429, in args_func
    args.func(args, p)
  File "/Users/pjuhas/arch/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 416, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "/Users/pjuhas/arch/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 535, in test
    channel_urls=channel_urls, override_channels=override_channels)
  File "/Users/pjuhas/arch/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 280, in create_env
    actions = plan.install_actions(prefix, index, specs)
  File "/Users/pjuhas/arch/anaconda/lib/python2.7/site-packages/conda/plan.py", line 402, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/Users/pjuhas/arch/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 738, in solve
    minimal_hint=minimal_hint)
  File "/Users/pjuhas/arch/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 483, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/Users/pjuhas/arch/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 341, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: boost-1.56.0-py27_2.tar.bz2 MatchSpec(u'bzip2 1.0.*')
```

The output of `conda info` is as follows:

```
$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.16.0
  conda-build version : 1.17.0
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /Users/pjuhas/arch/anaconda  (writable)
  default environment : /Users/pjuhas/arch/anaconda
     envs directories : /Users/pjuhas/arch/anaconda/envs
        package cache : /Users/pjuhas/arch/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/menpo/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/menpo/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/pavoljuhas/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/pavoljuhas/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/pjuhas/.condarc
    is foreign system : False
```

**Comment by asmeurer** [comment]
This is a known issue. When you do that, you have to list all dependencies explicitly (in this case, `bzip`).
