### ISSUE TITLE
Windows: build occasionally crashes upon creation of 'test-tmp_dir'

### ISSUE THREAD

**Issue by ukoethe** [conda/conda-build#577]
Platform: Windows 7, 64-bit, SSD

The error only occurs with `test-tmp_dir`. Moreover, it seems that it only happens when a package doesn't define tests, but I'm not sure. Here is the error message:

```
BUILD END: foo-1.0-0
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\conda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 190, in main
    args_func(args, p)
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 432, in args_func
    args.func(args, p)
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 419, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "C:\conda\lib\site-packages\conda_build\build.py", line 506, in test
    os.makedirs(tmp_dir)
  File "C:\conda\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 5] Access denied: 'C:\\conda\\conda-bld\\test-tmp_dir'

> conda info
Current conda install:

             platform : win-64
        conda version : 3.16.0-36-gd28d3f3-dirty
  conda-build version : 1.17.0+49.g0495f64
       python version : 2.7.9.final.0
     requests version : 2.7.0
     root environment : C:\conda  (writable)
  default environment : C:\conda\envs\foo
     envs directories : C:\conda\envs
        package cache : C:\conda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by asmeurer** [comment]
This will probably be fixed with the next version of conda.

**Comment by pelson** [comment]
> This will probably be fixed with the next version of conda.

Do you mean conda-build, which is where the traceback emanates? On that note, are there any conda-build release plans. I could really do with that skip section... :wink:

**Comment by asmeurer** [comment]
Nope, conda. [rm_rf now uses the trash](https://github.com/conda/conda/pull/1618), in conda 3.18.0, so functions in conda-build that use it to delete things should do a much better job of actually deleting them on Windows. 

I'm not 100% sure if that will fix this specific issue, though. 

Also, we do plan a conda-build release today I believe.
