### ISSUE TITLE
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml 

### ISSUE THREAD

**Issue by chdoig** [conda/conda-build#583]
I'm having issues trying to build a conda package from the pypi package mongoengine:

``` bash
$ conda build mongoengine/
Removing old build environment
Removing old work directory
BUILD START: mongoengine-0.10.0-py27_0
Fetching package metadata: ............
Solving package specifications: .
The following NEW packages will be INSTALLED:

    ncurses:    5.9-1        
    openssl:    1.0.1k-1     
    pip:        7.1.2-py27_0 
    pymongo:    2.8-py27_0   
    python:     2.7.10-0     
    readline:   6.2.5-1      
    setuptools: 18.1-py27_0  
    sqlite:     3.8.4.1-1    
    tk:         8.5.18-0     
    wheel:      0.24.0-py27_0
    zlib:       1.2.8-1      

Linking packages ...
[      COMPLETE      ]|##############################################################################################################################################################################################################| 100%
Removing old work directory
Source cache directory is: /anaconda/conda-bld/src_cache
Found source in cache: mongoengine-0.10.0.tar.gz
Extracting download
Package: mongoengine-0.10.0-py27_0
source tree in: /anaconda/conda-bld/work/mongoengine-0.10.0
+ /anaconda/envs/_build/bin/python setup.py install
Traceback (most recent call last):
  File "setup.py", line 83, in <module>
    **extra_opts
  File "/anaconda/envs/_build/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/dist.py", line 268, in __init__
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/dist.py", line 313, in fetch_build_eggs
  File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 836, in resolve
  File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 1081, in best_match
  File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 1093, in obtain
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/dist.py", line 380, in fetch_build_egg
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 617, in easy_install
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/package_index.py", line 594, in fetch_distribution
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/package_index.py", line 431, in find_packages
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/package_index.py", line 765, in scan_url
  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/package_index.py", line 283, in process_url
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/rednose/r
Command failed: /bin/bash -x -e /recipes/mongoengine/build.sh
```

I used:

``` bash
 conda skeleton pypi mongoengine
```

to create the recipe

This is the setup.py: https://github.com/MongoEngine/mongoengine/blob/v0.10.0/setup.py

and this is the meta.yaml:

``` yaml
 package:
  name: mongoengine
  version: "0.10.0"

source:
  fn: mongoengine-0.10.0.tar.gz
  url: https://pypi.python.org/packages/source/m/mongoengine/mongoengine-0.10.0.tar.gz
  md5: 41c863b67dd833334b5a47f734b76942
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mongoengine = mongoengine:main
    #
    # Would create an entry point called mongoengine that calls mongoengine.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pymongo >=2.7.1

  run:
    - python
    - pymongo >=2.7.1

test:
  # Python imports
  imports:
    - mongoengine
    - mongoengine.base
    - mongoengine.queryset

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - blinker
    - coverage ==3.7.1
    - nose
    - pillow >=2.0.0
    - python-dateutil
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://mongoengine.org/
  license: MIT License
  summary: 'MongoEngine is a Python Object-Document Mapper for working with MongoDB.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
```

I also don't understand what the conda's error means with "url=https://pypi.python.org/simple/rednose/r"... that's not a valid url

``` bash
$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.16.0
  conda-build version : 1.17.0
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /anaconda  (writable)
  default environment : /anaconda
     envs directories : /anaconda/envs
        package cache : /anaconda/pkgs
         channel URLs : https://conda.binstar.org/bokeh/osx-64/
                        https://conda.binstar.org/bokeh/noarch/
                        https://conda.binstar.org/chdoig/osx-64/
                        https://conda.binstar.org/chdoig/noarch/
                        https://conda.binstar.org/asmeurer/osx-64/
                        https://conda.binstar.org/asmeurer/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /.condarc
    is foreign system : False
```

**Comment by asmeurer** [comment]
You need to add rednose as a dependency in your meta.yaml. I don't know why skeleton didn't pick this up automatically.

**Comment by chdoig** [comment]
I tried that too:

```yaml
package:
  name: mongoengine
  version: "0.10.0"

source:
  fn: mongoengine-0.10.0.tar.gz
  url: https://pypi.python.org/packages/source/m/mongoengine/mongoengine-0.10.0.tar.gz
  md5: 41c863b67dd833334b5a47f734b76942
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mongoengine = mongoengine:main
    #
    # Would create an entry point called mongoengine that calls mongoengine.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pymongo >=2.7.1

  run:
    - python
    - pymongo >=2.7.1

test:
  # Python imports
  imports:
    - mongoengine
    - mongoengine.base
    - mongoengine.queryset

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - blinker
    - coverage ==3.7.1
    - nose
    - rednose
    - pillow >=2.0.0
    - python-dateutil
    - rednose
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://mongoengine.org/
  license: MIT License
  summary: 'MongoEngine is a Python Object-Document Mapper for working with MongoDB.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
```

Getting the same error.

**Comment by asmeurer** [comment]
That's the test requires. It needs to be in the `requirements` section (both `build` and `run`).

**Comment by chdoig** [comment]
Getting issue #584 when trying to build package python-termstyle (for rednose).

**Comment by chdoig** [comment]
It was fixed by adding both, nose and rednose, in the build and run requirements section. Would there be a way for conda skeleton to parse the file and add those dependencies in the correct place?

**Comment by IamGianluca** [comment]
I'm having a very similar problem in Windows. I'm trying to build `pymssql` for Windows 64-bit. My `meta.yaml` looks like this:

```
package:
  name: pymssql
  version: "2.1.2"

source:
  fn: pymssql-2.1.2.tar.gz
  url: https://pypi.python.org/packages/source/p/pymssql/pymssql-2.1.2.tar.gz
  md5: 064fc6f37d00073781221a363157688a
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pymssql = pymssql:main
    #
    # Would create an entry point called pymssql that calls pymssql.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pymssql.org
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'DB-API interface to Microsoft SQL Server for Python. (new Cython-based version)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
```

When I run `conda build pymssql` is get the following error message:

```
λ conda build pymssql
Removing old build environment
Removing old work directory
BUILD START: pymssql-2.1.2-py35_0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .........

The following NEW packages will be INSTALLED:

    msvc_runtime: 1.0.1-vc14_0  [vc14]
    pip:          8.1.1-py35_0
    python:       3.5.1-2
    setuptools:   20.3-py35_0
    wheel:        0.29.0-py35_0

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
Removing old work directory
Source cache directory is: C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\conda-bld\src_cache
Found source in cache: pymssql-2.1.2.tar.gz
Extracting download
Package: pymssql-2.1.2-py35_0
source tree in: C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\conda-bld\work\pymssql-2.1.2
Warning: Couldn't find Visual Studio: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat'

C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\conda-bld\work\pymssql-2.1.2 {git}{hg}
{lamb} set INCLUDE=C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\Library\include;

C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\conda-bld\work\pymssql-2.1.2 {git}{hg}
{lamb} set LIB=C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\Library\lib;

C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\conda-bld\work\pymssql-2.1.2 {git}{hg}
{lamb} REM ===== end generated header =====

C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\conda-bld\work\pymssql-2.1.2 {git}{hg}
{lamb} "C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\python.exe" setup.py install
setup.py: platform.system() => 'Windows'
setup.py: platform.architecture() => ('64bit', 'WindowsPE')
Traceback (most recent call last):
  File "setup.py", line 464, in <module>
    ext_modules = ext_modules(),
  File "C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\lib\distutils\core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\lib\site-packages\setuptools-20.3-py3.5.egg\setuptools\dist.py", line 269, in __init__
  File "C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\lib\site-packages\setuptools-20.3-py3.5.egg\setuptools\dist.py", line 313, in fetch_build_eggs
  File "C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\lib\site-packages\setuptools-20.3-py3.5.egg\pkg_resources\__init__.py", line 827, in resolve
  File "C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\lib\site-packages\setuptools-20.3-py3.5.egg\pkg_resources\__init__.py", line 1072, in best_match
  File "C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\lib\site-packages\setuptools-20.3-py3.5.egg\pkg_resources\__init__.py", line 1084, in obtain
  File "C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\lib\site-packages\setuptools-20.3-py3.5.egg\setuptools\dist.py", line 380, in fetch_build_egg
  File "C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\lib\site-packages\setuptools-20.3-py3.5.egg\setuptools\command\easy_install.py", line 628, in easy_install
  File "C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\lib\site-packages\setuptools-20.3-py3.5.egg\setuptools\package_index.py", line 608, in fetch_distribution
  File "C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\lib\site-packages\setuptools-20.3-py3.5.egg\setuptools\package_index.py", line 445, in find_packages
  File "C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\lib\site-packages\setuptools-20.3-py3.5.egg\setuptools\package_index.py", line 779, in scan_url
  File "C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\lib\site-packages\setuptools-20.3-py3.5.egg\setuptools\package_index.py", line 287, in process_url
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/setuptools_git/r

C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\conda-bld\work\pymssql-2.1.2 {git}{hg}
{lamb} if errorlevel 1 exit 1
Command failed: C:\WINDOWS\system32\cmd.exe /c call bld.bat
```

In this case it's complaining `setuptools_git` is missing, but `setuptools` is actually in my requirements in `meta.yaml`.

**Comment by ericdill** [comment]
@IamGianluca  You seem to be correctly identifying that it is complaining about missing `setuptools-git`. You should include that in the build requirements section of your meta.yaml. `setuptools` and `setuptools-git` are two different packages.  You might have to make a conda package for setuptools-git, but that shouldn't be too hard as there seem to be a number of conda packages for it already.

```
$ anaconda search -t conda setuptools | grep git
Using Anaconda Cloud api site https://api.anaconda.org
     Trentonoliphant/setuptools-git |      1.1 | conda           | win-32, win-64 
                                          : https://github.com/wichert/setuptools-git
                                          : https://github.com/Connexions/bamboo.setuptools_version
     auto/setuptools-git       |      1.0 | conda           | linux-64, linux-32
                                          : https://github.com/wichert/setuptools-git
     calex/setuptools-git      |      1.1 | conda           | linux-64       
     hargup/setuptools-git     |          | conda           | None-None, linux-64
     hobs/setuptools-git       |      1.1 | conda           | linux-64       
     lsst/setuptools-git       |          | conda           | linux-64, osx-64
     poppy-project/setuptools-git |      1.1 | conda           | linux-armv7l, osx-64
```

**Comment by IamGianluca** [comment]
@ericdill Thank you for your reply! It actually worked but I now have another issue which avoid the build to complete successfully. 

```
$ conda build pymssql                                                                                          
Removing old build environment                                                                                 
Removing old work directory                                                                                    
BUILD START: pymssql-2.1.2-py35_0                                                                              
Using Anaconda Cloud api site https://api.anaconda.org                                                         
Fetching package metadata: ......                                                                              
Solving package specifications: .........                                                                      
                                                                                                               
The following NEW packages will be INSTALLED:                                                                  
                                                                                                               
    msvc_runtime:   1.0.1-vc14_0  [vc14]                                                                       
    pip:            8.1.1-py35_0                                                                               
    python:         3.5.1-2                                                                                    
    setuptools:     20.3-py35_0                                                                                
    setuptools-git: 1.1-py35_0                                                                                 
    wheel:          0.29.0-py35_0                                                                              
                                                                                                               
Linking packages ...                                                                                           
[      COMPLETE      ]|##################################################| 100%                                
Removing old work directory                                                                                    
Source cache directory is: C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\conda-bld\src_cache       
Found source in cache: pymssql-2.1.2.tar.gz                                                                    
Extracting download                                                                                            
Package: pymssql-2.1.2-py35_0                                                                                  
source tree in: C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\conda-bld\work\pymssql-2.1.2         
Warning: Couldn't find Visual Studio: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat
'                                                                                                              
                                                                                                               
C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\conda-bld\work\pymssql-2.1.2 {git}{hg}               
{lamb} set INCLUDE=C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\Library\include;      
                                                                                                               
C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\conda-bld\work\pymssql-2.1.2 {git}{hg}               
{lamb} set LIB=C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\Library\lib;              
                                                                                                               
C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\conda-bld\work\pymssql-2.1.2 {git}{hg}               
{lamb} REM ===== end generated header =====                                                                    
                                                                                                               
C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\conda-bld\work\pymssql-2.1.2 {git}{hg}               
{lamb} "C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\envs\_build\python.exe" setup.py install     
setup.py: platform.system() => 'Windows'                                                                       
setup.py: platform.architecture() => ('64bit', 'WindowsPE')                                                    
running install                                                                                                
running bdist_egg                                                                                              
running egg_info                                                                                               
writing top-level names to pymssql.egg-info\top_level.txt                                                      
writing pymssql.egg-info\PKG-INFO                                                                              
writing dependency_links to pymssql.egg-info\dependency_links.txt                                              
reading manifest file 'pymssql.egg-info\SOURCES.txt'                                                           
writing manifest file 'pymssql.egg-info\SOURCES.txt'                                                           
installing library code to build\bdist.win-amd64\egg                                                           
running install_lib                                                                                            
running build_ext                                                                                              
building '_mssql' extension                                                                                    
error: Unable to find vcvarsall.bat                                                                            
                                                                                                               
C:\Users\gianluca.rossi\AppData\Local\Continuum\Anaconda3\conda-bld\work\pymssql-2.1.2 {git}{hg}               
{lamb} if errorlevel 1 exit 1                                                                                  
Command failed: C:\WINDOWS\system32\cmd.exe /c call bld.bat                                                    
```

I did a little [research](http://stackoverflow.com/questions/2817869/error-unable-to-find-vcvarsall-bat) and it seems I should install Microsoft C++ compiler for python (?). It seems like madness to me. Isn't there a better solution?

Should I open a separate issue for this?

**Comment by ericdill** [comment]
@IamGianluca I would suggest moving this issue to the conda mailing list: https://groups.google.com/a/continuum.io/forum/#!forum/conda 

I'll be happy to help you more over there. I'd like to avoid having this discussion on the conda-build issue tracker so as to avoid hammering the inboxes of the conda-build devs.
