### ISSUE TITLE
Could not find unpacked source dir exception

### ISSUE THREAD

**Issue by chdoig** [conda/conda-build#584]
When trying to build python-termstyle (dependency of rednose) to add in meta.yaml for issue #583.

I'm getting the following error:

```bash
$ conda skeleton pypi python-termstyle
More than one source version is available for python-termstyle:
Using the one with the least source size
use --manual-url to override this behavior
Using url https://pypi.python.org/packages/source/p/python-termstyle/python-termstyle-0.1.10.tgz (3 KB) for python-termstyle.
Downloading python-termstyle
Using cached download
Unpacking python-termstyle...
done
working in /var/folders/6j/hvntz4gs0pg9kcvxrzxnf0y40000gp/T/tmpE33rbhconda_skeleton_python-termstyle-0.1.10.tgz
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/anaconda/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 272, in main
    args_func(args, p)
  File "/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 429, in args_func
    args.func(args, p)
  File "/anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 286, in execute
    pypi.main(args, parser)
  File "/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 341, in main
    get_package_metadata(args, package, d, data)
  File "/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 478, in get_package_metadata
    python_version=args.python_version)
  File "/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 737, in get_pkginfo
    src_dir = get_dir(tempdir)
  File "/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 679, in get_dir
    raise Exception("could not find unpacked source dir")
Exception: could not find unpacked source dir
```

```bash
Current conda install:

             platform : osx-64
        conda version : 3.16.0
  conda-build version : 1.17.0
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /anaconda  (writable)
  default environment : /anaconda
     envs directories : /anaconda/envs
        package cache : /anaconda/pkgs
         channel URLs : https://conda.binstar.org/bokeh/osx-64/
                        https://conda.binstar.org/bokeh/noarch/
                        https://conda.binstar.org/chdoig/osx-64/
                        https://conda.binstar.org/chdoig/noarch/
                        https://conda.binstar.org/asmeurer/osx-64/
                        https://conda.binstar.org/asmeurer/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/cdoig/.condarc
    is foreign system : False
```

**Comment by asmeurer** [comment]
I see. It expects the source to have at least one directory, but the termstyle source is just setup.py and termstyle.py.

**Comment by chdoig** [comment]
Thanks!
