### ISSUE TITLE
conda metapackage not working: _build/info/index.json not found

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda/conda-build#599]
Dear All,

I am unable to build a package with `conda metapackage`. I think it all started after doing `conda update --all` in a dedicated conda installation that I have for building new packages.

This is the output when executing the `conda metapackage` command:
```
Removing old build environment
Removing old work directory
BUILD START: cgat-devel-0.2-nppy27r3.2.1_0
Removing old work directory
Package: cgat-devel-0.2-nppy27r3.2.1_0
no source
number of files: 1
Fixing permissions
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/sebastian/conda/conda-build/build-3/bin/conda-metapackage", line 5, in <module>
    sys.exit(main())
  File "/sebastian/conda/conda-build/build-3/lib/python2.7/site-packages/conda_build/main_metapackage.py", line 107, in main
    args_func(args, p)
  File "/sebastian/conda/conda-build/build-3/lib/python2.7/site-packages/conda_build/main_build.py", line 429, in args_func
    args.func(args, p)
  File "/sebastian/conda/conda-build/build-3/lib/python2.7/site-packages/conda_build/main_metapackage.py", line 124, in execute
    build(m)
  File "/sebastian/conda/conda-build/build-3/lib/python2.7/site-packages/conda_build/build.py", line 460, in build
    include_recipe=bool(m.path) and include_recipe)
  File "/sebastian/conda/conda-build/build-3/lib/python2.7/site-packages/conda_build/build.py", line 182, in create_info_files
    with open(join(config.info_dir, 'index.json'), **mode_dict) as fo:
IOError: [Errno 2] No such file or directory: '/sebastian/conda/conda-build/build-3/envs/_build/info/index.json'
```

The output of `conda info` is:
```
Current conda install:

             platform : linux-64
        conda version : 3.17.0
  conda-build version : 1.17.0
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /sebastian/conda/conda-build/build-3  (writable)
  default environment : /sebastian/conda/conda-build/build-3
     envs directories : /sebastian/conda/conda-build/build-3/envs
        package cache : /sebastian/conda/conda-build/build-3/pkgs
         channel URLs : https://conda.binstar.org/cgat/linux-64/
                        https://conda.binstar.org/cgat/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.binstar.org/r/linux-64/
                        https://conda.binstar.org/r/noarch/
                        https://conda.binstar.org/asmeurer/linux-64/
                        https://conda.binstar.org/asmeurer/noarch/
          config file : /ifs/home/sebastian/.condarc
    is foreign system : False
```

Many thanks for any help!

Best regards,
Sebastian.

**Comment by sebastian-luna-valero** [comment]
Dear All,

This is just to let you know that the issue seems to be solved with the new version of conda-build:
```
The following packages will be UPDATED:

    anaconda-build:  0.10.7-py27_0 --> 0.11.0-py27_0
    anaconda-client: 1.0.1-py27_0  --> 1.0.2-py27_0 
    conda:           3.17.0-py27_0 --> 3.18.1-py27_0
    conda-build:     1.17.0-py27_0 --> 1.18.0-py27_0
    pillow:          2.9.0-py27_0  --> 3.0.0-py27_0 
    psutil:          2.2.1-py27_0  --> 3.2.2-py27_0 

Proceed ([y]/n)? y
```

Many thanks,
Sebastian.
