### ISSUE TITLE
skeleton pypi doesn't work with cobra

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#60]
``` pytb
$conda skeleton pypi cobra
Using url https://pypi.python.org/packages/source/c/cobra/cobra-0.2.1.tar.gz (1719270) for cobra.
Downloading cobra (use --no-download to skip this step)
Using cached download
Unpacking cobra...
done
working in /var/folders/yc/8wpl9rlx47qgzxqpcf003k280000gn/T/tmpehwr8econda_skeleton
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/bin/conda-skeleton", line 12, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/main_skeleton.py", line 78, in main
    args.func(args, p)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/main_skeleton.py", line 85, in execute
    pypi.main(args, parser)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/pypi.py", line 246, in main
    run_setuppy(src_dir)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/pypi.py", line 381, in run_setuppy
    exec(compile(f.read(), 'setup.py', 'exec'), d)
  File "setup.py", line 1, in <module>
    #!/usr/bin/env python
ImportError: No module named 'ez_setup'
```

In https://github.com/conda/conda-build/pull/59 I get

``` pytb
$conda skeleton pypi cobra
Using url https://pypi.python.org/packages/source/c/cobra/cobra-0.2.1.tar.gz (1719270) for cobra.
Downloading cobra (use --no-download to skip this step)
Using cached download
Unpacking cobra...
done
working in /var/folders/yc/8wpl9rlx47qgzxqpcf003k280000gn/T/tmpoxgw5jconda_skeleton
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/bin/conda-skeleton", line 12, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/main_skeleton.py", line 79, in main
    args.func(args, p)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/main_skeleton.py", line 86, in execute
    pypi.main(args, parser)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/pypi.py", line 273, in main
    run_setuppy(tempdir, src_dir)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/pypi.py", line 406, in run_setuppy
    with open(join(src_dir, 'setup.py'), encoding='utf-8') as setuppy:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/yc/8wpl9rlx47qgzxqpcf003k280000gn/T/tmpoxgw5jconda_skeleton/setup.py'
```

**Comment by aebrahim** [comment]
FWIW cobra no longer uses ez_setup.py, so this can probably be closed.

**Comment by msarahan** [comment]
works today.  Closing
