### ISSUE TITLE
Build fails for python-levenshtein via pypi skeleton - Win64 - Python 3.4.3

### ISSUE THREAD

**Issue by bmcguirk** [conda/conda-build#608]
Hi guys - 

Just doing what I'm told and posting this issue here. Here's the full readout of everything I did before the build failed: 

    PS C:\Anaconda3\pkg_assembly> conda update --all
    Fetching package metadata: ....
    Solving package specifications: ...............
    Package plan for installation in environment C:\Anaconda3:

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        binstar-0.12               |                2          528 B
        alabaster-0.7.6            |           py34_0          14 KB
        comtypes-1.1.2             |           py34_0         220 KB
        cython-0.23.2              |           py34_0         1.9 MB
        funcsigs-0.4               |           py34_0          19 KB
        greenlet-0.4.9             |           py34_0          13 KB
        jedi-0.9.0                 |           py34_0         196 KB
        llvmlite-0.7.0             |           py34_5         5.2 MB
        multipledispatch-0.4.8     |           py34_0          12 KB
        path.py-8.1.1              |           py34_0          46 KB
        pillow-2.9.0               |           py34_0         945 KB
        psutil-3.2.1               |           py34_0         106 KB
        py-1.4.30                  |           py34_0         127 KB
        pyflakes-1.0.0             |           py34_0          98 KB
        pytz-2015.6                |           py34_0         166 KB
        sqlalchemy-1.0.8           |           py34_0         1.4 MB
        toolz-0.7.4                |           py34_0          53 KB
        xlrd-0.9.4                 |           py34_0         182 KB
        argcomplete-1.0.0          |           py34_0          84 KB
        astropy-1.0.4              |       np19py34_0         5.4 MB
        babel-2.0                  |           py34_0         2.3 MB
        bcolz-0.11.0               |           py34_0         324 KB
        cffi-1.1.2                 |           py34_0         107 KB
        clyent-0.4.0               |           py34_0          15 KB
        h5py-2.5.0                 |       np19py34_2         575 KB
        networkx-1.10              |           py34_0         1.1 MB
        nltk-3.0.5                 |           py34_0         1.7 MB
        numba-0.21.0               |       np19py34_0         1.3 MB
        numexpr-2.4.4              |       np19py34_0         108 KB
        openpyxl-2.0.2             |           py34_0         208 KB
        patsy-0.4.0                |       np19py34_0         368 KB
        pytest-2.8.0               |           py34_0         256 KB
        sympy-0.7.6.1              |           py34_0         6.5 MB
        xlwings-0.4.0              |           py34_0         356 KB
        cryptography-0.9.3         |           py34_0         1.1 MB
        datashape-0.4.7            |           py34_0          84 KB
        jupyter_core-4.0.6         |           py34_0          97 KB
        pbr-1.3.0                  |           py34_0         126 KB
        pytables-3.2.1.1           |       np19py34_0         1.5 MB
        sphinx-1.2.3               |           py34_0         1.1 MB
        mock-1.3.0                 |           py34_0          99 KB
        odo-0.3.4                  |           py34_0         206 KB
        blaze-core-0.8.3           |           py34_0         556 KB
        notebook-4.0.5             |           py34_0         4.3 MB
        qtconsole-4.0.1            |           py34_0         171 KB
        ipython-qtconsole-4.0.1    |           py34_0           4 KB
        spyder-2.3.6               |           py34_0         2.1 MB
        spyder-app-2.3.6           |           py34_0           7 KB
        ------------------------------------------------------------
                                               Total:        42.6 MB

    The following NEW packages will be INSTALLED:

        comtypes:          1.1.2-py34_0
        funcsigs:          0.4-py34_0
        pbr:               1.3.0-py34_0
        qtconsole:         4.0.1-py34_0

    The following packages will be UPDATED:

        alabaster:         0.7.3-py34_0      --> 0.7.6-py34_0
        argcomplete:       0.8.9-py34_0      --> 1.0.0-py34_0
        astropy:           1.0.3-np19py34_0  --> 1.0.4-np19py34_0
        babel:             1.3-py34_0        --> 2.0-py34_0
        bcolz:             0.9.0-np19py34_0  --> 0.11.0-py34_0
        binstar:           0.11.0-py34_0     --> 0.12-2
        blaze-core:        0.8.0-np19py34_0  --> 0.8.3-py34_0
        cffi:              1.1.0-py34_0      --> 1.1.2-py34_0
        clyent:            0.3.4-py34_0      --> 0.4.0-py34_0
        cryptography:      0.9.1-py34_0      --> 0.9.3-py34_0
        cython:            0.22.1-py34_0     --> 0.23.2-py34_0
        datashape:         0.4.5-np19py34_0  --> 0.4.7-py34_0
        greenlet:          0.4.7-py34_0      --> 0.4.9-py34_0
        h5py:              2.5.0-np19py34_1  --> 2.5.0-np19py34_2
        ipython-qtconsole: 3.2.0-py34_0      --> 4.0.1-py34_0
        jedi:              0.8.1-py34_0      --> 0.9.0-py34_0
        jupyter_core:      4.0.4-py34_0      --> 4.0.6-py34_0
        llvmlite:          0.5.0-py34_0      --> 0.7.0-py34_5
        mock:              1.0.1-py34_0      --> 1.3.0-py34_0
        multipledispatch:  0.4.7-py34_0      --> 0.4.8-py34_0
        networkx:          1.9.1-py34_0      --> 1.10-py34_0
        nltk:              3.0.3-np19py34_0  --> 3.0.5-py34_0
        notebook:          4.0.4-py34_0      --> 4.0.5-py34_0
        numba:             0.19.1-np19py34_0 --> 0.21.0-np19py34_0
        numexpr:           2.4.3-np19py34_0  --> 2.4.4-np19py34_0
        numpy:             1.9.2-py34_0      --> 1.9.3-py34_0
        odo:               0.3.2-np19py34_0  --> 0.3.4-py34_0
        openpyxl:          1.8.5-py34_0      --> 2.0.2-py34_0
        path.py:           7.6.1-py34_0      --> 8.1.1-py34_0
        patsy:             0.3.0-np19py34_0  --> 0.4.0-np19py34_0
        pillow:            2.8.2-py34_0      --> 2.9.0-py34_0
        psutil:            2.2.1-py34_0      --> 3.2.1-py34_0
        py:                1.4.27-py34_0     --> 1.4.30-py34_0
        pyflakes:          0.9.2-py34_0      --> 1.0.0-py34_0
        pytables:          3.2.0-np19py34_0  --> 3.2.1.1-np19py34_0
        pytest:            2.7.1-py34_0      --> 2.8.0-py34_0
        pytz:              2015.4-py34_0     --> 2015.6-py34_0
        spyder:            2.3.5.2-py34_0    --> 2.3.6-py34_0
        spyder-app:        2.3.5.2-py34_0    --> 2.3.6-py34_0
        sqlalchemy:        1.0.5-py34_0      --> 1.0.8-py34_0
        sympy:             0.7.6-py34_0      --> 0.7.6.1-py34_0
        toolz:             0.7.2-py34_0      --> 0.7.4-py34_0
        xlrd:              0.9.3-py34_0      --> 0.9.4-py34_0
        xlwings:           0.3.6-py34_0      --> 0.4.0-py34_0

    The following packages will be DOWNGRADED:

        sphinx:            1.3.1-py34_0      --> 1.2.3-py34_0

    Proceed ([y]/n)? y

    Fetching packages ...
    binstar-0.12-2 100% |###############################| Time: 0:00:00  33.84 kB/s
    alabaster-0.7. 100% |###############################| Time: 0:00:00 452.66 kB/s
    comtypes-1.1.2 100% |###############################| Time: 0:00:00   2.06 MB/s
    cython-0.23.2- 100% |###############################| Time: 0:00:00   7.36 MB/s
    funcsigs-0.4-p 100% |###############################| Time: 0:00:00   1.27 MB/s
    greenlet-0.4.9 100% |###############################| Time: 0:00:00 439.76 kB/s
    jedi-0.9.0-py3 100% |###############################| Time: 0:00:00   2.07 MB/s
    llvmlite-0.7.0 100% |###############################| Time: 0:00:00   6.82 MB/s
    multipledispat 100% |###############################| Time: 0:00:00 770.21 kB/s
    path.py-8.1.1- 100% |###############################| Time: 0:00:00   1.51 MB/s
    pillow-2.9.0-p 100% |###############################| Time: 0:00:00   5.64 MB/s
    psutil-3.2.1-p 100% |###############################| Time: 0:00:00   1.74 MB/s
    py-1.4.30-py34 100% |###############################| Time: 0:00:00   2.08 MB/s
    pyflakes-1.0.0 100% |###############################| Time: 0:00:00   1.61 MB/s
    pytz-2015.6-py 100% |###############################| Time: 0:00:00   1.36 MB/s
    sqlalchemy-1.0 100% |###############################| Time: 0:00:00   5.79 MB/s
    toolz-0.7.4-py 100% |###############################| Time: 0:00:00   1.16 MB/s
    xlrd-0.9.4-py3 100% |###############################| Time: 0:00:00   2.39 MB/s
    argcomplete-1. 100% |###############################| Time: 0:00:00   1.38 MB/s
    astropy-1.0.4- 100% |###############################| Time: 0:00:00   9.34 MB/s
    babel-2.0-py34 100% |###############################| Time: 0:00:00   7.44 MB/s
    bcolz-0.11.0-p 100% |###############################| Time: 0:00:00   3.04 MB/s
    cffi-1.1.2-py3 100% |###############################| Time: 0:00:00   2.34 MB/s
    clyent-0.4.0-p 100% |###############################| Time: 0:00:00 960.96 kB/s
    h5py-2.5.0-np1 100% |###############################| Time: 0:00:00   3.77 MB/s
    networkx-1.10- 100% |###############################| Time: 0:00:00   4.29 MB/s
    nltk-3.0.5-py3 100% |###############################| Time: 0:00:00   7.07 MB/s
    numba-0.21.0-n 100% |###############################| Time: 0:00:00   5.67 MB/s
    numexpr-2.4.4- 100% |###############################| Time: 0:00:00   1.41 MB/s
    openpyxl-2.0.2 100% |###############################| Time: 0:00:00   2.74 MB/s
    patsy-0.4.0-np 100% |###############################| Time: 0:00:00   4.02 MB/s
    pytest-2.8.0-p 100% |###############################| Time: 0:00:00   2.37 MB/s
    sympy-0.7.6.1- 100% |###############################| Time: 0:00:00   9.98 MB/s
    xlwings-0.4.0- 100% |###############################| Time: 0:00:00   2.92 MB/s
    cryptography-0 100% |###############################| Time: 0:00:00   5.14 MB/s
    datashape-0.4. 100% |###############################| Time: 0:00:00   1.37 MB/s
    jupyter_core-4 100% |###############################| Time: 0:00:00   2.13 MB/s
    pbr-1.3.0-py34 100% |###############################| Time: 0:00:00   2.06 MB/s
    pytables-3.2.1 100% |###############################| Time: 0:00:00   6.22 MB/s
    sphinx-1.2.3-p 100% |###############################| Time: 0:00:00   1.38 MB/s
    mock-1.3.0-py3 100% |###############################| Time: 0:00:00   2.00 MB/s
    odo-0.3.4-py34 100% |###############################| Time: 0:00:00   2.71 MB/s
    blaze-core-0.8 100% |###############################| Time: 0:00:00   4.05 MB/s
    notebook-4.0.5 100% |###############################| Time: 0:00:00   9.86 MB/s
    qtconsole-4.0. 100% |###############################| Time: 0:00:00   2.24 MB/s
    ipython-qtcons 100% |###############################| Time: 0:00:00 253.19 kB/s
    spyder-2.3.6-p 100% |###############################| Time: 0:00:00   8.25 MB/s
    spyder-app-2.3 100% |###############################| Time: 0:00:00 475.77 kB/s
    Extracting packages ...
    [      COMPLETE      ]|##################################################| 100%
    Unlinking packages ...
    menuinst Exception:Traceback (most recent call last):                    |  31%
      File "C:\Anaconda3\lib\site-packages\conda\install.py", line 317, in mk_menus
        menuinst.install(join(prefix, f), remove, prefix)
      File "C:\Anaconda3\lib\site-packages\menuinst\__init__.py", line 37, in install
        ShortCut(m, sc, prefix=prefix).remove()
      File "C:\Anaconda3\lib\site-packages\menuinst\win32.py", line 62, in remove
        self.create(remove=True)
      File "C:\Anaconda3\lib\site-packages\menuinst\win32.py", line 121, in create
        rm_rf(dst)
      File "C:\Anaconda3\lib\site-packages\menuinst\utils.py", line 19, in rm_rf
        os.unlink(path)
    PermissionError: [WinError 5] Access is denied: 'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Anaconda (64
    -bit)\\IPython (Py 3.4) QTConsole.lnk'
    menuinst Exception:Traceback (most recent call last):############        |  84%
      File "C:\Anaconda3\lib\site-packages\conda\install.py", line 317, in mk_menus
        menuinst.install(join(prefix, f), remove, prefix)
      File "C:\Anaconda3\lib\site-packages\menuinst\__init__.py", line 37, in install
        ShortCut(m, sc, prefix=prefix).remove()
      File "C:\Anaconda3\lib\site-packages\menuinst\win32.py", line 62, in remove
        self.create(remove=True)
      File "C:\Anaconda3\lib\site-packages\menuinst\win32.py", line 121, in create
        rm_rf(dst)
      File "C:\Anaconda3\lib\site-packages\menuinst\utils.py", line 19, in rm_rf
        os.unlink(path)
    PermissionError: [WinError 5] Access is denied: 'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Anaconda (64
    -bit)\\Spyder.lnk'
    [      COMPLETE      ]|##################################################| 100%
    Linking packages ...
    menuinst Exception:Traceback (most recent call last):################    |  93%
      File "C:\Anaconda3\lib\site-packages\conda\install.py", line 317, in mk_menus
        menuinst.install(join(prefix, f), remove, prefix)
      File "C:\Anaconda3\lib\site-packages\menuinst\__init__.py", line 42, in install
        ShortCut(m, sc, prefix=prefix).create()
      File "C:\Anaconda3\lib\site-packages\menuinst\win32.py", line 133, in create
        u'' + icon,
    OSError: Failed to create shortcut 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Anaconda (64-bit)\IPython (Py 3
    .4) QTConsole.lnk' - error 0x80070005
    menuinst Exception:Traceback (most recent call last):#################   |  95%
      File "C:\Anaconda3\lib\site-packages\conda\install.py", line 317, in mk_menus
        menuinst.install(join(prefix, f), remove, prefix)
      File "C:\Anaconda3\lib\site-packages\menuinst\__init__.py", line 42, in install
        ShortCut(m, sc, prefix=prefix).create()
      File "C:\Anaconda3\lib\site-packages\menuinst\win32.py", line 133, in create
        u'' + icon,
    OSError: Failed to create shortcut 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Anaconda (64-bit)\Spyder.lnk' -
     error 0x80070005
    [      COMPLETE      ]|##################################################| 100%
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!
    !!  The 'binstar' conda package has been renamed to 'anaconda-client'.
    !!  Please run:
    !!
    !!    conda install anaconda-client
    !!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    PS C:\Anaconda3\pkg_assembly> conda install anaconda-client
    Fetching package metadata: ....
    Solving package specifications: .
    Package plan for installation in environment C:\Anaconda3:

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        anaconda-client-1.0.2      |           py34_0         146 KB

    The following NEW packages will be INSTALLED:

        anaconda-client: 1.0.2-py34_0

    Proceed ([y]/n)? y

    Fetching packages ...
    anaconda-clien 100% |###############################| Time: 0:00:00   2.36 MB/s
    Extracting packages ...
    [      COMPLETE      ]|##################################################| 100%
    Linking packages ...
    [      COMPLETE      ]|##################################################| 100%
    PS C:\Anaconda3\pkg_assembly> conda skeleton pypi python-levenshtein
    python-levenshtein not found, trying python-Levenshtein
    Warning, the following versions were found for python-Levenshtein
    0.12.0
    0.11.2
    0.11.1
    0.10.2
    0.10.1
    Using 0.12.0
    Use --version to specify a different version.
    Using url https://pypi.python.org/packages/source/p/python-Levenshtein/python-Levenshtein-0.12.0.tar.gz (47 KB) for pyth
    on-Levenshtein.
    Downloading python-Levenshtein
    Using cached download
    Unpacking python-Levenshtein...
    done
    working in C:\Users\BRIAN~1.MCG\AppData\Local\Temp\tmpufhccve0conda_skeleton_python-Levenshtein-0.12.0.tar.gz
    Fetching package metadata: ......
    Solving package specifications: .
    The following NEW packages will be INSTALLED:

        numpy:      1.9.3-py34_0
        pip:        7.1.2-py34_0
        python:     3.4.3-0
        pyyaml:     3.11-py34_2
        setuptools: 18.3.2-py34_0
        wheel:      0.26.0-py34_1

    Linking packages ...
    [      COMPLETE      ]|##################################################| 100%
    Applying patch: 'C:\\Users\\BRIAN~1.MCG\\AppData\\Local\\Temp\\tmpufhccve0conda_skeleton_python-Levenshtein-0.12.0.tar.g
    z\\pypi-distutils.patch'
    patching file `core.py'
    Hunk #1 succeeded at 168 with fuzz 2 (offset 1 line).
    Writing recipe for python-levenshtein
    Done
    PS C:\Anaconda3\pkg_assembly> conda build python-levenshtein
    Removing old build environment
    Removing old work directory
    BUILD START: python-levenshtein-0.12.0-py34_0
    Fetching package metadata: ......
    Solving package specifications: .
    The following NEW packages will be INSTALLED:

        pip:        7.1.2-py34_0
        python:     3.4.3-0
        setuptools: 18.3.2-py34_0
        wheel:      0.26.0-py34_1

    Linking packages ...
    [      COMPLETE      ]|##################################################| 100%
    Removing old work directory
    Source cache directory is: C:\Anaconda3\conda-bld\src_cache
    Found source in cache: python-Levenshtein-0.12.0.tar.gz
    Extracting download
    Package: python-levenshtein-0.12.0-py34_0
    source tree in: C:\Anaconda3\conda-bld\work\python-Levenshtein-0.12.0

    C:\Anaconda3\conda-bld\work\python-Levenshtein-0.12.0>call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvar
    sall.bat" amd64
    Setting environment for using Microsoft Visual Studio 2008 x64 cross tools.

    C:\Anaconda3\conda-bld\work\python-Levenshtein-0.12.0>REM ===== end generated header =====

    C:\Anaconda3\conda-bld\work\python-Levenshtein-0.12.0>"C:\Anaconda3\envs\_build\python.exe" setup.py install
    running install
    running bdist_egg
    running egg_info
    writing requirements to python_Levenshtein.egg-info\requires.txt
    writing dependency_links to python_Levenshtein.egg-info\dependency_links.txt
    writing entry points to python_Levenshtein.egg-info\entry_points.txt
    writing namespace_packages to python_Levenshtein.egg-info\namespace_packages.txt
    writing python_Levenshtein.egg-info\PKG-INFO
    writing top-level names to python_Levenshtein.egg-info\top_level.txt
    reading manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*pyc' found anywhere in distribution
    warning: no previously-included files matching '*so' found anywhere in distribution
    warning: no previously-included files matching '.project' found anywhere in distribution
    warning: no previously-included files matching '.pydevproject' found anywhere in distribution
    writing manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
    installing library code to build\bdist.win-amd64\egg
    running install_lib
    running build_py
    creating build
    creating build\lib.win-amd64-3.4
    creating build\lib.win-amd64-3.4\Levenshtein
    copying Levenshtein\StringMatcher.py -> build\lib.win-amd64-3.4\Levenshtein
    copying Levenshtein\__init__.py -> build\lib.win-amd64-3.4\Levenshtein
    copying Levenshtein\_levenshtein.c -> build\lib.win-amd64-3.4\Levenshtein
    copying Levenshtein\_levenshtein.h -> build\lib.win-amd64-3.4\Levenshtein
    running build_ext
    building 'Levenshtein._levenshtein' extension
    creating build\temp.win-amd64-3.4
    creating build\temp.win-amd64-3.4\Release
    creating build\temp.win-amd64-3.4\Release\Levenshtein
    C:\Users\brian.mcguirk\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\x86_amd64\cl.exe /c /nol
    ogo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Anaconda3\envs\_build\include -IC:\Anaconda3\envs\_build\include /TcLevenshtein/_leve
    nshtein.c /Fobuild\temp.win-amd64-3.4\Release\Levenshtein/_levenshtein.obj
    _levenshtein.c
    Levenshtein/_levenshtein.c(714) : warning C4267: 'function' : conversion from 'size_t' to 'int', possible loss of data
    Levenshtein/_levenshtein.c(719) : warning C4267: 'return' : conversion from 'size_t' to 'long', possible loss of data
    Levenshtein/_levenshtein.c(732) : warning C4267: 'function' : conversion from 'size_t' to 'int', possible loss of data
    Levenshtein/_levenshtein.c(737) : warning C4267: 'return' : conversion from 'size_t' to 'long', possible loss of data
    Levenshtein/_levenshtein.c(798) : warning C4267: '=' : conversion from 'size_t' to 'long', possible loss of data
    Levenshtein/_levenshtein.c(814) : warning C4267: '=' : conversion from 'size_t' to 'long', possible loss of data
    Levenshtein/_levenshtein.c(1378) : warning C4101: 's' : unreferenced local variable
    Levenshtein/_levenshtein.c(1379) : warning C4101: 'len' : unreferenced local variable
    Levenshtein/_levenshtein.c(4176) : warning C4244: '=' : conversion from 'double' to 'size_t', possible loss of data
    Levenshtein/_levenshtein.c(4213) : warning C4244: 'initializing' : conversion from 'double' to 'size_t', possible loss o
    f data
    Levenshtein/_levenshtein.c(4214) : warning C4244: 'initializing' : conversion from 'double' to 'size_t', possible loss o
    f data
    Levenshtein/_levenshtein.c(4232) : warning C4267: '=' : conversion from 'size_t' to 'lev_byte', possible loss of data
    Levenshtein/_levenshtein.c(4369) : warning C4244: '=' : conversion from 'double' to 'size_t', possible loss of data
    Levenshtein/_levenshtein.c(4409) : warning C4244: 'initializing' : conversion from 'double' to 'size_t', possible loss o
    f data
    Levenshtein/_levenshtein.c(4410) : warning C4244: 'initializing' : conversion from 'double' to 'size_t', possible loss o
    f data
    Levenshtein/_levenshtein.c(4520) : warning C4267: '=' : conversion from 'size_t' to 'long', possible loss of data
    Levenshtein/_levenshtein.c(4534) : warning C4267: '=' : conversion from 'size_t' to 'long', possible loss of data
    Levenshtein/_levenshtein.c(4593) : warning C4267: '=' : conversion from 'size_t' to 'long', possible loss of data
    Levenshtein/_levenshtein.c(4607) : warning C4267: '=' : conversion from 'size_t' to 'long', possible loss of data
    Levenshtein/_levenshtein.c(4758) : warning C4244: 'return' : conversion from 'size_t' to 'double', possible loss of data

    Levenshtein/_levenshtein.c(4760) : warning C4244: 'return' : conversion from 'size_t' to 'double', possible loss of data

    Levenshtein/_levenshtein.c(4795) : warning C4244: 'initializing' : conversion from 'size_t' to 'double', possible loss o
    f data
    Levenshtein/_levenshtein.c(4915) : warning C4244: 'initializing' : conversion from 'size_t' to 'double', possible loss o
    f data
    Levenshtein/_levenshtein.c(5026) : warning C4244: '=' : conversion from 'size_t' to 'double', possible loss of data
    Levenshtein/_levenshtein.c(5126) : warning C4244: '=' : conversion from 'size_t' to 'double', possible loss of data
    C:\Users\brian.mcguirk\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\x86_amd64\link.exe /DLL
    /nologo /INCREMENTAL:NO /LIBPATH:C:\Anaconda3\envs\_build\libs /LIBPATH:C:\Anaconda3\envs\_build\PCbuild\amd64 /EXPORT:P
    yInit__levenshtein build\temp.win-amd64-3.4\Release\Levenshtein/_levenshtein.obj /OUT:build\lib.win-amd64-3.4\Levenshtei
    n\_levenshtein.pyd /IMPLIB:build\temp.win-amd64-3.4\Release\Levenshtein\_levenshtein.lib /MANIFESTFILE:build\temp.win-am
    d64-3.4\Release\Levenshtein\_levenshtein.pyd.manifest
       Creating library build\temp.win-amd64-3.4\Release\Levenshtein\_levenshtein.lib and object build\temp.win-amd64-3.4\Re
    lease\Levenshtein\_levenshtein.exp
    creating build\bdist.win-amd64
    creating build\bdist.win-amd64\egg
    creating build\bdist.win-amd64\egg\Levenshtein
    copying build\lib.win-amd64-3.4\Levenshtein\StringMatcher.py -> build\bdist.win-amd64\egg\Levenshtein
    copying build\lib.win-amd64-3.4\Levenshtein\_levenshtein.c -> build\bdist.win-amd64\egg\Levenshtein
    copying build\lib.win-amd64-3.4\Levenshtein\_levenshtein.h -> build\bdist.win-amd64\egg\Levenshtein
    copying build\lib.win-amd64-3.4\Levenshtein\_levenshtein.pyd -> build\bdist.win-amd64\egg\Levenshtein
    copying build\lib.win-amd64-3.4\Levenshtein\__init__.py -> build\bdist.win-amd64\egg\Levenshtein
    byte-compiling build\bdist.win-amd64\egg\Levenshtein\StringMatcher.py to StringMatcher.cpython-34.pyc
    byte-compiling build\bdist.win-amd64\egg\Levenshtein\__init__.py to __init__.cpython-34.pyc
    creating stub loader for Levenshtein\_levenshtein.pyd
    byte-compiling build\bdist.win-amd64\egg\Levenshtein\_levenshtein.py to _levenshtein.cpython-34.pyc
    creating build\bdist.win-amd64\egg\EGG-INFO
    copying python_Levenshtein.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
    copying python_Levenshtein.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
    copying python_Levenshtein.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
    copying python_Levenshtein.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
    copying python_Levenshtein.egg-info\namespace_packages.txt -> build\bdist.win-amd64\egg\EGG-INFO
    copying python_Levenshtein.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
    copying python_Levenshtein.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
    copying python_Levenshtein.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
    writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
    creating dist
    creating 'dist\python_Levenshtein-0.12.0-py3.4-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
    removing 'build\bdist.win-amd64\egg' (and everything under it)
    Processing python_Levenshtein-0.12.0-py3.4-win-amd64.egg
    creating c:\anaconda3\envs\_build\lib\site-packages\python_Levenshtein-0.12.0-py3.4-win-amd64.egg
    Extracting python_Levenshtein-0.12.0-py3.4-win-amd64.egg to c:\anaconda3\envs\_build\lib\site-packages
    Adding python-Levenshtein 0.12.0 to easy-install.pth file

    Installed c:\anaconda3\envs\_build\lib\site-packages\python_levenshtein-0.12.0-py3.4-win-amd64.egg
    Processing dependencies for python-Levenshtein==0.12.0
    Searching for setuptools==18.3.2
    Best match: setuptools 18.3.2
    Processing setuptools-18.3.2-py3.4.egg
    Adding setuptools 18.3.2 to easy-install.pth file
    Installing easy_install-script.py script to C:\Anaconda3\envs\_build\Scripts
    Installing easy_install.exe script to C:\Anaconda3\envs\_build\Scripts
    Installing easy_install-3.4-script.py script to C:\Anaconda3\envs\_build\Scripts
    Installing easy_install-3.4.exe script to C:\Anaconda3\envs\_build\Scripts

    Using c:\anaconda3\envs\_build\lib\site-packages\setuptools-18.3.2-py3.4.egg
    Finished processing dependencies for python-Levenshtein==0.12.0

    C:\Anaconda3\conda-bld\work\python-Levenshtein-0.12.0>if errorlevel 1 exit 1
    An unexpected error has occurred, please consider sending the
    following traceback to the conda GitHub issue tracker at:

        https://github.com/conda/conda-build/issues

    Include the output of the command 'conda info' in your report.

    Traceback (most recent call last):
      File "C:\Anaconda3\Scripts\conda-build-script.py", line 4, in <module>
        sys.exit(main())
      File "C:\Anaconda3\lib\site-packages\conda_build\main_build.py", line 190, in main
        args_func(args, p)
      File "C:\Anaconda3\lib\site-packages\conda_build\main_build.py", line 429, in args_func
        args.func(args, p)
      File "C:\Anaconda3\lib\site-packages\conda_build\main_build.py", line 384, in execute
        override_channels=args.override_channels, include_recipe=args.include_recipe)
      File "C:\Anaconda3\lib\site-packages\conda_build\build.py", line 417, in build
        windows.build(m)
      File "C:\Anaconda3\lib\site-packages\conda_build\windows.py", line 127, in build
        kill_processes()
      File "C:\Anaconda3\lib\site-packages\conda_build\windows.py", line 92, in kill_processes
        for n in psutil.get_pid_list():
    AttributeError: 'module' object has no attribute 'get_pid_list'
    PS C:\Anaconda3\pkg_assembly>
And, separately: 

    PS C:\Anaconda3\pkg_assembly> conda info
    Current conda install:

                 platform : win-64
            conda version : 3.17.0
      conda-build version : 1.17.0
           python version : 3.4.3.final.0
         requests version : 2.7.0
         root environment : C:\Anaconda3  (writable)
      default environment : C:\Anaconda3
         envs directories : C:\Anaconda3\envs
            package cache : C:\Anaconda3\pkgs
             channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/win-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : C:\Users\brian.mcguirk\.condarc
        is foreign system : False

**Comment by bmcguirk** [comment]
Possible duplicate of #527 but I'm not sure.

**Comment by jakirkham** [comment]
Guessing this was fixed at some point. FWIW we build [python-levenshtein]( https://github.com/conda-forge/python-levenshtein-feedstock ) in [conda-forge]( https://conda-forge.org/ ).
