### ISSUE TITLE
Build fails for bcbio-nextgen - linux-64 - Python 2.7

### ISSUE THREAD

**Issue by alexandrucoman** [conda/conda-build#619]
Hello,

I have encountered the following issue during the building of bcbio-nextgen recipe.

```
~ $ conda-build bcbio-nextgen --numpy 19 --no-binstar-upload
```

```
Removing old build environment
Removing old work directory
BUILD START: bcbio-nextgen-0.9.2a-py27_100
Fetching package metadata: ..........
Solving package specifications: ..................Your branch is up-to-date with 'origin/master'.
The following NEW packages will be INSTALLED:
    openssl:    1.0.1k-1     
    pip:        7.1.2-py27_0 
    python:     2.7.10-1     
    readline:   6.2-2        
    setuptools: 18.3.2-py27_0
    sqlite:     3.8.4.1-1    
    tk:         8.5.18-0     
    wheel:      0.26.0-py27_1
    zlib:       1.2.8-0      
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
Removing old work directory
checkout: u'master'

Cloning into '/home/travis/miniconda/conda-bld/work'...
done.
Already on 'master'
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
    https://github.com/conda/conda-build/issues
Include the output of the command 'conda info' in your report.
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 190, in main
    args_func(args, p)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 392, in build
    source.provide(m.path, m.get_section('source'))
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/source.py", line 269, in provide
    git_source(meta, recipe_dir)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/source.py", line 136, in git_source
    git_info()
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/source.py", line 160, in git_info
    stdout = stdout.decode(encoding, 'ignore')
TypeError: decode() argument 1 must be string, not None
```

The full log can be found [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/83559590/log.txt).

**Information regarding the environment**

```
~$ conda info
```

```
Current conda install:
             platform : linux-64
        conda version : 3.18.1
  conda-build version : 1.18.0
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /home/travis/miniconda  (writable)
  default environment : /home/travis/miniconda
     envs directories : /home/travis/miniconda/envs
        package cache : /home/travis/miniconda/pkgs
         channel URLs : https://conda.anaconda.org/bcbio-dev/linux-64/
                        https://conda.anaconda.org/bcbio-dev/noarch/
                        https://conda.anaconda.org/bcbio/linux-64/
                        https://conda.anaconda.org/bcbio/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/travis/.condarc
    is foreign system : False
```

**Environement setup**

**Download conda**
```
~$ wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
```

Output:

```
http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 23.21.145.66, 23.23.112.241, 54.83.3.29, ...
Connecting to repo.continuum.io (repo.continuum.io)|23.21.145.66|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24166764 (23M) [application/octet-stream]
Saving to: `miniconda.sh'
100%[======================================>] 24,166,764   102M/s   in 0.2s    
2015-10-04 14:35:19 (102 MB/s) - `miniconda.sh' saved [24166764/24166764]
```

**Install conda**

```
~$ bash miniconda.sh -b -p "$HOME/miniconda"
```

Output:

```
PREFIX=/home/travis/miniconda
installing: python-2.7.10-0 ...
installing: conda-env-2.4.2-py27_0 ...
installing: openssl-1.0.1k-1 ...
installing: pycosat-0.6.1-py27_0 ...
installing: pyyaml-3.11-py27_1 ...
installing: readline-6.2-2 ...
installing: requests-2.7.0-py27_0 ...
installing: sqlite-3.8.4.1-1 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-0 ...
installing: conda-3.16.0-py27_0 ...
installing: pycrypto-2.6.1-py27_0 ...
Python 2.7.10 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
```

**Upgrade conda**

```
~$ conda update --yes conda
```

Output:

```
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /home/travis/miniconda:
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    python-2.7.10              |                1        12.0 MB
    setuptools-18.3.2          |           py27_0         342 KB
    wheel-0.26.0               |           py27_1          76 KB
    conda-3.18.1               |           py27_0         172 KB
    pip-7.1.2                  |           py27_0         1.4 MB
    ------------------------------------------------------------
                                           Total:        13.9 MB
The following NEW packages will be INSTALLED:
    pip:        7.1.2-py27_0 
    setuptools: 18.3.2-py27_0
    wheel:      0.26.0-py27_1
The following packages will be UPDATED:
    conda:      3.16.0-py27_0 --> 3.18.1-py27_0
    python:     2.7.10-0      --> 2.7.10-1     
Fetching packages ...
python-2.7.10- 100% |################################| Time: 0:00:00  61.13 MB/s
setuptools-18. 100% |################################| Time: 0:00:00  27.00 MB/s
wheel-0.26.0-p 100% |################################| Time: 0:00:00  22.31 MB/s
conda-3.18.1-p 100% |################################| Time: 0:00:00  32.08 MB/s
pip-7.1.2-py27 100% |################################| Time: 0:00:00  45.50 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
```

**Install some conda packages**

```
~$ conda install --yes --quiet conda-build jinja2 toolz anaconda-client
```

Output:

```
Fetching package metadata: ....
Solving package specifications: ................
Package plan for installation in environment /home/travis/miniconda:
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    jpeg-8d                    |                0         699 KB
    libpng-1.6.17              |                0         214 KB
    patchelf-0.6               |                0         179 KB
    freetype-2.5.2             |                2         2.5 MB
    libtiff-4.0.2              |                1         930 KB
    markupsafe-0.23            |           py27_0          30 KB
    pillow-2.9.0               |           py27_0         781 KB
    pytz-2015.6                |           py27_0         173 KB
    six-1.9.0                  |           py27_0          17 KB
    toolz-0.7.4                |           py27_0          51 KB
    clyent-0.4.0               |           py27_0          14 KB
    jinja2-2.8                 |           py27_0         263 KB
    python-dateutil-2.4.2      |           py27_0         219 KB
    anaconda-client-1.0.2      |           py27_0          91 KB
    conda-build-1.18.0         |           py27_0         205 KB
    ------------------------------------------------------------
                                           Total:         6.3 MB
The following NEW packages will be INSTALLED:
    anaconda-client: 1.0.2-py27_0 
    clyent:          0.4.0-py27_0 
    conda-build:     1.18.0-py27_0
    freetype:        2.5.2-2      
    jinja2:          2.8-py27_0   
    jpeg:            8d-0         
    libpng:          1.6.17-0     
    libtiff:         4.0.2-1      
    markupsafe:      0.23-py27_0  
    patchelf:        0.6-0        
    pillow:          2.9.0-py27_0 
    python-dateutil: 2.4.2-py27_0 
    pytz:            2015.6-py27_0
    six:             1.9.0-py27_0 
    toolz:           0.7.4-py27_0 
```

**Install requirements for style checking**
```
~ $ conda install --yes --quiet pep8 pylint
```

```
Fetching package metadata: ....
Solving package specifications: ..................
Package plan for installation in environment /home/travis/miniconda:
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    pep8-1.6.2                 |           py27_0          47 KB
    logilab-common-0.63.2      |           py27_0         286 KB
    astroid-1.3.4              |           py27_0         205 KB
    pylint-1.4.2               |           py27_0         301 KB
    ------------------------------------------------------------
                                           Total:         839 KB
The following NEW packages will be INSTALLED:
    astroid:        1.3.4-py27_0 
    logilab-common: 0.63.2-py27_0
    pep8:           1.6.2-py27_0 
    pylint:         1.4.2-py27_0 
```

Thanks,
Alex

**Comment by pelson** [comment]
I just had the same issue. Would you mind providing you ``git --version``? I'm using a CentOS 5 image with ``git version 1.7.1``.

**Comment by ocefpaf** [comment]
I had the same issue and adding a `LANG=en_US.UTF-8` in my Centos 6 [docker image](https://github.com/ioos/conda-recipes/blob/master/Dockerfile#L43) fixed it.

**Comment by pelson** [comment]
Thanks @ocefpaf - I'll give that a shot!

**Comment by ocefpaf** [comment]
I forgot to mentioned that I also switched to Miniconda3 (even for the Py27 builds).

**Comment by alexandrucoman** [comment]
This issue is fixed by the following pull requests:
 - #614 - Fix `None` encoding bug
 - #621 - Add a method to shell out and execute a command through subprocess

Thanks,
Alex
