### ISSUE TITLE
"AttributeError: 'list' object has no attribute 'split'" via `conda skeleton pypi httpretty`

### ISSUE THREAD

**Issue by tomkinsc** [conda/conda-build#622]
Hi, I'm attempting to make a skeleton receipe for the PyPi package `httpretty`, a dependency of `moto`:

`conda skeleton pypi httpretty`

This results in an error with the following traceback:

    Traceback (most recent call last):
      File "/Users/tomkinsc/anaconda/bin/conda-skeleton", line 5, in <module>
        sys.exit(main())
      File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda_build/main_skeleton.py", line 272, in main
        args_func(args, p)
      File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda_build/main_build.py", line 468, in args_func
        args.func(args, p)
      File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda_build/main_skeleton.py", line 286, in execute
        pypi.main(args, parser)
      File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda_build/pypi.py", line 341, in main
        get_package_metadata(args, package, d, data)
      File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda_build/pypi.py", line 593, in get_package_metadata
        in pkginfo['tests_require']]))
      File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda_build/pypi.py", line 592, in <listcomp>
        d['tests_require'] = INDENT.join(sorted([spec_from_line(pkg) for pkg
      File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda/cli/common.py", line 473, in spec_from_line
        m = spec_pat.match(strip_comment(line))
      File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda/cli/common.py", line 470, in strip_comment
        return line.split('#')[0].rstrip()
    AttributeError: 'list' object has no attribute 'split'

And here is the output of `conda info`:

    Current conda install:
                 platform : osx-64
            conda version : 3.18.1
      conda-build version : 1.18.0
           python version : 3.4.3.final.0
         requests version : 2.7.0
         root environment : /Users/tomkinsc/anaconda  (writable)
      default environment : /Users/tomkinsc/anaconda
         envs directories : /Users/tomkinsc/anaconda/envs
            package cache : /Users/tomkinsc/anaconda/pkgs
             channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/osx-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : None
        is foreign system : False

**Comment by tomkinsc** [comment]
It seems this was due to httpretty [parsing its requirements file manually](https://github.com/keimlink/HTTPretty/blob/38ac76d3dabdda36bdc1b940deabebc884c28531/setup.py) and returning a 2xN list (depends, urls). The list also contained both dependencies and comment strings. This needs to be fixed upstream with httpretty to return a 1xN list of dependencies, sans comment strings (I've submitted a [PR](https://github.com/gabrielfalcao/HTTPretty/pull/261) there). 
Closing this issue for now.
