### ISSUE TITLE
conda skeleton fails for scipy package

### ISSUE THREAD

**Issue by pbowyer** [conda/conda-build#638]
``` bash
$ conda skeleton pypi mahotas
Warning, the following versions were found for mahotas
1.4.0
1.3.0
1.2.4
1.2.3
1.2.2
1.2.1
1.2
1.1.1
1.1.0
1.0.4
1.0.3
1.0.2
1.0.1
1.0
0.99
0.9.8
0.9.7
0.9.6
0.9.5
0.9.4
0.9.3
0.9.2
0.9.1
0.9
0.8.1
0.8
0.7.3
0.7.2
0.7.1
0.7
0.6.6
0.6.5
0.6.4
0.6.3
0.6.2
0.6.1
0.6
0.5.3
0.5.2
0.5.1
0.5
0.4
0.3
0.2
0.1
0.0.1
Using 1.4.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/m/mahotas/mahotas-1.4.0.tar.gz (1.5 MB) for mahotas.
Downloading mahotas
Using cached download
Unpacking mahotas...
done
working in /tmp/tmpoMBPakconda_skeleton_mahotas-1.4.0.tar.gz
Fetching package metadata: ......
Solving package specifications: .................
Applying patch: '/tmp/tmpoMBPakconda_skeleton_mahotas-1.4.0.tar.gz/pypi-distutils.patch'
patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/peter/anaconda/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/home/peter/anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 272, in main
    args_func(args, p)
  File "/home/peter/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/home/peter/anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 286, in execute
    pypi.main(args, parser)
  File "/home/peter/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 341, in main
    get_package_metadata(args, package, d, data)
  File "/home/peter/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 593, in get_package_metadata
    in pkginfo['tests_require']]))
TypeError: sequence item 0: expected string, NoneType found
```

``` bash
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.18.3
  conda-build version : 1.18.0
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : /home/peter/anaconda  (writable)
  default environment : /home/peter/anaconda
     envs directories : /home/peter/anaconda/envs
        package cache : /home/peter/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by jakirkham** [comment]
Can confirm seeing this on other packages as well. Pretty much any package that doesn't have test requirements.
