### ISSUE TITLE
Git required to build packages without git source

### ISSUE THREAD

**Issue by mausch** [conda/conda-build#647]
anaconda-client: 1.0.2-py34_0 
conda-build:     1.18.1-py34_0

I have a package with a local source path. When I try to build it in an environment without `git` I get the following error:

```
BUILD START: my_package-1.0.22-np19py34_0
Fetching package metadata: ........
Solving package specifications: ................................
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ...
    ------------------------------------------------------------
                                           Total:        47.4 MB

The following NEW packages will be INSTALLED:

    ...

Fetching packages ...
...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.4/site-packages/conda_build/main_build.py", line 190, in main
    args_func(args, p)
  File "/opt/conda/lib/python3.4/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/opt/conda/lib/python3.4/site-packages/conda_build/main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "/opt/conda/lib/python3.4/site-packages/conda_build/build.py", line 395, in build
    m.parse_again()
  File "/opt/conda/lib/python3.4/site-packages/conda_build/metadata.py", line 357, in parse_again
    self.meta = parse(get_contents(self.meta_path))
  File "/opt/conda/lib/python3.4/site-packages/conda_build/metadata.py", line 300, in get_contents
    env.globals.update(context_processor())
  File "/opt/conda/lib/python3.4/site-packages/conda_build/jinja_context.py", line 44, in context_processor
    ctx = get_environ()
  File "/opt/conda/lib/python3.4/site-packages/conda_build/environ.py", line 106, in get_dict
    d.update(**get_git_build_info(d['SRC_DIR']))
  File "/opt/conda/lib/python3.4/site-packages/conda_build/environ.py", line 47, in get_git_build_info
    env=env)
  File "/opt/conda/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
```

**Comment by groutr** [comment]
What does your meta.yaml file look like?

**Comment by mausch** [comment]
```
package:
    name: something
    version: 1.0.1
   
source:
    path: .

build:
    script: python setup.py install

requirements:
    build:
        - python ==3.4.3
        - setuptools
        - common_python_utilities 0.1*
        - flask 0.10*
        - flask-restful ==0.3.4
        - flask-restful-swagger ==0.19
        - sqlalchemy ==1.0.5
        - numpy ==1.9
        - scikit-learn ==0.16.1
        - scipy ==0.15.1
        - pymongo ==2.8
        - elasticsearch ==1.7
        - jsonpickle 0.8*
        - pytest ==2.7
        - coverage 3.7*
    run:
        - python ==3.4.3
        - common_python_utilities 0.1*
        - flask 0.10*
        - flask-restful ==0.3.4
        - flask-restful-swagger ==0.19
        - sqlalchemy ==1.0.5
        - numpy ==1.9
        - scikit-learn ==0.16.1
        - scipy ==0.15.1
        - pymongo ==2.8
        - elasticsearch ==1.7
        - jsonpickle 0.8*
        - pytest ==2.7
        - coverage 3.7*

test:
    requires:
        - pytest ==2.7
        - coverage 3.7*
    
about:
    home: https://github.com/something
    summary: "Utilities and REST API for xxx"
```

**Comment by JeremyEnns** [comment]
Ran into this issue as well, the build fails when .git folder exists in the recipe but git is not installed on the system.  

It’s trying to extract information from git (get_git_build_info), but a failed query causes the entire build to fail. The fact that a .git directory exists in the recipe directory should not require that git be installed for a build to succeed.  We ought to just display a warning and continue to build the package.

**Comment by ilanschnell** [comment]
I just opened https://github.com/conda/conda-build/pull/745, which has a simple fix for this bug.
