### ISSUE TITLE
Build fails if using namespace packages

### ISSUE THREAD

**Issue by remram44** [conda/conda-build#649]
I have two libs that share a namespace package, and one of them depends on the other.

When building the one that has the dependency, the build fails with "`OSError: File exists: <path to the namespace directory>`". It looks like you are not handling the fact that the directory will already have been created while installing the first package.

```
Traceback (most recent call last):
  File "/Users/remirampin/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/remirampin/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 190, in main
    args_func(args, p)
  File "/Users/remirampin/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/Users/remirampin/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "/Users/remirampin/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 455, in build
    post_process(sorted(files2 - files1), preserve_egg_dir=bool(m.get_value('build/preserve_egg_dir')))
  File "/Users/remirampin/anaconda/lib/python2.7/site-packages/conda_build/post.py", line 148, in post_process
    remove_easy_install_pth(files, preserve_egg_dir=preserve_egg_dir)
  File "/Users/remirampin/anaconda/lib/python2.7/site-packages/conda_build/post.py", line 105, in remove_easy_install_pth
    utils.copy_into(join(egg_path, fn), join(sp_dir, fn))
  File "/Users/remirampin/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 34, in copy_into
    shutil.copytree(srcname, dstname)
  File "/Users/remirampin/anaconda/lib/python2.7/shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "/Users/remirampin/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/Users/remirampin/anaconda/envs/_build/lib/python2.7/site-packages/reprounzip/unpackers'
```

**Comment by remram44** [comment]
Bump. Please look into this, still happening, super annoying.

**Comment by kalefranz** [comment]
The python community has abandoned namespace packages. Because getting them to work is *super annoying*.

Honestly, the user experience here has always been broken. And it's not conda's place--being a language-agnostic package manager--to fix it for the PyPA. (Nor do we even have the authority to.)

Rant over. You have a point. Conda can do better. And this issue should stay open as a bug until we can address it further.

**Comment by remram44** [comment]
Well, at least installing such packages work with other tools (e.g. pip).

Here's my workaround ([commit](https://github.com/ViDA-NYU/reprozip/commit/d51df32c9734477c211a513577ac92ce9a901de4)): remove build dependencies in the conda recipe (since conda will break if installing them) and pass `--single-version-externally-managed` to setup.py

**Comment by ikalev** [comment]
@remram44 adding ``preserve_egg_dir:  yes`` to your recipe should do the trick. On Python 3 you can now use native PEP420 namespace packages (once #1090 is released).
