### ISSUE TITLE
stdout encode/decode issue

### ISSUE THREAD

**Issue by PeterDSteinberg** [conda/conda-build#657]
When <code>conda build .</code> is run within anaconda-build, I am getting a stdout decode/encode issue where the argument <code>encoding</code> ends up being None.  I am on linux with a root miniconda install.

```
conda build .
Removing old build environment
Removing old work directory
BUILD START: pulp-1.6.0-py27_0
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.18.0 but the
latest version is 1.18.1. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .............
The following NEW packages will be INSTALLED:

    openssl:    1.0.2d-0      defaults
    pip:        7.1.2-py27_0  defaults
    pyparsing:  1.5.6-py27_0  defaults
    python:     2.7.10-2      defaults
    readline:   6.2-2         defaults
    setuptools: 18.4-py27_0   defaults
    sqlite:     3.8.4.1-1     defaults
    tk:         8.5.18-0      defaults
    wheel:      0.26.0-py27_1 defaults
    zlib:       1.2.8-0       defaults

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
Removing old work directory
Cloning into bare repository '/opt/anaconda/conda-bld/git_cache/__github.com_coin-or_pulp.git'...
checkout: u'1.6.0'

Cloning into '/opt/anaconda/conda-bld/work'...
done.
Note: checking out '1.6.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 081d1e0... Merge branch 'release/1.6.0'
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 190, in main
    args_func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 392, in build
    source.provide(m.path, m.get_section('source'))
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/source.py", line 269, in provide
    git_source(meta, recipe_dir)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/source.py", line 136, in git_source
    git_info()
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/source.py", line 160, in git_info
    stdout = stdout.decode(encoding, 'ignore')
TypeError: decode() argument 1 must be string, not None
command exited with status 1
```

**Comment by mcg1969** [comment]
https://github.com/conda/conda-build/issues/619

**Comment by mcg1969** [comment]
And here's a PR that supposedly fixes it? https://github.com/conda/conda-build/pull/614

**Comment by mcg1969** [comment]
The environment variable workaround is `PYTHONIOENCODING="UTF-8".`

**Comment by msarahan** [comment]
Please update to conda-build 1.18.1 and try again.

**Comment by mcg1969** [comment]
Sure, but this is on the anaconda.org build workers.

**Comment by msarahan** [comment]
Can they be updated to 1.18.1?

**Comment by mcg1969** [comment]
Not my place to say exactly but I see no obvious reason why it can't be done soon. They're busy folks these days...

**Comment by msarahan** [comment]
OK, well, thanks for mentioning the PYTHONIOENCODING workaround.  That's what people should use until the update conda-build.

**Comment by PeterDSteinberg** [comment]
I have confirmed this issue is fixed in the most recent conda-build.

**Comment by jakirkham** [comment]
Yeah, this is one of those annoying Python 2/3 issues that periodically crops up. Glad to here it is fixed for you, @PeterDSteinberg.

Can this be closed or are we waiting for an update on the anaconda.org workers?

**Comment by gilescope** [comment]
I'd vote close @jakirkham.
