### ISSUE TITLE
Build error OSX - Travis

### ISSUE THREAD

**Issue by Jorge-C** [conda/conda-build#675]
We're hitting a conda exception when trying to build a bioinformatics package on OSX. For the record, it builds fine on linux.

The recipe is [here](https://github.com/biocore/conda-recipes/pull/37).

Traceback:

```
Fixing permissions
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
    https://github.com/conda/conda-build/issues
Include the output of the command 'conda info' in your report.
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_build/main_build.py", line 190, in main
    args_func(args, p)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_build/main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_build/build.py", line 466, in build
    post_build(m, sorted(files2 - files1))
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_build/post.py", line 355, in post_build
    mk_relative(m, f)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_build/post.py", line 324, in mk_relative
    mk_relative_osx(path)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_build/post.py", line 244, in mk_relative_osx
    s = macho.install_name_change(path, osx_ch_link)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_build/macho.py", line 88, in install_name_change
    for link in otool(path):
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_build/macho.py", line 62, in otool
    assert line[0] == '\t', path
AssertionError: /Users/travis/miniconda/envs/_build/bin/bl2seq
Traceback (most recent call last):
  File "ci/main.py", line 138, in <module>
    build_upload_recipes(sys.argv[1], sys.argv[2])
  File "ci/main.py", line 45, in build_upload_recipes
    build(root)
  File "ci/main.py", line 67, in build
    check_call(build_cmd, shell=True)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'conda build "recipes/legacyblast"' returned non-zero exit status 1
```

conda info -a

```
# conda environments:
#
root                  *  /Users/travis/miniconda
sys.version: 3.5.0 |Continuum Analytics, Inc.| (defau...
sys.prefix: /Users/travis/miniconda
sys.executable: /Users/travis/miniconda/bin/python3
conda location: /Users/travis/miniconda/lib/python3.5/site-packages/conda
conda-build: /Users/travis/miniconda/bin/conda-build
conda-convert: /Users/travis/miniconda/bin/conda-convert
conda-develop: /Users/travis/miniconda/bin/conda-develop
conda-env: /Users/travis/miniconda/bin/conda-env
conda-index: /Users/travis/miniconda/bin/conda-index
conda-inspect: /Users/travis/miniconda/bin/conda-inspect
conda-metapackage: /Users/travis/miniconda/bin/conda-metapackage
conda-pipbuild: /Users/travis/miniconda/bin/conda-pipbuild
conda-server: /Users/travis/miniconda/bin/conda-server
conda-sign: /Users/travis/miniconda/bin/conda-sign
conda-skeleton: /Users/travis/miniconda/bin/conda-skeleton
user site dirs: 
CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
DYLD_LIBRARY_PATH: <not set>
PATH: /Users/travis/miniconda/bin:/Users/travis/.rvm/gems/ruby-2.0.0-p481/bin:/Users/travis/.rvm/gems/ruby-2.0.0-p481@global/bin:/Users/travis/.rvm/rubies/ruby-2.0.0-p481/bin:/Users/travis/.rvm/bin:/Users/travis/bin:/Users/travis/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
PYTHONHOME: <not set>
PYTHONPATH: <not set>
WARNING: could not import _license.show_info
```

**Comment by stuarteberg** [comment]
This problem is described in #411.  Your recipe involves an OSX "universal" binary, and conda chokes on the output of `otool` in such cases.

Someday somebody will get around to fixing `conda_build.macho()`, but in the mean time, your best option is to simply turn that universal binary into a non-universal binary.  That is, strip out support for architectures other than x86 (do this in `build.sh`).  As I wrote at the bottom of #411, there is a tool called `ditto` that can do this.

**Comment by colinbrislawn** [comment]
Thanks @stuarteberg! I'm new to this a really appreciate the guidance.
