### ISSUE TITLE
"Empty version string" when attempting to build on 1.18.2

### ISSUE THREAD

**Issue by tomkinsc** [conda/conda-build#699]
I am attempting to build a recipe for a particular bioinformatics package for the [bioconda](https://github.com/bioconda/bioconda-recipes) channel. I have successfully built and added other packages, but am running into a problem with the following recipe:

```yaml
package:
    name: bmtagger
    version: '3.101'
source:
    fn: bmtools.tar.gz
    url: ftp://ftp.ncbi.nlm.nih.gov/pub/agarwala/bmtagger/bmtools.tar.gz
    md5: 719474a0e3b54449cbe06f6e442994dd
build:
    number: 1
requirements:
  build:
    - blast
    - srprism
  run:
    - blast
    - srprism
test:
    commands:
        - bmtagger.sh -V
about:
    home: ftp://ftp.ncbi.nlm.nih.gov/pub/agarwala/bmtagger/
    license: Public Domain
    summary: BMTagger aka Best Match Tagger is for removing human reads from metagenomics datasets

```

The recipe checks out as valid YAML via [YAMLlint](http://www.yamllint.com/). When I call `conda build recipes/bmtagger`, I receive the following output:

```
wmc07-f52:recipes tomkinsc$ conda build recipes/bmtagger
Removing old build environment
Removing old work directory
BUILD START: bmtagger-3.101-1
Fetching package metadata: ......
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/tomkinsc/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda_build/main_build.py", line 190, in main
    args_func(args, p)
  File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda_build/main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda_build/build.py", line 380, in build
    override_channels=override_channels)
  File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda_build/build.py", line 283, in create_env
    actions = plan.install_actions(prefix, index, specs)
  File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda/plan.py", line 406, in install_actions
    add_defaults_to_specs(r, linked, specs)
  File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda/plan.py", line 350, in add_defaults_to_specs
    for spec in specs
  File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda/plan.py", line 351, in <genexpr>
    for fn in r.get_max_dists(MatchSpec(spec))
  File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 563, in get_max_dists
    pkgs = self.get_pkgs(ms, max_only=True)
  File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 544, in get_pkgs
    pkgs = [Package(fn, self.index[fn]) for fn in self.find_matches(ms)]
  File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 544, in <listcomp>
    pkgs = [Package(fn, self.index[fn]) for fn in self.find_matches(ms)]
  File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 360, in __init__
    self.norm_version = VersionOrder(self.version)
  File "/Users/tomkinsc/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 149, in __init__
    raise ValueError("Empty version string.")
ValueError: Empty version string.
```

Any idea why I'm seeing the `Empty version string` error? The version is clearly specified, and it appears to match the [regexes](https://github.com/conda/conda/blob/master/conda/resolve.py#L28-L29) used by conda build.

Here is the output of `conda info`:

```
Current conda install:

             platform : osx-64
        conda version : 3.18.8
  conda-build version : 1.18.2
       python version : 3.4.3.final.0
     requests version : 2.8.1
     root environment : /Users/tomkinsc/anaconda  (writable)
  default environment : /Users/tomkinsc/anaconda
     envs directories : /Users/tomkinsc/anaconda/envs
        package cache : /Users/tomkinsc/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by tomkinsc** [comment]
Resolved. It seems I had a dependency in without a version number in `/Users/tomkinsc/anaconda/conda-bld/osx-64/:`
