### ISSUE TITLE
Unicode characters in the long description cause `pipbuild`/`skeleton pypi` to fail

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#703]
For an example try the following in the `continuumio/miniconda` Docker container.

```
$ conda pipbuild pybind11 --release 1.0
Package search: {'_pypi_ordering': False, 'version': '1.0', 'name': 'pybind11', 'summary': 'Seamless operability between C++11 and Python'}
Creating standard recipe for pybind11-1.0
("Using url https://pypi.python.org/packages/source/p/pybind11/pybind11-1.0.tar.gz (25 KB) for pybind11.\nDownloading pybind11\nUsing cached download\nUnpacking pybind11...\ndone\nworking in /tmp/tmpyAVDPxconda_skeleton_pybind11-1.0.tar.gz\nFetching package metadata: ......\nSolving package specifications: .................\nApplying patch: '/tmp/tmpyAVDPxconda_skeleton_pybind11-1.0.tar.gz/pypi-distutils.patch'\n$PYTHONPATH = /tmp/tmpyAVDPxconda_skeleton_pybind11-1.0.tar.gz/pybind11-1.0\n", '  File "setup.py", line 50\nSyntaxError: Non-ASCII character \'\\xe2\' in file setup.py on line 51, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details\nError: command failed: /opt/conda/envs/_build/bin/python setup.py install\n')
conda create -n _pipbuild_ --yes python pip
/opt/conda/envs/_pipbuild_/bin/pip install pybind11==1.0
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/conda/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 81, in main
    args_func(args, p)
  File "/opt/conda/lib/python2.7/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/opt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 366, in execute
    build_package(package, version, noarch_python=args.noarch_python)
  File "/opt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 307, in build_package
    noarch_python=noarch_python)
  File "/opt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 243, in make_recipe
    depends = get_all_dependencies(package, version)
  File "/opt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 210, in get_all_dependencies
    execute(cmd2.split(), check_exit_code=True)
TypeError: execute() got an unexpected keyword argument 'check_exit_code'
```

**Comment by fissurezone** [comment]
I think line should read:
`        utils.execute(cmd2.split(), check_exit_code=True)`

**Comment by jakirkham** [comment]
Well, the `execute` function is gone at present. So, this changes the exception to the one below.

```
$ conda pipbuild pybind11
*** conda pipbuild is no longer supported.  It will be removmed in a future release of conda-build. ***
Please use conda build instead.
Package search: {'_pypi_ordering': False, 'version': '1.0', 'name': 'pybind11', 'summary': 'Seamless operability between C++11 and Python'}
Creating standard recipe for pybind11-1.0
Using Anaconda Cloud api site https://api.anaconda.org
Using url https://pypi.python.org/packages/source/p/pybind11/pybind11-1.0.tar.gz (25 KB) for pybind11.
Downloading pybind11
Unpacking pybind11...
done
working in /var/folders/jj/pp1xwt1n4zdgy9zxbxc22t8w66tr7q/T/tmpZYLFiLconda_skeleton_pybind11-1.0.tar.gz
Fetching package metadata: ............
Solving package specifications: ...................
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgcc-4.8.5               |                1         785 KB  defaults
    numpy-1.11.0.dev0          |         py27_100         3.1 MB  file:///zopt/conda/conda-bld/osx-64/
    ------------------------------------------------------------
                                           Total:         3.9 MB

The following NEW packages will be INSTALLED:

    libgcc:   4.8.5-1              defaults                            
    numpy:    1.11.0.dev0-py27_100 file:///zopt/conda/conda-bld/osx-64/
    openblas: 0.2.15-101           nanshe                              
    pyyaml:   3.11-py27_1          defaults                            
    yaml:     0.1.6-0              defaults                            

Fetching packages ...
libgcc-4.8.5-1 100% |###############################| Time: 0:00:00  10.54 MB/s
numpy-1.11.0.d  71% |######################         | Time:patching file core.py
Hunk #1 succeeded at 169 with fuzz 2 (offset 2 lines).
  File "setup.py", line 50
SyntaxError: Non-ASCII character '\xe2' in file setup.py on line 51, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
numpy-1.11.0.d 100% |###############################| Time: 0:00:00 100.84 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
Applying patch: '/var/folders/jj/pp1xwt1n4zdgy9zxbxc22t8w66tr7q/T/tmpZYLFiLconda_skeleton_pybind11-1.0.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /var/folders/jj/pp1xwt1n4zdgy9zxbxc22t8w66tr7q/T/tmpZYLFiLconda_skeleton_pybind11-1.0.tar.gz/pybind11-1.0
Error: command failed: /zopt/conda/envs/_build/bin/python setup.py install

conda create -n _pipbuild_ --yes python pip
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ..........
Solving package specifications: ...........
Package plan for installation in environment /zopt/conda/envs/_pipbuild_:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2f-0      defaults
    pip:        8.0.2-py27_0  defaults
    python:     2.7.11-0      defaults
    readline:   6.2-2         defaults
    setuptools: 19.6.2-py27_0 defaults
    sqlite:     3.9.2-0       defaults
    tk:         8.5.18-0      defaults
    wheel:      0.26.0-py27_1 defaults
    zlib:       1.2.8-0       defaults

Linking packages ...
[      COMPLETE      ]|#####################################################################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate _pipbuild_
#
# To deactivate this environment, use:
# $ source deactivate
#
/zopt/conda/envs/nanshenv/envs/_pipbuild_/bin/pip install pybind11==1.0
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/zopt/conda/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 82, in main
    args_func(args, p)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_build.py", line 486, in args_func
    args.func(args, p)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 372, in execute
    build_package(package, version, noarch_python=args.noarch_python)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 313, in build_package
    noarch_python=noarch_python)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 249, in make_recipe
    depends = get_all_dependencies(package, version)
  File "/zopt/conda/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 218, in get_all_dependencies
    ret = subprocess.Popen(cmd2.split()).wait()
  File "/zopt/conda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/zopt/conda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Though, as `pipbuild` is deprecated now, this isn't an issue and one should use `conda skeleton pypi pybind11` to generate the recipe instead. The results of that will be broken out into a separate comment.

**Comment by jakirkham** [comment]
Here is the result of using skeleton.

```
$ conda skeleton pypi pybind11
Using url https://pypi.python.org/packages/source/p/pybind11/pybind11-1.0.tar.gz (25 KB) for pybind11.
Downloading pybind11
Using cached download
Unpacking pybind11...
done
working in /var/folders/jj/pp1xwt1n4zdgy9zxbxc22t8w66tr7q/T/tmpOBflLsconda_skeleton_pybind11-1.0.tar.gz
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ............
Solving package specifications: ...............
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.11.0.dev0          |py27_openblas_101         3.1 MB  file:///zopt/conda/conda-bld/osx-64/

The following packages will be UPDATED:

    numpy: 1.11.0.dev0-py27_100 file:///zopt/conda/conda-bld/osx-64/ --> 1.11.0.dev0-py27_openblas_101 file:///zopt/conda/conda-bld/osx-64/ [openblas]

Fetching packages ...
numpy-1.11.0.d 100% |##################################################################################################################################################################| Time: 0:00:00  95.41 MB/s
Extracting packages ...
[      COMPLETE      ]|#####################################################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#####################################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#####################################################################################################################################################################################| 100%
Applying patch: '/var/folders/jj/pp1xwt1n4zdgy9zxbxc22t8w66tr7q/T/tmpOBflLsconda_skeleton_pybind11-1.0.tar.gz/pypi-distutils.patch'
patching file core.py
Hunk #1 succeeded at 169 with fuzz 2 (offset 2 lines).
  File "setup.py", line 50
SyntaxError: Non-ASCII character '\xe2' in file setup.py on line 51, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
$PYTHONPATH = /var/folders/jj/pp1xwt1n4zdgy9zxbxc22t8w66tr7q/T/tmpOBflLsconda_skeleton_pybind11-1.0.tar.gz/pybind11-1.0
Error: command failed: /zopt/conda/envs/_build/bin/python setup.py install
```

**Comment by jakirkham** [comment]
Still appears to be an issue.

```
$ conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.9
    conda-env version : 2.5.2
  conda-build version : 1.21.6
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /zopt/conda2  (writable)
  default environment : /zopt/conda2/envs/nanshenv
     envs directories : /zopt/conda2/envs
        package cache : /zopt/conda2/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/conda-forge/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/conda-forge/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/nanshe/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/nanshe/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/jakirkham/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/jakirkham/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/javascript/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/javascript/noarch/
          config file : /Users/kirkhamj/.condarc
         offline mode : False
    is foreign system : False
```

**Comment by carlthome** [comment]
:+1:

**Comment by msarahan** [comment]
pipbuild no longer exists.  You need to do (at least) 2 steps now:

1. conda skeleton pypi (package name)
2. try building with ``conda build (package name)``
3. troubleshoot as necessary, or if it worked, great, go use your package
