### ISSUE TITLE
An unexpected error occured

### ISSUE THREAD

**Issue by rbn920** [conda/conda-build#725]
conda skeleton has stopped working for me.

```
λ conda skeleton pypi --version 0.6.3 xlwings
Using url https://pypi.python.org/packages/source/x/xlwings/xlwings-0.6.3.tar.gz (989 KB) for xlwings.
Downloading xlwings
Using cached download
Unpacking xlwings...
done
working in C:\Users\Robby\AppData\Local\Temp\tmpf8wz4omxconda_skeleton_xlwings-0.6.3.tar.gz
Fetching package metadata: ......
Solving package specifications: ...............
Applying patch: 'C:\\Users\\Robby\\AppData\\Local\\Temp\\tmpf8wz4omxconda_skeleton_xlwings-0.6.3.tar.gz\\pypi-distutils.patch'
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\Robby\Anaconda3\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\Robby\Anaconda3\lib\site-packages\conda_build\main_skeleton.py", line 272, in main
    args_func(args, p)
  File "C:\Users\Robby\Anaconda3\lib\site-packages\conda_build\main_build.py", line 468, in args_func
    args.func(args, p)
  File "C:\Users\Robby\Anaconda3\lib\site-packages\conda_build\main_skeleton.py", line 286, in execute
    pypi.main(args, parser)
  File "C:\Users\Robby\Anaconda3\lib\site-packages\conda_build\pypi.py", line 341, in main
    get_package_metadata(args, package, d, data)
  File "C:\Users\Robby\Anaconda3\lib\site-packages\conda_build\pypi.py", line 478, in get_package_metadata
    python_version=args.python_version)
  File "C:\Users\Robby\Anaconda3\lib\site-packages\conda_build\pypi.py", line 741, in get_pkginfo
    run_setuppy(src_dir, tempdir, python_version)
  File "C:\Users\Robby\Anaconda3\lib\site-packages\conda_build\pypi.py", line 788, in run_setuppy
    apply_patch(join(stdlib_dir, 'distutils'), patch)
  File "C:\Users\Robby\Anaconda3\lib\site-packages\conda_build\source.py", line 249, in apply_patch
    execute([patch, ] + patch_args, cwd=src_dir, check_exit_code=True)
  File "C:\Users\Robby\Anaconda3\lib\site-packages\conda_build\utils.py", line 231, in execute
    output=(stdout, stderr))
subprocess.CalledProcessError: Command '['C:\\Users\\Robby\\Anaconda3\\Scripts\\patch.exe', '-p0', '-i', 'C:\\Users\\Robby\\AppData\\Local\\Temp\\tmpf8wz4omxconda_skeleton_xlwings-0.6.3.tar.gz\\pypi-distutils.patch_unix']' returned non-zero exit status 2
```

```
λ conda info
Current conda install:

             platform : win-64
        conda version : 3.19.0
  conda-build version : 1.18.2
       python version : 3.4.4.final.0
     requests version : 2.9.0
     root environment : C:\Users\Robby\Anaconda3  (writable)
  default environment : C:\Users\Robby\Anaconda3
     envs directories : C:\Users\Robby\Anaconda3\envs
        package cache : C:\Users\Robby\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by msarahan** [comment]
You have an outdated version of the patch package.  The current version is 2.5.9, build 1.  You can update with:

    conda update patch

The new patch program lives in (prefix)\Library\bin, not in (prefix)\Scripts.  You may need to manually delete the one in Scripts if the package update doesn't get rid of it.

**Comment by rbn920** [comment]
Thank you. I will try that when I am back at my desktop and follow up here.

**Comment by rbn920** [comment]
Unfortunately this did not help.

**Comment by rbn920** [comment]
Thank you. This worked but I did have to delete the old one manually.
