### ISSUE TITLE
'conda pipbuild pyusb' - error

### ISSUE THREAD

**Issue by vbsak** [conda/conda-build#743]
Hello, 
conda command from subject fails with following error:

Traceback (most recent call last):
  File "/home/liveuser/anaconda2/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/home/liveuser/anaconda2/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 81, in main
    args_func(args, p)
  File "/home/liveuser/anaconda2/lib/python2.7/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/home/liveuser/anaconda2/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 369, in execute
    build_package(package, version, noarch_python=args.noarch_python)
  File "/home/liveuser/anaconda2/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 302, in build_package
    directory = build_recipe(package, version=version)
  File "/home/liveuser/anaconda2/lib/python2.7/site-packages/conda_build/main_pipbuild.py", line 147, in build_recipe
    output = result.strip().splitlines()
AttributeError: 'tuple' object has no attribute 'strip'

---

Best regards, 
vbsak

**Comment by msarahan** [comment]
pipbuild no longer exists.  You need to do (at least) 2 steps now:

1. conda skeleton pypi (package name)
2. try building with ``conda build (package name)``
3. troubleshoot as necessary, or if it worked, great, go use your package
