### ISSUE TITLE
conda_build.environ.get_dict() broken in 1.19.0

### ISSUE THREAD

**Issue by jhunkeler** [conda/conda-build#751]
@kalefranz
I'm sure this was not intentional, however #749 introduced the following regression in `1.19.0`...

```
% python
Python 3.5.1 |Anaconda 2.4.1 (x86_64)| (default, Dec  7 2015, 11:24:55)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import conda_build.environ
>>> conda_build.environ.get_dict()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jhunk/anaconda3/lib/python3.5/site-packages/conda_build/environ.py", line 120, in get_dict
    if m.get_value('source/git_url'):
AttributeError: 'NoneType' object has no attribute 'get_value'
```

Output from `1.18.2`:

```
% python
Python 3.5.1 |Anaconda 2.4.1 (x86_64)| (default, Dec  7 2015, 11:24:55)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import conda_build.environ
>>> conda_build.environ.get_dict()
{'PYTHON': '/Users/jhunk/anaconda3/envs/_build/bin/python', 'PYTHONNOUSERSITE': '1', 'CONDA_DEFAULT_ENV': '/Users/jhunk/anaconda3/envs/_build', 'SRC_DIR': '/Users/jhunk/anaconda3/conda-bld/work', 'CONDA_BUILD': '1', 'MACOSX_DEPLOYMENT_TARGET': '10.6', 'ARCH': '64', 'SP_DIR': '/Users/jhunk/anaconda3/envs/_build/lib/python3.5/site-packages', 'SYS_PREFIX': '/Users/jhunk/anaconda3', 'R': '/Users/jhunk/anaconda3/envs/_build/bin/R', 'PY_VER': '3.5', 'CPU_COUNT': '8', 'LANG': 'en_US.UTF-8', 'LDFLAGS': '-arch x86_64', 'PREFIX': '/Users/jhunk/anaconda3/envs/_build', 'CXXFLAGS': '-arch x86_64', 'PERL_VER': '5.18.2', 'PATH': '/Users/jhunk/anaconda3/envs/_build/bin:/usr/local/cc65/bin:/Applications/Vice/tools:/Users/jhunk/anaconda3/bin:/Users/jhunk/.local/bin:/opt/local/libexec/gnubin:/opt/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin', 'CFLAGS': '-arch x86_64', 'HOME': '/Users/jhunk', 'OSX_ARCH': 'x86_64', 'PKG_CONFIG_PATH': '/Users/jhunk/anaconda3/envs/_build/lib/pkgconfig', 'STDLIB_DIR': '/Users/jhunk/anaconda3/envs/_build/lib/python3.5', 'SYS_PYTHON': '/Users/jhunk/anaconda3/bin/python', 'PY3K': '1'}
```

**Comment by jasongrout** [comment]
This also shows up when doing `python -m conda_build.environ` to check the environment variables available to yaml files.

**Comment by jhunkeler** [comment]
@jasongrout
Fixed in master! I'm going to go ahead and close this out.
