### ISSUE TITLE
conda skeleton pypi numpy does not work

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#76]
``` pytb
$conda skeleton pypi numpy
More than one source version is available for numpy:
0: https://pypi.python.org/packages/source/n/numpy/numpy-1.8.0.tar.gz (3.6 MB)
1: https://pypi.python.org/packages/source/n/numpy/numpy-1.8.0.zip (4.1 MB)
Which version should I use? 0
Using url https://pypi.python.org/packages/source/n/numpy/numpy-1.8.0.tar.gz (3779617) for numpy.
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/bin/conda-skeleton", line 7, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/main_skeleton.py", line 111, in main
    args.func(args, p)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/main_skeleton.py", line 119, in execute
    pypi.main(args, parser)
  File "/Users/aaronmeurer/Documents/Continuum/conda-build/conda_build/pypi.py", line 232, in main
    if data.has_key('classifiers'):
AttributeError: 'dict' object has no attribute 'has_key'
```

**Comment by ozancaglayan** [comment]
I intended to create a NumPy package compiled against OpenBLAS and ran this command which failed the same way. This is a Miniconda3 installation. The strange thing is that this exception, once encountered, breaks my IPython:

```
Traceback (most recent call last):
  File "/home/ozan/miniconda3/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/home/ozan/miniconda3/lib/python3.4/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/ozan/miniconda3/lib/python3.4/site-packages/IPython/config/application.py", line 563, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/home/ozan/miniconda3/lib/python3.4/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/ozan/miniconda3/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 332, in initialize
    self.init_shell()
  File "/home/ozan/miniconda3/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 348, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "/home/ozan/miniconda3/lib/python3.4/site-packages/IPython/config/configurable.py", line 354, in instance
    inst = cls(*args, **kwargs)
  File "/home/ozan/miniconda3/lib/python3.4/site-packages/IPython/terminal/interactiveshell.py", line 328, in __init__
    **kwargs
  File "/home/ozan/miniconda3/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 483, in __init__
    self.init_readline()
  File "/home/ozan/miniconda3/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 1843, in init_readline
    self.readline_startup_hook = readline.set_startup_hook
AttributeError: 'module' object has no attribute 'set_startup_hook'
```

Any clues?

**Comment by ozancaglayan** [comment]
Hmm removing `conda-bld` folder fixed my ipython back.

**Comment by ozancaglayan** [comment]
Pff, actually it was caused because I was in `conda-recipes` folder which also includes an `ipython` folder. I hate this import caused non-intuitive Python exceptions :)

**Comment by stoiver** [comment]
Same problems as  Juanlu001 when using numpy.distutils. 

Specific conda command: 

conda skeleton pypi anuga

Package http://github.com/stoiver/anuga_core

My setup.py is quite similar to the one used by  Juanlu001 in the package http://github.com/Pybonacci/poliastro

Here is the error 

    (anuga_clean)steve@bottineau:~/Sandpit$ conda skeleton pypi anuga
    Using url https://pypi.python.org/packages/source/a/anuga/anuga-1.3.8.tar.gz (12.4 MB) for anuga.
    Downloading anuga (use --no-download to skip this step)
    Using cached download
    Unpacking anuga...
    done
    working in /tmp/tmpelPQqqconda_skeleton_anuga-1.3.8.tar.gz
    Fetching package metadata: ......
    Solving package specifications: .
    Applying patch: '/tmp/tmpelPQqqconda_skeleton_anuga-1.3.8.tar.gz/pypi-distutils.patch'
    patching file core.py
    Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
    Running from anuga source directory.
    Traceback (most recent call last):
      File "setup.py", line 184, in <module>
        setup_package()
      File "setup.py", line 178, in setup_package
        setup(**metadata)
      File "/home/steve/miniconda/envs/_build/lib/python2.7/site-packages/numpy/distutils/core.py", line 130, in setup
        if dist.help or not _command_line_ok():
    AttributeError: 'NoneType' object has no attribute 'help'
    $PYTHONPATH = /tmp/tmpelPQqqconda_skeleton_anuga-1.3.8.tar.gz/anuga-1.3.8
    Error: command failed: /home/steve/miniconda/envs/_build/bin/python setup.py install

**Comment by timcera** [comment]
Any work-around or fix?

Have the same problem with 

    conda skeleton pypi openopt

**Comment by dtsmith2001** [comment]
I am not able to run

> conda skeleton pypi scikit-learn

either. This issue was reported in May 2014. I haven't been able to find a work-around after doing numerous searches. Is there indeed a work-around or fix?

I am using Anaconda 3 version 2.2.0 with scikit-learn 0.16.1. I did a fresh installation of Anaconda and followed the recipe in http://conda.pydata.org/docs/build_tutorials/pkgs.html to build
> pyinstrument
Building pandas with
> conda skeleton pypi pandas
worked just fine. It's scikit-learn that has a problem.

**Comment by rolando** [comment]
I just got the same issue as @dtsmith2001 with `scikit-learn`. I had to write manually a recipe for `scikit-learn` because I needed the package compatible with `numpy=1.6` :(

In OSX:

```
$ conda skeleton pypi scikit-learn
Warning, the following versions were found for scikit-learn
0.17b1
0.16.1
0.16.0
0.16b1
0.15.2
0.15.1
0.15.0
0.15.0b2
0.15.0b1
0.14.1
0.14
0.14a1
0.13.1
0.13
0.12.1
0.12
0.11
0.10
0.9
Using 0.17b1
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/s/scikit-learn/scikit-learn-0.17b1.tar.gz (7.5 MB) for scikit-learn.
Downloading scikit-learn
Using cached download
Unpacking scikit-learn...
done
working in /var/folders/55/nbg15c6j4k3cg06tjfhqypd40000gn/T/tmpf5347bconda_skeleton_scikit-learn-0.17b1.tar.gz
Fetching package metadata: ..........
Solving package specifications: ...............
The following NEW packages will be INSTALLED:

    pyyaml: 3.11-py27_1   defaults
    yaml:   0.1.6-0       defaults

The following packages will be UPDATED:

    numpy:  1.6.2-py27_4 defaults --> 1.10.1-py27_0 defaults

Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
Applying patch: '/var/folders/55/nbg15c6j4k3cg06tjfhqypd40000gn/T/tmpf5347bconda_skeleton_scikit-learn-0.17b1.tar.gz/pypi-distutils.patch'
patching file core.py
Hunk #1 succeeded at 169 with fuzz 2 (offset 2 lines).
Partial import of sklearn during the build process.
Traceback (most recent call last):
  File "setup.py", line 247, in <module>
    setup_package()
  File "setup.py", line 243, in setup_package
    setup(**metadata)
  File "/Users/rolando/miniconda/envs/_build/lib/python2.7/site-packages/numpy/distutils/core.py", line 130, in setup
    if dist.help or not _command_line_ok():
AttributeError: 'NoneType' object has no attribute 'help'
$PYTHONPATH = /var/folders/55/nbg15c6j4k3cg06tjfhqypd40000gn/T/tmpf5347bconda_skeleton_scikit-learn-0.17b1.tar.gz/scikit-learn-0.17b1
Error: command failed: /Users/rolando/miniconda/envs/_build/bin/python setup.py install

$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.18.3
  conda-build version : 1.18.1
       python version : 2.7.10.final.0
     requests version : 2.7.0
```

In  Linux:
```
$ conda skeleton pypi scikit-learn
Warning, the following versions were found for scikit-learn
0.17b1
0.16.1
0.16.0
0.16b1
0.15.2
0.15.1
0.15.0
0.15.0b2
0.15.0b1
0.14.1
0.14
0.14a1
0.13.1
0.13
0.12.1
0.12
0.11
0.10
0.9
Using 0.17b1
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/s/scikit-learn/scikit-learn-0.17b1.tar.gz (7.5 MB) for scikit-learn.
Downloading scikit-learn
Using cached download
Unpacking scikit-learn...
done
working in /tmp/tmp4Ngct2conda_skeleton_scikit-learn-0.17b1.tar.gz
Fetching package metadata: ......
Solving package specifications: .................
Applying patch: '/tmp/tmp4Ngct2conda_skeleton_scikit-learn-0.17b1.tar.gz/pypi-distutils.patch'
patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Partial import of sklearn during the build process.
Traceback (most recent call last):
  File "setup.py", line 247, in <module>
    setup_package()
  File "setup.py", line 237, in setup_package
    .format(scipy_req_str, instructions))
ImportError: Scientific Python (SciPy) is not installed.
scikit-learn requires SciPy >= 0.9.
Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html

$PYTHONPATH = /tmp/tmp4Ngct2conda_skeleton_scikit-learn-0.17b1.tar.gz/scikit-learn-0.17b1
Error: command failed: /home/rolando/miniconda/envs/_build/bin/python setup.py install

$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.18.3
  conda-build version : 1.18.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
```
