### ISSUE TITLE
Exception TooManyRedirects: Exceeded 30 redirects.

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#770]
When trying to build a package, I am seeing the following error. Seems like a connectivity issue and not a recipe issue

```
Removing old build environment
Removing old work directory
BUILD START: openblas-0.2.15-102
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/zopt/conda2/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/zopt/conda2/lib/python2.7/site-packages/conda_build/main_build.py", line 190, in main
    args_func(args, p)
  File "/zopt/conda2/lib/python2.7/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/zopt/conda2/lib/python2.7/site-packages/conda_build/main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "/zopt/conda2/lib/python2.7/site-packages/conda_build/build.py", line 380, in build
    override_channels=override_channels)
  File "/zopt/conda2/lib/python2.7/site-packages/conda_build/build.py", line 278, in create_env
    override_channels=override_channels)
  File "/zopt/conda2/lib/python2.7/site-packages/conda_build/build.py", line 266, in get_build_index
    prepend=not override_channels)
  File "/zopt/conda2/lib/python2.7/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/zopt/conda2/lib/python2.7/site-packages/conda/utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "/zopt/conda2/lib/python2.7/site-packages/conda/fetch.py", line 264, in fetch_index
    reversed(channel_urls))
  File "/zopt/conda2/lib/python2.7/site-packages/conda/fetch.py", line 263, in <lambda>
    use_cache=use_cache, session=session)),
  File "/zopt/conda2/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/zopt/conda2/lib/python2.7/site-packages/conda/fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "/zopt/conda2/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/zopt/conda2/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/zopt/conda2/lib/python2.7/site-packages/requests/sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/zopt/conda2/lib/python2.7/site-packages/requests/sessions.py", line 113, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

**Comment by jakirkham** [comment]
Seems to be working again.
