### ISSUE TITLE
Unexpected error when using noarch_python

### ISSUE THREAD

**Issue by jni** [conda/conda-build#791]
I'm trying and failing to create a conda package for a pure Python library. Building for OSX (my current system) worked fine, but when I added:

``` python
build:
  noarch_python: True
```

to my recipe, I got the following error:

``` pytb
Traceback (most recent call last):
  File "/Users/nuneziglesiasj/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 192, in main
    args_func(args, p)
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 486, in args_func
    args.func(args, p)
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 409, in execute
    include_recipe=args.include_recipe)
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 492, in build
    noarch_python.transform(m, sorted(files2 - files1))
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/conda_build/noarch_python.py", line 87, in transform
    assert 'py_' in m.dist()
AssertionError
```

Conda info:

```
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 3.19.3
  conda-build version : 1.19.0
       python version : 2.7.10.final.0
     requests version : 2.9.1
     root environment : /Users/nuneziglesiasj/anaconda  (writable)
  default environment : /Users/nuneziglesiasj/anaconda
     envs directories : /Users/nuneziglesiasj/anaconda/envs
        package cache : /Users/nuneziglesiasj/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/osx-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
                        http://conda.binstar.org/jni/osx-64/
                        http://conda.binstar.org/jni/noarch/
          config file : /Users/nuneziglesiasj/.condarc
    is foreign system : False
```

**Comment by jakirkham** [comment]
Looks like a dup of this issue ( https://github.com/conda/conda-build/issues/542 ).

**Comment by jakirkham** [comment]
Have you tried again with `noarch: python`?
