### ISSUE TITLE
conda-build traceback is missing git output

### ISSUE THREAD

**Issue by hohn** [conda/conda-build#795]
The original traceback:

```
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\traveler\build-2016-02-25-help-menu\build-root\miniconda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\traveler\build-2016-02-25-help-menu\build-root\miniconda\lib\site-packages\conda_build\main_build.py", line 190, in main
    args_func(args, p)
  File "C:\Users\traveler\build-2016-02-25-help-menu\build-root\miniconda\lib\site-packages\conda_build\main_build.py", line 468, in args_func
    args.func(args, p)
  File "C:\Users\traveler\build-2016-02-25-help-menu\build-root\miniconda\lib\site-packages\conda_build\main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "C:\Users\traveler\build-2016-02-25-help-menu\build-root\miniconda\lib\site-packages\conda_build\build.py", line 392, in build
    source.provide(m.path, m.get_section('source'))
  File "C:\Users\traveler\build-2016-02-25-help-menu\build-root\miniconda\lib\site-packages\conda_build\source.py", line 266, in provide
    git_source(meta, recipe_dir)
  File "C:\Users\traveler\build-2016-02-25-help-menu\build-root\miniconda\lib\site-packages\conda_build\source.py", line 130, in git_source
    check_exit_code=True)
  File "C:\Users\traveler\build-2016-02-25-help-menu\build-root\miniconda\lib\site-packages\conda_build\utils.py", line 231, in execute
    output=(stdout, stderr))
```

The error is of course

```
subprocess.CalledProcessError: Command
'['C:\\Users\\traveler\\PortableGit-2.7-64\\mingw64\\bin\\git.exe',
'clone', '--recursive',
'c:/Users/traveler/build-2016-02-25-help-menu/build-root/package-src/git_cache/Users_traveler_build-2016-02-25-help-menu_build-install-master_widgets',
'c:\\Users\\traveler\\build-2016-02-25-help-menu\\build-root\\package-src\\work']'
returned non-zero exit status 128
```

To find the source of this error requires manually running the git
command:

```
git clone --recursive \
    'c:/Users/traveler/build-2016-02-25-help-menu/build-root/package-src/git_cache/Users_traveler_build-2016-02-25-help-menu_build-install-master_widgets' \
    'c:\Users\traveler\build-2016-02-25-help-menu\build-root\package-src\work'
```

This gives:

```
fatal: destination path
'c:\Users\traveler\build-2016-02-25-help-menu\build-root\package-src\work'
already exists and is not an empty directory.
```

Removing the destination 

```
rm -fR 'c:\Users\traveler\build-2016-02-25-help-menu\build-root\package-src\work'
```

and re-running now works.

Can conda-build be changed to inlude the git output in error messages?
This would go a long way in debugging deeply nested problems.

Some more information:

```
0:$ ./Scripts/conda info
Current conda install:

             platform : win-64
        conda version : 3.19.3
  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Users\traveler\build-2016-02-25-help-menu\build-root\miniconda  (writable)
  default environment : C:\Users\traveler\build-2016-02-25-help-menu\build-root\miniconda
     envs directories : C:\Users\traveler\build-2016-02-25-help-menu\build-root\miniconda\envs
        package cache : C:\Users\traveler\build-2016-02-25-help-menu\build-root\miniconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by pelson** [comment]
Does #790 relate?

**Comment by stuarteberg** [comment]
>Does #790 relate?

No, looks like this error is occurring in `source.py`, whereas #790 deals with `environ.py`.
