### ISSUE TITLE
TypeError: environment can only contain string

### ISSUE THREAD

**Issue by rmcgibbo** [conda/conda-build#820]
I just saw a strange error on windows when building GPy. In this case, it only seemed to happen on Python 2.

```
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
 
    https://github.com/conda/conda-build/issues
 
Include the output of the command 'conda info' in your report.
 
 
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 194, in main
    args_func(args, p)
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 474, in args_func
    args.func(args, p)
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 423, in execute
    include_recipe=args.include_recipe)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 417, in build
    m.parse_again(permit_undefined_jinja=False)
  File "C:\Miniconda\lib\site-packages\conda_build\metadata.py", line 351, in parse_again
    self.meta = parse(self._get_contents(permit_undefined_jinja))
  File "C:\Miniconda\lib\site-packages\conda_build\metadata.py", line 628, in _get_contents
    env.globals.update(context_processor(self, path))
  File "C:\Miniconda\lib\site-packages\conda_build\jinja_context.py", line 65, in context_processor
    ctx = get_environ(m=initial_metadata)
  File "C:\Miniconda\lib\site-packages\conda_build\environ.py", line 165, in get_dict
    m.get_value('source/git_rev')))
  File "C:\Miniconda\lib\site-packages\conda_build\environ.py", line 64, in get_git_build_info
    remote_details = subprocess.check_output(["git", "remote", "-v"], env=env)
  File "C:\Miniconda\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Miniconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Miniconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
TypeError: environment can only contain string
```

Full log: https://ci.appveyor.com/project/rmcgibbo/conda-recipes/build/1.0.709/job/mb723cisbnwdddte

**Comment by rmcgibbo** [comment]
The error message is the same as #188, but this is with the latest (conda-build-1.19.1).

**Comment by jreback** [comment]
yeh this breaks with conda-build=1.19.1 (but works with 1.19.0), but ONLY ON WINDOWS.
This works fine on macosx/linux

```
package:
    name: pandas
    version: {{ GIT_DESCRIBE_TAG|replace("v","") }}

build:
    number: {{ GIT_DESCRIBE_NUMBER|int }}
    {% if GIT_DESCRIBE_NUMBER|int == 0 %}string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_0
    {% else %}string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}{% endif %}
```

**Comment by jreback** [comment]
cc @msarahan

**Comment by stuarteberg** [comment]
The problem is on [these lines][1]:

[1]: https://github.com/conda/conda-build/blob/3d60a3cc27ca49dd72641c0f62ccb036fd0007f3/conda_build/environ.py#L72-L74

```
        env['GIT_DIR'] = cache_dir
        remote_details = check_output(["git", "remote", "-v"], env=env,
                                      stderr=STDOUT)
```



Apparently on Windows, the `env` argument to `subprocess.check_call` may contain only `str`, not `unicode`.  I tried this little test on Windows:

```
﻿>>> subprocess.check_call('echo "hi"', shell=True, env={'MYVAR': 'blabla'})
"hi"
0
>>> subprocess.check_call('echo "hi"', shell=True, env={'MYVAR': u'blabla'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ilastik\Miniconda\lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\ilastik\Miniconda\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Users\ilastik\Miniconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Users\ilastik\Miniconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
```

I'll implement a pull request soonish, unless somebody beats me to it.

**Comment by stuarteberg** [comment]
Hey guys, would you mind giving #824 a try to see if it fixes the problem?  I don't really have a good way to test it on Windows.

**Comment by jreback** [comment]
how do you bootstrap install this? e.g. I *can* build with ``python setup.py install`` but then how do I actually use this in my env? e.g. ``conda build conda-build`` doesn't work in an env with only a pip install of ``conda-build``.

**Comment by stuarteberg** [comment]
>how do you bootstrap install this?

`conda-build` is pure-python, so for a quick test, I usually just use `PYTHONPATH`:

```bash
cd /tmp/
git clone http://github.com/stuarteberg/conda-build
cd conda-build
git checkout fix-820
cd /path/to/pandas
PYTHONPATH=/tmp/conda-build conda build conda.recipe
```

**Comment by stuarteberg** [comment]
...or whatever the right syntax would be on Windows, that is... :-P

**Comment by jakirkham** [comment]
This is in a Python 3 environment, @jreback?

**Comment by jreback** [comment]
its a PY2 env. So I can get this to work by encoding :<

```
(Pdb) l
 77                 # On Windows, subprocess env can't handle unicode.
 78                 cache_dir = cache_dir.encode(sys.getfilesystemencoding())
 79
 80             env['GIT_DIR'] = cache_dir
 81             remote_details = check_output(["git", "remote", "-v"], env=env,
 82  ->                                       stderr=STDOUT)
 83             remote_details = remote_details.decode('utf-8')
 84             remote_url = remote_details.split('\n')[0].split()[1]
 85             if '://' not in remote_url:
 86                 # Local filepaths are allowed, but make sure we normalize them
 87                 remote_url = normpath(remote_url)
(Pdb) !nenv = { k.encode('utf-8'):v.encode('utf-8') for k, v in env.iteritems() }
(Pdb) p nenv
{'TMP': 'C:\\Users\\conda\\AppData\\Local\\Temp', 'COMPUTERNAME': 'WIN-IGPU976LF33', 'VS140COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Stud
io 14.0\\Common7\\Tools\\', 'VS110COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Common7\\Tools\\', 'USERDOMAIN': 'WIN-IGPU976LF3
3', 'VS100COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\Common7\\Tools\\', 'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerS
hell\\v1.0\\Modules\\', 'VS90COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\Common7\\Tools\\', 'COMMONPROGRAMFILES': 'C:\\Program
Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 70 Stepping 1, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_RE
VISION': '4601', 'PATH': 'C:\\Miniconda2\\Library\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPow
erShell\\v1.0\\;C:\\Program Files (x86)\\Git\\cmd;C:\\Program Files (x86)\\CMake\\bin;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\
Program Files (x86)\\Microsoft SDKs\\TypeScript\\1.0\\;c:\\Program Files (x86)\\Microsoft SQL Server\\90\\Tools\\binn\\;\\Program Files (x86)\\emacs\\
emacs-24.3\\bin;C:\\Windows\\system32\\config\\systemprofile\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Miniconda;C:\\Miniconda\\Scripts;
C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Miniconda2;C:\\Miniconda2\\Scripts;C:\\Miniconda2\\Library\\bin', 'SYSTEM
ROOT': 'C:\\Windows', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'WINDOWS_TRACING_FLAGS': '3', 'VSSDK140INSTALL': 'C:\\Program Files (x86)\\Micro
soft Visual Studio 14.0\\VSSDK\\', 'TEMP': 'C:\\Users\\conda\\AppData\\Local\\Temp', 'CONDA_R': '3.2.2', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files
 (x86)\\Common Files', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'LOCALAPPDATA': 'C:\\Users\\conda\\AppData\\Local', 'H
OMEPATH': '\\Users\\conda', 'VS120COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\Common7\\Tools\\', 'PROGRAMW6432': 'C:\\Program
Files', 'USERNAME': 'conda', 'LOGONSERVER': '\\\\WIN-IGPU976LF33', 'PROMPT': '$P$G', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'PROGRAMDATA': 'C:\\
ProgramData', 'PYTHONPATH': 'C:\\conda-build', 'CONDA_PY': '27', 'CONDA_PERL': '5.18.2', 'GIT_DIR': 'C:/Miniconda2/conda-bld/git_cache/Users_conda_Doc
uments_pandas3.5', 'SESSIONNAME': 'Console', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'CONDA_NPY': '110', 'FP_NO_HOST_CHECK
': 'NO', 'WINDIR': 'C:\\Windows', 'WINDOWS_TRACING_LOGFILE': 'C:\\BVTBin\\Tests\\installpackage\\csilogfile.log', 'HOMEDRIVE': 'C:', 'SYSTEMDRIVE': 'C
:', 'NUMBER_OF_PROCESSORS': '1', 'APPDATA': 'C:\\Users\\conda\\AppData\\Roaming', 'PROCESSOR_LEVEL': '6', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Co
mmon Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'USERPROFILE': 'C:\\Users\\conda'}
(Pdb) p check_output(["git", "remote", "-v"], env=nenv, stderr=STDOUT)
'origin\tC:/Users/conda/Documents/pandas3.5/conda.recipe/../ (fetch)\norigin\tC:/Users/conda/Documents/pandas3.5/conda.recipe/../ (push)\n'
(Pdb)
```

**Comment by jakirkham** [comment]
So, not having it be unicode is a problem?

**Comment by jreback** [comment]
So given my last comments, I think everything is ok, except for the encoded ``GIT_DIR`` (which is added with a different encoding).

**Comment by stuarteberg** [comment]
Crap.  There's a dumb bug in my code.  I typed `git_dir` when I meant to type `cache_dir`.  I just force-pushed the fix to my branch.  Please try again.

**Comment by jreback** [comment]
and it works :+1:

**Comment by stuarteberg** [comment]
Phew! Sorry to be a dummy; thanks for checking the fix, and for your patience.

**Comment by jreback** [comment]
np, glad to help.

**Comment by stuarteberg** [comment]
>ideally this would become a test :) (and of course test on windows!)

Agreed, conda-build needs some Windows tests.
