### ISSUE TITLE
conda-build seems to be failing when parsing the test field with a conda inspect call

### ISSUE THREAD

**Issue by ocefpaf** [conda/conda-build#836]
I am experiencing the following failure on OS X with conda-build-1.19.2. The failure disappears if `conda-build` is downgraded to 1.18.1)

```shell
conda inspect linkages nco --name _test

An unexpected error has occurred, please consider sending the

following traceback to the conda GitHub issue tracker at:



    https://github.com/conda/conda-build/issues



Include the output of the command 'conda info' in your report.





Traceback (most recent call last):

  File "/Users/travis/miniconda3/bin/conda-inspect", line 5, in <module>

    sys.exit(main())

  File "/Users/travis/miniconda3/lib/python3.4/site-packages/conda_build/main_inspect.py", line 155, in main

    args_func(args, p)

  File "/Users/travis/miniconda3/lib/python3.4/site-packages/conda_build/main_build.py", line 478, in args_func

    args.func(args, p)

  File "/Users/travis/miniconda3/lib/python3.4/site-packages/conda_build/main_inspect.py", line 307, in execute

    linkages = get_linkages(obj_files, prefix)

  File "/Users/travis/miniconda3/lib/python3.4/site-packages/conda/utils.py", line 118, in __call__

    value = self.func(*args, **kw)

  File "/Users/travis/miniconda3/lib/python3.4/site-packages/conda_build/ldd.py", line 51, in get_linkages

    res[f] = [(basename(l), l) for l in links]

  File "/Users/travis/miniconda3/lib/python3.4/site-packages/conda_build/ldd.py", line 51, in <listcomp>

    res[f] = [(basename(l), l) for l in links]

  File "/Users/travis/miniconda3/lib/python3.4/posixpath.py", line 139, in basename

    i = p.rfind(sep) + 1

AttributeError: 'dict' object has no attribute 'rfind'
```

For the recipe and the CI log see https://github.com/conda-forge/nco-feedstock/pull/3.

**Comment by pelson** [comment]
Any news? This turns out to be a problem for using conda-build on OSX...

**Comment by jakirkham** [comment]
Trying to get this back on people's radar. It would be really great to see some sort of fix for this.

**Comment by msarahan** [comment]
I can't repeat this with the current 1.21.x branch.  Can any of you please check that out and test it?

**Comment by ocefpaf** [comment]
This was fixed at some point. Not sure when. Thanks to whomever fixed it!
