### ISSUE TITLE
Windows Build error: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#840]
AppVeyor build: https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.325/job/x2tye18wmbwh6vux
Recipe: https://github.com/conda-forge/staged-recipes/pull/178

```
Traceback (most recent call last): 
  File "setup.py", line 106, in <module>
    zip_safe=False
  File "C:\Miniconda\envs\_build\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Miniconda\envs\_build\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Miniconda\envs\_build\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Miniconda\envs\_build\lib\site-packages\setuptools-20.3-py2.7.egg\setuptools\command\install.py", line 61, in run
  File "C:\Miniconda\envs\_build\lib\distutils\command\install.py", line 563, in run
    self.run_command('build')
  File "C:\Miniconda\envs\_build\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Miniconda\envs\_build\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Miniconda\envs\_build\lib\distutils\command\build.py", line 127, in run
    self.run_command(cmd_name)
  File "C:\Miniconda\envs\_build\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Miniconda\envs\_build\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Miniconda\envs\_build\lib\site-packages\setuptools-20.3-py2.7.egg\setuptools\command\build_ext.py", line 49, in run
  File "C:\Miniconda\envs\_build\lib\site-packages\Cython\Distutils\build_ext.py", line 164, in run
    _build_ext.build_ext.run(self)
  File "C:\Miniconda\envs\_build\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Miniconda\envs\_build\lib\site-packages\Cython\Distutils\build_ext.py", line 172, in build_extensions
    self.build_extension(ext)
  File "C:\Miniconda\envs\_build\lib\site-packages\setuptools-20.3-py2.7.egg\setuptools\command\build_ext.py", line 174, in build_extension
  File "C:\Miniconda\envs\_build\lib\distutils\command\build_ext.py", line 530, in build_extension
    target_lang=language)
  File "C:\Miniconda\envs\_build\lib\distutils\ccompiler.py", line 691, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "C:\Miniconda\envs\_build\lib\distutils\msvc9compiler.py", line 606, in link
    libraries) 
  File "C:\Miniconda\envs\_build\lib\distutils\ccompiler.py", line 1068, in gen_lib_options
    lib_opts.append(compiler.library_dir_option(dir))
  File "C:\Miniconda\envs\_build\lib\distutils\msvc9compiler.py", line 753, in library_dir_option
    return "/LIBPATH:" + dir 
TypeError: cannot concatenate 'str' and 'NoneType' objects 
```

**Comment by jakirkham** [comment]
This is looking to be too general to be conda build.

**Comment by jakirkham** [comment]
It is worth noting that I see issue ( http://bugs.python.org/issue13765 ) opened by @almarklein. Since I'm unable to track down the linked NumPy issue down, it seems I'm unable to find the resolution to the issue. Any thoughts on what helped you fix your issue, @almarklein?

**Comment by almarklein** [comment]
You think its related? I found the numpy ticket: https://github.com/numpy/numpy/issues/2611
