### ISSUE TITLE
Conda skeleton pypi not finding tests_require in setup.py; failing to create recipe

### ISSUE THREAD

**Issue by davclark** [conda/conda-build#842]
I'm going the conda build route, as I'm trying to avoid pip installs _especially_ when such installs don't work without compilation flags due to the way conda packages C libraries.

Trying to exectute `conda skeleton pypi --python-version 3.4 fitbit` yields:

```
Traceback (most recent call last):
  File "/opt/anaconda3/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.4/site-packages/conda_build/main_skeleton.py", line 272, in main
    args_func(args, p)
  File "/opt/anaconda3/lib/python3.4/site-packages/conda_build/main_build.py", line 478, in args_func
    args.func(args, p)
  File "/opt/anaconda3/lib/python3.4/site-packages/conda_build/main_skeleton.py", line 286, in execute
    pypi.main(args, parser)
  File "/opt/anaconda3/lib/python3.4/site-packages/conda_build/pypi.py", line 341, in main
    get_package_metadata(args, package, d, data)
  File "/opt/anaconda3/lib/python3.4/site-packages/conda_build/pypi.py", line 593, in get_package_metadata
    in pkginfo['tests_require']]))
TypeError: unorderable types: NoneType() < str()
```

Conda info is:

```
Current conda install:

             platform : osx-64
        conda version : 4.0.5
  conda-build version : 1.19.2
       python version : 3.4.4.final.0
     requests version : 2.9.1
     root environment : /opt/anaconda3  (writable)
  default environment : /opt/anaconda3
     envs directories : /opt/anaconda3/envs
        package cache : /opt/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        http://conda.binstar.org/binstar/osx-64/
                        http://conda.binstar.org/binstar/noarch/
                        http://conda.binstar.org/davclark/osx-64/
                        http://conda.binstar.org/davclark/noarch/
          config file : /Users/dav/.condarc
    is foreign system : False
```

A quick search didn't turn up any relevant issues

**Comment by msarahan** [comment]
Thanks. There have been some difficult to isolate issues with skeleton
pypi.  This appears to be barfing on test requirements. We'll look into it.

**Comment by davclark** [comment]
Let me know if you need any further info from me - I'm happy to run things on my end!

**Comment by msarahan** [comment]
It looks to me like it doesn't like their way of splitting up the requirements.  I don't understand why, because their setup.py file reads the split txt, then puts it into the right place in the setup function call (https://github.com/orcasgit/python-fitbit/blob/master/setup.py#L30).  Conda skeleton pypi does try to find this info (https://github.com/conda/conda-build/blob/master/conda_build/pypi.py#L349-L353), but something is going wrong.

This is definitely an issue we need to fix for the sake of other PyPI packages as well, but I don't know where it fits on our timeline.  I'll raise it.

```
>>> client = pypi.get_xmlrpc_client("https://pypi.python.org/pypi/fitbit/0.1.3")

>>> class Args(object):
    def __init__(self, *args, **kw):
        self.all_urls=True
        self.noprompt=False
        self.manual_url=False

>>> pypi.get_download_data(Args(), client, "fitbit", "0.1.3", False)

({'_pypi_hidden': False,
  '_pypi_ordering': 6,
  'author': 'Issac Kelly and ORCAS',
  'author_email': 'bpitcher@orcasinc.com',
  'bugtrack_url': '',
  'cheesecake_code_kwalitee_id': None,
  'cheesecake_documentation_id': None,
  'cheesecake_installability_id': None,
  'classifiers': [],
  'description': 'python-fitbit\n=============\n\n.. image:: https://travis-ci.org/orcasgit/python-fitbit.svg?branch=master\n   :target: https://travis-ci.org/orcasgit/python-fitbit\n   :alt: Build Status\n.. image:: https://coveralls.io/repos/orcasgit/python-fitbit/badge.png?branch=master\n   :target: https://coveralls.io/r/orcasgit/python-fitbit?branch=master\n   :alt: Coverage Status\n.. image:: https://requires.io/github/orcasgit/python-fitbit/requirements.png?branch=master\n   :target: https://requires.io/github/orcasgit/python-fitbit/requirements/?branch=master\n   :alt: Requirements Status\n\nFitbit API Python Client Implementation\n\nFor documentation: `http://python-fitbit.readthedocs.org/ <http://python-fitbit.readthedocs.org/>`_\n\nRequirements\n============\n\n* Python 2.6+\n* `python-dateutil`_ (always)\n* `requests-oauthlib`_ (always)\n* `Sphinx`_ (to create the documention)\n* `tox`_ (for running the tests)\n* `coverage`_ (to create test coverage reports)\n\n.. _python-dateutil: https://pypi.python.org/pypi/python-dateutil/2.4.0\n.. _requests-oauthlib: https://pypi.python.org/pypi/requests-oauthlib\n.. _Sphinx: https://pypi.python.org/pypi/Sphinx\n.. _tox: https://pypi.python.org/pypi/tox\n.. _coverage: https://pypi.python.org/pypi/coverage/\n\nTo use the library, you need to install the run time requirements:\n\n   sudo pip install -r requirements/base.txt\n\nTo modify and test the library, you need to install the developer requirements:\n\n   sudo pip install -r requirements/dev.txt\n\nTo run the library on a continuous integration server, you need to install the test requirements:\n\n   sudo pip install -r requirements/test.txt',
  'docs_url': None,
  'download_url': 'UNKNOWN',
  'downloads': {'last_day': 14, 'last_month': 604, 'last_week': 201},
  'home_page': 'https://github.com/orcasgit/python-fitbit',
  'keywords': None,
  'license': 'Apache 2.0',
  'maintainer': None,
  'maintainer_email': None,
  'name': 'fitbit',
  'package_url': 'http://pypi.python.org/pypi/fitbit',
  'platform': 'UNKNOWN',
  'release_url': 'http://pypi.python.org/pypi/fitbit/0.1.3',
  'requires_python': None,
  'summary': 'Fitbit API Wrapper.',
  'version': '0.1.3'},
 'https://pypi.python.org/packages/source/f/fitbit/fitbit-0.1.3.tar.gz',
 'fitbit-0.1.3.tar.gz',
 '1c0527516dabd17475c8cf55971411e5')
```
