### ISSUE TITLE
Applying patch on osx does not seem to work

### ISSUE THREAD

**Issue by srossross** [conda/conda-build#854]
```
Applying patch: u'/Users/sean/Documents/workspace/anaconda-cluster/conda-recipes/m2crypto/setup.patch'
/usr/bin/patch: **** Only garbage was found in the patch input.
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/sean/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/sean/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 190, in main
    args_func(args, p)
  File "/Users/sean/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 429, in args_func
    args.func(args, p)
  File "/Users/sean/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 384, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "/Users/sean/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 384, in build
    source.provide(m.path, m.get_section('source'))
  File "/Users/sean/anaconda/lib/python2.7/site-packages/conda_build/source.py", line 267, in provide
    apply_patch(src_dir, join(recipe_dir, patch))
  File "/Users/sean/anaconda/lib/python2.7/site-packages/conda_build/source.py", line 238, in apply_patch
    check_call([patch, '-p0', '-i', path], cwd=src_dir)
  File "/Users/sean/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/patch', '-p0', '-i', u'/Users/sean/Documents/workspace/anaconda-cluster/conda-recipes/m2crypto/setup.patch']' returned non-zero exit status 2
(salty)mr_chomps:m2crypto sean$ conda install patch
```

**Comment by srossross** [comment]
cc @quasiben This is coming from the https://github.com/ContinuumIO/anaconda-cluster/tree/master/conda-recipes/m2crypto recipe. But I don' think this is the correct response that conda should be showing.
