### ISSUE TITLE
Building 3-tier packages in one directory

### ISSUE THREAD

**Issue by 183amir** [conda/conda-build#858]
Hello,

We have a set of Python packages called `bob.string1.string2` and we want to merge these packages when they are being packaged in `conda`. However, `conda` throws an error complaining that the folder already exists.

```
Traceback (most recent call last):
  File "/home/amir/miniconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/home/amir/miniconda/lib/python3.5/site-packages/conda_build/main_build.py", line 208, in main
    args_func(args, p)
  File "/home/amir/miniconda/lib/python3.5/site-packages/conda_build/main_build.py", line 493, in args_func
    args.func(args, p)
  File "/home/amir/miniconda/lib/python3.5/site-packages/conda_build/main_build.py", line 438, in execute
    include_recipe=args.include_recipe)
  File "/home/amir/miniconda/lib/python3.5/site-packages/conda_build/build.py", line 486, in build
    post_process(sorted(files2 - files1), preserve_egg_dir=bool(m.get_value('build/preserve_egg_dir')))
  File "/home/amir/miniconda/lib/python3.5/site-packages/conda_build/post.py", line 148, in post_process
    remove_easy_install_pth(files, preserve_egg_dir=preserve_egg_dir)
  File "/home/amir/miniconda/lib/python3.5/site-packages/conda_build/post.py", line 105, in remove_easy_install_pth
    utils.copy_into(join(egg_path, fn), join(sp_dir, fn))
  File "/home/amir/miniconda/lib/python3.5/site-packages/conda_build/utils.py", line 35, in copy_into
    shutil.copytree(srcname, dstname)
  File "/home/amir/miniconda/lib/python3.5/shutil.py", line 309, in copytree
    os.makedirs(dst)
  File "/home/amir/miniconda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/amir/miniconda/envs/_build/lib/python2.7/site-packages/bob/ip'
```

We want our packages to look like this when they are installed:

```
/home/amir/miniconda/envs/_build/lib/python2.7/site-packages/bob
├── ap
├── bio
│   ├── base
│   ├── face
│   ├── gmm
│   ├── spear
│   └── video
├── blitz
├── core
│   └── random
├── db
│   ├── arface
│   ├── atnt
│   ├── atvskeystroke
│   ├── avspoof
│   ├── banca
│   ├── base
│   ├── biosecure
│   ├── biosecurid
│   ├── casia_fasd
│   ├── casme2
│   ├── caspeal
│   ├── frgc
│   ├── gbu
│   ├── iris
│   ├── kboc16
│   ├── lfw
│   ├── livdet2013
│   ├── mnist
│   ├── mobio
│   ├── msu_mfsd_mod
│   ├── multipie
│   ├── nist_sre12
│   ├── replay
│   ├── scface
│   ├── utfvp
│   ├── verification
│   ├── voxforge
│   ├── wine
│   ├── xm2vts
│   └── youtube
├── extension
│   └── scripts
├── io
│   ├── audio
│   ├── base
│   ├── image
│   ├── matlab
│   └── video
├── ip
│   ├── base
│   ├── color
│   ├── draw
│   ├── facedetect
│   ├── flandmark
│   ├── gabor
│   └── optflow
├── learn
│   ├── activation
│   ├── boosting
│   ├── em
│   ├── libsvm
│   ├── linear
│   └── mlp
├── math
├── measure
└── sp
```

I have fixed this error by patching `conda`:

``` patch
--- /home/travis/miniconda/lib/python3.5/site-packages/conda_build/utils.py
+++ (clipboard)
@@ -10,6 +10,7 @@
 import fnmatch
 from os.path import dirname, getmtime, getsize, isdir, join
 from collections import defaultdict
+import distutils.dir_util

 from conda.utils import md5_file
 from conda.compat import PY3, iteritems
@@ -32,7 +33,7 @@
         dstname = os.path.join(dst, afile)

         if os.path.isdir(srcname):
-            shutil.copytree(srcname, dstname)
+            distutils.dir_util.copy_tree(srcname, dstname)
         else:
             shutil.copy2(srcname, dstname)
```

But I am not sure if this is the best solution. Also, this doesn't work when we cannot patch `conda`.
What do you think? Should I open a pull request for this? Maybe we can add some option to meta.yaml for this?

conda  info :

```
Current conda install:

             platform : linux-64
        conda version : 4.0.5
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/amir/miniconda  (writable)
  default environment : /home/amir/miniconda
     envs directories : /home/amir/miniconda/envs
        package cache : /home/amir/miniconda/pkgs
         channel URLs : https://conda.anaconda.org/bobpkgs/linux-64/
                        https://conda.anaconda.org/bobpkgs/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/conda-forge/linux-64/
                        https://conda.anaconda.org/conda-forge/noarch/
          config file : /home/amir/.condarc
    is foreign system : False
```

**Comment by msarahan** [comment]
That looks like an acceptable use case and a reasonable patch to me. Python's file copying functions are frustrating sometimes.  Please submit a PR.

**Comment by 183amir** [comment]
Fixed by https://github.com/conda/conda-build/pull/1090
