### ISSUE TITLE
`build_targets: conda` fails with `build: noarch_python: true` and `CONDA_FORCE_32BIT`

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#873]
_From @dsludwig on April 1, 2016 0:9_

Related to #255 

This also affects the multilib docker builder.

The output of these builds ends up in `conda-bld/noarch/` or `conda-bld/linux-32/`, when the upload command assumes they will be in `conda-bld/linux-64/` (assuming the build is running on `linux-64`).

```
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /opt/miniconda/conda-bld/noarch/testci-1.0.0-py_6.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes
discarding /home/dev/env/bin from PATH
[Upload Build Targets]
anaconda -q -t $TOKEN upload --force --user vagrant --package testci  --label foo --label bar /opt/miniconda/conda-bld/linux-64/*.tar.bz2 --build-id 6.0
Using Anaconda Cloud api site http://as.example.com:4990/api/
[ERROR]
Traceback (most recent call last):
  File "/opt/miniconda/bin/anaconda", line 6, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "/opt/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 87, in main
    description=__doc__, version=version)
  File "/opt/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
    return args.main(args)
  File "/opt/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 173, in main
    raise errors.BinstarError('file %s does not exist' % (filename))
BinstarError: file /opt/miniconda/conda-bld/linux-64/*.tar.bz2 does not exist
```

The `build_script.sh` run by the build worker (this affects the regular worker too) includes a command like:

```
anaconda upload /opt/miniconda/conda-bld/linux-64/*.tar.bz2
```

The prefix for this (including the platform) is set here: 
- [for regular worker](https://github.com/Anaconda-Server/anaconda-build/blob/develop/binstar_build_client/worker_commands/run.py#L77)
- [for docker worker](https://github.com/Anaconda-Server/anaconda-build/blob/develop/binstar_build_client/worker_commands/docker_run.py#L62)

This is concatenated with `*.tar.bz2` [here](https://github.com/Anaconda-Server/anaconda-build/blob/develop/binstar_build_client/worker/utils/script_generator.py#L90) and included in the build script [here](https://github.com/Anaconda-Server/anaconda-build/blob/develop/binstar_build_client/worker/utils/data/build_script.sh#L310)

_Copied from original issue: Anaconda-Server/anaconda-build#261_

**Comment by kalefranz** [comment]
_From @stephenakearns on April 8, 2016 19:36_

Related to conda build clean dir issue - #262 - @kalefranz to move over to conda_build
