### ISSUE TITLE
HTTP request failed

### ISSUE THREAD

**Issue by pmc2010** [conda/conda-build#909]
terminal results after attempting conda build with local package:

Removing old work directory
Initialized empty Git repository in /home/finances/anaconda3/conda-bld/git_cache/__github.com_pmc2010_py_3_5.git/
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/pmc2010/py_3_5.git/info/refs

fatal: HTTP request failed
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda-build/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/finances/anaconda3/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/home/finances/anaconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 208, in main
    args_func(args, p)
  File "/home/finances/anaconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 493, in args_func
    args.func(args, p)
  File "/home/finances/anaconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 438, in execute
    include_recipe=args.include_recipe)
  File "/home/finances/anaconda3/lib/python3.5/site-packages/conda_build/build.py", line 429, in build
    source.provide(m.path, m.get_section('source'))
  File "/home/finances/anaconda3/lib/python3.5/site-packages/conda_build/source.py", line 291, in provide
    git_source(meta, recipe_dir)
  File "/home/finances/anaconda3/lib/python3.5/site-packages/conda_build/source.py", line 133, in git_source
    check_call(args + [git_url, cache_repo_arg],  cwd=recipe_dir)
  File "/home/finances/anaconda3/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/git', 'clone', '--mirror', 'https://github.com/pmc2010/py_3_5.git', '/home/finances/anaconda3/conda-bld/git_cache/__github.com_pmc2010_py_3_5.git']' returned non-zero exit status 128

---
## Conda Info

 conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

```
         platform : linux-64
    conda version : 4.0.5
```

  conda-build version : 1.20.1
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/finances/anaconda3  (writable)
  default environment : /home/finances/anaconda3
     envs directories : /home/finances/anaconda3/envs
        package cache : /home/finances/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by msarahan** [comment]
Are you still having this error?  It seems like it might have been a transient connection error.  Please let me know if you still have issues.
