### ISSUE TITLE
'noarch_python' and header files

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#934]
@SylvainCorlay commented on [Tue May 10 2016](https://github.com/conda/conda/issues/2456)

I made a conda-forge recipe for pybind11, which is producing platform-dependent packages. 

I think that pybind11 should be a `noarch_python` package. It does not hold any binaries and has a universal pypi wheel.

The issue is that it holds headers (it is a header-only library), plus some pure python. `noarch_python` does not support the case where there are headers.

---

@msarahan commented on [Tue May 10 2016](https://github.com/conda/conda/issues/2456#issuecomment-218141127)

What is the error?

Also, on conda-forge, noarch needs modification of the CI scripts also, so that they won't build the same noarch package with each python version.  This is definitely something that needs work, and it needs work in both conda-build and in conda-forge.

**Comment by SylvainCorlay** [comment]
```
Traceback (most recent call last):
  File "/Users/scorlay/jupyter/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/scorlay/jupyter/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 192, in main
    args_func(args, p)
  File "/Users/scorlay/jupyter/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 486, in args_func
    args.func(args, p)
  File "/Users/scorlay/jupyter/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 409, in execute
    include_recipe=args.include_recipe)
  File "/Users/scorlay/jupyter/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 492, in build
    noarch_python.transform(m, sorted(files2 - files1))
  File "/Users/scorlay/jupyter/anaconda/lib/python2.7/site-packages/conda_build/noarch_python.py", line 87, in transform
    assert 'py_' in m.dist()
AssertionError
```
